### PR TITLE
Change colors to match IQX White Theme

### LINKED ISSUE #5032: Tweak colors to match new IQX colors
From https://github.com/Qiskit/qiskit-terra/pull/3196#issue-324844793, @nonhermitian says:
> Match the upcoming changes to IQX circuit composer styling.

The closed PR #3196 suggests a new set of colors the the MPL circuit drawer. However, the PR got out-of-sync.

Please, use PR #3196 as a reference to set the new colors and run binder (see https://github.com/Qiskit/qiskit-terra/pull/4544 as reference) to create the new reference images.

### PR DESCRIPTION
**Pull request by abhobe**
### Summary
Change gate colors to match IQX Light theme.
Change Dictionaries to match font color.

### Details and comments
fixes #5032

### CODE REVIEW

**Comment by 1ucian0** [comment]
Can you write test(s) following this style https://github.com/Qiskit/qiskit-terra/pull/4544 ?

**Comment by abhobe** [comment]
@1ucian0 https://mybinder.org/v2/gh/abhobe/qiskit-terra/5038?filepath=%2Ftest%2Fipynb%2Fmpl_tester.ipynb
Is this what you want?

**Comment by 1ucian0** [comment]
How this relates with the propousal from https://github.com/Qiskit/qiskit-terra/pull/5063#issuecomment-693445283 ?

**Comment by abhobe** [comment]
5063 solves this but does not fully match the style of IQX. The quantum and classical gates on IQX have white font color and the others have a black font. 5063 makes all fonts white instead.

**Comment by galeinston** [comment]
> 5063 solves this but does not fully match the style of IQX. The quantum and classical gates on IQX have white font color and the others have a black font. 5063 makes all fonts white instead. @1ucian0

I disagree with this. Attached is my screenshot of what I tested. 
Screen Shot 2020-09-17 at 6 38 24 AM

**Comment by Cryoris** [comment]
I think these pull requests intend to do the same, looking at #5032 it seems #5063 started working on this before... maybe you can join the efforts but I think we should close this one.

**Pull request closed without merging**
