### PR TITLE
Add user config file options to control parallel execution

### LINKED ISSUE #5323: 10 second overhead for batch jobs
### Informations

- **Qiskit Aer version**: 0.7.0
- **Python version**: 3.8.5
- **Operating system**: OSX Catalina

### What is the current behavior?

A single call to `execute` with a list of circuits takes around 10s longer than calling it for each circuit sequentially.

### Steps to reproduce the problem

Example code

```
from qiskit import execute, Aer, __qiskit_version__
from qiskit.circuit.random import random_circuit
import time
# make two random circuits
qcs = [random_circuit(2, 2, measure=True) for _ in range(2)]
# run them all at once and see how long it takes
t0 = time.time()
execute(qcs,Aer.get_backend('qasm_simulator'))
print('Time when batched',time.time()-t0)
# run them sequentially and see how long it takes
t0 = time.time()
for qc in qcs:
    execute(qc,Aer.get_backend('qasm_simulator'))
print('Time when run sequentially',time.time()-t0)
```

Similar results are found for different numbers 

### What is the expected behavior?

They should take around the same time. But when running the above I get the following

```
Time when batched 11.500309944152832
Time when run sequentially 0.00656580924987793
```

I do not see the same problem when running on IQX. There I instead get

```
Time when batched 0.6284997463226318
Time when run sequentially 0.2993638515472412
```

Which still isn't perfect, but it's better. So maybe it is an OSX problem?

### Suggested solutions

I should install Linux ;)

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

This commit adds new options to the user config file, 'parallel' and
'num_processes' which when set will override the default behavior of
terra's parallel_map function (which is used internally by transpile()
and assemble()). Along with these new options the default behavior on
macOS is changed to disable parallel execution by default.

### Details and comments

Fixes #5323

### CODE REVIEW

**Comment by nonhermitian** [comment]
So another option would be to do a one time benchmark to see when parallel should be turned on. The threshold would thus be higher on OSX. Doing so would require some parameters to be updated to circuits when gates are added but it not a biggie. I have been using this trick for many years for omp thresholds in ODE sims.

**Comment by nonhermitian** [comment]
Or another thought, just make parallel explicit eg

With parallel_map(ncpus=blah):
  Stuff

**Comment by mtreinish** [comment]
I did think about something like the autodetect/benchmark but I was worried about all the macOS users who complain about `BrokenProcessPool` errors. With macOS 10.15 it seems a pretty common occurrence to just have multiprocessing fail which is why I went for making it an opt-in thing on macOS. As for making it explicit like that, it's definitely an option, and probably not a bad thing to add.  I went with this approach because it still pretty generally provides a speed up for linux on >1 circuit so having it on by default makes sense. But also having simple configuration for users around how multiprocessing is used I think is generally handy. It also unblocks #3457 because a windows user can explicitly enable parallel_map and then have to live with the limitation that it only works inside of `if __name__ == '__main__'`. I think both of the options you've proposed probably would work well and are not mutually exclusive with this. I can look into expanding on those in a followup.

**Comment by nonhermitian** [comment]
Ok yeah the whole brokenpipe stuff is no fun. That would need a whole try statement and a disable flag for the benchmarks

**Review by 1ucian0 — APPROVED** [review]

**Pull request merged**
