### PR TITLE
Returns 2**num_qubits

### PR DESCRIPTION
**Pull request by WiFisunset**
### Summary
Draft: Created a function to return the information 2**(the number of qubits in the circuit).

### Details and comments
Note: I still have to validate if this function works as intended [WIP]

### CODE REVIEW

**Comment by WiFisunset** [comment]
Update: Tested successfully in the dev environment. 

Tox Results (Note: The failed 30, are referencing visualization.py, test_circuit_latex.py,  and visualization tests. None of which are affected by this PR): 
======
Totals
======
Ran: 10668 tests in 202.0826 sec.
 - Passed: 10448
 - Skipped: 190
 - Expected Fail: 0
 - Unexpected Success: 0
 - Failed: 30
Sum of execute time for each test: 1737.1764 sec.

==============
Worker Balance
==============
 - Worker 0 (872 tests) => 0:02:11.713305
 - Worker 1 (887 tests) => 0:02:26.525262
 - Worker 2 (887 tests) => 0:02:28.946997
 - Worker 3 (888 tests) => 0:03:18.699747
 - Worker 4 (890 tests) => 0:02:12.422927
 - Worker 5 (890 tests) => 0:02:29.464113
 - Worker 6 (891 tests) => 0:02:18.401942
 - Worker 7 (892 tests) => 0:02:28.263486
 - Worker 8 (892 tests) => 0:02:17.192733
 - Worker 9 (892 tests) => 0:02:21.824869
 - Worker 10 (894 tests) => 0:02:13.428367
 - Worker 11 (893 tests) => 0:02:25.343920

**Comment by ishworii** [comment]
@WiFisunset how to run tests locally?

**Comment by WiFisunset** [comment]
I was able to get the code to run with -elint being successful, yet it's not successful on the automatic checks on this PR.

Attempting to retry the checks on this PR page.

elint command success

**Comment by ikkoham** [comment]
Thank you for your contribution. Ci fails by black formatter.
1. Use black to format your code: `tox -eblack`
2. Your branch is out-of-date. You may need `Update branch` from the below box.

BTW, why do we need this property method? I feel good enough with `2 ** qc.num_qubits`.(`qc` is an instance of `QuantumCircuit`) If you have any motivation please could you please explain it in the PR comment?

**Comment by WiFisunset** [comment]
> Thank you for your contribution. Ci fails by black formatter.
> 
> 1. Use black to format your code: `tox -eblack`
> 2. Your branch is out-of-date. You may need `Update branch` from the below box.
> 
> BTW, why do we need this property method? I feel good enough with `2 ** qc.num_qubits`.(`qc` is an instance of `QuantumCircuit`) If you have any motivation please could you please explain it in the PR comment?

Np :)! And that makes sense, I'll update the branch (-eblack passes each time I use it to format the code).

And 2**qc.num_qubits does work as well, but calling something like qc.qubit_bit_capacity (or some other shorter name for the function (ie. qc.capacity), makes the flow of getting that information while programming much smoother. 

A lot of times I'm wondering what that value is when making circuits with more than 11 qubits honestly, and since 1,000 qubits is a goal for IBM, it would be more future-proofing and ease-of-use to make calculating that as simple as calling a function. As opposed to doing 2 ** qc.num_qubits each time (one would just call qc.capacity and get an answer). 

Plus that information of the quantum system is useful to know, especially in the case of someone in the future needing to know what that value is without knowing how to calculate that value, they could refer to the api for the function and learn that.

**Comment by Cryoris** [comment]
Hi @WiFisunset, it's great to see you're interested in contributing! However I'm having doubts that we really need this property. Why not just do
```
2 ** circuit.num_qubits 
```
directly? This is quite an easy operation and doesn't add another property to the circuit-class (which already has quite a lot of methods!). Also, doing the exponentiation directly would even be shorter than spelling out `circuit.qubit_bit_capacity`.

If you're looking for issues to contribute you could also check the ones labelled "good first issue" 🙂

**Comment by WiFisunset** [comment]
> This is quite an easy operation and doesn't add another property to the circuit-class (which already has quite a lot of methods!). Also, doing the exponentiation directly would even be shorter than spelling out `circuit.qubit_bit_capacity`.
> 

I agree that it's an easy operation, but from a programming perspective it is useful. It's akin to making a temperature class with Fahrenheit defined in it as a function, but not Celsius or Kelvin because the physicists/programmers making the functions already know how to manually convert it (to Celsius for example) by doing Fahrenheit − 32 × 5/9. 

I do think the function name being as long as it is doesn't lend to it being useful. So I'm going to shorten it to capacity for now. So the call would now be qc.capacity, which is a lot easier to call and faster to use.

**Comment by 1ucian0** [comment]
> Edit: I would also like for the output to have "bits" behind the number so users know what value is being described. I'll add that in another update.

If you do that you will change the type to string. Wouldn't that make it even less useful?

Can you point to some code where the expression `2 ** circuit.num_qubits` is used often enough to justify this addition?

**Comment by WiFisunset** [comment]
> If you do that you will change the type to string. Wouldn't that make it even less useful?
> 
> Can you point to some code where the expression `2 ** circuit.num_qubits` is used often enough to justify this addition?

I appreciate all the feedback I've been getting about the code. And I do agree that it would make it less useful, but it never hurts to throw out a suggestion for improvement to code in-progress. I spent the night thinking it over, and I agree that wouldn't be a good addition to the code.

On the topic of pointing to code/use-cases where it's used often enough to justify this addition. 

I can say that it's been taught enough as being important quantum information that we all know it as being quantum information that's relevant about the circuit/system, which is why I believe a quantum information science kit should have that quantum information encapsulated in it; in conjunction with the other reasonings I've listed in above comments. 

In addition to that, I do sporadically teach quantum computing using qiskit via streaming on a private channel, and it's a consistent question that comes up, especially when attempting to explain the benefits of quantum computing and why qubits offer a significant computational advantage compared to classical computing bits (as a matter of fact, that capacity is why systems with more qubits are being designed, because more qubits offer an exponential increase to that capacity).

On a more personal note. Since making the function (and now shortening it), I've been initializing circuits of various sizes (1 to 1000), and it's been very insightful to see for circuits with 23, 73, and other numbers of qubits. I am weary of explaining that though, as I feel my personal use case(s), might be pulled apart to use as a counterpoint. Trying to explain code where it's used often enough (using plot_state_qsphere as an example), would feel like attempting to explain how visualizing that would be useful, without anyone having used it in code before (I hadn't heard of a qsphere being used before I was introduced to it, but it definitely is useful as a visual representation of quantum information, and in teaching/explaining it as well). 

There's not much else I could explain in favor of this function being implemented, and I would like to know if this function might be better placed in say, visualization, for example (or something of the like). 

But if there's still opposition to this quantum information being encapsulated in the kit, then please let me know, and I'll close this PR out. Again, I do deeply appreciate the feedback, even thinking about the potential use cases has spurred a few other function ideas I could try later on :).

Note: I would like more feedback on the actual structure of my code (there may be a simpler/better way to implement the function, such as just having it return the value sans assigning it to a variable). So far the feedback has mainly/all been about the usefulness (or perceived lack thereof) of the code, and not the actual structure of the code itself. I would like feedback on both :)!

**Comment by WiFisunset** [comment]
Note: I was going through initializer.py, and came across this code which has 2 ** self.num_qubits within it. I was working one another function and happened to come across it :).

    def broadcast_arguments(self, qargs, cargs):
        flat_qargs = [qarg for sublist in qargs for qarg in sublist]

        if self.num_qubits != len(flat_qargs):
            raise QiskitError(
                "Initialize parameter vector has %d elements, therefore expects %s "
                "qubits. However, %s were provided."
                % (2 ** self.num_qubits, self.num_qubits, len(flat_qargs))
            )
        yield flat_qargs, []

    def validate_parameter(self, parameter):
        """Initialize instruction parameter can be str, int, float, and complex."""

**Comment by mtreinish** [comment]
Reading through the discussion on this PR I think the conclusion here among the @Qiskit/terra-core team that reviewed this back in June 2021 was that this isn't necessary as it's straightforward to implement without adding a helper method. So I'm going to close this PR. Thanks for proposing a change and I hope that you continue to propose suggestions and open issues and PRs where you continue to see gaps. Also, please feel free to reopen this PR if I'm missing something or you think there is more to discuss on this.

**Pull request closed without merging**
