### PR TITLE
Documenation changes

### PR DESCRIPTION
**Pull request by jaygambetta**
Working towards #1241 (need multiple registers)

I changed the documentation up a bit

I made an overview
I changed the install
I removed the dev_overview and made it a soft link to the contributing. 
I included the tutorials from qiskit-tutorial/qiskit with 

           jupyter nbconvert --to rst <input notebook>

and then fixing by hand the note blocks. I can not work out how to make a note in markdown which converts to rst with nbconvert. 
 
I fixed up all the headings. The convention i used is
            ######## parts ie terra, aqua,,
            *********** chapters
            ======= title 
             ---------  sections
             ^^^^^^^^^^ subsection
             """""""""" paragraph

I would like to have the .. parsed-literal:: (what is converted in the output of the notebooks) not be converted with sphinx to look like python code, but I think this needs to be done in the template. @diego-plan9 I don't know how to do this can you look into it. 

I would also like to change the icon to be the terra icon, not the qiskit one.  @diego-plan9 can you do this. That way each part has the element as its icon. 

Also, I think the order for updating documentation is 
1. Main doc section for tutorials (update them in juypter then convert to rst)
2. Soft links for files that are needed in GitHub (contributions, changelog) 
3. filler files updated in the doc

In a future update, it would be cool to have the interactive plots.

### CODE REVIEW

**Comment by jaygambetta** [comment]
Also, i think i might have stuffed up the other languages. I don't know what we want to do about this. We need to get someone assigned for the different ones.

**Comment by jaygambetta** [comment]
@Borjagodoy could you see above. Also Is it possible in the template to show the subsection when that section is viewed. 

Also the top could we have part says Qiskit Terra documentation and goes to the table of contents.

**Comment by diego-plan9** [comment]
> I would like to have the .. parsed-literal:: (what is converted in the output of the notebooks) not be converted with sphinx to look like python code, but I think this needs to be done in the template. @diego-plan9 I don't know how to do this can you look into it.

Hmm do you mean disabling the python color-highlighting for those blocks? If that is the case, something along the lines of  using `.. code-block:: text` instead might work:

```
.. code-block:: text

    [<IBMQBackend('ibmqx4') from IBMQ()>,
     <IBMQBackend('ibmqx5') from IBMQ()>,
     <IBMQBackend('ibmqx2') from IBMQ()>,
     <IBMQBackend('ibmq_16_melbourne') from IBMQ()>,
     <IBMQBackend('ibmq_qasm_simulator') from IBMQ()>]
```

code-text

**Comment by jaygambetta** [comment]
I don't think it was colored when we used .. parsed-literal::. As we discussed on slack I think it would be better if it has no shading and looks like computer output (mono font or something).

**Comment by 1ucian0** [comment]
Considering adding the link to the Slack invitation when Slack is mentioned (I think it is just in the README.md) and close #1237. Thanks!

**Comment by ajavadia** [comment]
Thanks @jaygambetta @diego-plan9 @Borjagodoy

**Pull request merged**
