### PR TITLE
Revert "remove randomness from two_qubit_decompose"

### PR DESCRIPTION
**Pull request by ajavadia**
Reverts Qiskit/qiskit-terra#3585

Recent PRs are failing due to this merge.

### CODE REVIEW

**Comment by 1ucian0** [comment]
The solution to that is https://github.com/Qiskit/qiskit-terra/pull/3586

**Comment by ajavadia** [comment]
Changing tests is not a fix. The algorithm is failing on some instances of input. Those instances should be captured and made into new test cases, not simply dismissed.

Before #3585 we were not getting these failures, so makes me think the failures come from the change to the algorithm itself.

**Comment by 1ucian0** [comment]
> Changing tests is not a fix. The algorithm is failing on some instances of input. Those instances should be captured and made into new test cases, not simply dismissed.

You are right, I agree. #3586 will give us those instances.

> Before #3585 we were not getting these failures,...

Just by chance... We need to move to a more deterministic testing. Now it is possible to see which are the failing cases, but the solution is not reverting #3585 either.

**Comment by ajavadia** [comment]
> Just by chance... We need to move to a more deterministic testing.

No we don't, and this is the reason. Deterministic tests will mask these failures, which is why I insisted on implementing randomized tests in `test/randomized`.
The randomized algorithm for two_qubit_decompose has been on master for 8 months, and I don't recall a single instance of failure like the ones we are seeing now. So either we have been extremely lucky, or the algorithmic change implemented in #3585 is not correct. To reiterate what @levbishop [said in #3585](https://github.com/Qiskit/qiskit-terra/pull/3585#issuecomment-567276758):

>  The tests are fairly complete and if it passes the tests it's probably ok

Now we are seeing it does not pass the tests. Therefore I'd like to revert this until we have a better understanding of how to make the algorithm more robust. I don't want to just keep ploughing through with making everything deterministic and pretend we have solved the underlying problem.

**Comment by 1ucian0** [comment]
> No we don't, and this is the reason. Deterministic tests will mask these failures, which is why I insisted on implementing randomized tests in test/randomized.

Yes. And I move them to ` test/randomized`. The merge blocking tests should be deterministic.

I will work in a better `two_qubit_decompose` while waiting for @chriseclectic approval of this one.

**Comment by 1ucian0** [comment]
I think https://github.com/Qiskit/qiskit-terra/pull/3653 it's a better alternative to this PR.

**Comment by 1ucian0** [comment]
> The randomized algorithm for two_qubit_decompose has been on master for 8 months, and I don't recall a single instance of failure like the ones we are seeing now. 

There were some instances in the last 30 days (it's true that none of the is in master):
Screen Shot 2019-12-24 at 10 36 00 PM

However, the output and info of most of those failed tested is lost, making it hard to understand why they failed. Having `test/randomized` is key to capture these instances. I'm all with you about that.

**Comment by kdk** [comment]
I think its safe to revert for now, and then we can move forward with #3653 .

**Comment by ajavadia** [comment]
@1ucian0 that's cool I didn't know you can get a history of failures for a testcase.

**Pull request merged**
