### PR TITLE
Fix quantum part of Shor's algorithm

### PR DESCRIPTION
**Pull request by bartek-bartlomiej**
### Summary

Fixes [#6262](https://github.com/Qiskit/qiskit-terra/issues/6262)

Quantum part of Shor's algorithm stopped working properly in Aqua `0.7.0` (due to mistake in order of applying bits in QFT). Unfortunately, it was missed and during successive refactor new bugs were introduced.

In this PR, quantum part of algorithm was rewritten according to the Beauregard's article (and now should work).
New tests checking output of quantum part was added as well.

### Details

* simplify `_get_angles` method
* rewrite implementation of modular adder and multiplier
* use `QuantumRegister` while generating gates instead of `circuit.qubit` slices
* introduce `_power_mod_N` for grouping multiplication gates in one gate
* replace `modinv` method with built-in `pow` (for Python >=3.8)
* replace storing common gates in class instance with passing them as arguments
* introduce `_validate_input` method
* add tests for quantum part output values

### CODE REVIEW

**Comment by Cryoris** [comment]
Hi @bartek-bartlomiej, thanks for the fix! I have a few comments about the tests.
* could you add a test that tries to cover the use case from #6262 (or is there already one?)
* I don't think all these tests are really necessary (bear in mind that we have hundreds of other that are run on every PR🙂). Even if they are marked as slow, I think we should only have tests that explicitly check different settings. E.g. could we also run smaller numbers? Does using larger numbers test something different than small numbers? Or, does it suffice to run one test case instead of two or three for the same test?

**Comment by bartek-bartlomiej** [comment]
Sorry for late response! @Cryoris, thank you for questions :smiley:

Ad. 1.
There is one called `test_shor_quantum_result`, with a case `N=15, a=4, r=2` which is analogous to case from issue. (For `a = 4` and `a = 11` the order will be the same, that is `r = 2`).

Ad. 2.
I'm aware of huge amount of tests. I've already dropped tests for bigger numbers, e.g. `N=35` (on my machine, single lasted 30 minutes :astonished: On the other hand, test with `N=21` runs about 2 minutes). What's more, as far as I can see, tests marked as slow are skipped during CI.

The main reason of using different numbers is to test that implementation is *general*. It's difficult to verify with only one test case, e.g. only for `N=15` :wink: Unfortunately, the smallest number you can factor is `15 = 3*5`. Next number is `21 = 3*7` which requires bigger amount of qubits and longer duration of simulation.

`test_shor_exponentiation_result` could be most debatable, as long it not check 'public' functionality of Shor's algorithm. On the other hand, it can help spot bug explicitly in exponentiation gate (`_power_mod_N` method) in the future.

**Comment by woodsp-ibm** [comment]
@Cryoris Did you have any more feedback - or if the conflicts were fixed (presumably they came about because of the new formatting we are doing with black) does this seem good?

**Comment by Cryoris** [comment]
If the tests run reasonably fast I think I'm good 👍🏻

**Comment by woodsp-ibm** [comment]
@bartek-bartlomiej Do you think you can finish this PR off - it would great to have Shor fixed up.

**Comment by bartek-bartlomiej** [comment]
Hello @woodsp-ibm, sorry for delay! I've resolved conflicts and applied new formatting, so I think PR is now ready :slightly_smiling_face:

**Review by woodsp-ibm — APPROVED** [review]

**Comment by woodsp-ibm** [comment]
@bartek-bartlomiej Thanks for sorting out the conflicts so this is ready and of course for fixing up the problem in Shor algorithm!

**Pull request merged**
