### PR TITLE
Fixed issue#6397 by adjusting the height of the title in plot_bloch_multivector

### LINKED ISSUE #6397: Title overlaps in plot_bloch_multivector
### Information

- **Qiskit Terra version**: 0.17.3
- **Python version**: 3.9
- **Operating system**: Ubuntu

### What is the current behavior?
Title overlaps the Bloch sphere in single-qubit system when plotted using `plot_bloch_multivector`. But no issues with multi-qubit systems.
Desktop - 3

### Steps to reproduce the problem
```python
qc = QuantumCircuit(2,2)
qc.x(0)
V = execute(qc, Aer.get_backend('statevector_simulator')).result().get_statevector()
plot_bloch_multivector(V, title="Single Qubit System")
```

### PR DESCRIPTION
**Pull request by singhmeet11**
### Summary
Fixes #6397 

### Details and comments
**Issue -** The title of the plot was overlapping
**Problem -** The y coordinate of the `suptitle` in `pyplot` is taken to be 0.98 to be default, which led to the overlap
**Fix -** Appended `y=1.01` which created enough gap so that there would be no overlap. \
**Original** 
original
**Fixed**
fixed

### CODE REVIEW

**Comment by singhmeet11** [comment]
Hi, can someone please tell me how do I add the test case for this. Like if I had changed the outlook of a circuit, I would have made additions to `test/ipynb/mpl/test_circuit_matplotlib_drawer.py`, but I can not find the place to create the test for graph outputs.

**Comment by javabster** [comment]
Hi @singhmeet11 this is looking good! As for tests I think it would be best to create a new file in the mpl folder for testing graphs, so the steps would be something like this:

- Create new file e.g. qiskit-terra/test/ipynb/mpl/test_graph_matplotlib_drawer.py
- Add new tests to this file (use test_circuit_matplotlib_drawer.py as a guide)
- Update qiskit-terra/test/ipynb/mpl_tester.ipynb to also run tests from the test_graph_matplotlib_drawer.py
- Follow the instructions in [here](https://github.com/javabster/qiskit-terra/blob/main/CONTRIBUTING.md#snapshot-testing-for-visualizations) about how to run the snapshot tests and update the reference images

Thanks for your contribution so far 😄

**Comment by enavarro51** [comment]
@javabster I'm wondering if creating a new testing infrastructure for visualizations should be handled in a separate issue. There might be some design issues that need to be discussed. For example, should there be separate mpl_tester.ipynb versions for circuit and other visualizations?

**Comment by singhmeet11** [comment]
@enavarro51 that seems like a good idea. But as of now I have made it very similar to `test_circuit_matplotlib_drawer.py` with a few modifications here and there. One change that I have had to do was that I introduced a parameter for file name in the very definition of the `graph_drawer` the reason for this was that the `state_drawer` does not have a parameter name file name.

Although we can adjust testing for circuit and graphs in one `mpl_tester` , making two might help in  making a more structured repo.
As for the changes till now , you can take a look here -  https://github.com/Qiskit/qiskit-terra/compare/main...singhmeet11:issue6397 , I am not succesfull yet but I am looking  into what is wrong 
Let me know what you guys think..

**Comment by enavarro51** [comment]
If you want to proceed with the tester here, that's fine. I'd suggest you look at #6450 as a model. @TharrmashasthaPV did what you're trying to do for the latex drawer. You can ignore the code for installing dependencies since that's a purely latex issue.

Here are some ideas.
- Create new test/ipynb/graphs and test/ipynb/graphs/references directories and copy all the necessary .py files over as your starting point, renaming as necessary.
- You need to have a reference .png image in the references dir for each test you are running. Initially you will just have one test and one image.

Hope that helps.

**Comment by javabster** [comment]
Hi folks, thanks for the suggestion @enavarro51 😄 

There is a question here around how we want to organise the visualisation tests in future as the number of snapshot tests increases. Do we want to organise according to visualisation style (i.e. folders for mpl, latex and text) or according to what is being drawn (i.e. folders for circuit, graphs etc.)? This could be a nice discussion to bring up in the #qiskit-dev slack channel😄 

For the time being in this specific PR as the graphs being tested are mpl visualisations I would still keep them in the mpl folder. And it keeps it consistent with the structure in #6450. We can reorganise at a later date if a different folder structure is preferred

**Comment by singhmeet11** [comment]
@javabster and @enavarro51 I have made a new pull request for the test that I have created. I think this works properly(I checked by running Binder). Currently I have only done this for `plot_bloch_multivector` let me know what you guys think then I will make appends for other graphs in the next few days. 

Also I think this pull request can be merged.

**Comment by javabster** [comment]
> @javabster and @enavarro51 I have made a new pull request for the test that I have created. I think this works properly(I checked by running Binder). Currently I have only done this for `plot_bloch_multivector` let me know what you guys think then I will make appends for other graphs in the next few days.
> 
> Also I think this pull request can be merged.

can you share the link to your other pull request please?

**Comment by javabster** [comment]
Closing this PR as it seems the fix is already in main 😄

**Pull request closed without merging**
