### PR TITLE
Make to_gate work if gates are wrapped in Instructions 

### LINKED ISSUE #4011: Cannot call to_gate() if circuit contains (unitary) Instruction instance
### Information

- **Qiskit Terra version**: 0.12.0
- **Python version**: 3.7.5
- **Operating system**: macOS catalina

### What is the current behavior?

If a circuit contains an `Instruction` instance it cannot be converted to a `Gate` even if all instructions are unitary. This is important to also enable e.g. `control()` or `power()` on a circuit, which are currently only supported for `Gate` types.

### Steps to reproduce the problem

```python
>>> circuit = QuantumCircuit(1)
>>> circuit.x(0)
>>> other.append(circuit.to_instruction(), [0])
>>> other.to_gate()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jul/Work/Qiskit/qiskit-terra/qiskit/circuit/quantumcircuit.py", line 601, in to_gate
    return circuit_to_gate(self, parameter_map)
  File "/Users/jul/Work/Qiskit/qiskit-terra/qiskit/converters/circuit_to_gate.py", line 51, in circuit_to_gate
    raise QiskitError('One or more instructions in this instruction '
qiskit.exceptions.QiskitError: 'One or more instructions in this instruction cannot be converted to a gate'
```

### What is the expected behavior?

A circuit should be castable to a gate if all operations are unitary, independent of whether they are wrapped in a `Instruction`.

### Suggested solutions

When a circuit is converted to a gate the instructions should be unrolled to check whether they are unitary.

### PR DESCRIPTION
**Pull request by Cryoris**
### Summary

Fixes #4011.

### Details and comments

If a circuit contains unitary operations only it should be convertable to a `Gate`. 
However, if a unitary circuit gets wrapped in an `Instruction` that's not possible:
```python
>>> circuit = QuantumCircuit(1)
>>> circuit.x(0)
>>> other.append(circuit.to_instruction(), [0])
>>> other.to_gate()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jul/Work/Qiskit/qiskit-terra/qiskit/circuit/quantumcircuit.py", line 601, in to_gate
    return circuit_to_gate(self, parameter_map)
  File "/Users/jul/Work/Qiskit/qiskit-terra/qiskit/converters/circuit_to_gate.py", line 51, in circuit_to_gate
    raise QiskitError('One or more instructions in this instruction '
qiskit.exceptions.QiskitError: 'One or more instructions in this instruction cannot be converted to a gate'
```
In this PR, `convert_to_gate` tries to unroll the circuit instructions until it finds a `Gate` object and only fails if the an instruction is not decomposable to a gate.

### CODE REVIEW

**Comment by 1ucian0** [comment]
I'm not sure if I like this approach. If I understand this correctly the performance of `to_gate()` gets hit because every element needs to be type checked.

Maybe I just dont understand the use case. Gates can be instructions but not in the other direction. Why somebody would `.to_instruction()` a unitary circuit instead of `.to_gate` it?

**Comment by nonhermitian** [comment]
Probably because you can say Operator.to_instruction() in the quantum info module and Operator can be (and usually is) a unitary. There is no to_gate method.

**Comment by 1ucian0** [comment]
Good point. Adding `Operator.to_gate` method seems a reasonable solution to me.

**Comment by Cryoris** [comment]
> I'm not sure if I like this approach. If I understand this correctly the performance of to_gate() gets hit because every element needs to be type checked.

Circuits for which `to_gate` worked don't have a performance hit. Before, all the "first-level" operations (i.e. content of `circuit.data` w/o decomposing or unrolling anything) are checked to be gate types, and if yes we returned a gate. This still works the same.
But now instead of raising if a "first-level" operation is not a gate, it's trying to decompose. 

So the performance of what worked before is the same, but where an error was raised before we need to do more type checks.

> Maybe I just dont understand the use case. Gates can be instructions but not in the other direction. Why somebody would .to_instruction() a unitary circuit instead of .to_gate it?

What Paul said, plus some circuit operations such as `Initialize` or `Isometry` are `Instruction`s although they contain only unitary operations. It is not possible to do a controlled initialization now.

It would also be possible to make sure all that is unitary actually returns a `Gate` and all objects offer `to_gate`. However if a user uses `to_instruction` somewhere in the workflow it would break so this seemed like the more accomodating solution.

**Comment by Cryoris** [comment]
This is not quite ready, there's something going on with the mapping of the qubits and `find_bit_position` which doesn't work if the instructions are unrolled. As far as I understand it, that method maps the qubits the instruction acts on to the correct qubits of the circuit. It assumes that the qubit the instruction acts on are of the same quantum register as the circuit. 
If we're unpacking the instructions, that does not hold anymore. 
I.e. here's a tiny test that fails (I'll add it to the tests later):
```python
from qiskit.circuit import QuantumCircuit, QuantumRegister, Instruction
from qiskit.circuit.library import HGate

inst = Instruction('inst', 1, 0, [])
q = QuantumRegister(1)
inst.definition = [
    (HGate(), [q[0]], [])
]

circuit = QuantumCircuit(1)
circuit.append(inst, [0])
gate = circuit.to_gate()
```
yields:
```
...
  File "/Users/jul/Work/Qiskit/qiskit-terra/qiskit/converters/circuit_to_gate.py", line 75, in find_bit_position
    reg_index = ordered_regs.index(bit.register)
ValueError: QuantumRegister(1, 'my_reg') is not in list
```

**Comment by 1ucian0** [comment]
After some discussion, let's move forward and add an `Instruction.to_gate` method. Thanks!

**Comment by Cryoris** [comment]
If we had an `Instruction.to_gate` then we also get `QuantumCircuit.to_gate` for free, right? 🙂 
```python
def to_gate(self):
    return self.to_instruction().to_gate()
```

**Comment by Cryoris** [comment]
Closing this as it is stale. If we revive this we can just do the changes anew to avoid conflicts.

**Pull request closed without merging**
