### PR TITLE
[WIP] Qasm2 functional interface to qasm translation

### PR DESCRIPTION
**Pull request by jwoehr**
### Summary
Add a `load()` / `unload()` interface to qasm translation as a first step to untangling qasm from `QuantumCircuit`.

### Details and comments
Suggested by @1ucian0 

Reviewers will likely suggest more work, but this is pr is pretty self-contained and complete and supplements the existing code without yet changing `QuantumCircuit` itself.

### CODE REVIEW

**Comment by 1ucian0** [comment]
Thanks for bringing this up! This is a good first step towards #1742 . [Once up a time](https://app.slack.com/client/T7RSPHKK2/CG8JSE0UB/1550407847.039800), @jaygambetta suggested this API:
```python
from qiskit.converter import load, export
circuit = load(import_object, type='openqasm')
export_object = export(circuit, type='openqasm')
```

I think something like closer to what you have here is better indeed:
```python
from qiskit import qasm
circuit = qasm.load(import_object, include_path=<opt,str>, format=['filename', 'string',...])
export_object = qasm.export(circuit, filename=<opt,str>)
```

I'm not fully sure about the export/unload API. ideas @ajavadia, @kdk ?

I will try to find some time to also push some code in the branch so we remove the `2` in `qasm2`.

**Comment by jwoehr** [comment]
> circuit = qasm.load(import_object, include_path=<opt,str>, format=['filename', 'string',...])

- I guess `import_object` is `str` or `List{str]`
- What is `format=['filename', 'string',...]`

> export_object = qasm.export(circuit, filename=<opt,str>)

I can proceed with this change.

> I'm not fully sure about the export/unload API. ideas @ajavadia, @kdk ?

Let me know.

> I will try to find some time to also push some code in the branch so we remove the `2` in `qasm2`.

Thanks, `qasm2` was just a way for me to make sure I didn't pollute the extant code base.

**Comment by jwoehr** [comment]
What's the philosophy? Should I trap file errors and make them `QiskitError` or just let it blow up?

**Comment by jwoehr** [comment]
The latest change provides for exporting qasm to a file object as well as a file name.

**Comment by jwoehr** [comment]
Build seems to have gone completely nuts. I haven't changed my code and now the builds are failing with this error:
```
Traceback (most recent call last):
testtools.testresult.real._StringException: Traceback (most recent call last):
  File "D:\a\1\s\test\python\test_qasm2.py", line 37, in setUp
    self._circ_draw = y_f.read()
  File "c:\hostedtoolcache\windows\python\3.7.6\x64\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 22: character maps to <undefined>
```
There is no 0x90 in the position described. What is this, please?

**Comment by 1ucian0** [comment]
It seems like an encoding error in the input file. Did you change the input file?

**Comment by jwoehr** [comment]
> It seems like an encoding error in the input file. Did you change the input file?

I haven't changed anything. The tests are being triggered by me merging changes periodically from Qiskit/qiskit-terra master branch. My code hasn't changed. I have even examined the file in a hex editor. The supposed error in `test_qasm2.py`, line 37, position 22, is the letter `a` in `self._circ_draw`, hex 0x61.

**Comment by jwoehr** [comment]
I think the test failure is only happening on Windows testing.

**Comment by jwoehr** [comment]
This is some kind of problem with the Windows build conveyor.

```
$ od -hc test_qasm2.py  | grep 90
# returns nothing

# in Midnight Commander hex dump shows this.
5F 63 69 72 │ 63 5F 64 72 │ 61 77 20 3D │ 20 79 5F 66 │ 2E 72 65 61 │ 64 28 29 0A │ 20 20 20 20 │ 20 20 20 20  _circ_draw = y_f.read().
```
The error is `UnicodeDecodeError: 'charmap' codec can't decode byte 0x90` ...
**There is no 0x90 in the entire file**. There's something wrong in the Windows build.

**Comment by mtreinish** [comment]
The error you're hitting isn't in the qasm file it's in the text drawer. the 0x90 character is in the text visualization, which is not part of the windows character encoding. See: https://github.com/Qiskit/qiskit-terra/issues/2616

**Comment by jwoehr** [comment]
> The error you're hitting isn't in the qasm file it's in the text drawer. the 0x90 character is in the text visualization, which is not part of the windows character encoding. See: #2616

Thanks for clarifying, @mtreinish ... that was driving me nuts! w/r/t #2616 ... well, I guess we have more information now ;)

**Comment by jwoehr** [comment]
> The error you're hitting isn't in the qasm file it's in the text drawer. the 0x90 character is in the text visualization, which is not part of the windows character encoding. See: #2616
So should I just disable some of my test cases so this goes through?

**Comment by 1ucian0** [comment]
This is still in my ToDo. It needs some refactors but it's not high priority for now.

**Comment by jwoehr** [comment]
> This is still in my ToDo. It needs some refactors but it's not high priority for now.

Not something you can describe in few words simply enough that I can do the work?

**Comment by 1ucian0** [comment]
Mostly merging `qasm` and `qasm2` modules. I also need to have a deeper look. Hopefully I will find some time soon-ish.

**Comment by 1ucian0** [comment]
This PR is moving towards https://github.com/1ucian0/qiskit-openqasm2

**Pull request closed without merging**
