### PR TITLE
[WIP] Remove underscore prefix from files

### PR DESCRIPTION
**Pull request by charlesastaylor**
### Summary
Proposed in #1206. Removing underscore prefix from modules that aren't private.

### Details and comments
I have made a start but thought it would be sensible to make  WIP PR before changing too much. I've been working on the principle (mentioned in #1206) that if a module has a member that is used in a different package it shouldn't have the underscore prefix. I think my changes for the modules in the top level package are what is intended but I'm a less clear about what to do for the sub packages.

### CODE REVIEW

**Comment by 1ucian0** [comment]
Let's do this post 0.7

**Comment by jaygambetta** [comment]
@charlesastaylor  i am going to close this as with all the rework there are many conflicts. I still would love you to do it but rather than doing them all at once could you do them folder by folder. If you want to do it that way we could even accept some before 0.7. 

A good folder to start with is quantum_info, qasm, etc

**Comment by charlesastaylor** [comment]
I'll take a look when I get some time. Should I just open a PR for each folder or do I have to create a corresponding issue first as well?

**Comment by jaygambetta** [comment]
no just make a pr and then say addressing issue blah.

**Pull request closed without merging**
