### PR TITLE
Import the multi-controlled Gates from Terra, not Aqua

### PR DESCRIPTION
**Pull request by Cryoris**
### Summary

Several multi-controlled gates (see below) have been copied to Terra, but are not included in any `__init__` and therefore only imported through Aqua, where they are included in an `__init__` file.
If they already exist in Terra we should also include them from there, so we can finally remove these duplicate gate implementations from Aqua.

Two files remain in Aqua, namely the multi-control multi-target Toffoli and some boolean logic gates. Is there a reason why only part of the gates have been moved here?

### Details and comments

This affects:
```
multi_controlled_u1_gate -> mcu1
multi_controlled_toffoli_gate -> mct
multi_controlled_rotation_gates -> mcrx, mcry, mcrz
```

These gates exist in Aqua: https://github.com/Qiskit/qiskit-aqua/tree/master/qiskit/aqua/circuits/gates
The three files named above also co-exist in Terra.

### CODE REVIEW

**Comment by ewinston** [comment]
Hi Julien, can these gates be made to behave like other gates in extensions/standard? I would expect them to inherit from ControlledGate.

**Comment by Cryoris** [comment]
Yes, these are ongoing projects, as  e.g. for the multi-controlled U1 (#3883) or the relative-phase Toffolis (#3761). But this PR is to not have dead code in Terra that's not imported. Also, if we import them here we can remove them from Aqua at once.

**Comment by ewinston** [comment]
Ok, this seems fine then. Are you also submitting a similar pr for the multi controlled rotation gates?

**Comment by Cryoris** [comment]
Yes, the plan is to add these and the multi-controlled Toffolis as
ControlledGates as well.

**Pull request merged**
