### PR TITLE
deprecate Bit-tuple equality check

### PR DESCRIPTION
**Pull request by 1ucian0**
While cleaning up things from the `Bit` object introduction change, I noticed that `__eq__` with tuples did not have a `DeprecationWarning`. So, this PR adds it.

### CODE REVIEW

**Comment by 1ucian0** [comment]
> There are still a handful of places where we're internally still returning and comparing tuples (making the DeprecationWarning fatal fails a handful of tests) that should probably be fixed here as well.

I cleaned them all up! Thanks for your review!

**Comment by 1ucian0** [comment]
The backport is in #3054

**Comment by mtreinish** [comment]
This will need a release note because it's a deprecation that didn't exist before.

**Comment by 1ucian0** [comment]
> This will need a release note because it's a deprecation that didn't exist before.

Release note added!

**Comment by 1ucian0** [comment]
removing `stable backport potential` because of https://github.com/Qiskit/qiskit-terra/pull/3054#issuecomment-526601677

**Comment by 1ucian0** [comment]
> Looks good, also needs a changelog entry.

done in 856cda1199b973530dfebcb9e5d6c7773f3ad196

**Pull request merged**
