### PR TITLE
Tag benchmark failures in travis

### PR DESCRIPTION
**Pull request by kdk**
A few changes to the way we run benchmarks in travis:
1. Tag issues created for failing benchmark jobs with a label 'benchmarks failing' to prevent raising duplicate issues (#2772 and #2771 of #2770)
~~2. Include circuit_construction benchmarks in the set of benchmarks to be run in CI~~
3. Try to obtain the following behavior:
  - On PR branches, compare benchmarks between PR branch and current master
  - On merges to master, compare between new master and old master

For 3, we currently run PR branches vs master, but compare merges to master against themselves. `asv continuous` takes a `base` and an optional `branch`.
- For PR branches, `$TRAVIS_PULL_REQUEST_BRANCH` should be the branch name, so the command should look like `asv continuous master $PR_NAME` (compare $PR_NAME to master).
- For merge branches, `$TRAVIS_PULL_REQUEST_BRANCH` should be empty, `asv continuous master` should default to running `master` against `master~1`.

Ref: 
https://docs.travis-ci.com/user/environment-variables/
https://asv.readthedocs.io/en/stable/commands.html#asv-continuous

### CODE REVIEW

**Comment by mtreinish** [comment]
https://travis-ci.com/Qiskit/qiskit-terra/jobs/215567096#L945

It looks like `$TRAVIS_PULL_REQUEST_BRANCH` won't work because it's the branch name on your fork not on the Qiskit/qiskit-terra repo. We probably should just add logic to the job definition to use $TRAVIS_BRANCH_HEAD if it's a pull request else nothing.

**Comment by kdk** [comment]
`circuit_construction` benchmarks push the run time to just beyond the 45m limit, so removed for now. Can re-add after #2529 .

**Comment by yaelbh** [comment]
Is it possible (or already done) to run only tests and benchmarks that depend on code that was modified?

**Comment by kdk** [comment]
Answering the question "which tests/benchmarks will be impacted by this code change?" in an automated way isn't always trivial, unfortunately.

**Pull request merged**
