### PR TITLE
Better handling of Bloch sphere output

### PR DESCRIPTION
**Pull request by nonhermitian**
### Summary
This fixes an issue where the Bloch sphere could only be output once if called directly.  In addition, it cleans up the internals for dealing with user passed `fig` and `axes`.  Note that none of this is actually directly used in qiskit, but some users are trying.

### Details and comments
```python
fig = plt.figure(figsize=(15,7))
ax = fig.add_subplot(1, 2, 1, projection='3d')
B1 = Bloch(fig=fig, axes=ax)
B1.add_vectors([0,0,1])
B1.render('Qubit #1')
ax2 = fig.add_subplot(1, 2, 2, projection='3d')
B2 = Bloch(fig=fig, axes=ax2)
B2.add_vectors([0,1,0])
B2.render()
```
bloch

### CODE REVIEW

**Comment by mtreinish** [comment]
@nonhermitian did you mean to include those 2 jupyter notebooks in the PR too, or just the changes to bloch.py?

**Comment by nonhermitian** [comment]
Opps

**Comment by nonhermitian** [comment]
Good find.

**Comment by jaygambetta** [comment]
can we call it _bloch

**Pull request merged**
