### PR TITLE
Added reverse_bits parameter to plot_bloch_multivector() (#5959)

### LINKED ISSUE #5959: plot_bloch_multivector should have most significant qubit on the left
### What is the expected enhancement?
Since the standard ordering of qubits for a multiqubit state is most significant (left) to least significant (right), the multivector Bloch sphere output should respect the same order.  

For example, in the sample shown by the API documentation, qubit 1 should be on the left and qubit 0 on the right.
https://qiskit.org/documentation/stubs/qiskit.visualization.plot_bloch_multivector.html

### PR DESCRIPTION
**Pull request by jsistos**
### Summary
Fixes #5959 

### Details and comments
Currently, the function plot_bloch_multivector orders the qubits in increasing order.
```python
from qiskit import QuantumCircuit
from qiskit.quantum_info import Statevector
from qiskit.visualization import plot_bloch_multivector
%matplotlib inline

qc = QuantumCircuit(3)
qc.h(0)
qc.x(2)

state = Statevector.from_instruction(qc)
plot_bloch_multivector(state, title="New Bloch Multivector")
```
image

This is the opposite of Qiskit's standard qubit ordering. Adding a parameter `reverse_bits` to the function allows deciding between the two options (Default value is set to `False`).
```python
qc = QuantumCircuit(3)
qc.h(0)
qc.x(2)

state = Statevector.from_instruction(qc)
plot_bloch_multivector(state, title="New Bloch Multivector", reverse_bits=True)
```
image

### CODE REVIEW

**Comment by jsistos** [comment]
Maybe we could add a parameter to the function instead so that both styles can be displayed. I hadn't really think about it, but I could try it in a few days.

**Comment by mtreinish** [comment]
> Maybe we could add a parameter to the function instead so that both styles can be displayed. I hadn't really think about it, but I could try it in a few days.

Yeah, I agree this should probably be a kwarg that enables either order because I can see use cases for either. I'm also not sure if we want to change the default order here as it might catch people off guard.

**Comment by jsistos** [comment]
So I added the parameter `reverse_order` to `qiskit.visualization.plot_bloch_multivector()`, and set the default to False to maintain compatibility. What do you think @mtreinish ?

**Review by kdk — COMMENTED** [review]
> So I added the parameter `reverse_order` to `qiskit.visualization.plot_bloch_multivector()`, and set the default to False to maintain compatibility. What do you think @mtreinish ?

Maybe, for consistency with the circuit drawers (which have the same behavior), the keyword arg could be named `reverse_bits`?

**Review by kdk — APPROVED** [review]
Thanks @jsistos , this looks good!

**Pull request merged**
