### PR TITLE
Update README.md: `pip install qiskit` no longer installs all elements

### PR DESCRIPTION
**Pull request by garrison**
### Summary

This updates the README to reflect that `pip install qiskit` no longer installs all elements.

### CODE REVIEW

**Review by HuangJunye — APPROVED** [review]
LGTM. Thanks for the fix. I am not sure I have the approval permission, but I am going to try anyway.

**Review by Cryoris — APPROVED** [review]
LGTM. Should we also update the top of the README files in the leftover elements that still says
> Qiskit is made up of elements that each work together to enable quantum computing. This element is <Terra/Aer/Ignis> ...

Or do we keep that until they are renamed?

@garrison would you mind submitting a similar PR to Aer and Ignis which still state that `pip install qiskit` installs all elements? 🙂

**Comment by garrison** [comment]
> would you mind submitting a similar PR to Aer and Ignis which still state that `pip install qiskit` installs all elements?

There is https://github.com/Qiskit/qiskit-aer/pull/1424.  I had not considered Ignis, but I'll open a PR there shortly, too.

**Comment by garrison** [comment]
I pushed an additional commit following https://github.com/Qiskit/qiskit-aer/pull/1424#discussion_r793810182 which dimissed the reviews.  I believe this PR is ready now.

**Review by jakelishman — APPROVED** [review]

**Pull request merged**
