### PR TITLE
Fix for size mismatched in initializer instruction

### LINKED ISSUE #2372: gate dimension mismatch not detected
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
The following code should throw an error, because it's trying to append a 3 qubit initializer to 2 qubits. But it does not raise.

```python
random_state = [
    1 / math.sqrt(4) * complex(0, 1),
    1 / math.sqrt(8) * complex(1, 0),
    0,
    1 / math.sqrt(8) * complex(1, 0),
    1 / math.sqrt(8) * complex(0, 1),
    0,
    1 / math.sqrt(4) * complex(1, 0),
    1 / math.sqrt(8) * complex(1, 0)]

qc = QuantumCircuit(qr)
qc.initialize(random_state, qr[0:2])
```

In stable this works as expected, so probably an issue with the recent append PR.

### PR DESCRIPTION
**Pull request by 1ucian0**
Fixes #2372 

Each instruction is in charge of testing how many parameters are expected. This PR fixes that and add tests.

### CODE REVIEW

**Comment by ajavadia** [comment]
This looks good. The second test doesn't seem to be checking anything new though (there's already a test to see if initialize works on a register)

**Comment by 1ucian0** [comment]
Both tests fail in master without this patch. Which is the test that does the same?

**Comment by ajavadia** [comment]
> Both tests fail in master without this patch. Which is the test that does the same?

I know. I'm just saying i don't understand what coverage test#2 adds on top of test#1, they do the same thing. If you're testing that initialize can be applied to a register, there's already another test for that too.

**Comment by 1ucian0** [comment]
Oh! I see what you mean. It was because my first fix did not consider the length of the register. But it is true that there is not difference in the fix that I pushed. Removed. Thanks.

**Pull request merged**
