### PR TITLE
add 'unitary' to BasicAer simulators

### LINKED ISSUE #2341: BasicAer qasm_simulator missing 'unitary' implementation
### Information

- **Qiskit Terra version**: 0.8
- **Python version**: 3.6
- **Operating system**: MacOS 10.14

### What is the current behavior?

The BasicAer qasm simulator has 'unitary' in its bases gates, but does not have an implementation for arbitrary unitaries leading to an exception for any circuit that contains them.

### Steps to reproduce the problem

```python
from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister
from qiskit import execute, BasicAer
from qiskit.quantum_info.operators import Operator

# Add to a circuit
qr = QuantumRegister(1)
cr = ClassicalRegister(1)
circ = QuantumCircuit(qr, cr)
circ.append(Operator([[0, 1], [1, 0]]), [qr[0]])
circ.measure(qr, cr)

backend = BasicAer.get_backend('qasm_simulator')
job = execute(circ, backend)
job.result().get_counts(0)
```

Raises
`BasicAerError: 'qasm_simulator encountered unrecognized operation "unitary"'`

### What is the expected behavior?

Circuit executes

### Suggested solutions

I will put in a PR to add an implementation of arbitrary unitaries to the BasicAer simulators.

### PR DESCRIPTION
**Pull request by chriseclectic**
### Summary

Adds arbitrary 'unitary' gates to BasicAer simulator basis gates.

Closes #2341

### CODE REVIEW

**Comment by ajavadia** [comment]
can you add a couple tests?

**Comment by jaygambetta** [comment]
code looks good but I agree with @ajavadia we should get some tests

**Comment by ajavadia** [comment]
@chriseclectic ping

**Comment by chriseclectic** [comment]
@ajavadia added tests

**Pull request merged**
