### PR TITLE
Fix target acquire alignment typo

### PR DESCRIPTION
**Pull request by HuangJunye**
### Summary

There was a typo for "acquire_alignment" attribute in Target. This PR corrected the typo.

### Details and comments

qiskit-ibm-runtime repo should also correct the typo: https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/qiskit_ibm_runtime/utils/backend_converter.py#L109
I have submitted a PR to fix that: https://github.com/Qiskit/qiskit-ibm-runtime/pull/184

### CODE REVIEW

**Review by mtreinish — CHANGES_REQUESTED** [review]
Unfortunately because this is part of a stable released interface fixing the typo isn't as straightforward as it might seem. Simply changing the attribute name will break any downstream users of `Target` when they upgrade to 0.20.0 and they'll had compatibility issues for trying to support 0.19.x and 0.20.0 at the same time. Causing a breaking change like that is a big deal and we should try to avoid it all costs. If we really need to fix this we'll have to go through a full deprecation cycle before we can remove the old name.

To do this properly the first step is to add a new attribute with the correct spelling and have it aliased to the existing name. Then in 0.21.0 we can deprecate the old name and start to migrate people to the new name. Finally in 0.23.0 (assuming at least 3 months have past since 0.21.0) we can remove the incorrect spelling and only the new attribute will exist.

**Comment by HuangJunye** [comment]
Thanks for explaining the details of deprecation cycle. Do you prefer to keep the typo or to fix it?

**Comment by mtreinish** [comment]
Personally I'd probably just leave it, all APIs have warts and to me a typo like this isn't worth the overhead both for us and downstream consumers to fix it. That being said I know others feel differently about issues like this and find having the correct and consistent spelling of things more important than I do. I probably would actually be fine with just doing the first step and support both the incorrect and correct spelling at the same time and just supporting both moving forward. It's not much cognitive overhead for maintaining the class if we do it correctly and then we don't have to worry about the compatibility issues with deprecation.

**Comment by HuangJunye** [comment]
Decided not to make the change. Closing the PR.

**Pull request closed without merging**
