### PR TITLE
Equivalence checkers

### LINKED ISSUE #761: Provide equivalence checkers
According to @liupibm:

### The goal of the quivalence checker
Given two circuits, check whether their final amplitude vectors V1 and V2 are equivalent: they differ only in the global phase, i.e., the equation V1*E^(I*x)=V2 has a solution.

This is useful for debugging transpiler passes also.

### PR DESCRIPTION
**Pull request by liupibm**
Fix #761

## [what is it?]
Two equivalence checkers are provided under qiskit/tools:
equivalence_checker_with_sympy_backend
fast_equivalence_checker
For more details, please refer to READMEs in the above folders.

## [What is the goal of an equivalence checker?]
Given two qasm programs, the tool checks whether their final amplitude vectors V1 and V2 are equivalent: they differ only in the global phase, i.e., the equation V1*E^(I*x)=V2 has a solution.

## [equivalence_checker_with_sympy_backend]
This checker depends on the sympy backends in qiskit, which processes the circuit gate by gate. Given there are usually many gates, the processing is slow.

## [fast_equivalence_checker]
This checker is at least 10X faster than equivalence_checker_with_sympy_backend.
It is optimized by processing the quantum circuit layer by layer, rather than gate by gate.

### CODE REVIEW

**Comment by lbello** [comment]
If I understand correctly, #219 depends on #217. So I'm putting this PR on hold, waiting for #217 to be merged.

**Comment by liupibm** [comment]
sounds good.
Let us merge #217 first and come back to this.

**Comment by delapuente** [comment]
@1ucian0 @liupibm what's the status of this? #217 is merged, can we remove the `on-hold` status? I've open the issue #761 to track this bug.

**Comment by ajavadia** [comment]
This PR is quite out of date now, in light of a few recent changes:

1- The proposed equivalence checker uses the Sympy simulator, which is now its own external repository (not part of Terra): https://github.com/QISKit/qiskit-addon-sympy

2- The Qiskit simulation framework is moving to Qiskit-Aer, which will have high performance simulation tools. Keeping exact forms through Sympy is secondary to speed, since we are targeting near-term devices that are noisy anyway. *Epsilon*-equivalence checking that is fast is more practical.

3- Equivalence checking through simulation can be very slow, and we need to think of potentially having equivalence databases. 

I am closing this until we rethink the issue and discuss in #761.

**Pull request closed without merging**
