### PR TITLE
Add user config file for local settings

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

This commit adds the concept of a user config file to set local defaults
when using qiskit-terra. This enables the end user to override the
default values for some commonly used terra functions in their local
environment. Right now this only includes the backend used by the
circuit drawer, but it will be expanded in the future as more settings
with opinionated defaults are exposed. To set a config file you can
either create one in the default location
'~/.config/qiskit/settings.conf' or use the QISKIT_SETTINGS environment
variable to specify an alternative location.

### Details and comments

### CODE REVIEW

**Comment by nonhermitian** [comment]
Why is this not in the .qiskit dir and why are we not taking advantage of the runtime config stuff we already have?

**Comment by mtreinish** [comment]
> Why is this not in the .qiskit dir and why are we not taking advantage of the runtime config stuff we already have?

It's a typo/mistake in the commit message, I copied the directory from the ibmq provider code and just changed the file name. The directory is `~/.qiskit`:  https://github.com/Qiskit/qiskit-terra/blob/4353b20bf87aa8b329aab64462d6ca89f9380913/qiskit/user_config.py#L15-L16 

The reason It's not using the same file is after looking at the same qiskitrc is that the way the ibmq provider parses that is it uses any section name as a different set of credentials. So adding anything to it will be interpreted as a new set of credentials. Instead of trying to change the contract there it felt better to just make it a distinct file.

**Comment by nonhermitian** [comment]
Yes, it is unfortunate that that design choice was made. I was mentioning reusing the runtime config functionally we already have, but I think they were moved out of terra to the provider, so that answers that question.

**Comment by mtreinish** [comment]
> Yes, it is unfortunate that that design choice was made. I was mentioning reusing the runtime config functionally we already have, but I think they were moved out of terra to the provider, so that answers that question.

Ah that's what you were asking about, yeah that was moved out of the repo with the split of the qiskit-ibmq-provider: https://github.com/Qiskit/qiskit-ibmq-provider/blob/master/qiskit/providers/ibmq/credentials/configrc.py

**Pull request merged**
