### PR TITLE
Fix performance of QuantumCircuit append() and qasm()

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

In #4072 the _append() and _qasm() methods were changed to use the
public facing data property instead of the private _data. The public
facing one adds additional validation that is necessary to ensure the
internal structure of the circuit object is always consistent. This
comes with an overhead that can lead to a significant slowdown in
circuit related operations. [1] This commit corrects this to use the
internal _data which skips the validation because terra itself shouldn't
build a circuit with invalid data. If the QFT circuit library class is
doing something that could violate this it needs to be updated.

[1] https://qiskit.github.io/qiskit/#circuit_construction.CircuitConstructionBench.time_circuit_extend?commits=c505eefd

### Details and comments

### CODE REVIEW

**Comment by Cryoris** [comment]
Could you add
```python
def qasm(self, formatted=False, filename=None):
    self._build()
    return super().qasm(formatted, filename)

def append(self, instruction, qargs=None, cargs=None):
    self._build()
    return super().append(instruction, qargs, cargs)
```
to the QFT class? That should fix the docs issues. I'll work on a more permanent solution for all these flexible objects in the circuit library.

**Comment by mtreinish** [comment]
oh, I missed your comment, I just added `_build()` to the `__init__()` which seemed to fix it too: https://github.com/Qiskit/qiskit-terra/pull/4169/commits/56eab8aeac203f6dccd2ab7896cae8ab7db4a418 I'm not sure what advantage trying to build an empty circuit at class creation time give you

**Comment by Cryoris** [comment]
Since the class attributes, such as the number of qubits, the approximation degree or others can be changed, we want to avoid re-building the whole circuit on every change but only when it is actually used. 

Adding `_build` to `__init__` fixes it in the docs because the object is not changed there 🙂But if it would be modified it would break. E.g. 
```python
qft = QFT(2)
qft.num_qubits = 3
qft.qasm()
```
would still give the same error, since `_data` is reset to `None`.

**Comment by mtreinish** [comment]
ok, yeah I missed rebuilding on the setters. But I still don't understand the rationale for the whole dynamic/lazy building here. What advantage does this provide over just making a new QFT object if you want new value for num_qubits? I can see what you're getting at that you don't want to rebuild twice is you adjust both `approximation_degree` and `num_qubits` right after each other. But why you don't just build a new QFT object isn't clear to me. The overhead of the class constructor is minimal compared to the `_build` method

**Comment by Cryoris** [comment]
Is some algorithms we need to pass around circuit library objects where we need to change only one attribute. For instance we can have an algorithm that uses a QFT where the operator, that determines the number of qubits, is only available upon execution, not initialization. Then we need to adjust the number of qubits before execution, while the QFT is set at initialization. E.g.
```python
class AmplitudeEstimation:
    def __init__(self, qft: QFT, ...):
        # initialize
        self.qft = qft
   
    def run(self, operator: QuantumCircuit, ... ):
       self.qft.num_qubits = operator.num_qubits
       # construct circuit, append QFT, run and execute
```
The QFT can be specialized in other ways, say the approximation degree, or even a complete different version of a QFT. But that doesn't matter to the Algorithm, it only needs to adjust the number of qubits. 
This concept occurs in different places with different attributes. 

To not rebuild on every change we made the object construct the circuit lazily.

**Pull request merged**
