### PR TITLE
passmanager method `add_passes` renamed to `add`

### PR DESCRIPTION
**Pull request by 1ucian0**
In the discussion with @ajavadia if the passmanger method for adding passes should be called `add_passes` or `add_pass`, we decided for just `add`. This PR is that rename.

### CODE REVIEW

**Comment by jaygambetta** [comment]
Can we use append since order matters

**Comment by 1ucian0** [comment]
I like it! The alternative PR with that change is #1508. Feel free to merge one of them and close the other one.

**Comment by jaygambetta** [comment]
We have a few hours with test to decide.

**Comment by ajavadia** [comment]
I'm good with append.

**Comment by ajavadia** [comment]
Ok i'll close this and we merge that one.

**Pull request closed without merging**
