### PR TITLE
Choose how to justify circuit with matplotlib drawer

### PR DESCRIPTION
**Pull request by maddy-tod**
### Summary
This implements the justify parameter as described in #1725 for the matplotlib drawer. 

The change consists of now looping over the layers of gates, rather than drawing each gate into its own column.

### CODE REVIEW

**Comment by ajavadia** [comment]
@t-imamichi or @nkanazawa1989 can you please take a look at this

**Comment by nkanazawa1989** [comment]
@maddy-tod can you remove `compress` option from `qiskit.tools.visualization._qcstyle.py` ?

Also I found a bug when wide and non-wide gates are placed in the same layer.

e.g.
```
cr = ClassicalRegister(2)
qr = QuantumRegister(3)
qc = QuantumCircuit(qr, cr)

qc.x(qr[0])
qc.x(qr[0]).c_if(cr, 1)
qc.u3(pi/2, pi/2, pi/2, qr[2])

qc.draw(filename='tmp.png', output='mpl')
```
tmp

Also wide gate (in the example, u3) is overlapped with the line of conditional gate. You need to shift conditional gate one step. Generation of coordinate to plot gates is bit tricky. Gate width should not be applied to a layer. It should be applied to each gate.

**Comment by maddy-tod** [comment]
Hi @nkanazawa1989  thanks for spotting this bug! I have fixed it, the output is now :
image

**Comment by maddy-tod** [comment]
I also found that when drawing 
```
qr = QuantumRegister(3, 'q')
circuit = QuantumCircuit(qr)
circuit.rzz(0, qr[0], qr[1])
circuit.rzz(pi / 2, qr[2], qr[1])
circuit.draw(filename='tmp3.png', output='mpl')
```
the output is
image
Is this incorrect? In the text drawer this is drawn as
```
        ┌────────┐               
q_0: |0>┤        ├───────────────
        │ Rzz(0) │┌─────────────┐
q_1: |0>┤        ├┤             ├
        └────────┘│ Rzz(1.5708) │
q_2: |0>──────────┤             ├
                  └─────────────┘
```

**Pull request merged**
