### PR TITLE
Start deprecation of complex parameters in Qiskit Pulse

### PR DESCRIPTION
**Pull request by TsafrirA**
### Summary
This PR starts the deprecation process of complex parameters in Qiskit Pulse, by raising a `PendingDeprecationWarning` when one assigns a complex value to `ParameterExpression` in any Pulse object.

### Details and comments
PR #9002 began the deprecation of the last complex parameters in Qiskit Pulse (namely the `amp` parameter of pulses in the `SymbolicPulse` library). Complex values in `ParameterExpression` have caused issues in the past (for example #9187), and it seems likely that eventually complex values will be phased out. With #9002 in place, we can therefore begin heading in this direction and deprecate the use of complex parameters.

A `PendingDeprecationWarning` is raised whenever a complex value is assigned to any `ParameterExpression` of any Pulse instance.

### CODE REVIEW

**Comment by TsafrirA** [comment]
@nkanazawa1989 
Following today's discussion, we can add a second warning higher up the hierarchy which will catch only assignment of proper complex values (as covered by [this test](https://github.com/Qiskit/qiskit-terra/blob/126c9ba1e3b1dc1486b0191de759bd756ff91a28/test/python/pulse/test_parameter_manager.py#L352)), and leave the original as is for `SymbolicPulse` to catch cases where the final result is complex (even when the assigned value is real, as covered by [this test](https://github.com/Qiskit/qiskit-terra/blob/126c9ba1e3b1dc1486b0191de759bd756ff91a28/test/python/pulse/test_parameter_manager.py#L338)). As I said, I don't think there are other cases where one would use complex parameters outside of the `SymbolicPulse`, but we can go with that solution if you prefer.

**Comment by nkanazawa1989** [comment]
Yes, because we are dropping the complex valued parameter support from the Qiskit stack, explicit deprecation warning at higher level would make more sense. I'm not sure if we should drop complex valued expression. Alternatively to this, once we deprecate, we can also upgrade pulse library with [sympy assumption system](https://docs.sympy.org/latest/guides/assumptions.html#assumptions) and make a query to check if the expression is real (maybe it's slow).

**Comment by TsafrirA** [comment]
I think @wshanks is right. This PR will cover practically everything, and then the formal and final deprecation could possibly be done higher in the stack (Directly in `ParameterExpression`?).

**Comment by nkanazawa1989** [comment]
Surprisingly it's already dropped without deprecation. You can try this code
```python
from qiskit.circuit import Parameter, Gate, QuantumCircuit

param = Parameter("complex_val")
gate = Gate("rabi", 1, [param])

qc = QuantumCircuit(1)
qc.append(gate, [0])

qc.assign_parameters({param: 0.1+0.1j}, inplace=False)
```
that results in 
```
---------------------------------------------------------------------------
CircuitError                              Traceback (most recent call last)
<ipython-input-52-66dc527d85d2> in <module>
      7 qc.append(gate, [0])
      8 
----> 9 qc.assign_parameters({param: 0.1+0.1j}, inplace=False)

~/Develop/qiskit/qiskit-terra/qiskit/circuit/quantumcircuit.py in assign_parameters(self, parameters, inplace)
   2637             # replace the parameters with a new Parameter ("substitute") or numeric value ("bind")
   2638             for parameter, value in unrolled_param_dict.items():
-> 2639                 bound_circuit._assign_parameter(parameter, value)
   2640         else:
   2641             if len(parameters) != self.num_parameters:

~/Develop/qiskit/qiskit-terra/qiskit/circuit/quantumcircuit.py in _assign_parameter(self, parameter, value)
   2726                     # if fully bound, validate
   2727                     if len(new_param.parameters) == 0:
-> 2728                         instr.params[param_index] = instr.validate_parameter(new_param)
   2729                     else:
   2730                         instr.params[param_index] = new_param

~/Develop/qiskit/qiskit-terra/qiskit/circuit/gate.py in validate_parameter(self, parameter)
    228             if not parameter.is_real():
    229                 msg = f"Bound parameter expression is complex in gate {self.name}"
--> 230                 raise CircuitError(msg)
    231             return parameter  # per default assume parameters must be real when bound
    232         if isinstance(parameter, (int, float)):

CircuitError: 'Bound parameter expression is complex in gate rabi'
```

Complex parameter assignment still works in the pulse domain.
```python
from qiskit.pulse import Schedule, Play, Constant, DriveChannel

param = Parameter("complex_val")
sched = Schedule()
sched += Play(Constant(100, param), DriveChannel(0))

sched.assign_parameters({param: 0.1+0.1j}, inplace=False)
```

However, we are migrating to the pulse gate model and direct schedule execution is going to be deprecated. Considering this situation probably we can also deprecate the complex parameter assignment also in the pulse domain. One exception here is a program for `DynamicsBackend` (or `PulseSimulator`), i.e. we can still directly pass the Schedule and for now we can use complex valued parameter.

**Review by nkanazawa1989 — APPROVED** [review]
Thanks. LGTM

**Pull request merged**
