### PR TITLE
warning when make test

### PR DESCRIPTION
**Pull request by 1ucian0**
### Summary

Fixes https://github.com/Qiskit/qiskit-terra/issues/5045

### Details and comments

Echos a warning when `make test`.

### CODE REVIEW

**Comment by mtreinish** [comment]
I think we should hold on this to get some more opinions. While I'm in favor of this as I think we want to push people, especially new contributors towards tox which is an easier experience since it handles installation and testing together, I know there are people who prefer the makefile and have been using `make test` for a long time. So I want to make sure to not alienate those people with a warning. 

Also, now that I think about it a bit I'm not sure if warning at the top is super useful. The test output is pretty verbose, so it will print the warning and then disappear in the sea of output for each individual test right?

**Comment by 1ucian0** [comment]
> Also, now that I think about it a bit I'm not sure if warning at the top is super useful. The test output is pretty verbose, so it will print the warning and then disappear in the sea of output for each individual test right?

True. Maybe at the end?

**Comment by 1ucian0** [comment]
> So I want to make sure to not alienate those people with a warning.

@nonhermitian @levbishop ?

**Comment by nonhermitian** [comment]
I am good.

**Review by kdk — APPROVED** [review]

**Pull request merged**
