### PR TITLE
Improve parenthesis in circuit library equations 

### PR DESCRIPTION
**Pull request by saktar-unr**
### Summary
The pull request fixes issuehttps://github.com/Qiskit/qiskit-terra/issues/7800 (#7800). I have modified the docstrings of standard_gates module to fix the parenthesis size.

### Details and comments
The docstrings of some files of qiskit/circuit/library/standard_gates module were written without appropriate latex tag (\left, \right) for parenthesis (they were using default parenthesis). So, the parenthesis size was not align with other text. We can refer to https://github.com/Qiskit/qiskit-terra/issues/7800#issuecomment-1078872749 to see how modifying latex tags fixes parenthesis size.

I have edited docstrings of 13 files in the standard_gates module. Basically I adjusted the parenthesis tags to fix their size.

### CODE REVIEW

**Comment by Cryoris** [comment]
Thanks for the PR @saktar-unr! This looks great, I just have some two small things we could also fix:
* the parameter name in the CRX docs is wrong, could you adjust that to use `\theta` consistently?
* the equations in the U1 docs don't have a parameter at all, could you adjust that it shows `U1(\lambda)` instead of `U1`?

**Comment by saktar-unr** [comment]
@Cryoris, Thank you! I fixed CRX gate parameter as you said. Did you meant to fix CU1 gate (https://qiskit.org/documentation/stubs/qiskit.circuit.library.CU1Gate.html#qiskit.circuit.library.CU1Gate) by adding CU1(\lambda) instead of CU1. 

I could not find any parameter issue in U1 gate documentation (https://qiskit.org/documentation/stubs/qiskit.circuit.library.U1Gate.html#qiskit.circuit.library.U1Gate).

**Comment by saktar-unr** [comment]
@Cryoris, Thank you very much for all the guidelines. This was my first ever issue and pull request where I learned a lot. I hope to contribute more in the future!

**Comment by Cryoris** [comment]
Great to hear @saktar-unr, we can certainly find more projects you can tackle!

**Pull request merged**
