### PR TITLE
Pauli-X measurement instruction

### PR DESCRIPTION
**Pull request by yaelbh**
### Summary

This PR replaces the old PR #5311, while addressing the comments there.

### Details and comments

1. This is only `measure_x`, when it's finalized (after review) I'll write `measure_y`.
2. Afterwards we can consider @itoko's suggestion https://github.com/Qiskit/qiskit-terra/pull/5311#issuecomment-1050432663.

Ready for review if the CI passes.
@1ucian0 @nkanazawa1989 @itoko

### CODE REVIEW

**Review by nkanazawa1989 — COMMENTED** [review]
LGTM. I like this implementation in calibration perspective. Since we can attach calibration per every instruction, a general Pauli measure instruction is difficult to manage because schedule may change depends on the basis.

(but I will hold my approval since I'm not expert of circuit instruction)

**Comment by ikkoham** [comment]
I have a question. Should `QC.remove_final_measurements` remove this instruction or not?

**Comment by 1ucian0** [comment]
> I have a question. Should `QC.remove_final_measurements` remove this instruction or not?

I think `RemoveFinalMeasurements` should remove this measurement. The original motivation was to create a statevector out of the circuit https://github.com/Qiskit/qiskit-terra/issues/2903

**Comment by ikkoham** [comment]
Thank you, it would be useful to have an option to leave the Hadamard gate when removing the X measurement.

**Comment by ajavadia** [comment]
> Since we can attach calibration per every instruction, a general Pauli measure instruction is difficult to manage because schedule may change depends on the basis.

What do you mean by this @nkanazawa1989 ? 

Also is the experiments usecase here that there is a separate measure_x calibration that is different from just a Hadamard+measure?

**Comment by yaelbh** [comment]
The purpose of this PR is to speed-up Aer (statevector method) for VQE circuits. The idea is that VQE circuits will express their expectation value using the new instructions. Consequently, Aer will be able to efficiently simulate multi-qubit Pauli measurements.

I'm not sure if the last couple of sentences make sense; at least they made sense some time ago, when I started this work. Possibly, since then, the interface between VQE and Aer has changed, especially in light of the new Estimator primitive.

I'm closing this PR, because currently I'm not focused on classical simulation for VQE. I find the addition of instructions less simple than it looks, for reasons detailed in previous comments. Back then, we (@chriseclectic and I) considered two alternatives. The one that we decided to pursue is to add instructions to Terra, and let Aer benefit from them. The other alternative is to build a mechanism in Aer that detects Pauli measurement instructions, in circuits that don't contain them explicitly.

**Pull request closed without merging**
