### PR TITLE
Add circuit library to Terra API Reference list

### LINKED ISSUE #9462: "Circuit Library" is not listed in "Qiskit Terra API Reference"
### Environment

https://qiskit.org/documentation/

### What is happening?

The Qiskit Terra API Reference list (Qiskit Terra API Reference) does not include Circuit Library (https://qiskit.org/documentation/apidoc/circuit_library.html). It used to be linked from the sidebar but now it should be there.

### How can we reproduce the issue?

Go to Qiskit Terra API Reference page https://qiskit.org/documentation/apidoc/terra.html and try to find Circuit Library

### What should happen?

Circuit Library (https://qiskit.org/documentation/apidoc/circuit_library.html) should be listed in Qiskit Terra API Reference page (https://qiskit.org/documentation/apidoc/terra.html)

### Any suggestions?

_No response_

### PR DESCRIPTION
**Pull request by priti-ashvin-shah-ibm**
### Summary
I read the contributing guidelines.

### Details and comments

I moved the circuit_library to be within API Reference regarding issue #9462.  In addition, regarding issue https://github.com/Qiskit/qiskit/issues/1644  Removed Circuit Library from (sidebar) being at the same level as API Reference. 

Close #9462

### CODE REVIEW

**Review by HuangJunye — CHANGES_REQUESTED** [review]
Looks good! Can you also remove the title `Circuit Library` of https://github.com/Qiskit/qiskit-terra/blob/main/docs/apidocs/circuit_library.rst similar to https://github.com/Qiskit/qiskit-terra/blob/main/docs/apidocs/circuit.rst so that the generated API page follows the style of the rest of the API module pages (`Circuit Library (qiskit.circuit.library`)?

Screen Shot 2023-02-03 at 18 53 00

**Comment by HuangJunye** [comment]
@priti-ashvin-shah-ibm Can you also update the PR description to [link the issue](https://github.com/Qiskit/qiskit-terra/issues/9462) you the PR is fixing?

**Comment by priti-ashvin-shah-ibm** [comment]
I agree that I didn’t even write anything in the PR, was using as CI for building a doc.  It is a draft pr.

**Comment by HuangJunye** [comment]
I updated the description because issue https://github.com/Qiskit/qiskit/issues/1644 is on the qiskit meta repo not in terra. And to close https://github.com/Qiskit/qiskit/issues/1644, we need to make corresponding updates in meta repo to remove it from the sidebar.

**Review by HuangJunye — APPROVED** [review]
LGTM! Thanks for your contribution!

**Review by 1ucian0 — APPROVED** [review]
Thanks!

**Pull request merged**
