### PR TITLE
Bit-string oracle for the circuit library

### PR DESCRIPTION
**Pull request by Cryoris**
### Summary

Adds a bit-string oracle to the circuit library.
Provided with a bit-strings specifying a target state, it applies a -1 phase if the qubit states match the bit-string. 
E.g. if the bit-string reads `'0xx1'` it applies -1 if qubit 0 is in state `|0>` and qubit 3 is in state `|1>`.

### Details and comments

Used in Quantum Amplitude Estimation and Grover's algorithm. Essentially implements a MCZ with open/closed controls, but I didn't want to add a new gate before we figure out where multi-controlled gates should go.

### CODE REVIEW

**Comment by boschmitt** [comment]
I think the name is too generic and what it implements is too specific.

IMHO it is weird to have this fancy way to add a MCZ gate.

**Comment by Cryoris** [comment]
Name suggestions are welcome 😄 

>IMHO it is weird to have this fancy way to add a MCZ gate.

Functionally it's the same as an MCZ yes, but you'd use it in a different context. If I want to create a circuit with a MCZ then I'd use `ZGate().control()`, or `MCXGate` directly. Here it's about having a standalone `QuantumCircuit` used as oracle in Grover or Amplitude Estimation. If we implement `MCZ` then this class could just be a wrapper but I think it's important having this as a circuit type to be able to use it interchangeably with other oracles and circuits in algorithms.

**Comment by ajavadia** [comment]
I have two issues with this:
1- The bit order should be reversed to be little-endian :)
2- Can we try to consolidate this with the oracle compiler in #4522? So the user would express the design intent for this oracle using a classical Python function, decorated with `@oracle`. Because you could write many types of "BitstringOracle" - here you put a phase on a qubit (i.e. MCZ), you may want to flip a qubit instead (i.e. MCX), you may want to put a phase on amplitudes without using ancilla (i.e. Diagonal operator). Can we generically write these in terms of Python functions?

**Comment by Cryoris** [comment]
1 - Ok 😉 
2 - Do you mean integrating this into the oracle compiler or having the same interface? It would be nice if the oracles worked with Python functions consistently. However, it might be a bit inconvenient if you have an oracle with many qubits that does just a simple action, e.g.
```python
@oracle
def my_oracle(a: Bit, b: Bit, c: Bit, d: Bit, e: Bit):
   return not e
```
Maybe we could add a list as input to the oracle compiler? 
```python
@oracle
def my_oracle(a: List[Bit]):  # do we need to explicitly give the length of the list?
   return a[4]
```

**Comment by ajavadia** [comment]
For this case I think we just need to add support for an if/else. Can we do that @1ucian0 @boschmitt?

@oracle
def myoracle(a: Int1, b: Int1, c: Int1, d: Int1, e: Int1) -> Int1:
if a==0 and b==0 and c==1:
    return not e
else:
    return e

This would be the logic, but we can support syntactic sugar on top like word-level rather than bit-level expressions:

@oracle
def myoracle(x: Int5) -> Int1:
    if not x[4] and not x[3] and x[2]:
          return not x[0]
    else:
          return x[0]

Or like your syntax:

@oracle
def myoracle(x: Int4, y: Int1) -> Int1:
    if x == ‘110x’:
          return not y
    else:
          return y

**Pull request closed without merging**
