### PR TITLE
Speed up fidelity computation

### PR DESCRIPTION
**Pull request by kevinsung**
### Summary
Speeds up computation of fidelity.

### Details and comments
Uses `scipy.linalg.eigh` and `eigvalsh`, which are specialized to Hermitian matrices, to compute the matrix square roots faster.
Benchmark script executed on my laptop:
```
import timeit
import qiskit.quantum_info as qi

n_range = [7, 8, 9, 10]

for n in n_range:
    N = 2**n

    p = qi.random_density_matrix(N)
    q = qi.random_density_matrix(N)

    t0 = timeit.default_timer()
    _ = qi.state_fidelity(p, q)
    t1 = timeit.default_timer()

    print(f'Time with {n} qubits: {t1 - t0}.')
```
Output before:
```
Time with 7 qubits: 0.2144935099995564.
Time with 8 qubits: 1.050258133999705.
Time with 9 qubits: 11.87974080099957.
Time with 10 qubits: 124.77152486199975.
```
Output after:
```
Time with 7 qubits: 0.060302328999569.
Time with 8 qubits: 0.3195206459995461.
Time with 9 qubits: 1.8964228539998658.
Time with 10 qubits: 13.649769595999715.
```

### CODE REVIEW

**Comment by mtreinish** [comment]
Thanks for pushing this, I know we had some reliability issues with `eigh` on newer macOS versions, see: https://github.com/Qiskit/qiskit-terra/pull/3884 

@nonhermitian any thoughts on this?

**Comment by nonhermitian** [comment]
I would be a bit cautious here. What does the timing with schur look like?

**Comment by kevinsung** [comment]
Replacing the call to `eigh` with `schur`:
```
Time with 7 qubits: 0.08709751700007473.
Time with 8 qubits: 0.5088386980005453.
Time with 9 qubits: 3.0198565020000387.
Time with 10 qubits: 18.231902159999663.
```
Additionally replacing the call to `eigvalsh` with `schur`:
```
Time with 7 qubits: 0.14845086300010735.
Time with 8 qubits: 0.6890015429999039.
Time with 9 qubits: 3.8268830870001693.
Time with 10 qubits: 23.53117320599995.
```

**Comment by nonhermitian** [comment]
Ok looks like schur is the way to go for now.

**Comment by kevinsung** [comment]
Ok I switched both calls to using `schur`. Let me know if you want to allow the `eigvalsh` call, since only `eigh` was specifically mentioned as being potentially problematic.

**Comment by kevinsung** [comment]
Upon further investigation, I discovered that the main reason the original code is slow is that the function `_funm_svd` in `utils.py` explicitly uses the slower 'gesvd' lapack driver:
https://github.com/Qiskit/qiskit-terra/blob/2591bc8fcd957db37ab8edaf46e020ea9e27f5df/qiskit/quantum_info/states/utils.py#L149
Simply changing this line to use the default driver (which is 'gesdd') gave a large speedup. Why is the slower driver being used?

I reran the benchmark script since my laptop was performing differently. This time I seeded the matrix generation and ran a few times to ensure consistent results. The output I got was:
1. Original code:
```
Time with 7 qubits: 0.1419102399959229.
Time with 8 qubits: 0.9013907920016209.
Time with 9 qubits: 8.311445758008631.
Time with 10 qubits: 95.4847254990018.
```
2. Change `_funm_svd` to use default lapack driver:
```
Time with 7 qubits: 0.055180703988298774.
Time with 8 qubits: 0.2489175070077181.
Time with 9 qubits: 1.470295552004245.
Time with 10 qubits: 7.401587213011226.
```
3. Use `eigh` and `eigvalsh` instead of `svd`:
```
Time with 7 qubits: 0.022977120999712497.
Time with 8 qubits: 0.1714069779991405.
Time with 9 qubits: 0.7301249449956231.
Time with 10 qubits: 3.344589893997181.
```
If the lapack driver choice is important in other places for some reason, we could at least let it be passed as an argument to `_funm_svd` and use the faster driver wherever possible.

**Comment by chriseclectic** [comment]
@kevinsung I can't recall why `gesvd` was originally used (it was probably copied from legacy code). If there is no significant difference in accuracy between the two drivers we should switch to the faster default one.

I'm not sure if `eigvalsh` has the same issues on newer MacOS that @nonhermitian found with `eigh`.

**Comment by kevinsung** [comment]
The faster default svd driver does not appear to be any less accurate than the slower one. I've modified this PR to simply remove the specification to use the slow driver. Let me know if you want me to use the faster method that uses eigh, though I understand if you want to avoid that.

**Comment by chriseclectic** [comment]
Ok let's switch that for then then. I would like to switch to the faster eigenvalue method once the blas issue on Catalina is fixed.

Maybe we could have both versions and switch according to operating system. What do you think @nonhermitian @mtreinish ?

Something like:
```python
import platform

def check_macos_catalina():
    # Check if MacOS
    if platform.system() != 'Darwin':
        return False
    
    # Get MacOS Version and check for 10.15.X
    major, minor, _ = platform.mac_ver()[0].split('.')
    if major == '10' and minor == '15':
        return True
    return False
```
and then in fidelity have
```python
import platform

def state_fidelity(...):
    ...
    # Fidelity of two DensityMatrices
    if check_macos_catalina():
        # There is a bug with the Scipy eigh Lapack function and openblas on
        # MacOS Catalina so we need to use a slower implementation based on SVD
        ... svd method with default driver...
    else:
        ...eigenvalue method...
```

And then we should track the openblas issue and remove the slower code when it is fixed.

**Comment by mtreinish** [comment]
@chriseclectic it's a bit more subtle than just Catalina it depends on how python is installed (ie conda vs not conda), which python version, and if you're on macOS > 10.13. Basically on macOS 10.14 and 10.15 outside of conda all python versions fail with `eigh`, with conda installed python it fails if python == 3.5. If you want to select the method conditionally like that I would look for the mac os version >= 10.14 and use the fallback method for that. I just worry that there will be subtle differences between the different methods which will become annoying to debug in the future.

**Pull request merged**
