### PR TITLE
Add doc8 run to CI and lint checks for CHANGELOG.rst

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

This commit adds running doc8 to our normal CI and lint workflows. Right
now we don't have any doc verification (aside from what pylint enforces
on docstrings in code) and when it comes time to publish a new release
there is a scramble to fix all the warnings (and potentially errors) in
the documentation. By running doc8 we can verify that our documentation
is formatted properly for sphinx to compile the output without issue.

### Details and comments

### CODE REVIEW

**Comment by 1ucian0** [comment]
Currently, `docs/` was moved to https://github.com/Qiskit/qiskit. Should this PR be closed?

**Comment by mtreinish** [comment]
Yes, I will move this to the meta-repository

**Comment by mtreinish** [comment]
Actually, now that I think about it there is still the CHANGELOG.rst file which had it's fair share of problems when I was doing the 0.7 release documentation so I'm just going to re-target this for just that file

**Comment by mtreinish** [comment]
Just for reference I added the doc8 job to the meta-repository here too: https://github.com/Qiskit/qiskit/pull/52

**Comment by diego-plan9** [comment]
Agreed on closing, moving to the general repo. Might be worth checking the granularity of the CI triggers (ie. when a file is changes) and revising the decision.

**Pull request closed without merging**
