### PR TITLE
result.get_memory()

### LINKED ISSUE #1063: result.get_memory() command
We have many requests to have the random numbers streamed in memory. 

The basic idea is to get something to run like 

```
backend = IBMQ.get_backend('name')
backend.update_settings('memory'=True)
job = backend.run(qobj)
result = job.result()
```
then we go 

```
outcomes = result.get_memory()
``` 
outcomes will be 

```
['010', '100', '111' ...]
```
 
- [ ] make sure the experiment can work with it @taalexander  is doing this
- [ ] pass the api 
- [ ] qiskit function exists to get_memory

### PR DESCRIPTION
**Pull request by ajavadia**
### Summary
Fixes #1063
This PR supports reading per-shot measurements, in a new field of the result.data called memory. This information is accessible via result.get_memory().

The Aer.QasmSimulator() and Aer.QasmSimulatorPy() do this in #1373. The devices are being modified separately to do this. However, backends may continue to just return counts, if they choose.

### CODE REVIEW

**Comment by jaygambetta** [comment]
actually can we wait and make a test to go with this after the simulation is updated.

**Comment by ajavadia** [comment]
Yes this should be merged only after #1373. On hold for now.

**Comment by jaygambetta** [comment]
@ajavadia can this be merged now

**Comment by ajavadia** [comment]
No let's merge this after #1404.

**Pull request merged**
