### PR TITLE
Mocking of fake backends with several optimization levels

### PR DESCRIPTION
**Pull request by rafamartinc**
### Summary
* Fixes issue #2446 
* Tests added

### CODE REVIEW

**Comment by ajavadia** [comment]
I think for compactness, we can use `subTest` here, because all tests are very similar.
Take a look at `test_no_coupling_map` in the same file (` test/python/transpiler/test_preset_passmanagers.py`). 

I think all tests can be compacted by having an outer loop on backends (`[FakeTenerife(), FakeReuschlikon(), FakeMelbourne(), FakeTokyo()]`) and and inner loop on optimization_level ([0, 1, 2, 3])

**Comment by rafamartinc** [comment]
Is there anything else I should do from my side? Thanks!!

**Comment by 1ucian0** [comment]
> I think all the new tests you are introducing can be compacted

I dont agree that compacted tests are a good idea. However, we can discuss that in a different PR. Merging!

**Comment by rafamartinc** [comment]
> > I think all the new tests you are introducing can be compacted
> 
> I dont agree that compacted tests are a good idea. However, we can discuss that in a different PR. Merging! Thanks @rafamartinc for your first contribution!

Agreed, though we can also separate the tests in the future if they come to be more complex and test more assertions. Thank you both, @ajavadia @1ucian0 !!

**Pull request merged**
