### PR TITLE
Fix docs build on case-insensitive systems

### PR DESCRIPTION
**Pull request by jakelishman**
### Summary

During the switchover of the `SymbolicPulse` classes in the pulse library, there are several objects documented under `qiskit.library.pulse` that differ only by capitalisation.  Under `autosummary`, these therefore generate files with names that differ only by capitalisation, which causes naming clashes on systems that have case-insensitive semantics, such as macOS.  This then causes warnings to be emitted from the Sphinx build, failing it.

Autosummary has this setting that can be used as a workaround.  I went this route rather than converting the documentation to use more inline documentation for the library for now, because I expect the clash to be more short-lived, and I didn't want to make a change that meaningful impacts the style of the documentation without knowing the full context around it.

### Details and comments

For reference, the particular set of warnings/errors looked like:
```text
/Users/jake/code/qiskit/terra/qiskit/pulse/library/__init__.py:docstring of qiskit.pulse.library:52: WARNING: autosummary: stub file not found 'qiskit.pulse.library.constant'. Check your autosummary_generate setting.
/Users/jake/code/qiskit/terra/qiskit/pulse/library/__init__.py:docstring of qiskit.pulse.library:52: WARNING: autosummary: stub file not found 'qiskit.pulse.library.sawtooth'. Check your autosummary_generate setting.
/Users/jake/code/qiskit/terra/qiskit/pulse/library/__init__.py:docstring of qiskit.pulse.library:52: WARNING: autosummary: stub file not found 'qiskit.pulse.library.triangle'. Check your autosummary_generate setting.
/Users/jake/code/qiskit/terra/qiskit/pulse/library/__init__.py:docstring of qiskit.pulse.library:52: WARNING: autosummary: stub file not found 'qiskit.pulse.library.cos'. Check your autosummary_generate setting.
/Users/jake/code/qiskit/terra/qiskit/pulse/library/__init__.py:docstring of qiskit.pulse.library:52: WARNING: autosummary: stub file not found 'qiskit.pulse.library.sin'. Check your autosummary_generate setting.
/Users/jake/code/qiskit/terra/qiskit/pulse/library/__init__.py:docstring of qiskit.pulse.library:52: WARNING: autosummary: stub file not found 'qiskit.pulse.library.gaussian'. Check your autosummary_generate setting.
/Users/jake/code/qiskit/terra/qiskit/pulse/library/__init__.py:docstring of qiskit.pulse.library:52: WARNING: autosummary: stub file not found 'qiskit.pulse.library.drag'. Check your autosummary_generate setting.
```

### CODE REVIEW

**Review by Eric-Arellano — APPROVED** [review]
Thank you!

**Comment by jakelishman** [comment]
It's going to be a little fiddly to enforce that this isn't broken by other PRs in CI, I think, since we only really build the docs on Linux.  We don't _need_ the docs to build on anything other than Linux, so I don't think it's worth provisioning a Mac VM (which are less available, generally) to do another docs test as well.

I could add a linter Python script that runs after the docs build and checks that the set of filenames in `docs/stubs` is the same size as the set `{f.lower() for f in filenames}`, if we think that's worth it.

**Review by HuangJunye — APPROVED** [review]
LGTM.

**Comment by HuangJunye** [comment]
> It's going to be a little fiddly to enforce that this isn't broken by other PRs in CI, I think, since we only really build the docs on Linux. We don't _need_ the docs to build on anything other than Linux, so I don't think it's worth provisioning a Mac VM (which are less available, generally) to do another docs test as well.
> 
> I could add a linter Python script that runs after the docs build and checks that the set of filenames in `docs/stubs` is the same size as the set `{f.lower() for f in filenames}`, if we think that's worth it.

I am not sure if it's worth it to do this preventatively, but I don't have a strong opinion.

**Review by mtreinish — APPROVED** [review]
This LGTM it's straightforward to fix the name conflict on case insensitive filesystems.

In general I think this should be a sufficiently rare occurrence so we don't need to actively guard against it yet. Mostly because it's a function of the pulse module having everything exist in a flat namespace and this is the first time we've encountered this in the documentation builds so far. I do think your suggestion though of adding a custom python lint script to the docs job is probably the way we would need to enforce this though if we need it in the future.

**Comment by jakelishman** [comment]
Yeah, agreed.  It's trivial to write, but let's just stick it in if it turns out we need it, rather than over-reacting off a single occurrence.

**Pull request merged**
