### PR TITLE
fixed issue 4959 by change text pi with character unicode u03C0

### LINKED ISSUE #4959: Show pi in the text drawer as π
### What is the expected enhancement?

Based on a discussion in #4931, there's interest in displaying pi in the text drawer as `π `instead of `pi`.
``` 
                   ┌─────────┐               ┌─────────┐
Change from   q_0: ┤ RX(pij) ├     to   q_0: ┤ RX(πj)  ├
                   └─────────┘               └─────────┘
```
To do this on all platforms requires completion of #4900 and modifying pi_check and 24 tests.

### PR DESCRIPTION
**Pull request by alejomonbar**
… correspond to pi

### Summary

Fixes #4959 

### Details and comments

Circuit drawn using circuit.draw() when output a pi value just present the text. I used Unicode for plotting pi

### CODE REVIEW

**Review by 1ucian0 — CHANGES_REQUESTED** [review]
That will break some encodings... Have a look to some suggestions in the original issue.

**Comment by alejomonbar** [comment]
> That will break some encodings... Have a look to some suggestions in the original issue.

Luciano I'm having problems trying to execute "make test" in the terminal. Any suggestion why ddt is not installed and I try to install it again but it told me that I already have it.

Screen Shot 2020-10-08 at 9 01 17 AM

**Comment by alejomonbar** [comment]
@1ucian0 Luciano, I was looking at the errors they are caused by the comparison between (see below). Of course, I'm not going to produce the text in the first circuit because I want the second. Can I change the test cases?

["                    ┌──────────┐",
                              "q_0: |0>─────■──────┤ RY(pi/2) ├",
                              "        ┌────┴─────┐└────┬─────┘",
                              "q_1: |0>┤ RY(pi/2) ├─────┼──────",
                              "        └──────────┘     │      ",
                              "q_2: |0>─────────────────■──────",
                              "                                "]

["                    ┌──────────┐",
                              "q_0: |0>─────■──────┤ RY(\u03C0) ├",
                              "        ┌────┴─────┐└────┬─────┘",
                              "q_1: |0>┤ RY(\u03C0/2) ├─────┼──────",
                              "        └──────────┘     │      ",
                              "q_2: |0>─────────────────■──────",
                              "                                "]

**Comment by 1ucian0** [comment]
> Luciano I'm having problems trying to execute "make test" in the terminal. Any suggestion why ddt is not installed and I try to install it again but it told me that I already have it.

Did you `pip install -r requirements-dev.txt`? Have a look to https://qiskit.org/documentation/contributing_to_qiskit.html for further details.

**Comment by alejomonbar** [comment]
> > Luciano I'm having problems trying to execute "make test" in the terminal. Any suggestion why ddt is not installed and I try to install it again but it told me that I already have it.
> 
> Did you `pip install -r requirements-dev.txt`? Have a look to https://qiskit.org/documentation/contributing_to_qiskit.html for further details.

I solved it using tox -epy38. I change almost all the test for drawing that were causing the errors.

**Comment by 1ucian0** [comment]
> "                    ┌──────────┐",
> "q_0: |0>─────■──────┤ RY(\u03C0/2) ├",
> "        ┌────┴─────┐└────┬─────┘",

The encoding of the testing files (and all the files in general) is utf8. You can use `┤ RY(π/2) ├`.

**Pull request closed without merging**
