### PR TITLE
Move API docs for Terra into source

### PR DESCRIPTION
**Pull request by nonhermitian**
### Summary
Moves the API doc files into Terra so that they can be modified locally when source changes.

### Details and comments

Co-authored-by: Matthew Treinish <mtreinish@kortar.org>

### CODE REVIEW

**Comment by mtreinish** [comment]
I definitely support splitting the docs back out to the repo, they never should have been combined into a single repo.

But, I'd rather not add this to our sdist since there isn't any python code in the project we should be able to have the top level `docs/` outside of the sdist and make this work. We can have sphinx just pull the source directly at build time in the meta repo instead of relying on python to find the docs source.

**Comment by nonhermitian** [comment]
Not sure exactly what you are suggesting.  In order for this to work, the meta needs to be installed, and then I need to fetch the rst files for each different element, and provider, from somewhere.

**Comment by nonhermitian** [comment]
I would also like a travis step that builds the docs so that any bugs in the docs can be corrected at the element level.  There are many that need to be addressed.

**Comment by mtreinish** [comment]
The paths to the docs are a known static things we can just pull the rst source from github at a given version for the meta docs in the conf.py over there instead of putting that all in the package. Also, does this actually include the rst files in the sdist without updating the manifest?

**Comment by nonhermitian** [comment]
So I can move the docs outside of the qiskit main.  However I am a bit confused:

If I install all the elements from source and want to build the docs how does that work in your model?

I am sure you know more than I do though, so let me move them to top level.  I am also not sure how to modify https://github.com/Qiskit/qiskit/pull/551 to do what you suggest.

**Comment by mtreinish** [comment]
Well the meta package doesn't really support doing builds at points which are not releases currently because the meta package was kind of only designed to deal with releases. So the docs in the meta assume a specific set of releases of each element. When you say you want to build it with everything installed from source do you mean at a random git checkout from master of the elements or just source builds of the releases. We could support either case, doing everything at releases will just work the same. For the git checkout case it just requires figuring out what the current checkout is to pull the rst at that version which is in `__version__` for source installs for most elements (aer and ibmq being the exceptions).

I can take a spin at modifying https://github.com/Qiskit/qiskit/pull/551 this afternoon or tomorrow to handle docs outside of the sdist.

**Comment by nonhermitian** [comment]
Yeah I guess my concern is that at present I can install from source and build the docs from the meta repo.  If I make a branch, tweak it and install it, the changes will show up in the docs.  How does this work if the docs are top level?  This is why I have the solution I do now.  It always works, at the expense of docs in the source.

**Comment by mtreinish** [comment]
ugh, github sigh. It mishandled the merge commit. I'll rebase to fix this one sec.

**Comment by mtreinish** [comment]
I just made a few changes here, mostly adding a CI job to azure that builds the docs and hosts the output, adding the reno release notes to the docs build, a tox job to make it simpler to build things locally, and updating the CONTRIBUTING.md guide to include the extra details. I think this should be good to go now (holding off on approving because I added myself as a co-author)

**Pull request merged**
