### PR TITLE
Move CONTRIBUTING.rst to top level

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

The CONTRIBUTING.rst doc contains a lot of useful information about the
not only contributing to the project but also some useful information
about project policy and conventions. But it's currently in a hidden
directory so that github ui will show it on a help menu. So unless you
know to click on that help menu or that it's hidding in the .github
directory you'll never see it. This commit addresses this by moving the
file to the repo root so it's more obvious where it is.

### Details and comments

### CODE REVIEW

**Comment by 1ucian0** [comment]
Isn't the current place standard? Does affect the tick in https://github.com/Qiskit/qiskit-terra/community?

**Comment by mtreinish** [comment]
> Isn't the current place standard? Does affect the tick in https://github.com/Qiskit/qiskit-terra/community?

It's not standard if we want people to actually read it outside of github, because they won't know to look for it there (I didn't for example know where it was at first). It doesn't look like it matters if it's in the repo root or .github either, I checked one of my other projects: https://github.com/mtreinish/stestr/community and it's doc is in the repo root: https://github.com/mtreinish/stestr/blob/master/CONTRIBUTING.rst But, regardless I also added a symlink to the old location so it will still show it as being there if it was a requirement.

**Comment by levbishop** [comment]
According to [the github docs](https://help.github.com/en/articles/setting-guidelines-for-repository-contributors), Github looks in repository root, `DOCS/` or `.github`. I am in favour of this patch and no need for the symlink.

Interestingly, [you can also set a organization-wide default](https://help.github.com/en/articles/creating-a-default-community-health-file-for-your-organization) for these community files (code of conduct, etc) in a `Qiskit/.github` repo, where repos without their own local version can fall back to. We should probably use that for at least the code of conduct, if not the contributing etc

**Comment by mtreinish** [comment]
> According to [the github docs](https://help.github.com/en/articles/setting-guidelines-for-repository-contributors), Github looks in repository root, `DOCS/` or `.github`. I am in favour of this patch and no need for the symlink.
> 

Cool, I'll delete the symlink then.

**Comment by jaygambetta** [comment]
Before we do this we need to make sure it’s over the full organization.  We should also change it to md as we are no longer using it in documentation and that way it matches the others

**Comment by mtreinish** [comment]
@jaygambetta Ok, I've pushed up PRs to the other qiskit repos (at least the ones tracked by the meta and the meta itself) and converted all those docs to markdown if they were an restructured text. I'll push up the conversion for terra as part of this PR shortly, but I'd like to land #2562 first, so the conversion doesn't merge conflict with that. (I can just run pandoc to do the conversion after that lands in one go)

**Comment by mtreinish** [comment]
Ok, I've update this PR to now have everything in markdown and also moved the code of conduct along with the contributing doc.

**Pull request merged**
