### PR TITLE
DAGBackend bug. Fixes #1040

### LINKED ISSUE #1040: Compile fails on some composite operations when unrolling to base U gates
### Informations

- **Qiskit Terra version**: 0.6
- **Python version**: 3.7
- **Operating system**: MacOs

### What is the current behavior?

The following circuit fails to compile if basis gates does not include `u2`:

```python
qr = QuantumRegister(3)
cr = ClassicalRegister(3)
circ = QuantumCircuit(qr, cr)

circ.cz(qr[0], qr[1])
circ.ccx(qr[0], qr[1], qr[2])
```

### Steps to reproduce the problem

Unrolling to  `basis_gates='cx'` gives the following error:

```python
qobj = qiskit.compile(circ, backend, basis_gates='cx')
DAGCircuitError: 'U is not in the list of basis operations'
```

Unrolling to basis gates `basis_gates='u2,cx'` 
```python
qobj = qiskit.compile(circ, backend, basis_gates='u2,cx')
qobj.experiments[0].instructions
```
returns the following output:
```python
[QobjItem(name='u2', params=[0.0, 3.141592653589793], qubits=[2], texparams=['0', '\\pi']),
 QobjItem(name='u2', params=[0.0, 3.141592653589793], qubits=[1], texparams=['0', '\\pi']),
 QobjItem(name='cx', params=[], qubits=[0, 1], texparams=[]),
 QobjItem(name='u2', params=[0.0, 3.141592653589793], qubits=[1], texparams=['0', '\\pi']),
 QobjItem(name='cx', params=[], qubits=[1, 2], texparams=[]),
 QobjItem(name='U', params=[0.0, 0.0, -0.7853981633974483], qubits=[2], texparams=['0', '0', '- 0.25 \\pi']),
 QobjItem(name='cx', params=[], qubits=[0, 2], texparams=[]),
 QobjItem(name='U', params=[0.0, 0.0, 0.7853981633974483], qubits=[2], texparams=['0', '0', '0.25 \\pi']),
 QobjItem(name='cx', params=[], qubits=[1, 2], texparams=[]),
 QobjItem(name='U', params=[0.0, 0.0, -0.7853981633974483], qubits=[2], texparams=['0', '0', '- 0.25 \\pi']),
 QobjItem(name='cx', params=[], qubits=[0, 2], texparams=[]),
 QobjItem(name='U', params=[0.0, 0.0, 0.7853981633974483], qubits=[2], texparams=['0', '0', '0.25 \\pi']),
 QobjItem(name='u2', params=[0.0, 3.141592653589793], qubits=[2], texparams=['0', '\\pi']),
 QobjItem(name='U', params=[0.0, 0.0, 0.7853981633974483], qubits=[1], texparams=['0', '0', '0.25 \\pi']),
 QobjItem(name='cx', params=[], qubits=[0, 1], texparams=[]),
 QobjItem(name='U', params=[0.0, 0.0, 0.7853981633974483], qubits=[0], texparams=['0', '0', '0.25 \\pi']),
 QobjItem(name='U', params=[0.0, 0.0, -0.7853981633974483], qubits=[1], texparams=['0', '0', '- 0.25 \\pi']),
 QobjItem(name='cx', params=[], qubits=[0, 1], texparams=[])]
```

Also of note is that either operation alone unrolls fine:

```python
qr = QuantumRegister(3)
cr = ClassicalRegister(3)
circ = QuantumCircuit(qr, cr)
circ.cz(qr[0], qr[1])
qobj = qiskit.compile(circ, backend, basis_gates='cx')
```
returns
```python
[QobjItem(name='U', params=[1.5707963267948966, 0.0, 3.141592653589793], qubits=[1], texparams=['0.5 \\pi', '0', '\\pi']),
 QobjItem(name='cx', params=[], qubits=[0, 1], texparams=[]),
 QobjItem(name='U', params=[1.5707963267948966, 0.0, 3.141592653589793], qubits=[1], texparams=['0.5 \\pi', '0', '\\pi'])]
```
and 

```python
qr = QuantumRegister(3)
cr = ClassicalRegister(3)
circ = QuantumCircuit(qr, cr)
circ.ccx(qr[0], qr[1], qr[2])
qobj = qiskit.compile(circ, backend, basis_gates='cx')
```
returns
```python
[QobjItem(name='U', params=[1.5707963267948966, 0.0, 3.141592653589793], qubits=[2], texparams=['0.5 \\pi', '0', '\\pi']),
 QobjItem(name='cx', params=[], qubits=[1, 2], texparams=[]),
 QobjItem(name='U', params=[0.0, 0.0, -0.7853981633974483], qubits=[2], texparams=['0', '0', '- 0.25 \\pi']),
 QobjItem(name='cx', params=[], qubits=[0, 2], texparams=[]),
 QobjItem(name='U', params=[0.0, 0.0, 0.7853981633974483], qubits=[2], texparams=['0', '0', '0.25 \\pi']),
 QobjItem(name='cx', params=[], qubits=[1, 2], texparams=[]),
 QobjItem(name='U', params=[0.0, 0.0, -0.7853981633974483], qubits=[2], texparams=['0', '0', '- 0.25 \\pi']),
 QobjItem(name='cx', params=[], qubits=[0, 2], texparams=[]),
 QobjItem(name='U', params=[0.0, 0.0, 0.7853981633974483], qubits=[2], texparams=['0', '0', '0.25 \\pi']),
 QobjItem(name='U', params=[1.5707963267948966, 0.0, 3.141592653589793], qubits=[2], texparams=['0.5 \\pi', '0', '\\pi']),
 QobjItem(name='U', params=[0.0, 0.0, 0.7853981633974483], qubits=[1], texparams=['0', '0', '0.25 \\pi']),
 QobjItem(name='cx', params=[], qubits=[0, 1], texparams=[]),
 QobjItem(name='U', params=[0.0, 0.0, 0.7853981633974483], qubits=[0], texparams=['0', '0', '0.25 \\pi']),
 QobjItem(name='U', params=[0.0, 0.0, -0.7853981633974483], qubits=[1], texparams=['0', '0', '- 0.25 \\pi']),
 QobjItem(name='cx', params=[], qubits=[0, 1], texparams=[])]
```

### What is the expected behavior?

The `u2` gates should unroll to `U` gates if `u2` is not in the basis gates string.

### Suggested solutions

Unknown

### PR DESCRIPTION
**Pull request by 1ucian0**
### Summary
The `DAGBackend` modifies `self.basis`, so it should have its own copy. This is the fix for #1040. It was hard to debug... 

(the unroller backend should die a painful death)

### CODE REVIEW

**Comment by 1ucian0** [comment]
Take a look @chriseclectic :)

**Comment by chriseclectic** [comment]
This seems to do the trick!

**Comment by ajavadia** [comment]
Should this fix be applied to other unroller backends as well? I think they may have the same problem (i.e. modify basis).

`_circuitbackend.py`
`_jsonbackend.py`
`_unrollerbackend.py`
`_printerbackend.py`

**Comment by 1ucian0** [comment]
Indeed:
 - `_circuitbackend.py` modifies the basis [here, for example](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/unroll/_circuitbackend.py#L117).
 - `_jsonbackend.py` modifies the basis [here, for example](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/unroll/_jsonbackend.py#L139).
 - `_printerbackend.py` the basis [here, for example](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/unroll/_printerbackend.py#L123).

I was unable to trigger the bug in these situations. But I think is safe to apply the same fix (in 
78e291b). Also, the method `set_basis` should get a copy too (in 546b0fd).

`UnrollerBackend` in `_unrollerbackend.py` is a base class and seems that is not directly affected.

**Pull request merged**
