### PR TITLE
circuit.properties()

### LINKED ISSUE #1088: Return important circuit properties from a QuantumCircuit
### What is the expected enhancement?
It is often of interest to compute several properties of a quantum circuit after compiling to a given device.  For example, # of gates, # of cx-gates, depth, and # of swap gates added, are all properties of interest.  However, only some of these values (# gates, and cx gates) can actually be extracted from the qasm in a qobj, others require going qobj -> circuit -> DAG.  Some, like # of swaps added, cannot be gathered from the given information. These values should be reported in the qobj experiment headers.

### PR DESCRIPTION
**Pull request by ajavadia**
Fixes #1088

### CODE REVIEW

**Comment by jaygambetta** [comment]
As we discussed in slack I would rather have methods. Lets start with that and see if we need a summary later

**Comment by jaygambetta** [comment]
Why not put the test in test/circuits and test of the circuit not the dag since this is where most users will interact and the dag log term will be in the circuit

**Comment by ajavadia** [comment]
yeah i thought about that but then decided to put in dag, because if a test fail, it is really a failure of the dag and not circuit. 
we need to merge circuit and dag and this whole thing will be moot.

**Comment by jaygambetta** [comment]
Ok. 

Also can you edit the quantum circuit notebook in the tutorial. It’s a Pr should these methods.  As this becomes documentation for Qiskit Terra

**Comment by ajavadia** [comment]
@jaygambetta done.

**Pull request merged**
