### PR TITLE
Fix numpy exact eigensolver for 1 qubit op

### LINKED ISSUE #5734: NumPyEigensolver and NumPyMinimumEigensolver return wrong results for 1-qubit operators
### Information

- **Qiskit Terra version**: latest
- **Python version**: 3.8.5
- **Operating system**: Ubuntu 20.04.1

### What is the current behavior?

`NumPyEigensolver` and `NumPyMinimumEigensolver` returns wrong results when 1 qubit operators are given.

### Steps to reproduce the problem

```python
from qiskit.algorithms import NumPyEigensolver, NumPyMinimumEigensolver
from qiskit.opflow import PauliSumOp

def test_exact_eigen(op):
    print(op)
    solver = NumPyMinimumEigensolver()
    print(solver.compute_minimum_eigenvalue(op).eigenvalue)

    solver = NumPyEigensolver(k=2)
    print(solver.compute_eigenvalues(op).eigenvalues)

    solver = NumPyEigensolver(k=1)
    print(solver.compute_eigenvalues(op).eigenvalues)
    print()

op = PauliSumOp.from_list([('XI', 1)])
test_exact_eigen(op)

op = PauliSumOp.from_list([('X', 1)])
test_exact_eigen(op)
```

output:
```
1.0 * XI
(-0.9999999999999999-4.129073125279104e-18j)  # OK
[-1.-1.79927237e-18j -1.-1.41733575e-18j]  # OK
[-1.+2.60286226e-18j]  # OK

1.0 * X
(0.9999999999999996+0j)   # NG, wrong answer, should be -1
[-1.+0.j  1.+0.j]  # OK
[ 1.+0.j -1.+0.j]  # NG, size is not correct, should be an array with size 1
```

### What is the expected behavior?

output:
```
1.0 * XI
(-0.9999999999999999-4.129073125279104e-18j)
[-1.-1.79927237e-18j -1.-1.41733575e-18j]
[-1.+2.60286226e-18j]

1.0 * X
(-1)
[-1.+0.j  1.+0.j]
[-1]
```

### Suggested solutions

There are two reasons as follows.
1. use of numpy.linalg.eig https://github.com/Qiskit/qiskit-terra/blob/f53a4b0bd1c951b6b1ccc3c8c33eec6e9cf3288e/qiskit/algorithms/eigen_solvers/numpy_eigen_solver.py#L120
[The documentations](https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html) says that
> The eigenvalues are not necessarily ordered.

2. the current code does not truncate result with k==1 https://github.com/Qiskit/qiskit-terra/blob/f53a4b0bd1c951b6b1ccc3c8c33eec6e9cf3288e/qiskit/algorithms/eigen_solvers/numpy_eigen_solver.py#L124

I propose to use [`eigh`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.eigh.html) that guarantees the ascending order of results.

### PR DESCRIPTION
**Pull request by t-imamichi**
### Summary

This PR sort the eigenvalues even for 1-qubit operators and adds some unit tests.
If matrices are diagonal, the current code calls `sort` two times to the same array (`sort` and `argsort` to `diag`). This PR fixes it too.

~~Replace `np.linalg.eig` and `scipy.sparse.linalg.eigs` with `np.linalg.eigh` and `scipy.sparse.linalg.eigsh` to obtain a sorted result.~~

Fixes #5734 

### Details and comments

~~The current solver uses `np.linalg.eig`, which does not sort the result. This PR replaces it with `np.linalg.eigh`, which returns a sorted result. The input should be Hermitian to use `np.linalg.eigh`, but I think every opflow operator is Hermitian. If not, I will add a manual sort instead of `np.linalg.eigh`.
This also replace `scipy.sparse.linalg.eigs` with `scipy.sparse.linalg.eigsh` to be consistent with `np.linalg.eigh`~~

References
- https://numpy.org/doc/stable/reference/generated/numpy.linalg.eigh.html
> Returns
> w(…, M) ndarray
> The eigenvalues in ascending order, each repeated according to its multiplicity.
- https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.eigsh.html
> Return eigenvectors (True) in addition to eigenvalues. This value determines the order in which eigenvalues are sorted. 
> The sort order is also dependent on the which variable.
> For which = ‘LM’ or ‘SA’:
> If return_eigenvectors is True, eigenvalues are sorted by algebraic value.

### CODE REVIEW

**Comment by mtreinish** [comment]
It's good to see the numpy eigh function being used we had a lot of trouble with inconsistent results stemming from the LAPACK driver that the scipy version uses by default (see #5263 and #5251).

**Comment by t-imamichi** [comment]
Thank you for your information. In most cases, `scipy.sparse.linalg.eigsh` will be invoked (`k` is usually small). The conventional code uses `scipy.sparse.linalg.eigs` and I don't know any trouble. So, I think `scipy.sparse.linalg.eigsh` works too. But, if anyone has a concern, I'm OK to revert `scipy.sparse.linalg.eigsh`(this PR) to `scipy.sparse.linalg.eigs`(master).

**Comment by nonhermitian** [comment]
The underlying solution method is the same. The difference is in the post processing. The default is six dense vectors to form the Krylov subspace.

**Comment by t-imamichi** [comment]
@woodsp-ibm could you review it?

**Comment by woodsp-ibm** [comment]
> The input should be Hermitian to use np.linalg.eigh, but I think every opflow operator is Hermitian. If not, I will add a manual sort instead of np.linalg.eigh.

Since the matrix operator in opflow, is backed by Terra operator, which has tests to determine if matrix is hermitian or not, symmetric or not, etc I am not sure your assumption holds true. Hence I think we used `eig` when creating it the past as it works for general matrices and did not require them to be symmetric.

**Comment by t-imamichi** [comment]
I think the `MinimumEigenSolver` is expected to return `k` "minimum" eigenvalues as output and the outputs are expected to be real values. Otherwise the term "minimum" might be ambiguous (real part, imaginary part, lexicographically, norm, or something else?). 

I think the current implementation follows the assumption that the eigenvalues are real because it sorts the eigenvalues by real part. `scisparse.linalg.eigs(which='SR')` means sort by real part and `argsort` also sort them lexicographically.

https://github.com/Qiskit/qiskit-terra/blob/a026b627b3462ee116357a7042641cc1c2186af4/qiskit/algorithms/eigen_solvers/numpy_eigen_solver.py#L122-L125

https://numpy.org/doc/stable/reference/generated/numpy.sort.html#numpy.sort
> The sort order for complex numbers is lexicographic.

https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.eigs.html
> ‘SR’ : smallest real part

So, if we allow non-Hermitian matrices, it would be complicated because the eigenvalues are not always real values.

**Comment by t-imamichi** [comment]
I revert `eigh` to `eig` and `eigsh` to `eigs` to keep the consistency with the current output except the incorrect output in the issue #5734

**Comment by woodsp-ibm** [comment]
I know we had the eigenvalues as complex in the output and expected that. I am not sure why they were sorted by by real. Does the sort by magnitude end up losing the sign which would result in an ordering that was not desired and we would not get what we considered to normally be the lowest values? In general yes it was expected the problems that were normally being dealt with, like chemistry, had real eigenvalues but the restriction was not imposed by the code. Later code like chemistry just takes the real part from the eigenvalues.

**Comment by t-imamichi** [comment]
If complex values are expected as eigenvalues, the current code might not make sense because scipy.sparse.linalg.eigs takes care of only the real part. I'm not sure what kind of order of complex-value eigenvalues are expected. Anyways, I reverted my code to use eig and eigs and sort the indices as same as the current code does.

**Comment by woodsp-ibm** [comment]
Ok, thanks. By expected I only meant the application layers get the real part from the eigen values and do not assume its real, but that it could be complex. FYI Opflow also uses complex for expectation values https://github.com/Qiskit/qiskit-terra/issues/5738

Anyway I think its all good, thanks for fixing the issue.

**Review by woodsp-ibm — APPROVED** [review]

**Pull request merged**
