### PR TITLE
Fixed handling of "decimals" parameter by updating format_statevector and format_unitary

### LINKED ISSUE #1062: Remote backend has a wrong result (local simulator has a correct one)
### Informations

- **Qiskit Terra version**: 0.6.0
- **Python version**: 3.6
- **Operating system**: Win64

### What is the current behavior?
I am working with the Bell State programme ([link](https://github.com/Qiskit/qiskit-terra/blob/master/examples/python/hello_quantum.py)).
I found that my local simulator's result was correct, like this:
```
simulation:  COMPLETED
{'00': 514, '11': 510}
```
But when I run it on your backends (the least busy one), which is 'ibmq_16_melbourne', I found the result was wrong:
```
experiment:  COMPLETED
{'00': 575, '01': 31, '10': 43, '11': 375}
```
However, both of them get the same correct quantum circuit.

My code is strictly same with the link, so I do not understand why there is a wrong result from your remote backend.

### What is the expected behavior?
```
simulation:  COMPLETED
{'00': 514, '11': 510}
```
### Suggested solutions
Please help me have a look on the problem. Thank you so much!

### LINKED ISSUE #5428: The "get_statevector" and "get_unitary" methods of the result objects of statevector and unitary simulators seem to ignore the "decimals" parameter
### Informations

- **Qiskit version**: 0.20.1
- **Python version**: The one on the Jupyter server of the IBM Q Experience
- **Operating system**: The one on the Jupyter server of the IBM Q Experience

### What is the current behavior?

The "get_statevector" and "get_unitary" methods of the result objects of statevector and unitary simulators seem to ignore the "decimals" parameter

### Steps to reproduce the problem

%matplotlib inline
# Importing standard Qiskit libraries and configuring account
from qiskit import QuantumCircuit, execute, Aer, IBMQ
from qiskit.compiler import transpile, assemble
from qiskit.tools.jupyter import *
from qiskit.visualization import *
# Loading your IBM Q account(s)
provider = IBMQ.load_account()

circ = QuantumCircuit(1,1)

circ.h(0)

backend = Aer.get_backend('statevector_simulator') 

job = execute(circ, backend) 
result = job.result()  
outputstate = result.get_statevector(circ, decimals=3)
print(outputstate)
outputstate = result.get_statevector(circ, decimals=1)
print(outputstate)
outputstate = result.get_statevector(circ)
print(outputstate)

*****

Something similar happens with the get_unitary method when the unitary simulator is used

### What is the expected behavior?

The number of decimals of the outputstate should be the one used as parameter

### PR DESCRIPTION
**Pull request by sajidanis**
### Summary

Fixes #5428

### Details and comments

The call from result.py for postprocess to format the state vector and unitary matrix having arg of type ndarray and were no postprocessing to be done. Earlier it just return the statevector without any postprocessing. This PR added the postprocessing which handles the decimal argument.

### CODE REVIEW

**Review by kdk — COMMENTED** [review]
Thanks @sajidanis , this fix looks good. Can you add a test and remove the formatting changes from `result.py`?

**Review by kdk — COMMENTED** [review]
Thanks for the update @sajidanis . It looks like there are still some unrelated changes in `result.py`. Also, can you add a test?

**Comment by sajidanis** [comment]
@kdk  Where I have to add a test? Should I have to write in the test package of qiskit-terra or a separate file.

**Comment by sajidanis** [comment]
@kdk Sure will add a test as well. Was busy with quantum challenge.

**Review by kdk — COMMENTED** [review]
Thanks for adding the test @sajidanis . It looks like there are a few lint errors ( https://dev.azure.com/qiskit-ci/qiskit-terra/_build/results?buildId=22059&view=logs&j=7684b0c9-af38-5400-184f-6880bd8a4dd7&t=9d95188b-4e59-58d8-f7c4-3f1fbd4209ad&l=11 ) Looks good otherwise.

**Review by kdk — APPROVED** [review]
Looks good, thanks!

**Review by 1ucian0 — APPROVED** [review]
approving back, after conflict solving

**Pull request merged**
