### PR TITLE
Update default data of mock backends

### LINKED ISSUE #5426: Need mock backend defaults update
### What is the expected enhancement?
Recently we have been making many changes to backend default object (i.e. command def with `ParametricPulse`s, introduction of channel-qubit mapping, etc...), however some of mock backends in terra have not been updated. This outdated some unittests with mock backend, and sometime this makes development (sanity check) harder because of the mismatch of current backend data structure and mocks. We should update those defaults data, and perhaps we need a unittest for the schema version check of mocks.

### PR DESCRIPTION
**Pull request by nkanazawa1989**
### Summary
fix #5426 

### Details and comments
Added reno because some people may use mock to test algorithms, i.e. gate scheduling.

### CODE REVIEW

**Review by mtreinish — COMMENTED** [review]
There are a couple of devices like poughkeepsie and melbourne where the updates may cause issues. For melbourne it's because the number of qubits changes which breaks tests, for poghkeepsie the last data avaible for it before it retired was bad. These both came up in previous updates #4329. Can you remove those devices from the update (I don't think poughkeepsie is in the update list)?

**Comment by nkanazawa1989** [comment]
Thanks. I reverted melbourne files.

**Comment by nkanazawa1989** [comment]
Scheduled circuit test failed due to update of Paris. Is it possible to update the reference gate time of unittest rather than reverting default snapshot of Paris? @mtreinish

**Comment by mtreinish** [comment]
Yeah, if the tests are dependent on a hard coded gate time in the `FakeParis` snapshots we should just update the tests. 
Melbourne is just a special case because it went from 14 qubits to 15 qubits which breaks a lot of the transpiler tests where melbourne is used for the coupling map and its easier to just not change that rather than updating all those tests. But in this case changing the test is easier.

**Comment by nkanazawa1989** [comment]
Thanks. I updated hardcorded reference value and my local test passed.

**Review by mtreinish — APPROVED** [review]

**Pull request merged**
