### PR TITLE
Fix incorrect qargs setting in sabre_swap

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

The sabre swap pass was incorrectly setting a qargs attribute on the op
field of DAGNode objects. This is incorrect because the op fields are
Instruction objects that shouldn't have a qargs attribute. This is
causing issues in other passes that construct Operators on the gates in
a circuit. This mainly comes up in Optimize1qGatesDecomposition where
runs of 1q gates are collected into an operator to be decomposed and
simplified.

### Details and comments

Co-authored-by: Christopher J. Wood <cjwood@us.ibm.com>

### CODE REVIEW

**Review by kdk — COMMENTED** [review]
Can you also fix this in the lookahead pass?

**Comment by mtreinish** [comment]
> Can you also fix this in the lookahead pass?

Done in: https://github.com/Qiskit/qiskit-terra/pull/5749/commits/224e76466bd8cb287fd4795c68f84d8540eb81f6 I didn't realize that lookahead had it too, I just was testing sabre and encountered it.

**Review by ajavadia — APPROVED** [review]

**Review by 1ucian0 — DISMISSED** [review]
Is it possible to write a test failing in master that passes here?

**Comment by mtreinish** [comment]
> Is it possible to write a test failing in master that passes here?

It is a bit weird to test, we either have to run sabre swap on a dag and loop over the op nodes and check for `not hasattr(node.op, 'qargs')` which is a weird case because we normally don't have tests that assert the absence of an attribute on every member of a container type, especially since the negative space for attributes is infinite. The other thing which would provide coverage is too generic and something I assume we'll get for free when the fake backends are updated. Just run a full transpile that runs sabre or lookahead with basis gates set that triggers `Optimize1qGatesDecomposition` to run after. This wasn't caught because we're still running most of our full path transpile tests with the old basis set for ibmq which currently doesn't run the new optimize1q pass (#5554 will change this though)

**Pull request merged**
