### PR TITLE
minor_spelling_mistakes

### PR DESCRIPTION
**Pull request by Aniruddha120**
### Summary

Two misspelled words were edited

### CODE REVIEW

**Comment by Aniruddha120** [comment]
Hello,
You may feel bothered by my email, but I cant resist myself asking it.
Would the code owners mind if I improve the spelling mistakes of the
qiskit(terra, aqua others) if I find them?


Aniruddha Sarkar

**Comment by 1ucian0** [comment]
everybody is welcomed to improve the project!

(btw, I just noticed the *noteble* in this PR, after merging. If you find further mistakes, please also include this one).

**Comment by Aniruddha120** [comment]
Sir,

Thank you for your kind reply. I will sure improve it, if I find any
mistakes further.

Yours faithfully,

Aniruddha Sarkar

**Comment by Aniruddha120** [comment]
> 
> 
> everybody is welcomed to improve the project!
> 
> (btw, I just noticed the _noteble_ in this PR, after merging. If you find further mistakes, please also include this one).

Would you mind , if I ask your email or any social platform where I can discuss something about a development?

**Comment by 1ucian0** [comment]
I'm on slack as `@luciano` and on gitter as `@1ucian0`

**Comment by Aniruddha120** [comment]
> 
> 
> I'm on slack as `@luciano` and on gitter as `@1ucian0`

I just knocked you on slack, you may not seem the notification as you have turned it off.

**Pull request merged**
