### PR TITLE
Use _append when args already converted and broadcast.

### PR DESCRIPTION
**Pull request by kdk**
eecddc4a63205b6fe4b1a631b6a8fb40b442c3a4 was removed from #2824 pending #2826 (see #2824 for profiling data and justification.) Once #2826 merges (and `QuantumCircuit._data` can be assumed to be already validated), this can be re-introduced.

### CODE REVIEW

**Comment by 1ucian0** [comment]
Is this still relevant @kdk ? Still `on hold`?

**Comment by kdk** [comment]
Yes, on hold for #2838.

**Comment by 1ucian0** [comment]
@kdk , #2838 is merged. Still on hold?

**Comment by kdk** [comment]
Ready for review.

**Pull request merged**
