### PR TITLE
Added functionality to update cost dictionary in template substitution

### LINKED ISSUE #5232: Quantum cost of template substitution
### What is the expected enhancement?
Template substitution allows users to identify sub-circuits in a quantum circuit and replace them with equivalent quantum circuits with a lower implementation cost. For example `CNOT(0,1) CNOT(0,1)` is equivalent to the identity `I`. Since the implementation cost of `I` is lower than two CNOT gates this replacement makes sense. 

Currently, the implementation cost of a quantum circuit is evaluated in `TemplateSubstitution._quantum_cost(self, left, right)` in `template_substitution.py`. `_quantum_cost` evaluates the cost using a hard coded `cost_dict` instance. The user should be able to add/remove/modify elements from this dictionary as it is architecture dependent and the user may also whish to add his own gates to it.

`cost_dict` should therefore be an attribute of the `TemplateSubstitution` class that users can access when creating template matching transpiler passes.

### PR DESCRIPTION
**Pull request by born-2learn**
### Summary

Fixed #5232 

### Details and comments

Added `cost_dict` to `__init__` constructor method of `TemplateSubstitution` class and updated the dictionary calls in `_quantum_cost()` with `self` instances.

### CODE REVIEW

**Comment by eggerdj** [comment]
This is looking good. One part that is still missing is the following: users typically interact with `class TemplateOptimization(TransformationPass)` which then calls `TemplateSubstitution`. I.e. it might be necessary to allow as argument to `TemplateOptimization.__init_` an optional user provided cost dict that can be passed to `TemplateSubstitution`

**Comment by eggerdj** [comment]
See here for alternative implementation: https://github.com/Qiskit/qiskit-terra/pull/5521

**Comment by born-2learn** [comment]
Apologies for the delay @eggerdj. Can I complete the PR by this weekend(just after my exams)?

**Comment by eggerdj** [comment]
@born-2learn Sure, you can go and have a look at #5521 which has the needed functionality. Tests are missing in #5521. Perhaps you could start from that code and add a couple of tests?

**Comment by lcapelluto** [comment]
Replaced with https://github.com/Qiskit/qiskit-terra/pull/5521

**Pull request closed without merging**
