### PR TITLE
Parameters in InstructionDurations.

### LINKED ISSUE #7315: Instruction duration is parameter agnostic
## Summary

The class `InstructionDurations` in `qiskit.transpiler.instruction_durations.py` is agnostic to parameter values. This poses problems for gates that have a parameter-dependent duration.

## Details

Instruction durations are created using e.g. the following code:
```python
durations = InstructionDurations(
    [("h", 0, 50), ("cx", [0, 1], 700), ("reset", None, 10),
     ("cx", [1, 2], 200), ("cx", [2, 3], 300),
     ("x", None, 50), ("measure", None, 1000)]
)
```
Here, for each tuple, the first argument is the name of the instruction, the second argument is the qubits it applies to, and the third argument is the duration. The problem with this structure is that it does not have the parameters of the instructions. This is fine for basis gates like `["x", "h", "cx"]` and even `rz(theta)` since it does not have a duration. However, this is not sufficient for cases such as `rzx(theta)` in which the same instruction on the same pair of qubits can have a different duration depending on the parameter `theta`.

## Proposed solution

We can add an additional entry to the tuples in `InstructionDurations` that corresponds to the parameters of the instruction. E.g. `(inst_name, qubits, params, duration)`. This will also better reflect the information of the `QuantumCircuit.calibrations` variable which contains the schedule for a given instruction, qubits, and parameter values of the instruction.

### PR DESCRIPTION
**Pull request by eggerdj**
### Summary

This PR is a draft to fix #7315 .

### Details and comments

The fix is done by adding an optional parameter to the key in `InstructionDurations`. Internally, an extra dictionary `duration_by_name_qubits_params` is added.

TODOs:
- [x] Add tests.

### CODE REVIEW

**Comment by itoko** [comment]
Thank you for taking on this. I know this is still a WIP but I have a comment at this moment.

I strongly recommend you to keep the current interface accepting `(inst_name, qubits, duration)` or `(inst_name, qubits, duration, unit)` and *add* (not replace with) the new interface accepting `(inst_name, qubits, parameters, duration)` or `(inst_name, qubits, parameters, duration, unit)`. If we removed the current interface, it would break not a few existing codes (as you had to add many `None`s in tests).

Suggestions:
```
if not isinstance(items[-1], str):
    inst_durations[i] = (*items, "dt")  # set default unit

if len(items) == 4:  # (inst_name, qubits, duration, unit)
    inst_durations[i] = (*items[:2], None, items[3])

# assert items == (inst_name, qubits, parameters, duration, unit)
if len(items) != 5:  # (inst_name, qubits, duration, parameters, unit)
    raise TranspilerError(
        "Each entry of inst_durations dictionary must be "
        "(inst_name, qubits, duration) or "
        "(inst_name, qubits, duration, unit) or "
        "(inst_name, qubits, parameters, duration) or "
        "(inst_name, qubits, parameters, duration, unit)"
    )
```

**Comment by eggerdj** [comment]
@itoko Thanks for the feedback. Would you mind taking a second look?

**Comment by itoko** [comment]
I ran the newly added test (`test_dd_with_calibrations_with_parameters`) in my local env and noticed that it can be run successfully on the latest main branch (i.e. without this PR). Does this test reflect your original issue? If so, it seems already resolved by the PR #7463. Doesn't #7463 cover this PR? or do you still have any other case such that InstructionDurations should store duration of parameterized gates?

**Comment by itoko** [comment]
Thank you for the update @eggerdj . It looks good to me now. One last point, I'm not sure if float is a safe dict key, given the rounding error. Any suggestions or comments on that point? @mtreinish @jakelishman

**Comment by itoko** [comment]
@eggerdj I'm having second thought. I'm leaning that we don't need to care about rounding errors too much here. In our major use case, we can assume the same person who registers the duration and retrieve it with parameter (float) values. So if the person carefully use the same float values, there would be no problem. Do you think users often want to do maths on parameters after registering with the values (e.g. 1/3) and try to retrieve with the tweaked value (10/3)/10? If not as I expect, I think it would be sufficient to note the fact users must use exactly the same float values for `parameters` in the docstring (I'll approve after the update of the docstring).

**Comment by eggerdj** [comment]
@itoko Sounds good. See here: [df388c7](https://github.com/Qiskit/qiskit-terra/pull/7321/commits/df388c76321d6c8c356e2d1daf3b102a9faf212e)

**Review by itoko — APPROVED** [review]

**Pull request merged**
