### PR TITLE
Speed up schedule()

### PR DESCRIPTION
**Pull request by itoko**
### Summary
Speed up ALAP and ASAP scheduling methods.

### Details and comments
This PR improves the implementation of scheduling algorithms (ALAP and ASAP) without changing their interface. It constructs the resulting Schedule at once in order to avoid useless creation of intermediate Schedules, which made the original schedule() slow.

### CODE REVIEW

**Comment by itoko** [comment]
On hold until the benchmarking work is done as well as #3698.

**Comment by taalexander** [comment]
This makes sense to me that this would result in a speedup. I imagine the improvements could be very tangible. Do you have some temporary benchmarks we could so that we might consider merging this in before the full benchmark suite is ready?

**Comment by itoko** [comment]
Here is the improvement of time taken for schedule() in my local environment by this PR for a RB circuit with `n` Clifford gates. 
```
n=300: 22.656 seconds -> 0.937 seconds
n=200: 9.015 seconds -> 0.567 seconds
n=100: 2.076 seconds -> 0.282 seconds
```
We can see more improvements for deeper circuits as expected.

Benchmark code:
```
import numpy as np
from qiskit import transpile, schedule
from qiskit.ignis.verification import randomized_benchmarking as rb
from qiskit.test.mock.fake_openpulse_2q import FakeOpenPulse2Q

np.random.seed(10)
backend = FakeOpenPulse2Q()
rb_opts = {
    'length_vector': [n],
    'nseeds': 1,
    'rb_pattern': [[0, 1]]
}
rb_circs, xdata = rb.randomized_benchmarking_seq(**rb_opts)

qc_transpile = transpile(rb_circs[0], backend)

# measure the time taken only for schedule()
sched = schedule(qc_transpile, backend)
```
(Note: Please regard those circuits as random circuits for benchmark rather than RB circuits.)

**Comment by itoko** [comment]
One more thing: This fix #3678 as a by-product.

**Comment by taalexander** [comment]
Yes, I agree this is a significant improvement! I will review this ASAP.

**Pull request merged**
