### PR TITLE
Properly check if connection can be established for importing interactive visualizations

### LINKED ISSUE #895: Loading Qiskit with no internet results in a ConnectionError
### What is the current behavior?
Loading Qiskit with no Internet results in a `ConnectionError`.

### Steps to reproduce the problem
Run Qiskit without Internet connection.

### What is the expected behavior?
Qiskit prompt no error at all.

### PR DESCRIPTION
**Pull request by nonhermitian**
Fix #895

### Summary
As pointed out by @chriseclectic , loading qiskit with no internet connection results in a `ConnectionError` because the interactive visualizations max out the number of attempts to look for the needed host url.  Here we replace the previous check with on that gracefully exits if no connection can be established.

### CODE REVIEW

**Comment by delapuente** [comment]
Please, remember to file an issue and link the PR with it by adding "Fix <issuenumber>".

**Comment by diego-plan9** [comment]
Can you remember to remove `requests` as a dependency, as the only place where it was used is now replaced by a standard library call (which I think is a good move)?

**Comment by diego-plan9** [comment]
Also, perhaps we could take the chance to reevaluate the need for the
```
from qiskit.tools.visualization import (circuit_drawer, plot_histogram)
```

line from the main `qiskit/__init__.py`, in the spirit of @ajavadia's comment at https://github.com/Qiskit/qiskit-terra/pull/890#issuecomment-420779587?

Our top-level `qiskit` namespace and `import qiskit` is already more complicated and full of implications than ideal, and importing a member of `qiskit.tools` there entangles (no pun intended) it even more, which has been the root cause of two user-facing bugs (#895 and #889) already since it was introduced. Any thoughts?

**Comment by nonhermitian** [comment]
Actually the bug fixed here was caught becuase of the top level visualization imports. They were not the cause. Anytime someone loaded the visualization module, the same issue would pop up.

**Comment by nonhermitian** [comment]
The function added here could also be useful for having a more graceful error message if the register function cannot connect to the host urls.

**Pull request merged**
