### PR TITLE
equivalence of toffoli in terms of cx and sqrt(cx)

### PR DESCRIPTION
**Pull request by ajavadia**
an example that can be a use case for backendV2 and its compiler support.

ccx can be written as 2 cx and 3 csx (which is better than only if cx was available)

cx and csx can also be written as rzx(pi/2) and rzx(pi/4) respectively.

so in principle the basis translator should be able to rewrite ccx in terms of rzx(pi/2) and rzx(pi/4) if that's the instruction set that the backend has.

### CODE REVIEW

**Comment by ajavadia** [comment]
I hope there is a test that checks all additions to the standard equivalence library are correct

**Comment by ajavadia** [comment]
> I hope there is a test that checks all additions to the standard equivalence library are correct

yep, and it caught my off-by-global-phase error.

**Review by jakelishman — APPROVED** [review]
This looks straightforwards, and the equivalences look right now in local testing.

I think we're ok without a changelog, unless we normally put one in for additional equivalences?

**Comment by ShellyGarion** [comment]
Are there any other equivalences in the equivalence library that can be written more efficiently with a csx gate?

**Comment by ajavadia** [comment]
> I think we're ok without a changelog, unless we normally put one in for additional equivalences?

I think we are ok without one too.

> Are there any other equivalences in the equivalence library (or that we should add to it) that can be written more efficiently with a csx gate?

This can be extended to multi-controlled toffolis, see pg 17 of barenco https://arxiv.org/pdf/quant-ph/9503016.pdf
Something to add as an enhancement. The XX decomposer is perhaps more useful for leveraging fractional gates, since it can be used to synthesize infinite operations. But it cannot act beyond 2-qubit gates, so I think both have their place.

**Pull request merged**
