### PR TITLE
text drawing unitary gates

### LINKED ISSUE #2234: text drawer: long params should not print
<!-- ⚠️ If you do not respect this template, your issue will be closed -->
<!-- ⚠️ Make sure to browse the opened and closed issues to confirm this idea does not exist. -->

### What is the expected enhancement?
Some gates have very long params, for example a Unitary gate with a big matrix as its param. In this case we should just print the gate name (e.g. "unitary"). I think we should have an upper bound on the length of param that gets printed.

```python
from qiskit import QuantumRegister, QuantumCircuit
from qiskit.quantum_info.random import random_unitary
qr = QuantumRegister(2)
qc = QuantumCircuit(qr)
U1 = random_unitary(4)
qc.append(U2, [qr[0], qr[1]])
qc.draw(output='text', line_length=1000)
```

```
          ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
q41_0: |0>┤0                                                                                                                                                                                                                                                                                                                                                                                                                              ├
          │  unitary([[-0.3794878 -0.78729597j  0.27032976-0.01244361j -0.14796288-0.12451722j
  -0.33736711-0.10819849j]
 [-0.00417172+0.0353919j  -0.2500359 +0.25555567j  0.21747781+0.67564305j
  -0.55307508-0.24742917j]
 [ 0.08379332-0.27677401j -0.6132419 -0.64069463j  0.326534  -0.0859802j
  -0.06256294+0.10903404j]
 [-0.32374365-0.21552018j  0.08981208+0.06571817j  0.48386387+0.33267255j
   0.66896473-0.20987362j]]) │
q41_1: |0>┤1                                                                                                                                                                                                                                                                                                                                                                                                                              ├
          └───────────────────────────────────────────────────────────────────────────────────────────
```

should instead be:
![image](https://user-images.githubusercontent.com/8622381/56902341-169c5d00-6a68-11e9-8243-4a956c17cf46.png)

### PR DESCRIPTION
**Pull request by 1ucian0**
Fixes #2234 

Unitary gate should not print the parameters when text-drawed.

### CODE REVIEW

**Comment by chriseclectic** [comment]
There are a couple of other instructions that use matrix params (eg expectation value Snapshots, Kraus, multiplexer), so would it be possible instead to do a check of param type before displaying so this fix can apply to those aswell? Something like if any params are not `(str, float, int)` etc don't display them and just print the instruction name in the box?

**Comment by 1ucian0** [comment]
Can I have a snippet for each example?

**Comment by chriseclectic** [comment]
Try:

```python
import numpy as np
from qiskit import *
from qiskit.quantum_info.operators import *

# Error channel: (1-p)*II + p*ZZ
error = SuperOp(0.75 * np.eye(4) + 0.25 * np.diag([1, -1, -1, 1])) 

qr = QuantumRegister(1)
cr = ClassicalRegister(1)
circ = QuantumCircuit(qr, cr)
circ.append(error, [qr[0]])
print(circ)
```

which at the moment displays
```python
 »
q6_0: |0>»
         »
 c6_0: 0 »
         »
«      ┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
«q6_0: ┤ Kraus([[ 0.5+0.j  0. +0.j]
 [ 0. +0.j -0.5+0.j]],[[-0.8660254-0.j  0.       +0.j]
 [ 0.       +0.j -0.8660254+0.j]]) ├
«      └──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
«c6_0: ════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
«                                                                                                                              
```

**Comment by chriseclectic** [comment]
Here is one for the multiplexer example (which is still in development):

```python
import numpy as np
from qiskit import *
from qiskit.circuit import Gate
from qiskit.quantum_info.operators import *

cx_multiplexer = Gate('multiplexer', 2, [np.eye(2), np.array([[0, 1], [1, 0]])])

qr = QuantumRegister(2)
circ = QuantumCircuit(qr)
circ.append(cx_multiplexer, [qr[0], qr[1]])
print(circ)
         ┌─────────────────────────────────────────────────┐
q8_0: |0>┤0                                                ├
         │  multiplexer([[1. 0.]
 [0. 1.]],[[0 1]
 [1 0]]) │
q8_1: |0>┤1                                                ├
         └─────────────────────────────────────────────────┘
```

**Comment by 1ucian0** [comment]
Thanks! I will just avoid printing params when they are ndarrays. That makes sense @ajavadia ?

**Comment by ajavadia** [comment]
@1ucian0 Yeah that's fine for now, thanks.

**Pull request merged**
