### PR TITLE
Transition Visualization: defer matplotlib import

### PR DESCRIPTION
**Pull request by drewrisinger**
### Summary

As laid out in https://github.com/Qiskit/qiskit-terra/issues/5100,
``qiskit.visualization.transition_visualization`` is on the critical
path for any ``qiskit`` import. This means that the imports in this file
will always be imported. Profiling of import time showed that
``matplotlib.animation`` was a slow import, and so should be deferred
from the critical path.

### Details and comments

Ref #5100 

Moved after ``HAS_MATPLOTLIB`` check to be reasonably sure that matplotlib & the animation module is installed.

### CODE REVIEW

**Comment by drewrisinger** [comment]
Follow-up from comment https://github.com/Qiskit/qiskit-terra/issues/5100#issuecomment-696702010 @mtreinish

**Review by mtreinish — COMMENTED** [review]
How about moving the entire `try` `except` `HAS_MATPLOTLIB` block to run time imports. While it won't make a difference in import time now it is the direction we want to move things slowly. We can just get it done here first.

**Comment by drewrisinger** [comment]
I don't know if you're planning on releasing another point release for ``0.15``, but this would probably be able to be backported.

**Comment by mtreinish** [comment]
> I don't know if you're planning on releasing another point release for `0.15`, but this would probably be able to be backported.

We weren't planning on pushing a 0.15.3. Mostly because we were hoping to push out a 0.16.0 this week, although looking at the open issues targeting 0.16.0 it will probably be next week.

**Review by mtreinish — APPROVED** [review]

**Review by kdk — APPROVED** [review]

**Pull request merged**
