### PR TITLE
Allow more plotting styles when plotting on the bloch sphere

### PR DESCRIPTION
**Pull request by smturro2**
### Summary
Added different style to plot the vector on the bloch sphere. Originally users could only plot a vector, now they can plot it
using a point or any string they want.

### Details and comments
I included the ability to plot the states using any strings so users could plot the point using "X" or "*" as a symbol. When plotting multiple states on the Bloch sphere this could be useful for identify the different states.
image
This is what the output looks like when using "X" as the style. This state is a 3 qubit system with the first doing being in the bell state and a separable third state that went through a rotation around x

### CODE REVIEW

**Comment by smturro2** [comment]
Is there anything else I can help with to expedite the merge process?

**Comment by poig** [comment]
@smturro2 Hi, can you tick the "allow edits by maintainers", I want to make some commit to this pr, thank you.

**Comment by javabster** [comment]
Hi @smturro2 so sorry for the slow reply, as this PR was not attached to an existing issue it seems to have gotten lost in our PR backlog.

If you are still interested in working on this I'd like to ask if you could give a bit more detail about what value this is adding for the user? Also please add a release note 😄

**Comment by poig** [comment]
Hi @smturro2 , this is related to what I did in #8202 so if you are still interested to continue working on this, recommend just combining my pr code with yours, I didn't do it yet without your announcement.

Hi @javabster , so you can take a look at my issue, link to pr, so basically this is extending the Bloch drawer to the options argument from [`FancyArrowPatch`](https://matplotlib.org/stable/api/_as_gen/matplotlib.patches.FancyArrowPatch.html).

**Comment by javabster** [comment]
closing this PR as original contributor is unresponsive, we can reopen at a later date if they return 😃

**Pull request closed without merging**
