### PR TITLE
fixed issue 4179 by updating matplotlib text scaling

### PR DESCRIPTION
**Pull request by metacubestormerxii12**
### Summary
Fixes issue #4179 

### Details and comments
Multiplied the outputted font size by the self._scale and removed variable DEFAULT_SCALE altogether(4.3). There was only one instance where the scale parameter was used previously so removing DEFAULT_SCALE was much more efficient than dividing by 4.3 every line that I added in "scale._self * <rest of equation>".

### CODE REVIEW

**Comment by 1ucian0** [comment]
MPL circuit drawer issues are piling up, since we dont have a good way to track changes on it. I'm putting this PR `on hold` (meaning "do not merge yet") until https://github.com/Qiskit/qiskit-terra/pull/4544 (or a similar solution) gets in.

**Comment by metacubestormerxii12** [comment]
Ok gotcha. I can see that there are many issues piling up.

**Comment by 1ucian0** [comment]
#4544 is merged... Let's add a test with the new method!

I will try helping, but fill free to do it yourself and ask me if any question.

**Comment by metacubestormerxii12** [comment]
I had to write some important school work yesterday. Ill be able to work on it today

**Comment by metacubestormerxii12** [comment]
My bad, meant to just do a regular comment

**Comment by metacubestormerxii12** [comment]
I'm getting the following error when I start the checks. Is this where it is supposed to automatically access the binder or am I supposed to manually go to it and run it?

**Comment by 1ucian0** [comment]
I moved `test_conditional` to the new testing style in 8b88f1c84.

**Comment by 1ucian0** [comment]
I moved `test_plot_barriers` to the new testing style in 762e9ccc6.

**Pull request merged**
