### PR TITLE
Fix qpy import of circuit with StatePreparation

### LINKED ISSUE #8297: qpy import of circuit with StatePreparation fails
### Environment

- **Qiskit Terra version**: 0.21.0
- **Python version**: 3.8.9
- **Operating system**: macOS (M1)
- Qiskit version 0.37.0

### What is happening?

When reimporting a simple circuit containing a StatePreparation with `qiskit.qpy`, one gets the error `qiskit.exceptions.QiskitError: 'The num_qubits parameter to StatePreparation should only be used when params is an integer'`.

### How can we reproduce the issue?

Minimal example:
```
#!/usr/bin/python3
import qiskit
import qiskit.qpy
print(qiskit.__qiskit_version__)
qc = qiskit.QuantumCircuit(1)
qc.prepare_state([0,1], [0])
with open("tmp.qpy", "wb") as file:
    qiskit.qpy.dump(qc, file)
with open("tmp.qpy", "rb") as file:
    new_qc = qiskit.qpy.load(file)
#qiskit.exceptions.QiskitError: 'The num_qubits parameter to StatePreparation should only be used when params is an integer'
```

### What should happen?

Reimporting a circuit with qiskit.qpy should be possible.

### Any suggestions?

_No response_

### PR DESCRIPTION
**Pull request by king-p3nguin**
### Summary
- Resolve #8297

### CODE REVIEW

**Review by jakelishman — COMMENTED** [review]
Thanks for this!  Please could you also add a test of this in `test/python/circuit/test_circuit_load_from_qpy.py` - there's a similar-ish test on line 596 called `test_initialize` that it can go near.

**Comment by king-p3nguin** [comment]
Thank you for the review! I added a new test.

**Review by jakelishman — APPROVED** [review]
Ace, thanks for the test and the fix!

**Comment by 1ucian0** [comment]
@mergigyio refresh

**Comment by 1ucian0** [comment]
@mergifyio refresh

**Pull request merged**
