### PR TITLE
Fixing the tools for plotting Pauli vec

### PR DESCRIPTION
**Pull request by jaygambetta**
### Summary
I am not sure where we lost a dimensional factor in the plotting of the state in the Pauli vec. Added it back in and made a quick test for the future.

### CODE REVIEW

**Comment by mtreinish** [comment]
The image tests actually upload the results in a tarball you can [download](https://dev.azure.com/qiskit-ci/b6f351e4-6a09-4bf6-b029-4b7806a7bde7/_apis/build/builds/48802/artifacts?artifactName=image_test_failure_img_diffs&api-version=7.0&%24format=zip) in this case. The image file it generated was:

paulivec

you can just drop that image in https://github.com/Qiskit/qiskit-terra/tree/main/test/visual/mpl/graph/references and that should fix the failure.

**Comment by Cryoris** [comment]
Upon running the test with your local modifications, the graph output is stored in `<local-qiskit-terra-folder>/test/visual/mpl/graph/graph_results/paulivec.png`. Just copying this into the `../references` subfolder should get the test to run.

It seems the visualization uses the definition of the Pauli vector $\vec n$ such that the plotted state $\rho$ is constructed as 

$$
\rho = \vec n \cdot \vec\sigma = \sum_i n_i \sigma_i,
$$

which implies that the Pauli vector coefficients are 

$$
n_i = \frac{1}{2} \mathrm{Tr}(\rho\sigma_i).
$$

The example in the test is constructing plotting the Pauli vector for the $|1\rangle$ state, so with this defintion

$$
\rho = |1\rangle\langle 1| = \begin{pmatrix} 0 & 0 \newline 0 & 1 \end{pmatrix} = \frac{1}{2} (I - Z) \Rightarrow \vec n = \begin{pmatrix} 0.5 \newline 0 \newline 0 \newline -0.5 \end{pmatrix}.
$$

Could this additional factor of 1/2 in the inner product could cause the discrepancy in what you were expecting?

**Comment by jaygambetta** [comment]
The standard definition is 


\rho = 1/d \sum_I x_I P_I

so that x_I = trace[P_I rho] and for a single qubit the coefficients are x, y and z which are the Bloch vectors and for stabilizers states the coefficients have a value of 1. I think we defined it for the first time in this paper 0908.1955.

**Comment by jaygambetta** [comment]
please feel free to add. I also think it might be better to add this as a method to statevector rather than a hidden function if you want to use it. It is exponential but useful.

**Comment by Cryoris** [comment]
Docstring is updated in bdfd094 👍🏻 

It's actually already possible to call the paulivec plot from the statevector class via `Statevector(...).draw("paulivec")`. [That draw method](https://qiskit.org/documentation/stubs/qiskit.quantum_info.Statevector.html#qiskit.quantum_info.Statevector.draw) supports also all other plot methods, maybe it would be nice to highlight this in a tutorial or the class docstring.

**Pull request merged**
