### PR TITLE
Implementing circuit.qiskit_code()

### PR DESCRIPTION
**Pull request by rfclambert**
### Summary

As mentionned in #2809 , it could be usefull to have a circuit return its own code. I did an implementation of this in the form of the `circuit.qiskit_code()` method. 

### Details and comments

I mostly adapted the code from the qasm generator (`circuit.qasm()`), and added a support for unitaries. I hope the choice for the name (`qiskit_code()`) is correct, I wasn't sure how to name the method. I added a testfile for it, which I hope is efficient at testing the different ways a Quantum Circuit can be defined.

### CODE REVIEW

**Comment by 1ucian0** [comment]
We have to be very careful with this feature, because it messes up with the python namespace.

```python
qr = QuantumRegister(2, 'q%') 
circuit = QuantumCircuit(qr)                                                                              
print(circuit.qiskit_code())

q% = QuantumRegister(2, 'q%')
qc = QuantumCircuit(q%)
```

```python
qr = QuantumRegister(2, 'qc')
circuit = QuantumCircuit(qr)
circuit.h(qr[0])
print(circuit.qiskit_code())

qc = QuantumRegister(2, 'qc')
qc = QuantumCircuit(qc)
qc.h(qc[0])
```

**Comment by nonhermitian** [comment]
@1ucian0 I am not sure what the concern here is as we are just printing text of the circuit.

I think this is looking good so far.  I think the unitary matrices should be above the circuit code so that it is clear the separate pieces.

I think we also need to do some truncation of things like `0.0300000` and so on, and probably use the `pi_check` function here (after I update to return things like `3*pi/2` rather than `3pi/2`).

There are also probably some other corner cases somewhere, but I need time to play with this more.  However, this is cool, saves tons of time.

**Comment by 1ucian0** [comment]
> @1ucian0 I am not sure what the concern here is as we are just printing text of the circuit.

I agree that a way to serialize a circuit is needed. But, if I understand correctly, this is more than just printing text of the circuit. The output should be valid python code, right?

**Comment by nonhermitian** [comment]
Yes, It should be something that I could copy and paste and have it run.  I guess you are thinking about overwriting names when I execute that code somewhere.  However, this is more of a convenience function rather than something you would use in a script somewhere.  We could be a bit more careful about the names though to minimize the overlap with canonical naming conventions.

**Comment by rfclambert** [comment]
You're right, I think it could lead to issuesif we just use the names like that. I will try to better format the names to prevent this kind of unwanted behaviour.

**Comment by rfclambert** [comment]
I have one remaining issue with the names: what I did was to add a prefix to the circuit name, different from the prefix for registers name. And, if the name wasn't a proper identifier,we filter the non-alphanumerical characters. But there is still one problem, and I think this simple prefix and filtering approach won't work for that: if we give the same name to two registers, but with different non-alphanumerical characters (for example `qr1~` and `qr1%`), then it will be transformed into the same name...

And for the troncature of paramters, I wondered if just doing `str(float(param))` would work, or is there a way for a parametter to be impossible to transform to a float? (so `float(param)` would raise an error)

**Comment by 1ucian0** [comment]
I brought this issue into discussion and there is consensus that this feature will be very hard to maintain and there are standard ways to move objects. The discussion is happening in #2809. 

Closing this PR until the issue is agreed on how to solve it.

**Pull request closed without merging**
