### PR TITLE
Aer ibmq except import error 3613

### PR DESCRIPTION
**Pull request by jwoehr**
### Summary
Address #3613 and change `try  ... except` to `if ... else` in qiskit terra `__init.py__`

### CODE REVIEW

**Comment by jwoehr** [comment]
Is the Linter fail bogus?

**Comment by jwoehr** [comment]
```
qiskit/__init__.py:53:4: E0611: No name 'aer' in module 'qiskit.providers' (no-name-in-module)
qiskit/__init__.py:53:4: E0401: Unable to import 'qiskit.providers.aer' (import-error)
```
What's wrong here?

**Comment by kdk** [comment]
> ```
> qiskit/__init__.py:53:4: E0611: No name 'aer' in module 'qiskit.providers' (no-name-in-module)
> qiskit/__init__.py:53:4: E0401: Unable to import 'qiskit.providers.aer' (import-error)
> ```
> 
> What's wrong here?

At a guess, pylint might check if its within a `try/except ImportError` block before checking if an import error should be raised. In any case, since we're validating for aer/ibmq before the import, it should be okay to silence these.

**Comment by jwoehr** [comment]
> In any case, since we're validating for aer/ibmq before the import, it should be okay to silence these.

Okay, wasn't sure if that was Naughty or Nice :) I'll get on it later tonight, thanks, @kdk

**Comment by jwoehr** [comment]
Whee! It passed.

**Comment by kdk** [comment]
Given @mtreinish 's comment above, I'm going to close this. Given the complications around namespace packaging and the possibility of breaking environments, I don't think the problem solved here is worth the added risk. Thanks for your work on this @jwoehr .

**Pull request closed without merging**
