### PR TITLE
Add support for backend.run to FakeBackend

### LINKED ISSUE #3194: enhance fake backends for testing
`qiskit/test/mock` contains a fake provider, a fake job and several fake IBMQ backends with configuration and noise properties. This can be used for easier local testing.

We need to make the `backend.run()` method of these to actually run the simulations using BasicAer and give back the result. Ideally I'd like to run Aer with noise simulation, but that would introduce a dependency of Terra to Aer.

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

Currently we have many FakeBackend classes which contain snapshots of
real device parameters from the actuall IBM Quantum devices. These
contain all the necessary information to simulate a circuit with a noise
model. However, these fake backends did not implement a run() method if
you went to execute a circuit with a fake backend it would return a fake
job and no result. This commit addresses this by adding a real
implementation of the run() method on the FakeBackend class that will
run the input qobj on Aer with noise if it's available. If Aer is not
installed then basic aer will be used (which doesn't support noise). To
make this clear a warning is raised indicating that BasicAer is being
used to indicate this to the user.

### Details and comments

Fixes #3194

### CODE REVIEW

**Comment by mtreinish** [comment]
The only thing I wasn't sure about here was the FakeJob class. With this change it is no longer used anywhere. A follow on here might be to deprecate it for eventual removal, but it might be useful somewhere for testing something.

**Comment by nonhermitian** [comment]
But why not have Aer instantiate these as simulators using configurable backends?  I think @cjwood already has some of this implemented.

**Comment by mtreinish** [comment]
> But why not have Aer instantiate these as simulators using configurable backends? I think @cjwood already has some of this implemented.

I didn't think there were pieces in place to have configurable backends like that yet. This was just the best way to add support to the existing backend classes with the existing model of things

**Comment by chriseclectic** [comment]
I agree with Pauli, having a mock backend importing a simulator behind the scenes seems messy. It would be better to just initialize a configurable simulator from the backend (or backend config). 

This is already done with the noise model in Aer, all that remains is making the backends themselves configurable to store a noise model which I had an on-hold working version of in `Aer PR [486](https://github.com/Qiskit/qiskit-aer/pull/). 

I can go back to cleaning that up after our next patch release but had it left on hold wiating to see what IBMQ provider had planned regarding configurable backends.

**Comment by mtreinish** [comment]
So maybe I'm missing something but how does making configurable backends in Aer help here. The whole point of these classes are to provide a backend class that behaves the same as real devices but don't require any external dependencies. The only way these classes don't work currently is the run method returns any empty result. All this PR is trying to do is give us a way to run something simple like:

```
from qiskit import *
from qiskit.test import mock

backend = mock.FakeSingapore()
circ = QuantumCircuit(2)
circ.h(0)
circ.cx(0, 1)
circ.measure_all()

execute(circ, backend).result().get_counts()
```
give a reasonable result instead of waiting a predetermined amount of time and returning an empty list. Right now if I want this functionality I need to run:
```
from qiskit import *
from qiskit.test import mock
from qiskit import Aer
from qiskit.providers.aer import noise

backend = mock.FakeSingapore()
circ = QuantumCircuit(2)
circ.h(0)
circ.cx(0, 1)
circ.measure_all()
tcirc = transpile(circ, backend)
qobj = assemble(tcirc, backend)
sim = Aer.get_backend('qasm_simulator')
noise_model = noise.NoiseModel.from_backend(backend)
sim.run(qobj, noise_model).result().get_counts()
```
or
```
from qiskit import *
from qiskit.test import mock
from qiskit.providers.basicaer import BasicAer
backend = mock.FakeSingapore()
circ = QuantumCircuit(2)
circ.h(0)
circ.cx(0, 1)
circ.measure_all()
tcirc = transpile(circ, backend)
qobj = assemble(tcirc, backend)
sim = BasicAer.get_backend('qasm_simulator')
sim.run(qobj, noise_model).result().get_counts()
```

which is what you to do now if you want to run the circuit with a fake backend. The idea is not to provide the full feature set of aer which is still available if you call it directly but just have the existing objects look a bit more like the real devices so they can be used more easily and for testing all of terra, not just the parts which don't require a result.

If we changed these classes to be Aer backends this would add a hard coupling on Aer which defeats the purpose of having them since that would introduce an external dependency. These classes are used for testing in places where just terra is installed currently, and while you don't get the noise model for a better simulation if aer isn't installed and it falls back to basicaer, it still would be able to give you something. The only way I could see this working with that constraint is if by configurable backend you mean we pass Aer the backend object and it runs with it, something like:

```
from qiskit.providers import aer

backend = mock.FakeSingapore()
sim = aer.QasmBackend()
sim.copy_config_from_backend(backend)
sim.run(qobj)
```

But that's just a few lines different from what is in there now, and looking at Qiskit/qiskit-aer#486 that's not this.

The other problem here is that since these are supposed to mock real backends they support either circuit or schedule jobs (for devices that have the properties). The aer backends (even if they were configurable) for pulse and qasm simulators are different classes so we couldn't easily subclass these for devices which support pulse.

**Comment by ajavadia** [comment]
Yeah the point of `FakeBackend`s is to be able to mock the real devices without actual API access, for example if I want to see how circuits get transpiled for them, simulate them with noise models derived from real parameters, etc. 

Perhaps you mean you want the user to do:
```
backend = mock.FakeSingapore()

# circuit 
noise_model = NoiseModel.from_backend(backend)
sim = aer.QasmSimulator(noise_model=noise_model)
sim.run(circuit)

# pulse schedule
hamiltonian = Hamiltonian.from_backend(backend)
sim = aer.PulseSimulator(hamiltonian=hamiltonian, noise_model=noise_model)
sim.run(schedule)
```

This doesn't work now, but once it does I think the implementation here can be changed to do just this. But `fake_backend.run()` makes the FakeBackends behave like normal backends and saves you some extra lines of configuring Aer.

**Comment by nonhermitian** [comment]
If the fake backends are now being used for more than just testing, should they not be moved somewhere more relevant?

**Comment by ajavadia** [comment]
I’m fine moving them elsewhere. Maybe qiskit.mock, with proper deprecation.

**Comment by mtreinish** [comment]
> Looks good, can you add a release note?

Added in https://github.com/Qiskit/qiskit-terra/pull/3890/commits/d7b5ef5d256f59d394e7045944025f27198fe9a2

**Comment by chriseclectic** [comment]
@ajavadia what you posted should already work now (minus a bug or two).

@mtreinish the point of configurable simulators would mean what you posted would be to do it as the following:

```
from qiskit import *
from qiskit.test import mock
from qiskit.providers.aer import QasmSimulator

backend = mock.FakeSingapore()
sim = QasmSimulator.from_backend(backend)
circuit = ...
job = execute(circuit, sim)
```

**Pull request merged**
