### PR TITLE
Update transpiler documentation of instruction_durations

### LINKED ISSUE #6667: Setting instruction duration in transpile seems to do nothing.
### Information

- **Qiskit Terra version**: latest
- **Python version**:
- **Operating system**:

### What is the current behavior?
```python

qc = QuantumCircuit(1)
qc.x(0)
qc.measure_all()

trans_qc = transpile(qc, backend, instruction_durations=[('x', [0], 100000000000000)] )
```
should take forever to run but it does not.

### What is the expected behavior?
I have not seen this feature before, but if it does what it says,

https://qiskit.org/documentation/stubs/qiskit.compiler.transpile.html#qiskit-compiler-transpile

 I should be able to modify the duration of instructions.  Perhaps this is for pulses only, and the documentation just does not spell this out?

### PR DESCRIPTION
**Pull request by Kovi11Day**
### Summary
Fixes #6667

When the `transpile()` function is provided with the `instruction_durations` argument and no `scheduling_method` argument is specified, the behaviour before update is to ignore the `instruction_durations` argument and not apply any scheduling pass.

After the update, the behaviour is to apply scheduling pass with the default scheduling method: `as_late_as_possible`.

### Details and comments
Add condition in `qiskit.compiler.transpiler`: if `scheduling_method` is not provided and `instruction_durations` argument specified, set `scheduling_method=as_late_as_possible`.
Note that the `as_late_as_possible` scheduling method was chosen as it is the one applied by default by the scheduler when no method is specified. This scheduling method improves the outcome fidelity over the `as_soon_as_possible` scheduling method.

### CODE REVIEW

**Review by jakelishman — COMMENTED** [review]
Thank you for looking at this!  Your solution certainly does what you'd set out to do, and it does solve the problem in the initial PR.  It's also good that you were consistent and used the same as the default scheduling method elsewhere.

However, I do wonder if we would be better handling the defaults slightly closer to `PassManager`, rather than here. We expose the presets `level_[0-3]_pass_manager` publically (which are used within `transpile`), and I'd probably expect those presets to include deciding on a default scheduling method if it's appropriate as well; they also read `instruction_durations` from `PassManagerConfig`.  This is slightly out of my wheelhouse, though, so I'll also check with @ajavadia for his opinion.

**Comment by Kovi11Day** [comment]
Thank you very much for reviewing my code.


Indeed, I understand your point about the presets being exposed publicly and therefore also requiring a default scheduling method. I would like some guidance before I proceed.


To include a default scheduling method in the presets, I could add a condition in `level_[0-3]_pass_manager()` which would be similar to the current condition added to `transpile()`.


However, I would like to point out that, when `transpile()` is called without `instruction_durations` specified, the transpiler fetches it from the backend.
Therefore, if we completely remove the current changes from `transpile()`, and add the default scheduling method at the level of `level_[0-3]_pass_manager()` instead, the pass manager wouldn’t be able to distinguish between the two different calls of `transpile()`:

- **scenario1**: `transpile()` called with `instruction_durations` specified but no `scheduling_method`. Here a scheduling pass is intended (we use the default pass).

- **scenario2**: `transpile()` called with neither `instruction_durations` nor `scheduling_method`. Here no scheduling passes are intended at all. However, the transpiler will fetch `instruction_durations` from the backend and therefore, at the level of the pass manager, this scenario will be identical to scenario1 and a default scheduling pass will be applied where none was originally intended.


So it seems to me that to solve the original issue **as well as** include a default scheduling method in the presets, I should update the `transpile()` **as well as** `level_[0-3]_pass_manage()` with the condition:
```
if scheduling_method is None and instruction_durations:
	scheduling_method="as_late_as_possible"
```

Please let me know what you think and how I should proceed. Thank you.

**Comment by ajavadia** [comment]
I think we shouldn't distinguish between `instruction_durations` that are available from a backend and ones that are explicitly passed to `transpile()`. In either case what is important is that the transpiler has access to durations for the instructions. This is the case for all other args as well, they can be either supplied by a Backend or by the user explicitly.

However the implications of this need some thought. If the transpiler always schedules a circuit when `instruction_durations` are known, then this means all `transpile(circuit, backend)` commands now return a scheduled circuit with many `delay` instructions. This is kind of a big change. E.g. 
- the simulator is not equipped to handle this yet (https://github.com/Qiskit/qiskit-aer/issues/1299)
- the payload size gets larger
- the output circuit generally gets harder to inspect by the end user

I do believe it is the right thing to do eventually (i.e. a physical circuit that is compiled for a backend should be scheduled), but it is against the expectation of many users I think. For this reason I lean towards making scheduling opt-in for now, i.e. keep the current behavior. Sorry that I am going back on what I said in #6667 but you brought up a good point about `instruction_durations` being fetched from backends.

**Comment by ajavadia** [comment]
To be clear I think this should be done eventually. I just think we need some ground work first to make sure it doesn't become annoying for users. This would be:
- larger payload should not add a large runtime penalty to simulation or experiments
- it should be easy to ignore delay instructions when visualizing circuits (unless we explicitly want to visualizing timing with the timeline_drawer)

**Comment by Kovi11Day** [comment]
Thank you for your feedback.
I understand the points which you have highlighted.
In order to solve the initial issue I have simply updated the docstring in the  `transpile()` function to mention that `instruction_durations` is only applicable if `scheduling_method` is specified. Let me know what you think.

As for the ground work required for the more long-term solution of setting a default scheduling method when required. Should we open issues related to these or should the current issue remain open until those are dealt with?

**Review by ajavadia — APPROVED** [review]
Thanks!

**Comment by kdk** [comment]
@Kovi11Day Can you update your branch and then this can be merged. (Alternately, if you unlock it to updates from maintainers, our CI can take care of updating it and merging when ready).

**Pull request merged**
