### PR TITLE
Unroll 3-or-moreQ pass

### PR DESCRIPTION
**Pull request by 1ucian0**
The current swappers do not work with 3Q gates. Therefore, it makes sense to decompose those gates before. This pass decomposes 3q gates recursively.

### CODE REVIEW

**Comment by 1ucian0** [comment]
The `Unroll` pass decomposes the full circuit to a basis set. That might create situations where information information get lost (for example, is this cx coming from a cz). This pass allows other passes to say: I don't know how to deal with 3q, unroll just those ones.

**Comment by jaygambetta** [comment]
Then you can set it by the basis you want. If you are breaking up a cox you need to know what. For the mapper it will not mapper which gate basis you choose as long as it is single and two qubit.

**Comment by 1ucian0** [comment]
`Decompose` and `Unroll` are related, but not the same. `Unroll('U')` makes sure that you will only have 'U's at the end. `Decompose('swap')` will guarantee that you will not have 'swap's at the end. Both are necessary and complementary. Similarly to the former, `Decompose3Q` will keep everything as it is, but no 3Q at the end. That's what mapper needs. As you said, as long as the circuit have single or two qubits gate, the mapper is fine with it. There is no way to express that with the unroller.

**Comment by ajavadia** [comment]
It seems like what this pass should do is to unroll recursively down to a 1Q and 2Q basis. Decomposing just 3Q gates is limiting because what if the circuit has a 4Q or 5Q composite gate?
The pass can be written in a way that it decomposes until every gate is at maximum a two-body interaction. It is slightly different than the current unroller pass because no explicit basis is required.

**Comment by 1ucian0** [comment]
I see your point there! It will no be testable until we don't have better support for custom gates. I can modify it to consider that and be read. Do you think the name `DecomposeTo2QorLess` is better?

**Comment by 1ucian0** [comment]
After talking with @ajavadia and @jaygambetta, I see their point. The pass should be renamed to `Unroll2Q` since is recursive.

**Comment by 1ucian0** [comment]
I renamed the pass and I change it to consider 3-or-moreQ gates, not just 3. Ready for review.

**Comment by ajavadia** [comment]
Thanks. This looks good. I updated the pass name to match the title of this PR, as I think that makes more sense. Good to merge.

**Pull request merged**
