### PR TITLE
For appended circuit add padding for wire labels in text drawing mode

### LINKED ISSUE #4066: Exception in draw() when drawing appended circuits with both quantum and classical bits
### Information

- **Qiskit Terra version**: 0.12.0
- **Python version**: 3.7.4
- **Operating system**: Windows 10

### What is the current behavior?

Let's take a look at two `QuantumCircuit` objects `qc1` and `qc2`, such that both of them have quantum and classical registers. If we append `qc2` to `qc1` and afterwards try to draw `qc1` in `output=text` mode, the following exception may occur 
```
d:\python_venvs\qiskit_venv\lib\site-packages\qiskit\visualization\text.py in _set_multibox(self, label, qubits, clbits, top_connect, bot_connect, conditional, controlled_edge)
   1051                 else:
   1052                     named_bit = self.qregs[bit_i]
-> 1053                     wire_label = ' ' * len(wire_label)
   1054                 self.set_qubit(named_bit, BoxOnQuWireMid(label, box_height, order,
   1055                                                          wire_label=wire_label))

UnboundLocalError: local variable 'wire_label' referenced before assignment
```

### Steps to reproduce the problem
Here is a sample code to reproduce
```
from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit

qreg1 = QuantumRegister(2)
creg1 = ClassicalRegister(1)
qc1 = QuantumCircuit(qreg1, creg1)

qreg2 = QuantumRegister(1)
creg2 = ClassicalRegister(1)
qc2 = QuantumCircuit(qreg2, creg2)
qc2.measure(qreg2[0], creg2[0])

qc1.append(qc2, [qreg1[0]], [creg1[0]])
qc1.draw()
```
Important notes:
* `qc2` must have only one qubit in its quantum register
* `qc2` must be appended to `qc1` in such a way, that between `qc2`'s quantum and classical registers be at least one quantum register from `qc1` (in the above case it is the qubit `qreg1[1]`)

### What is the expected behavior?
Produce a drawing of the circuit.

### Suggested solutions
Either the line `wire_label = ' ' * len(wire_label)` should be changed, so that on the right hand side it does not rely on the value of `wire_label` from previous iteration of the for loop (and the `if` block), or the `wire_label` variable should be initialized before the loop.

### PR DESCRIPTION
**Pull request by hay-k**
### Summary
Fixes #4066 as well as improves the drawing of wire labels in text mode.

### Details and comments
For issue #4066 please read its own description. Additional details addressed in this pull request, which are not described in the issue are described below.

Let's consider the following scenario: we have two circuits `qc1` and `qc2`, we append `qc2` to `qc1` then draw `qc1` in text mode. In the whole circuit the part corresponding to `qc1` is being drawn just as a box. Inside this box only those qubit wires are labeled, which are being used by `qc2`. Currently the labels are not padded correctly to the same lenght, which results in drawings like this
qiskit-terra-1
In this pull request I have fixed this by padding all labels from right with enough spaces, so that all of them have the same length, so that correctly aligned drawings are produced
qiskit-terra-2

### CODE REVIEW

**Comment by hay-k** [comment]
@1ucian0 sure, I will add a test. 
In 'qiskit-terra/test/python/visualization/test_circuit_text_drawer.py', right?

**Comment by 1ucian0** [comment]
Yes!

**Comment by 1ucian0** [comment]
@hay-k let me know if I can help!

**Comment by hay-k** [comment]
@1ucian0 I have examined how the other test cases are implemented, so that I can do in similar manner. I plan to add a new test case class called `TestTextDrawerAppendedCircuits` under `qiskit-terra/test/python/visualization/test_circuit_text_drawer.py` and implement at least the following 4 test scenarios
* Small (under 10 qubits) appended circuit with only quantum registers
* Small (under 10 qubits) appended circuit with both quantum and classical registers
* Big (over 10 qubits) appended circuit with only quantum registers
* Big (over 10 qubits) appended circuit with both quantum and classical registers

Do you approve?

**Comment by 1ucian0** [comment]
for the two first cases (small), we already have tests. For the rest, go ahead!

**Pull request merged**
