### PR TITLE
Add control-flow support to `GatesInBasis`

### PR DESCRIPTION
**Pull request by jakelishman**
### Summary

It's not yet entirely clear how control-flow will be supported through the `Target` and `basis_gates`, but for the time being, we just test them as if they will be added like any other instruction.  This is unlikely to entirely remain the case as more classical handling is added.

### CODE REVIEW

**Review by mtreinish — APPROVED** [review]
Thanks for doing this it LGTM, it seems simple and straightforward enough.

**Comment by mtreinish** [comment]
My thinking on the support was that a `Target` would need to contain the control flow ops the backend supported. We already require that measurement, reset, delay, and other non gate operations need to be in the target for it to be usable on the backend so I wasn't really treating control flow any differently. TBH, I was less interested in the `BackendV1` basis gates approach and haven't thought about it much, although I guess the analogous thing would be to include the suported control flow instructions in  the basis gates list.

**Comment by jakelishman** [comment]
At the moment there's an issue that control-flow operations are naturally variadic in qubit count, but even `Target.add_instruction(ForLoopOp(...), {None: None})` still imposes a constraint on `Target.instruction_supported` that the number of qubits match.  Since you can only hold one `ForLoopOp` instruction for the `for_loop` name, you can't really represent that variadicity.

**Comment by jakelishman** [comment]
For V1, just throwing it in the basis gates will work for now.  I suspect we'll probably need to look towards a V2.5 / backwards-compatible V3 as more classical control is added, but it does depend strongly on how much classical processing information we want to pass from backends to Terra.

**Comment by mtreinish** [comment]
Well we can evolve the target interface independently of backend too. That's part of why I made them separate objects (although far from the primary reason). But that's something we'll have to look at for 0.23.0 I guess because it's a general issue for any variable width operation (thinking a global MS gate on ions would have the same problem). I'll open an issue to track this for 0.23.0.

**Comment by jakelishman** [comment]
Oh, good forward thinking with the backend/target split, then - I hadn't fully considered that at all.  Yeah, that does give us rather more freedom.

**Pull request merged**
