### PR TITLE
Remove label parameter from gate methods in QuantumCircuit

### LINKED ISSUE #5098: Some QuantumCircuit methods do not pass label and ctrl_state for controlled gates
### Information

- **Qiskit Terra version**: master
- **Python version**: 3.8
- **Operating system**: Ubuntu 18.04

### What is the current behavior?
The following controlled-gate methods in QuantumCircuit do not accept label or ctrl_state as a param.
- ccx, toffoli, mcx, rccx, rcccx, fredkin, mcu1
### Steps to reproduce the problem
```
from qiskit import QuantumCircuit

qc = QuantumCircuit(3)
qc.cx(0, 1, label='Label', ctrl_state=0)
qc.ccx(0, 1, 2, label='Label', ctrl_state=1)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-decb3879596f> in <module>
      3 qc = QuantumCircuit(3)
      4 qc.cx(0, 1, label='Label', ctrl_state=0)
----> 5 qc.ccx(0, 1, 2, label='Label', ctrl_state=1)

TypeError: ccx() got an unexpected keyword argument 'label'
```
### What is the expected behavior?
All the above gates should accept label and ctrl_state
### Suggested solutions
Add label and ctrl_state to the above methods in QuantumCircuit class and pass them through to gate classes.

### PR DESCRIPTION
**Pull request by eptru**
### Summary
Fixes #5098.

Previously the following gate methods in `QuantumCircuit ` allows `label ` parameter:
`control, ch, cp, rx, crx, ry, cry, crz, cswap, csx, cu, cu1, cu3, x, cx, cnot, cy, cz`

Other gate methods don't accept `label ` as a parameter. This created a discrepancy between gate methods in `QuantumCircuit`.

`label` parameter is removed from the gate methods mentioned above.

### Details and comments
This is my first issue so I would really appreciate any feedback. Be nitpicky as you may.

I did NOT remove `label` parameter from `to_gate()` since it serves a different purpose and we can't use append to substitute this.
Let me know if you prefer to remove `label` parameter from `to_gate()` and I will be happy to do that.

I removed `label` parameter from `control()` method and as a result I also removed `label` from `mcmt.control()` since `mcmt` (multi-control multi-target gate) inherits from `QuantumCircuit`. Let me know if you don't like this change.

### CODE REVIEW

**Review by 1ucian0 — CHANGES_REQUESTED** [review]
This issue is making it to the top of my list after a year. Sorry about that :(

@eptru, if you are still there, consider using `qiskit.utils.deprecation. deprecate_arguments` to deprecate the label argument.

**Comment by 1ucian0** [comment]
hi @eptru , still working on this?

**Comment by prakharb10** [comment]
I think #8339 can be considered a fix as this seems stale.

**Comment by 1ucian0** [comment]
I'm closing this issues as stalled and returning https://github.com/Qiskit/qiskit-terra/issues/5098 to the pool of available `good first issues`

**Pull request closed without merging**
