### PR TITLE
Fix find_z2_symmetries when resulting object is empty

### LINKED ISSUE #9418: New sparse z2symmetry cannot be empty
### Environment

- **Qiskit Terra version**: 0.23.0
- **Python version**: 3.9
- **Operating system**: MacOs

### What is happening?

The method `quantum_info.analysis.Z2symmetries` was created as a copy of the similar class from opflow to prepare the deprecation of this class.
The type inputs in this new class were changed from `list[Pauli]` to `PauliList`.
However I just discovered that PauliList cannot be instantiated with an empty list.
The method `Z2symmetries.find_z2_symmetries` creates an object of the class `Z2symmetries` which will be empty in some cases. In theses cases the output is `cls(PauliList([]), PauliList([]), [], None)` which is raising an error.

### How can we reproduce the issue?

```
from qiskit.quantum_info import Pauli, PauliList, SparsePauliOp
from qiskit.quantum_info.analysis.z2_symmetries import Z2Symmetries
qubit_op = SparsePauliOp.from_list([("II", 0.0)])
z2_symmetries = Z2Symmetries.find_z2_symmetries(qubit_op)
```

```
---------------------------------------------------------------------------
QiskitError                               Traceback (most recent call last)
<ipython-input-1-e3e1d36b0d38> in <module>
      2 from qiskit.quantum_info.analysis.z2_symmetries import Z2Symmetries
      3 qubit_op = SparsePauliOp.from_list([("II", 0.0)])
----> 4 z2_symmetries = Z2Symmetries.find_z2_symmetries(qubit_op)

~/Documents/own_repo/qiskit-terra/qiskit/quantum_info/analysis/z2_symmetries.py in find_z2_symmetries(cls, operator)
    203 
    204         if _sparse_pauli_op_is_zero(operator):
--> 205             return cls(PauliList([]), PauliList([]), [], None)
    206 
    207         for pauli in iter(operator):

~/Documents/own_repo/qiskit-terra/qiskit/quantum_info/operators/symplectic/pauli_list.py in __init__(self, data)
    138         else:
    139             # Conversion as iterable of Paulis
--> 140             base_z, base_x, base_phase = self._from_paulis(data)
    141 
    142         # Initialize BasePauli

~/Documents/own_repo/qiskit-terra/qiskit/quantum_info/operators/symplectic/pauli_list.py in _from_paulis(data)
    179         num_paulis = len(data)
    180         if num_paulis == 0:
--> 181             raise QiskitError("Input Pauli list is empty.")
    182         paulis = []
    183         for i in data:

QiskitError: 'Input Pauli list is empty.'
```

### What should happen?

One should be able to instantiate an empty Z2Symmetries object.
`Z2symmetries.find_z2_symmetries` should not give errors on empty operators.

### Any suggestions?

My suggestion is to extend the typing `PauliList` to `list[Pauli] | PauliList`.
This would resolve the issue by replacing all `cls(PauliList([]), PauliList([]), [], None)` with `cls([], [], [], None)`.

I think it makes sense to support both because we can iterate though them the same way. We also won't use the additional features of the PauliList for applications to symmetry reduction

### PR DESCRIPTION
**Pull request by Anthony-Gandon**
### Summary

Fix #9418 .
This PR extends the input typing of the `Z2Symmetries` class in quantum_info.analysis from `PauliList` to `list[Pauli] | PauliList`.
With this we can fix the errors of `find_z2_symmetries(operator)` when the operator is None or when it does not have symmetries. 
Test were added to cover these exact two cases.

### CODE REVIEW

**Comment by woodsp-ibm** [comment]
We need this fix in the 0.23 release right, since this corrects a bug in RC1 in the Z2 Symmetries functionality that will be new in this release.

**Comment by ikkoham** [comment]
`Iterable[Pauli]` is better for the `__init__` since `PauliList` is also `Iterable[Pauli]` and each property should be `list[Pauli]`. (If what I am saying is too difficult, shall I commit directly?)

**Comment by Anthony-Gandon** [comment]
I had a small discussion with @woodsp-ibm and we concluded that Iterable[Pauli] would complexify the __eq__. More precisely, list equality would need to be replaced with element wise equality.

**Comment by woodsp-ibm** [comment]
Iterable[Pauli] can be used on the constructor. Its would be simple to create a list from that in the init and internally store as a list. This way eq remains the same. If we really want/need to do this.

@ikkoham this was my comment to @Anthony-Gandon in a DM yesterday

> I think I would go with list[Pauli] - at least for the returns. If you want the input on constructor to be more flexible then you could use Iterable{Pauli] there and create a list from it. I imagine the Z2Symmetry logic will go away at some point since on large systems it makes so little difference overall. As such it maybe simpler just to use list all round. I doubt any one will use it outside of the find symmetries method we have. If someone wanted Iterable on the constructor it could always be added later I think. As such I would just go with list[Pauli] for now - keep it simpler

**Comment by Anthony-Gandon** [comment]
I'm not sure we really want it if we don't use the features of having PauliList in the attributes

**Comment by woodsp-ibm** [comment]
I agree, as I stated in the DM I would keep it simple as list type.

**Comment by ikkoham** [comment]
How about this? I don't think there is any essential difference because it immediately consumes the `Iterable`s and makes a list.
https://github.com/Anthony-Gandon/qiskit-terra/pull/1

You can reject this PR and make it as is. In that case, however, the test must be rewritten. There is a type violation.

**Comment by Anthony-Gandon** [comment]
Looks good to me, I merged your suggestion @ikkoham. It is true that I had forgotten a PauliList in the tests, this is fixed by this Iterable PR, thanks

**Review by ikkoham — APPROVED** [review]
Thank you very much. LGTM!

**Pull request merged**
