### PR TITLE
Show all gate types in table

### PR DESCRIPTION
**Pull request by gines-carrascal**
### Summary
Show the ammount of each gate type that is used in the table.

### Details and comments
Example:
'''
circuit0	
Width	18
Depth	18
Gate Count	36
ccx Count	14
cx Count	14
measure Count	5
x Count	2
barrier Count	1
'''

### CODE REVIEW

**Comment by nonhermitian** [comment]
It might be best to set a `max_height` and `overflow` for the table given that the number of rows is no longer fixed

https://github.com/Qiskit/qiskit-terra/blob/838c812af03b61261a040b03831eb1db13bdfbca/qiskit/tools/jupyter/library.py#L106

**Comment by gines-carrascal** [comment]
done, thanks

**Comment by 1ucian0** [comment]
Hi @gines-carrascal 
Sorry for the delay. It seems that the @nonhermitian approval was not enough. 
Do you mind handling the conflicts? I will merge it after that.

**Comment by nonhermitian** [comment]
Actually we decided not to do this, and to keep the list simple focusing on non-local gates

**Comment by 1ucian0** [comment]
Closing as `wont fix` in that case. Thanks @gines-carrascal anyway!

**Comment by gines-carrascal** [comment]
@nonhermitian, please reconsider, I understan not to show all one qubit gates, but  ccx is also a non-local gate, the current implementation only shows cx, even if the circuit has other multiple-qubit gates.
I'm working comparing different arithmetric adder implementations with lots of Toffoly gates that I have to count by hand.

**Pull request closed without merging**
