### PR TITLE
Argument `epsilon` and `factr` of optimizers `L_BFGS_B` and   `factr` of `P_BFGS` has been removed

### PR DESCRIPTION
**Pull request by 1ucian0**
Argument `epsilon` and `factr` of `~qiskit.algorithms.optimizers.L_BFGS_B` and 
 `factr` of `qiskit.algorithms.optimizers.P_BFGS` has been removed. They were deprecated in #6319 (released in 0.18.0 - Jul 12, 2021).

### CODE REVIEW

**Review by Cryoris — APPROVED** [review]
LGTM, thanks! 👍🏻

**Review by woodsp-ibm — DISMISSED** [review]

**Comment by 1ucian0** [comment]
`on hold` until 0.21 release(I assume)

**Review by ikkoham — APPROVED** [review]
LGTM!

**Review by Cryoris — APPROVED** [review]
LGTM

**Pull request merged**
