### PR TITLE
Fix progress bar spawning and make parallel tools easier to use

### LINKED ISSUE #1392: Progressbars not spawned unless execute or compile are called first
### Informations

- **Qiskit Terra version**: master
- **Python version**: 3.7
- **Operating system**: OSX

### What is the current behavior?
The following no longer spawns a progress bar"
```
HTMLProgressBar()
ans = parallel_map(func, list(range(100)))
```
unless `compile` or `execute` have been run first.

### Steps to reproduce the problem
uncomment the line below:
```
import time
from qiskit import *
from qiskit.transpiler._parallel import parallel_map
from qiskit.tools.jupyter import *

q = QuantumRegister(2)
c = ClassicalRegister(2)
qc = QuantumCircuit(q, c)

qc.h(q[0])
qc.cx(q[0], q[1])
qc.measure(q, c)

backend = Aer.get_backend('qasm_simulator')
#qobj = compile([qc], backend)

def func(t):
    time.sleep(0.1)
    return 0

TextProgressBar()
parallel_map(func, list(range(100)))
```

### What is the expected behavior?
You should not have to call `execute` or `compile` before a progressbar can be displayed.

### PR DESCRIPTION
**Pull request by nonhermitian**
### Summary
fixes #1392 

Also moves parallel routines out of transpiler and into tools so that they may be used easier.  Additionally moved `TextProgressBar` out of Jupyter tools and into parallel tools since it is just text based.

### CODE REVIEW

**Comment by jaygambetta** [comment]
@nonhermitian there are some conflicts. Also i think we should put the progress bar in tools/events or something like that. I would also put the _pubsub in there as well. @atilag do you have any reason why the pubsub needs to stay in the main folder.

**Comment by atilag** [comment]
It is intended to be a general purpose tool and at that time I didn't find any better place, but surely it can be moved to `tools/` , I'd not create too many directory levels of indirection though.

**Comment by jaygambetta** [comment]
im good with in tools

**Comment by jaygambetta** [comment]
@nonhermitian can you rebase

**Pull request merged**
