### PR TITLE
[WIP] introduce GroupingMeasure class

### PR DESCRIPTION
**Pull request by to24toro**
### Summary
This PR introduces GroupingMeasure class which is a sub class of Instruction class and enables to n-qubits syncronized measurement in backendV2.
In previous, the class for measure, Measure class limits the number of  measured qubit is one.
I expect this PR is a first step for solving failure of schedule with backendV2 and being able to measure all qubits.

### Details and comments
related to https://github.com/Qiskit/qiskit-terra/issues/9488.

### CODE REVIEW

**Comment by jakelishman** [comment]
Just to let you know: this PR is unlikely to see review immediately, and it may well be in the future that we need to go a slightly different direction, but we definitely are thinking about it.

We're discussing a generalisation of how measurements are handled in Terra, but there's a lot of knock-on effects we've got to consider to get this right.  There are different stages within the Terra compilation model: abstract, possibly user-defined operations when building a `QuantumCircuit`; an intermediate representation used within the transpiler during hardware-mapping and optimisation; the concrete, more assembler-like form output by the transpiler.

It's only the last of these that scheduling and hardware need to be concerned about, but for us we need to make sure we've got the right data structures in place to handle all three.  There are a lot of old assumptions about measurements built into the transpiler, and adding more (especially co-opting the opcode `measure`) is something we need to take a lot of care with.  We're also interested in expanding the types of measurement that can be performed, and how Terra reasons about them (e.g. #9269).

**Comment by nkanazawa1989** [comment]
Thanks Jake. I agree in the long run we need to consider canonicalization of measurement instruction, but on the (pulse/circuit) scheduling side we need more immediate solution. IBM backend provides the `meas_map` configuration that is just ignored in current transpiler. This configuration defines a list of subset qubit that must be measured simultaneously, and ignorance of this constraint gives two side effects:

- We cannot generate pulse schedule with V2 backend. In V2 backend schedules are stored in `Target` but measurement calibration representing the grouped measurement (defined in the meas_map) cannot be handled as a Qiskit `Measure` instruction because of its qubit number limitation. We should fix this immediately.
- Dynamical decoupling results in poor mitigation effect. Because measurement instruction is implicitly re-aligned in the backend compiler (according to the meas_map constraint), an echo pulse train in front of the measurement instruction generates unbalanced delay. One can use backend-provided scheduler pass to consider the measurement grouping so this is not super high-priority.

The first bullet is indeed the breaking API change and I want to fix this in this release. Basically we just need to introduce multi qubit measurement as a Qiskit instruction and update V2 converter not to ignore the calibration for it.

**Comment by jakelishman** [comment]
I don't think it's a straightforward change to allow the current `Measure` class and the `"measure"` opcode in the output to become variadic in general.  The meaning of the `measure` opcode is, for better or worse, not fully defined by the `Measure` class - the Qiskit compiler behaviour and output is not _primarily_ class-based: it's opcode-based.  You can see this in the basis-translator equivalence library, the look-up keys of `Target`, the historic Qobj format, etc.  We sometimes like to pretend it's class-based, but it's not - there's hidden historic assumptions everywhere.

Off the top of my head, it'll probably be ok to add a new `"grouped_measure"` opcode that's variadic, but that may have implications for the Python-space deployements of our hardware, in that they might need to report that they accept that.  If we do add that as a temporary solution, I don't think we should compel any of our transpiler passes to consider it in optimisations, since it will be intended as an output operation.  Upgrading transpiler passes to support other types of measurement in optimisations is something that I think needs more careful design - evidenced by how many times it's been tried unsuccessfully in the past.

**Comment by ikkoham** [comment]
Since I'm not so familiar with BackendV2 issue, I can't review the PR. But I would like to suggest renaming the class name. Grouping seems like abelian grouping to me. How about ConcurrentMeasure?

**Comment by to24toro** [comment]
Thank you for discussion.
After the [discussion](https://github.com/Qiskit/qiskit-terra/issues/9488#issuecomment-1485382404), I close this draft.

**Comment by to24toro** [comment]
Thank you for discussion.
After the [discussion](https://github.com/Qiskit/qiskit-terra/issues/9488#issuecomment-1485382404), I close this draft.

**Pull request closed without merging**
