### PR TITLE
Fix/5056 composite instruction to qasm

### LINKED ISSUE #5056: qc.qasm() does not include params of composited gates
### Information

- **Qiskit Terra version**: 0.15.2
- **Python version**:  3.7.7
- **Operating system**: macOS 10.15.6

### What is the current behavior?
When you create a `QuantumCircuit` from a qasm string including composited gates,

```python
from qiskit.circuit import QuantumCircuit
qasm_str = (
    'OPENQASM 2.0;'
    'include "qelib1.inc";'
    'gate nG0 (param0) q0 { h q0; }'
    'qreg q[3];'
    'creg c[3];'
    'nG0 (pi) q[0];'
)
qc = QuantumCircuit.from_qasm_str(qasm_str)
```

the circuit is correctly created. But if you get qasm from the already created circuit

```python
qc.qasm(formatted=True)
```
```qasm
OPENQASM 2.0;
include "qelib1.inc";
gate nG0 q0 {h q0; }   // it should be: gate nG0 (param0) q0 { h q0; }
qreg q[3];
creg c[3];
nG0(pi) q[0];
```

the composited gates params are not present, so the qasm is incorrect. Any attempt of creating a new quantum circuit from this qasm will fail:

```python
qc2 = QuantumCircuit.from_qasm_str(qc.qasm())
```
```python
QasmError: "Gate or opaque call to 'nG0' uses 1 qubits but is declared for 0 qubits line 6 file "
```

### What is the expected behavior?
The qasm of the created quantum circuit should include the params of the composited gate.

```python
qc.qasm(formatted=True)
```

```qasm
OPENQASM 2.0;
include "qelib1.inc";
gate nG0 (param0) q0 {h q0; }
qreg q[3];
creg c[3];
nG0(pi) q[0];
```

### Suggested solutions
Take into account `Instruction` params when creating qasm in `qc.qasm()`.

### PR DESCRIPTION
**Pull request by raulotaolea**
### Summary
Fixes #5056 

### Details and comments
Now `qc.qasm()` includes composite gates params.

```python
from qiskit.circuit import QuantumCircuit
qasm_str = (
    'OPENQASM 2.0;'
    'include "qelib1.inc";'
    'gate nG0 (param0,param1) q0,q1 { h q0; }'
    'qreg q[3];'
    'qreg r[3];'
    'creg c[3];'
    'nG0(pi,pi) q[0],r[0];'
)
qc = QuantumCircuit.from_qasm_str(qasm_str)
qc.qasm(formatted=True)
```
```qasm
OPENQASM 2.0;
include "qelib1.inc";
gate nG0(param0,param1) q0,q1 { h q0; }. <-- Now the params are included in the definition
qreg q[3];
qreg r[3];
creg c[3];
nG0(pi,pi) q[0],r[0];
```

### CODE REVIEW

**Comment by raulotaolea** [comment]
The tests are failing after merging with master. In the last version of master, when creating a `QuantumCircuit` from a qasm with composited gates, their definitions are not included anymore. I think that the problem is here https://github.com/Qiskit/qiskit-terra/pull/4181/files#diff-28dc1ee1c54218f12f7d0decd1f290e4L420-L423. @1ucian0 do you know if this is preventing the composited declarations from being created?

**Comment by 1ucian0** [comment]
I adjusted your PR based on that change.

**Review by 1ucian0 — CHANGES_REQUESTED** [review]
I'm not sure if this is the way to go. However, I dont know the way to go :S

Here is the problem with this PR:
```python
from qiskit import *

from qiskit.circuit import QuantumCircuit
qasm_str = (
    'OPENQASM 2.0;'
    'include "qelib1.inc";'
    'gate nG0 (param0) q0 { u1(param0) q0; }'
    'qreg q[3];'
    'creg c[3];'
    'nG0 (pi) q[0];'
    'nG0 (pi/2) q[0];'
)
qc = QuantumCircuit.from_qasm_str(qasm_str)
print(qc.qasm())
```
```
OPENQASM 2.0;
include "qelib1.inc";
gate nG0_140576103553808(param0) q0 { u1(pi/2) q0; }
gate nG0(param0) q0 { u1(pi) q0; }
qreg q[3];
creg c[3];
nG0(pi) q[0];
nG0_140576103553808(pi/2) q[0];
```

I dont know the solution to this, because custom gates bind the variables at `ast_to_dag` time, so the info on the parameters is gone. Maybe @kdk have some idea?

**Comment by 1ucian0** [comment]
This was already noticed by OP in https://github.com/Qiskit/qiskit-terra/issues/5082

**Review by raulotaolea — COMMENTED** [review]
Thanks @1ucian0 for the review ! This PR is to include the gate's params in the qasm, so for me is ok.

**Comment by raulotaolea** [comment]
The #5082 is not blocking me, so we can create a new PR if we find a solution.

**Review by 1ucian0 — APPROVED** [review]
In that case, let's merge this. Thanks!

**Pull request merged**
