### PR TITLE
Add type hints to gates and QuantumCircuit

### LINKED ISSUE #3705: Gate docstrings and type hints
### What is the expected enhancement?

The standard gates could have a better documentation. They're missing type information on the input and only a few explain what their action on the qubits actually is. This forces users to go look either in the code (which some might not do) or elsewhere (books/internet). Since the qubit ordering is different in Qiskit compared to many other places, I believe it would be very useful to have a more accurate documentation. Especially for users getting started with quantum computing; the gates are probably one of the first objects they get in contact with. 

In #3472, many gates already get an updated docstring that includes the matrix representation. 
However the types are still missing and the docstrings could be more elaborate in general. 

For example we could go from
```
def rz(self, phi, q):  
    """Apply Rz to q."""
```
to
```

def rz(self, 
       phi: Union[int, Qubit], 
       qubit: Union[int, Qubit]) -> Instruction:
    r"""
    Apply the RZ gate to the specified qubit.

    The RZ gate rotates the state of the qubit around the Z-axis by the angle phi,
    e.g. it maps $|0\rangle$ to $|0\rangle$ and $|1\rangle$ to $-|1\rangle$.

    **Matrix Definition**
    
    The matrix for this gate is given by:
    
    .. math::
        U_{\text{RX}}(\theta)
            = \exp\left(-i \frac{\theta}{2} \sigma_X \right)
            = \begin{bmatrix}
                \cos(\theta / 2) & -i \sin(\theta / 2) \\
                -i \sin(\theta / 2) &  \cos(\theta / 2)
            \end{bmatrix}

    Args:
        phi: the rotation angle
        qubit: the qubit to which the RZ gate is applied

    Returns:
        the instruction added to self
    """
```
(Note: the matrix representation bit is part of #3472)

### LINKED ISSUE #6780: Inconsistency in whether gates accept labels
### Information

- **Qiskit Terra version**: 0.19.dev
- **Python version**: all
- **Operating system**: all

### What is the current behavior?

Not all defined `Gate` classes accept a label in their initialiser (e.g. `RXXGate`), and `QubitCircuit` is quite inconsistent on whether instruction methods accept a label: maybe about half (e.g. `QubitCircuit.x`) do, and about half (e.g. `QubitCircuit.h`) don't.

### Steps to reproduce the problem

```python
>>> qc = QuantumCircuit(1)
>>> qc.x(0, label="my_x")
<qiskit.circuit.instructionset.InstructionSet object at 0x7f9d60df81c0>
>>> qc.h(0, label="my_h")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: h() got an unexpected keyword argument 'label'
```

```python
>>> from qiskit.circuit.library import HGate, RZZGate
>>> HGate(label="my_h")
<qiskit.circuit.library.standard_gates.h.HGate object at 0x7f9d90e77040>
>>> RZZGate(0, label="my_rzz")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'label'
```

### What is the expected behavior?

Consistency.

### Suggested solutions

Add the label kwarg everywhere.

*edit*: this is a partial duplicate of #5098.

### PR DESCRIPTION
**Pull request by jakelishman**
### Summary

This is pretty much all documentation changes, except that it also moves the definition of `QuantumCircuit.measure` into `quantumcircuit.py` rather than monkey-patching it from `measure.py`.  This makes it consistent with other instruction definitions, and made it easier to access the `QubitSpecifier` and `ClbitSpecifier` type aliases.

#### Add type hints to QuantumCircuit

This adds full type hints to all public function entry points in
QuantumCircuit.  This will not cause quantumcircuit.py to pass a mypy
check yet; there are various idioms used within the file which are not
statically type-safe (nor, in some cases, dynamically type safe in the
sense that we sometimes rely on mismatched types to throw exceptions).
These include anything which takes the `inplace` argument, since
`inplace=True` versions do not return, which influences the out types to
    Optional["QuantumCircuit"]
This then means that methods using these functions (e.g.
`QuantumCircuit.__add__`) become unsafe; even though they use the
default `inplace=False`, subclasses could override this while still
maintaining type safety, and so the operation is not safe.

This patch makes no attempt to modify the behaviour of these
non-type-safe functions, only to classify what the current types are.

#### Add type hints and label to all standard gate classes

This completes the standard-library gate documentation overhaul tracked
by #3705, and mostly done in #4017, by adding type hints to the
initializers.

It also adds the missing `label` option to the iSWAP, R, RXX, RYY, RZX
and RZZ gates, to bring them up to parity with the other gates, tracked
in #6780.

#### Add parameters to QuantumCircuit gate docstrings

This only adds short documentation to the docstrings of the gate methods
(for example `QuantumCircuit.x`) about the parameters and the return
values.  It does not currently import the matrix representations into
the docstrings themselves, because the gate classes include those.  The
expectation is that you would see the docstring when running
interactively, and even in Jupyter, this typically does not include
displaying maths.  The matrix form is more useful when looking at the
online Sphinx documentation, where the cross-reference gate link will
work more easily.

### Details and comments

Fix #3705 
Fix #6780

I didn't pull the actual matrix definitions into the QuantumCircuit docstrings, because I think they'll add a lot of unreadable noise to the points where you'd actually see them most commonly - in the Jupyter/IDE popups for help and completions.  These are text-based, and so don't really show maths in the most part.  The only places you expect to see the maths are in the Spinx websites, where the links that are already in the docstring will work anyway.

There is a slight nuisance at the moment in that neither `sphinx.ext.napoleon` nor `sphinx_autodoc_typehints` quite handle cross-referencing the typehints in the docstrings properly, but this is something we could fix externally.

There are a few parts in `QuantumCircuit` where we're not doing things fully type-safely, and a couple of places where we do it in such a way that mypy can't statically analysise it.  I haven't attempted to fix any of this, since that can be done elsewhere.

### CODE REVIEW

**Comment by jakelishman** [comment]
Oh yeah, in other details: this leaves the fractured nature of the `label` parameter in the gate methods of `QuantumCircuit`, because we internally haven't made a 100% decision one way or the other.  We can make those changes in the future if we need to.

**Comment by levbishop** [comment]
Looks good. Any reason you didn't bring `reset` in like you did with `measure`?
For a future PR: the consensus seems to be settling on `qiskit.extensions` being a mistake so perhaps one day we could eventually eliminate monkeypatching completely...

**Review by levbishop — DISMISSED** [review]

**Comment by jakelishman** [comment]
@levbishop: no good reason - I suspect I noticed that `measure` was being monkey-patched in because it's referenced within `QuantumCircuit` anyway, and I just didn't notice that `reset` wasn't it.  I've brought it in as well.

There are still 3 monkey-patched functions in the circuit library (`QuantumCircuit.mcr[xyz]`), but these seem to be of quite a different form so I've left them as-is.  Aer also patches a bunch of functionality in, so it's not like we can be entirely consistent just within Terra.  At any rate, this inclusion is pretty tangential to the rest of this PR - I think I only did the `measure` originally because mypy moaned about it.

**Comment by jakelishman** [comment]
Oh, I should highlight: the hints I've added _should_ all be correct (I believe), but there's a few places where the `inplace` argument messes with mypy's static analysis.  Things like the arithmetic operators use functions which technically return `Optional[T]` (because of the `inplace` argument), but since we use them with `inplace=False`, we know they _do_ return `T`.

**Comment by levbishop** [comment]
For now lets just make any added hints correct, since that is uncontroversial. 
Clogging up the logic with extra "useless" code such as casting, just to appease mypy should probably wait for if we ever decide to make mypy a part of our CI strategy.

**Review by levbishop — APPROVED** [review]

**Pull request merged**
