### PR TITLE
Scrolling when text draw in Jupyter output 

### PR DESCRIPTION
**Pull request by 1ucian0**
This PR is an alternative solution to PR #1400. 

When the circuit is draw in Jupyter, the output is wrapped in a `<pre style="word-wrap: normal;white-space: pre;line-height: 15px;">`, meaning that horizontal scrolling is allowed if needed. It looks like this:

### CODE REVIEW

**Comment by nonhermitian** [comment]
How about both this and #1400 with the option to select via `wrap=True/False`?

**Comment by 1ucian0** [comment]
I have no problem. I'm honestly fine with whatever you think is the best for the Jupyter users. Maybe this can be activated with `scroll=True/False` instead of `wrap` (it seems more descriptive about the result to me)?

**Comment by ajavadia** [comment]
The `mpl` also wraps around. It would be nice if that also had this option.

**Comment by 1ucian0** [comment]
Currently? I could not find any reference to `wrap` in `qiskit/tools/visualization/_matplotlib.py`...

**Comment by mtreinish** [comment]
It's in there, it's called `fold` and it's a value in the `style` dict kwarg: https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/tools/visualization/_circuit_visualization.py#L163 It's a bit different though because it's a number of elements before folding/wrapping as opposed to the characters in the text output.

**Comment by mtreinish** [comment]
Also, I agree with @nonhermitian I don't think this is an alternative to #1400 it feels complementary to setting a fixed default for jupyter.

**Comment by 1ucian0** [comment]
so.. `fold` is similar (opposite?) to `line_length`, right?

**Pull request merged**
