### PR TITLE
Added num_ctrl_bits and ctrl_state to UnitaryGate call to ControlledGate

### LINKED ISSUE #4549: Control() method of UnitaryGate does not pass num_ctrl_bits and ctrl_state to ControlledGate
### Information

- **Qiskit Terra version**: 0.13
- **Python version**: 3.8
- **Operating system**: Ubuntu 18.04

### What is the current behavior?

In the control() method for UnitaryGate, the call to ControlledGate does not include the num_ctrl_bits or ctrl_state.

### Steps to reproduce the problem
```
from qiskit import *
from qiskit.extensions import UnitaryGate
import numpy as np
c=QuantumCircuit(3)
op = np.matrix([[1,0],[0,-1]])
r=UnitaryGate(op, label='rt')
re=r.control(2, ctrl_state='10')
c.append(re, [0,1,2])
c.draw('text')
```
produces this output.
```
q_0: ───■───
     ┌─┴┼──┐
q_1: ┤0 │  ├
     │  rt │
q_2: ┤1    ├
     └─────┘
```
### What is the expected behavior?
```
q_0: ──o───
       │   
q_1: ──■───
     ┌─┴──┐
q_2: ┤ rt ├
     └────┘
```
### Suggested solutions

Add num_ctrl_bits and ctrl_state to the ControlledGate call.

### PR DESCRIPTION
**Pull request by enavarro51**
### Summary

Fix #4549

### Details and comments

The control() method in UnitaryGate did not include the num_ctrl_bits or ctrl_state parameters when making a call to ControlledGate.

### CODE REVIEW

**Comment by ewinston** [comment]
@enavarro51 Thanks for catching this. Could you add a simple test to test_controlled_gate which this bug fix addresses?

**Comment by enavarro51** [comment]
@ewinston Added test. Also updated imports to qiskit.circuit.library...

**Comment by ewinston** [comment]
@enavarro51 I was going to suggest adding a test to make sure the controlled unitary is correct but just noticed it has a pre-existing bug where the call to `compute_control_matrix` also doesn't reference `ctrl_state`. 
https://github.com/Qiskit/qiskit-terra/blob/8e53368f557c3138a69bd28c2f64e0241330d1ae/qiskit/extensions/unitary.py#L134.

**Comment by enavarro51** [comment]
Yeah. Missed that one. I'll add the ctrl_state to that call and add a matrix check to the test file.

**Comment by enavarro51** [comment]
@ewinston I added ctrl_state to the call to compute_control_matrix. I set up a test where I feed a pauli-z to UnitaryGate and add a control. If ctrl_state is '1' I get a diagonal with 1's except the bottom right which is -1. If I use ctrl_state='0', the -1 moves up a row in the diagonal. I haven't dug into the math, but I am assuming this is correct behavior.

However, if I then run the circuit on the unitary_simulator I get the same matrix no matter what the ctrl_state is set to, so the assert fails for ctrl_state = '0'. Here's the code I used. I tried this with BasicAer and Aer.
```
    def test_controlled_unitary_gate(self, num_ctrl_qubits):
        """Test that UnitaryGate with control returns params."""
        ctrl_state = '1'
        circ = QuantumCircuit(2)
        umat = np.array([[1, 0], [0, -1]])
        ugate = UnitaryGate(umat).control(1, ctrl_state=ctrl_state)
        circ.append(ugate, [0,1]))
        simulator = BasicAer.get_backend('unitary_simulator')
        op_mat = execute(circ, simulator).result().get_unitary(circ)
        self.assertTrue(matrix_equal(op_mat, ugate.params, ignore_phase=True))
```
Soooo, what's next.

**Comment by ewinston** [comment]
There seem to be a couple of issues here but for now perhaps try the test,
'self.assertTrue(matrix_equal(op_mat, Operator(ugate).data, ignore_phase=True))'

**Comment by enavarro51** [comment]
@ewinston Operator(ugate).data gives the same output whether ctrl_state='1' or '0', so the assertTrue is true for either case. This means Operator(ugate).data is different from ugate.params for ctrl_state='0'.

**Comment by ewinston** [comment]
I committed what I had in mind. Operator(ugate).data does seem to reflect ctrl_state.

**Pull request merged**
