### PR TITLE
[WIP] Pulse, SamplePulse, & ParametricPulse moved to pulse/types.py & imports updated

### LINKED ISSUE #4074: Pulse, ParametricPulse and SamplePulse types should not live in pulse_lib
### What is the expected enhancement?
These are all types within our IR and should not live within an implementation library (they currently are in `pulse_lib`). They probably should live in a module `qiskit.pulse.types`

### PR DESCRIPTION
**Pull request by enavarro51**
### Summary

Fix #4074

### Details and comments

Created pulse/types.py and moved Pulse, SamplePulse, and ParametricPulses to types. Removed from pulse_lib, pulse.py and sample_pulse.py. Removed ParametricPulses class from parametric_pulses.py and left remaining code.

Updated all `__init__.py` files and any affected imports in any of the .py files under pulse. Removed the empty channels dir. Left the mostly deprecated commands dir.

### CODE REVIEW

**Comment by lcapelluto** [comment]
I still don't think `types` is the right name for a file of `Pulse`s. If anything, there could be a `type` module with _all_ "types" not just one @taalexander

**Comment by lcapelluto** [comment]
@taalexander I'm still unconvinced that this is an improvement, but maybe this would be a compromise:
```
pulse/channels.py
    # Contains DriveChannel, AcquireChannel, MeasureChannel, ControlChannel
pulse/pulses.py
    # Contains SamplePulse, Constant, Drag, Gaussian, GaussianSquare
pulse/types.py
     # contains class Pulse, ParametricPulse, and class Channels
```
it's closer to what you want while being transparent about what things are and where they are.

**Comment by taalexander** [comment]
I am ok with this, although maybe it makes sense for the Parametric pulse implementations to lives in `library`. `MemorySlot` and `RegisterSlot` could also live in `types`.

Another option:
Have a types package with:
- `base` (Pulse, Channel, Register)
- `pulses` (`Waveform`, `Parametric`, `Gaussian`, ...)
- `channels` (...)
 
A final option would be to put all of these in a single module `types`.

**Comment by lcapelluto** [comment]
So, your first rec would look like:
```
pulse/pulse_lib/          # soon to be 'library'
    ...
    sample_pulse.py       # soon to be 'waveform.py'
    parametric_pulses.py  # Gaussian, Drag, Constant, etc
pulse/channels.py
pulse/types.py  # contains Pulse, Channel, MemorySlot, RegisterSlot
```
I like this option a lot ^

 - It makes it clear where to get pulses from and keeps all the waveform-related stuff in one place: the pulse library
  - Thus, it's easy to find documentation for pulses in the API ref for `library`
  - It makes it easy to find available channels both in the code base and in the API ref
 - This doesn't require any deprecations to the user import paths (in this PR at least, since pulse_lib -> library will require user changes)
  - keeps each module focused on one subject
  - *** It satisfies the original task, which is to group together the types that are operated on by instructions in Pulse: Channels, Pulses, and classical memory.
  - Moving these classes to `types` will also improve the API Reference: when you are learning about types, you want a high level overview: you want to know what all the pieces are and how they fit into the big picture. When you are on a module level reference such as `pulse.channels`, you want to know what each channel does specifically and how to use it

**Comment by taalexander** [comment]
The only change I might be hesitant to make is to have `ParametricPulse` and `Waveform` in `types`. They seem fundamental to me.

**Comment by lcapelluto** [comment]
Yeah, I'd be hesitant about that, too, thinking about the user experience. I agree that keeping it in `pulse.library` is a nicer experience for them :)

**Comment by taalexander** [comment]
> Yeah, I'd be hesitant about that, too, thinking about the user experience. I agree that keeping it in `pulse.library` is a nicer experience for them :)

Could you please elaborate on the ways it is nicer? My thoughts are that `library` is a location of things that use preexisting class, like a standard library. However, `Waveform` and `ParametricPulse` are fundamental types that without these nothing in `library` could be defined.

**Comment by enavarro51** [comment]
@taalexander. I see there are some new issues, #4167, #4168, related to this. Are changes moving in that direction and if so, is this branch still relevant? Thanks.

**Comment by lcapelluto** [comment]
@taalexander Do you mean `Pulse`? I agree that `Pulse` makes sense in `types`. `Waveform` is just a specific kind of `Pulse` that needs to be used and instantiated by the user, like `Gaussian`. The `library` creates `Waveform`s and `ParametricPulse`s use the `library`. If you want library to be something that only uses pulse and not the other way around, we should move all the waveform related stuff somewhere else. Not sure a better name for that, though. `pulse.pulses` seems on the verge of losing meaning. Can you think of a better name?

**Comment by taalexander** [comment]
> @taalexander. I see there are some new issues, #4167, #4168, related to this. Are changes moving in that direction and if so, is this branch still relevant? Thanks.

It seems we are not quite clear on the scope of the required changes yet. I do believe your work is relevant, however, we should nail down the expected changes before we move forward to prevent additional frustration for you. Please bear with us.

**Comment by taalexander** [comment]
> @taalexander Do you mean `Pulse`? I agree that `Pulse` makes sense in `types`. `Waveform` is just a specific kind of `Pulse` that needs to be used and instantiated by the user, like `Gaussian`. The `library` creates `Waveform`s and `ParametricPulse`s use the `library`. If you want library to be something that only uses pulse and not the other way around, we should move all the waveform related stuff somewhere else. Not sure a better name for that, though. `pulse.pulses` seems on the verge of losing meaning. Can you think of a better name?

I don't think everything must be in the perfect place. I still think `types` is the best place for keeping `Waveform` in the root `pulse` namespace, I would like to avoid putting it in `library` as it is fundamental enough that it should be available from `pulse` without in a sense having to call out to an external source. However, if you insist that it goes in `library` over `types` that is fine and we can move forward.

**Comment by hykavitha** [comment]
@enavarro51 @lcapelluto @taalexander : let me know what needs to be done on #4167  #4168 issues that I'm working and you have made a suggestion. to push it or not?

**Comment by 1ucian0** [comment]
This `[WIP]` PR seems stalled for some time already, without any update. Does it make sense to keep it open?

ping @enavarro51 @lcapelluto @taalexander .

**Comment by enavarro51** [comment]
@1ucian0 I believe these changes were incorporated in #4662, so this PR can probably be closed. You may want to get confirmation from @taalexander or @lcapelluto.

**Pull request closed without merging**
