### PR TITLE
[WIP] channels package for quantum channels and CPTP maps

### PR DESCRIPTION
**Pull request by chriseclectic**
### Summary

Adds qchannel package to qiskit.tools. This package contains classes for representing quantum channels (CPTP maps) and is essentially an implementation of the paper: 

*Tensor networks and graphical calculus for open quantum systems*
Wood, Biamonte, Cory, Quant. Inf. Comp. 15, 0579-0811 (2015)
Open access: [arXiv: arXiv:1111.6950v3](https://arxiv.org/abs/1111.6950)

### Details and comments

* Contains classes for channel representations: 
  * `Choi`: Choi-Jamiolkowski process matrix
  * `SuperOp`: Linear superoperator
  * `Chi`: Pauli basis Choi-matrix / Chi matrix
  * `PTM`: Pauli basis superoperator / Pauli transfer-matrix
  * `Kraus`:  Kraus / operator-sum operators
  * `Stinespring`: Stinespring / system-environment insometry
  * `Unitary`: single-matrix Kraus representation (not generic operator map like other reps)

* The classes can be converted into each other using their init methods eg: `SuperOp(Kraus([k1, k2]))`
* All classes contain methods for
  * `is_cptp`: check if map is completely positive trace preserving
  * `evolve: evolve a quantum state by the channel
  * `adjoint`: compute to the adjoint channel
  * `conjugate`: compute the conjugate channel
  * `transpose`: compute the transposed channel
  * `compose`: compose with another channel
  * `tensor`: tensor product with another channel
  * `power`: compose channel with itself n times
  * `add`: linear addition of two channels
  * `subtract`: linear subtraction of two channels
  * `multiply`: scalar multiplication of two channels
* Operator overloads:
  * `+,-,*` for add, subtract, multiply
  * `@` for evolve, compose

#### TODO

- [ ] Tests for `Unitary` class
- [ ] Tests for `Choi` class
- [ ] Tests for `SuperOp` class
- [ ] Tests for `Chi` class
- [ ] Tests for `PTM` class
- [ ] Tests for `Stinespring` class
- [ ] Tests for `Kraus` class

### CODE REVIEW

**Comment by jaygambetta** [comment]
same with Additional channel transformations (such as twirling, averaging)

**Comment by chriseclectic** [comment]
Sounds good, I updated the comment to indicate what will be separate PRs

**Comment by jaygambetta** [comment]
chris do you have an estimate of when this will come of WIP. can we break it into simple little steps.

**Comment by chriseclectic** [comment]
Closing and opening a new reworked pr

**Pull request closed without merging**
