### PR TITLE
Convert `operator.coeffs` to real if possible in `pauli_evolution._to_sparse_pauli_op`

### PR DESCRIPTION
**Pull request by t-imamichi**
### Summary

Convert `operator.coeffs` to real if possible in `pauli_evolution._to_sparse_pauli_op`.
This fixes CI breakage of Nature (e.g., https://github.com/Qiskit/qiskit-nature/actions/runs/1770404994)

Since #7551 is stable backported, this might also need to be stable backported.

### CODE REVIEW

**Review by ikkoham — APPROVED** [review]
Thank you for the quick fix.

**Comment by Cryoris** [comment]
Would it be better to remove the check for complex completely to make sure we have the exact same behavior as in Terra 0.19.x? We could comment it out and add a note that we'll add this for the 0.20 release only.

**Comment by t-imamichi** [comment]
According to stable branch before #7591, there was no check of complex. I'm not sure we need this or not.
If you remove the check, you can make another PR and close this.
https://github.com/Qiskit/qiskit-terra/blob/73024df2f62b0f8c9fd2e439a7bbeba2d8b0aaa9/qiskit/circuit/library/pauli_evolution.py#L120

**Comment by ikkoham** [comment]
I'm not 100% sure, but if we pass in the complex coefficients, won't it just end up causing other errors, since it's not a unitary gate? If so, I think this is more helpful.

**Comment by Cryoris** [comment]
> I'm not 100% sure, but if we pass in the complex coefficients, does it just cause other errors, since it's not a unitary gate? If so, I think this is more helpful.

I agree it would be more helpful, but I think it would be better to be precise and not allow any complex part at all 🙂 But since that breaks the application CIs we'll have to postpone this check.

And I'm a little worried that `np.real_if_close` is still unstable -- what if there's some code in the applications where the complex part is just above the threshold that numpy accepts as real?

**Comment by t-imamichi** [comment]
If the imaginary part is larger than the threshold of `np.real_if_close`, it raises `ValueError`. You can configure the threshold by `tol` option.
https://numpy.org/doc/stable/reference/generated/numpy.real_if_close.html

**Comment by Cryoris** [comment]
I just think it would be the safest solution to not change the behavior of the stable release at all (and remove the check completely). 

We can definitely discuss if we should use `np.real_if_close` for the 0.20 release. But if you're sure that using it already now is safe enough for the applications and won't break down the road, then I'm also fine using it now already 🙂

**Comment by t-imamichi** [comment]
This is just a workaround. I don't have any strong opinion. Nature team may have preference. What do you think, @mrossinek?

**Comment by mrossinek** [comment]
From what I understand the problem is that Terra introduced a check against complex coefficients. While I do not think that this should be causing any issues in Nature (I cannot speak for other application modules), it does not seem like a change that would go into a bugfix release. However, one could argue it should go into a bugfix release if the presence of complex coefficients does indeed result in buggy behavior.

That said, 

> If the imaginary part is larger than the threshold of `np.real_if_close`, it raises `ValueError`. You can configure the threshold by `tol` option. https://numpy.org/doc/stable/reference/generated/numpy.real_if_close.html

I do not see this raising `ValueError`. Instead it appears to keep complex numbers when they are not close to being real.
If that is indeed the case, then I do not think that this fix causes a problem unless an application module requires complex phases (which, as I said, to my knowledge is not the case).

**Comment by Cryoris** [comment]
Fixing it on 0.19 directly by reverting the check sounds good to me 👍🏻 

@mrossinek and I did some digging and we think we found the source of the spurious complex parts in the coefficients. Namely when we taper our Hamiltonian with `Z2Symmetries.taper` there is some arithmetic with complex numbers involved -- even if the Hamiltonian has only real coeffs -- which leads to roundoff errors that are complex. These roundoff errors are not removed and make their way into the `PauliEvolutionGate`. 

One solution to that would be to adjust `SparsePauliOp.simplify`, which is called after the complex arithmetic, to filter out these small roundoff errors.

**Comment by jakelishman** [comment]
I'm against `SparsePauliOp` automatically removing small imaginary terms at any point - instead, can you implement the truncation yourself within `Z2Symmetries`, where you've got the full context, and _know_ that any small introduced imaginary components should be neglected?  `SparsePauliOp` should be a general quantum information tool; we shouldn't be encoding assumptions from one particular use case into it.  That's what I meant above by the caller being responsible.  Inside the `PauliEvolution` code, it should not be possible to gain an imaginary component at all.

That said, in a very quick look over `Z2Symmetries`, I couldn't see an obvious places where an imaginary component could enter if it didn't exist before.  Are the imaginary values coming from something in Nature?

**Comment by ikkoham** [comment]
OK. Let's merge  #7594.

> it's slightly more complicated because SparsePauliOp uses complex128 as its dtype

We are planning to implement the configurable dtype #6086 and #7215. I think this resolve the type problem.

**Pull request closed without merging**
