### PR TITLE
[WIP] Add an optional numba function abs2

### PR DESCRIPTION
**Pull request by jlapeyre**
This PR defines `abs2`, which does `abs(v) ** 2` if numba is not available, and a more efficient implementation if numba is available.

Micro-benchmark code is included showing 3 to 36 x performance improvement for arrays (vectors and matrices) of complex floats, depending on the size of the array. Importantly, I discovered no array size that gives worse performance.

In general, it is easy to get worse performance with numba.  So, I have been keeping notes on experiments and comparing to numpy and rust, etc. that I will post somewhere. For example `abs2` works on scalars, say Python's builtin `complex` type. But, the peformance is much worse (maybe 2 orders of magnitude) than just doing `abs(z) ** 2`. So you should be careful about where you use `abs2`, although, as usually, this performance hit might not be relevant depending on the context.

I have some other implementations in numba that I'll probably add to this PR.

Here are the micro benchmarks. `t_ratio` is the performance gained by using `abs2`.
```python
Matrix
abs2(m), nelem = 10, t = 2.921800187323242e-07
abs2(m), nelem = 100, t = 3.4966370149049907e-06
abs2(m), nelem = 1000, t = 0.000824352280178573
abs2(m), nelem = 10000, t = 0.12676568638009486
abs(m) ** 2, nelem = 10, t = 1.2861250143032522e-06
abs(m) ** 2, nelem = 100, t = 0.00012874547200044618
abs(m) ** 2, nelem = 1000, t = 0.01293344686011551
abs(m) ** 2, nelem = 10000, t = 1.3503075915999943
nelem = 10**1, t_ratio = 4.401823984690458
nelem = 10**2, t_ratio = 36.819798981606446
nelem = 10**3, t_ratio = 15.689223128386129
nelem = 10**4, t_ratio = 10.65199605791764

Vector
abs2(a), nelem = 10, t = 2.745754798525013e-07
abs2(a), nelem = 100, t = 2.9939497995655986e-07
abs2(a), nelem = 1000, t = 6.490845000371337e-07
abs2(a), nelem = 10000, t = 4.258170799585059e-06
abs2(a), nelem = 100000, t = 4.59942890011007e-05
abs2(a), nelem = 1000000, t = 0.000870293218002189
abs(a) ** 2, nelem = 10, t = 8.056662097806111e-07
abs(a) ** 2, nelem = 100, t = 1.3862563500879333e-06
abs(a) ** 2, nelem = 1000, t = 8.963448000140488e-06
abs(a) ** 2, nelem = 10000, t = 0.00013053619969869034
abs(a) ** 2, nelem = 100000, t = 0.0013221607491985196
abs(a) ** 2, nelem = 1000000, t = 0.013194122158980463
nelem = 10**1, t_ratio = 2.934224899519088
nelem = 10**2, t_ratio = 4.630192364244282
nelem = 10**3, t_ratio = 13.809369965894572
nelem = 10**4, t_ratio = 30.655463541154937
nelem = 10**5, t_ratio = 28.746193884351133
nelem = 10**6, t_ratio = 15.160548061340032
```

### CODE REVIEW

**Comment by jakelishman** [comment]
I left a comment in the Slack about my opposition to including any Numba in Terra, and copying the gist over to keep things in the same place:

We settled on Rust for our compiled extensions, and I disagree with the principle of "let's add options", because that means more maintenance weight for us, and more partially supported perpetually incomplete features for users.  We've been talking about moving all the `quantum_info` types completely into Rust, which would remove all the switching overhead and give us much more flexibility than Numba overall - I think that would be a better direction than this.

This particular PR seems to be targetting a microbenchmark.  Do you have numbers for a more complete integration benchmark showing that this is a bottleneck?  Good numbers on that wouldn't be convincing alone for me (I think a complete move to Rust types would offer the same / better performance with no JIT penalty and no additional import complexity), but I definitely don't think microbenchmark results are justification.

As a minor aside, I would also point out that `abs(z)**2` is most often used in the context of `sum(abs(z)**2)`, which would be better spelled as `np.linalg.norm(z)`.  That's more memory efficient (avoids two array allocations) and faster, so would perhaps be a better comparison.

**Comment by jlapeyre** [comment]
I originally thought of opening an issue and linking this PR so there is concrete code to look at. The @jakelishman 's comment, and my comment, really belong in an issue, not a PR like this.

**Comment by jakelishman** [comment]
Sorry, I realise my comment is a bit disjointed, because I still had the Slack discussion fresh in my mind - by "let's add options", I was referring to a comment you'd made saying "it makes sense to introduce [Numba] as an option [if there is a compelling use case]".  You're also right about `np.linalg.norm` - that was just a brain fade on my part.

My primary opposition is that Numba's advantages are being fast for prototyping and for adding on top of code in an interpreter that isn't properly packaged, but that doesn't match Terra's needs.  Every additional option risks tying our hands - I gave the example in Slack that we're talking about moving large swathes of the data classes for `quantum_info` into Rust.  If we add Numba now, that restricts us to maintain compatibility in the future, and any "optional switching" adds really quite a lot of maintenance and testing weight.

Compiled extensions (like in Rust) are more flexible for what we can actually do with them, and we control the platforms we can ship them on.  Terra already has a complete packaging set-up so that advantage of Numba is nullified, and to me, the flexibility of full Rust gives us far more options for wide-ranging optimisations and operations at the data-structure level (which really is the core of performance) and better control over efficient multithreading in conjunction with our multiprocessing. 

I've added the topic to the Terra meeting agenda for wider discussion.

**Comment by jlapeyre** [comment]
We discussed this in another forum. So far, my experience with numba has been similar to others' (with the exception of the first project I did).  If I find a compelling use case, I'll bring this up again. Until then, we can close this issue.

**Pull request closed without merging**
