### PR TITLE
The option fig.tight_layout is triggering warnings in some situations so it is being removed

### LINKED ISSUE #3112: backend overview and plot_gate_map show matplotlib warning
### Information

- **Qiskit Terra version**: master
- **Python version**: 3.5
- **Operating system**: mac

Matplotlib version 3.0.3

### What is the current behavior?

> /Users/kevin.krsulichibm.com/q/qiskit-terra/lib/python3.5/site-packages/matplotlib/figure.py:2369: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  warnings.warn("This figure includes Axes that are not compatible "

image

image

Only occurs on the first call, so recalling the function will clear the warning

### Steps to reproduce the problem

```
%matplotlib inline
import matplotlib.pyplot as plt

import qiskit.tools.jupyter

qk.IBMQ.load_account()
ibmq_open_provider = qk.IBMQ.get_provider( hub = 'ibm-q', group = 'open', project = 'main' )

%qiskit_backend_overview

from qiskit.visualization import plot_gate_map
plot_gate_map(ibmq_open_provider.get_backend('ibmqx2'))
```

### PR DESCRIPTION
**Pull request by 1ucian0**
Fixes #3112 

The option `fig.tight_layout()` is triggering warnings in same situations (maybe related with complicated relation between MPL and MacOS). This setting it seems unnecessary, since it produces the same output. We can always add `bbox_inches='tight'` as [is suggested](https://stackoverflow.com/questions/35393863/matplotlib-error-figure-includes-axes-that-are-not-compatible-with-tight-layou).

### CODE REVIEW

**Comment by kdk** [comment]
There is also (at least) a `plt.set_tight_layout` in `plot_gate_map`, which was responsible for #3112 . I also tried converting to a constrained layout instead of a tight layout, which also worked okay.

**Comment by 1ucian0** [comment]
So... are you suggesting to remove all of them? All gone after cc0bff71. Let me know.

**Comment by nonhermitian** [comment]
Not sure why we need this when the issue seems to be a bug in a specific point release from February. The solution is to just update or revert matplotlib to 3.1.1 or 3.0.2 respectively.

**Comment by kdk** [comment]
It's only an issue because 3.0.3 is matplotlib's old stable and is what python 3.5 users will use by default.

If downgrading matplotlib is the answer, that's fine, but I did try mpl 3.0.2 and 3.0.1 on python 3.5 and neither removed the warning from #3112 .

**Comment by nonhermitian** [comment]
But surely 3.1.1 works, does it not?  I am using it without error.

It just seems a bit silly to remove bits of our code for version and platform specific issues in other packages that are readily resolved by pip upgrade.

**Comment by kdk** [comment]
Only for python>=3.6, matplotlib-3.1.0 removed support for python 3.5 so upgrading to matplotlib-3.1 isn't an option.

**Comment by nonhermitian** [comment]
Ok remove it.

**Pull request merged**
