### PR TITLE
Fix display of negative fractions in arrays

### PR DESCRIPTION
**Pull request by deeksha-singh030**
### Summary
#7234
Qiskit Terra version: Qiskit Terra 0.18.3
Python version: Python 3.9.7
Operating system: Windows 10 (x64)
Path of changed file: qiskit-terra\qiskit\visualization\array.py in function _proc_value(val)

### Details
In a Jupyter notebook:
b = np.array(
[
[-5.664 - 3.623j, 7.672 - 4.470j, 1.864 - 7.149j],
[0.766 - 4.821j, -4.413 - 0.228j, 9.759 + 4.256j],
[1.0335 - 3.672j, 3.890 - 5.741j, 7.760 + 3.812j],
]
)
display(array_to_latex(b, prefix=r"\mathbf{B}="))
-5.664 is displayed as -705/125 but if the value is negated (to 5.664) it appears as 5.664 (not as a fraction)
So, in the following path I've changed line 77 in proc_value function from (num + denom < 20) to  (abs(num) + abs(denom) < 20) so that negative fractions will also appear as decimal like positive fractions using array_to_latex.

### CODE REVIEW

**Review by jakelishman — COMMENTED** [review]
This looks good thanks, and it's good you were able to get everything compiling.  Please could you add a release note with a bugfix section, with just a sentence describing the bug you fixed?

(If you've got the dev requirements installed, it's just `reno new array-to-latex --edit`.)

**Comment by deeksha-singh030** [comment]
@jakelishman I've made the changes. Please take a look on it.

**Comment by jakelishman** [comment]
I think you maybe need to push some more changes up?  At the moment, there's nothing new since I commented.

**Comment by deeksha-singh030** [comment]
@jakelishman I've published a release note to this branch. Please  take a look on it and tell me if I've done what I was supposed to  do or not?

**Comment by jakelishman** [comment]
Heya - I still can't see the release note in this PR.  Perhaps it's not been pushed to GitHub, or it's gone onto a different branch by accident?  You can see in the "files changed" tab at the top whether it's there - a new release note in that view will appear [like this](https://github.com/Qiskit/qiskit-terra/pull/7525/files#diff-d32597fc29fb1a390e68272394d4a9a3307f0fa5b6bffe00cf57727ae1c69b5e).

**Comment by deeksha-singh030** [comment]
@jakelishman Please take a look. I'm sorry for causing this much trouble.

**Review by jakelishman — APPROVED** [review]
No need to be sorry, it's your first time, and it can be tricky to use `git`.  I've fixed up the release note using the proper `reno` tool, and this looks good to go.

I think you've made this PR using only the web interface of GitHub.  In general, we'd recommend not doing that, but working locally on your own computer; you can't test your code on GitHub, and here you couldn't use the `reno` tool to generate the release note properly.  There's some advice on getting things set up right in [the contributing guide](https://github.com/Qiskit/qiskit-terra/blob/main/CONTRIBUTING.md).

Congratulations on getting your first PR merged!

**Pull request merged**
