### PR TITLE
Fixed noise adaptive layout choosing 0 reliability cx

### PR DESCRIPTION
**Pull request by DavideFrr**
Changed swap_reliab of swap graph edges with 0 reliability from -math.inf to math.inf

### Summary

Fixed issue   #3517 

### Details and comments

Fixed the issue where a cx with 0 reliability would be always choosed by the `NoiseAdaptiveLayout` trasnpiler pass.

### CODE REVIEW

**Comment by ajavadia** [comment]
Thanks for your contribution.

It seems like the bug was introduced in https://github.com/Qiskit/qiskit-terra/pull/2656, and actually I just saw a comment there that pointed it out. So it's good that it's finally getting fixed.

I believe the source of confusion is the name of variables used in this file. `swap_reliab` and `best_reliab` should actually be `swap_cost` and `best_cost`, because lower is better for them. And the algorithm tries to minimize cost using Floyd-Warshall for shortest weighted path.

Can you take this opportunity to fix the variable names as well?

**Comment by DavideFrr** [comment]
@ajavadia I believe something like this would much clearer to understand for everyone:

```
swap_reliab = pow(g_reliab, 3)
# convert swap reliability to edge weight for Floyd-Warshall shortest weighted paths algorithm
swap_cost = -math.log(swap_reliab) if swap_reliab != 0 else math.inf
self.swap_graph.add_edge(ginfo.qubits[0], ginfo.qubits[1], weight=swap_cost)
self.swap_graph.add_edge(ginfo.qubits[1], ginfo.qubits[0], weight=swap_cost)
```
Also I think that `swap_costs_temp` and `self.swap_costs` should become `swap_reliabs_temp` and `self.swap_reliabs`. This is my humble opinion, the final decision is up to you.

**Comment by DavideFrr** [comment]
I inadvertently clicked on close

**Comment by ajavadia** [comment]
Sounds good thanks

**Comment by DavideFrr** [comment]
Ok, now it should be all right

**Pull request merged**
