### PR TITLE
Circuit order and register

### LINKED ISSUE #1016: The `test_online_qasm_simulator_two_registers` is failing in master
### What is the current behavior?
The test is failing in the `master` branch with the following error:

```
======================================================================
FAIL: test_online_qasm_simulator_two_registers (python.ibmq.test_ibmq_qasm_simulator.TestIbmqQasmSimulator)
Test online_qasm_simulator_two_registers.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Qiskit/qiskit-terra/test/python/common.py", line 373, in _wrapper
    return decorated_func(self, *args, **kwargs)
  File "/home/travis/build/Qiskit/qiskit-terra/test/python/ibmq/test_ibmq_qasm_simulator.py", line 109, in test_online_qasm_simulator_two_registers
    self.assertEqual(result1, {'00 01': 1024})
AssertionError: {'01 00': 1024} != {'00 01': 1024}
- {'01 00': 1024}
?     ---

+ {'00 01': 1024}
?    +++
```

### Steps to reproduce the problem
The failure is intermittent. It seems related with running all the test suite. When running isolated, it seems not to be failing.

### What is the expected behavior?
The test should pass regardless of other tests.

### Suggested solutions
It will be temporally marked as an expected failure but we should dig into what happens.

### LINKED ISSUE #1244: Check if the simulators follow the new bit ordering convention
The epic #1148 decided a new bit ordering convention that needs to be followed by the simulators:

From the #1148's text:
 
> Imagine we create two registers `q` and `v` and that `q` is declared
> first.
> 
> ```
> circ = QuantumCircuit()
> q = QuantumRegister(5)
> v = QuantumRegister(6)
> circ.add_register(q)
> circ.add_register(v)
> ```
> 
> The tensor product order for these registers is
> 
> ```Vn x ... V1 x V0 x Qn x .. Q1 x Q0```
>  
> Check the simulators do this

> The classical bits are order with V being the most signifcant register and Q the least significant. That way the the mapping stays 1:1 between basis states and classical bits.
> 
> Check the measurements do this if i have two classical registers. We will not have any spaced between the registers. So if the outcome is for register V is `1...01` and for Q is `0..11` then the bit string returned is `1...010..11`. Currently qiskit was suppost to return it `1...01 0..11`

### PR DESCRIPTION
**Pull request by jaygambetta**
Fixes: #1243, Fixes #1244, Fixes #1016 

1.  added an add_register to QuantumCircuit
2. I added a process_fidelity to check the unitary order
3. I made test that confirm the order of the counts, statevector and unitary 

@mtreinish and @1ucian0 the circuit drawer is still not the correct order I would like to out the order test in the test function

Things i needed to also add to fix the random order bug. 
1. Made it so you can check if register is the same ( quantum and classical)
2. made the register lists over dictionary so the order is preserved
3. made orderdict in dagcircuit but i also think we need to make these list eventually otherwise we get the same error when adding them together.

### CODE REVIEW

**Comment by jaygambetta** [comment]
This is passing locally and this is a bug somewhere that is changing the order. We really need to find where this is.

**Comment by jaygambetta** [comment]
After lots of debugging 

On the server (where test run)
```
[['q1', 0], ['q1', 1], ['q0', 0], ['q0', 1]]
OPENQASM 2.0;
include "qelib1.inc";
qreg q0[2];
qreg q1[2];
creg c0[2];
creg c1[2];
measure q0[0] -> c0[0];
measure q1[1] -> c1[1];
u3(3.14159265358979,0,3.14159265358979) q0[1];
measure q0[1] -> c0[1];
u3(3.14159265358979,0,3.14159265358979) q1[0];
measure q1[0] -> c1[0];

[['c0', 2], ['c1', 2]]
QobjItem(name='u3', params=[3.141592653589793, 0.0, 3.141592653589793], qubits=[3], texparams=['\\pi', '0', '\\pi'])
QobjItem(clbits=[1], memory=[1], name='measure', qubits=[3])
QobjItem(clbits=[0], memory=[0], name='measure', qubits=[2])
QobjItem(clbits=[3], memory=[3], name='measure', qubits=[1])
QobjItem(name='u3', params=[3.141592653589793, 0.0, 3.141592653589793], qubits=[0], texparams=['\\pi', '0', '\\pi'])
QobjItem(clbits=[2], memory=[2], name='measure', qubits=[0])
```
On my computer (mac)

```
[['q0', 0], ['q0', 1], ['q1', 0], ['q1', 1]]
OPENQASM 2.0;
include "qelib1.inc";
qreg q0[2];
qreg q1[2];
creg c0[2];
creg c1[2];
measure q0[0] -> c0[0];
measure q1[1] -> c1[1];
u3(3.14159265358979,0,3.14159265358979) q1[0];
measure q1[0] -> c1[0];
u3(3.14159265358979,0,3.14159265358979) q0[1];
measure q0[1] -> c0[1];

[['c0', 2], ['c1', 2]]
QobjItem(clbits=[3], memory=[3], name='measure', qubits=[3])
QobjItem(name='u3', params=[3.141592653589793, 0.0, 3.141592653589793], qubits=[2], texparams=['\\pi', '0', '\\pi'])
QobjItem(clbits=[2], memory=[2], name='measure', qubits=[2])
QobjItem(name='u3', params=[3.141592653589793, 0.0, 3.141592653589793], qubits=[1], texparams=['\\pi', '0', '\\pi'])
QobjItem(clbits=[1], memory=[1], name='measure', qubits=[1])
QobjItem(clbits=[0], memory=[0], name='measure', qubits=[0])
```

**Comment by jaygambetta** [comment]
We see that the qobj is correct just a different order but what is not correct is the mapping to cbits.

**Comment by jaygambetta** [comment]
Ok this should be fixed now and not random with the order.

**Comment by jaygambetta** [comment]
Things i needed to also add are. 
1. Made it so you can check if register is the same (added type for quantum and classical)
2. made the register lists over dictionary
3. made orderdict in dagcircuit but i also think we need to make these list eventually

**Comment by jaygambetta** [comment]
@ajavadia @nonhermitian it passes online !!!!!!!

**Comment by ajavadia** [comment]
This looks great. Nice job debugging the register orders. And for reviving the online simulator test.

Since I banged my head on this a few times, I'm putting the treatise here in bold for posterity:
- **REGISTERS ARE ADDED IN AN ARRAY. IF REGISTER1 IS ADDED LATER, IT GOES TO THE LEFT OF TENSOR**

- **WITHIN REGISTERS, BIT1 IS MORE SIGNIFICANT THAN BIT0. SO BIT1 IS ON THE LEFT OF TENSOR**

- **GIVEN THE ABOVE, TWO REGISTERS WITH TWO QUBITS EACH, LOOK LIKE:**
qreg1[1]  - qreg1[0]  --- qreg0[1] -  qreg0[0]

**Comment by jaygambetta** [comment]
I think the commit history shows how much i banged my head against the wall as well.

**Pull request merged**
