### PR TITLE
Stop relying on runtime imports for gate methods

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

In #4035 the import of gate objects was moved from import time to
runtime. However runtime imports don't happen for free and this adds
between a 5% and 15% run time overhead on circuit construction using
the gate methods (which is the most common usage). To fix this
performance regression this commit removes the runtime imports and
moves them to the module level ensuring it's only run once. This has a
ripple effect though caused by the shared package hierarchy of
`qiskit.circuit.library` it is impossible to import `QuantumCircuit` when at
the module level it is importing anything from qiskit.circuit.library.
This is because there is code being run at the module level in
`qiskit.circuit.library.__init__` that depends on QuantumCircuit being
initialized. However, because this gets triggered by the import of the
`qiskit.circuit.quantumcircuit` module python throws an error. As long as
`qiskit.circuit.library.__init__` has imports from
`qiskit.circuit.quantumcircuit` this cycle will exist. This commit fixes
this by moving the standard_gates package up a level in the hierarchy so
that all the dependencies for building QuantumCircuits are imported at
the same level and library elements (which depend on those) occur at a
level separate from that. For backwards compatibility a shim module is
added to `qiskit.circuit.library.standard_gates` which just imports
everything from `qiskit.circuit.standard_library`. So we can continue to
advertise `qiskit.circuit.library.standard_gates` as the entry point for
the gate classes if we desire moving forward but now the import tree
works.

### Details and comments

### CODE REVIEW

**Comment by Cryoris** [comment]
Yeah, that was the main argument I had in favor of not putting the gates within the circuit library. If we put the gates on the `qiskit.circuit` level could we name the directory `qiskit.circuit.gates`? The prefix `standard` was mainly to distinguish if from the `generalized_gates` directory in the library. That was also @ajavadia's preferred name, and it's less typing.

Personally, I would be fine with 
```
from qiskit.circuit.gates import HGate
from qiskit.circuit.library import SomeGeneralizedGateOrCircuit
```
I feel like this would be better to not have to many criss-cross imports (as we already still support the extensions import)

**Comment by mtreinish** [comment]
> Yeah, that was the main argument I had in favor of not putting the gates within the circuit library. If we put the gates on the qiskit.circuit level could we name the directory qiskit.circuit.gates? 

Sure we can rename the directory to `gates` instead of `standard_gates`. As long as we maintain compatibility with the existing paths I don't have a strong preference what the new path ends up being.

> I feel like this would be better to not have too many criss-cross imports (as we already still support the extensions import)

I agree, we basically have 3 valid import paths for the gates now with this. The problem is that we can't really walk back `qiskit.circuit.library.standard_gates` anymore since it's out in a release (and heavily documented in that release). This is why merging big changes like this right before a release isn't generally a good idea.

**Comment by challngr** [comment]
I have been doing performance tests on BasicSwap and Stochastic Swap transpiler passes for large-ish circuits.  The regression is quite clear.  It appears to be much worse than 5%-15% as the circuits start to grow beyond about 100 qubits.  See my comments in https://github.com/Qiskit/qiskit-terra/issues/4484 for details.

**Comment by kdk** [comment]
Following up on some offline discussion. Closing this as the performance improvement is outweighed by the cost of having a non-standard import location for the standard gates. For programmatically constructing large circuits, we should be directing users towards `append` instead.

**Pull request closed without merging**
