### PR TITLE
Fix classical-bit handling in control-flow StochasticSwap

### LINKED ISSUE #8903: Qasm3 exporter failing when if branch does not contain all clbits
### Environment

- **Qiskit Terra version**: 0.39.0
- **Python version**: 3.10.6
- **Operating system**: MacOs 12.6 (21G115)

### What is happening?

In some cases, the qasm3 exporter gives an error if the circuit has more clbits than needed in the if_else statement.

### How can we reproduce the issue?

Run the following:

```
backend_wellington = provider.get_backend('ibm_wellington')

cr = ClassicalRegister(1) # if >1 breaks
cr2 = ClassicalRegister(1) # if this reg exists, breaks
qr = QuantumRegister(5)
qc = QuantumCircuit(qr, cr, cr2)

with qc.if_test((cr[0], 1)) as _:
    qc.cnot(0,1)
    qc.cnot(0,2)
    qc.cnot(0,3)
    qc.cnot(0,4)

qc_trans = transpile(qc, backend=backend_wellington, basis_gates=backend_wellington.configuration().basis_gates+['if_else'], optimization_level=1)
print(qasm3.Exporter().dumps(qc))
print(qasm3.Exporter().dumps(qc_trans))
```

Now, `qc` gets correctly exported, while `qc_trans` provides the following error:
```
QASM3ExporterError: 'Tried to push a scope whose circuit needs 2 clbits, but only provided 1 clbits to create the mapping.'
```

### What should happen?

The QASM3 string should be output for both cases.

### Any suggestions?

_No response_

### PR DESCRIPTION
**Pull request by jakelishman**
### Summary

Previously we were expanding control-flow blocks to be full-width over _all_ wires, and only contracting the qubits back again, without changing the clbits given as node arguments.  This modifies the

The changes in most of the tests are necessary because the tests were testing behaviour that should be considered incorrect.  The principal new test of all this behaviour is the additional assertions added in `_visit_block` in the random tests; these uniformly fail without this patch, and succeed with it.

### Details and comments

Fix #8903.

### CODE REVIEW

**Review by mtreinish — COMMENTED** [review]
The code change looks good to me, but the one thing I think would be good is a dedicated test for this, or alternatively with the follow-on effects to ensure we can serialize with qpy and qasm3 transpiled control flow circuits. Just to verify we don't regress this in the future, especially once we get sabre control flow aware.

**Comment by jakelishman** [comment]
This idea of writing post-transpile integration tests turned out to be an excellent idea - in trying to write them, I've already turned up more bugs in unrelated code than I was expected, such as #8923.

**Comment by jakelishman** [comment]
Added more tests in fb30ff8d6.  They need all of:
- #8924
- #8928
- #8930
to merge first before they'll pass, because of other bugs I found while writing the integration tests.

**Comment by jakelishman** [comment]
This PR should be ready to review and merge, now that its dependents are in.

**Review by mtreinish — APPROVED** [review]
LGTM, thanks for adding the extensive testing and fixing the long tail of issues it uncovered.

**Pull request merged**
