### PR TITLE
temporary fix for multiple job-submitting process

### LINKED ISSUE #772: Localjob is not process safe and leads to hang
Users cannot run multiple processes, each of which submits some jobs. 

As a user, I want to run multiple processes to submit the jobs in parallel. However, they will hang in mac. 

You can argue that (#567) the user would better assembly multiple circuits and send them in one job, then the qiskit will internally use the `PoolExecutor` to handle them.

However, as a general tool, qiskit should not impose restrictions on how the users run it. The users should have the options to decide whether or not to submit the jobs using multiple processes. 

To fix the hang bug, simply change the code as follows. 
```python
class LocalJob(BaseJob):
    if sys.platform in ['darwin', 'win32']:
        _executor = futures.ThreadPoolExecutor()
    else:
        _executor = futures.ProcessPoolExecutor()
    def __init__(self, fn, qobj):
        super().__init__()
        self._qobj = qobj
        self._backend_name = qobj.header.backend_name
        self._future = self._executor.submit(fn, qobj)
```
-> 
```python
import os
class LocalJob(BaseJob):
    processes2executors = {}
    def __init__(self, fn, qobj):
        super().__init__()
        self._qobj = qobj
        self._backend_name = qobj.header.backend_name
        pid = os.getpid()
        if pid not in LocalJob.processes2executors:
            print(pid, "first time to create the executor")
            if sys.platform in ['darwin', 'win32']:
                _executor = futures.ThreadPoolExecutor()
            else:
                _executor = futures.ProcessPoolExecutor()
            LocalJob.processes2executors[pid] = _executor
        else:
            print(pid, "reuse my executor")
            _executor = LocalJob.processes2executors[pid]
        self._future = _executor.submit(fn, qobj)
```

In the original code, the executor is shared by multiple job-submitting processes. Some process cannot be joined even if it has finished its work because the underlying executor is still busy.  In the patch, the executor is made process-local, i.e., each process owns an executor. So, the process can be joined after it finishes its own work.

This is only a patch for mac. For Linux, the executor is the `ProcessPoolExecutor`, which needs to be explicitly shut down using `executor.shutdown()` before the job-submitting process is to be joined. Otherwise, it will still lead to another hang. 

To achieve this, qiskit needs to provide the 'session' APIs so that each job-submitting process opens a session upon start and closes the session upon join, where the session close can trigger the `executor.shutdown()`.

Anyway, the original code of Localjob looks like a code smell.

### PR DESCRIPTION
**Pull request by liupibm**
### Summary
Temporary fix #772 
Once we have better solution, this fix should be replaced to the better solution.

### CODE REVIEW

**Comment by liupibm** [comment]
@ewinston the travis CI seems to fail even if I revert my version to the original version. 

Will give it a try later on.

**Comment by ewinston** [comment]
@liupibm I'm not sure why the travis is failing except that it seems to be independent of the code. Perhaps @delapuente or @atilag know?

**Comment by delapuente** [comment]
Travis seems to experience intermittent failures while running some tasks (non-code related, sometimes it is during environment setup). I think it's due to the hight traffic we send to them but not sure. Anyway, I've restarted the task and everything seems OK.

**Comment by delapuente** [comment]
@liupibm it seems GitHub is tricked to think there are no changes if you submit an empty commit. Don't do it. It is preferable you ask one of us to review and possibly relaunch the Travis task.

**Comment by liupibm** [comment]
@nonhermitian @ewinston Yes, multithreads run on a single core and multiprocesses run on mulitple cores. 

Based on my experience on Java, the multithreads does not help improve performance much (unless some threads use I/O and some use CPU at the same time). It merely gives the feeling that each thread is working because the cpu assigns a tiny time slice to each thread using the fair scheduler. 

see more details here: https://stackoverflow.com/questions/40810816/threadpool-in-python-is-not-as-fast-as-expected

**Comment by liupibm** [comment]
@delapuente thanks,
I reverted my change to the original code to see whether the test failures are due to my change.

I am still unable to pass the tests now, will keep you notified once the they are passed. thanks,

**Comment by liupibm** [comment]
@delapuente @ewinston  I still cannot pass the tests. 
will try to fix my own problem on the client side. 

You can probably close this. thanks,

**Comment by ajavadia** [comment]
thanks for the clarification @liupibm

**Pull request closed without merging**
