### PR TITLE
Generic PrimitiveJob and BaseSampler/BaseEstimator

### PR DESCRIPTION
**Pull request by ikkoham**
### Summary

This PR improves type hinting with `Generic`.
The type of result returned by `Primitives.run` is made explicit, so it is enabling code completion and improving the user experience.

image

### CODE REVIEW

**Review by jakelishman — COMMENTED** [review]
It's useful to do this, but I don't think you need to override the derived methods to add the type hints.  Deriving a class from `Generic` means you can define the specialisation during the inheritance, rather than at method resolution.  For example, given a file `generic.py`:
```python
import typing

T = typing.TypeVar("T")

class Base(typing.Generic[T]):
    def f(self) -> T:
        raise NotImplementedError

class Int(Base[int]):
    pass

class Str(Base[str]):
    pass

reveal_type(Base().f())
reveal_type(Int().f())
reveal_type(Str().f())
```
the result of running mypy on it is:
```text
generic.py:15: note: Revealed type is "<nothing>"
generic.py:16: note: Revealed type is "builtins.int"
generic.py:17: note: Revealed type is "builtins.str"
Success: no issues found in 1 source file
```

**Comment by jakelishman** [comment]
Ah sorry, I'd misread the code a bit.  Yeah, in the way the primitives typing is currently done, the way you've done things is the best.  Making `JobV1` generic wouldn't solve the problems here, because `BaseEstimator` and so on aren't generic, and they define the return value of `run` to be just `Job`, which has no methods defined.  I think you'd either have to do what you've done and manually override the type hints, or make `BaseEstimator` generic over a `TypeVar("JobT", bound=Job)` (I think it's covariant in this type too).

**Comment by ikkoham** [comment]
@jakelishman Thank you for your advice. I updated the code. Is this correct?

**Comment by ikkoham** [comment]
I believe #9480 will fix the lint error.

**Review by jakelishman — DISMISSED** [review]
I can't comment on whether the type bounds you've chosen are precisely what the interface is meant to be (I assume that you're correct), but the implementation of them looks fine to me.

**Comment by jakelishman** [comment]
I can re-approve once the conflicts are fixed.  Looks like it's just super minor stuff.

**Comment by ikkoham** [comment]
@jakelishman Thank you very much! For the bound, this PR does not should neither strengthen nor weaken the restrictions of the type.

**Review by t-imamichi — APPROVED** [review]

**Review by jakelishman — APPROVED** [review]

**Pull request merged**
