### PR TITLE
Make `ComputeUncompute` compatible with runtime primitives

### PR DESCRIPTION
**Pull request by ElePT**
### Summary
This PR adapts certain checks for the [terra `Options` class](https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/providers/options.py) to also accept the [`qiskit-ibm-runtime` `Options` class](https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/qiskit_ibm_runtime/options/options.py) so that the class runs with the runtime primitives.

### Details and comments
WIP, more tests to be performed after latest updates on the runtime repo.

### CODE REVIEW

**Review by jakelishman — CHANGES_REQUESTED** [review]
We can't have provider-specific code in Terra.  If the options are part of the interface, then Terra can _only_ use the interface to access them, and if that doesn't work, the runtime provider needs to fix their implementation.  If they're not part of any interface, then Terra can't interact with them - if it needs to, they need adding to a defined interface.

*edit*: while obviously this code doesn't rise to the same level yet, this sort of layer violation is how the successor to the `QuantumInstance` would appear.

**Comment by woodsp-ibm** [comment]
Aren't we going to hit the same issue with gradients. It seems to me the larger problem is that the core function of a primitive should be the same - i,e if options are dealt with via an options class why do we have to deal with them differently. Sure different optional capabilities within is fine but methods to add, query, update etc ought to be compatible.
(Having seen your message Jake I thought I had posted this earlier - had not hit the button!)

**Review by mtreinish — CHANGES_REQUESTED** [review]
I'm strongly opposed to this change, we should be building algorithms off a common shared interface and not special casing for what the qiskit-ibm-runtime implementation is doing, especially if they're not using the same interface as everyone else. If the runtime provider isn't using the common shared abstract interface that's a bug in the qiskit-ibm-runtime package which needs to be fixed over there. If the primitives interface is insufficient for some reason we can evolve it (hopefully more gracefully than was done in 0.22.0 with the `.run()` transition which was a violation of our backwards compatibility guarantees).

**Comment by 1ucian0** [comment]
> the qiskit-ibm-runtime package which needs to be fixed over there.

I think this refers to https://github.com/Qiskit/qiskit-ibm-runtime/pull/580

**Comment by jyu00** [comment]
So the [base primitive](https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/primitives/base/base_primitive.py#L30) says the `options` into `__init__` is of type `dict`, which is allowed by the primitives in `qiskit_ibm_runtime`.

**Comment by Cryoris** [comment]
Actually, since https://github.com/Qiskit/qiskit-ibm-runtime/pull/569 we should be good right? Since that ensured that `<runtime primitive>.options` returns the right type of `Options`. Running it locally on the qiskit-ibm-runtime main branch seems to work for me, so we only have to wait for the runtime release and can close this PR, can't we?

**Comment by ikkoham** [comment]
Yeah. I think runtime already supported the options and update_options.
https://github.com/Qiskit/qiskit-ibm-runtime/blob/300fc1566689c3a4c7771bbb638e3ec22defbeea/qiskit_ibm_runtime/sampler.py#L338-L353


And changing the `__init__`'s argument types are not a Liskov violation.

**Comment by ElePT** [comment]
Thanks for the feedback. I had left this PR as a draft (while ooo) because I had wanted to consult on using provider-specific code in Terra first, and I got my answer now. I had also not seen that https://github.com/Qiskit/qiskit-ibm-runtime/pull/569 had added `update_options`, so I agree that we can just close it, as @Cryoris suggested.

**Pull request closed without merging**
