### PR TITLE
Fix wrong argument supplied to _identity_op()

### LINKED ISSUE #9197: commutation_checker.py tries to create identity operator with size 2^(2^num_qubits)
### Environment

- **Qiskit Terra version**: 0.22.2
- **Python version**: 3.10.8
- **Operating system**: Manjaro Linux 22.0.0

### What is happening?

I am trying to transpile a deep 10 qubit circuit with optimization_level=3. This results in
> ValueError: Maximum allowed dimension exceeded" in qiskit/circuit/commutation_checker.py, line 27, in _identity_op

### How can we reproduce the issue?
I broke my code down to this simple example:
``` 
import numpy as np
from qiskit import Aer, transpile, QuantumCircuit
from qiskit.circuit.library import XGate

n_qubits = 4
circ = QuantumCircuit(n_qubits + 1)
ctrl_str = format(np.random.randint(0, 2**n_qubits), "b").zfill(n_qubits)
mcx_gate =  XGate().control(num_ctrl_qubits=n_qubits, ctrl_state=ctrl_str).repeat(2)
circ.append(mcx_gate, list(range(n_qubits + 1)))
transpile(circ, backend=Aer.get_backend("aer_simulator"), optimization_level=3)
```
This fails with 
> numpy.core._exceptions._ArrayMemoryError: Unable to allocate 32.0 GiB for an array with shape (65536, 65536) and data type float64

on my system with 16GiB of memory.

### What should happen?

Transpilation should proceed without any issues.

### Any suggestions?

Simple fix: _identity_op() in commutation_checker.py takes as argument num_qubits:
https://github.com/Qiskit/qiskit-terra/blob/e775b4d19ad62558f30f39814b3d923ce03c8654/qiskit/circuit/commutation_checker.py#L24-L28
but is called with 2**num_qubits instead:
https://github.com/Qiskit/qiskit-terra/blob/e775b4d19ad62558f30f39814b3d923ce03c8654/qiskit/circuit/commutation_checker.py#L145-L147
So we simply need to replace the argument in line 147 with `extra_qarg2`. I don't know how to fix an issue unfortunately.

### PR DESCRIPTION
**Pull request by mstnb**
### Summary
This fixes a typo in the CommutationChecker where 2**num_qubits was passed to _identity_op instead of num_qubits.

### Details and comments
Fixes #9197.

### CODE REVIEW

**Review by jakelishman — COMMENTED** [review]
This looks correct, thanks for the quick response!  Please could you also add a test in the file `test/python/circuit/test_commutation_checker.py` that we get a correct result - something like
```python
from qiskit.circuit import CommutationChecker, Qubit
from qiskit.circuit.library import XGate

qargs = [Qubit() for _ in [None]*8]
CommutationChecker().commute(XGate(), qargs[:1], [], XGate().control(7), qargs, [])
```
should be `False`, for example, and will completely blow up Numpy without your fix.  You could write a test about that.

We also need to [add a short release note](https://github.com/Qiskit/qiskit-terra/blob/main/CONTRIBUTING.md#release-notes) - if you've done `pip install reno` already, you should be able to run `reno new --edit fix-commutation-checker-size` and remove everything but the `fixes` section (and write a sentence there briefly explaining what was fixed).

**Comment by mstnb** [comment]
Okay, is there any naming convention for these test cases? And I guess all the methods in the QiskitTestCase are called automatically so I can simply add a new method?

**Comment by jakelishman** [comment]
Sorry for the delay in responding here.  As long as the method name starts with `test_` (and doesn't clash with another), yeah, it gets called automatically - `QiskitTestCase` is a subclass of [Python's built-in `unittest.TestCase`](https://docs.python.org/3/library/unittest.html), so all the assertion methods on those classes should work as well.

**Comment by mstnb** [comment]
Hi, I didn't get to work on this any sooner. I now added a simple unit test and release note. I wanted to merge the upstream changes to my repo to be able to push my changes. Apparently I pressed the wrong button now, sorry for that.
I messed something up on my local repo, trying to get that fixed.

**Comment by jakelishman** [comment]
A "detached HEAD" state in git means you've just got a commit checked out that isn't the end point of any branch.  If you've not got any changes in your working directory, you can just `git checkout <branch>` where `<branch>` is wherever you want to get back to.

If you've got the changes you want to push in your local copy right now, but `git` is saying weird things, then you might want to try copying the files with changes in to somewhere safe, then running
```
git fetch origin
git checkout bug-9197-fix
git merge origin/bug-9197-fix
```

Ideally this will just update your local branch with the changes that have happened to the remote on GitHub, and then you'll just be able to run `git push` to update GitHub with the changes you've made locally.  The point of copying the files is just so you don't lose your changes if something goes wrong.

Don't worry - there's nothing you can do that can break our side of things, and the worst that can possibly happen is that your branch gets too messed up, and then we can close this and you can just make a new pull request.

**Comment by mtreinish** [comment]
To unblock this since the same bug being fixed by this was reported again in #9693 I pushed up the test proposed by @jakelishman  and also added a release note.

**Review by mtreinish — APPROVED** [review]

**Review by jakelishman — APPROVED** [review]

**Pull request merged**
