### PR TITLE
Fixed issue 2788 by updating qiskit/visualization/matplotlib.py

### PR DESCRIPTION
**Pull request by MozammilQ**
### Summary
Fixes: #2788 

### Details and comments

Simple fix: just reduced the extra x_offset from 0.5 to 0.05 in both the quantum register and classical register parts of "_draw_regs_sub"
defined in : qiskit/visualization/matplotlib.py

This changes the x_offset of the parallel lines drawn for both the quantum and classical registers

After the fix, the result looks like this:

changed_fix_issue_2788

Earlier, before the fix, the result was like this

before_fix_issue_2788

In my opinion reducing the x_offset any less than 0.05 makes the figure look unpleasant to eyes so I kept it to 0.05 only

### CODE REVIEW

**Comment by MozammilQ** [comment]
@1ucian0 

While trying to fix the issue, I am sure I can break it also because I am still learning.
So, I humbly request the reviewers to guide me with their words, if they find me lost.  :)

Maybe this time I have got @nonhermitian words in #2788  right --->   " space on the line between the qubit label and the first gate "


Before fix the plot looked like :-
before_fix



After the fix the plot looks like :-

after_fix

git diff    shows this -->

diff --git a/qiskit/visualization/matplotlib.py b/qiskit/visualization/matplotlib.py
index 65d86ca8..49f59976 100644
--- a/qiskit/visualization/matplotlib.py
+++ b/qiskit/visualization/matplotlib.py
@@ -66,10 +66,10 @@ class Anchor:
         if self.__fold > 0:
             if h_pos + (gate_width - 1) > self.__fold:
                 index += self.__fold - (h_pos - 1)
-            **x_pos = index % self.__fold + 1 + 0.5 * (gate_width - 1)
+            x_pos = index % self.__fold + 0.5 + 0.5 * (gate_width - 1)**
             y_pos = self.__yind - (index // self.__fold) * (self.__reg_num + 1)
         else:
-            **x_pos = index + 1 + 0.5 * (gate_width - 1)**
+            **x_pos = index + 0.5 + 0.5 * (gate_width - 1)**
             y_pos = self.__yind
 
         # could have been updated, so need to store
@@ -595,7 +595,7 @@ class MatplotlibDrawer:
                          color=self._style.tc,
                          clip_on=True,
                          zorder=PORDER_TEXT)
-            **self._line([self.x_offset + 0.5, y], [self._cond['xmax'], y],
+            self._line([self.x_offset + 0.05, y], [self._cond['xmax'], y],**
                        zorder=PORDER_REGLINE)
         # classical register
         this_creg_dict = {}
@@ -626,7 +626,7 @@ class MatplotlibDrawer:
                          color=self._style.tc,
                          clip_on=True,
                          zorder=PORDER_TEXT)
-            **self._line([self.x_offset + 0.5, y], [self._cond['xmax'], y], lc=self._style.cc,
+            self._line([self.x_offset + 0.05, y], [self._cond['xmax'], y], lc=self._style.cc,**
                        ls=self._style.cline, zorder=PORDER_REGLINE)
 
         # lf line





If it looks fine then I will create another Pull Request, otherwise I will retry.

**Comment by 1ucian0** [comment]
Sorry this PR slipped through the cracks. I think there was a confusion on who was on it. I think the approach after "After the fix the plot looks like" makes sense.

Maybe breaks when the only instruction is measure, since might overlap the classical wire count.

**Comment by 1ucian0** [comment]
Also, test it with `initial_stage`.

**Comment by 1ucian0** [comment]
@MozammilQ ping?

**Comment by MozammilQ** [comment]
Busy elsewhere, I will look into it when I finish here, need some more time :)

**Comment by 1ucian0** [comment]
MPL circuit drawer issues are piling up, since we dont have a good way to track changes on it. I'm putting this PR `on hold` (meaning "do not merge yet") until https://github.com/Qiskit/qiskit-terra/pull/4544 (or a similar solution) gets in.

**Comment by 1ucian0** [comment]
#4544 is merged... Let's add a test with the new method!

I will try helping, but fill free to do it yourself and ask me if any question.

**Comment by MozammilQ** [comment]
I got the message just now, I have been far away from my workspace. I don't know when I will be back. So, probably I should close this PR.

**Comment by amitracal** [comment]
Is this still on hold or can I try to solve this one ?

**Comment by 1ucian0** [comment]
Feel free to jump in @amitracal .

I'm closing this PR.

**Pull request closed without merging**
