### PR TITLE
default to mpl with text fallback for circuits

### PR DESCRIPTION
**Pull request by nonhermitian**
### Summary
One part of #2319

### CODE REVIEW

**Comment by nonhermitian** [comment]
This needs to be tweaked after #2331 is merged.

**Comment by nonhermitian** [comment]
@mtreinish, A test you added in #2331 `test_default_backend_auto_output_without_mpl` seems to fail for me.  It looks as if the mocking for `HAS_MATPLOTLI=False` does not stick.  Inserting a `print` in the test shows that it is still `True`.  As I have no idea how the mocking works, your help would be most appreciated.

**Comment by mtreinish** [comment]
Ah, the issue is because the logic to module level now, so where we're mocking in that test no longer works. I'll take a look and see if I can come a fix for that in a bit.

**Comment by ajavadia** [comment]
Does #2319 actually ask for mpl to be the default drawer? It asks for mpl to have colors by default... @jaygambetta?

**Comment by mtreinish** [comment]
Sorry I said that I would look at the test mocking shortly and completely forgot about it. But, as I remembered to fix the tests again I started thinking more about this change and I wonder if we really want to do this. I have a couple of concerns, the first being we've defined the visualization interface as stable and changing the default behavior would break that (existing users with mpl installed correctly would have draw calls change). For example, a code snippet I've seen a bunch of places is something like:
```
qc = QuantumCircuit(1)
qc.x(0)
print(qc.draw())
```
(which honestly I don't understand because you can just do `print(qc)`, but people seem to like it) If people are using that script they could potentially going from working as expecting and printing the actual circuit with the text drawer to printing `Figure(334.444x108.694)`. The other concern is the use of fallbacks by default. We had this before when it was just latex and mpl and decided to change that because it was too surprising for users. When they called the circuit_drawer() they didn't know which backend they were going to get and we wanted a more predictable interface for users. While this isn't the same type of fallback (since it's based on an ImportError instead of a runtime error) I do think the same concerns still apply. For example if we consider the same example above when copying it between 2 machines it could potentially behave differently (going from mpl to text or vice versa).

**Comment by nonhermitian** [comment]
The stated goal is to have parity between qiskit and the IQX qiskit installations.  The latter having 'mpl' set by default in order to match the circuit composer.  Thus we want an user, by default, to have the niceties of the mpl backend if available.

**Comment by ajavadia** [comment]
Should we close this?
My main concern is speed. For a 20 q circuit, mpl takes a couple seconds to render, whereas text is almost instantaneous.

**Comment by nonhermitian** [comment]
I will just close this

**Pull request closed without merging**
