### PR TITLE
Corrected the error in the display of multi-letter subscript of a register

### LINKED ISSUE #3520: An error occurs when displaying multiple Qbits with subscript names set in QuantumRegister using the QuantumCircuit draw method
### Information

- **Qiskit Terra version**: 0.10.0
- **Python version**: 3.7.4
- **Operating system**: Win10

### What is the current behavior?
Hi Team,

There is no problem when displaying 1Qbit with the subscript name set in QuantumRegister with the draw method of QuantumCircuit.

image

However, An error ( ParseFatalException ) occurs when displaying multiple Qbits with subscript names set in QuantumRegister using the QuantumCircuit draw method

image

By the way, if {} is not added, it will be displayed as follows:

image

### Steps to reproduce the problem
As I wrote above

### What is the expected behavior?
I would like to be able to display multiple Qbits using the QuantumCircuit draw method for the subscript name set by the user in QuantumRegister.

When displaying multiple Qbits with the QuantumCircuit draw method, a subscript of the number is added, so I would like the subscript specified by the user to be displayed even before the number

### Suggested solutions
Please let me know if there are any method at this time

Thank you.

### PR DESCRIPTION
**Pull request by TharrmashasthaPV**
### Summary

Fixes #3520 .

### Details and comments

There was an error in displaying the subscript names on a named register when a circuit is printed using circuit.draw(output="mpl"). The display error was particularly seen when the subscript of the name of a register contains more than a single letter (eg. qr_alice). When the name is provided in latex format (like qr_{alice}), compilation error was observed. This has been corrected by updating matplotlib.py. The register name is now displayed properly when provided in latex format (eg. qr_{alice}).

### CODE REVIEW

**Comment by ajavadia** [comment]
TharrmashasthaPV  seems like you have deleted your repository so this PR cannot be merged. If you want you can redo the PR.

**Comment by 1ucian0** [comment]
I'm adding this fix in https://github.com/Qiskit/qiskit-terra/pull/3663/commits/2d8231d58c33f2a2f7aa4172b2248f187a9c3e87 to #3663 becuase affects the same line.

**Comment by 1ucian0** [comment]
If #3663 gets merged, this PR can be closed (I added @TharrmashasthaPV  as a co-author of https://github.com/Qiskit/qiskit-terra/commit/2d8231d58c33f2a2f7aa4172b2248f187a9c3e87)

**Comment by TharrmashasthaPV** [comment]
@ajavadia . Sorry for the inconvenience caused. I should have done it by mistake. And thanks @1ucian0 for adding this up with your PR.

**Pull request closed without merging**
