### PR TITLE
Improve CONTRIBUTING.md

### LINKED ISSUE #7692: Fix contributing doc
### What is the expected enhancement?

While preparing to submit #7688 I came back to [CONTRIBUTING.md](https://github.com/Qiskit/qiskit-terra/blob/main/CONTRIBUTING.md) to review the relnotes process. I detected a small text typo that I propose fixing in the PR linked below.

### PR DESCRIPTION
**Pull request by omarcostahamido**
- improve sentence articulation.
- this fixes #7692

### CODE REVIEW

**Comment by omarcostahamido** [comment]
@mtreinish do you think this PR, which is only fixing small things, could include some change to clarify what you taught me yesterday [here](https://github.com/Qiskit/qiskit-terra/pull/7688#issuecomment-1047258326)?
For example, on the yaml sample, instead of:

    The ``qiskit.QuantumCircuit`` module has a new method ``foo()``. This is
    the equivalent of calling the ``qiskit.foo()``to do something to your
    QuantumCircuit.

have it say:

    The ``qiskit.QuantumCircuit`` module has a new method ``foo()``. This is
    the equivalent of calling the :func:`~qiskit.foo()`to do something to your
    QuantumCircuit.

And then on the following paragraph include: 

    Note that you can use sphinx [syntax for cross-references](https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#cross-referencing-python-objects).

❓

**Comment by mtreinish** [comment]
Yeah, I think we can definitely update the example release note, but I'd probably change it to:

```rst
The :class:`.QuantumCircuit` class has a new method :meth:`~.QuantumCircuit.foo`.
This is the equivalent of calling the :func:`~qiskit.foo`to do something to your
:class:`.QuantumCircuit` to your object
```

just to use references everywhere.

As for the comment about the cross reference syntax. I think it's probably better to just link to the sphinx restructured text primer https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html as the contents of a release not get combined into a sphinx document as part of the larger documentation build, so any feature in sphinx is available to the release notes, not just the cross-refs.

**Comment by omarcostahamido** [comment]
Sorry for the delay. I've updated this now.
Please let me know if it look good now.
Thank you.

**Review by mtreinish — APPROVED** [review]
LGTM, thanks for making these updates

**Comment by omarcostahamido** [comment]
@mtreinish thank you, for helping me.

**Pull request merged**
