### PR TITLE
reorganize passes directory

### PR DESCRIPTION
**Pull request by ajavadia**
Since the passes are getting more and cluttered I started organizing them a bit, comments welcome.

### CODE REVIEW

**Comment by 1ucian0** [comment]
It's probably easier to discuss this in a issue, before writing a PR. Anyway, here is a summary of the current view, if I'm understanding correctly (not implying that I agree):

### Layout Selection (Placement)
`passes/layout/`
- SetLayout
-    TrivialLayout
-    DenseLayout
-    NoiseAdaptiveLayout
-    CSPLayout
-    ApplyLayout
-    Layout2qDistance
-    EnlargeWithAncilla
-    FullAncillaAllocation

### Swap Insertion (Routing)
`passes/swap/`

-    BasicSwap
-    LookaheadSwap
-    StochasticSwap

### Basis Change
`passes/basis/`
 - Decompose
 - Unroll3qOrMore
 - Unroller

### Optimizations
`passes/optimization/`
 -  Optimize1qGates
- Collect2qBlocks
-    ConsolidateBlocks
-    CXCancellation
-    CommutationAnalysis
-    CommutativeCancellation
-    RemoveDiagonalGatesBeforeMeasure
-    RemoveResetInZeroState

### Circuit Analysis
`passes/analysis/`
-   Width
-    Depth
-    Size
-    CountOps
-    CountOpsLongestPath
-    NumTensorFactors
-    DAGLongestPath

### Additional Passes
`passes/utils/`
-    CheckMap
-    CheckCXDirection
-    CXDirection
-    MergeAdjacentBarriers
-    BarrierBeforeFinalMeasurements
-    RemoveFinalMeasurements
-    FixedPoint
-    DAGFixedPoint

Maybe a short description for each category?

**Comment by ajavadia** [comment]
the category names should be pretty descriptive. 
*layout* passes are responsible for choosing a layout of virtual qubits on physical qubits.
*swap* passes are responsible for inserting swaps.
etc.

The only thing I'm concerned about is when passes do not fall cleanly within one category, for example a pass that chooses both layout and inserts swaps (#2860 has examples of this i think). But I still think some sort of categorization is useful as the number of passes increase.

**Comment by 1ucian0** [comment]
Maybe using a tree categorization? 
```
passes/mapping/layout/<same content>
passes/mapping/swap/<same content>
passes/mapping/CheckCXDirection
passes/mapping/PassesDoingBoth
```

**Comment by itoko** [comment]
I agree that some sort of categorization is useful at this moment and have no concern on your proposing categorization.
The `utils` category would be useful for miscellaneous passes which may be categorized in future.

Just a small comment on directory name. I think `routing` would be slightly better than `swap` in the future.
Because we'd likely to have some routing passes which use N-hop CNOTs (Bridge gates) as well as SWAPs for resolving CNOTs on non-adjacent qubits (e.g. https://arxiv.org/abs/1907.02686) in the future.

**Comment by ajavadia** [comment]
@itoko ok i renamed to `routing`.
@1ucian0 we don't have such passes yet and i think their utility would be limited as they don't scale well. This is just a simple reorg, and I don't want to make it too complicated structurally yet. Once we get more passes in we can re-evaluate.

**Comment by 1ucian0** [comment]
I think an important distinction is with passes running on "physical" circuits (after layout embedded) and virtual circuits (without an associated layout). We should include that info somewhere, not sure if in this reorganization...

**Comment by ajavadia** [comment]
I added release notes. The passes are accessible under the same namespace `qiskit.transpiler.passes`, deprecating their individual files is cumbersome and i'm not sure worth it.
The categorization of what is a physical vs. virtual pass is not clear-cut because optimization passes run on both.

**Pull request merged**
