### PR TITLE
Enhancements for plot_bloch_vector()

### PR DESCRIPTION
**Pull request by Arihant-Joshi**
### Summary
Fixes [#6140 ](https://github.com/Qiskit/qiskit-terra/issues/6140)

The plot_bloch_vector function has been updated to support a new "wave" coord_type, plotting coefficients of the qubit's wave function, and handling the default cases for this.

### Details and comments

Adds the following to the plot_bloch_vector() function of state_visualizations.py

1. Adds the option to supply a list of 2 complex numbers as parameters, which are plotted on the bloch sphere as wave function coefficients when coord_type=="wave"
2. Converts coord_type to lower case to reduce user error while comparing strings.
3. Adds conditions to use the default values of coord_type according to length of bloch[] parameter.
4. Print warning to the user in case coord_type is reverted as per 3.

### CODE REVIEW

**Comment by 1ucian0** [comment]
Hi @Arihant-Joshi, thanks for the contribution and welcome to the community!

Do you mind adding an example in a release note?  Also, we are using black for code formatting now. Can you run `make black` before pushing?

Thanks!

**Comment by 1ucian0** [comment]
hi @Arihant-Joshi ! Are you still working on this? Just to recap, there is a merge conflict and it would be great if you can add some testing in `test/ipynb/mpl/graph/test_graph_matplotlib_drawer.py`.

**Comment by HuangJunye** [comment]
This PR has been staled for more than a year. Should we close it? @1ucian0

**Comment by javabster** [comment]
Closing this PR due to lack of response from contributor. If contributor returns and wants to reopen this just let us know and we can do that 😄

**Pull request closed without merging**
