### PR TITLE
Initial pull requst for review for adding a new QuantumCircuit constructor

### PR DESCRIPTION
**Pull request by BramDo**
### Summary
First commit on #8709
This is a first commit for adding a new QuantumCircuit constructor QuantumCircuit.from_instructions.
It uses a rough interface, so it is missing bookkeeping and set tracking. The code for testing the method from_instruction can be found in circuit_draw.py.

### Details and comments
Method for the constructor
```
@classmethod
    def from_instructions(
        cls, instructions: Iterable[CircuitInstruction], *, name=None, metadata=None, global_phase=0
    ):
        """Return a circuit from instructions

        Returns:
            QuantumCircuit: a circuit from instructions
        """
```

### CODE REVIEW

**Comment by 1ucian0** [comment]
Hi @BramDo, welcome to the community! Take a look to the [contributor guidelines](https://qiskit.org/documentation/contributing_to_qiskit.html) if you didn't already. Also, considering starting with a `good first issue` as `help wanted` issues tend to assume your are familiar with the Qiskit internals and code-style.

You can also pass by `#qiskit-pr-help` on [Slack](https://ibm.co/joinqiskitslack) if you need extra guidance.

**Review by 1ucian0 — CHANGES_REQUESTED** [review]
I dont think this works with classical bits (let allow with conditions). Testing is always needed, but even more for this kind of code with so many corner cases.

The comment https://github.com/Qiskit/qiskit-terra/issues/8709#issuecomment-1241108537 provides really good initial guidance on the direction.

**Comment by BramDo** [comment]
> I dont think this works with classical bits (let allow with conditions). Testing is always needed, but even more for this kind of code with so many corner cases.
> 
> The comment [#8709 (comment)](https://github.com/Qiskit/qiskit-terra/issues/8709#issuecomment-1241108537) provides really good initial guidance on the direction.

Thank you for the review and the helpful changes. I will investigate  how to implement this with classical bits according to the mentioned guidance. Good point about the conditions, that part is still open.  I will go to slack for further questions.

**Comment by BramDo** [comment]
This is still work in progress.

**Comment by kevinsung** [comment]
Bram has dropped out of the QAMP project this PR was for. I will take over this issue. Please close this PR and I'll open a new one.

**Pull request closed without merging**
