### PR TITLE
Fix #7438 - Remove redundant skip in test

### LINKED ISSUE #7438: Enable ignored test in test_fake_backends
### What is the expected enhancement?

While working on #3905 I saw a test which is skipped until https://github.com/Qiskit/qiskit-aer/issues/741 is fixed. Maybe is should be checked again.
https://github.com/Qiskit/qiskit-terra/blob/main/test/python/mock/test_fake_backends.py
```
    @unittest.skip("Skipped until qiskit-aer#741 is fixed and released")
    @unittest.skipUnless(HAS_AER, "qiskit-aer is required to run this test")
    def test_transpile_schedule_and_assemble(self):
        """Test transpile, schedule and assemble on generated backend."""
        qc = get_test_circuit()
```

### PR DESCRIPTION
**Pull request by TheGupta2012**
### Summary
Fixes #7438 by removing redundant 

### Details and comments
This test was disabled wrongly, given that Pull Request 741 in aer was merged and newer versions of aer have been released since.

### CODE REVIEW

**Review by jakelishman — COMMENTED** [review]
You're welcome to go through this and sort it out, but I think it might be a little more complex than just removing the skip.  I had a very brief go before Christmas, and I think I hit some old code in the `ConfigurableFakeBackend` that was pretty out-of-date and might need a fair bit of updating.  I don't remember 100%, though.

**Comment by TheGupta2012** [comment]
> You're welcome to go through this and sort it out, but I think it might be a little more complex than just removing the skip. I had a very brief go before Christmas, and I think I hit some old code in the `ConfigurableFakeBackend` that was pretty out-of-date and might need a fair bit of updating. I don't remember 100%, though.

Okay, I shall look into it. Thanks for the update!

**Comment by TheGupta2012** [comment]
- @jakelishman, would you be able to provide an insight to the most recent test fail as I wasn't really familiar with qiskit pulse. 
- Besides that, `ConfigurableBackend` had a parameter `version` which stood for `backend_version`. This was overlapping with the `version` parameter in the `BackendV2` and thus was changed to fix previous traceback.

**Comment by jakelishman** [comment]
At @javabster's request, I've fixed the merge conflicts that were in this PR in order to have it run its CI again, but I don't know any context. My only comment above was just that I'd attempted to remove the `unittest.skip` line before and seen some failures (and sorry that I never replied to the question at the time).

It's possible that #9168 could be used instead of this PR, but I don't know the context of either PR, nor of the code in question here.

**Comment by 1ucian0** [comment]
Closing in favor #9168 . Thanks!

**Pull request closed without merging**
