### PR TITLE
Fix for conditional single gate plotting using mpl

### LINKED ISSUE #7017: mpl drawer cannot draw circuits conditioned on single bits
### Information

- **Qiskit Terra version**: main
- **Python version**:
- **Operating system**:

### What is the current behavior?
```python

qreg = QuantumRegister(1)
creg = ClassicalRegister(2)
circuit = QuantumCircuit(qreg, creg)
circuit.h(0).c_if(0, True)
circuit.draw('mpl')
```

gives

File "/Users/paul/Desktop/GitHub/qiskit-terra/qiskit/visualization/circuit_visualization.py", line 284, in circuit_drawer
    image = _matplotlib_circuit_drawer(
  File "/Users/paul/Desktop/GitHub/qiskit-terra/qiskit/visualization/circuit_visualization.py", line 679, in _matplotlib_circuit_drawer
    return qcd.draw(filename)
  File "/Users/paul/Desktop/GitHub/qiskit-terra/qiskit/visualization/matplotlib.py", line 345, in draw
    self._draw_ops(verbose)
  File "/Users/paul/Desktop/GitHub/qiskit-terra/qiskit/visualization/matplotlib.py", line 757, in _draw_ops
    self._condition(node, cond_xy)
  File "/Users/paul/Desktop/GitHub/qiskit-terra/qiskit/visualization/matplotlib.py", line 875, in _condition
    clbit_b = min(xy_plot, key=lambda xy: xy[1])
ValueError: min() arg is an empty sequence

### What is the expected behavior?
It should draw.  The text based version does:

```
           ┌───┐    
  q11: ────┤ H ├────
           └─╥─┘    
       ┌─────╨─────┐
c11: 2/╡ c11_0 = T ╞
       └───────────┘
```

### PR DESCRIPTION
**Pull request by paniash**
### Summary

Fixes #7017.  Minor bug fix involving plotting of `QuantumCircuit` object when using conditional single gates like `circuit.h(0).c_if(0, True)`.

### CODE REVIEW

**Comment by 1ucian0** [comment]
This is an unexpectedly short fix :)

Does it make sense @TharrmashasthaPV and @enavarro51 ?

**Comment by enavarro51** [comment]
Probably need @TharrmashasthaPV to weigh in, but isn't this what #6259 fixes? (Which got stuck in CI, by the way).

**Comment by 1ucian0** [comment]
@paniash do you mind adding a test?

**Comment by TharrmashasthaPV** [comment]
Hey. I am just not sure if this is a complete fix. Because for one, the circuit
```python
q = QuantumRegister(1,'q')
c = ClassicalRegister(2,'c')
circuit = QuantumCircuit(q, c)
circuit.h(0).c_if(1, True)
circuit.h(0).c_if(0, True)
circuit.draw('mpl')
```
outputs
image
The label is `0x1` irrespective of the bit the gate is conditioned on. Also, `circuit.draw('mpl', cregbundle=False)` breaks and if a gate is conditioned on a complete register like `circuit.x(0).c_if(c,1)`, the drawer breaks.

**Comment by paniash** [comment]
@TharrmashasthaPV Thanks for pointing it out. Can you confirm if this issue is fixed in #6259? If so, then I'll close this PR.

**Comment by 1ucian0** [comment]
> Which got stuck in CI, by the way

Ups.. unstacking this.

**Comment by 1ucian0** [comment]
https://github.com/Qiskit/qiskit-terra/pull/6259 merged. That seems to solve #7017. If #6259 is incomplete and this PR is the way to go, please reopen it.

**Pull request closed without merging**
