### PR TITLE
Run randomized testing and benchmarks in Azure

### LINKED ISSUE #2921: run randomized_tests and benchmarks on Azure

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

Azure pipelines gives us much faster node start up time and much more
capacity than travis, so we are moving jobs over to azure to speed up
our CI time. This commit moves the randomized testing and comparison
benchmarks over to run in azure pipelines instead of in travis. After
this the only jobs left in travis are release wheel build automation
(see #3009) and the coverage job. 

### Details and comments

The coverage job will need extra setup because coveralls (the service we
use for coverage aggregation) doesn't natively support appveyor, so we'll
have to generate tokens and do extra manual setup before that migration
is possible.

Fixes #2921

### CODE REVIEW

**Comment by mtreinish** [comment]
So the jobs don't work yet, but this was actually a good test, the master azure check `Qiskit.qiskit-terra` passes. Which verifies the `continueOnError` job attribute works as expected, which is what we wanted. Having the benchmarks or randomized testing fail is not something we want to block

**Comment by mtreinish** [comment]
On looking at this in real time I'm not sure that we want to merge it. It looks like it holds up the check until the jobs finish running (even though they're no fatal). For the benchmark tests this adds a ~20 min job to the end of the run which make the jobs take ~40mins. I'm not sure we want to double our time for CI because of this.

**Comment by mtreinish** [comment]
I opened a feature request on azure pipelines for a `fast_finish` flag: https://developercommunity.visualstudio.com/idea/728163/fast-finish-flag-for-stage.html that's what we leveraged in travis to not block the CI return on the slow running jobs.

**Comment by 1ucian0** [comment]
The feature request process for azure seems to be slow. Shall we close this PR in the meanwhile? We can track the status in #2921

**Comment by mtreinish** [comment]
Yeah I'm just going to close this now that we have a Travis subscription for all of Qiskit there isn't as much of a pressing need for this. If the need arises we can always reopen this

**Pull request closed without merging**
