### PR TITLE
Remove deprecated functionality from extensions, qasm, and dagcircuit modules

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

This commit goes through qiskit.extensions, qiskit.qasm, qiskit.util,
and qiskit.dagcircuit modules and cleans up deprecated functionality
that has gone through a full deprecation cycle and no longer needs to
be supported.

### Details and comments

### CODE REVIEW

**Comment by jakelishman** [comment]
We may need to leave `qiskit.util` another cycle, but issue a proper deprecation warning out of it.  Of what I've got cloned, Aer and the old IBMQ still reference the old form, and looking at `qiskit/util.py`, it's not actually issuing any deprecation warnings, so people may not be aware.  (See the two PRs linked above.)

For linking purposes: Ali also has #7011 to clean up `qiskit.circuit`.

**Comment by mtreinish** [comment]
Hmm, yeah I'll back it out the `qiskit.util` removal from this pr and do it later. We couldn't add deprecation warnings because the only way I could think of doing it besides add a wrapper function for each function in the module was to use a module getattr function. But that was added in python 3.7 so it wouldn't work on 3.6.

**Comment by jakelishman** [comment]
Why not just issue the deprecation warning raw in the `util.py` file?  As long as `qiskit/__init__.py` doesn't import it, it won't get triggered until a user does the import, and modern Terra doesn't import it.

**Comment by jakelishman** [comment]
I mean something like having the file be:
```python
import warnings
from qiskit.utils import *

warnings.warn("Use qiskit.utils instead", DeprecationWarning)
```

It isn't imported by Terra during init, so users won't see the warning until they import it themselves, and you can't use any functions through its namespace without importing it.  The warning can be attached to the import, rather than the member access, I think?

**Comment by mtreinish** [comment]
I did try that when I first pushed up #5420 but back then `qiskit.util` was getting imported by things in the root of the package (probably from aer or ibmq which at the time got imported if available for `qiskit.Aer` and `qiskit.IBMQ`). But, yeah we can do that now as things have shifted around it should work fine. Do you want to push up a PR adding the warning?

**Comment by jakelishman** [comment]
Sure - I'll do it in a bit.  I want to go through and check the other downstream qiskit packages first for uses of `qiskit.util`, and see if there's a sensible way we can put in the deprecation warning without heavily leaking that through to users; the functions in `qiskit.utils` are often the type that get actually run during module initialisation, so there's a good chance even importing Aer/whatever will show something to users (though perhaps #7204 will help with that).

**Review by jakelishman — APPROVED** [review]
These deprecations look good to me now.

**Pull request merged**
