### PR TITLE
Test circuit drawer uses "π" instead of "pi"

### LINKED ISSUE #4959: Show pi in the text drawer as π
### What is the expected enhancement?

Based on a discussion in #4931, there's interest in displaying pi in the text drawer as `π `instead of `pi`.
``` 
                   ┌─────────┐               ┌─────────┐
Change from   q_0: ┤ RX(pij) ├     to   q_0: ┤ RX(πj)  ├
                   └─────────┘               └─────────┘
```
To do this on all platforms requires completion of #4900 and modifying pi_check and 24 tests.

### PR DESCRIPTION
**Pull request by alejomonbar**
### Summary

Fixed #4959 

### Details and comments
Change pi_check function when output is "text" from "pi" to "π". Also, the test cases were updated to check different circuits with the new symbol "π". Different encoders were tested to see if they accepted "π" and gave good results.

### CODE REVIEW

**Comment by enavarro51** [comment]
@1ucian0 We'd discussed also doing the dagger for sdg, tdg, and sxdg for the text drawer. Something like `S†`. Unicode is 2020. Easy to do in text drawer `special_label` but not sure whether there are encoding issues for this and there would be more test modifications. Should we open another issue for this?

**Comment by 1ucian0** [comment]
I dont think there is `†` in cp437. I think that one should depend on `self.encoding`. For another PR...

**Review by 1ucian0 — APPROVED** [review]
Thanks! Welcome to the community!

**Comment by alejomonbar** [comment]
> Thanks! Welcome to the community!

Thank you for helping me. Looking forward to continuing helping

**Comment by 1ucian0** [comment]
I dont think there is `†` in cp437. I think that one should depend on `self.encoding`. For another PR...

**Pull request merged**
