### PR TITLE
Fix deprecation warning for `deprecated_functionality`

### PR DESCRIPTION
**Pull request by garrison**
### Summary

This fixes some deprecation warnings that pop up during my use of `main` (or, equivalently, `qiskit-terra==0.22.0rc1`)

### CODE REVIEW

**Review by mtreinish — APPROVED** [review]
Lol, I haven't gone through the release notes yet, I didn't realize that we deprecated a deprecation decorator. I find that quite amusing

This LGTM, thanks for identifying and fixing this.

**Comment by wshanks** [comment]
> I didn't realize that we deprecated a deprecation decorator. I find that quite amusing

I found it confusing that the PR that did this (#8696) didn't have a single joke in it.

**Comment by garrison** [comment]
Lint is failing because `qiskit.pulse.transforms.alignments -> qiskit.utils` means there are now cyclic imports.

**Comment by mtreinish** [comment]
Sigh, our import "tree" is kind of a disaster it looks like the root cause is that the utils path is shared with the new decorator and the quantum instance (which imports everything because it's a big layer violation). I think the best way to handle this is probably to just avoid the decorator and emit the warning inline with the desired text.

**Review by mtreinish — DISMISSED** [review]

**Comment by garrison** [comment]
While writing the warning string, I learned that these `to_dict()` methods were deprecated as part of #7300, which was part of Terra 0.21.

**Comment by mtreinish** [comment]
It looks like reno is getting confused by the merge commit which moved a bunch of release notes in #8850 and is causing it to get confused about the source of release notes. I think the only way to fix that is to rebase the branch on main and force push it to your fork so that reno can track the history with the file moves.

**Review by jakelishman — APPROVED** [review]
I'd love to have the time to go through Terra and reorganise the imports such that there's a proper import-time hierarchy, places that import "higher" in the hierarchy only do it at runtime, and it's all enforced by lint, but it's such a complex task, I've no idea when that would become possible.  This seems sensible in the interim.

**Pull request merged**
