### PR TITLE
Improve the performance of taper in opflow

### PR DESCRIPTION
**Pull request by ikkoham**
### Summary

This improves the performance that is reported in the slack:
https://qiskit.slack.com/archives/CB6C24TPB/p1658860652834669

image

### CODE REVIEW

**Review by mrossinek — APPROVED** [review]
I can verify that this fixes the linked problem discussed on Slack :+1: 

Thanks for the quick fix, @ikkoham!

**Review by Cryoris — COMMENTED** [review]
LGTM, could you add a bugfix releasenote?

**Comment by MarcoBarroca** [comment]
Thanks a lot for the quick fix on this! 🙂

**Comment by ikkoham** [comment]
Do we need the release note for the performance improvement PR?

**Comment by Cryoris** [comment]
Ah I thought it would count as bugfix as your screenshot in the description said that it didn't finish due to memory issues (which I would consider a bug) 😄

**Comment by MarcoBarroca** [comment]
Hey, so this still seems to be an issue with bigger molecules. When trying to calculate the Z2Symmetries for LiI without using the FreezeCoreTransformer() or when trying with an I2 molecule with or without FreezeCoreTransformer() it still fails to complete due to memory.

Here is the code for I2:

```
#Define Molecule
molecule = Molecule(
             # coordinates in Angstrom
                  geometry=[
                            ["I", [2.666 ,0.0 ,0.0]],
                            ["I", [0.0 ,0.0,0.0]]
                            ],
                     multiplicity=1,  # = 2*spin + 1
                     charge=0
                    )
    
#Set driver
driver = ElectronicStructureMoleculeDriver(
    molecule=molecule,
    basis="sto3g",
    driver_type=ElectronicStructureDriverType.PYSCF,
    )

#Get properties
properties = driver.run()
    
# Spin orbitals occupation
PN_property = properties.get_property("ParticleNumber")

  
#Define the problem

problem = ElectronicStructureProblem(driver)

#Get 2nd Quant Op.
second_q_ops = problem.second_q_ops()
    
num_spin_orbitals = problem.num_spin_orbitals
num_particles = problem.num_particles
    
hamiltonian = second_q_ops[0] #Set Hamiltonian

#Get Pauli OP
mapper=ParityMapper()
converter = QubitConverter(mapper
                                ,two_qubit_reduction=True
                                ,z2symmetry_reduction='auto'
                           )
    
#Final OP
qubit_op = converter.convert(hamiltonian,num_particles=num_particles,sector_locator=problem.symmetry_sector_locator)
print(qubit_op.num_qubits)
```

**Comment by ikkoham** [comment]
Hi @MarcoBarroca, thank you for your report.

I2 has `register length=108, number terms=13140176`. That is huge molecule, we cannot convert now.
The code fails in `ParityMapper()`, so if you don't use `two_qubit_reduction()`, the code fails.

@mrossinek The code doesn't work for the reasons above, and we can't handle this scale, but could you please consider this issue in qiskit_nature?

**Comment by mrossinek** [comment]
@MarcoBarroca At this scale, you are very likely running into the performance issues of the `QubitMapper`. We're actively working on improving that; see for example here: https://github.com/Qiskit/qiskit-nature/issues/644

**Review by Cryoris — DISMISSED** [review]

**Comment by ikkoham** [comment]
There is no end to performance improvement. I still think it could be improved... maybe...

**Review by Cryoris — APPROVED** [review]

**Pull request merged**
