### PR TITLE
Add tests to check that results act consistently for all backends

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary
This commit adds some additional tests that loop over all available
backends to verify that certain common results operations work on all
the available backends. It turns out during the course of a normal test
run we don't verify that results operations work with all the available
(in-repo) backends. This has led to issues like #1119 and #1116 because
we didn't have this verification. This adds the start of the testing
coverage needed, it only adds coverage for adding results. But, we can
expand this to cover additional results operations in the future.

### CODE REVIEW

**Comment by mtreinish** [comment]
This is blocked on #1125

**Comment by mtreinish** [comment]
#1125 has merged so this should be good to go now.

**Comment by mtreinish** [comment]
Fwiw, the history of this patch is that I originally included it as part of #1118  which I wrote to specifically verify the failure mode from the statevector simulator on all the backends. I had to split it out because it caught issues in the clifford simulator. I'm fine making the changes, especially on the ibmq side. But, as far as changing the operation run I'm not sure which to use. I picked result addition because of the history of this patch, and viewed it as more of a starting point than anything.

**Comment by diego-plan9** [comment]
Closing as #1373 includes similar tests in `test_aer_simulators.py` and `test_ibmq_backends.py`, which hopefully serve as the starting point mentioned in the last comment.

**Pull request closed without merging**
