### PR TITLE
Use evd driver for eigh in TwoQubitWeylDecomposition

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

The hermitian optimized eigen solver function in scipy has shown
to possibly produce varied results in different environments. For
example, the matrix returned by the `eigh()` call in the
`TwoQubitWeylDecomposition` class's `__init__` method when called for
a CXGate:
```python
TwoQubitWeylDecomposition(Operator(CXGate()))
```
was observed to be
```
[[ 0.70710678  0.         -0.70710678  0.        ]
 [ 0.         -0.70710678  0.          0.70710678]
 [ 0.          0.70710678  0.          0.70710678]
 [ 0.70710678  0.          0.70710678  0.        ]]
```
on one system/environment but
```
[[ 0.70710678  0.         -0.70710678  0.        ]
 [ 0.          0.70710678  0.          0.70710678]
 [ 0.         -0.70710678  0.          0.70710678]
 [ 0.70710678  0.          0.70710678  0.        ]]
```
on a different environment. This difference was resulting in
inconsistent decompositions being generated and made reproducing results
from the transpiler difficult. In testing the numpy equivalent
function [2] has proven to be more reliable across different
environments. It turns out that this was because the LAPACK driver
used by the numpy routine was `evd` while the default driver for scipy
was `ev`. Switching the scipy driver to use `evd` too fixes this issue. This
commit switches the `eigh()` usage in the `TwoQubitWeylDecomposition`
class to explicilty set the driver to `evd instead of the default `ev`,
this should fix the inconsistent decompositions we were seeing between
environments.

### Details and comments

[1] https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.eigh.html
[2] https://numpy.org/doc/stable/reference/generated/numpy.linalg.eigh.html

### CODE REVIEW

**Comment by mtreinish** [comment]
I just remembered that we will need to bump the minimum version of numpy in the requirements list to 1.18.0 with this. The numpy eigh() function was added in 1.18.0

**Comment by nonhermitian** [comment]
So they both use zheevd in general. So it seems hard to fathom that there is any difference between the two when using that driver. Scipy selects between multiple drivers, but it can also be manually set. Did you try setting the driver explicitly in the scipy version?

**Comment by mtreinish** [comment]
I didn't mostly because I assumed the driver selection would be deterministic and it would be using the same driver on both systems I was testing on (@ajavadia also had the same issue on two of his systems). I'll give setting a driver explicitly a try on Monday. 

But at the end of the day if this solves the issue for us I don't see the harm in switching to use the numpy routine even if why it's happening is a bit of a mystery. My first thought after figuring out that `eigh()` was the source of the issue was a local BLAS+LAPACK version difference, but at least in my case the versions installed were from the same linux distro packages (at the same versions).

**Comment by nonhermitian** [comment]
Actually looking theough the docs it is ev by default in scipy and evd in numpy. So driver='evd' in scipy should return the same in both modules

**Comment by nonhermitian** [comment]
And yes not the end of the world, but then we wouldn't need to bump up a dependency for no reason.

**Comment by mtreinish** [comment]
Ok, tested locally on my 2 systems and using evd as the driver produces a consistent result. So I'll update this to just use that with the scipy method. That way we can avoid the requirements bump

**Comment by ajavadia** [comment]
Yes I can confirm this is consistent for me too. Also I found that we can revert much of the roundings introduced in https://github.com/Qiskit/qiskit-terra/pull/4862 and https://github.com/Qiskit/qiskit-terra/pull/4835.
(We still need the M2 rounding but that seems to be it)

**Review by ajavadia — APPROVED** [review]

**Comment by mtreinish** [comment]
@ajavadia do you want me to remove that rounding in this PR or do it in a followup?

**Comment by ajavadia** [comment]
follow up is fine, thanks

**Comment by mtreinish** [comment]
Well it turns out that the `driver` kwarg for scipy was only added in scipy 1.5.0:

https://docs.scipy.org/doc/scipy/reference/release.1.5.0.html#scipy-linalg-improvements

So we should have bumped the minimum version in this PR. But, it turns out chemistry in aqua doesn't work with scipy 1.5 because pyscf caps at <1.5. I opened to https://github.com/Qiskit/qiskit-terra/pull/5263 address this an unbreak aqua ci.

**Pull request merged**
