### PR TITLE
Fix failing PassManager visualization tests

### LINKED ISSUE #3283: Passmanager visualizer tests fail locally
### Information

- **Qiskit Terra version**: Master
- **Python version**:
- **Operating system**:

### What is the current behavior?

When running the unit tests locally off of master the pass manager visualization tests always fail. The traceback:

```
==============================
Failed 2 tests - output below:
==============================

test.python.visualization.test_pass_manager_drawer.TestPassManagerDrawer.test_pass_manager_drawer_basic
-------------------------------------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    b'Traceback (most recent call last):'
    b'  File "/home/mtreinish/git/qiskit/qiskit-terra/test/python/visualization/test_pass_manager_drawer.py", line 80, in test_pass_manager_drawer_basic'
    b"    self.assertFilesAreEqual(filename, path_to_diagram_reference('pass_manager_standard.dot'))"
    b'  File "/home/mtreinish/git/qiskit/qiskit-terra/test/python/visualization/visualization.py", line 46, in assertFilesAreEqual'
    b'    self.assertEqual(cur.read(), exp.read())'
    b'  File "/usr/lib64/python3.7/unittest/case.py", line 852, in assertEqual'
    b'    assertion_func(first, second, msg=msg)'
    b'  File "/usr/lib64/python3.7/unittest/case.py", line 1233, in assertMultiLineEqual'
    b'    self.fail(self._formatMessage(msg, standardMsg))'
    b'  File "/usr/lib64/python3.7/unittest/case.py", line 693, in fail'
    b'    raise self.failureException(msg)'
    b'AssertionError: \'digr[53 chars]abel="[0] FlowLinear";\\n1 [color=red, fontname[2206 chars]n}\\n\' != \'digr[53 chars]abel=FlowLinear;\\n1 [color=red, fontname=helve[2152 chars]n}\\n\''
    b'Diff is 2795 characters long. Set self.maxDiff to None to see it.'
    b''

test.python.visualization.test_pass_manager_drawer.TestPassManagerDrawer.test_pass_manager_drawer_style
-------------------------------------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    b'Traceback (most recent call last):'
    b'  File "/home/mtreinish/git/qiskit/qiskit-terra/test/python/visualization/test_pass_manager_drawer.py", line 95, in test_pass_manager_drawer_style'
    b"    self.assertFilesAreEqual(filename, path_to_diagram_reference('pass_manager_style.dot'))"
    b'  File "/home/mtreinish/git/qiskit/qiskit-terra/test/python/visualization/visualization.py", line 46, in assertFilesAreEqual'
    b'    self.assertEqual(cur.read(), exp.read())'
    b'  File "/usr/lib64/python3.7/unittest/case.py", line 852, in assertEqual'
    b'    assertion_func(first, second, msg=msg)'
    b'  File "/usr/lib64/python3.7/unittest/case.py", line 1233, in assertMultiLineEqual'
    b'    self.fail(self._formatMessage(msg, standardMsg))'
    b'  File "/usr/lib64/python3.7/unittest/case.py", line 693, in fail'
    b'    raise self.failureException(msg)'
    b'AssertionError: \'digr[53 chars]abel="[0] FlowLinear";\\n1 [color=cyan, fontnam[2209 chars]n}\\n\' != \'digr[53 chars]abel=FlowLinear;\\n1 [color=cyan, fontname=helv[2155 chars]n}\\n\''
    b'Diff is 2798 characters long. Set self.maxDiff to None to see it.'
    b''
```

### Steps to reproduce the problem

Run tests locally

### What is the expected behavior?

The tests pass

### Suggested solutions

Either fix or remove these tests, all the image comparison tests are super flaky and provide limited value.

### PR DESCRIPTION
**Pull request by maddy-tod**
### Summary
Fixes #3283 

#3004 extended the PassManager drawing to include the index of the pass, but the reference files were not updated. This PR updates them.

### CODE REVIEW

**Comment by mtreinish** [comment]
Ah, so this means we do not run these tests in CI anywhere, before we merge this we should also update the CI configuration in this PR to include graphviz and any other external requirements we need to make the tests actually run.

**Comment by 1ucian0** [comment]
Additionally, I'm working in some internal refactor for the pass manager object. That might affect this.

**Comment by 1ucian0** [comment]
`On hold` until #3286 gets merged or rejected.

**Comment by mtreinish** [comment]
@1ucian0 we shouldn't block this on that 3286. This is needed so people can actually run the tests locally which is far more critical right now than that PR. If you have graphviz installed and run tests they fail, we need to quickly update this PR to make sure we run these in CI and #3286 will then have to update the images/tests if it breaks the tests. We shouldn't hold up fixing broken tests on another refactor.

**Comment by 1ucian0** [comment]
you are right. This PR only affects tests.

**Pull request merged**
