### PR TITLE
moving Aer

### PR DESCRIPTION
**Pull request by jaygambetta**
The goal of this pr is to move Aer to stale aer if using the local c++ so that clean aer can come in and take its place. Also to move python aer so that it is separate from clean aer

It is still failing test so im in test hell at the moment but import works  @chriseclectic if you want to have a look let me know. I am trying to clear the way for your aer

### CODE REVIEW

**Comment by delapuente** [comment]
I think we should do this after merging #1477.

**Comment by jaygambetta** [comment]
I would rather not as this is more complicated then moving as it is deciding which ones are in aerpy module and the aer module. Also this is blocking the following to speed up aerpy.

**Comment by chriseclectic** [comment]
@jaygambetta @delapuente It might be better to review and merge #1469 before this or #1477 since it only changes the contents of the python simulator backend files and a couple of test files.

**Comment by delapuente** [comment]
Closed in favour of #1484. All the changes made here are included there, in addition to some extra tweaks and a deeper cleaning of Aer.

**Pull request closed without merging**
