### PR TITLE
Add DAGCircuit node contraction and subcircuit replacement.

### PR DESCRIPTION
**Pull request by kdk**
Draft branch of possible implementation for replacement of subcircuits with a DAG (for discussion in #2959 ).

### CODE REVIEW

**Comment by eddieschoute** [comment]
Can one contract a node and just leave it in the DAG, without changing functionality?

**Comment by kdk** [comment]
> Can one contract a node and just leave it in the DAG, without changing functionality?

Not always, some contractions will leave behind an invalid DAG, but if the group of nodes to be replaced forms an uninterrupted subcircuit, contracting it to a single node will be valid (and if the node has the correct definition, the functionality of the circuit will not be changed.) This is like the inverse of decomposing a composite gate.

**Comment by eddieschoute** [comment]
Is that implemented yet? I can't find it.

The fact that it's not interrupted makes sense to me but the nonadjacent merge thing doesn't. It seems to me this is valid in a lot of cases.

**Comment by kdk** [comment]
> Is that implemented yet? I can't find it.
> 
> The fact that it's not interrupted makes sense to me but the nonadjacent merge thing doesn't. It seems to me this is valid in a lot of cases.

Not yet in this branch. As of now, contractions are replaced with an opaque 'contraction' node, but its possible to add it.

The nonadjacent merge case is definitely valid, and it may not need to be exposed as a user visible flag. I left it for now since there may be a case where a user wants to explicitly exclude nonadjacent merges, and there's a possibility the performance of their consistency check will scale differently than that of the adjacent case. We can remove it later if neither of those end up being practical concerns.

**Comment by kdk** [comment]
Closing as superseded by `DAGCircuit.replace_block_with_op` in #7185 .

**Pull request closed without merging**
