### PR TITLE
added a quick_simulate function

### PR DESCRIPTION
**Pull request by edwinagnew**
### Summary
A function which can quickly simulate a QuantumCircuit. It can also take an input string to modify the input. For example to test a 1-bit adder:

`from qiskit import QuantumCircuit, quick_simulate
#make adder
qc = QuantumCircuit(4,2)
qc.cx(0,2)
qc.cx(1,2)
qc.ccx(0,1,3)
qc.barrier()
qc.measure(2,0)
qc.measure(3,1)

#get results
quick_simulate(qc) #returns {'00':1024}
quick_simulate(qc, x="10") # returns {'01': 1024}
etc.`

### Details and comments
I wasn't exactly sure where to place the import statement. At the moment it can be imported as 'from qiskit import simulate' but if it would be better placed in the providers directory then line 82 in qiskit/__init__.py can be moved to qiskit/providers/__init__.py
I also just copied and pasted the license agreement without signing anything anywhere, it that OK?

### CODE REVIEW

**Comment by 1ucian0** [comment]
Hi @edwinagnew, 
This sort of extension on the high level interface is usually discussed in a `discussion` issue first to check for consensus. I would recommend you to submit one of those (no need to close the PR, but setting `on hold` until consensus is reached) and, based on that, decide the direction for this PR.

**Comment by ajavadia** [comment]
Hi, thanks for your contribution. However for this kind of thing you can use the built-in `quantum_info` module which is designed as a native way of extracting quantum information from a circuit (statevector, expectation value, equivalent unitary, counts). So here's how you can do it in a one liner, I don't think we need to create yet another function for this.

```py
from qiskit.quantum_info import *
Statevector.from_instruction(qc).sample_counts(1000)
```

**Comment by edwinagnew** [comment]
Hi, thanks for pointing that out, I wasn't aware and I agree this would be redundant.
 I still believe the functionality of being able to prepare a circuit on a given classical input is useful as I find myself needing that a lot, so could I add that to the sample_counts method?

**Comment by 1ucian0** [comment]
I did not try it, but the functionally you are searching for seems very similar to what https://pypi.org/project/kaleidoscope/ (from @nonhermitian ) offers. Check the example here: https://twitter.com/nonhermitian/status/1306548622012620801

**Comment by nonhermitian** [comment]
Yes it works similar with respect to getting a statevector, unitary, or counts directly from a circuit object. I found this to be extremely handy to have.

**Pull request closed without merging**
