### PR TITLE
ConsolidateBlocks should not fail because "failed to diagonalize M2"

### PR DESCRIPTION
**Pull request by 1ucian0**
Besides the problem with `weyl_coordinates` (see https://github.com/Qiskit/qiskit-terra/issues/3637#issuecomment-612970960), `ConsolidateBlocks` should not fail because the synthesis fails.

This PR considers that and continues even when synthesis fails.

### CODE REVIEW

**Comment by nonhermitian** [comment]
The solution here: https://github.com/Qiskit/qiskit-terra/issues/3637 does not fix this?

**Comment by 1ucian0** [comment]
I think the solucion for #3637 is normalization. The code raising in #3637 is independent from the transpiler. This PR is about the transpiler should continue when synthesis fails (does not matter why).

**Comment by nonhermitian** [comment]
But the user should be explicitly told that consolidate blocks is not being run if that is the case.

**Comment by kdk** [comment]
:+1: We would not have found and fixed the case from #3637 if the failure had been caught silently. The synthesis algorithms aren't expected to fail regularly, so I'm okay with allowing it to raise when it fails.

**Comment by 1ucian0** [comment]
closing in favor of https://github.com/Qiskit/qiskit-terra/pull/4156

**Pull request closed without merging**
