### PR TITLE
Rename InstructionScheduleMap to CircuitInstructionMap

### LINKED ISSUE #3480: Utility function to measure only a subset of qubits using OpenPulse
### What is the expected enhancement?
Currently, measurement in OpenPulse is often done by getting the default measurement schedule from the `CmdDef`:
```
meas = cmd_def.get('measure', qubits=tuple(range(total_number_of_qubits)))
```
This isn't ideal because it will stimulate measurement on all qubits.

More convenient would be to be able to do
```
schedule += measure_qubits(qubits_to_measure: List)
```
where `measure_qubits` is a utility function exposed within `pulse` and `qubits_to_measure` is a subset of all qubits. Only the qubits in `qubits_to_measure` will have a measurement pulse. All qubits will still have to be acquired according to the `meas_map`.

The implementation may be similar to changes in the scheduler which have been started here:
https://github.com/Qiskit/qiskit-terra/pull/3415

### LINKED ISSUE #3592: inconsistent attribute for InstructionScheduleMap
There is an attribute `defaults.circuit_instruction_map` which returns a `InstructionScheduleMap`. The name should be consistent. The latter makes more sense.

### PR DESCRIPTION
**Pull request by taalexander**
### Summary
Closes #3592. This PR renames `InstructionScheduleMap` to `CircuitInstructionMap` and deprecates `InstructionScheduleMap`.

### CODE REVIEW

**Comment by ajavadia** [comment]
Since both "circuit" and "instruction" are used in the circuit model, `CircuitInstructionMap` can be confusing as it is not explicit that you are mapping to a pulse schedule. `InstructionScheduleMap` makes more sense to me.

**Comment by taalexander** [comment]
I'm not sure I agree. This attribute is already in the pulse module and therefore outputting schedules within this context is expected. The unspecified context is what it is mapping which in this case are `circuit instructions` and not `pulse instructions` which also exist. I think the best name would be `CircuitInstructionToScheduleMap` but that is pretty verbose.

**Comment by lcapelluto** [comment]
@taalexander ping me whenever it's ready for review :)

**Comment by lcapelluto** [comment]
can we do `InstructionScheduleMap` and I'll open a new PR with the attribute updated/deprecated only? let's get this over with

**Comment by taalexander** [comment]
Closing per above comment.

**Pull request closed without merging**
