### PR TITLE
mpl drawer update for controlled gates and layering

### LINKED ISSUE #4052: Error in text drawing of open controlled CX and CCX gates
### Information

- **Qiskit Terra version**: 0.13.0.dev0+6002304
- **Python version**: 3.7
- **Operating system**: Ubuntu 18.04

### What is the current behavior?

The control bullets are drawn closed irrespective of the provided control state in CX and CCX gates in text drawer. The same error is observed in CY gate. Other controlled and multi-controlled gates are drawn fine. See below for an instance.

### Steps to reproduce the problem

```
qc = QuantumCircuit(4)
qc.append(XGate().control(1,ctrl_state='0'),[0,1])
qc.append(XGate().control(2,ctrl_state='10'),[0,1,2])
qc.append(XGate().control(3,ctrl_state='100'),[0,1,2,3])
qc.append(YGate().control(1,ctrl_state='0'),[0,1])
qc.append(YGate().control(2,ctrl_state='10'),[0,1,2])
qc.draw('text')
```

### LINKED ISSUE #4148: Circuit marplot lib register and measurement on-top of each other
### What is the expected enhancement?
If the circuit goes over two frames the second frame if it is a measurement the register and the value are on top of each other -- see figure. 

image

### LINKED ISSUE #4248: Some open-controlled gates incorrectly drawn in mpl drawer
### Information

- **Qiskit Terra version**: 0.14.0.dev0+d0a487b
- **Python version**: 3.6
- **Operating system**: Ubuntu 18.04

### What is the current behavior?

Visualization open controlled gates was added in #4131 . But a few gates were missed out. In the circuit below, all were implemented as open-controlled gates but were drawn as below:

err_circuit

### Steps to reproduce the problem

```
qc = QuantumCircuit(3)
qc.append(YGate().control(ctrl_state='0'),[0,1])
qc.append(ZGate().control(ctrl_state='0'),[0,1])
qc.append(HGate().control(ctrl_state='0'),[0,1])
qc.append(U1Gate(pi/3).control(ctrl_state='0'),[0,1])
qc.append(RZGate(pi/4).control(ctrl_state='0'),[0,1])
qc.append(SwapGate().control(ctrl_state='0'),[0,1,2])
                    
qc.draw('mpl')
```

### LINKED ISSUE #4257: Initialize tutorial example fails to draw
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
```python
# Initializing a three-qubit quantum state
import math
desired_vector = [
    1 / math.sqrt(16) * complex(0, 1),
    1 / math.sqrt(8) * complex(1, 0),
    1 / math.sqrt(16) * complex(1, 1),
    0,
    0,
    1 / math.sqrt(8) * complex(1, 2),
    1 / math.sqrt(16) * complex(1, 0),
    0]

q = QuantumRegister(3)

qc = QuantumCircuit(q)

qc.initialize(desired_vector, [q[0],q[1],q[2]])
qc.draw(output='mpl')
```

gives

```
/opt/miniconda3/lib/python3.7/site-packages/qiskit_terra-0.14.0-py3.7-macosx-10.9-x86_64.egg/qiskit/visualization/matplotlib.py in _draw_ops(self, verbose)
    856                     vec = '[%s]' % param
    857                     self._custom_multiqubit_gate(q_xy, wide=_iswide,
--> 858                                                  text=op.op.label or "|psi>",
    859                                                  subtext=vec)
    860                 elif op.name == 'unitary':

AttributeError: 'Initialize' object has no attribute 'label'
```

### PR DESCRIPTION
**Pull request by enavarro51**
### Summary

Fix #4052 (continued)
Fix #4148 
Fix #4248 
Fix #4257 

### Details and comments

Changes to text drawer
- Fixed controlled custom multiqubit gate
- Restructured flow in instruction_to_gate to simplify

Changes to test_circuit_text_drawer
-  Fixed controlled custom multiqubit gate

Changes to mpl drawer
- Adjusted layer_width for large gates
- Restructured layer_width code to handle controlled and large gates
- Fixed controlled custom multiqubit gate display
- Added support for hamiltonian display
- Restructured draw_ops to simplify
- Fixed single control gates to show open controls 4248
- Added code for multi-control swap and rzz
- Fixed cbit total at bottom left positioning 4148
- Fixed initialize crash 4257

### CODE REVIEW

**Comment by 1ucian0** [comment]
Can this be broken into two PRs? I have some doubts about the text drawer changes, specially the "Fixed controlled custom multiqubit gate" part.

I think the MPL part is okey, but probably needs attention from somebody more familiar with that code.

**Comment by enavarro51** [comment]
Definitely may need some discussion here. The text drawer changes relate to a discussion with @ajavadia from #4173. It seemed to me that the controls for these multiqubit custom gates were different than the rest, but he said that was the way they should stay. I can back out the text drawer changes and recommit. Tomorrow I can discuss more about the mpl changes here, if you'd like.

**Comment by 1ucian0** [comment]
> It seemed to me that the controls for these multiqubit custom gates were different than the rest, but he said that was the way they should stay. I can back out the text drawer changes and recommit. Tomorrow I can discuss more about the mpl changes here, if you'd like.

Thanks a lot! that would be great. We can split the discussion in that way.

**Comment by enavarro51** [comment]
@mtreinish I noticed you had been assigned this PR and I wasn't sure if you were aware of the current state of the master matplotlib.py vs. this branch. Below are the outputs from a test file I use, first using the master branch and the second using this branch.
testdraw-master

testdraw

The problems with master include,
- The control on the H in the 4th layer should be open
- The names of the iswap, dcx, and ms should be capitalized
- The dcx and ms are too narrow
- The controlled-swap and the controlled-rzz are incorrect
- The very wide controlled-Fred... gate overwrites several gates
- The Hamiltonian is way too wide due to the array param being used for width. This would also happen for an isometry gate.

Just wanted to let you know there are issues here.

**Comment by 1ucian0** [comment]
MPL circuit drawer issues are piling up, since we dont have a good way to track changes on it. I'm putting this PR `on hold` (meaning "do not merge yet") until https://github.com/Qiskit/qiskit-terra/pull/4544 (or a similar solution) gets in.

**Comment by 1ucian0** [comment]
#4544 is merged... Let's add a test with the new method!

I will try helping, but fill free to do it yourself and ask me if any question.

**Comment by 1ucian0** [comment]
This one was covered by PR #4616.

**Pull request closed without merging**
