### PR TITLE
probabilities_ket computation bugfix

### PR DESCRIPTION
**Pull request by gadial**
### Summary
This change fixes a small typo which made one line of code part of a for-loop into which it obviously does not belong. This resulted in wrong display of probabilities_ket, e.g.

```
"probabilities_ket": {
                        "00": 1.0000000000000002,
                        "10": 0.4999999999999999
                    },
```
Following my fix, the probabilities are now computed and displayed properly.

### Detailed description
The for-loop

```
for (const auto &val : psi_ket){
           probs_ket[val.first] = get_probs(val.second);
}
```

Computes the full **probs_ket** vector for a snapshot in a given shot. Here **val** iterates over the possible outcomes for measurements, computing the probability for each.

This vector should next be added to the **snapshots_probs_ket** vector, which accumulates the probabilities over all the shots the simulator performs. Hence, since we accumulate over shots, we use addition: 

`snapshots_probs_ket[psi.first] += probs_ket;`

The bug was caused due to a typo inserting the second line into the for-loop, thus adding **probs_ket** to the accumulator multiple time as it is computed (note the indentation):

```
for (const auto &val : psi_ket) {
           probs_ket[val.first] = get_probs(val.second);
snapshots_probs_ket[psi.first] += probs_ket;
}
```

The fix is trivial.

### CODE REVIEW

**Comment by ajavadia** [comment]
can you please update the CHANGELOG file with a one-line description of this PR?
In the UNRELEASED portion.

**Comment by ajavadia** [comment]
@gadial: thanks for the fix. can you please sign the CLA so we can accept the PR?

**Comment by gadial** [comment]
Signed, sorry for taking so long.

**Comment by diego-plan9** [comment]
> Signed, sorry for taking so long.

No worries at all, and thanks for the fix @gadial !

**Pull request merged**
