### PR TITLE
Coupling map constructors

### PR DESCRIPTION
**Pull request by ajavadia**
adding factory methods for some simple `CouplingMap`s

### CODE REVIEW

**Comment by 1ucian0** [comment]
I think for full coupling maps we don't need to create the internal graph,
but just have a flag a the number of qubits.

**Comment by ajavadia** [comment]
> I think for full coupling maps we don't need to create the internal graph,
but just have a flag a the number of qubits.

It would save a bit of space but I'm not sure significant enough to warrant having to check flags and special cases. Also backends would report the full couplings if they are fully connected.

**Comment by 1ucian0** [comment]
Hmm.. because Metcalfe's law I thought the explosion of edges might be a problem. However, I test it using (pympler)[https://pypi.org/project/Pympler/] and Im probably wrong and, as you said, it's not a problem:
```
from pympler import asizeof

from qiskit.transpiler import CouplingMap

for i in range(0, 1001, 50):
    coupling = CouplingMap.from_full(i)
    print(i, asizeof.asizeof(coupling))
```
```
0 2360
50 838736
100 3360856
150 6833304
200 13366008
250 19700056
300 27263000
350 42578272
400 53621128
450 65943976
500 79546824
550 94429672
600 110592528
650 128035376
700 172629544
750 194476392
800 217603248
850 242010096
900 267696944
950 294663792
1000 322910648
```
Are these sizes realistic?

**Comment by 1ucian0** [comment]
> Also backends would report the full couplings if they are fully connected.

Right now, full couplings are `None`. Should backends change that?

**Comment by ajavadia** [comment]
> Right now, full couplings are None. Should backends change that?

I think that's just what simulators do meaning couplings are not even defined. But for a device with physical couplings (physical gates) all gates would get reported. Each has a different error, etc.

**Pull request merged**
