### PR TITLE
Alternative circuit checking using equivalence checker

### PR DESCRIPTION
**Pull request by gadial**

### CODE REVIEW

**Comment by yaelbh** [comment]
There is a bug when `up_to_phase` is `True`. A single qubit circuit with a Z gate is said to be equivalent to the identity circuit. It will be fixed in a follow-up PR (see #5692).

**Comment by yaelbh** [comment]
Will also take a deeper look at the ancilla qubits

**Comment by ajavadia** [comment]
I think what we want here is to define a user-friendly interface/function for checking two circuits are equivalent. So this function should be able to accept 2 circuits, and an "equivalence criteria", then choose the appropriate engine for conducting the equivalence checking.

The equivalence criteria can be:
- exact unitary equivalence
- equivalence up to global phase
- equivalence up to qubit permutation
- equivalence up to diagonal (relative phase)
- equivalence of wavefunctions (exact or up to phase)
- equivalence of measurement samples

The engines can be:
- unitary simulation
- statevector simulation
- density matrix simulation
- clifford simulation
(^ these 4 exist via qiskit.quantum_info as well as Aer)
- exact netlist equivalence
- BDD-based method
- ZX calculus
- etc..

So I think the interface function should let the user specify the equivalence criteria and the engine to use. For scalability I think we need to be able to choose Aer as one of the backends. If this function gets smarter it can automatically choose the engine (e.g. recognize that the circuits are clifford circuits).

**Comment by nonhermitian** [comment]
There are two types of qubit permutation: one sided permutation from swapping, and two sided from permuting labels.

**Comment by yaelbh** [comment]
@ajavadia @nonhermitian thanks for the comments. I'm copying your comments to #5692, which is an issue for discussion on equivalence checking. Note that this pull request is about to close, in favor of other ones (starting from #5700), that will replace it.

**Comment by mtreinish** [comment]
This seems like it's been superseded by #5700 so I'm going to close this. If I'm missing something or am mistaken please feel free to re-open this.

**Pull request closed without merging**
