### PR TITLE
Fixed issue5145 by changing the font size

### LINKED ISSUE #5145: passing dt to schedule.draw() gives jumbled x-axis labels
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?

Screen Shot 2020-09-29 at 05 45 44

### PR DESCRIPTION
**Pull request by tgag17**
### Summary
Fixes #5145 

### Details and comments
Reduced the font size of the axis from 18 to 8 so that the values are indicated clearly and are displayed without any overlap

### CODE REVIEW

**Comment by ajavadia** [comment]
the solution probably has to be something adaptive, not hardcoding a smaller font.

**Comment by tgag17** [comment]
Actually even the y-axis seemed too jumbled up and by reducing the font the plot looked much neater. So I thought that it would be better if the default font would be changed.
Do you recommend a relatively smaller font only when the dt is passed then?

**Comment by ajavadia** [comment]
No i was just suggesting that the font might need to be a function of canvas size and how many point are plotted. It needs to be tested for a few plots of different sizes and options to see what looks good. If you find a setting that is generally good, then I’m fine. Thanks for your contribution.

**Comment by nonhermitian** [comment]
Also probably not showing all digits, but just a few would help here. Angling the text could also be fruitful here depending on the number of labels.

**Comment by tgag17** [comment]
Should something be done with the y-axis too?

**Comment by javabster** [comment]
@tgag17 are you still working on this? Thanks for the work so far, it would be great if you could share some screenshots testing out the plots with different options to see if the new default font size you've proposed works for a range of plot options. And yes feel free to edit the y axis as well if you like, again please share some screenshots of different options so we can compare

**Comment by tgag17** [comment]
Hi! @javabster I am not sure but I think the issue has been solved with the addition and use of pulse_v2 instead of the legacy pulse drawer. If possible could you please confirm, if the issue is still relevant?
Thanks!

**Comment by javabster** [comment]
> Hi! @javabster I am not sure but I think the issue has been solved with the addition and use of pulse_v2 instead of the legacy pulse drawer. If possible could you please confirm, if the issue is still relevant?
> Thanks!

Ah yes you're quite right @tgag17 thank-you! I will close this PR and issue, please feel free to choose another good first issue if you would like something else to work on :)

**Pull request closed without merging**
