### PR TITLE
Moving Pauli to quantum_info

### LINKED ISSUE #1142: cleaning up the Pauli object
The tools.qi.pauli is important and will stay around. It is slow with int vs bools and needs to be cleaned up. Richard and Antonio will work on a proposal for what should be methods of Pauli and what should function in there and make tests for it. 

Some questions and related to the ordering issue I make soon. 

The Pauli has internal two vectors which are ordered 

v = [q0,q1,q2,q3, .... qn ], w =  [q0,q1,q2,q3, .... qn ] 

it makes a matrix which is ordered 

qn x .... q3 x q2 x q1 x q0 where x is tensor product. 

it makes a string label (eg. 'XIZ...') which is ordered 

q2q1q0 

My question for all is qiskit matrix is defined as the largest qubit to the left, I don't care what the internal of the Pauli uses (v,w), but the label what is our convention.

### PR DESCRIPTION
**Pull request by jaygambetta**
Fixes #1142

### CODE REVIEW

**Comment by jaygambetta** [comment]
@mtreinish I think I got all the moves so it should be ok with plotting.

**Comment by jaygambetta** [comment]
can you show me how to fix this.

**Comment by mtreinish** [comment]
Just add an empty `__init__.py` file to those 2 directories. Here's a patch you can apply to your tree for it:

```
commit c8326a34d1c94f2370ca41c50ec7020b3e027563
Author: Matthew Treinish <mtreinish@kortar.org>
Date:   Thu Nov 15 11:31:05 2018 -0500

    Add init files

diff --git a/qiskit/quantum_info/operators/__init__.py b/qiskit/quantum_info/operators/__init__.py
new file mode 100644
index 00000000..e69de29b
diff --git a/qiskit/quantum_info/states/__init__.py b/qiskit/quantum_info/states/__init__.py
new file mode 100644
index 00000000..e69de29b
```

**Comment by jaygambetta** [comment]
@mtreinish does this work

**Pull request merged**
