### PR TITLE
Conditionals must be updated to match schema

### PR DESCRIPTION
**Pull request by kdk**
Addresses #1283 by updating `assemble_circuits` to replace QASM-style conditionals with a bfunc+Qobj-conditional. Also, updates qobj json schema to allow `bfunc`s with single integer `register` and `memory` attributes.

### CODE REVIEW

**Comment by kdk** [comment]
Should be on hold until #861 supports qobj-conditionals for basic aer.

**Comment by diego-plan9** [comment]
> Also, updates qobj json schema to allow bfuncs with single integer register and memory attributes.

Can you add the `type: specs` label, if indeed the PR contains changes to the schema? It would help in collecting the list of schema changes and book-keeping in general.

**Comment by kdk** [comment]
Can be taken off on-hold after #1955 merges.

**Comment by ajavadia** [comment]
can you please rebase this? `circuits_to_qobj` is now deprecated in favor of `qiskit.compiler.assembler` (#1856)  and there are a couple changes to qobj (#1909)

**Comment by ajavadia** [comment]
The `'conditional'` field in a qobj should be an integer right (conditioned on a single register bit)? I wonder why the schema has it as follows:
```
                "conditional": {
                    "oneOf": [
                        {
                            "minimum": 0,
                            "type": "integer"
                        },
                        {
                            "type": "object"
                        }
                    ]

                },
```

It should definitely NOT be an array. But the example given in #1283 seems to expect an array. @chriseclectic can you double check that in Aer you don't expect an array?

With this patch, that example correctly outputs integers for the conditionals:
```
[QasmQobjInstruction(mask='0x3', name='bfunc', register=2, relation='==', val='0x0'),
 QasmQobjInstruction(conditional=2, name='x', qubits=[0]),
 QasmQobjInstruction(mask='0x3', name='bfunc', register=3, relation='==', val='0x1'),
 QasmQobjInstruction(conditional=3, name='y', qubits=[0]),
 QasmQobjInstruction(mask='0x3', name='bfunc', register=4, relation='==', val='0x2'),
 QasmQobjInstruction(conditional=4, name='z', qubits=[0]),
 QasmQobjInstruction(mask='0x3', name='bfunc', register=5, relation='==', val='0x3'),
 QasmQobjInstruction(conditional=5, name='h', qubits=[0])]
```

**Comment by kdk** [comment]
@ajavadia Updated, thanks for the comments.

Agree that `conditonal`s in the schema can be either integers (qobj-style) for objects (deprecated qasm-style). I don't know of a case where they would be an array.

aer checks for an integer, and falls back to assuming an object:
https://github.com/Qiskit/qiskit-aer/blob/e002af4f02cb956d8a9d73881d9e63e6a9e5c162/src/framework/operations.hpp#L511
basic-aer does the same:
https://github.com/Qiskit/qiskit-terra/blob/b123277669445bf1e8b1e2533c6db9d4a4ed0e84/qiskit/providers/basicaer/qasm_simulator.py#L496

**Pull request merged**
