### PR TITLE
[WIP] Add subunit reporting from CI

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

Now that we're using stestr to run results we can start tracking the ci
results over time so we can see various trends in what we're developing.
This includes things like failure rates, and individual test run times.
This works by leveraging the subunit2sql project to store results.

### CODE REVIEW

**Comment by mtreinish** [comment]
Hmm, it looks like travis is probably mangling the secret key for the DB_URI and subunit2sql is not able to use it. In the meantime if people want to play with the instance I setup for this here is the link (dns will come after we get it working):

http://169.63.131.233/#/?duration=P1D&resolutionKey=min&end=2018-12-22T02:00:00.000Z

http://169.63.131.233/#/test/test.python.test_mapper.TestMapper.test_move_measurements?end=2018-12-22T02:00:00.000Z&resolutionKey=min&duration=P1D

(the only data in there is test data from running unit tests on my desktop)

If people want to see this in use for a project with a lot more data you can check out:

http://status.openstack.org/openstack-health/#/

http://status.openstack.org/openstack-health/#/test/tempest.api.compute.volumes.test_attach_volume.AttachVolumeShelveTestJSON.test_attach_volume_shelved_or_offload_server

**Comment by mtreinish** [comment]
Ah, I figured out why the script isn't able to parse the URL set in the travis settings. According to the docs travis doesn't allow secrets to be set for pull request (or other untrusted) jobs which means we'll have no way to verify this works prior to merge and when it does land there will only be results for post merge jobs (which isn't a big deal and actually makes the data more consistent and easier to work with).

**Comment by 1ucian0** [comment]
@mtreinish still in your radar?

**Comment by mtreinish** [comment]
It is still on my radar, but it's a lower priority and keeps getting pushed down as more important things come up. It's not blocking anything it's just about aggregating data on how things perform in CI testing.

**Comment by mtreinish** [comment]
I'm abandoning this since it requires running an additional service outside of our normal ci environment. I have found an alternative built in to azure pipelines that provides a subset of the functionality that using subunit2sql would enable (it's enabled in https://github.com/Qiskit/qiskit-terra/pull/2927 ). While this doesn't provide everything that this patch would have provided (like run time analysis over time), it provides enough and also doesn't require us to maintain an additional service. Which is a big win.

**Pull request closed without merging**
