### PR TITLE
Fixed issue 3842 by comparison to an absolute error value

### LINKED ISSUE #3842: DiagonalGate does not raise when diagonal entries do not have modulus 1
### Information

- **Qiskit Terra version**: 0.12.0
- **Python version**: 3.6.9
- **Operating system**: Linux

### What is the current behavior?

`diag_gate` allows entries whose modulus are not one.

### Steps to reproduce the problem

```
import qiskit
from numpy import exp,pi

backend = qiskit.Aer.get_backend("statevector_simulator")
qc = qiskit.QuantumCircuit(1)
qc.h(0)
qc.diag_gate([exp(1j*pi/8),0],qc.qregs)  # <-- no error here
qiskit.execute(qc,backend).result().to_dict()
```

### What is the expected behavior?

An error should be raised.

### Suggested solutions
Line 59 in https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/extensions/quantum_initializer/diag.py#L59: 
`if not np.abs( np.abs(z) - 1 ) < _EPS:`

### PR DESCRIPTION
**Pull request by JiahanBro**
### Summary

Fixes #3842 

### Details and comments

The absolute value of the difference between the input to the value 1 has to be compared to the error bound given by _EPS in order to fulfill the if condition.

### CODE REVIEW

**Comment by 1ucian0** [comment]
Hi @JiahanBro!

Sorry for the delay here! The code was moved to `qiskit/extensions/quantum_initializer/diagonal.py`. Since it might be related with or affects https://github.com/Qiskit/qiskit-terra/pull/4375, maybe @ewinston can have a look to it?

**Comment by 1ucian0** [comment]
Also, considering adding a test that fails in master and passes here. Thanks and my apologies again! Your contribution is valued :)

**Comment by ewinston** [comment]
@JiahanBro Don't worry about creating a test since I think it already exists in #4375 which will probably merge shortly after.

**Comment by ewinston** [comment]
@JiahanBro Can you resolve the conflict? The class has moved to "diagonal.py".

**Comment by JiahanBro** [comment]
Should I just close the pull request and delete the branch?

**Comment by ewinston** [comment]
> Should I just close the pull request and delete the branch?

Whatever is convenient for you. It's a small change so maybe that's easier.

**Pull request closed without merging**
