### PR TITLE
Set sphinx-build --keep-going by default

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

For sphinx builds we set the -W flag to treat warnings as errors. This
however, has the unfortunate side-effect of exiting the sphinx build
on the first warning and in the typical documentation debugging
workflow multiple iterations are required to debug all the issues. This
commit adds the --keep-going sphinx-build flag [1] to the default build
options. The --keep-going flag will still treat warnings as errors, but
not exit the build early. This should hopefully improve the
debuggability of the documentation as we'll get a complete picture of
what's wrong with a build instead of having to deal with it one warning
at a time.

### Details and comments

[1] https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-keep-going

### CODE REVIEW

**Review by jakelishman — COMMENTED** [review]
On qutip we also had `-T` enabled, which turns on complete Python tracebacks on errors - I don't know how well that'll interact with the jupyter cells, but it may well be useful.

While we're at it, ought we to set these options in the tutorials CI build?  I'm guessing we don't because it probably does emit warning right now.

**Review by nkanazawa1989 — APPROVED** [review]
This option really helped me to debug documentation. With this option sphinx will reuse generated rst files for next run. In my laptop running full terra documentation build had been taking over 5 minutes, so this drastically improved the workflow.

**Comment by jakelishman** [comment]
Oh yeah, that's a great point Naoki - I'd been frustrated by that in the past as well, and I didn't know `--keep-going` fixed it.

**Comment by mtreinish** [comment]
> On qutip we also had `-T` enabled, which turns on complete Python tracebacks on errors - I don't know how well that'll interact with the jupyter cells, but it may well be useful.

Well jupyter-execute still prints the full traceback as the error message I think. But setting `-T` is a good idea, I'll do that now.

> 
> While we're at it, ought we to set these options in the tutorials CI build? I'm guessing we don't because it probably does emit warning right now.

We can it doesn't hurt anything. But, since they're all nbsphinx executed notebook files we don't really see sphinx warnings very often from it.

**Review by jakelishman — DISMISSED** [review]

**Comment by mtreinish** [comment]
I had to revert the tutorials job change in: https://github.com/Qiskit/qiskit-terra/pull/7940/commits/0e1e7ce96771263eb43b6d7dce33654b1a1e1b5f because it turns out it is emitting a warning for a missing tutorial and we'll have to fix that in the tutorials repo before we can start running with `-W` here.

**Review by jakelishman — APPROVED** [review]

**Pull request merged**
