### PR TITLE
Add missing support for missing option fields to plot_histogram

### LINKED ISSUE #896: Make non interactive plot_histogram accept the same formatting options as the interactive version
### What is the expected enhancement?
Both representations, interactive and non-interactive will support the same formatting capabilities.

### PR DESCRIPTION
**Pull request by mtreinish**
Fix #896

### Summary

This commit adds support for the 3 missing option fields: height,
width, and sort from iplot_histogram (using online js) to
plot_histogram (using matplotlib).

### Details and comments

This difference between the 2 histogram plot options was pointed out in review for #866.

### CODE REVIEW

**Comment by mtreinish** [comment]
Actually taking another look at this I'm not sure I got the sorting right. I'm sorting the order of the bars per result. (not changing the orders of the bits on the graph) But, I think the intent of the sort option on the js was to flip the endianness of result bits. That being said the the js isn't actually doing that correctly. For example running:

```
from qiskit.tools import visualization
visualization.plot_histogram([{'000': 4, '010': 10}, {'000':8, '001': 4, '010': 9}],
                             legend = ['run_1', 'run_2'],
                             options={'sort': 'asc'})
```

The interactive graph draws the graphs in the results order 000, 010, 001. Then if you switch to 'desc' it uses 010, 000, 001.

**Comment by mtreinish** [comment]
@filemaster can you provide some insight here, what was the intended behavior of the sort field on the options dict on the interactive graph?

**Comment by Tansito** [comment]
@mtreinish yeah, as you said the visualization doesn't seem right, I will check it and let you know where is the problem.

**Comment by delapuente** [comment]
Put on hold until @Tansito or @filemaster take a look. Please, remember to open a PR and link with the issue by using "Fix <issue_number>".

**Comment by Tansito** [comment]
@mtreinish and @delapuente the problem was initially in the input due to the histogram must have the same values in the X axis for the different executions. We updated a new version for the visualization engine that fix this problem (inside it will fill the X values that are not setted by default to 0) with other fixes and features.

How the issue is solved in the JS library (cloud), no changes are required in qiskit.

**Comment by mtreinish** [comment]
@Tansito ok cool, thanks. That also does confirm that the options 'sort' field in this PR isn't doing the correct thing. I will respin this to make the matplotlib sort field match the JS side.

**Comment by mtreinish** [comment]
Ok, I've updated this PR to mirror the JS 'sort' field behavior so the order of the bits is reversed instead of just the order of the individual executions.

**Pull request merged**
