### PR TITLE
Increase Accuracy of OpenQASM 2.0 Dump

### LINKED ISSUE #7166: Truncating floats in QASM dump alters circuit's functionality
### Information

- **Qiskit Terra version**: 0.18.3 (dates back to 0.14)
- **Python version**: Any
- **Operating system**: Any

### What is the current behavior?
In #4276, the `pi_check` function was introduced for pretty printing the list of parameters when dumping a `QuantumCircuit` to `qasm`, see 
https://github.com/Qiskit/qiskit-terra/blob/637acc0c408d8199dd58780cc3dafabc14e61a0f/qiskit/circuit/instruction.py#L450-L463
This also introduced a fixed truncation (`ndigits=8`) of floating point numbers that are not close to any fraction or fraction of pi. However, *8* digits is not enough to uniquely identify a double precision floating point number. You need up to *17* significant digits for that. This leads to the following situation:

Let's say I have a circuit that contains, e.g., a phase gate with more than 8 significant digits in its rotation angle.
Then, I dump the circuit to a `.qasm` file and read that file back into a `QuantumCircuit`.
If I compare both unitary functionalities (i.e., the respective unitary matrices), these will no longer be equal due to the numerical error introduced by the truncation.

### Steps to reproduce the problem

```python
from qiskit import QuantumCircuit, execute, Aer

qc = QuantumCircuit(1)
qc.p(1/4096, 0)

qasm_str = qc.qasm()

backend = Aer.get_backend('aer_simulator')

qc.save_unitary()
job = execute(qc, backend)
result = job.result()
unitary = result.get_unitary(qc)

qc_qasm = QuantumCircuit.from_qasm_str(qasm_str)
qc_qasm.save_unitary()
job = execute(qc_qasm, backend)
result = job.result()
unitary_qasm = result.get_unitary(qc_qasm)
    
print(unitary == unitary_qasm)
```
yields
```bash
[[ True  True]
 [ True False]]
```

### What is the expected behavior?

Merely dumping a file to `.qasm` should not alter a circuit's functionality.

### Suggested solutions

A quick fix for this would be to just change the default value for the `ndigits` parameter in the respective function call to `17`.

### PR DESCRIPTION
**Pull request by burgholzer**
### Summary

This PR improves the accuracy of the OpenQASM 2.0 export by not truncating parameters of gates to `single` precision and using a tighter bound for checking whether a given parameter is close to a fraction of pi.
Resolves #7166.

### Details and comments

For details, see the discussion in #7166. The additional precision is accomplished by relying on Python's built-in float formatting as a default in the `pi_check` function.

### CODE REVIEW

**Review by jakelishman — COMMENTED** [review]
Given the discussion in #7166, I'm fine with this.  On the `ndigits` front: probably the ideal would be for us to have the default be `None`, and to use Python's default float formatting if `ndigits is None` (or the current implementation if not).  In that mode, Python will output the shortest string which evaluates to the same target float - that's why `str(0.3)` is `"0.3"`, `str(0.3 * 3) == "0.8999999999999999"` and `str(0.9) == "0.9"`, for example.

If you'd like to do that in this PR, let me know, otherwise we can just move on to merge.  Either way, please could you add an "upgrade" release note for this change (`reno new --edit change-qasm-float-output`) that explains that the number of digits output by `QuantumCircuit.qasm()` has changed to more accurately represent the parameters.  If you want to make the above change, it'll be a "feature" note, rather than an "upgrade".

*edit*: the lint CI run is also failing, probably because there's a docstring line that's a bit too long in the new test you added.  Nothing major - you can just split the line in two.

**Comment by jakelishman** [comment]
Ok cool! Yeah, that's exactly it - if `ndigits=None` then we don't specify a format specifier (as opposed to `:{ndigits}f`).

**Comment by burgholzer** [comment]
I refactored the `pi_check` function accordingly and added corresponding release notes (which I hope are sufficiently accurate).

One of the (potentially easy to fix) things in the `pi_check` function is the hard-coded check for zero in
https://github.com/Qiskit/qiskit-terra/blob/fe8ab43f1218d6997458fb3bf4011045f40932b0/qiskit/circuit/tools/pi_check.py#L69-L70
All other comparisons are conducted with respect to `eps`.
In my opinion, it would make the function more consistent, if this zero check was also conducted with respect to `eps`.

**Comment by jakelishman** [comment]
Yeah, your new form looks better to me, thanks, and all your changes look like they make a lot of sense.  I really dislike the whole `pi_check` function as a whole, and I'm not surprised there's more hard-coded weirdness in it, to be honest...  I agree that that line you've highlighted should also be a comparison to `eps`.

(I can't do a proper review on GitHub right now because it seems to have bugged out a little, and it's showing commits that aren't actually on the branch.  Don't worry about it - your branch is actually fine, it's just GitHub being weird, and it'll fix itself in a bit, I'm sure.)

**Comment by burgholzer** [comment]
> Yeah, your new form looks better to me, thanks, and all your changes look like they make a lot of sense. I really dislike the whole pi_check function as a whole, and I'm not surprised there's more hard-coded weirdness in it, to be honest... I agree that that line you've highlighted should also be a comparison to eps.

I updated the respective line to properly compare against `eps` and adjusted the tests to reflect the change. 
I believe that the function itself has it's purpose but it also has the potential of introducing unnecessary approximations without people actively being aware of them.

> (I can't do a proper review on GitHub right now because it seems to have bugged out a little, and it's showing commits that aren't actually on the branch. Don't worry about it - your branch is actually fine, it's just GitHub being weird, and it'll fix itself in a bit, I'm sure.)

Something seems to have gotten messed up in the git history. I rebased the commits and changes now show up properly again.
This should be ready for a proper review now.

**Comment by burgholzer** [comment]
@jakelishman gentle ping so this doesn't go stale again.

**Review by jakelishman — DISMISSED** [review]
I read it quickly, and all the code looks sensible to me, thank you! I'm actually on paternity leave for the next few weeks, so it's difficult for me to check completely properly. @1ucian0, please could you take over and merge if you're happy?

**Comment by burgholzer** [comment]
@1ucian0 @jakelishman gentle ping. It's been another month 🙃

**Review by jakelishman — APPROVED** [review]
Sorry once more for this falling through the cracks.  I've fixed the merge conflict that had arisen, and we can merge this for the 0.23 series.

**Comment by burgholzer** [comment]
No worries, thanks for getting back!

**Pull request merged**
