### PR TITLE
trace-preserving property for QuantumChannel verified more precisely

### PR DESCRIPTION
**Pull request by molar-volume**
### Summary
resolves https://github.com/Qiskit/qiskit-terra/issues/5610

### Details and comments
using `np.linalg.eigvalsh` to verify trace-preserving property

### CODE REVIEW

**Review by nkanazawa1989 — COMMENTED** [review]
Thanks. Could you please add reno because it may impact the result of some calculation? 

Now we have almost the same code in two places, i.e. `QuantumChannel.is_tp` and `process_fidelity`. To reduce maintenance overhead, we may want to define a common sub routine `is_trace_preserving` in somewhere like [predicates](https://github.com/Qiskit/qiskit-terra/blob/f53a4b0bd1c951b6b1ccc3c8c33eec6e9cf3288e/qiskit/quantum_info/operators/predicates.py). This may return a list of non-zero eigenvalues, then `QuantumChannel.is_tp` just return `False` if the list is not empty and `process_fidelity` raises warning with eigenvalues. Any thought? @chriseclectic

**Comment by woodsp-ibm** [comment]
It seems however you did your branch updates that it's added a couple of files here (one from opflow and one from algorithms) that were changed this way in master already by some other PR - just pulls myself and Manoel into the conversation etc.

**Comment by molar-volume** [comment]
@woodsp-ibm Sorry for that, instead of merge, I rebased my branch locally
@nkanazawa1989 turns out there was a lot copy-pasted code from `Operator` to `QuantumChannel` .
Besides `is_cp` and `is_tp` is applied to both `QuantumChannel` and `Operator` in `measures` module, and `Operator` is treated as `QuantumChannel` in `transformations`.

**Review by chriseclectic — APPROVED** [review]
LGTM

**Pull request merged**
