### PR TITLE
Stochastic optimization of quantum programs

### PR DESCRIPTION
**Pull request by liupibm**
## [What is it]
A stochastic optimizer is under qiskit/tools/mcmc
 qoptimizer.py

## [how to run it]
In PyCharm, simply run qoptimizer.py
You can change the file to be optimized by passing the argument "--qasm_files=your_qasm_path"

## [What is the expected result?]
The optimized mutants, i.e., the mutants that are correct and have better performance, are stored into the folder mcmc_mutants_good.

At the bottom of each mutant program, we also show:
1 new_cost_correctness (correctness): the difference of the final amplitude vector (value=0 means the final vector is exactly the same as the original program)
2 new_cost_perf (performance): the increase of circuit depth (value<0 means the depth becomes shorter than the original program)
3 new_cost: sum of the above two.

Clearly, for optimized mutants, new_cost_correctness=0 and new_cost_perf<0

Besides, the log of the cost after each iteration is recorded in the folder mcmc_cost_logs

## [dependency]
1 goto qiskit root folder that has setup.py
    python3 setup.py install
2 pip3 install "sympy==1.0"

### CODE REVIEW

**Comment by ajavadia** [comment]
Hi @liupibm. After Release 0.4, we have now started working on the QISKit Pass framework to make the compiler more modular. It would be better to hold off on this merge until those components are in place. Then we can easily merge this into the new architecture, as a new optimization pass.

In the meantime, could you ensure that the branch is clean (i.e. remove unnecessary log files, fix style issues, etc)? 

Thanks!

**Comment by delapuente** [comment]
Not very sure if this is a pass for the transpiler or a utility built on top of Qiskit. @liupibm, I did not take a look at your implementation but according to your description, I tend to think this is kind of a pre-processing pass for the QASM. Am I wrong?

**Comment by liupibm** [comment]
this one is also outdated and depends on #219 and the sympy backend which is not in terra any more.

I guess we can close this one similar to #219 .

**Comment by ajavadia** [comment]
@liupibm yes you are right. This is quite old now and the codebase has changed a lot. 

However, it would be great to have this as a transpiler pass. You can follow the example of a pass here: https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/transpiler/passes/cx_cancellation.py

If you plan to do this, here are some notes to consider:

1- This pass will require unrolling to a `basis_gates` consisting of `{'h', 't', 'tdg', 's', 'sdg', 'x', 'y', 'z', 'cx'}`. This unrolling pass must be specified as a `requires` property.

2- Can you try using the `local_statevector_simulator` which is faster than `sympy_simulator`? This will speed things up a bit. You can check the fidelity of the statevectors and penalize based on that.

3- This will be a more time-consuming pass than a typical pass, so we should be aware of that and communicate that to a user.

Thanks!

Closing this PR.

**Pull request closed without merging**
