### PR TITLE
Adds error_map plot

### PR DESCRIPTION
**Pull request by nonhermitian**
### Summary
Adds error map plot and uses this in the `backend_monitor` to replace the old one.

Screen Shot 2019-08-12 at 1 35 03 PM

### CODE REVIEW

**Comment by jaygambetta** [comment]
I know the H gate is what we benchmark (check its not times by 2). I am worried that this is not general for different systems. What if I have a different gates set for my backend. Should this be all the gates in the gate set that we have access to. If so our real gate set is {H, Z(theta), CNOT} with Z entered with zero error (frame change) but we since the family of U2 = Z H Z we allow this to happen with the user passing them to the hardware. 

I dont have a strong opinion here except to make it clear that the error are the errors the user has and the next step is we need to make the backends report only this set and allow the transpiler to the other gates and write it this way. 

Personally if we can do this we can get rid of U1, U2, and U3 and replace U1 with Z(theta), U2 not sure we need it if we have a better transpolar, and U3 could just be U for arbitrary rotation. 

We originally had U1, U2, and U3 because it was simpler to compile to these before we got more advanced in the compilers. Forcing the user to use U2 if they could over U3 allows them to have shorter gates. If we can now make the transpiler minimize the number of H this would make this concern obsolete. 

@ajavadia thoughts?

**Comment by jaygambetta** [comment]
ps I like the layout and the error maps for the measurement.

**Comment by nonhermitian** [comment]
This is failing for an unrelated reason:
```
==============================
Failed 1 tests - output below:
==============================
test.python.pulse.test_commands.TestSamplePulse.test_pulse_limits
-----------------------------------------------------------------
Captured traceback:
~~~~~~~~~~~~~~~~~~~
    b'Traceback (most recent call last):'
    b'  File "C:\\projects\\qiskit-sdk-py\\test\\python\\pulse\\test_commands.py", line 69, in test_pulse_limits'
    b'    SamplePulse(unit_pulse_c128)'
    b'  File "C:\\projects\\qiskit-sdk-py\\qiskit\\pulse\\commands\\sample_pulse.py", line 50, in __init__'
    b'    self._samples = self._clip(samples, epsilon=epsilon)'
    b'  File "C:\\projects\\qiskit-sdk-py\\qiskit\\pulse\\commands\\sample_pulse.py", line 85, in _clip'
    b"    raise PulseError('Pulse contains sample with norm greater than 1+epsilon.')"
    b"qiskit.pulse.exceptions.PulseError: 'Pulse contains sample with norm greater than 1+epsilon.'"
    b''
    b'During handling of the above exception, another exception occurred:'
    b''
    b'Traceback (most recent call last):'
    b'  File "C:\\projects\\qiskit-sdk-py\\test\\python\\pulse\\test_commands.py", line 71, in test_pulse_limits'
    b"    self.fail('SamplePulse incorrectly failed on approximately unit norm samples.')"
    b'  File "C:\\Python37\\lib\\unittest\\case.py", line 693, in fail'
    b'    raise self.failureException(msg)'
    b'AssertionError: SamplePulse incorrectly failed on approximately unit norm samples.'
    b''
```

**Comment by mtreinish** [comment]
@nonhermitian see: https://github.com/Qiskit/qiskit-terra/pull/2989

**Comment by ajavadia** [comment]
> We originally had U1, U2, and U3 because it was simpler to compile to these before we got more advanced in the compilers. Forcing the user to use U2 if they could over U3 allows them to have shorter gates. If we can now make the transpiler minimize the number of H this would make this concern obsolete.

The discussion of what basis the devices should report is a good one, but outside the scope of this PR. I would just point out that we already have functions that convert U3 to U2 or U1 if possible, so a user shouldn't have to manually do U2s.

I like the idea of writing circuits in `H`, `Z`, `CNOT` basis which are more standard. A circuit might end up with a lot of Z gates though, and look longer than a circuit in the u1,u2,u3 basis.

> I know the H gate is what we benchmark (check its not times by 2).

Correct. Right now we report errors for `id`, `u1`, `u2`, `u3`, `cx`.
`u1` has 0 error.
`id` and `u2` have the same error.
`u3` has double this error.

So while I would also like the error map to not be smart and just visualize what `backend.properties()` reports, currently there's some redundant info which would make the visualization not nice.

**Pull request merged**
