### PR TITLE
Stop building decomposition dag at instance creation

### LINKED ISSUE #1441: _define_decomposition() is slow
### What is the expected enhancement?
After #1210 every gate has associated with it a `gate._decompositions`. The quick and dirty way was to call a `self._define_decompositions()` at __init__ time, but that gets called with every Gate and becomes slow for large circuits. We should factor out that logic so it is a class property and only computed once per class, not for each instance separately.

### LINKED ISSUE #1729: Avoid redefining decompositions for non-parametric gates
### What is the expected enhancement?
The unroller pass depends on decompositions that are defined per gate, and expands those gates according to those decomposition rules.

For gates such as crz, cu1, cu3, rx, ry, rz, rzz, u1, u2, u3, the decomposition depends on the parameter, and so each gate instance can have its own decomposition.

However, for all other gates, this is redundant and can start to add up. Instead, the decomposition should be defined once, for the class (not each instance).

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

This commit adjust how we define decompositions for gates. Previously we
ran a function which built a dag of the decompositions during `__init__`
for the gate class. This meant we'd build a new dag every time we
created a new gate, which for large circuits would start to add up.
However, the decompositions are static for most gates and we only need
to run it once. To accomplish that this commit makes the decompositions
a class defined parameter and removes it from `__init__`. This way we only
ever build the decomposition dags once unless explicitly needed.

Gates that are not touched: crz, cu1, cu3, rx, ry, rz, rzz, u1, u2, u3,
are left alone because the decomposition depends on run time variables
in the instance and this optimization provides no benefit.

### Details and comments

Fixes #1729

### CODE REVIEW

**Comment by ajavadia** [comment]
luciano sped things up in #1455 by making sure that `_define_decompositions()` is only called upon request (i.e. when the unroller needs to make an unrolling decision).  But it is still per instance, not per class. So there's still merit to this PR to get further improvement from some classes (those that don't have any parameters).

**Comment by mtreinish** [comment]
ugh, well that makes rebasing this fun :) I'll do that right now

**Comment by 1ucian0** [comment]
Sorry for the overlapping, it was part of moving the unroller as a pass :(

**Comment by 1ucian0** [comment]
Since #1441 is closed, I'm closing this PR.

**Comment by ajavadia** [comment]
I would still like to do what Matthew did in this PR. It provides further speedups to what was already achieved. However, this PR is probably already quite out of sync with master, so might make sense to open a new PR. I'll open an issue.

**Comment by mtreinish** [comment]
Hmm, it looks like we're still modifying `input_dag` in the `substitute_node_with_dag()` even in the non-conditional case. This is causing the failures later when there is a conditional, so simply duplicating the input_dag when there is a conditional (like https://github.com/Qiskit/qiskit-terra/pull/1445/commits/a00e3a1d6199ac5c729734e23d234d4cad313e3f ) is not sufficient because the global decomposition dag has already been modified by the time we call copy. We'll need to figure out why/where the input_dag gets modified and guard against that if we plan to use class level attributes for the decomposition_dags.

**Comment by 1ucian0** [comment]
I'm closing this PR because it has conflicts with the current master. Feel free to open a new PR for closing #1729 !

**Comment by mtreinish** [comment]
@1ucian0 It's unlikely to be feasible while we're still modifying the dag in place. If we move to shared instance for any dag (including the decomposition dags like this commit) this gets really messy since those in place modifications effect the global/shared instance.  We have to stop doing that as a first step before this is really something we can consider, especially weighed against the modest performance benefits I was seeing locally (there might be some edge cases I'm missing though)

**Pull request closed without merging**
