### PR TITLE
Fix issue 4959 modifying the tests from pi to π

### PR DESCRIPTION
**Pull request by alejomonbar**
### Summary

Fixes https://github.com/Qiskit/qiskit-terra/issues/4959

### Details and comments

The test cases were comparing a string which includes "pi" and I modify it to "π"

### CODE REVIEW

**Comment by alejomonbar** [comment]
> Jhon Montanez needs to sign CLA too

I'm Jhon Montanez. I didn't update my git hub email account in the terminal and I pull requested and I don't know how to solve it now :(!

**Comment by 1ucian0** [comment]
Maybe you want to remove it as co-author from the history?

**Comment by alejomonbar** [comment]
> Maybe you want to remove it as co-author from the history?

Yes, I'm trying to do that. But, I don't find the correct way to do that. Any advice?

**Comment by 1ucian0** [comment]
I think if you squash you will be able to remove the co-author.

**Comment by 1ucian0** [comment]
The problem the current solution is that `π` might be out of the charset for `self.enconding` an `pi` should be used in that case. Have a look to https://github.com/Qiskit/qiskit-terra/issues/4959#issuecomment-701068482

**Comment by alejomonbar** [comment]
> The problem the current solution is that `π` might be out of the charset for `self.enconding` an `pi` should be used in that case. Have a look to [#4959 (comment)](https://github.com/Qiskit/qiskit-terra/issues/4959#issuecomment-701068482)

I tried to encode and decode with both encodings utf8 and cp437 and both are able to manage π. Do you want me to try another encode?

**Comment by 1ucian0** [comment]
Probably you are right and most of the charsets that have `╞` also have `π`. I was thinking that maybe obscure code pages like 866 might be a problem.. but probably they are problematic already...

**Comment by 1ucian0** [comment]
?

**Comment by alejomonbar** [comment]
> ?

Sorry, @1ucian0, I closed this pull request and I create a new one. I couldn't figure out how to eliminate those commits with Jhon Montanez. The new pull request is this https://github.com/Qiskit/qiskit-terra/pull/5218

**Pull request closed without merging**
