### PR TITLE
Entangling capacity as an Ansatz quality metric (resolves #8176)

### LINKED ISSUE #8176: Entangling capacity as an Ansatz quality metric for all variational Quantum circuits
### What should we add?

In the paper https://arxiv.org/pdf/1905.10876.pdf three metrics were proposed to represent Ansatz quality of variational circuits were proposed: Expressibility, Entangling capacity and circuit cost. However, to the best of our knowledge these metrics are not available in Qiskit nor in any of these issues in progress. 

We have implemented these metrics and matched our numbers to that of this paper. We have two ways to compute Entangling capacity -using Meyer Wallach measure and Von-Neumann measure. 

Changes required in the qiskit.utils library:
Introduced a new folder `Entanglement `with 3 python scripts with function as follows: (i) `circuit.py` - has the circuits comprising of 19 parametric circuits in the https://doi.org/10.1007/s42484-021-00038-w
(ii) `meyer_wallach_measure.py` - computes the meyer wallach entanglement measure for using with two libraries : qiskit and qutip ; qutip is tested to give faster computation.
(iii) `von_neumann_entropy.py` - computes the von neumann entanglement measure using with two libraries : qiskit and qutip ; qutip is tested to give faster computation.
We have introduced changes in the python script of /qiskit/utils/circuit_util.py and added a class entanglement which is utility class to calculate the entanglement capability of a particular parametric circuit with initialized parameters using the function present in the` /qiskit/utils/entaglement/`

### PR DESCRIPTION
**Pull request by anupamaray**
### Summary

Resolves #8176

### Details and comments

Need to add label: Changelog: New Feature to the PR

### CODE REVIEW

**Comment by aakif-akhtar** [comment]
`from qiskit.utils.circuit_utils import Entanglement
from qiskit.utils.entanglement.parametric_circuits import Ansatz

import numpy as np
from qiskit import Aer


total_circuit = 1
feature_dim = 4
repitition = 1
num_eval = 1
entanglement_cap = np.zeros((total_circuit, repitition))
backend = Aer.get_backend("statevector_simulator")

for k in range(num_eval):

    for i in range(total_circuit):
        circuit_id = i + 1

        for layers in range(repitition):

            ansatze = Ansatz(layers + 1, feature_dim, circuit_id).get_ansatz()
            ent_cap = Entanglement(ansatze, backend, num_params=10).von_neumann()
            entanglement_cap[i, layers] = ent_cap

    file_name = "entropy_run" + str(k)
    np.savetxt(file_name + ".csv", entanglement_cap, delimiter="\t")`
    
    
    To test the new module we can use the above python script to get the default entanglement measure using meyer-wallach measure of parametric circuit 1 given in the article https://arxiv.org/pdf/1905.10876.pdf

**Review by aakif-akhtar — DISMISSED** [review]

**Comment by aakif-akhtar** [comment]
> One aspect that seems to be missing so far are unit tests for the new function that is introduced.

@woodsp-ibm yes so the testing code was somehow throwing errors with tex -edocs so we removed it and tried and everything worked so kept it out of utils.. this is the testing code to test the new feature we are trying to add.
specifically the two lines with comments in the below code are to test the two functions added.
```

from qiskit.utils.circuit_utils import Entanglement
from qiskit.utils.entanglement.parametric_circuits import Ansatz
import numpy as np
from qiskit import Aer
total_circuit = 19 #for iterating over every given 19 parametric circuit in Ansatz
feature_dim = 4 #no of qubits
repitition = 1 #no. of layers in the ansatz
num_eval = 1 #total number of time we need to run the measure
meyer_wallach_measure = np.zeros((total_circuit, repitition))
von_neumann_measure = np.zeros((total_circuit, repitition))
backend = Aer.get_backend("statevector_simulator")
for k in range(num_eval):
    for i in range(total_circuit):
        circuit_id = i + 1
        for layers in range(repitition):
            ansatze = Ansatz(layers + 1, feature_dim, circuit_id).get_ansatz()
            mw_cap = Entanglement(ansatze, backend, num_params=100).get_entanglement() #tests function Meyer Wallach
            vn_cap = Entanglement(ansatze, feature_dim, ent_measure="von-neumann").get_entanglement() #tests function von_neumann
            meyer_wallach_measure[i, layers] = mw_cap
            von_neumann_measure[i, layers] = vn_cap
    file_name = "mw_entropy_run" + str(k)
    np.savetxt(file_name + ".csv", meyer_wallach_measure, delimiter="\t")
    file_name = "vn_entropy_run" + str(k)
    np.savetxt(file_name + ".csv", von_neumann_measure, delimiter="\t")
```

**Comment by woodsp-ibm** [comment]
Test should be in the form of Python units that assert correctness of result etc. See the many examples here https://github.com/Qiskit/qiskit-terra/tree/main/test/python for various aspects

**Comment by Cryoris** [comment]
Reproducing and checking the numbers from the circuit expressitivity paper is very interesting! 

However we're not quite sure how this contribution should be integrated to Qiskit yet. 
* _If_ we include it in Qiskit, the best place for the entanglement measures would likely be the `qiskit.quantum_info` module.   Then, the code would have to work with normal Qiskit circuits (not new defined, analogous classes) and we would not be able to include all the pre-constructed circuits. If some of them turn out to be very useful, we could potentially add them to the `circuit.library` module.
* Alternatively, we could keep your code in a third party repository. There you would have full freedom of how to structure the code, keep all the measures, circuits etc.

Depending on how much you want to change the current code or whether you want to keep it as is, either of the solutions might be better 🙂

**Comment by anupamaray** [comment]
@Cryoris the code works for any ansatz and can be used for VQE or VQC or any variational quantum algorithm. So its pretty generic and the only input it needs is a quantum circuit so we kept it under utils.

we have put in 19 types of ansatz that we have tested on..u don't need to include any of the constructed circuits.. we added that to provide a mechanism to test the function. the testing code give in the comment above uses that reconstructed circuit code. barring that we don't need that code at all.
We are working on creating unit tests as pointed by Steve and will be try to push them asap after the tox tests.
Thanks

**Comment by anupamaray** [comment]
@woodsp-ibm @HuangJunye please let me know if you need any information or any codes or anything to help move this PR. Thanks

**Comment by woodsp-ibm** [comment]
@anupamaray While I was able to help you with procedure/mechanics for the PR the material is not a subject area I can technically review the content. Someone from terra-core team will need to do this.

**Comment by Cryoris** [comment]
We discussed this in the team and it would be great to add the von Neumann and Meyer-Wallach entanglement measures to quantum info. There's an existing file `qiskit/quantum_info/states/measures.py` which already contains similar functions. There you could add the entanglement measures as two new standalone functions, but we think that it would be best to not add the `Entanglement`and `Ansatz` classes to Qiskit Terra.

I think your full code, with all the ansatz circuits, would be a great contribution to the qiskit-community repository 🙂

**Comment by anupamaray** [comment]
Thanks @Cryoris for your time and feedback. we went through `qiskit/quantum_info/states/measures.py` but here all functions accept only statevectors and not circuits. 
for our code  we want to compute the entangling capacity of an ansatz so we pass the quantum circuit. for example the function we will add to measures.py will look like:
`def entanglement_von_neumann (qc): 
Args:
        qc: a quantum circuit.
    Returns:
        float: The von-Neumann entanglement.`
  
Is this okay or we need to find some other code where u have functions taking a quantum circuit as input. Kindly let us know. Thanks a ton for your help and feedback.

**Comment by Cryoris** [comment]
I think you could have the function accept both a statevector or a quantum circuit, since you anyways convert the circuit into a statevector, right? Something like
```python
def von_neumann_entropy(data):
    if not isinstance(data, Statevector):
        data = Statevector(data)
```
You could also add a second argument for the number of parameter sets you want to average over in case your circuit is parameterized, maybe like
```python
def von_neumann_entropy(data, num_parameter_samples=None):
    if isinstance(data, QuantumCircuit) and data.num_parameters > 0:
        parameter_sets = [np.random.random(data.num_parameters) for _ in range(num_parameter_samples)]
        return np.mean(von_neumann_entropy(data.bind_parameters(params) for params in parameter_sets))

    if not isinstance(data, Statevector):
        data = Statevector(data)

   ....

**Comment by Cryoris** [comment]
@anupamaray are you still pursuing this? I think this would be a great addition in the format we discussed above! 🙂

**Comment by anupamaray** [comment]
yes Julien, we have cleaned up and put in this format, but then some lint tests failed. I ll get to it asap and resubmit it. Thanks a ton for your feedback and support.

**Comment by javabster** [comment]
hi @anupamaray re you still working on this?

**Comment by woodsp-ibm** [comment]
As this became a tutorial I am closing this as complete.

**Pull request closed without merging**
