### PR TITLE
Pylint disabled import-errors

### PR DESCRIPTION
**Pull request by levbishop**
We disable a lot of pylint import-error warnings. It looks like the intention is to allow successfully running pylint without installing the optional dependencies. However, this doesn't work. If you only `pip install -e qiskit` (ie without requirements-dev.txt or `[visualizations, classical-function-compiler, etc]` then pylint still finds a lot to complain about despite the disabled warnings: [pylint-nooptionals.txt](https://github.com/Qiskit/qiskit-terra/files/5991638/pylint-nooptionals.txt)

We could fix it by adding a bunch more pylint suppressions until it runs successfully for a bare qiskit install but this PR explores going the other way and removing the suppressions completely on the basis that you should just install requirements-dev.txt if you are doing dev work.

### CODE REVIEW

**Review by kdk — COMMENTED** [review]
I don't have a strong opinion on whether installing optional packages should be needed to run pylint (code changes look good if so,  if not, we'd probably want CI coverage of both cases).  I did find it interesting that all the warnings raised in `pylint-nooptionals.txt` were from missing matplotlib.

**Comment by levbishop** [comment]
> I don't have a strong opinion on whether installing optional packages should be needed to run pylint (code changes look good if so, if not, we'd probably want CI coverage of both cases). I did find it interesting that all the warnings raised in `pylint-nooptionals.txt` were from missing matplotlib.

Not all from matplotlib. Even after installing matplotlib there are warnings about tweedledum, Ipython, ipywidgets, pygments, ddt, nbformat, nbconvert, networkx, hypothesis....

**Comment by levbishop** [comment]
To summarize a discussion from today: The consensus seems to be that all tooling (`pylint`, testing, CI, etc) should pass if all the requirements in `requirements-dev.txt` are installed (this is what `tox.ini` and the CI pipeline do). In case there are packages that are difficult to install (eg jax on windows) then they can be excluded from `requirements-dev.txt` and in that case pylint suppressions (and test skipping) may be required -- we should drop otherwise superfluous import-error suppressions.

I will redo this PR to match that philosopy.

**Comment by levbishop** [comment]
> I will redo this PR to match that philosopy.

No changes were needed. I think this is ready to merge

**Review by kdk — APPROVED** [review]

**Pull request merged**
