### PR TITLE
Pin setuptools in CI

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

The recently released setuptools 64.0.0 release introduced a regression
that prevents editable installs from working (see pypa/setuptools#3498).
This is blocking CI as we use editable installs to build and install
terra for testing. When there is an upstream release fixing this issue
we can remove the pins.

### CODE REVIEW

**Comment by agroszer** [comment]
`SETUPTOOLS_ENABLE_FEATURES="legacy-editable"` helped us

**Comment by mtreinish** [comment]
@agroszer thanks, I'll give that a try now. I was just trying to avoid needing that in the hope a downgrade/pin would be sufficient. I'm not sure what is causing the previous release to fail now.

**Comment by agroszer** [comment]
went down the same rabbithole

**Review by kevinhartman — DISMISSED** [review]
LGTM

**Review by Cryoris — APPROVED** [review]

**Comment by agroszer** [comment]
setuptools 64.0.1 fixes this

**Pull request merged**
