### PR TITLE
Remove VCR

### LINKED ISSUE #2468: No module named 'vcr': requirement is missing (vcrpy)
### Information

- **Qiskit Terra version**: 0.10.1
- **Python version**: 3.7.3
- **Operating system**: windows 10

### What is the current behavior?
Fresh qiskit installation inside a new environment on windows 10. 
In one of the terra tutorial (using_the_transpiler) `from qiskit.test.mock import FakeTokyo` is failing 'ModuleNotFoundError: No module named vcr'

### Suggested solutions
'pip install vcrpy' 
'vcrpy' needs to be added in requirements.

### PR DESCRIPTION
**Pull request by 1ucian0**
This PR removes VCR. Thanks for your service!

This PR also moves the logic from https://github.com/Qiskit/qiskit-terra/pull/2305 into the test option.

Fixes #2468

### CODE REVIEW

**Comment by mtreinish** [comment]
Can you also remove the record and mock-online tox targets from the tox.ini too?

**Comment by 1ucian0** [comment]
done in 8912c0e5

**Comment by 1ucian0** [comment]
Fixes #2468

`on hold` because @diego-plan9 would like to have a deeper look. Remove the tag when you are done!

**Comment by diego-plan9** [comment]
> on hold because @diego-plan9 would like to have a deeper look. Remove the tag when you are done!

Thanks! Yes, is mostly some extra time to ensure the IBMQ provider (as arguably is the main user of the online decorators, and is under an active round of development for the new API) is able to cope correctly with the changes proposed.

**Comment by diego-plan9** [comment]
Removing `on hold`, as the provider now includes the decorator in order to avoid depending on the possible deprecation.

**Pull request merged**
