### PR TITLE
Remove autoscale view call from plot_state_hinton

### LINKED ISSUE #4249: `plot_state_hinton` doesn't plot all real matrix components
### Information

- **Qiskit Terra version**: 0.13
- **Python version**: 3.7
- **Operating system**: MacOS

### What is the current behavior?

`plot_state_hinton` isn't plotting all matrix components for computational basis states.

### Steps to reproduce the problem

Plot a computational basis state on any number of qubits

```python
from qiskit.quantum_info import DensityMatrix
from qiskit.visualization import *

rho = DensityMatrix.from_label('11').data
plot_state_hinton(rho)
```
returns

hinton_broken

### What is the expected behavior?

It should look like the hinton version of hte city plot, but there are not enough ticks or entrys on the real part of the plot. It is only plotting the one non-zero component.

city_working

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

This commit removes the use of matplotlib's autoscale_view() [1] from
the plot state hinton visualization. This function is truncating the
plot if there are axis that are empty. This is not really necessary for
the hinton function anyway since we have fixed limits on the plots as we
add the ticks based on the shape of the input matrix. However it was
being used to handle boxes on edges of the graph (ie when the top row or
right most edge had a box) that wouldn't be properly centered. This
commit worksaround that by padding both sides of the tick list to ensure
the data is always centered.

### Details and comments

[1] https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.autoscale_view.html

Co-authored-by: Christopher J. Wood <cjwood@us.ibm.com>

Fixes #4249

### CODE REVIEW

**Comment by 1ucian0** [comment]
I might be missing something. Here is the output on the branch `mtreinish:fix-hinton`:
```python
from qiskit import QuantumCircuit, BasicAer, execute, visualization
qc = QuantumCircuit(2)
qc.h(0)
qc.cx(0,1)
qc.z(1)
backend = BasicAer.get_backend('statevector_simulator')
job = execute(qc, backend=backend)
sv = job.result().get_statevector(qc)
visualization.plot_state_hinton(sv)
```
image

In master, the looks fine:
image

**Review by 1ucian0 — DISMISSED** [review]
I might be missing something. Here is the output on the branch `mtreinish:fix-hinton`:
```python
from qiskit import QuantumCircuit, BasicAer, execute, visualization
qc = QuantumCircuit(2)
qc.h(0)
qc.cx(0,1)
qc.z(1)
backend = BasicAer.get_backend('statevector_simulator')
job = execute(qc, backend=backend)
sv = job.result().get_statevector(qc)
visualization.plot_state_hinton(sv)
```
image

In master, it looks fine:
image

**Comment by mtreinish** [comment]
Ugh, yeah it looks like everything is off by one now, in that case. I only tested the bug case and it worked fine for that, but clearly this needs more adjustment

**Comment by mtreinish** [comment]
With @chriseclectic fix on top of my branch this works fine with the example before:

hinton

so this should be good to go now.

**Review by chriseclectic — APPROVED** [review]

**Pull request merged**
