### PR TITLE
Add a script to submit a QASM file to a backend

### PR DESCRIPTION
**Pull request by t-imamichi**
A script to submit a QASM file to a backend.

## Description
User can submit a QASM file to any of backends of https://quantumexperience.ng.bluemix.net/qx/devices

## Motivation and Context
Users sometimes just have and/or make QASM files instead of python scripts with QISKit.
This script helps such users run and test their QASM files.

## How Has This Been Tested?
- First, copy `Qconfig.py` in the same directory as `run_qasm.py`.
- Prepare a QASM file, say `test.qasm`.
- Run the following command.
```
$ python run_qasm.py --qasm test.qasm --device sim  # submit to the simulator
$ python run_qasm.py --qasm test.qasm --device qx2  # submit to ibmqx2
```

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by atilag** [comment]
As we encourage people to use our Python API to create their circuits, there are still many valid use cases of people making QASM programs. This could be a nice tool for them (I admit it was in our wishlist too).
I'm gonna tag this issue as good for contributors :)
The external tool should reside into the the `/tools` (not `/qiskit/tools`) directory.

**Comment by t-imamichi** [comment]
Thank you for your comment. My commit puts the script in `/tools`. Do you have any suggestion to revise it?

**Comment by atilag** [comment]
Nevermind, I though this was an Issue! We usually want to discuss these things in an issue before starting to code.
I cannot review this at the moment, if nobody can before mid next week, I will.

**Comment by jaygambetta** [comment]
I would like to rewrite it slightly different as soon the online backends will not understand qasm. You should go though a path of load a qasm and then run a qasm with tools in the sdk this way this is not broken when we switch to qobj. @levbishop can give more information.

**Comment by ewinston** [comment]
Hi Takashi, I think it could be useful to have a command line script to run circuits, however the implementation is not taking advantage of methods already defined in the SDK. For instance there is already a JobProcessor class which seems similar to your JobManager class. Also, there is some redundancy in backend handling. Finally, how we submit jobs to the API is changing in the next release to qobj which might break this.

**Comment by t-imamichi** [comment]
Hi, Erick. Thank you for the information. I agree that I have to write a new script based on the upcoming qobj-based-API.

**Comment by delapuente** [comment]
@t-imamichi, @ajavadia should this be part of Qiskit, or is it a tool build on top of Qiskit?

**Comment by t-imamichi** [comment]
I am sorry. I forget to close this PR. Since a job manager has been implemented, this PR should not be part of Qiskit.

**Pull request closed without merging**
