### PR TITLE
accept single qubit in initialize to fix #8408

### LINKED ISSUE #8408: QuantumCircuit.initialize()  no longer accepts single instance of Qubit
### Environment

Used to work in Qiskit v0.34.2, tested to not work in v0.37. Appears to have been broken by commit https://github.com/Qiskit/qiskit-terra/commit/3591fa635db75e3d7f1afea19359acb2fb3a6740

### What is happening?

We used to be able to `circuit.initialize([0,1], qr[0])` but now that raises an error `TypeError: 'Qubit' object is not iterable`

Changing to `circuit.initialize([0,1], [qr[0]])` works as the `qubits` parameter is now a list. Prior to commit https://github.com/Qiskit/qiskit-terra/commit/3591fa635db75e3d7f1afea19359acb2fb3a6740 the `QuantumCircuit._bit_argument_conversion()` function was called on the passed in `qubits` param. Should that still be called?

### How can we reproduce the issue?

```
# Successful with Qiskit v0.34.2, raises error with v0.35.0+
qr = qiskit.QuantumRegister(1)
circuit = qiskit.circuit.QuantumCircuit(qr)
circuit.initialize([0, 1], qr[0])
```

### What should happen?

Unless there is a need to not convert single `Qubit` into a list automatically, I would have expected the `circuit.initialize([0,1], qr[0])` to work.

### Any suggestions?

It appears `QuantumCircuit._bit_argument_conversion()` still exists. Maybe adding the `qubits = self._bit_argument_conversion(qubits, self.qubits)` call back to `initialize()` will restore the expected functionality?

### PR DESCRIPTION
**Pull request by epelaaez**
### Summary
To fix issue #8408, passes `qubits` through `QuantumCircuit.qbit_argument_conversion()` in the `initialize` function before creating the `Initialize` instruction to make sure they are formatted correctly.

### Details and comments

Fix #8408.

### CODE REVIEW

**Comment by Cryoris** [comment]
Thanks for the PR @epelaaez! I'm not quite sure if this is the right solution though, as the `qbit_argument_conversion` is still called in `append`. Isn't the error comming from calling `len` on a single qubit? If yes, couldn't we resolve this by changing the `if` statement to include single `Qubit`s? 🙂 

Also could you add a test to check the fixed behavior?

**Comment by epelaaez** [comment]
Thanks for the feedback @Cryoris! You were right, the issue was with calling `len` on a single qubit. I've changed the solution to also check for single `Qubit`s in the `if` statement. Also, I've added a simple test, please let me know if this is sufficient.

**Comment by Cryoris** [comment]
Looks good! Could you update the documentation to reflect this function accepts qubits and add a bugfix releasenote?

**Comment by epelaaez** [comment]
Done @Cryoris!

**Comment by Cryoris** [comment]
Looks good thanks! Actually, could you add the same to the `state_preparation` method (in `state_preparation.py`)? Since that's the same initialize just without the reset it would be good if they behave the same way.

**Comment by epelaaez** [comment]
Done @Cryoris! I also added a test and updated the release note I had pushed.

**Review by jakelishman — APPROVED** [review]
This looks good, thanks for the fix!

**Pull request merged**
