### PR TITLE
Migrate qiskit.aqua.utils, qiskit.aqua.aqua_globals and qiskit.aqua.quantum_instance to qiskit.utils

### PR DESCRIPTION
**Pull request by manoelmarques**
#### Attention: 
The files were migrated from qiskit-aqua with their commit history included. I understand that the merge ***should be a merge commit*** and not a ***squash and merge*** in order to preserve the previous Aqua history.

### Details and comments
Migrate:

qiskit/aqua/utils/arithmetic.py
qiskit/aqua/utils/backend_utils.py
qiskit/aqua/utils/circuit_utils.py
qiskit/aqua/utils/entangler_map.py
qiskit/aqua/utils/measurement_error_mitigation.py
qiskit/aqua/utils/name_unnamed_args.py
qiskit/aqua/utils/run_circuits.py
qiskit/aqua/utils/subsystem.py
qiskit/aqua/utils/validation.py
qiskit/aqua/aqua_globals.py
qiskit/aqua/quantum_instance.py
qiskit/aqua/aqua_error.py
qiskit/aqua/missing_optional_library_error.py

from qiskit-aqua to qiskit-terra.
This commit migrates the above from the qiskit-aqua package to live in qiskit.utils and qiskit.exceptions (last 2 files).
They were originally copied from:

https://github.com/Qiskit/qiskit-aqua/tree/fe939b1eee848a8dea1810810ff8e90374170e97/qiskit/aqua/utils/arithmetic.py
https://github.com/Qiskit/qiskit-aqua/tree/fe939b1eee848a8dea1810810ff8e90374170e97/qiskit/aqua/utils/backend_utils.py
https://github.com/Qiskit/qiskit-aqua/tree/fe939b1eee848a8dea1810810ff8e90374170e97/qiskit/aqua/utils/circuit_utils.py
https://github.com/Qiskit/qiskit-aqua/tree/fe939b1eee848a8dea1810810ff8e90374170e97/qiskit/aqua/utils/entangler_map.py
https://github.com/Qiskit/qiskit-aqua/tree/fe939b1eee848a8dea1810810ff8e90374170e97/qiskit/aqua/utils/measurement_error_mitigation.py
https://github.com/Qiskit/qiskit-aqua/tree/fe939b1eee848a8dea1810810ff8e90374170e97/qiskit/aqua/utils/name_unnamed_args.py
https://github.com/Qiskit/qiskit-aqua/tree/fe939b1eee848a8dea1810810ff8e90374170e97/qiskit/aqua/utils/run_circuits.py
https://github.com/Qiskit/qiskit-aqua/tree/fe939b1eee848a8dea1810810ff8e90374170e97/qiskit/aqua/utils/subsystem.py
https://github.com/Qiskit/qiskit-aqua/tree/fe939b1eee848a8dea1810810ff8e90374170e97/qiskit/aqua/utils/validation.py
https://github.com/Qiskit/qiskit-aqua/tree/fe939b1eee848a8dea1810810ff8e90374170e97/qiskit/aqua/aqua_globals.py
https://github.com/Qiskit/qiskit-aqua/tree/fe939b1eee848a8dea1810810ff8e90374170e97/qiskit/aqua/quantum_instance.py
https://github.com/Qiskit/qiskit-aqua/tree/fe939b1eee848a8dea1810810ff8e90374170e97/qiskit/aqua/aqua_error.py
https://github.com/Qiskit/qiskit-aqua/tree/fe939b1eee848a8dea1810810ff8e90374170e97/qiskit/aqua/missing_optional_library_error.py.

You can refer to that for the full development history leading up until this point.

Co-authored-by: a-matsuo <47442626+a-matsuo@users.noreply.github.com>
Co-authored-by: Christopher Wood <cjwood@us.ibm.com>
Co-authored-by: Donny Greenberg <dongreenberg2@gmail.com>
Co-authored-by: Gawel Kus <gawel.kus@ibm.com>
Co-authored-by: Haruki Imai <imaihal@jp.ibm.com>
Co-authored-by: Ikko Hamamura <ikkoham@users.noreply.github.com>
Co-authored-by: Jack J. Woehr <jwoehr@softwoehr.com>
Co-authored-by: Jakub Marecek <jakub.marecek@ie.ibm.com>
Co-authored-by: Jessie Yu <jessieyu@us.ibm.com>
Co-authored-by: Julien Gacon <jul@zurich.ibm.com>
Co-authored-by: Manoel Marques <Manoel.Marques@ibm.com>
Co-authored-by: Matthew Treinish <mtreinish@kortar.org>
Co-authored-by: Miroslav Tomasik <mirotomasik@gmail.com>
Co-authored-by: Richard Chen <chenrich@us.ibm.com>
Co-authored-by: Richard Young <richard.young2@ibm.com>
Co-authored-by: Shaohan Hu <shaohan.hu@ibm.com>
Co-authored-by: Stephen Wood <40241007+woodsp-ibm@users.noreply.github.com>

### CODE REVIEW

**Review by mtreinish — DISMISSED** [review]
LGTM, but marked as on hold because I want to rebase this on top of #5420 and to ensure we use a merge commit here instead of the default squash (need to enable it when it's time to merge). The on hold label will block mergify from trying to squash this.

**Comment by nonhermitian** [comment]
Just out of curiosity, why is `QuantumInstance` going into a utils folder?  Namely utils are helper functions, but `QuantumInstance` is a primary function still in the applications stack.

**Comment by mtreinish** [comment]
> Just out of curiosity, why is `QuantumInstance` going into a utils folder? Namely utils are helper functions, but `QuantumInstance` is a primary function still in the applications stack.

It was a compromise, I argued it should go in the future qiskit/algorithms directory (which will be added in the next migration PR) since it will only be used by the algorithms which will be migrated in a future PR. Especially since I feel strongly it shouldn't be in the root qiskit namespace. But others felt it was a generally useful tool for some things and knew of examples of places its used directly outside of an algorithm. So we decided on putting it in utils.

Personally I want to see it go away as I don't think it provides value as a standalone thing, and we should have (or add) top level constructs in the provider interface and other utilities to provide any functionality it provides. But, that will likely be a longer process and outside the scope of just migrating this code from aqua into terra.

**Review by mtreinish — DISMISSED** [review]

**Review by mtreinish — APPROVED** [review]

**Comment by mtreinish** [comment]
Just a follow up on the quantum instance location, it will be moved to qiskit.algorithms as fallout from https://github.com/Qiskit/qiskit-terra/pull/5422/commits/258838d104754ad551b42da9a42d39c405161523 we left it in under utils but will move it in the pr that migrates the algorithms directory.

**Pull request merged**
