### PR TITLE
Unify OpenQASM 2 exceptions

### PR DESCRIPTION
**Pull request by jakelishman**
### Summary

Since gh-9784 added a new `qiskit.qasm2` package and suitable exceptions for both import and export of OpenQASM 2 programs, this commit now unifies the exception handling through the rest of the library to use these exceptions.

To avoid breaks in compatibility, the old `qiskit.qasm.QasmError` is now a re-export of `qiskit.qasm2.QASM2Error`.  This is the base error of both the exporter and importers, despite the old documentation of `QasmError` claiming to be specifically for parser errors.  In practice, the exporter also emitted `QasmError`, so having that be `QASM2Error` allows people catching that error to get the same behaviour in these new forms.  The actual exporter and importer are updated to emit the precise subclasses.

### Details and comments

Probably this will clash a little with #9955 (and this PR technically probably wants to merge before that one) and potentially #9953.  I'll fix any merge conflicts as they arise.

This PR is preparing for a later total deprecation and removal of the `qiskit.qasm` namespace, likely starting in Terra 0.26, since we've begun the process of moving to `qiskit.qasm2` and `qiskit.qasm3` as explicitly versioned packages, to avoid confusion in the future.

### CODE REVIEW

**Comment by jakelishman** [comment]
The problems in the QPY backwards compatibility tests are likely because it uses a slightly unusual ordering and import structure for its objects, and there are nasty circular dependencies between `qiskit.qasm` and `qiskit.circuit`.  Once those circular imports are solved, it should not be an issue for the import structure in the QPY backwards compatibility tests if there's a temporary dependency between `qiskit.qasm` and `qiskit.qasm2`, since both will be fully at the same level of the hierarchy.

See #9959 for the fix on that.

**Comment by jlapeyre** [comment]
Arg. I made every effort to ensure no conflicts... Anyway, a blank line and an unwanted import

**Comment by jakelishman** [comment]
John: what are you trying to do to this PR?  It was already up-to-date and rebased completely on top of `main` before your force push.

**Comment by jlapeyre** [comment]
I convinced myself that it was not correct (because it was rebased on most recent main, and things disappeared). But, I think  it was correct. I also think that what I force pushed was also the same as what you did.

**Comment by jlapeyre** [comment]
I fixed or avoided the two errors above here: https://github.com/jakelishman/qiskit-terra/pull/14

**Comment by jakelishman** [comment]
Ok, I've reverted it back to the previous state and put in the correct test fix - the issue is that a change in some of the imports caused `qiskit.qasm2` to be loaded when previously it wasn't, which caused two "new" `Gate` subclasses to be picked up by an automated discovery in a place that they shouldn't have been.

**Comment by jlapeyre** [comment]
I was just comparing your last branch to mine. I think I rebased on top of main that was less up to date than yours. So I agree reverting was correct.

> picked up by an automated discovery in a place that they shouldn't have been.

 I assumed it was intended. I may have tried harder with `DefinedGate`. But I ran into an opaque compiled extension when I wanted to look at `OpCode`.

**Review by jlapeyre — APPROVED** [review]
This looks ready

**Pull request merged**
