### PR TITLE
Wrap probability distributions to `Gate`s, not `Instruction`s

### PR DESCRIPTION
**Pull request by Cryoris**
### Summary

Another follow-up to #6634, in particular to fix the finance tutorials using `AmplitudeEstimation`.

### Details and comments

The probability distributions should be wrapped as `Gate` not as `Instruction` otherwise we cannot call `control` or `inverse` on them.

### CODE REVIEW

**Comment by mtreinish** [comment]
Does this fix all the issues with the wrapping? At this point in the release we need to be sure, otherwise we should revert #6634 and save it for 0.19.0 when we have time to debug these failures.

**Comment by Cryoris** [comment]
I checked the reported tests that failed, but @manoelmarques reported that this tutorial failed which I cannot find: https://ibm-quantumcomputing.slack.com/archives/GNZHKJ93J/p1625717295162700

**Comment by manoelmarques** [comment]
@Cryoris sorry, the link for the failed tutorial is https://github.com/Qiskit/qiskit-aqua/runs/3017779860?check_suite_focus=true

**Comment by Cryoris** [comment]
Ok the tutorial and the finance readme sample now work. I couldn't check all the Aqua tests as there's still Qiskit/qiskit-aqua#1618 to be merged to fix the tests.

**Review by mtreinish — APPROVED** [review]

**Pull request merged**
