### PR TITLE
pi_check in qasm and truncate floats

### LINKED ISSUE #4272: Qasm output should look for numbers close to fractions of pi
### What is the expected enhancement?
`circuit.qasm()` outputs long float values for many parameters even though many are close to fractions of pi that can be checked with `pi_check`.  Also, the number of digits returned is excessive, and should be truncated to a reasonable precision.

### PR DESCRIPTION
**Pull request by nonhermitian**
### Summary
fixes #4272 
Does what the title says.

Screen Shot 2020-04-26 at 22 14 02

### CODE REVIEW

**Comment by ajavadia** [comment]
can you add a test that the qasm produced by this is parsable.

**Comment by ajavadia** [comment]
good to go after it passes

**Comment by nonhermitian** [comment]
Hold on doing sqrt(2) as well

**Comment by jaygambetta** [comment]
@nonhermitian  that was just as a suggestion in my approval. It could be another pr as there might be a few irrational numbers we want to use (don't do them all but quantum does use a few)

**Comment by nonhermitian** [comment]
Ok, I hold off for another day.

**Pull request merged**
