### PR TITLE
average_data can be imported from qiskit.quantum_info.analysis

### LINKED ISSUE #2960: Make it easier to import average_data
### What is the expected enhancement?

Should be able to import `qiskit.quantum_info.analysis.average.average_data` directly from `qiskit.quantum_info`

### PR DESCRIPTION
**Pull request by desireevl**
### Summary
Fixes #2960 

### Details and comments
Simplified importing `average_data`.

Originally: 
```python
from qiskit.quantum_info.analysis.average import average_data
```
New: 
```python
from qiskit.quantum_info import average_data
```

### CODE REVIEW

**Comment by chriseclectic** [comment]
I think we want to discourage the namespace of quantum info being completely flat, and start moving the non-main classes into their sub-modules (eg synthesis, analysis, random).

Here it would make sense to change it to:

```python
from qiskit.quantum_info.analysis import average_data
```

**Comment by ajavadia** [comment]
I agree with Chris's comment: https://github.com/Qiskit/qiskit-terra/issues/2960#issuecomment-536643217

**Comment by 1ucian0** [comment]
Hi @desireevl, still working on this?

**Comment by desireevl** [comment]
@1ucian0 just committed the new change

**Comment by ajavadia** [comment]
@desireevl can you please fix the lint error? you need to insert new lines at the end of the two files you have modified. thanks.

**Comment by 1ucian0** [comment]
I moved ahead and added the extra line breaks. Hope is okey with @desireevl

**Pull request merged**
