### PR TITLE
Add support for slicing and concatenation of PassManagers

### PR DESCRIPTION
**Pull request by faisaldebouni**
…gers

### Summary
Addressed issue #3195 by implementing the following functions in PassManager class:
```
__len__
__getitem__
__add__
```
allowing usage such:
pm = PassManager(..)
pm2 = pm[1:3]
pm3 = pm + pm2[0:2]
pm3 += [pass1,pass2]

### Details and comments
1- `__len__` will return the number of passes sets (FlowControllers) 
Implementing this function caused the following undesired behaviour:
the function `transpile_circuit` in file:transpile_circuit.py checks if a pass manager is selected or not using this if statement:
`if transpile_config.pass_manager:`
however, if an empty pass manager is passed this if statement will be evaluated to False (since length is 0) causing the transpiler to choose different pass managers depending on optimization level although an empty pass manager is selected.
I addressed this issue by changing the if statement to check if `pass_manager is not None` instead.

2- `__getitem__` will create a new PassManager instance which will have the same max_iteration and callback function of the original pass manager, plus the passes selected by the index.

3- `__add__ `
a- when adding two pass managers like:
`pm = pm1 + pm2`
it will create a new PassManager instance with the max_iteration and callback function of the FIRST pass manager and then concatenates the passes of the the second pass 

b- when adding a pass (or list of passes) to a pass manager, like:
`pm += [unroll,basic_swap]`
it will append the pass (or list of passes) to the passes list
however, setting a control for this group of passes is not possible with this syntax

### CODE REVIEW

**Comment by faisaldebouni** [comment]
I apologies for requesting review too early. This is my first PR and I don't know what I'm doing. Anyway, I hope the implementation is complete now.

**Comment by 1ucian0** [comment]
No worries! Let me have a look...

**Comment by faisaldebouni** [comment]
from your PR #3286, I take it that I'm missing something in my implementation. I would really appreciate it if you can just give me some hints. I suspect that it has something to do with the fact that the created passmanager doesn't hold the same property set and valid passes as the original but I believed that this fine since run() resets those and builds them again anyway.

**Comment by 1ucian0** [comment]
The PR #3286 breaks down the pass manager so the user-facing part is much easier. That means that this PR should be simplified, because the pass manager proposed in #3286 should be easier to emulate an iter.

Let's wait for #3286 to get merged. Then we can work together in adapting this PR. Sorry about it @faisaldebouni . Your code was the final push to convince me that the pass manager should be simpler. Thanks for that.

**Comment by 1ucian0** [comment]
`on hold` waiting for #3286.

**Comment by 1ucian0** [comment]
#3286 merged. `on hold` removed

**Comment by faisaldebouni** [comment]
Great work simplifying passmanager class. I will try to adapt this to the new structure.

**Comment by faisaldebouni** [comment]
The implementation should work with the new passmanager now. Please note that the property set is not preserved for the new "sliced" passmanager. If you don't agree that this is the correct behaviour please let me know.

**Pull request merged**
