### PR TITLE
Added cregbundle parameter to mpl drawer

### LINKED ISSUE #4290: MPL drawer should expose cregbundle as a parameter
In the spirit of https://github.com/Qiskit/qiskit-terra/issues/2797, PR https://github.com/Qiskit/qiskit-terra/pull/4274 exposes `cregbundle` as a parameter for circuit drawing.

MPL should use that parameter and deprecate the style dict key.

### PR DESCRIPTION
**Pull request by enavarro51**
### Summary

Fix #4290

### Details and comments

Added the 'cregbundle' parameter to the matplotlib_circuit_drawer function and the MatplotlibDrawer class. The default value for all drawers is now True. 

The style dictionary key, 'cregbundle' has been deprecated and a warning is displayed if used. For now if the user sets this key in the style dict, it will override the parameter setting. All references to 'bundle' have been removed from qcstyle.py.

### CODE REVIEW

**Comment by ajavadia** [comment]
I think @1ucian0 didn't set the default to True as there were some bugs in the text drawer still? I do prefer a default of True across the board if there aren't obvious bugs.

**Comment by enavarro51** [comment]
Yeah. @1ucian0 said to go ahead and set it to True in #4290, and there were no test errors.

**Comment by 1ucian0** [comment]
> I think @1ucian0 didn't set the default to True as there were some bugs in the text drawer still? I do prefer a default of True across the board if there aren't obvious bugs.

Just for the release. Now that we have some time in master, let's flip it to true and hunt those bugs.

**Comment by 1ucian0** [comment]
MPL circuit drawer issues are piling up, since we dont have a good way to track changes on it. I'm putting this PR `on hold` (meaning "do not merge yet") until https://github.com/Qiskit/qiskit-terra/pull/4544 (or a similar solution) gets in.

**Comment by 1ucian0** [comment]
#4544 is merged... Let's add a test with the new method!

I will try helping, but fill free to do it yourself and ask me if any question.

**Comment by 1ucian0** [comment]
I added the test here 98e4a11 !

Check the result here: https://mybinder.org/v2/gh/enavarro51/qiskit-terra/fixissue4290branch?urlpath=apps/test/ipynb/mpl_tester.ipynb

**Comment by enavarro51** [comment]
@1ucian0 #4597 needs to be merged before this one will pass the auto tests.

**Comment by enavarro51** [comment]
Also I looked at your binder. I think there ought to be 2 cregbundle images, one for True and one for False. And each time I click on one of your binder links, it goes through a several minute long build. Is this normal?

**Comment by 1ucian0** [comment]
> @1ucian0 #4597 needs to be merged before this one will pass the auto tests.

Good point! I will start pushing that one. This PR `on hold` until #4597 gets merged.

> Also I looked at your binder. I think there ought to be 2 cregbundle images, one for True and one for False.

Not sure what you mean by this... is the test failing?

> And each time I click on one of your binder links, it goes through a several minute long build. Is this normal?

Yes. That's normal. If the branch has no updates, there is no need in click the link again. You would see the same results.

**Comment by enavarro51** [comment]
Oh, what I meant is that there should be a reference image that shows cregbundle True and a separate image that shows cregbundle False, each of which would be compared to the output of the changed code. One might be affected by a change while the other one isn't.

**Comment by 1ucian0** [comment]
> > @1ucian0 #4597 needs to be merged before this one will pass the auto tests.
> 
> Good point! I will start pushing that one. This PR `on hold` until #4597 gets merged.

Hold on.. #4597 affects latex, not MPL. Why should that one block this one?

**Comment by enavarro51** [comment]
Because this PR sets cregbundle=True as default and the latex version crashes when cregbundle=True, for the test_teleport in test_visualization.py. That's what @rao107 fixed.

**Comment by 1ucian0** [comment]
I see, this PR changes the default. That is not necessary, we have a different PR for that https://github.com/Qiskit/qiskit-terra/pull/4595

Smaller single-issue PR are prefered to avoid blocking.

**Comment by 1ucian0** [comment]
I extended the test.

**Comment by 1ucian0** [comment]
This one was covered by PR #4616.

**Pull request closed without merging**
