### PR TITLE
Add concept of validation pass to passmanager

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

This commit adds a new type of base pass to the pass manager validation
passes. These passes are used to check the current state of the dag and
perform checks on it (and error appropriately if not). For example,
this can be used to to verify whether the dag is valid or not, or
whether it can actually be run on the specified backend or not.
Since validation passes are only for checking the state of the
transpilation they can only read the DAG and property set and not modify
either.

### Details and comments

### CODE REVIEW

**Comment by mtreinish** [comment]
The other thought I had here was instead of just having validation passes error when they encounter an error is to maybe have a `validation_errors`  attribute on the pass manager which will be appended to if a validation error encounters an issue, then have run() raise an error with all the details from that if is anything set it in there.

**Comment by 1ucian0** [comment]
I just would like to [add this](https://github.com/Qiskit/qiskit-terra/issues/3289#issuecomment-545100355), as an example of a validation pass.

**Comment by 1ucian0** [comment]
Ill implement [this pass](https://github.com/Qiskit/qiskit-terra/issues/3289#issuecomment-545100355) in this PR as the first use-case.

**Comment by taalexander** [comment]
+1 on this, I have something similar here https://github.com/Qiskit/qiskit-terra/blob/6c1b0aa08660c7322f208828a8535c0e5aed2249/qiskit/pulse/basepasses.py#L152 that was very useful 

For an example see https://github.com/Qiskit/qiskit-terra/blob/6c1b0aa08660c7322f208828a8535c0e5aed2249/qiskit/pulse/validation.py#L25

This made assembling the Qobj as a lowering pass much simpler.

https://github.com/Qiskit/qiskit-terra/blob/6c1b0aa08660c7322f208828a8535c0e5aed2249/qiskit/pulse/lowering.py#L76

**Comment by 1ucian0** [comment]
I think the best way to do something like this, following our design is:
```
def is_map_correct(pm):
   return pm['map'] == "the right one"

...

pm.append(CheckMap(coupling_map))  # this analize and runs the result of the analysis in the property set
pm.append(ErrorPass(msg='the map is not correct', action="raise", condition=is_map_correct())
```
Actions could be things like `warning_log`, `raise`, or something else.

**Comment by 1ucian0** [comment]
I implemented this in https://github.com/Qiskit/qiskit-terra/pull/5274 Have a look

**Comment by 1ucian0** [comment]
I'm closing this one in favor of #5274

**Pull request closed without merging**
