### PR TITLE
Remove warnings about dt, dtm, and rep_time units changing

### PR DESCRIPTION
**Pull request by lcapelluto**
### Summary

They've been in place for 3 months, they should be removed in the next release

### CODE REVIEW

**Comment by 1ucian0** [comment]
Did we reno the issue as "deprecated" before? If yes, lgtm!

**Comment by lcapelluto** [comment]
@1ucian0 there was a "change-rep-time-unit" upgrade in 0.12. I can't find the similar upgrade for `dt`. The warnings were to make sure users weren't surprised that units of the return values had changed, but the methods are the same. Would you like me to add another upgrade note that the warning is no longer there, and a reminder about the units?

**Comment by 1ucian0** [comment]
I think a deprecated release note would make it. The warnings were there and we just need a way to tell users the reason for their code stopped working, if they ignored the warnings...

**Comment by lcapelluto** [comment]
Will do!

**Pull request merged**
