### PR TITLE
Remove aer provider tests

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

These tests haven't run in a long time, they skip (not silently but
among all the test results no one notices) They also don't work
currently even if we fix the original breakage. If we're not
cross-testing terra master on aer and vice versa keep these tests in
terra don't provide value (although travis and appveyor limit how much
we can do there). We can revisit adding them back in the future if
needed.

### Details and comments

### CODE REVIEW

**Comment by ajavadia** [comment]
@chriseclectic do the tests in Aer cover the ones here? or is there something we should still port over? I agree they don't belong in Terra.

**Comment by chriseclectic** [comment]
The test headers and test multi-register conventions ones could be ported over since I we don't test those things currently.

**Comment by ajavadia** [comment]
Ok I'll open an issue in Aer and we can remove them from Terra once @mtreinish rebases this.

**Comment by mtreinish** [comment]
> Ok I'll open an issue in Aer and we can remove them from Terra once @mtreinish rebases this.

Oops, I didn't see the merge conflict, It's rebased now. I'll never understand why github can't handle a 3-way merge sanely...

**Comment by jaygambetta** [comment]
did we open a link in aer. Can link it here and then I'm good to merge as long as the test are in aer

**Comment by ajavadia** [comment]
https://github.com/Qiskit/qiskit-aer/issues/188

**Pull request merged**
