### PR TITLE
Allow giving jobs names via execute for IBMQ devices

### PR DESCRIPTION
**Pull request by nonhermitian**
### Summary
Allows for setting a job name when using `execute` with an IBMQ backend.

### CODE REVIEW

**Comment by nonhermitian** [comment]
I am not sure how this got merged, as I just updated the branch.

**Comment by nonhermitian** [comment]
Fortunately, the error has nothing to do with the PR:
```
************* Module qiskit.extensions.quantum_initializer.initializer
qiskit/extensions/quantum_initializer/initializer.py:214:23: E1101: Module 'scipy' has no 'kron' member (no-member)
```

feel free to revert if feel it necessary.

**Comment by 1ucian0** [comment]
Maybe something wrong about code ownership? I'll check.

**Comment by kdk** [comment]
On the lint error, scipy released 1.4.0 yesterday, though I checked locally and `scipy.kron` still exists. It is deprecated though, so now seems as good a time as any to replace it with `numpy.kron`.

**Comment by 1ucian0** [comment]
I think, as owner, you can circumvent code ownership. Did you see any warning/pop up?

**Pull request merged**
