### PR TITLE
Add measure and reset methods to QuantumState classes

### PR DESCRIPTION
**Pull request by chriseclectic**
### Summary

Adds `measure` and `reset` methods to `Statevector` and `DensityMatrix` classes.

### Details and comments

* `measure` samples a single measurement outcome for the specified subsystems, and collapses those systems to the post-measurement computational basis state.

* `reset` resets the specified subsystems to the |0> computation basis state (for statevectors this involves sampling a measurement outcome so is non-determinisitic).

### TODO

- [x] Statevector reset tests
- [x] Statevector measure tests
- [x] Density matrix reset tests
- [x] Density matrix measure tests

### CODE REVIEW

**Comment by ajavadia** [comment]
Should `sample_measure` from #3987 be called just `sample`, as it's just sampling a distribution and not measuring & collapsing like here (also it would be shorter).

**Comment by chriseclectic** [comment]
I thought `sample` along wasn't descriptive enough (you could sample many things from a state). Maybe it could be `sample_counts` instead of `sample_measure` though? (would we still keep the `memory=True` option if its sample counts though, maybe add a `sample_memory`?)

**Comment by ajavadia** [comment]
`sample_counts` and `sample_memory` sound good to me, but i'm good with whatever you want. just wanted to bring up what we mean by "measure" (if it's collapsing in our terminology)

**Comment by chriseclectic** [comment]
@ajavadia I made a separate PR (#4056) for renaming sample_measure

**Pull request merged**
