### PR TITLE
Update image reference for visual testing

### LINKED ISSUE #9760: visual testing needs an update (and maybe some regressions?)
Currently (0.24.0.dev0+126c9ba), the images in the visual testing are falling behind. Some, they might even highlight regressions. Here a list of the suspicious ones:

- [ ] `test_idle_wires_barrier`: maybe the default changed? [reference](https://user-images.githubusercontent.com/766693/224000340-0734d000-4a1b-4218-a3f9-6091efa337ef.png) [new image](https://user-images.githubusercontent.com/766693/224000379-632e4db1-1da7-4d76-9fb6-8c2fc9a1afe8.png) [diff](https://user-images.githubusercontent.com/766693/224000422-43bf546f-eea0-4ade-9655-38d00519c2c4.png)
- [ ] `test_plot_barriers`: the barrier label is great [reference](https://user-images.githubusercontent.com/766693/224002322-c0dfee5f-420b-40e6-a85b-cb42cc045c6f.png) [new image](https://user-images.githubusercontent.com/766693/224002410-483cb741-aacf-4dd7-b42f-8ec8c556df4b.png) [diff](https://user-images.githubusercontent.com/766693/224002451-eac5a6e3-2289-41fd-905d-e863a3963bd1.png)
- [ ] `test_plot_state_hinton`: why smaller? [reference](https://user-images.githubusercontent.com/766693/224003543-4b6b9fbf-57b0-45b2-9f2f-5bc09880cd05.png) [new image](https://user-images.githubusercontent.com/766693/224003561-42a55ff0-7e66-476f-8d77-6ed30033fe8a.png) [diff](https://user-images.githubusercontent.com/766693/224003572-b069be62-335a-46a1-9129-c6be5eecd904.png)
- [ ] `test_plot_histogram_2_sets_with_rest` (`histogram_2_sets_with_rest.png`): the result is not the same [reference](https://user-images.githubusercontent.com/766693/224004096-bf1268c0-5478-4b88-aa3d-a0d5eb052184.png) [new image](https://user-images.githubusercontent.com/766693/224004125-25328487-0051-4719-8354-d655f46cf1b5.png) [diff](https://user-images.githubusercontent.com/766693/224004138-171ebe94-34ad-4611-93d3-fc5362059917.png)

Run `jupyter notebook test/ipynb/mpl_tester.ipynb` to check details

This issue is to update the reference images and submit issues for regressions when confirmed

### PR DESCRIPTION
**Pull request by 1ucian0**
Fixes #9760 

Most of them, they just needed new references. In the case of `idle_wires_barrier.png`, the parameter to test was missing.

### CODE REVIEW

**Review by jakelishman — COMMENTED** [review]
All reference images that involve a $\lvert0\rangle$ seem to be showing a regression that needs fixing - in the new versions of these files, an incorrect character is being used for the left vertical of the ket.

**Comment by 1ucian0** [comment]
Hard to know how it was before. Here a solution I got from `bloch.py`

**Comment by jakelishman** [comment]
Actually, `\lvert` and `\rvert` require `amsmath`.  It might be trickier than I'd hoped to thread suitable `\usepackage{amsmath}` headers into every required place, so maybe we don't actually bother fixing things.  `\left.|` or bare `|` are still not really correct, but in _most_ places that they're being used, the growth isn't really used and the spacing isn't the end of the world.

**Comment by 1ucian0** [comment]
after https://github.com/Qiskit/qiskit-terra/pull/9961, this might not be valid anymore

**Pull request closed without merging**
