### PR TITLE
Unify the interface for plot_histogram and plot_state

### LINKED ISSUE #1165: No method to override use of interactive plot visualizations
### What is the expected enhancement?

When running visualizations that have an interactive mode if you're system meets the requirements we unconditionally use the interactive visualizations. We need to provide an option to let users override this and use the non-interactive visualizations.

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

This commit works towards unifying the interfaces for the
plot_histogram and plot_state functions. Right now we have two
implementations of both functions, one using matplotlib and the other
an interactive js visualization. The 2 different backends behave very
similarly (although not identically).

Prior to this commit we treated the functions as the same and chose
which one based on runtime conditions. The interactive js
visualizations are designed to run in jupyter and require network
connectivity to run, so if those were both true we would always use it,
otherwise fallback to the matplotlib. However this approach gave the
user no choice. To address this a top level functions are added in front
of both backends which will provide the public interface. These retain
the current selection logic as before, but also add a kwarg, 'method',
to enable user selection.

### Details and comments

Fixes #1165 

Still todo:

- [X]  Work out differences between backends, mostly that plot_state has no options kwarg and interactive doesn't have filename (might just need to document this as limitations with the backend)
- [X] Figure out options values for interactive plots
- [X] Docstrings for both functions
- [x] Add missing mpl method to plot_state for hinton (implemented in #1246)
- [x] Add return type to mpl plots (just like for circuit_drawer())

### CODE REVIEW

**Comment by mtreinish** [comment]
@nonhermitian when you get a sec I'm curious about your thoughts on the updated interface here. I don't do a lot state visualizations and I want to make sure the changes here still provide a useful interface.

**Comment by nonhermitian** [comment]
Sure, let em take a look.

**Comment by nonhermitian** [comment]
I am getting duplicate images in the notebooks.  Likely because a fig instance is returned now.  Same thing with the mpl circuit drawer in master.

**Comment by nonhermitian** [comment]
I also think that the overall style of the plots could greatly be improved (e.g. the `city_plot` should be viewed from higher up, and not be green, `plot_state` grid lines should be behind the bars (perhaps also backgroud be grey?, we should also use a unified color scheme for plots: https://www.ibm.com/design/language/resources/color-library/ is what I have been using)

**Comment by nonhermitian** [comment]
```python
plot_histogram(job.result().get_counts(circuits[0]), mode='interactive')
```
does not work, complaining about `number_to_keep` `KeyError`, i.e. it must be called with `options={'number_to_keep': XX}`

**Comment by mtreinish** [comment]
Hmm, I normally just fix the duplicate graphs by ending the line in jupyter with a semicolon. Like:

`visualization.plot_state(rho, 'city', mode='mpl');`

But, I guess that's not really a solution. I'd hate to choose between being able to return the actual figure and having this be the default behavior though.

**Comment by mtreinish** [comment]
> ```python
> plot_histogram(job.result().get_counts(circuits[0]), mode='interactive')
> ```
> 
> does not work, complaining about `number_to_keep` `KeyError`, i.e. it must be called with `options={'number_to_keep': XX}`

Yeah, looks like that was a bug in #866, I'll push a patch to this pr to fix the broken logic in the interactive histogram.

**Comment by mtreinish** [comment]
> I also think that the overall style of the plots could greatly be improved (e.g. the `city_plot` should be viewed from higher up, and not be green, `plot_state` grid lines should be behind the bars (perhaps also backgroud be grey?, we should also use a unified color scheme for plots: https://www.ibm.com/design/language/resources/color-library/ is what I have been using)

I've got a local branch in progress reworking the style for the 'city' plot method per some of @jaygambetta comments in #1246. Let's open an issue and keep track of all the changes that need to happen to fix the visualization style.

**Comment by nonhermitian** [comment]
Perhaps calling: `plt.close(fig)` right after you return the fig internally.  It should plot the first time, but not on return.

**Comment by mtreinish** [comment]
Oh, that's a good idea, I'll push up a patch doing that.

**Comment by mtreinish** [comment]
@jaygambetta this should be fixed now

**Pull request merged**
