### PR TITLE
No more basis_gates as string

### LINKED ISSUE #1333: Unify basis_gates parameter handling (using a list)
### What is the expected enhancement?

(I have the feeling there is already an issue for this topic but can't seem to find it - apologies if it ends up being a duplicated issue).

After #1323, the `basis_gates` for a backend is defined in its configuration as a list:
```
'basis_gates': ['u1', 'u2', 'u3', 'cx', 'id', 'snapshot']
```

Traditionally, we have been passing a comma-separated string around for the internal functions (throughout the transpiler layers), which is a tad ackward and cumbersome (specially since the final "consumers" of the basis gates end up splitting the string into a list, such as the `DAGBackend`). 

Actually one of the changes in #1323 was actually to "stringify" back the basis gates [at the right point in the transpilation process](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/transpiler/_transpiler.py#L62), mostly for avoiding modifying the function signatures. It might be a good time to avoid that going back and forth entirely, making it always a list throughout the whole transpilation process.

### Proposed solution

Remove the default value for `basis_gates` in the functions involved in the transpilation process, updating the docstrings and ensuring that it is handled properly at the main entry point. A potential drawback is that we might need to change the format of the argument in the public `compile()` method, deprecating or similar (although might not be a concern if we mostly keep the change internal).

### PR DESCRIPTION
**Pull request by 1ucian0**
This PR deprecates parameter `basis_gates` as a string in the transpilation/compilation process.
Fixes #1333

### CODE REVIEW

**Comment by ajavadia** [comment]
Can we keep the old one working with a DeprecationWarning please?

**Comment by ajavadia** [comment]
And a line to the "changed" section of the CHANGELOG, since these are touching relatively common user-facing functions (compile/execute)

**Comment by diego-plan9** [comment]
> Can we keep the old one working with a DeprecationWarning please?

Yes, please - ideally "sanitizing" the parameter at the highest level possible, to prevent several deprecation warnings cascading through (for example, `transpile()` -> `transpile_dag()`, etc). Also, can we mention the version where it will be fully deprecated (ie. `in qiskit 0.X+`, `after qiskit 0.blah`) either on the warning, docstring, or at #1645?

Taking advantage of your work on `basis_gates` topic and the file, can you check if this TODO still  makes sense?
https://github.com/Qiskit/qiskit-terra/blob/b81275ac74e14d10db815fe2532812b27c43db46/qiskit/transpiler/_transpiler.py#L176

**Comment by 1ucian0** [comment]
Yes. The `TODO` still makes sense. Also.... shall we remove this after 0.8?

**Comment by dongreenberg** [comment]
Can you please add a line in the changelog and warning for the correct way to unroll? I've had a bunch of external folks asking me a lot of questions about this (and using the string form we're deprecating here).

**Comment by 1ucian0** [comment]
Changelog entry in 2ec0f1b2.

**Comment by 1ucian0** [comment]
A more detail deprecation message added in 9e0d0a9f.

**Comment by 1ucian0** [comment]
PR ready!

**Pull request merged**
