### PR TITLE
Convert issue templates to GitHub forms

### LINKED ISSUE #7253: Update issue templates to latest one
GitHub has rolled out new issue forms for public repository.
https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/
Please check this out.
I recently got to know about this Feature. It will be good if we implement this in this repository.

### PR DESCRIPTION
**Pull request by jakelishman**
### Summary

The feature and enhancement request forms are essentially unchanged.
The bug report form makes more use of the description fields, since now
they're not buried in HTML comments in the textarea bodies - they're
more likely to be read, and they're not in the way so much.

### Details and comments

You can't make a form for PRs yet, which is a shame.  Fix #7253.

The new form looks like this:

Screenshot 2021-11-11 at 13 06 32

The issue body it produces at the end looks basically identical to what we have now - for example, see jakelishman/qiskit-terra#4.  If we like this, I can copy it across to the other Qiskit family repos as well, for consistency.

### CODE REVIEW

**Comment by levbishop** [comment]
If the templates make sense across all of qiskit github organization, this could be a good candidate for the default mechanism?
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

**Comment by jakelishman** [comment]
I didn't know GitHub had defaults - that's cool!  Here, while I think we'll be similar across the repository, we specifically ask for the version of `Terra` (cf. `Aer`, whatever) in the top matter, and that'll need to change across each.  Thinking more, we've got retworkx and openqasm that also need to do their own thing here.  By the docs, if you want to overwrite any of the issue templates, you have to overwrite all of them - we can't have generic enhancement and feature request templates get inherited, but everyone writes their own bug reporter.

Perhaps I could make a generic template that just asks for the version information of "this package" in the organisation? Terra, Aer, OpenQASM and retworkx will likely all overwrite those templates, but it might make it a bit easier for things like qiskit-nature, qiskit-dynamics, qiskit-machine-learning, and any new spin-outs we make to get going.

**Comment by divshacker** [comment]
Thank you very much for opening a PR @jakelishman

**Review by levbishop — APPROVED** [review]

**Comment by levbishop** [comment]
Probably worth adding a template repo as well. Indeed we're likely to override it once new projects get going, but can be good to set a default.

**Pull request merged**
