### PR TITLE
fix BasicAer sampling bug (#1624)

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

* fix BasicAer sampling bug

* changelog

* remove legacysimulator from test_compile

(cherry picked from commit 5f7b2e7fc6e3dd92fc4476c8756fdf99ad4027bf)

### Details and comments

Conflicts:
    CHANGELOG.rst
    test/python/tools/test_compiler.py

The changelog conflicts were inevitable as the stable branch doesn't
have the same history as master. As for the test conflict it was a
difference in the simulator (python vs c++) used, this backport
switches to use the python like on master.

### CODE REVIEW

**Comment by mtreinish** [comment]
Ugh, it looks like the pylint version on the stable branch doesn't work. I'll have to push up a patch to increase the min version or something to workaround this issue.

**Comment by mtreinish** [comment]
Ok, it looks like using pip  constraints to pin all the requirements installed used during the ci jobs to the versions used the last time the stable branch passed works and pylint is passing now. I have a feeling the branch is still a little messed up because I'm seeing 2 entries for travis. But we can tackle that when it's time to merge this.

**Comment by jaygambetta** [comment]
@mtreinish im good for you to merge this and make a new version of terra and qiskit mega.

**Comment by ajavadia** [comment]
I'm also good with this as a hot fix to stable. Will there be a need for `constraints.txt` in the future as well?

**Comment by mtreinish** [comment]
> I'm also good with this as a hot fix to stable. Will there be a need for `constraints.txt` in the future as well?

We may in the future it really depends on whether our requirements and CI continue to work with any pins we have moving forward. In this specific case it's needed because pylint is incredibly picky on which versions of packages it decides to work with. With the version pins for pylint we had on the 0.7.x branch a new version of a secondary or tertiary requirement of something was causing pylint to enter an infinite recursion loop and exit. The only way I could figure out how to workaround it was to just mirror the version of everything installed the last successful run. Removing the pin introduced about 2 dozen new or changed rules that caused the job to fail.

We also do have a constraints.txt file on master right now because of a similar wedge situation caused by pylint's improper use of private APIs in its requirements see: https://github.com/Qiskit/qiskit-terra/pull/1868 so it's likely we'll continue to need this after we merge current master into stable.

**Pull request merged**
