### PR TITLE
Fix the typo in the documentation of CU1Gate and CZGate

### PR DESCRIPTION
**Pull request by ChihHanHuang**
### Summary

1. Fix the typo in the documentation of CU1Gate

https://qiskit.org/documentation/stubs/qiskit.circuit.library.CU1Gate.html#qiskit.circuit.library.CU1Gate

2. Fix the typo in the documentation of CZGate

https://qiskit.org/documentation/stubs/qiskit.circuit.library.CZGate.html#qiskit.circuit.library.CZGate

### Details and comments

1. Fixed typo of Math formula in the documentation of CU1Gate

The documentation page for the CU1Gate displays a Math formula incorrectly. The order is wrong. Original Math formula:
``
|0\rangle\langle 0| \otimes I + |1\rangle\langle 1| \otimes U1
``
It should be

`I \otimes |0\rangle\langle 0| + U1 \otimes |1\rangle\langle 1|`

Here is a visual representation of what was changed:

Original:

image

Correct:

image

Reference:
Please see and compare the doc and code of CU3Gate

https://qiskit.org/documentation/stubs/qiskit.circuit.library.CU3Gate.html

2. Fixed typo of Math formula in the documentation of CZGate

The documentation page for the CZGate displays a Math formula incorrectly. The order is wrong and the order of q_1 and q_0 is also wrong. Original Math formula:
``
CZ\ q_1, q_0 =
            |0\rangle\langle 0| \otimes I + |1\rangle\langle 1| \otimes Z
``
It should be
``
        CZ\ q_0, q_1 =
            I \otimes |0\rangle\langle 0| + Z \otimes |1\rangle\langle 1|
``

Here is a visual representation of what was changed:

Original:

image

Correct:

image

Reference:
Please see and compare the doc and code of CYGate

https://qiskit.org/documentation/stubs/qiskit.circuit.library.CYGate.html

### CODE REVIEW

**Review by Cryoris — COMMENTED** [review]
LGTM, thanks for the fix! Could you also update the description of `CPhase` which has the same error as `CU1`?

**Comment by ChihHanHuang** [comment]
@Cryoris Thank you
Sure. I will create a new PR for CPhase later. You could merge this PR first. Thank you so much

**Comment by Cryoris** [comment]
Since this is only another one-line change I think it would be better to just include it here too 🙂 If you're too busy right now let me know then I can also add it to this PR!

**Comment by ChihHanHuang** [comment]
@Cryoris No problem!Just added it in this PR. Thank you very much

**Review by Cryoris — APPROVED** [review]
LGTM, thanks for adding the CPhase fix!

**Pull request merged**
