### PR TITLE
Fixed issue #693 - increasing spacing of parameters in latex drawer

### LINKED ISSUE #693: increase spacing of parameters in latex drawer
QISKit's visualization module is not properly drawing the **cu1** gate. With the following code,

```
from qiskit import QuantumProgram
from qiskit.tools.visualization import circuit_drawer

qp = QuantumProgram()
qr = qp.create_quantum_register('qr', 3)
cr = qp.create_classical_register('cr', 1)
qc = qp.create_circuit('test', [qr], [cr])
qc.cu1(2.3, qr[0], qr[2])
qc.measure(qr[1], cr[0])

circuit_drawer(qc)
```

The obtained image is,

test

Which is clearly corrupt.

### Informations

- **Qiskit (Python SDK) version**: 0.5.7
- **Python version**: 3.6.6
- **Operating system**: Ubuntu 18.04.1 LTS

### PR DESCRIPTION
**Pull request by carmenrv**
### Summary
Fixes #693 

I have changed the qiskit code because it was written with an older version of qiskit. The new code is:
```python
from qiskit import *
from numpy import pi

#Create a Quantum register with 3 qubits
q = QuantumRegister(3, 'q')

#Create a Quantum Circuit acting on the q register
circ = QuantumCircuit(q)

circ.x(q[0])
circ.cu1(2*pi/(2**2), q[1], q[0])
circ.h(q[1])
circ.cu1(2*pi/(2**3), q[2], q[1])
circ.cu1(2*pi/(2**3), q[2], q[0])
circ.h(q[2])
circ.h(q[0])
circ.cu1(2*pi/(2**2), q[1], q[0])
circ.h(q[1])
circ.cu1(2*pi/(2**3), q[2], q[1])
circ.cu1(2*pi/(2**3), q[2], q[0])
circ.h(q[2])
circ.h(q[0])
circ.cu1(2*pi/(2**2), q[1], q[0])
circ.h(q[1])
circ.cu1(2*pi/(2**3), q[2], q[1])
circ.cu1(2*pi/(2**3), q[2], q[0])
circ.h(q[2])
circ.h(q[0])
circ.cu1(2*pi/(2**2), q[1], q[0])
circ.h(q[1])
circ.cu1(2*pi/(2**3), q[2], q[1])
circ.cu1(2*pi/(2**3), q[2], q[0])
circ.h(q[2])

circ.draw(output='latex') 
```
This code produced two errors, the one described in the issue and also it did not draw some of the H gates.

Screenshot 2019-05-25 at 19 49 18

The problem was that the latex_source code did not include those H gates. Using the following command:

```python
print(circ.draw(output='latex_source'))
```
we may see the `latex_source` that was produced.

```latex
% \documentclass[preview]{standalone}
% If the image is too large to fit on this documentclass use
\documentclass[draft]{beamer}
% img_width = 3, img_depth = 23
\usepackage[size=custom,height=10,width=60,scale=0.7]{beamerposter}
% instead and customize the height and width (in cm) to fit.
% Large images may run out of memory quickly.
% To fix this use the LuaLaTeX compiler, which dynamically
% allocates memory.
\usepackage[braket, qm]{qcircuit}
\usepackage{amsmath}
\pdfmapfile{+sansmathaccent.map}
% \usepackage[landscape]{geometry}
% Comment out the above line if using the beamer documentclass.
\begin{document}
\begin{equation*}
    \Qcircuit @C=0.5em @R=1.0em @!R {
	 	\lstick{q_{0}: \ket{0}} & \control\qw & \dstick{1.6}\qw & \qw & \control\qw & \dstick{0.79}\qw & \control\qw & \dstick{1.6}\qw & \qw & \control\qw & \dstick{0.79}\qw & \control\qw & \dstick{1.6}\qw & \qw & \control\qw & \dstick{0.79}\qw & \control\qw & \dstick{1.6}\qw & \qw & \control\qw & \dstick{0.79}\qw & \qw & \qw & \qw\\
	 	\lstick{q_{1}: \ket{0}} & \ctrl{-1} & \qw & \control\qw & \dstick{0.79}\qw & \qw & \ctrl{-1} & \qw & \control\qw & \dstick{0.79}\qw & \qw & \ctrl{-1} & \qw & \control\qw & \dstick{0.79}\qw & \qw & \ctrl{-1} & \qw & \control\qw & \dstick{0.79}\qw & \qw & \qw & \qw & \qw\\
	 	\lstick{q_{2}: \ket{0}} & \qw & \qw & \ctrl{-1} & \ctrl{-2} & \qw & \gate{H} & \qw & \ctrl{-1} & \ctrl{-2} & \qw & \gate{H} & \qw & \ctrl{-1} & \ctrl{-2} & \qw & \gate{H} & \qw & \ctrl{-1} & \ctrl{-2} & \qw & \gate{H} & \qw & \qw\\
	 }
\end{equation*}

\end{document}
```

As you may see the problem is in the element `\Qcircuit`, in the table that is created there are some missing H gates that should be there:
```
\Qcircuit @C=0.5em @R=1.0em @!R {
	 	\lstick{q_{0}: \ket{0}} & \control\qw & \dstick{1.6}\qw & \qw & \control\qw & \dstick{0.79}\qw & \control\qw & \dstick{1.6}\qw & \qw & \control\qw & \dstick{0.79}\qw & \control\qw & \dstick{1.6}\qw & \qw & \control\qw & \dstick{0.79}\qw & \control\qw & \dstick{1.6}\qw & \qw & \control\qw & \dstick{0.79}\qw & \qw & \qw & \qw\\
	 	\lstick{q_{1}: \ket{0}} & \ctrl{-1} & \qw & \control\qw & \dstick{0.79}\qw & \qw & \ctrl{-1} & \qw & \control\qw & \dstick{0.79}\qw & \qw & \ctrl{-1} & \qw & \control\qw & \dstick{0.79}\qw & \qw & \ctrl{-1} & \qw & \control\qw & \dstick{0.79}\qw & \qw & \qw & \qw & \qw\\
	 	\lstick{q_{2}: \ket{0}} & \qw & \qw & \ctrl{-1} & \ctrl{-2} & \qw & \gate{H} & \qw & \ctrl{-1} & \ctrl{-2} & \qw & \gate{H} & \qw & \ctrl{-1} & \ctrl{-2} & \qw & \gate{H} & \qw & \ctrl{-1} & \ctrl{-2} & \qw & \gate{H} & \qw & \qw\\
	 }
```

Reviewing the code of `latex.py` and analysing https://arxiv.org/pdf/quant-ph/0406003 section Spacing, I found out that substituting `@!R` in row 165 by `@!`  solved the issue. The reason why I decided to make this change is that 
`@!R` Sets  all  rows  to  the  height  of  the  tallest object in the circuit, while `@!`Sets  all  entries  to  the  size  of  the  largest object in the circuit. And if you check the way `latex.py` builds the latex array, you realize that having the adequate size for each layer is important.

After changing that, the output of the program was:

Screenshot 2019-05-25 at 19 58 53

And again using the command:

```python
print(circ.draw(output='latex_source'))
```

the output of `latex_source` was:

```latex
% \documentclass[preview]{standalone}
% If the image is too large to fit on this documentclass use
\documentclass[draft]{beamer}
% img_width = 3, img_depth = 38
\usepackage[size=custom,height=10,width=60,scale=0.7]{beamerposter}
% instead and customize the height and width (in cm) to fit.
% Large images may run out of memory quickly.
% To fix this use the LuaLaTeX compiler, which dynamically
% allocates memory.
\usepackage[braket, qm]{qcircuit}
\usepackage{amsmath}
\pdfmapfile{+sansmathaccent.map}
% \usepackage[landscape]{geometry}
% Comment out the above line if using the beamer documentclass.
\begin{document}
\begin{equation*}
    \Qcircuit @C=0.5em @R=0.0em @! {
	 	\lstick{q_{0}: \ket{0}} & \gate{X} & \control \qw & \dstick{1.6}\qw & \qw & \qw & \qw & \control \qw & \dstick{0.79}\qw & \gate{H} & \control \qw & \dstick{1.6}\qw & \qw & \qw & \qw & \control \qw & \dstick{0.79}\qw & \gate{H} & \control \qw & \dstick{1.6}\qw & \qw & \qw & \qw & \control \qw & \dstick{0.79}\qw & \gate{H} & \control \qw & \dstick{1.6}\qw & \qw & \qw & \qw & \control \qw & \dstick{0.79}\qw & \qw & \qw & \qw & \qw & \qw & \qw\\
	 	\lstick{q_{1}: \ket{0}} & \qw & \ctrl{-1} & \qw & \gate{H} & \control \qw & \dstick{0.79}\qw & \qw & \qw & \qw & \ctrl{-1} & \qw & \gate{H} & \control \qw & \dstick{0.79}\qw & \qw & \qw & \qw & \ctrl{-1} & \qw & \gate{H} & \control \qw & \dstick{0.79}\qw & \qw & \qw & \qw & \ctrl{-1} & \qw & \gate{H} & \control \qw & \dstick{0.79}\qw & \qw & \qw & \qw & \qw & \qw & \qw & \qw & \qw\\
	 	\lstick{q_{2}: \ket{0}} & \qw & \qw & \qw & \qw & \ctrl{-1} & \qw & \ctrl{-2} & \qw & \gate{H} & \qw & \qw & \qw & \ctrl{-1} & \qw & \ctrl{-2} & \qw & \gate{H} & \qw & \qw & \qw & \ctrl{-1} & \qw & \ctrl{-2} & \qw & \gate{H} & \qw & \qw & \qw & \ctrl{-1} & \qw & \ctrl{-2} & \qw & \gate{H} & \qw & \qw & \qw & \qw & \qw\\
	 }
\end{equation*}

\end{document}
```

### CODE REVIEW

**Comment by ajavadia** [comment]
Awesome thank you @carmenrv for tackling the 10-month-old issue!

**Comment by carmenrv** [comment]
> This looks good! Could you update the reference image used in testing the latex drawer too?


test1

**Comment by ajavadia** [comment]
@maddy-tod is there a script to update the reference images? I couldn't find it.

**Comment by maddy-tod** [comment]
@ajavadia to my knowledge there is no script. The only file that needs to be updated is the one tested against in `test_circuit_visualization_output`, so running the test with [this line](https://github.com/Qiskit/qiskit-terra/blob/c29c112c10a4ee0d683164c84ff18f19304e4df5/test/python/visualization/test_circuit_visualization_output.py#L86) removed will generate a new reference image.

**Comment by ajavadia** [comment]
@maddy-tod i tried doing that but those tests are skipped anyway. when i force them to run, they fail for me.

**Comment by maddy-tod** [comment]
It seems that the reference file is very out of date - for example it doesn’t plot the identity gate even though this was added in #1880. I think the best thing to do is to generate a new reference image from this PR and work out how to ensure the reference files don’t get out of date in future - maybe these tests should run more frequently?

**Comment by 1ucian0** [comment]
This PR is from a `master` branch in a fork. Not being an expert git user, this creates a detached HEAD state in which I dont feel comfortable touching. So, I will merge this PR and then regenerate the the reference images. If something goes wrong, I will revert the merge.

**Pull request merged**
