### PR TITLE
Removing pointless (?) setter/getter patter from some algorithms

### PR DESCRIPTION
**Pull request by 1ucian0**
Some of the code imported from Aqua came with this pattern of pointless-looking setter/getters. I might be missing something here. Is it okey to remove them?

### CODE REVIEW

**Comment by manoelmarques** [comment]
One thing I might say is that, specially in the result classes, you lose the property type information and sphinx documentation allowed by typehints for each property getter/setter removed.

**Review by stefan-woerner — APPROVED** [review]

**Comment by Cryoris** [comment]
I agree with Manoel, there's value in having the documentation in some cases. However I think that we indeed to have a lot of boilerplate here.

One solution would be to put the documentation in the class docstring. To keep the type info (which we should) can we use Python's dataclass? https://docs.python.org/3/library/dataclasses.html

**Comment by 1ucian0** [comment]
yeap... I think class docstring is the way to go.

**Comment by woodsp-ibm** [comment]
Its a public interface - the variables and there interaction with the class may be self-evident but it should have documentation as needed. Instance vars can be documented via Sphinx - they are not for now from what I have seen - only class vars.

The getter/setter, even when its a simple private field, is consistent with what is done elsewhere in Qiskit. This change, if its wanted, should be done in a consistent way throughout - maybe doing it on a couple of algos in a PR here  was to open up some discussion with more concrete examples. Maybe it should be opened up as an Issue to bring the subject up more generally with examples to have a wider discussion in Qiskit.

**Comment by levbishop** [comment]
> To keep the type info (which we should) can we use Python's dataclass? https://docs.python.org/3/library/dataclasses.html

Dataclass is really nice but it's a python 3.7+ feature and currently we still support 3.6 (see #5301)

**Comment by mtreinish** [comment]
For documentation, Sphinx will autogenerate the attribute entries for `@property` methods and use the method docstring for that getter method as the attribute docstring. However, there is no requirement to do that just to get documentation, the easiest way is to manually list the attribute in the docstring for the class. With the napolean plugin we use for docstrings it would be something like:

```python
class Foo:
    """Class for something
    
    Attributes:
        my_special_attr (int): This attribute has the number of something for the class
   """
```

**Pull request closed without merging**
