### PR TITLE
[WIP] Enhancement of parallel_map for multi-node environment using mpi4py

### PR DESCRIPTION
**Pull request by imaihal**
### Summary
Parallel_map is used for parallelization in Qiskit, but it can create processes only on single node. This limited the performance improvement of my chemistry example. This PR enhances the parallel_map to run on multiple nodes by using mpi4py.  

### Details and comments
Since original parallel_map uses Pool of multiprocessing module, it can create processes only on single node. MPI for Python (mpi4py) is widely used to run python code on multiple nodes, and provides MPIPoolExecutor, which uses dynamic process management features introduced in the MPI-2 standard. This PR uses it to enhance the existing parallel_map to create processes on multiple noes. This can be done without modifying interface of parallel_map. 

PR

To run this code, you need to set up MPI environment and use mpiexec command as follows.
`
mpiexec  -hostfile <hostfile> -np <number of procs> python -m mpi4py.futures <program> 
`
#### Results
I evaluated this PR using my chemistry example based on [tutorial code (LiH)](https://github.com/Qiskit/qiskit-community-tutorials/blob/master/chemistry/LiH_with_qubit_tapering_and_uccsd.ipynb). I measured the performance by applying some modification such as using quasm_simulator as the backend. A qobj of my example includes 136 circuits(experiments). The performance of parallel_map in transpiling improved by **2.6 times**  in 64 processes in 4 nodes compared with 16 processes in 1 node.

#### TODO
This PR is still in Work-In-Progress because following items need to be updated. 
- This replaces existing parallel_map, but it is better to provide a flag or some mechanism to enable/disable this code
- Error handling may need to be updated  

I would like to hear your comments about this approach.

[Reference] MPIPoolExecutor:
https://mpi4py.readthedocs.io/en/stable/mpi4py.futures.html#mpipoolexecutor

### CODE REVIEW

**Comment by nonhermitian** [comment]
I think the requirement of having mpi4py is a bit much for most users, as is the need for command line execution.  Perhaps what is needed is the ability to set the executor from the call to `parallel_map`?

**Comment by imaihal** [comment]
Thanks for the comments. I think so, too. I think one node is enough for most users, so, currently most users don't want to set up MPI environment.

I merged with latest master. Now, modification is basically just one line to replace executor. Yes, that is one way to enable/disable.

**Comment by kdk** [comment]
Is it possible to detect at runtime whether a user is running in an mpi4py environment, and switch between the two executors accordingly?

**Comment by imaihal** [comment]
Sorry for late reply. I need to find good(general) way, but I think it is possible.

**Comment by ajavadia** [comment]
@imaihal any update on this?

**Comment by mtreinish** [comment]
@imaihal since this is stale and hasn't been updated in > 1yr I'm going to close this PR. But please feel free to reopen this if you have the bandwidth to finish the implementation and update this for current terra.

**Pull request closed without merging**
