### PR TITLE
Add equivalences from CX to CPhase+U and CRZ+U

### LINKED ISSUE #6906: Transpiling `cp` into `['u', 'cx']` works; transpiling `cx` into `['u', 'cp']` doesn't
### Information

- **Qiskit Terra version**: `0.18.0`
- **Python version**: `Python 3.9.6`
- **Operating system**: `Pop!_OS 21.04 x86_64`

### What is the current behavior?
I am able to transpile a `cp` gate into using `['u', 'cx']` as basis gates, but I am unable to transpile a `cx` gate using `['u', 'cp']`. I want to be able to use `['u', 'cp']` as the transpilation target for more advanced circuits, but it does not work. Additionally, trying to transpile to `['u', 'crz']` also fails.

### Steps to reproduce the problem
```
from qiskit import QuantumCircuit, QuantumRegister
from qiskit import transpile
import numpy as np

# works fine
qr3 = QuantumRegister(2)
qc3 = QuantumCircuit(qr3)
qc3.cp(np.pi, qr3[0], qr3[1])
qc3 = transpile(qc3, basis_gates=['u', 'cx'])
print(qc3)

# fails to transpile
qr1 = QuantumRegister(2)
qc1 = QuantumCircuit(qr1)
qc1.cx(qr1[0], qr1[1])
qc1 = transpile(qc1, basis_gates=['u', 'cp'])
print(qc1)
```

### What is the expected behavior?
Transpilation  should work in both directions, and `['u', 'cp']` should be a complete gate set.

### Suggested solutions
I believe this is an issue with the way the transpiler runs; I don't understand all of the details of the transpiler to offer any useful suggestions.

### PR DESCRIPTION
**Pull request by epelaaez**
### Summary
Adds CX equivalences to fix issue #6906 

### Details and comments
None

### CODE REVIEW

**Review by 1ucian0 — CHANGES_REQUESTED** [review]
Thanks @epelaaez Can you add a test for this case and a release note?

It also seems that you have to readjust `test.python.transpiler.test_basis_translator.TestBasisExamples.test_cx_bell_to_ecr`. You can test it locally with :
```
tox -epy37 -- -n test.python.transpiler.test_basis_translator.TestBasisExamples.test_cx_bell_to_ecr
```

**Comment by 1ucian0** [comment]
Do you mind having a look @kdk ?

**Comment by kdk** [comment]
> It also seems that you have to readjust test.python.transpiler.test_basis_translator.TestBasisExamples.test_cx_bell_to_ecr. 

This is likely uncovering an issue that needs to be fixed within the `BasisTranslator`. The new rules are allowing it to find a faster-to-find but ultimately worse decomposition of `cx` in terms of `ecr` (the pass as written currently always prefers the fastest translation it can find). I'll take a look at updating the weightings used in the search.

**Comment by epelaaez** [comment]
Thanks for the comment @kdk. 

Then, should I just worry about creating a new test for the added feature and the release note?

**Comment by kdk** [comment]
> Then, should I just worry about creating a new test for the added feature and the release note?

That'd be great! I'll take care of looking into the needed changes in the `BasisTranslator`.

**Comment by epelaaez** [comment]
While doing the test for the features I added, I encountered something strange in https://github.com/Qiskit/qiskit-terra/blob/685622de76b1b9074f41f6a674e1bc15af8c3c3c/test/python/transpiler/test_basis_translator.py#L768-L769

As you can see, a `QuantumRegister` is created but not added to the circuit. This wouldn't be a problem if when adding gates the register is not referenced, but it is: https://github.com/Qiskit/qiskit-terra/blob/685622de76b1b9074f41f6a674e1bc15af8c3c3c/test/python/transpiler/test_basis_translator.py#L770-L773

Changing line 769 to `expected = QuantumCircuit(qr)` does not fix the test issue, but I thought it was worth noting.

**Comment by kdk** [comment]
Good catch, that is a latent bug in the test, but agree this isn't likely to be the cause of the `BasisTranslator` failure. (Currently, `QuantumCircuit(2)` implicitly creates a `QuantumRegister(2)` behind the scenes and adds it to the circuit, so these are functionally equivalent, but this behavior is slated to be deprecated in the future.)

**Comment by epelaaez** [comment]
I think the only thing missing is the issue @kdk mentioned about `BasisTranslator`.

**Comment by mtreinish** [comment]
We recently merged a pretty big change in the search algorithm used by the `BasisTranslator` in #7211. It's probably worth rebasing this and testing to see if we're still having issues now.

**Comment by epelaaez** [comment]
Thanks @mtreinish! 

Seems like it is somewhat working now. Linux, Windows, and MacOS tests passed in [1f26cee](https://github.com/Qiskit/qiskit-terra/pull/7013/commits/1f26cee8edb7e69a7d26614f0d7ab2a2e65ccd3a) while Docs and Lint failed, but Linux and Lint are now failing in [de0f5fc](https://github.com/Qiskit/qiskit-terra/pull/7013/commits/de0f5fc5eadf5005b2541adae892b0503bbd6931) while the other pass although I only added some comments. From the pipeline, I see that there was problem while installing Qiskit dependencies: [`ERROR: Could not build wheels for qiskit-terra, which is required to install pyproject.toml-based projects`](https://dev.azure.com/qiskit-ci/qiskit-terra/_build/results?buildId=35363&view=logs&j=8fcf860c-8d5a-5d3a-546e-59924dc71ae1&t=75d638e4-ca43-5212-fafc-49493bf048bf&l=3618). How can I fix this?

Also, I've added the comments illustrating the equivalent circuits for the cx equivalences I added, but I'm missing to add the global phase difference between the normal gate and the equivalence, is there some Qiskit function that can help me compute this phase?

**Comment by mtreinish** [comment]
It looks it was a temporary networking blip that caused the CI jobs to fail. It failed to download some rust dependency packages during the build. Let me retrigger CI on the failed jobs to retry them

**Comment by HuangJunye** [comment]
Awesome! @epelaaez Thanks for your quick response for making the changes and made the PR into Terra 0.20!

**Pull request merged**
