### PR TITLE
MCZ is now drawn correctly in matplotlib (#5981)

### LINKED ISSUE #5981: MPL circuit drawer does not draw CCZ properly
Take the following example:
```python
from qiskit import QuantumCircuit
from qiskit.circuit.library import ZGate

qc = QuantumCircuit(3)
qc.append(ZGate().control(2, ctrl_state='01'), range(3))
```
The `text` and `latex` drawer outputs are the following:
```python
qc.draw('text')

q_0: ─■─
      │ 
q_1: ─o─
      │ 
q_2: ─■─
```
```python
qc.draw('latex')
```
image

However, here is the `mpl` output:
```python
qc.draw('mpl')
```
image

### PR DESCRIPTION
**Pull request by jsistos**
### Summary
Fixes #5981

### Details and comments

When drawing a circuit using the mpl drawer, there is a subset of multi-qubit gates which is drawn in a particular way (such as CX or SWAP). For controlled Z gates, only CZ was included in such cases. This was fixed by including all variations of the Z gate in the case, excluding Z itself.
All multi-controlled Z gates have Z as their base_gate. To exclude Z, we only make sure that gate_name is not Z.

The drawer takes the last parameter in the list of qubits as the 'target' qubit.

### CODE REVIEW

**Review by javabster — CHANGES_REQUESTED** [review]
hi @jsistos I’ve tested manually and it works as expected :tada:

As you’ve made changes to the matplotlib visualisations could you please check if your changes have broken any snapshot tests and add a new test covering the work you’ve done. You can follow these steps to check and update the snapshots:

1. Go to link: https://mybinder.org/v2/gh/jsistos/qiskit-terra/fix5981?urlpath=apps/test/ipynb/mpl_tester.ipynb. This opens a jupyter application running in the cloud which automatically runs the snapshot tests (note this may take some time to finish loading)

2. If any tests fail you should see some sets of 3 images (left: reference image, middle: your test result, right: differences)

3. Fix any broken tests. Working on code for one aspect of the visualisations can sometimes result in minor changes elsewhere to spacing etc. In these cases you just need to update the reference images as follows:
a) download the mismatched images (link at top of jupyter output)
b) unzip the folder
c) copy and paste the new images into `qiskit-terra/test/ipynb/mpl/references` , replacing the existing reference images
d) commit and push your changes, restart the jupyter app in your browser. The tests should now pass.

4. Add new snapshot tests covering your new contributions.
a) Add your new snapshot tests to `test/ipynb/mpl/test_circuit_matplotlib_drawer.py` , where you can also find existing tests to use as a guide.
b) commit and push your changes, restart the jupyter app in your browser and run the cells again. As this is the first time you run your new tests there won’t be any reference images to compare to. Instead you should see an option in the list of tests to download the new images
c) download the new images, then copy and paste into `qiskit-terra/test/ipynb/mpl/references`
d) commit and push your changes, restart the jupyter app in your browser. The new tests should now pass.

Thanks for your contribution so far, keep up the good work!

**Review by javabster — CHANGES_REQUESTED** [review]
Thanks @jsistos tests look good! One last thing, could you add a 'fixes' release note as well please? There is guidance on how to add a release note in the contributing guidelines here: https://github.com/Qiskit/qiskit-terra/blob/master/CONTRIBUTING.md#release-notes

**Comment by jsistos** [comment]
Done @javabster ! Let me know if anything else is needed.

**Review by javabster — APPROVED** [review]
LGTM 🚀

**Review by 1ucian0 — APPROVED** [review]
Great job! Let's merge!

**Pull request merged**
