### PR TITLE
Text drawer extended for drawing circuits with single classical bit conditioning

### PR DESCRIPTION
**Pull request by TharrmashasthaPV**
### Summary

Fixes part of #6475 . This PR extends the current text drawer to support drawing circuits that contain gates or instructions that are conditioned on a single classical bit.

### Details and comments

This PR follows #6018 . The current text drawer breaks when trying to draw circuits that contain instructions with single bit conditioning. This PR fixes this issue. Two tests have been added. Below are some examples of circuits drawn after this PR.

With cregbundle = True:
```
         ┌───┐                          
 q_0: ───┤ H ├───────────────────■──────
         └─╥─┘      ┌───┐      ┌─┴─┐    
 q_1: ─────╫────────┤ X ├──────┤ X ├────
           ║        └─╥─┘      └─╥─┘    
 q_2: ─────╫──────────╫──────────╫──────
           ║          ║     ┌────╨─────┐
c1: 2/═════╬══════════╬═════╡ c1_0 = T ╞
      ┌────╨────┐┌────╨────┐└──────────┘
 c: 2/╡ c_1 = F ╞╡ c_0 = T ╞════════════
      └─────────┘└─────────┘            
```

With cregbundle = False:
```
      ┌───┐          
 q_0: ┤ H ├───────■──
      └─╥─┘┌───┐┌─┴─┐
 q_1: ──╫──┤ X ├┤ X ├
        ║  └─╥─┘└─╥─┘
 q_2: ──╫────╫────╫──
        ║    ║    ║  
c1_0: ══╬════╬════■══
        ║    ║    =1 
c1_1: ══╬════╬═══════
        ║    ║       
 c_0: ══╬════■═══════
        ║    =1      
 c_1: ══o════════════
        =0           
```

### CODE REVIEW

**Comment by javabster** [comment]
HI @TharrmashasthaPV this is generally looking good! I notice in your final test case there is a weird overlap of the second H gate and the classical register, needs some more spacing I think

Screenshot 2021-06-24 at 10 53 57

**Comment by TharrmashasthaPV** [comment]
Hi @javabster . I think that is because the default value of `vertical compression` in `_text_circuit_drawer()` method is `high`. That's why there's an overlap in the H gate. However, the value of vertical compression in the default `.draw()` method is `medium`. For instance the same test circuit when drawn using `.draw()` method outputs

image

**Comment by javabster** [comment]
> Hi @javabster . I think that is because the default value of `vertical compression` in `_text_circuit_drawer()` method is `high`. I guess that's why there's an overlap in the H gate. However, the value of vertical compression in the default `.draw()` method is `medium`. For instance the same test circuit when drawn using `.draw()` method gives me an output as below
> 
> image

Ok it's good that it isn't a bug in `.draw()` but I think it should still be fixed for the `_text_circuit_drawer()`, perhaps by adjusting the vertical compression for cases like this

**Comment by TharrmashasthaPV** [comment]
> > Hi @javabster . I think that is because the default value of `vertical compression` in `_text_circuit_drawer()` method is `high`. I guess that's why there's an overlap in the H gate. However, the value of vertical compression in the default `.draw()` method is `medium`. For instance the same test circuit when drawn using `.draw()` method gives me an output as below
> > image
> 
> Ok it's good that it isn't a bug in `.draw()` but I think it should still be fixed for the `_text_circuit_drawer()`, perhaps by adjusting the vertical compression for cases like this

If I am understanding correct, should we change the value of `vertical_compression` of `text_circuit_drawer()` to `medium` for these tests?

**Comment by javabster** [comment]
> > > Hi @javabster . I think that is because the default value of `vertical compression` in `_text_circuit_drawer()` method is `high`. I guess that's why there's an overlap in the H gate. However, the value of vertical compression in the default `.draw()` method is `medium`. For instance the same test circuit when drawn using `.draw()` method gives me an output as below
> > > image
> > 
> > 
> > Ok it's good that it isn't a bug in `.draw()` but I think it should still be fixed for the `_text_circuit_drawer()`, perhaps by adjusting the vertical compression for cases like this
> 
> If I am understanding correct, should we change the value of `vertical_compression` of `text_circuit_drawer()` to `medium` for these tests? Or would it be better if we have tests for both `medium` and default vertical compressions in the tests?

yep @TharrmashasthaPV that's correct!

@1ucian0 any thoughts about using `_text_circuit_drawer()` instead of .draw()`?

**Comment by 1ucian0** [comment]
> @1ucian0 any thoughts about using `_text_circuit_drawer()` instead of `.draw()`?

In other tests we do the same. I think is good for now. At same point probably makes sense to refactor them at some point.

**Comment by 1ucian0** [comment]
After https://github.com/Qiskit/qiskit-terra/pull/6370, it seems that we are moving towards bullet representations when they are possible. 

Wouldn't be better something like this?
```python
qr = QuantumRegister(2, "qr")
cr = ClassicalRegister(2, "cr")
circuit = QuantumCircuit(qr, cr)
circuit.h(qr[0]).c_if(cr[0], 1)
circuit.h(qr[1]).c_if(cr[1], 0)
circuit.draw('text', cregbundle=False)
```
```
       ┌───┐        
qr_0: ─┤ H ├────────
       └─╥─┘ ┌───┐ 
qr_1: ───╫───┤ H ├─
         ║   └─╥─┘ 
cr_0: ═══■═════╬═══
               ║
cr_1: ═════════o═══
```

(may understanding of your code is that this change would be easy to make. Please, ignore my comment otherwise)

**Comment by TharrmashasthaPV** [comment]
> After #6370, it seems that we are moving towards bullet representations when they are possible.
> 
> Wouldn't be better something like this?
> 
> ```python
> qr = QuantumRegister(2, "qr")
> cr = ClassicalRegister(2, "cr")
> circuit = QuantumCircuit(qr, cr)
> circuit.h(qr[0]).c_if(cr[0], 1)
> circuit.h(qr[1]).c_if(cr[1], 0)
> circuit.draw('text', cregbundle=False)
> ```
> 
> ```
>        ┌───┐        
> qr_0: ─┤ H ├────────
>        └─╥─┘ ┌───┐ 
> qr_1: ───╫───┤ H ├─
>          ║   └─╥─┘ 
> cr_0: ═══■═════╬═══
>                ║
> cr_1: ═════════o═══
> ```
> 
> (may understanding of your code is that this change would be easy to make. Please, ignore my comment otherwise)

Thanks for pointing this out. I have made this change in the latest commit. @javabster I have also made the change in the `vertical_compression` value in the test.

**Review by javabster — APPROVED** [review]
Thanks @TharrmashasthaPV, LGTM 🚀

**Pull request merged**
