### PR TITLE
Fix ``PauliSumOp.permute`` to not change the original object

### PR DESCRIPTION
**Pull request by Cryoris**
### Summary

Fix ``PauliSumOp.permute`` which applies the permutation not only to the new copy that is returned to the user but also to the original object. This only occured when the permutation doesn't add new qubits to the operator.

### CODE REVIEW

**Comment by Cryoris** [comment]
It seems this is actually the symptom of a bigger underlying issue, see #7340

**Comment by jakelishman** [comment]
I'm worried that this is going to have significant performance implications across any opflow operations that use these objects.  If opflow assumes that the inner objects are immutable, then any internal opflow operation that returns a new object will first create a new primitive type, then pass it to the constructor of the opflow type, which will copy it again.  For example, in `PauliSumOp.mul`, it returns `PauliSumOp(scalar * self.primitive, coeff=self.coeff)`.  This creates a new `SparsePauliOp`, which will then be copied.

If you want to do this, you usually add a `copy` keyword argument to the constructor with a default of `True`, and then update all internal library calls to this function to pass `copy=False` (where appropriate).

**Comment by Cryoris** [comment]
For the `PauliSumOp` that's likely not much of an issue since copying it is really efficient (~0.3ms for 100 terms of 500 qubit operators) but looking more into it it seems that, though a design choice, it is not really enforced in other constructors, e.g.
```python
>>> from qiskit.opflow import StateFn
>>> from qiskit.circuit import QuantumCircuit
>>> qc = QuantumCircuit(1)
>>> sf = StateFn(qc)
>>> print(sf)
CircuitStateFn(

q:

)
>>> qc.x(0);
>>> print(sf)
CircuitStateFn(
   ┌───┐
q: ┤ X ├
   └───┘
)

```

Probably it's better to revert to the first version and just fix the permutation.

**Comment by jakelishman** [comment]
This is inner-loop code, though - 0.3ms is a lot of time to waste on something that's called millions of times, but also, there's hidden performance loss because you overstress the garbage collector by allocating and freeing many more objects.

Also, the cost is actually much bigger than you think.  For example, here's the current behaviour for scalar multiplication in your 100-term, 500-qubit operator:
```python
In [1]: from qiskit.opflow import PauliSumOp
   ...: from qiskit.quantum_info import SparsePauliOp, random_pauli_list
   ...: op = PauliSumOp(SparsePauliOp(random_pauli_list(500, 100)))
   ...: %timeit 2 * op
26 µs ± 459 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```
but with the `primitive.copy()` in the constructor of `PauliSumOp` it becomes:
```
In [1]: from qiskit.opflow import PauliSumOp
   ...: from qiskit.quantum_info import SparsePauliOp, random_pauli_list
   ...: op = PauliSumOp(SparsePauliOp(random_pauli_list(500, 100)))
   ...: %timeit 2 * op
79.9 µs ± 1.26 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

so a little over 3 times worse.

**Comment by Cryoris** [comment]
Yeah, good point 😄 Let's only fix the `permute` method then instead of copying in the initializer since the immutability here is also not ensured by other opflow classes.

**Review by ikkoham — APPROVED** [review]
LGTM. Thanks for shooting the problem.

@jakelishman FWIW, opflow is defined as being immutable by the original author. I know that this degrades performance because it returns a copy every time. I think it would be a good idea to provide the option `inplace: bool`, but I think it's a lot of work, and I'd like to eventually unify it with the quantum_info operator, so I'm going to leave this issue.And also, opflow uses permute, and quantum_info uses qargs. I think this is a bit complicated.

**Comment by jakelishman** [comment]
That sounds fine as a process to me, if performance isn't the major concern immediately.

This PR is a simple bugfix that doesn't change any public API, so it's suitable for backporting into the current Terra series - I've also labelled it "stable backport potential" too, so we can get it out sooner.

To be clear, I wasn't suggesting that we make `opflow` mutable - I'm a _big_ fan of everything being immutable. A `copy` keyword in initialisers lets the creator know if it can safely store an object directly or not.  It's kind of an orthogonal concern to mutability.  In reference terms, `copy=True` implies you're passing a single read-only reference, but `copy=False` says you're giving ownership.

**Comment by ikkoham** [comment]
Thank you. For now, I think this is fine, as we can optimize performance when we need it.
I understood the concept of copy. It is clear and I think useful.

**Review by jakelishman — APPROVED** [review]

**Comment by jakelishman** [comment]
(Apologies, this had sat without being merged for a while because it hadn't had "full" code-owner review - Ikko's approval doesn't overcome the branch protection rules on `releasenotes` unfortunately.)

**Pull request merged**
