### PR TITLE
Simulator code optimizations, automatic testing, and Qiskit data structures

### PR DESCRIPTION
**Pull request by yaelbh**
## Description
This is the non-operator-sum part of the PR-split we discussed. The original PR that was split was #276 .
This includes:
1) Improve run time by not applying the identity matrix on the state vector.
2) Handling of floating point equalities.
3) A bunch of new tests for the simulator, accompanied by a script run_tests.py, which runs them sequentially and compares with previous versions.
4) A new file qstructs,py, which defines Python classes that represent QC entities like QuantumState, DensityMatrix, and UnitaryOperator. Including functions for random generation of these entities.

## Motivation and Context
Serves as a basis to the work on operator-sum, which will be the second part in the split of #276 .

## How Has This Been Tested?
Passed all simulator tests (old and new).

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
        Detailing the last item: a bug fix in the Pauli channel interface 

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
       Please provide a link to the document, thanks.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ajavadia** [comment]
put this on hold until the new release incorporating major changes to the cpp code base, and until we have better testing of simulator input/output.

**Comment by ajavadia** [comment]
@yaelbh I think this will be done in Aer and this PR can be closed, is that right?

**Comment by yehuda-naveh** [comment]
Generally yes, but I'll let Yael do the call after she's back on Tuesday. There are parts that should be still taken from here to the new simulator, and maybe some still relevant to existing Terra. I prefer Yael to make the final call here.

**Comment by yaelbh** [comment]
@ajavadia I agree with closing. Perhaps part of this belongs to terra and not to aer, in this case it will be resubmitted to terra in the form of at least one new PR.

**Pull request closed without merging**
