### PR TITLE
Compile split up for transpile passes

### PR DESCRIPTION
**Pull request by jaygambetta**
### Summary

Start of issue #704. As I said it is not going to change any inputs and outputs but allow correct modularity for passes.  I want to do this before we go parallel as done in @nonhermitian  pr and it should be simple to adapt that to this as it only parallelizes the step 2. DAG -> DAG*

### Details and comments

@ajavadia @1ucian0 @nonhermitian this is not finished but I started to split it up as we discussed today. I used functions for now rather than a method on a super dag object (i don't care either way but i dont think we can really make a super dag until we understand the relations) while we make sure all the parts have the elements they need i am fine with functions..

@diego-plan9 it does not change any input and output just the order inside and as such it passes all your tests for qobj.

while doing it I realize we have some major bugs that by getting more modular we should be able to solve easier or make clearer what is our choice. For example, if a user makes a circuit with different registers in the same list and the first is one qubit.

### CODE REVIEW

**Comment by jaygambetta** [comment]
The fails are because of loops not being correct linting for python. Will change when we make the functions use only dag not circuit methods. 

But the biggest part of this Pr is to change the philosophy. We need to start following: 

QuantumCircuits are only to simplify for the user building. It had simple methods. 

Dagcircuit is for the the transpiler and for us if we want to hand remove sections of circuits add in gates etc. all that hard stuff should be done here. 

Qobj is to be sent to the backends.  It is a Jason serialization of dags with some extra backend information. 

We should keep all three phases separate for modularity.

**Comment by diego-plan9** [comment]
Thanks Jay - for housekeeping and reflecting the conversations, I'm adding this PR to the `0.6` milestone (but not the associated issue, as that one is likely to span over in time).

**Comment by ajavadia** [comment]
This is now ready for review.

**Comment by jaygambetta** [comment]
great thanks Ali. 

Next pr i will remove compile from the transpile function and it will only be in the wrapper.

**Pull request merged**
