### PR TITLE
[text-drawer] Fix for CX (and others) open controlled qubtis < 3

### LINKED ISSUE #4052: Error in text drawing of open controlled CX and CCX gates
### Information

- **Qiskit Terra version**: 0.13.0.dev0+6002304
- **Python version**: 3.7
- **Operating system**: Ubuntu 18.04

### What is the current behavior?

The control bullets are drawn closed irrespective of the provided control state in CX and CCX gates in text drawer. The same error is observed in CY gate. Other controlled and multi-controlled gates are drawn fine. See below for an instance.

### Steps to reproduce the problem

```
qc = QuantumCircuit(4)
qc.append(XGate().control(1,ctrl_state='0'),[0,1])
qc.append(XGate().control(2,ctrl_state='10'),[0,1,2])
qc.append(XGate().control(3,ctrl_state='100'),[0,1,2,3])
qc.append(YGate().control(1,ctrl_state='0'),[0,1])
qc.append(YGate().control(2,ctrl_state='10'),[0,1,2])
qc.draw('text')
```

### LINKED ISSUE #4180: Controlled Gate .draw() error: method draws incorrect gate if amount of control qubits < 3
### Information

- **Qiskit Terra version**: 0.18.0
- **Python version**: 3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
- **Operating system**: Linux
- *Qiskit Aqua version**: 0.7.0
That's not a "standard" versions set, expected Aqua version is 0.6.5.
Unfortunately, Controlled gates don't work at all with the standard Qiskit 0.18.0 setup.
See details at the [4175](https://github.com/Qiskit/qiskit-terra/issues/4175) bug investigation.

### What is the current behavior?
Anti-contolled gates with 1 or 2 control qubits aren't displayed correcly

### Steps to reproduce the problem
In the Jupyter notebook cell execute code
```
from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit, execute, Aer
from qiskit.extensions.standard import XGate
import qiskit.tools.jupyter
%qiskit_version_table
qreg = QuantumRegister(5) 
qc = QuantumCircuit(qreg)
control1 = XGate().control(1, ctrl_state='0')
qc.append(control1, [0, 1])
control2 = XGate().control(2, ctrl_state='00')
qc.append(control2, [0, 1, 2])
control2_2 = XGate().control(2, ctrl_state='10')
qc.append(control2_2, [0, 1, 2])
control3 = XGate().control(3, ctrl_state='010')
qc.append(control3, [0, 1, 2, 3])
qc.draw()
```

The result is
image

### What is the expected behavior?

1. q0 control symbol should be "empty circle" in the first gate;
2. q0 and q1 control symbols should be "empty circle" in the second gate;
3. one control symbols should be "empty circle" in the thrid gate;
4. fourth gate is visualized correctly.

I'm not sure where the issue is: in the visualization part, or in the gate part.

**Update 1**: I wrote an additional test. The controlled gate is formed and computed incorrectly. A code below generates a standard "CNOT" gate instead of anti-controlled not:
```
from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit, execute, Aer
from qiskit.extensions.standard import XGate

simulator = Aer.get_backend('qasm_simulator')
qreg = QuantumRegister(2) 
creg = ClassicalRegister(2)
qc = QuantumCircuit(qreg, creg)

#qc.x(qreg[0])
control1 = XGate().control(1, ctrl_state='0')
qc.append(control1, [0, 1])
qc.measure(qreg,creg)   

job = execute(qc, simulator, shots=1000)
result = job.result()
counts = result.get_counts(qc)
print("\nTotal count for 00 and 11 are:",counts)
qc.draw()
```
A circuit and results:
image
With the anti-controlled not only '01' should be measured.

### PR DESCRIPTION
**Pull request by 1ucian0**
Fixes #4180
Fixes #4052

Since we fully support controlled arbitrary gates, CX, CY, CU1, and CU3 are not special cases any more. I removed that code so they fall in the general case which support open controlled gates nicely. I also improved the support for CSWAP, CRZZ, and CRZ.

### CODE REVIEW

**Comment by enavarro51** [comment]
Just a note. This was also being addressed in #4173.

**Comment by 1ucian0** [comment]
Sorry.. I should have checked first.

I think this PR i better because removes code instead of adding.

**Comment by enavarro51** [comment]
Agree on removing the code being better. I was hesitant to do that thinking it might have raised other issues.
But I am also addressing a bigger problem in #4173 with some gates not displaying correctly. I stated the issue in a comment to #4052. I was waiting on @ajavadia to resolve a couple of questions with the fix I did.

**Comment by 1ucian0** [comment]
This PR fixes also CY and CU1, I will check out in the bug you are mentioning if I see any other case. Thanks!

**Comment by Cryoris** [comment]
#4180 also mentions that the simulator doesn't recognize the open controls for CX and CCX correctly, @1ucian0 do you think we should keep it open or create a new issue for that?

**Comment by 1ucian0** [comment]
That's an issue in qiskit-aer, I think. We could either transfer it there or just submit a new issue in aer repo

**Comment by ajavadia** [comment]
Yes if this is a superset of #4180 let's close that one and focus all fixes here with extra tests. Thanks @enavarro51

**Comment by 1ucian0** [comment]
> Yes if this is a superset of #4180 let's close that one and focus all fixes here with extra tests. Thanks @enavarro51

You mean #4173 ?

**Comment by enavarro51** [comment]
Actually it looks to me like #4180 has quite a few additional changes. What I don't know is if @1ucian0 addressed the bug that I referenced in a comment in #4052. If not, then maybe the best course of action is to merge & close #4180 and then I can revert to the new master in #4173 and then add my code back to fix the bug.

**Comment by 1ucian0** [comment]
Merging this PR into https://github.com/Qiskit/qiskit-terra/pull/4173/ to use the fixes from @enavarro51 Thanks!

**Pull request closed without merging**
