### PR TITLE
Drop support for Python 3.7

### PR DESCRIPTION
**Pull request by jakelishman**
### Summary

This updates our documentation and build processes to set Python 3.8 as the oldest support version of Python, consistent with our policy on Python support.

This commit also removes remaining Python-version gating, since we were principally using this to account for differences between 3.7 and 3.8. Several backport packages are no longer required for any suppported Python version, because of this change.

### Details and comments

New niceties that are now valid for inclusion in Terra:

- assignment expressions using `:=` (the walrus operator).  Use these sparingly; it's easy to write illegible code with them that _technically_ passes the style check.  The archetypal clean usage of it is for checking a variable that's created and only used within the `if` branch, like
  ```python
  if (obj_attribute := getattr(obj, "attribute", None)) is not None:
      # ... do something with 'obj_attribute'
  ```
- positional-only parameters in functions.  These arguments _cannot_ be passed as keyword arguments.  When there's no reason that an argument should be passed as a keyword at all, it's a good idea to use this, because it means that the name of that variable isn't leaked into the public API, so changing its name doesn't need any deprecations (for example if the accepted types / objects are going to expand, and the original name doesn't make sense any more).
  
  You can also use positional-only keyword arguments to allow a function that takes `**kwargs` to accept _any_ name:
  ```python
  def f(a, /):
      return a
  f(1)    # 1
  f(a=1)  # TypeError: f() got some positional-only arguments passed as keyword arguments: 'a'
  
  def f(a, /, **kwargs):
      return a, kwargs
  f(1)       # 1, {}
  f(1, a=2)  # 1, {"a": 2}
  ```

  The Python 3.8+ standard library uses lots of these, as do extension modules.  They're often a good idea.
- Lots of parts of the `typing` module are now available without needing the backport `typing_extensions`
- `importlib.metadata` is available without its backport `importlib_metadata`
- Two additions to `functools` are now stabilised (`cached_property` and `singledispatchmethod`) (and `lru_cache` no longer needs a `maxsize` explicitly setting)
- `multiprocessing.shared_memory` is now available.

### CODE REVIEW

**Comment by mtreinish** [comment]
Heh, we've entered the domain where no supported version of python will run multiprocessing on macOS by default, and that's causing a test to fail: https://dev.azure.com/qiskit-ci/qiskit-terra/_build/results?buildId=45813&view=logs&j=80763036-ed5e-5d3e-143d-8ae8edc29f03&t=0b590cc4-1220-55fc-f610-714bdf68abc8&l=23469

**Comment by jakelishman** [comment]
Yeah, that test was testing that we said we'd support Python 10.11??  Pretty odd.  I've removed the test in 1140a03.

**Comment by mtreinish** [comment]
Just out of curiosity I ran `pupgrade --plus-38` on the repo. It changed ~300 lines. I think all of the changes were to type hints though, basically dropping quotes on non-imported types and changing things like `Union[int, flow]` to `int | float` and `Optional[int]` to `int | None`. We probably should look into whether we want to make those changes in a follow up PR

**Comment by jakelishman** [comment]
Yeah, I just tried that.  A bunch of its changes actually look not totally related to Python 3.8 - there's a lot of stuff like removing quotes from delayed annotations in files that already have `from __future__ import annotations` that are fine.  It seems to go beyond its remit, though - it's done a bunch of removing unnecessary tuples from calls to `all`.  It's not _wrong_, but that's not a change enabled by Python 3.8 (and the way it's done it violates black, but that's easy to fix).  Let's look at it in a follow-up.

**Review by mtreinish — DISMISSED** [review]
This LGTM, thanks for doing this. I think we should probably hold off on merging this until after the final 0.24.0 release though, just in case there is a potential version issue during the 2 weeks of overlap while we're developing for both releases at the same time.

**Comment by jakelishman** [comment]
I'm fine doing that, although technically we're developing 0.24 throughout its entire lifecycle, so there'd still be overlap.  There is more risk during the rc period, though, for sure.

**Review by mtreinish — APPROVED** [review]

**Pull request merged**
