### PR TITLE
Add Schedule name in Schedule.draw()

### PR DESCRIPTION
**Pull request by AdithyaSireesh**
### Summary
I added a title to the Schedule.draw() function. This is with regard to request #3752 .
Screen Shot 2020-02-04 at 2 19 22 AM

### Details and comments
The file changed was matplotlib.py . I manually selected a good font size(20px), similar to the one used by the plot_bloch_vector file's title. The y(0.92) position is also hard coded to stay at a good height above the plot.

### CODE REVIEW

**Comment by nkanazawa1989** [comment]
Looks good! Can you add fontsize setting to [style class](https://github.com/Qiskit/qiskit-terra/blob/c028a285e14a8de3ba27718ae1e6ae0d1da96317/qiskit/visualization/pulse/qcstyle.py#L18-L25) and get the value from it? Best font size may change depending on the figure size, which is configurable from the style setting.

**Comment by AdithyaSireesh** [comment]
> style class

Sure thing. Will do that ASAP :).

**Comment by taalexander** [comment]
Hello @AdithyaSireesh any update one changes requested by @nkanazawa1989?

**Comment by taalexander** [comment]
bumping again.

**Comment by AdithyaSireesh** [comment]
Apologies for not responding. I have recently recovered from a bad flu. But, I should get back to working on it in a day or two.

**Comment by taalexander** [comment]
I hope you are feeling better, thank you for updating 😄.

**Comment by lcapelluto** [comment]
Hey, @AdithyaSireesh! I hope you are still feeling well. Do you have time to round back on this?

**Comment by AdithyaSireesh** [comment]
Apologies for not replying. I think there would be a delay if I continued as I fell sick again. Have been trying to get some rest. Once again, I would like to apologise. Is it possible to ask someone else to complete the task?

**Comment by lcapelluto** [comment]
Closing because this is fixed by https://github.com/Qiskit/qiskit-terra/pull/4122

**Pull request closed without merging**
