### PR TITLE
Deprecate Python 3.7 support

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

This commit deprecates Python 3.7 support. During the deprecation window we will continue to fully support Python 3.7 and test it in CI, but it will emit a warning that we will be removing support for 3.7 in the future to inform users to upgrade to Python 3.8 or newer. The removal will occur during the qiskit-terra 0.25.0 release as it is the first release scheduled to occur after the upstream Python EoL date in June 2023. [1]

### Details and comments

[1] https://devguide.python.org/versions/

### CODE REVIEW

**Comment by jakelishman** [comment]
I wouldn't be opposed to us considering doing the removal in Terra 0.24, if that's consistent with our policies (I can't remember), on the basis that Terra 0.24 will still be live _while_ Python 3.7 goes EOL - if we wait til the version after, we officially have to support Python 3.7 after it's done.

I'm also keen to drop Python 3.7 asap really, because the number of work-arounds we have in Terra for pre-Python-3.8 is already big, and it's only going to get bigger over the next 9 months til 0.25.

**Comment by mtreinish** [comment]
Well, it'd violate the deprecation policy if we removed it during 0.24.0 because there isn't an intermediate release between the initial deprecation and the release removal. But we'll be able to remove it from `main` as soon as we branch `stable/0.24` so realistically the burden for development is only the next ~6 months.

**Comment by jakelishman** [comment]
Yeah, violating the policy is no good.  I wish I'd remembered about it before we did 0.22, because I would have wanted to discuss it then.

For maintenance: it's maintenance of the stable branch I'm concerned about - if something breaks in backport/user testing, we may well still need to be putting out more workarounds for an EOL Python into our latest of the software right up til the 0.25 release.  But given that we missed the window to discuss it before 0.22, it's a fairly moot point now.

**Review by jakelishman — APPROVED** [review]
I'm very much looking forwards to seeing the back of Python 3.7 (although that does feel a bit strange for me to say, since it was the version I used for most of my PhD!).  I think it's good to get this merged in sooner rather than later, so people who care about avoiding the deprecation warnings (and test against `main` Terra) have longer to react.

**Pull request merged**
