### PR TITLE
Add auto-validated objects machinery

### PR DESCRIPTION
**Pull request by diego-plan9**
### Summary

Introduce `qiskit.validation`, with the mechanisms for using objects (Models) that are validated at instantiation time against a specification (Schemas). These classes are meant to be the basis for solving  #996 (along with #1023, #1052, #1057 and potentially a number of other issues in the process).

The implementation is based on `marshmallow`, and the PR is in collaboration with @delapuente .

### Details and comments

The functionality is probably best explained by the tests and the documentation - an example of defining a model and its schema is:

```python
    class PersonSchema(BaseSchema):
        name = String(required=True)
        age = Int()

    @bind_schema(PersonSchema)
    class Person(BaseModel):
        pass
```

That allows for different usage:
```python
# Valid instantiation
Person(name='John Doe')
Person(name='John Doe', age=100, other_field_not_in_schema=[1,2,3])
Person.from_dict({'name': 'John Doe'})

# Failing instantiation
Person()  # fails due to not having a field that is required
Person(name='John Doe', age='one hundred')  # fails due to invalid age type
```

The details have been tuned to the Terra needs and the features used currently by the `json` schemas (open-ended nature of a specification, nesting of schemas, support for polymorphic types a-la-oneof, need for validation at instantiation time, ability to enforce that entities conform to a specific schema in the public API). This PR is still marked as a WIP as some further testing and fine-tuning might be needed.

### Next steps

This PR only contains the "base" classes - once the PR is merged, the functions will be updated and the real-world models created.

### CODE REVIEW

**Comment by jaygambetta** [comment]
This looks good to me.

**Comment by jaygambetta** [comment]
Above is not blocking just a question for organization

**Comment by diego-plan9** [comment]
Thanks for the review, @jaygambetta ! We are making some final tweaks and should be ready to get out of WIP soon.

> Should this be under the folder backends/validation

It's a good question - actually is something that was considered at one point, but went with `qiskit/validation` as some bits touch more parts than just the backends backends (for example, the `Results` and the `Qobj`, that will also become based on these utilities in upcoming PRs), and as the concept of "validation" as a whole felt important enough for terra as a whole. We can reevaluate once all the classes are in place before 0.7 if needed, as it is probably something that is easier to decide upon after seeing the real usage.

**Comment by jaygambetta** [comment]
I agree. I also wonder if result and qobj should be. If they are not we can keep it separate just make sure in the documentation that backends results validation and qobj are interconnected concepts.

**Comment by diego-plan9** [comment]
Taking the PR out of WIP after a round of ironing it out along with @delapuente.

**Pull request merged**
