### PR TITLE
Utility for reporting a CI failure as a GitHub issue.

### PR DESCRIPTION
**Pull request by delapuente**
Part of #926 (adds the script but don't use it yet).

This PR adds a new tool for creating an issue on GitHub when the
CI fails. The utility identifies the report with the name of the
branch and commit hash an avoids to open two reports for the same
subject.

### CODE REVIEW

**Comment by delapuente** [comment]
@diego-plan9 @mtreinish what do you think?

**Comment by jaygambetta** [comment]
is there an update on this.

**Comment by delapuente** [comment]
It's still waiting for review.

**Comment by diego-plan9** [comment]
Labelling as `on hold` until after 0.7, as part of the CI discussion.

**Comment by 1ucian0** [comment]
0.7 is out, let's bring this back out of `on hold`

**Comment by mtreinish** [comment]
I have no issue with this as a standalone tool and as something we integrate into travis, since we often (but not always) manually open a bug on CI failures. My only concern with this PR was because of it's early coupling to a proposed decrease in our test matrix (which I'm still opposed to).  But by itself I have no real issue with it.

That being said in my experience maintaining CI systems doing things like this automatically provide little to no benefit without a guarantee of anyone actually looking at it and debugging. What I've seen normally happen with this kind of tool is that we automatically add an issue to our already lengthy list of issues (we're at >140 right now) and it doesn't increase the chances that someone will look at it and/or debug the failure.

**Comment by 1ucian0** [comment]
@delapuente please, update to the current master and let's have it. We can revisit later if the usefulness is worthy.

**Comment by delapuente** [comment]
@diego-plan9 or @1ucian0 this is ready again!

**Pull request merged**
