### PR TITLE
Update colormap for phase in qsphere state visualization

### LINKED ISSUE #5167: Q-sphere phase colors does not match IQX phase colors
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?

As pointed out by @HwajungKang, it is a bit tricky to figure out that the color wheels are more or less rotated by pi.  It is even harder to decode due to the implicit phase re-normalization in the Qiskit Q-sphere that is not mentioned anywhere:

https://github.com/Qiskit/qiskit-terra/blob/dc3a2a667b8dc22512ca409ecae347d8dbdd944c/qiskit/visualization/state_visualization.py#L761

Qiskit:
Screen Shot 2020-10-01 at 13 21 55

IQX:

Screen Shot 2020-10-01 at 13 18 43

### PR DESCRIPTION
**Pull request by alejomonbar**
### Summary

Fixed #5167 

### Details and comments
I modify the color wheel of qsphere visualization to fit the color of the IQX wheel. To do it I modify the beginning of the color list to start from the angle pi + pi/4 which corresponds to the beginning color of IQX. Also, I modify the color of the inside circle to "white" because I was getting bad results when there is no background color (color = plt.rcParams['figure.facecolor']) [see image]

Screen Shot 2020-10-12 at 1 12 20 PM
Screen Shot 2020-10-12 at 1 13 10 PM

### CODE REVIEW

**Comment by alejomonbar** [comment]
@nonhermitian do you think this can solve issue #5167 or should I change something?

**Comment by 1ucian0** [comment]
ping @nonhermitian ?

**Comment by nonhermitian** [comment]
I am good.

**Review by javabster — DISMISSED** [review]
This PR seems to have fallen through the cracks somehow, apologies @alejomonbar. This LGTM 🚀 
Screenshot 2021-06-04 at 10 47 01

**Review by mtreinish — DISMISSED** [review]

**Review by mtreinish — APPROVED** [review]

**Pull request merged**
