### PR TITLE
Fix horizontal barrier offset before ccnot

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

If there is a barrier right before a ccnot in a circuit it requires a
modified horizontal offset for the barrier because of the spacing
between the elements. This commit fixes this by modifying offset when
drawing a ccnot if there is a barrier on overlapping rows in the
circuit.

### CODE REVIEW

**Comment by mtreinish** [comment]
There is a bug in the overlap detection right now, it's not really checking for any overlap, just that there is overlap between the end of the barrier and the ccnot. I will push a new revision fixing this shortly

**Comment by mtreinish** [comment]
Ok, it should properly detect if there is any overlap now

**Comment by jaygambetta** [comment]
I am not sure how to check it. Maybe we should make a list of circuits for viewing.

**Comment by mtreinish** [comment]
When I was writing the patch I just threw together a random circuit with a ccnot to test it:

```
from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister
from qiskit.tools import visualization

qr = QuantumRegister(3)
qr_a = QuantumRegister(2)
c = ClassicalRegister(3)
c_a = ClassicalRegister(2)
qc = QuantumCircuit(qr, qr_a, c, c_a)

qc.h(qr[0])
qc.barrier(qr)
qc.y(qr[0])
qc.x(qr_a[0])
qc.h(qr[1])
qc.h(qr[2])
qc.barrier(qr)
qc.ccx(qr[0], qr[1], qr[2])
qc.x(qr_a[1])
qc.measure(qr, c)
qc.measure(qr_a, c_a)

visualization.latex_circuit_drawer(qc, filename='ccnot.png')
```
to verify this works. With this patch it yields:

ccnot

Without this patch applied it was:

ccnot

**Comment by jaygambetta** [comment]
Looks great.

**Comment by mtreinish** [comment]
@jaygambetta fwiw I fully expect there to be other edge cases related to drawing barriers and overlapping other boxes. The problem is the way barriers are drawn in the latex isn't part of the underlying xymatrix being built by the qcircuit latex library (because lines aren't really elements in the drawing) So every time we encounter an edge condition like this we've got to update the code that loops over the circuit to detect that and adjust the offset. Since nothing with barriers is dynamically spaced. It's pretty tedious...

**Pull request merged**
