### PR TITLE
Add XYGate (#7164)

### LINKED ISSUE #7164: XY gate
### What is the expected enhancement?
It would be useful if the `XY` gate could be added to the existing circuit library https://qiskit.org/documentation/apidoc/circuit_library.html

The use case is for a basis gate for the qiskit transpiler.

### PR DESCRIPTION
**Pull request by epelaaez**
### Summary

Add two-qubit `XYGate(theta, beta)` as discussed in #7164. 

### Details and comments

Closes #7164.

### CODE REVIEW

**Comment by Cryoris** [comment]
The default value looks good to me 👍🏻 Now we just need to make sure the gate is properly tested. A lot of tests should automatically include the gate (and by the number of failing tests it looks like that's the case 😄) so we'll just have to cover possible corner cases.

**Comment by epelaaez** [comment]
The cancelled test ran out of time:

image

Is there any way to circumvent this restriction?

Also, @Cryoris, the new gate is now passing all the tests it goes through. Do you think we need to add new tests specific for this gate or is it good enough with the ones already in place?

**Comment by jakelishman** [comment]
If there are any tests of behaviour that are specific to this gate, then it's useful to add those, but I think you've got that.  The test failure is just one of those annoying things that happens sometimes - occasionally the VMs are overloaded and everything runs really slowly for no real reason.  I've re-run that test, but it's not a big deal anyway.

**Comment by epelaaez** [comment]
Thanks for the clarification @jakelishman! Then, I think this should be good to review!

**Comment by jakelishman** [comment]
I'll leave the full review to Julien (@Cryoris) because I don't really know the context of this PR, but the code all seems fine to me.  Please could you add a feature release note as well?

**Review by 1ucian0 — CHANGES_REQUESTED** [review]
I think `qiskit/circuit/library/__init__.py` also needs to be updated

**Comment by Cryoris** [comment]
If @1ucian0's comment in addressed this looks good to me. We'll have to enable translation and decomposition to this gate though in the future, though.

**Review by jakelishman — APPROVED** [review]

**Pull request merged**
