### PR TITLE
Fix the order of the Lie-Trotter formula in the documentation

### PR DESCRIPTION
**Pull request by Pythonix**
### Summary
The Lie-Trotter formula has a second order error [1][2].

### Details and comments
[1] https://arxiv.org/pdf/math-ph/0506007.pdf
[2] https://simons.berkeley.edu/sites/default/files/docs/15639/trottererrortheorysimons.pdf

### CODE REVIEW

**Comment by poig** [comment]
@Pythonix second order trotterization is SuzukiTrotter, lie trotter is first order
ref: https://qiskit.org/documentation/_modules/qiskit/synthesis/evolution/suzuki_trotter.html#SuzukiTrotter

**Comment by Pythonix** [comment]
@poig Thanks for the reply, according to the documentation it indeed seems to be like that, but the two linked resources contradict that. 
image
That's from the first linked paper.

**Comment by poig** [comment]
> That's from the first linked paper.
I think you might misunderstood the paper
image
image

**Review by Cryoris — COMMENTED** [review]
Yeah that should be $t^2$! Thanks for noticing :) Could you maybe add the first of your references to the docs? It seems easier to find the error scaling in that paper than in the one that is linked right now.

**Comment by Pythonix** [comment]
> Yeah that should be t2! Thanks for noticing :) Could you maybe add the first of your references to the docs? It seems easier to find the error scaling in that paper than in the one that is linked right now.

Should I replace the existing reference, or just add a second one?

**Comment by Cryoris** [comment]
I think a second one would be good 🙂

**Review by Cryoris — APPROVED** [review]
LGTM, thanks for the fix!

**Review by 1ucian0 — APPROVED** [review]

**Pull request merged**
