### PR TITLE
Add benchmark tools

### PR DESCRIPTION
**Pull request by hitomitak**
### Summary
I added the benchmark tools in test/performance/simulate directory.
This benchmark can simulate qiskit, ProjectQ, and Q# with the same qasm scenario or qiskit code. 

### Details and comments

The detailed description is available as following README.md file. 
https://github.com/hitomitak/qiskit-core/tree/benchmark/test/performance/simulate/benchmarks

### CODE REVIEW

**Comment by hitomitak** [comment]
@ajavadia Thank for comments. I added the description to CHANGELOG and fixed some pylint errors.

**Comment by delapuente** [comment]
I love the idea but I would move this to a separated repository since it does not relate directly to Qiskit.

**Comment by jaygambetta** [comment]
@diego-plan9 can we put this on hold and come back to it after 0.6

**Comment by diego-plan9** [comment]
Yes, makes a lot of sense :+1:

**Comment by atilag** [comment]
Thanks @hitomitak !
I do think that these kind of tests, now belong to `Aer`, so I'd suggest to close this issue and move the discussion to the `Aer` repository.

**Pull request closed without merging**
