### PR TITLE
Move jobs to cron and reduce PR test to the reference environment

### LINKED ISSUE #1072: Reduce the number of run test when pushing to a PR
### What is the expected enhancement?
Reduce the number of test run when pushing to a PR by focusing on a reference environment (Python 3.5 + Linux) and add a cron task to perform all the checks once per day.

### PR DESCRIPTION
**Pull request by delapuente**
Fix #1072

### Summary
Reduces run test to the reference environment (Python 3.5, Linux) in Travis and enable a cron task for the remaining tests.

### CODE REVIEW

**Comment by 1ucian0** [comment]
on hold after 0.7

**Comment by ajavadia** [comment]
I'll keep this open until we look into paid plans to see if we can relieve some of the bottleneck.

**Comment by 1ucian0** [comment]
0.7 is out! time to have this discussion back :)

**Comment by diego-plan9** [comment]
Closing as per agreement with the CI task force!

**Pull request closed without merging**
