### PR TITLE
Perform qobj circuit assembly in parallel

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

Right now when assemble() is called with more than 1 circuit
we run this serially. However, each assembly is a self contained task
that can be run in a parallel process. This commit adds parallel_map
usage to assemble_circuits and assemble_schedules to run assembly in
parallel when multiple circuits are being assembled together as part of
a single job.

### Details and comments

### CODE REVIEW

**Comment by kdk** [comment]
Do you have benchmarking data? Assembly is already pretty quick (at least for the largest single circuit cases we benchmark: https://qiskit.github.io/qiskit/#assembler.AssemblerBenchmarks.time_assemble_circuit?p-depth=4096&p-n_qubits=8 ) so I'm wondering what the circuit count/size cutoff is where we end up ahead of the serialization cost.

**Comment by mtreinish** [comment]
Heh, well pseudo-serialization, nothing in terra actually serializes it (that's part of what makes this model so weird) it's just converting from one container format to another (that's why removing marshmallow was able to help with performance so much). But I ran a sweep of benchmarks just now to get an idea, because I wasn't actually sure either. I modified the benchmark case there and added `[self.circuit] * number of circuits`. Running on my 8 core desktop in parallel I got:

```
========== ======= ==================== =============
 n_qubits   depth   number of circuits               
---------- ------- -------------------- -------------
    1         8             1              245±1μs   
    1         8             5              675±7μs   
    1         8             10             1.19±0ms  
    1         8             50           5.31±0.02ms 
    1         8            100           10.4±0.01ms 
    1        128            1              911±6μs   
    1        128            5            3.99±0.03ms 
    1        128            10           7.73±0.01ms 
    1        128            50            38.3±0.2ms 
    1        128           100            77.6±0.3ms 
    1        1024           1            5.43±0.02ms 
    1        1024           5             26.6±0.1ms 
    1        1024           10            54.2±0.2ms 
    1        1024           50             279±2ms   
    1        1024          100             557±2ms   
    1        2048           1             10.8±0.2ms 
    1        2048           5             54.1±0.3ms 
    1        2048           10            110±0.4ms  
    1        2048           50             561±3ms   
    1        2048          100             1.12±0s   
    1        4096           1             21.5±0.2ms 
    1        4096           5             110±0.6ms  
    1        4096           10            223±0.9ms  
    1        4096           50             1.13±0s   
    1        4096          100            2.27±0.01s 
    2         8             1              302±6μs   
    2         8             5              913±20μs  
    2         8             10           1.65±0.01ms 
    2         8             50           7.51±0.01ms 
    2         8            100           14.8±0.02ms 
    2        128            1              1.29±0ms  
    2        128            5            5.87±0.04ms 
    2        128            10           11.5±0.02ms 
    2        128            50            58.1±0.3ms 
    2        128           100            117±0.4ms  
    2        1024           1            8.33±0.03ms 
    2        1024           5             41.7±0.6ms 
    2        1024           10            84.3±0.3ms 
    2        1024           50             432±5ms   
    2        1024          100             865±6ms   
    2        2048           1             16.8±0.4ms 
    2        2048           5             84.5±0.3ms 
    2        2048           10             171±1ms   
    2        2048           50             867±6ms   
    2        2048          100             1.73±0s   
    2        4096           1             33.8±0.2ms 
    2        4096           5              169±4ms   
    2        4096           10             342±1ms   
    2        4096           50            1.72±0.01s 
    2        4096          100            3.44±0.01s 
    5         8             1              383±5μs   
    5         8             5            1.29±0.01ms 
    5         8             10           2.43±0.01ms 
    5         8             50           11.4±0.01ms 
    5         8            100            22.7±0.1ms 
    5        128            1            2.47±0.04ms 
    5        128            5            11.4±0.05ms 
    5        128            10           22.8±0.06ms 
    5        128            50            116±0.3ms  
    5        128           100             234±1ms   
    5        1024           1             16.7±0.2ms 
    5        1024           5             85.9±0.2ms 
    5        1024           10             174±1ms   
    5        1024           50             881±3ms   
    5        1024          100             1.75±0s   
    5        2048           1             34.0±0.5ms 
    5        2048           5             173±0.7ms  
    5        2048           10            346±0.8ms  
    5        2048           50            1.74±0.01s 
    5        2048          100            3.47±0.01s 
    5        4096           1             68.0±0.3ms 
    5        4096           5              347±1ms   
    5        4096           10             697±2ms   
    5        4096           50            3.51±0.01s 
    5        4096          100             7.05±0s   
    8         8             1              507±4μs   
    8         8             5            1.91±0.01ms 
    8         8             10           3.63±0.02ms 
    8         8             50           17.4±0.04ms 
    8         8            100            34.8±0.1ms 
    8        128            1            3.57±0.01ms 
    8        128            5             17.4±0.2ms 
    8        128            10           34.4±0.07ms 
    8        128            50            178±0.4ms  
    8        128           100             359±3ms   
    8        1024           1             26.3±0.3ms 
    8        1024           5              134±1ms   
    8        1024           10            269±0.9ms  
    8        1024           50             1.35±0s   
    8        1024          100            2.74±0.01s 
    8        2048           1             53.7±0.2ms 
    8        2048           5              275±1ms   
    8        2048           10             546±3ms   
    8        2048           50            2.75±0.01s 
    8        2048          100            5.53±0.04s 
    8        4096           1             107±0.4ms  
    8        4096           5              560±1ms   
    8        4096           10             1.12±0s   
    8        4096           50            5.62±0.01s 
    8        4096          100            11.2±0.05s 
========== ======= ==================== =============
```

vs

```
========== ======= ==================== =============
 n_qubits   depth   number of circuits               
---------- ------- -------------------- -------------
    1         8             1              244±1μs   
    1         8             5              674±4μs   
    1         8             10           1.20±0.01ms 
    1         8             50           5.37±0.03ms 
    1         8            100           10.6±0.05ms 
    1        128            1              917±4μs   
    1        128            5            4.02±0.01ms 
    1        128            10           7.89±0.02ms 
    1        128            50             40.1±4ms  
    1        128           100             80.5±9ms  
    1        1024           1            5.51±0.06ms 
    1        1024           5             26.9±0.1ms 
    1        1024           10            54.4±0.3ms 
    1        1024           50             283±3ms   
    1        1024          100             563±6ms   
    1        2048           1            10.9±0.05ms 
    1        2048           5             54.9±0.3ms 
    1        2048           10            111±0.3ms  
    1        2048           50            562±0.4ms  
    1        2048          100             1.13±0s   
    1        4096           1             22.2±0.3ms 
    1        4096           5              116±2ms   
    1        4096           10             224±2ms   
    1        4096           50            1.14±0.01s 
    1        4096          100            2.30±0.01s 
    2         8             1             295±0.7μs  
    2         8             5              908±3μs   
    2         8             10           1.66±0.01ms 
    2         8             50           7.59±0.01ms 
    2         8            100           15.0±0.04ms 
    2        128            1            1.31±0.01ms 
    2        128            5            5.92±0.01ms 
    2        128            10            12.0±0.4ms 
    2        128            50            59.3±0.3ms 
    2        128           100            119±0.2ms  
    2        1024           1            8.51±0.02ms 
    2        1024           5             41.7±0.3ms 
    2        1024           10             85.9±1ms  
    2        1024           50             437±4ms   
    2        1024          100             872±8ms   
    2        2048           1             17.2±0.3ms 
    2        2048           5             86.0±0.7ms 
    2        2048           10             174±3ms   
    2        2048           50             876±3ms   
    2        2048          100             1.76±0s   
    2        4096           1             33.9±0.3ms 
    2        4096           5             174±0.6ms  
    2        4096           10             348±1ms   
    2        4096           50             1.75±0s   
    2        4096          100            3.50±0.02s 
    5         8             1              377±1μs   
    5         8             5              1.31±0ms  
    5         8             10             2.47±0ms  
    5         8             50           11.6±0.05ms 
    5         8            100           23.1±0.02ms 
    5        128            1            2.45±0.02ms 
    5        128            5            11.7±0.07ms 
    5        128            10            23.6±0.3ms 
    5        128            50            120±0.8ms  
    5        128           100            239±0.9ms  
    5        1024           1             17.1±0.2ms 
    5        1024           5              88.0±1ms  
    5        1024           10             176±1ms   
    5        1024           50             892±8ms   
    5        1024          100            1.80±0.01s 
    5        2048           1             34.4±0.3ms 
    5        2048           5              175±1ms   
    5        2048           10             352±1ms   
    5        2048           50            1.77±0.01s 
    5        2048          100            3.65±0.1s  
    5        4096           1             69.8±0.4ms 
    5        4096           5              365±20ms  
    5        4096           10             725±20ms  
    5        4096           50            3.68±0.06s 
    5        4096          100            7.41±0.1s  
    8         8             1              503±2μs   
    8         8             5              1.92±0ms  
    8         8             10            3.71±0.5ms 
    8         8             50            17.9±0.3ms 
    8         8            100            36.1±0.4ms 
    8        128            1            3.76±0.08ms 
    8        128            5             17.8±0.2ms 
    8        128            10            35.9±0.7ms 
    8        128            50             183±3ms   
    8        128           100             371±5ms   
    8        1024           1             27.6±0.4ms 
    8        1024           5              139±4ms   
    8        1024           10             283±5ms   
    8        1024           50            1.44±0.04s 
    8        1024          100            2.80±0.07s 
    8        2048           1             55.9±0.6ms 
    8        2048           5              291±10ms  
    8        2048           10             558±10ms  
    8        2048           50            2.79±0.05s 
    8        2048          100            5.65±0.03s 
    8        4096           1             110±0.6ms  
    8        4096           5              569±2ms   
    8        4096           10            1.15±0.01s 
    8        4096           50            5.86±0.07s 
    8        4096          100            11.5±0.05s 
========== ======= ==================== =============
```

when running serially.

It's not a major difference but still a small speed up. It also looks like at the small single circuit case and low duplicate count there is a small extra cost, probably a combination of the extra loop for each circuit to facilitate running in parallel and forking overhead. I mostly wrote this because it seemed like an easy thing we could do speed things up a bit more after the marshmallow removal. It's actually more subtle of a difference than I was hoping for

**Comment by kdk** [comment]
Thanks for the data. I agree it looks like an improvement. Can pass it through `asv compare --split --no-only-changed`? (The serialization I had in mind was the pickling-depickling to get the circuits to the worker processes and the assembled qobjs back.)

**Comment by mtreinish** [comment]
I'll have to rerun things, it didn't actually store the results because I used --python=same to simplify the configuration of running locally.

**Comment by mtreinish** [comment]
ok, setup up a VM on my desktop with 4 vCPUs and reran the benchmarks so I could do asv compare. This is what the results show:

```
Benchmarks that have stayed the same:

       before           after         ratio
     [8bf63cb4]       [3f191d42]
     <parallel-assemble~2>       <parallel-assemble>
          217±2μs          237±2μs     1.09  assembler.AssemblerBenchmarks.time_assemble_circuit(1, 8, 5)
          392±3μs          423±2μs     1.08  assembler.AssemblerBenchmarks.time_assemble_circuit(1, 8, 10)
          339±2μs          361±2μs     1.07  assembler.AssemblerBenchmarks.time_assemble_circuit(2, 8, 5)
      3.42±0.01ms      3.63±0.05ms     1.06  assembler.AssemblerBenchmarks.time_assemble_circuit(1, 8, 100)
      1.76±0.01ms      1.86±0.01ms     1.06  assembler.AssemblerBenchmarks.time_assemble_circuit(1, 8, 50)
      5.70±0.06ms      6.00±0.06ms     1.05  assembler.AssemblerBenchmarks.time_assemble_circuit(2, 8, 100)
      2.87±0.02ms      2.99±0.01ms     1.04  assembler.AssemblerBenchmarks.time_assemble_circuit(2, 8, 50)
       49.9±0.8ms         51.8±3ms     1.04  assembler.AssemblerBenchmarks.time_assemble_circuit(2, 2048, 5)
          598±1μs          619±3μs     1.04  assembler.AssemblerBenchmarks.time_assemble_circuit(5, 8, 5)
      1.13±0.01ms         1.17±0ms     1.03  assembler.AssemblerBenchmarks.time_assemble_circuit(5, 8, 10)
        101±0.8μs         104±10μs     1.03  assembler.AssemblerBenchmarks.time_assemble_circuit(2, 8, 1)
      5.35±0.03ms      5.44±0.02ms     1.02  assembler.AssemblerBenchmarks.time_assemble_circuit(5, 8, 50)
          1.02±0s       1.04±0.03s     1.02  assembler.AssemblerBenchmarks.time_assemble_circuit(2, 2048, 100)
      1.90±0.01ms      1.93±0.01ms     1.01  assembler.AssemblerBenchmarks.time_assemble_circuit(8, 8, 10)
       11.1±0.1ms       11.2±0.2ms     1.01  assembler.AssemblerBenchmarks.time_assemble_circuit(5, 8, 100)
          994±3μs         1.00±0ms     1.01  assembler.AssemblerBenchmarks.time_assemble_circuit(8, 8, 5)
        158±0.7μs          160±1μs     1.01  assembler.AssemblerBenchmarks.time_assemble_circuit(5, 8, 1)
      9.21±0.05ms      9.30±0.05ms     1.01  assembler.AssemblerBenchmarks.time_assemble_circuit(8, 8, 50)
       1.77±0.02s       1.78±0.03s     1.00  assembler.AssemblerBenchmarks.time_assemble_circuit(8, 1024, 100)
       75.7±0.4μs       76.0±0.7μs     1.00  assembler.AssemblerBenchmarks.time_assemble_circuit(1, 8, 1)
          181±2ms          181±5ms     1.00  assembler.AssemblerBenchmarks.time_assemble_circuit(8, 2048, 5)
          126±2ms          126±2ms     1.00  assembler.AssemblerBenchmarks.time_assemble_circuit(1, 4096, 10)
       19.1±0.2ms       19.1±0.1ms     1.00  assembler.AssemblerBenchmarks.time_assemble_circuit(8, 8, 100)
       40.3±0.3ms       40.2±0.3ms     1.00  assembler.AssemblerBenchmarks.time_assemble_circuit(1, 128, 100)
       3.83±0.01s       3.81±0.09s     1.00  assembler.AssemblerBenchmarks.time_assemble_circuit(8, 4096, 50)
          513±3ms          509±8ms     0.99  assembler.AssemblerBenchmarks.time_assemble_circuit(2, 2048, 50)
          635±4ms         629±10ms     0.99  assembler.AssemblerBenchmarks.time_assemble_circuit(1, 4096, 50)
       32.5±0.3ms       32.1±0.1ms     0.99  assembler.AssemblerBenchmarks.time_assemble_circuit(2, 128, 50)
       1.11±0.01s       1.09±0.01s     0.99  assembler.AssemblerBenchmarks.time_assemble_circuit(5, 1024, 100)
       65.2±0.4ms       64.4±0.5ms     0.99  assembler.AssemblerBenchmarks.time_assemble_circuit(2, 128, 100)
          1.03±0s       1.02±0.02s     0.99  assembler.AssemblerBenchmarks.time_assemble_circuit(2, 4096, 50)
      4.76±0.07ms      4.68±0.05ms     0.99  assembler.AssemblerBenchmarks.time_assemble_circuit(2, 1024, 1)
       3.65±0.03s       3.59±0.04s     0.98  assembler.AssemblerBenchmarks.time_assemble_circuit(8, 2048, 100)
      3.12±0.01ms      3.07±0.02ms     0.98  assembler.AssemblerBenchmarks.time_assemble_circuit(2, 128, 5)
          314±2ms        309±0.8ms     0.98  assembler.AssemblerBenchmarks.time_assemble_circuit(1, 1024, 100)
      3.89±0.07ms      3.82±0.02ms     0.98  assembler.AssemblerBenchmarks.time_assemble_circuit(1, 128, 10)
          239±2μs          235±1μs     0.98  assembler.AssemblerBenchmarks.time_assemble_circuit(8, 8, 1)
       7.67±0.01s       7.53±0.01s     0.98  assembler.AssemblerBenchmarks.time_assemble_circuit(8, 4096, 100)
       20.2±0.2ms       19.8±0.8ms     0.98  assembler.AssemblerBenchmarks.time_assemble_circuit(2, 4096, 1)
       71.6±0.5ms       70.2±0.4ms     0.98  assembler.AssemblerBenchmarks.time_assemble_circuit(5, 128, 50)
       2.24±0.01s       2.19±0.02s     0.98  assembler.AssemblerBenchmarks.time_assemble_circuit(5, 2048, 100)
      1.98±0.01ms      1.94±0.02ms     0.98  assembler.AssemblerBenchmarks.time_assemble_circuit(1, 128, 5)
          678±1μs          663±7μs     0.98  assembler.AssemblerBenchmarks.time_assemble_circuit(2, 128, 1)
          632±3ms          619±2ms     0.98  assembler.AssemblerBenchmarks.time_assemble_circuit(1, 2048, 100)
        255±0.9ms          249±1ms     0.98  assembler.AssemblerBenchmarks.time_assemble_circuit(2, 1024, 50)
      6.19±0.06ms      6.05±0.03ms     0.98  assembler.AssemblerBenchmarks.time_assemble_circuit(2, 128, 10)
       21.5±0.1ms       21.0±0.1ms     0.98  assembler.AssemblerBenchmarks.time_assemble_circuit(5, 2048, 1)
          439±2μs          429±3μs     0.98  assembler.AssemblerBenchmarks.time_assemble_circuit(1, 128, 1)
          145±3ms          142±1ms     0.98  assembler.AssemblerBenchmarks.time_assemble_circuit(5, 128, 100)
       49.3±0.4ms       48.1±0.4ms     0.98  assembler.AssemblerBenchmarks.time_assemble_circuit(2, 1024, 10)
       43.5±0.5ms       42.4±0.6ms     0.98  assembler.AssemblerBenchmarks.time_assemble_circuit(5, 4096, 1)
         1.41±0ms      1.38±0.01ms     0.98  assembler.AssemblerBenchmarks.time_assemble_circuit(5, 128, 1)
          176±1ms          172±3ms     0.97  assembler.AssemblerBenchmarks.time_assemble_circuit(8, 1024, 10)
        115±0.4ms        112±0.6ms     0.97  assembler.AssemblerBenchmarks.time_assemble_circuit(8, 128, 50)
          1.28±0s       1.25±0.01s     0.97  assembler.AssemblerBenchmarks.time_assemble_circuit(1, 4096, 100)
      2.21±0.03ms      2.15±0.01ms     0.97  assembler.AssemblerBenchmarks.time_assemble_circuit(8, 128, 1)
          379±1ms          369±3ms     0.97  assembler.AssemblerBenchmarks.time_assemble_circuit(8, 4096, 5)
      9.68±0.06ms      9.42±0.05ms     0.97  assembler.AssemblerBenchmarks.time_assemble_circuit(2, 2048, 1)
       62.1±0.3ms       60.5±0.3ms     0.97  assembler.AssemblerBenchmarks.time_assemble_circuit(1, 2048, 10)
        102±0.3ms       99.0±0.8ms     0.97  assembler.AssemblerBenchmarks.time_assemble_circuit(2, 2048, 10)
          762±4ms          741±2ms     0.97  assembler.AssemblerBenchmarks.time_assemble_circuit(8, 4096, 10)
       24.6±0.3ms       23.9±0.2ms     0.97  assembler.AssemblerBenchmarks.time_assemble_circuit(2, 1024, 5)
          557±6ms          540±3ms     0.97  assembler.AssemblerBenchmarks.time_assemble_circuit(5, 1024, 50)
        157±0.9ms        152±0.5ms     0.97  assembler.AssemblerBenchmarks.time_assemble_circuit(1, 1024, 50)
          510±2ms          495±3ms     0.97  assembler.AssemblerBenchmarks.time_assemble_circuit(2, 1024, 100)
       35.5±0.2ms       34.4±0.3ms     0.97  assembler.AssemblerBenchmarks.time_assemble_circuit(8, 2048, 1)
      6.80±0.04ms      6.60±0.01ms     0.97  assembler.AssemblerBenchmarks.time_assemble_circuit(5, 128, 5)
       2.08±0.01s       2.02±0.03s     0.97  assembler.AssemblerBenchmarks.time_assemble_circuit(2, 4096, 100)
        110±0.8ms          107±2ms     0.97  assembler.AssemblerBenchmarks.time_assemble_circuit(5, 1024, 10)
       62.4±0.7ms       60.5±0.7ms     0.97  assembler.AssemblerBenchmarks.time_assemble_circuit(1, 4096, 5)
       71.7±0.4ms       69.4±0.4ms     0.97  assembler.AssemblerBenchmarks.time_assemble_circuit(8, 4096, 1)
          318±2ms          308±2ms     0.97  assembler.AssemblerBenchmarks.time_assemble_circuit(1, 2048, 50)
      2.95±0.01ms      2.86±0.02ms     0.97  assembler.AssemblerBenchmarks.time_assemble_circuit(1, 1024, 1)
      10.9±0.08ms      10.6±0.03ms     0.97  assembler.AssemblerBenchmarks.time_assemble_circuit(8, 128, 5)
          4.62±0s       4.47±0.01s     0.97  assembler.AssemblerBenchmarks.time_assemble_circuit(5, 4096, 100)
          221±2ms          214±1ms     0.97  assembler.AssemblerBenchmarks.time_assemble_circuit(5, 2048, 10)
       1.84±0.01s       1.78±0.01s     0.97  assembler.AssemblerBenchmarks.time_assemble_circuit(8, 2048, 50)
       15.0±0.3ms       14.6±0.2ms     0.97  assembler.AssemblerBenchmarks.time_assemble_circuit(1, 1024, 5)
         894±10ms          866±4ms     0.97  assembler.AssemblerBenchmarks.time_assemble_circuit(8, 1024, 50)
       10.7±0.2ms       10.4±0.1ms     0.97  assembler.AssemblerBenchmarks.time_assemble_circuit(5, 1024, 1)
       31.2±0.2ms       30.2±0.4ms     0.97  assembler.AssemblerBenchmarks.time_assemble_circuit(1, 2048, 5)
       54.1±0.3ms       52.3±0.4ms     0.97  assembler.AssemblerBenchmarks.time_assemble_circuit(5, 1024, 5)
          231±2ms        223±0.6ms     0.96  assembler.AssemblerBenchmarks.time_assemble_circuit(8, 128, 100)
       20.2±0.2ms       19.4±0.2ms     0.96  assembler.AssemblerBenchmarks.time_assemble_circuit(1, 128, 50)
       22.1±0.1ms       21.3±0.2ms     0.96  assembler.AssemblerBenchmarks.time_assemble_circuit(8, 128, 10)
          462±4ms          444±3ms     0.96  assembler.AssemblerBenchmarks.time_assemble_circuit(5, 4096, 10)
      5.94±0.09ms      5.71±0.04ms     0.96  assembler.AssemblerBenchmarks.time_assemble_circuit(1, 2048, 1)
      17.5±0.08ms       16.8±0.1ms     0.96  assembler.AssemblerBenchmarks.time_assemble_circuit(8, 1024, 1)
         88.1±1ms       84.7±0.6ms     0.96  assembler.AssemblerBenchmarks.time_assemble_circuit(8, 1024, 5)
       30.4±0.3ms       29.2±0.3ms     0.96  assembler.AssemblerBenchmarks.time_assemble_circuit(1, 1024, 10)
          103±2ms         97.8±2ms     0.95  assembler.AssemblerBenchmarks.time_assemble_circuit(2, 4096, 5)
       13.9±0.2ms      13.3±0.02ms     0.95  assembler.AssemblerBenchmarks.time_assemble_circuit(5, 128, 10)
          209±4ms          199±1ms     0.95  assembler.AssemblerBenchmarks.time_assemble_circuit(2, 4096, 10)
       12.2±0.1ms       11.6±0.2ms     0.95  assembler.AssemblerBenchmarks.time_assemble_circuit(1, 4096, 1)
          370±4ms          351±5ms     0.95  assembler.AssemblerBenchmarks.time_assemble_circuit(8, 2048, 10)
          111±2ms        105±0.3ms     0.95  assembler.AssemblerBenchmarks.time_assemble_circuit(5, 2048, 5)
        696±100μs          659±1μs     0.95  assembler.AssemblerBenchmarks.time_assemble_circuit(2, 8, 10)
       1.13±0.02s          1.07±0s     0.95  assembler.AssemblerBenchmarks.time_assemble_circuit(5, 2048, 50)
       2.34±0.02s       2.22±0.02s     0.95  assembler.AssemblerBenchmarks.time_assemble_circuit(5, 4096, 50)
         240±10ms          222±2ms     0.93  assembler.AssemblerBenchmarks.time_assemble_circuit(5, 4096, 5)
```

**Pull request merged**
