### PR TITLE
Fix registerless bit naming collisions in QASM

### LINKED ISSUE #6779: QASM output of registerless Clbits and Qubits can shadow an existing name
### Information

- **Qiskit Terra version**: 0.19.dev
- **Python version**: all
- **Operating system**: all

### What is the current behavior?

Unbound clbits and qubits are output in QASM into registers invariably called `regless`.  This is a valid identifier for other registers, and the same name is emitted whether or not clashes exist, presumably because `QuantumCircuit` usually keeps names unique when the registers are added to the circuit, so there usually can't be a clash.

### Steps to reproduce the problem

```python
>>> from qiskit.circuit import QuantumCircuit, ClassicalRegister, Clbit, Qubit
>>> cr = ClassicalRegister(2, name='regless')
>>> cb = Clbit()
>>> qb = Qubit()
>>> qc = QuantumCircuit(cr, [cb], [qb])
>>> print(qc.qasm())
OPENQASM 2.0;
include "qelib1.inc";
creg regless[2];
qreg regless[1];
creg regless[1];
```

A similar failure occurs with a `QuantumRegister(..., name="regless")`.

### What is the expected behavior?

The automatically generated `qreg regless[1]` and `creg regless[1]` should have unique names.

### Suggested solutions

As far as I know there are no universally reserved names, but we can just generate a name like `_[cq]regless_<entropy>`, which should be good enough - by `<entropy>` I mostly just mean noise to prevent users from accidentally shadowing the name.  `QuantumCircuit.qasm()` should (I've got to assume!) be deterministic, so the entropy could just be a string like `_qiskitprivate`, or if we really want to make sure users can't create a clash then
```python
entropy = hash(tuple(register.name for registers in self.qregs + self.cregs))
```
That seems like overkill to me, though.

### PR DESCRIPTION
**Pull request by jakelishman**
### Summary

Fix naming collisions of implicit registers in QuantumCircuit.qasm when
dealing with registerless qubits and clbits.  Previously, registerless
qubits and clbits were put into corresponding `qreg` and `creg` both
called `regless`, despite the collision.  They will now have separate,
deterministically generated names, which will not clash with any
user-defined register names in the circuit.

The naming entropy is chosen to be this way to ensure that the output is
entirely deterministic, and reproducible between different runs of
Python and different systems; it's inconvenient for users using things
like Makefiles if our output is not fixed for a given input.

### Details and comments

Fix #6779

### CODE REVIEW

**Comment by levbishop** [comment]
I don't understand the logic of the entropy routine but it doesn't avoid name collisions:
```python
>>> print(QuantumCircuit(ClassicalRegister(2, name=f'qregless_qiskitgenerated_29ea27a3'), [Clbit()], [Qubit()]).qasm())
OPENQASM 2.0;
include "qelib1.inc";
creg qregless_qiskitgenerated_29ea27a3[2];
qreg qregless_qiskitgenerated_29ea27a3[1];
creg cregless_qiskitgenerated_29ea27a3[1];
```

**Comment by jakelishman** [comment]
Yeah, it isn't quite perfect at avoiding naming collisions, but I thought it would be good enough (the previous version had a naming collision immediately).  Really the best solution would be if we had reserved some specific register "namespace" for internal use (like if we disallow register names beginning `qiskitgenerated`), but I didn't want to make that breaking change.  This will be obsoleted by QASM 3 anyway, which allows "loose" qubits and bits, so the implicit register creation won't be necessary.

In this case, to find a collision, you have to _try_: you have to use our salt, and then try to make a collision within that.  I didn't want to use anything more complex like a cryptographic hash function because it'd just be wasting time (crc32 is just a checksum, and on modern hardware it may even by a processor intrinsic), and I didn't want to use something like `id` or `hash` because I wanted the output to be deterministic and independent of the Python version, OS, because I think stochastic output just causes nuisances for people trying to cache output, or things like this.

**Comment by levbishop** [comment]
I feel like this is a kind of a sour-spot solution: it has some slightly confusing code with a performance hit, that since it walks over all of the existing names seems like it might be supposed prevent collisions, but then doesn't actually completely prevent them. I'd prefer either the simple solution where we just error if `regless` is already taken, or a complete solution that never collides (for example trying `regless_1`, `regless_2`, ... until you hit one that's vacant/

**Comment by jakelishman** [comment]
Yeah, that's fair.  I've swapped it to a guaranteed-unique version.

**Review by levbishop — APPROVED** [review]
Looks good now

**Pull request merged**
