### PR TITLE
Fix qubits in gate map when dpi is passed to savefig

### LINKED ISSUE #3710: plot_gate_map and plot_error_map are missing qubit circles in savefig() ouptut with dpi set
### Information

- **Qiskit Terra version**: master
- **Python version**: 3.8
- **Operating system**: Linux

### What is the current behavior?

When running `savefig()` on the output Figure object from `plot_gate_map()` and `plot_error_map()` when the `dpi` kwarg is set, the background circles used for qubit are missing form the output saved. For example:

error_map

### Steps to reproduce the problem
```
from qiskit.visualization import plot_gate_map
from qiskit.test import mock
backend = mock.FakeYorktown()
plot_gate_map(backend).savefig('my_gate_map.png', dpi=450)
```
returns:

my_gate_map

### What is the expected behavior?

A scaled version of:
my_gate_map_no_scaling

### Suggested solutions
Fix the bug when using `savefig()` and dpi kwarg. 

This might be an issue with matplotlib that will need to be fixed over there first.

### PR DESCRIPTION
**Pull request by nonhermitian**
### Summary

fixes #3710

### CODE REVIEW

**Comment by nonhermitian** [comment]
I still cannot get the image tests to pass locally with reference images I have updated myself.

**Comment by nonhermitian** [comment]
So this is once again blocked by image checks that I cannot seem to resolve on OSX.  It works though.

**Comment by ajavadia** [comment]
Do we still need this given https://github.com/Qiskit/qiskit-terra/pull/3896?

**Comment by 1ucian0** [comment]
Closing this PR as  stalled. The issue is tracked by #3710

**Comment by nonhermitian** [comment]
Yes, this is blocked on the fact that images generated on osx don't seem to pass tests. At least I cannot figure it out. The last time I checked this did solve the issue though.

**Review by mtreinish — APPROVED** [review]

**Pull request merged**
