### PR TITLE
checking parameters in CmdDef

### LINKED ISSUE #2603: If more kwargs/args than required are supplied to `CmdDef` and error is not raised
### Information

- **Qiskit Terra version**: master
- **Python version**: 3.7
- **Operating system**:OSX

### What is the current behavior?
If additional kwargs/args are supplied to `cmd_def.get` no error is raised and a result is still returned if the required parameters are present.

### Steps to reproduce the problem
```python
from qiskit.test.mock import FakeOpenPulse2Q
from qiskit.pulse import CmdDef

backend = FakeOpenPulse2Q()
config = backend.configuration()
defaults = backend.defaults()
cmd_def = CmdDef.from_defaults(defaults.cmd_def,
                               defaults.pulse_library)

print(cmd_def.get_parameters('u1', 0))
print(cmd_def.get('u1', 0, 0))
print(cmd_def.get('u1', 0, P1=0, P2=1, P3=2))
```

### What is the expected behaviour?
An error should be raised if unnecessary args/kwargs are supplied. Similarly for an insufficient number of args/kwargs if partial binding is not supported.

### Suggested solutions
Add error checks. @nkanazawa1989 could you check if your PR #2493 fixes this?

### LINKED ISSUE #2641: CmdDef raise an error to bind parameters to ParametrizedSchedule
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
CmdDef cannot bind parameters when ParametrizedSchedule consists of multiple instructions. This is related to #2603 .

### Steps to reproduce the problem
```
from qiskit import IBMQ
from qiskit.pulse import CmdDef

IBMQ.load_accounts()
backend = IBMQ.get_backend('ibmq_poughkeepsie')

default = backend.defaults()
cmd_def = CmdDef.from_defaults(default.cmd_def,default.pulse_library)
cmd_def.get_parameters('u3', 0)
cmd_def.get('u3', 0, P1=1, P2=2, P3=3)
```

### Suggested solutions
Parameters are supplied to CmdDef and checked and bound at each instruction level. This problem can be avoided by checking parameters at CmdDef level.

### PR DESCRIPTION
**Pull request by nkanazawa1989**
### Summary
fix #2641, fix #2603.

### Details and comments
Add check for parameter duplication and undefined parameters in `CmdDef` . Each instruction extracts a subset of parameters defined in the instruction. Unittest is also added.

### CODE REVIEW

**Comment by taalexander** [comment]
Can you please explain why this is required to be implemented at the CmdDef and Schedule level and not the parsed function level? The referenced bug was not present with the old parser and I do not currently understand why it is happening.

**Comment by taalexander** [comment]
I believe it should be possible to fix this without changing the cmd_def, nor should you need to modify the *args/**kwargs of ParameterizedSchedule. Only the way the ParameterizedSchedule tracks and passes parameters to sub-ParameterizedSchedules need be modified.

**Comment by nkanazawa1989** [comment]
Because we didn't care about undefined parameter names, and this was pointed in #2603 and fixed in #2493. After this fix, the parser doesn't accept undefined parameter names and this is the reason of the bug.
```
ParametrizedSchedule(P1, P2, P3)
    |
    +-instruction1(P1)
    |    +-parser1(P1)
    |
    +-instruction2(P2)
    |    +-parser2(P2)
    |
    +-instruction3(P3)
         +-parser3(P3)
```
In the above example, the ParametrizedSchedule calls each instruction under `._parameterized` with parameter set (P1, P2, P3) to bind them, but new parser don't accept undefined parameter names (e.g. only P1 is allowed for parser1, but `.bind_parameters()` passes all (P1, P2, P3) in current implementation). This means we need to prepare sub-parameter set for each instruction not to bind undefined parameters in the parsers.

Actually, we don't have unittests for ParametrizredSchedule with multiple parametrized instructions, and we should cover this situation in the test.

**Comment by nkanazawa1989** [comment]
Ok, I'll think about how to avoid changing CmdDef. The reason why I changed CmdDef is this recursive call.
https://github.com/Qiskit/qiskit-terra/blob/508feafec0e9d67a91847d1dd8a0c09a1706bfed/qiskit/pulse/schedule.py#L379-L381
To prepare a parameter subset from parameter arguments, we can get predefined parameter names from `parameters` property of `param_sched`. However, when `param_sched` is a based callable, it doesn't have the property. Anyway I will update the PR not to change CmdDef.

**Comment by taalexander** [comment]
Thank you for looking at this. I if you make sure to build the kwarg dictionary upon receiving *args, **kwargs at the top level ParameterizedSchedule, the necessary kwargs can then just be passed for each of the lower level ParameterizedSchedules. This is just a temporary fix and we should think about how to incorporate parameters natively in Schedule.

**Comment by nkanazawa1989** [comment]
Yes, I agree. I modified the code to do so. 
https://github.com/Qiskit/qiskit-terra/blob/9ffb2c9016cc4a6c7d525f5aa52605ab05e79a07/qiskit/pulse/schedule.py#L397-L403
This is temporary fix. I suggest to create `ParametrizedInstruction` class rather than using callable. In this way we can incorporate parameters more natively (because class can have a parameter property).

**Pull request merged**
