### PR TITLE
Cache Bit and Register __repr__ and use for __eq__

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

This commit caches the generated repr for the Bit class (and its
subtypes Qubit, Clbit, etc) and Register class at init time. Currently
when we create DAGNode objects in the dagcircuit a big portion of
the time is spent regenerating the str for the repr. However this
information is static and the string manipulation which is slow
doesn't need to be run constantly.

### Details and comments

### CODE REVIEW

**Comment by mtreinish** [comment]
The main goal of this is to speed up `DAGNode` creation (mainly in the context of `apply_operation_back`). The improvement today is small compared to the overall speed of that method. Looking at `circuit_to_dag` (which is mainly apply_operation_back) for a random 65 qubit circuit with a depth of 4096, with master today the profile looks like:

Screenshot_2020-10-21_13-13-05


While with this PR:

Screenshot_2020-10-21_13-15-12


(in both profiles the pink block is `Bit.__repr__`)

Where this comes up more is after #5267 merges, because then the `__repr__` is a more substantial portion of the time spent in `apply_operation_back()` so shrinking the time we spend in `Bit.__repr__` has a larger impact.

**Comment by mtreinish** [comment]
To continue the speed up after looking at profiles from https://github.com/Qiskit/qiskit-terra/pull/5267#issuecomment-713820785 I realized the next biggest time sync in `apply_operation_back()` was comparing bits with `Bit.__eq__` and that the cached repr we added here has all the necessary information to do that in a single string comparison instead of multiple layers of nested checks. So in https://github.com/Qiskit/qiskit-terra/pull/5272/commits/061583b1cbe685c1ef43d729fb5883bfcfc53693 I modified __eq__ to make this optimization and with that and #5267 applied it makes a noticeable impact on the speed of `apply_operation_back()`. See: https://github.com/Qiskit/qiskit-terra/pull/5267#issuecomment-713864706

**Comment by mtreinish** [comment]
I just ran profiles of the same 65 by 4096 random circuit circuit to dag conversion again, and with `__eq__` this makes a decent impact even without #5267. Without this PR the profile of `apply_operation_back()` looks like: 

Screenshot_2020-11-04_16-38-22


Then with this PR in it's current form (caching `__repr__` and using that for `__eq__`):

Screenshot_2020-11-04_16-37-37

**Comment by mtreinish** [comment]
I'm removing the stable backport tag here. I don't think the performance improvement here is really worth the risk of regression on the stable branch. It's more than I thought without #5267 but it doesn't really seem big enough to backport.

**Review by ajavadia — APPROVED** [review]

**Pull request merged**
