### PR TITLE
Skip on QE tests if QE is not configured

### LINKED ISSUE #747: Skip on QE tests if QE is not configured
@mtreinish reported:

### What is the expected enhancement?

When running the test suite locally if you do not have a QE
configuration setup you'll encounter ~40 failures during a run by
default that require this configuration. Instead of failing we should
just skip these tests if there is no config present because it can't be
expected that everyone has the QE configuration setup locally.
While there is a env variable, SKIP_ONLINE, to short circuit the whole
method and also raise a unittest skip, this is not the default for
running locally. This commit switches the bare Exception to be
unittest.SkipTest() to treat the condition as a skipped test instead
of a failure.

### PR DESCRIPTION
**Pull request by mtreinish**
Fix #747 

### Summary
When running the test suite locally if you do not have a QE
configuration setup you'll encounter ~40 failures during a run by
default that require this configuration. Instead of failing we should
just skip these tests if there is no config present because it can't be
expected that everyone has the QE configuration setup locally.
While there is a env variable, SKIP_ONLINE, to short circuit the whole
method and also raise a unittest skip, this is not the default for
running locally. This commit switches the bare Exception to be
unittest.SkipTest() to treat the condition as a skipped test instead
of a failure.

### CODE REVIEW

**Comment by ajavadia** [comment]
Thanks Matthew, and welcome!

**Comment by diego-plan9** [comment]
Can we actually debate a bit before merging, also taking into account that @1ucian0 is working on a related PR? The issue is not the implementation but the desired behaviour (partly that is why we encourage opening an issue before submitting the PR).

The initial idea was that, by default, a contributor should run the full test suite (ie. including the online tests) locally, in order to catching potential problems before reaching the public PR - and currently it is kind of implied that he should have a valid set of credentials (and he is able to opt out via the  `SKIP_ONLINE` indeed, as you noted). I feel there is some value in enforcing raising an error (in a way, it makes the contributor aware that the full test suite is not being able to be run properly), and keep the skipping explicit - might be a philosophical discussion, but it would be great to see some discussion! Any thoughts?

**Comment by ajavadia** [comment]
It seems to me that a failure should imply something is wrong with the code. In this case, the user has incomplete access to the features, so it should be skipped *for that user*. They will be able to see that the for example 40 tests were skipped.

But I do wonder what the difference between this and SKIP_ONLINE is. Should we just set SKIP_ONLINE if no credentials are found?

**Comment by mtreinish** [comment]
Right @ajavadia is describing the need here. The fundamental issue is while we have an opt-out mechanism but by default out of the box the test suite will always fail. We can't expect everyone who runs the tests or works on the repo to have QE credentials, for example I don't. All I did was clone the clean repo and ran the tests and hit ~40 failures. Skip is the right state for these tests if there is no configuration because they can't be run successfully. As @ajavadia described failure or error implies something is wrong with the code.

As for the difference between SKIP_ONLINE and this it really comes down the reason message in the logs and the nature by which it was skipped. Skipping because of missing configuration because we don't have enough information to run the tests and it tells the user in the results that we didn't run these tests because there was no QE configuration found. When you set SKIP_ONLINE it doesn't even check, and just skips the tests because the user said so, it's basically test selection just via an env variable instead of by using the test runner (although that's not easy to do with the stdlib unittest test runner).

**Comment by 1ucian0** [comment]
We are retaking the conversation about #234 and this issue should be fixed then.

I agree that the tests should pass after cloning, without the need to create a user in QX.

**Comment by delapuente** [comment]
Semantically, I agree that the correct action is to skip the tests when preconditions for testing are not satisfied. But I also agree with @diego-plan9 that it is convenient. As some of you said, perhaps the solution is to opt-in instead of opting out but I'd see a PR that solves both conveniences, for contributors and for the project.

**Comment by diego-plan9** [comment]
Labelling it `on hold`, as probably will be superseeded by #697.

**Comment by ajavadia** [comment]
I think this can be closed now that #697 is merged.

**Pull request closed without merging**
