### PR TITLE
Fix bind propagation when decomposing composite gates.

### LINKED ISSUE #2482: Decompose does not propagate bound parameters
```
>>> import qiskit as qk
>>> p = qk.circuit.Parameter('p')
>>> qc = qk.QuantumCircuit(1)
>>> qc.rx(p,0)
<qiskit.circuit.instructionset.InstructionSet object at 0x1037b3668>
>>> inst = qc.to_instruction()
>>> qc2 = qk.QuantumCircuit(1)
>>> qc2.append(inst, [0])
<qiskit.circuit.instructionset.InstructionSet object at 0x124066710>
>>> print(qc2)
        ┌─────────────┐
q_0: |0>┤ Circuit0(p) ├
        └─────────────┘
>>> print(qc2.bind_parameters({p: 0.5}))
        ┌───────────────┐
q_0: |0>┤ Circuit0(0.5) ├
        └───────────────┘
>>> print(qc2.bind_parameters({p: 0.5}).decompose())
        ┌───────┐
q_0: |0>┤ Rx(p) ├
        └───────┘
```
In the normal workflow, this isn't an issue since we decompose before we bind, but both forms should work.

### PR DESCRIPTION
**Pull request by kdk**
### Summary

Fixes #2482 and #3509 by returning a new class from the `circuit_to_{instruction,gate}` converters, allowing the converters to control how parameters are bound when `Instruction._define` is called.

### Details and comments

For background, `Instruction` objects currently have a `.definition` property, backed by a `._definition` attribute. Because we generally instantiate a large number of `Instruction` objects, populating `._definition` is deferred from initialization to a `._define` method, which is called by the `.definition` getter.

Two implications of this approach:
1. For `Instruction` sub-classes, parameters are read from `Instruction.params` only once, the first time `Instruction.definition` is accessed (#3728).
2. For user-defined `Instruction` instances, a custom `.definition` can be set, but locally overriding `._define` is difficult or not possible.

In #2482, a parameterized circuit is converted into an instruction, then bound to a set of parameters and decomposed. The `circuit_to_instruction` converter assigns a fixed `.definition` to the output `Instruction`, including parameterized instructions from the input circuit. `bind_parameters` will assign the bind values to the output `Instruction.params`, but due to #3728 , these will not be propagated into the `definition`.

The approach taken in  ccd404d is to create two new `Instruction` sub-classes, `_CircuitInstruction` and `_CircuitGate` which accept a circuit as an `__init__` argument, and override `_define` to construct a composite instruction with assigned parameter values. `_Circuit{Instruction,Gate}` do not have the standard `__init__(self, *params)` constructor signature, which is expected by e.g. `ControlledGate.inverse`.

Other possible approaches:
- Monkey-patch a custom `_define` method on to `Instruction` instances generated by the converters. This requires a deepcopy for the monkey-patched method to be preserved across copies so `Instruction.copy` would need to either always `deepcopy`, or to do so selectively for `Instruction`s generated by the converters.
- Update the base `Instruction._define` to look for a `_target_circuit` attribute or similar and implement the conversion there.
- ( 34f16da ) When binding parameters, check each `Instruction._definition` to find and bind instances of that parameter.

A fix for #2482 and #3509 is needed to unblock development work in aqua, and can be short-term, as much of the `Instruction.definition` infrastructure will be changed by #3146 .

WIP for:
 - [x] Release note
 - [x] ~`ControlledGate.inverse` expects `Instruction`s to have a constructor that accepts `*params`, which `_CircuitGate` and `_CircuitInstruction`do not. Additionally, without access to the `Instruction` instance used as the `base_gate`, its not clear how to clone or reproduce the target circuit.~ No longer an issue with 34f16da .

### CODE REVIEW

**Comment by kdk** [comment]
Alternate implementation added in 34f16da . Compared to ccd404d , avoids introducing new instruction-from-circuit classes, but requires re-walking `instr._definition` when we `bind_parameters` (so an equivalent to a `ParameterTable` would be needed for `Instruction.definition` for large definitions).

**Comment by ewinston** [comment]
This implementation keeps multiple instances of a parameter and recurses through deep circuits during binding? Appears to work. Did using a single instance with references to it seem to not work or just required too big a change?

**Comment by kdk** [comment]
> This implementation keeps multiple instances of a parameter and recurses through deep circuits during binding? Appears to work. Did using a single instance with references to it seem to not work or just required too big a change?

Keeping a single reference would've also worked, but required a larger change, across `Instruction.definition`, the converters, and the unroller.

**Comment by mtreinish** [comment]
@ewinston did @kdk answer your question? I think you should review this before we merge.

**Pull request merged**
