### PR TITLE
Fixed problem with fold=-1 in mpl drawer and added fold tests

### LINKED ISSUE #4506: circuit draw() does not show properly when you use output='mpl' and fold=-1
### Information

- **Qiskit Terra version**: 0.14.1
- **Python version**: 3.7.4
- **Operating system**: Darwin

### What is the current behavior?
For a quantum circuit, qc, when you run qc.draw(output='mpl', fold=-1) the circuit is drawn in one line but the horizontal lines and registers are gone. Works with output='text'.

### Steps to reproduce the problem
q = QuantumRegister(2, 'q')
c = ClassicalRegister(2, 'c')
qc = QuantumCircuit(q,c)

for _ in range(40):
    qc.h(q[0])
    qc.h(q[1])
qc.measure(q,c)
qc.draw(output='mpl',fold=-1)

### What is the expected behavior?
Should have proper figure

### PR DESCRIPTION
**Pull request by enavarro51**
### Summary

Fixed #4506

### Details and comments

Fixed display when fold=-1 in mpl drawer, which indicates no folding. It now displays the same as when the fold number is greater than the number of anchors. 

Added a fold test with 2 png comparison files to test fold=-1 and fold=4.

### CODE REVIEW

**Comment by 1ucian0** [comment]
MPL circuit drawer issues are piling up, since we dont have a good way to track changes on it. I'm putting this PR `on hold` (meaning "do not merge yet") until https://github.com/Qiskit/qiskit-terra/pull/4544 (or a similar solution) gets in.

**Comment by 1ucian0** [comment]
#4544 is merged... Let's add a test with the new method!

I will try helping, but fill free to do it yourself and ask me if any question.

**Comment by enavarro51** [comment]
I supplied 2 test images for this one.

**Comment by 1ucian0** [comment]
This one was covered by PR #4616.

**Pull request closed without merging**
