### PR TITLE
Add option to reverse qubit order in latex drawer

### LINKED ISSUE #767: Add option to reverse qubit order when drawing circuits
### What is the expected behavior?
Currently, qubits registers are displayed with their lower bits in the top; the flag would allow the order to be reversed.

### PR DESCRIPTION
**Pull request by mtreinish**
Fix #767

### Summary

This commit adds a new kwarg parameter to the latex drawer
reverse_qubits which gives users an option to reverse the order qubits
are displayed. Currently the bit order increases downward with the q_0
bit being displayed at the top. When the reverse_qubit option is set to
True the order is reversed and q_N is at the top and the order
decreases.

### Details and comments

Related to #693

### CODE REVIEW

**Comment by ajavadia** [comment]
Is it possible to do this for the `matplotlib_circuit_drawer` too? We want to keep the interfaces as close as possible. Because most users will call them via the wrapper method `circuit_drawer`.

**Comment by mtreinish** [comment]
@ajavadia sure it should be simple enough. I haven't looked at the matplotlib drawer in detail yet. But I'll take a look and add that on to this PR too.

**Comment by ajavadia** [comment]
Thanks. @t-imamichi and @nkanazawa1989 may be able to help.

**Comment by nkanazawa1989** [comment]
@mtreinish `matplotlib_citcuit_drawer` has a y-coordinate of each gate in dictionary format. It is very easy to change the order of it. I'll work on it.

**Comment by nkanazawa1989** [comment]
@mtreinish In your code, the option seems to reverse the bit order of qubits only. And if we assign multiple qubits, order of qubit might be reversed. These are correct spec?

https://github.com/Qiskit/qiskit-terra/pull/762/files#diff-601179d490e381950db4bf9a4fe01d93R272

**Comment by nkanazawa1989** [comment]
I modified `matplotlib_circuit_drawer` part. Also creg order is changed.

image

**Comment by delapuente** [comment]
Please, remember to file an issue before sending the PR and include “Fix #issuenumber” in the PR description to keep them linked. This helps us to keep track of the state of the library and properly prioritise the tasks. I’ve opened #767 for this.

**Comment by mtreinish** [comment]
@nkanazawa1989 yeah, the intent of the feature is to just mirror the qubit side of the circuit. (not to touch the classical bits) So what I have implemented on the latex side was all intentional. If there is more than one qregister the order of those is reversed just like the individual bits.

For example:

normal

when reversed becomes:

reverse

**Comment by rraymondhp** [comment]
@mtreinish  IMHO, the classical registers should be reversed too. They are what we actually use as keys in the histogram, and the order is from right-to-left which is nicely aligned with from bottom-to-up.

**Comment by nkanazawa1989** [comment]
@rraymondhp Thanks, I agree. Can you give us comments on register order?
@mtreinish Could you decide final spec? `matplotlib_circuit_drawer` will fit in with your update.

**Comment by ajavadia** [comment]
Yes I agree that classical bits should also be reversed.
But let's not change the order of qubit registers (put them in the order defined by user still circ(q1, q2))

**Comment by mtreinish** [comment]
@ajavadia @nkanazawa1989 @rraymondhp ok, I understand now. Let's change the name of the flag to `reverse_bits` and I'll update the function to reverse the order of the bits (both classical and qubits) but not touch the order of the registers.

**Comment by mtreinish** [comment]
Ok, the latest revision corrects the behavior of the new flag as discussed. For example:

normal

when reverse_bits is set to true becomes:

reverse

**Comment by delapuente** [comment]
@nkanazawa1989, does the current version of the `matplotlib_circuit_drawer` function support this same feature? How?

**Comment by nkanazawa1989** [comment]
@delapuente Yes. The same function has already implemented in my repo, but I need small adjustment. I will soon make new PR with referring this discussion.

**Comment by delapuente** [comment]
Oh, cool. Just make sure we use the same API. Thank you!

**Pull request merged**
