### PR TITLE
do not transpile Schedule when execute

### LINKED ISSUE #4164: Running a schedule in execute gives warning about transpiler
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
The docs (https://qiskit.org/documentation/tutorials/advanced/terra/pulse/getting_started_with_pulse.html) say that I can use the `execute` function for a schedule the same as a circuit.  However when I do I get the warning:

```
UserWarning:

Transpiling schedules is not supported yet.
```
but the job gets sent to the device.

### PR DESCRIPTION
**Pull request by 1ucian0**
Fixes #4164

When `execute` with a schedule, a warning that is not going to be transpiled arises. This PR just do not run transpile for a schedule.

### CODE REVIEW

**Comment by 1ucian0** [comment]
`on hold`. This is not the right fix indeed. I will have a look in an hour! Sorry!

**Comment by taalexander** [comment]
Why does the `Schedule` even make it to the passmanager if it is not a circuit?

**Comment by lcapelluto** [comment]
@1ucian0 how is this going?

**Comment by 1ucian0** [comment]
> Why does the Schedule even make it to the passmanager if it is not a circuit? I don't understand what the warning is attempting to convey?

I added the warning because transpile was just returning the argument without changing anything. There was a comment with the text of the warning.

This PR does not even run the transpiler for Schedule. It is ready for review @lcapelluto

**Comment by taalexander** [comment]
> This PR does not even run the transpiler for Schedule. It is ready for review @lcapelluto

This is what I was wondering, why the schedule made it to the transpiler.  Thanks for fixing this!

**Pull request merged**
