### PR TITLE
Fix Pulse channel index validation

### LINKED ISSUE #10475: Pulse's channel index validation fails
### Environment

- **Qiskit Terra version**: 0.25.0 (main)
- **Python version**: 3.9
- **Operating system**: Windows

### What is happening?

Channel index validation doesn't produce a `PulseError` when the channel is either non-integer or negative. Only when both are true.

### How can we reproduce the issue?

The following should produce a `PulseError`, but it doesn't:

```
from qiskit import pulse

pulse.DriveChannel(0.5)
pulse.DriveChannel(-1)
```

Because of [this line](https://github.com/Qiskit/qiskit-terra/blob/e55389f3f05e2d871fdea3814917c93b5c280e93/qiskit/pulse/channels.py#L124), only when the index is both not an integer *and* negative, an error is raised. This does raise a `PulseError`: 
```
pulse.DriveChannel(-1.5)
```

### What should happen?

A `PulseError` should be raised if either of the conditions are met.

### Any suggestions?

_No response_

### PR DESCRIPTION
**Pull request by TsafrirA**
### Summary
Fix a bug in the validation of Pulse channel index.

Fix #10475

### CODE REVIEW

**Review by jakelishman — COMMENTED** [review]
I think this has been around for a while now, so could you add a test and potentially a one-liner bug-fix release note?

**Review by jakelishman — APPROVED** [review]
Super, thanks!

**Comment by jakelishman** [comment]
btw, if you want your PR to autoclose an issue on merge, there's [specific words you have to use](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue), with one issue per line.  "Addresses" isn't one unfortunately, so I updated your top comment to "Fix", which is one of them.

**Comment by TsafrirA** [comment]
Thanks @jakelishman!

**Pull request merged**
