### PR TITLE
[stable] Remove LegacySwap, Remove default_pass_manager, Fix layout issues

### PR DESCRIPTION
**Pull request by ajavadia**
backport of #2672

### CODE REVIEW

**Comment by nonhermitian** [comment]
I would be happy if all got ported save for the change of default PM. The swap mapper is just a faster version of the same alg.

**Comment by mtreinish** [comment]
I guess that would be ok, since it doesn't really change the behavior of any of the default transpile calls, it'll just be faster. As long as we don't delete the LegacySwap pass from stable. Part of my concern is that someone is using LegacySwap (for better or worse) in 0.8.2 and then have it disappear from 0.8.3 which wouldn't really be a stable release.

**Comment by 1ucian0** [comment]
I'm not sure changing the default swapper is a minor change...

**Comment by ajavadia** [comment]
The fix is actually more involved here, we need to backport #2050, #2590, #2598 first before this works. I think then this has to go in the next minor release.

**Pull request closed without merging**
