### PR TITLE
Flipped qft circuit to respect qiskit's qubit index convention

### PR DESCRIPTION
**Pull request by trevordavila**
### Summary
Fixes the implementation of the quantum Fourier transform in the circuit library. 

### Details and comments
The original QFT code attempted to implement the standard QFT circuit as in the following circuit diagram (layer of swap gates at the end not shown):
qft

There were 2 issues:
1. The control and target qubits of the controlled rotations were switched. This is clear because the control qubit of the controlled rotations had a Hadamard gate applied before the controlled rotations, which is incorrect.
2. To implement this circuit in qiskit, the diagram needs to be flipped due to qiskit's convention of storing less significant digits of a binary integer in lower index qubits (i.e. the top of a circuit diagram). So first a Hadamard on the nth qubit needs to be applied, then controlled rotations of the nth qubit, and so on, followed by swap gates.

In this pull request, I've fixed these issues by implementing a flipped version of the above circuit diagram. I also changed controlled u1 gates to controlled phase gates, since u1 gates are being deprecated.

This is my first pull request on GitHub, so any feedback will be greatly appreciated. Thanks!

### CODE REVIEW

**Comment by ajavadia** [comment]
@trevordavila thanks for this contribution. I think it is a duplicate of https://github.com/Qiskit/qiskit-terra/pull/4849 however.

**Comment by trevordavila** [comment]
@ajavadia Ah you're right, sorry about that. I didn't see that pull request.

After looking at that pull request, I thin the control and target qubit of the controlled u1 gates need to be swapped. So line 260 of qft.py should be
`self.cu1(lam, k, j)`

**Comment by Cryoris** [comment]
CU1 is symmetric, swapping control and target doesn't matter 🙂

**Comment by trevordavila** [comment]
Ah right :) Thanks folks. I'll close the request.

**Pull request closed without merging**
