### PR TITLE
Paulihedral 2.3

### PR DESCRIPTION
**Pull request by XiuqiCao**

### CODE REVIEW

**Comment by jakelishman** [comment]
I think you might find it helpful to install `git` locally, and read about more about [how to make pull requests on GitHub](https://docs.github.com/en/get-started/quickstart/github-flow).  There's no need to open a new PR every time you make changes to your files.

You'll also need to [read about the procedures for contributing to Terra](https://github.com/Qiskit/qiskit-terra/blob/main/CONTRIBUTING.md) - at the moment, the code you're uploading is not really suitable, and for a feature like this, it would have been better to open an issue to discuss implementation before beginning.  It might be better to begin by trying to make this a package in the [Qiskit Ecosystem](https://qiskit.org/ecosystem/) first, which has far less stringent requirements than Terra, and then if it proves useful to other people, we could consider working with you to polish it up for Terra.

**Comment by gushuli** [comment]
> 

Hi Jake,

Thank you for your suggestions and the materials you provided. I am sorry for opening multiple PRs. We will try to follow them and stick to this PR until everything is done. For the code organization and implementation, we will discuss with @ajavadia to plan the code polishing up.

Best
Gushu

**Comment by 1ucian0** [comment]
Hi @XiuqiCao, are you still working on this?

**Comment by javabster** [comment]
closing this PR as contributor is unresponsive, we can reopen at a later date if they return 😃

**Pull request closed without merging**
