### PR TITLE
Add suport for latex drawing simulator instruction

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

This commit adds support for drawing simulator instructions to the latex
circuit visualization for drawing simulator instructions. These are
visualized as barriers on the circuit. Longer term we will add an
annotation to show which slot is used (or in the case of noise whether
it's switched on or off), but for right now this does not support adding
the annotations, that will be added im a future PR. This commit just
adds the initial support.

### CODE REVIEW

**Comment by mtreinish** [comment]
Putting this on hold for now, it looks like there is a bug if there is a simulator instruction right before a measure that causes the drawer to crash.

**Comment by mtreinish** [comment]
@jaygambetta @ajavadia so the reason this is still a WIP is that I haven't had a chance to figure out a good latex pattern for handling the annotations. I find something that works somewhere, but breaks in other conditions. If we're ok just drawing a barrier without the annotation this commit is much simpler and I can respin it today.

**Comment by 1ucian0** [comment]
Let's do this for other visualizers.

**Comment by jaygambetta** [comment]
Is this ready

**Comment by mtreinish** [comment]
Yes, this should be good to go. Once this lands I will open an issue to add annotations to the simulator instructions to track that effort as a future feature. But for right now it will draw the barrier line for `save`, `load`, `snapshot`, and `noise`

**Pull request merged**
