### PR TITLE
Merge condition check codes in compose() method

### PR DESCRIPTION
**Pull request by QianJianhua1**
### Summary
Merge condition check codes in compose() method.

### Details and comments
Merge the two consecutive "if front" check codes into one.

### CODE REVIEW

**Review by kdk — COMMENTED** [review]
Thanks @QianJianhua1 , I agree these two `if` statements could be merged (though I would expect the performance improvement in doing so to be small). However, to me, I find the updated version less readable than the original (having this as two conditions did separate out the "merge `_data` lists" phase from the "update `ParameterTable`" phase, and the comment `# just append new parameters` is now misplaced). Is there a way the readability of the original could be preserved?

**Comment by QianJianhua1** [comment]
Thank you @kdk  Partly agree with you. But if you think of "update _data" and "update parameter" as one continuous process, you might think otherwise. In other words, after _data is updated, parameter must be updated.
if front is true, we just consider how to deal with them(contain _data and parameter), Otherwise just append the new part.
I have changed the comments, please review it again.

**Review by javabster — APPROVED** [review]
This lgtm, thanks @QianJianhua1!

**Comment by jakelishman** [comment]
On this one I agree with @QianJianhua1 about the newer readability: in the previous version with its split if statements, it wasn't super clear why you needed to invalidate the parameter table in the second `if front`, unless you also saw the first `if front`.  Putting them together, it's very clear to me - we have to invalidate it because data has been inserted before, so _all_ previous indices are now invalid.

**Review by kdk — APPROVED** [review]
Thanks for the updates @QianJianhua1 , this LGTM!

**Pull request merged**
