### PR TITLE
Add support for displaying controlled gates to latex

### LINKED ISSUE #3764: Latex drawer does not support controlled gates
### Information

- **Qiskit Terra version**: master
- **Python version**: 3.7
- **Operating system**: MacOS

### What is the current behavior?

The latex drawer does not print controlled gates correctly.

### Steps to reproduce the problem

```
qr = QuantumRegister(3, 'q')
circuit = QuantumCircuit(qr)
circuit.append(HGate().control(2), [qr[0], qr[1], qr[2]])
circuit.draw('latex')
```
image

### What is the expected behavior?

Something along the text drawer:
```
q_0: |0>──■──
          │  
q_1: |0>──■──
        ┌─┴─┐
q_2: |0>┤ H ├
        └───┘
```

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

This commit adds support for drawing controlled gates to the latex
drawer. It handles an arbitrary number of controls on a gate and will
visualize them as controls instead of as a custom multiqubit gate.

### Details and comments

Fixes #3764

### CODE REVIEW

**Comment by mtreinish** [comment]
There is a bug I'm not sure how we should handle in the most recent revision if a control qubit is in the middle of a multiqubit gate. For example: `circuit.append(RXXGate(3.14).control(1), [qr[1], qr[2], qr[0]])` My thinking is in this case just treat it as a custom multiqubit gate and don't draw the controls. Does anyone have any other thoughts on this?

**Comment by ajavadia** [comment]
In the text drawer version that was merged today Luciano puts a control on the side of the box which I think is a reasonable solution.

**Comment by mtreinish** [comment]
I see I just ran it locally:

```
             ┌────────────┐
q_0: |0>──■──┤1           ├
          │  │            │
q_1: |0>──■──■  Rxx(3.14) ├
        ┌─┴─┐│            │
q_2: |0>┤ H ├┤0           ├
        └───┘└────────────┘
```

Unfortunately, that will be hard to do with the latex drawer. The way it builds the matrix of elements I think it'll be hard to have it's hard to add a control symbol overlapping the multiqubit box for the gate like that. (it's for a similar reason we don't have the annotations for the wires). I think the best I can do for the short term is have a big box covering all the qubits.

**Comment by mtreinish** [comment]
Ok I've updated this to handle the overlapping control case, with the latest commit running:

```
import qiskit as qk
from qiskit.extensions import *

qr = qk.QuantumRegister(3)
cr = qk.ClassicalRegister(3)
circ = qk.QuantumCircuit(qr, cr)
circ.append(RXXGate(3.14).control(1), [qr[1], qr[2], qr[0]])
circ.append(RXXGate(3.14).control(1), [qr[0], qr[1], qr[2]])
circ.append(RXXGate(3.14).control(1), [qr[0], qr[2], qr[1]])
circ.append(RXXGate(3.14).control(1), [qr[1], qr[0], qr[2]])
circ.append(RXXGate(3.14).control(1), [qr[1], qr[2], qr[0]])
circ.append(RXXGate(3.14).control(1), [qr[2], qr[0], qr[1]])
circ.append(RXXGate(3.14).control(1), [qr[2], qr[1], qr[0]])

circ.draw(output='latex')
```

yields:

latex

**Comment by 1ucian0** [comment]
The following example raises an error:
```python
ghz_circuit = QuantumCircuit(3, name='ghz')
ghz_circuit.h(0)
ghz_circuit.cx(0, 1)
ghz_circuit.cx(1, 2)
ghz = ghz_circuit.to_gate()
cghz = ghz.control(1)
circuit = QuantumCircuit(4)
circuit.append(cghz, [1, 0, 2, 3])
circuit.draw('latex')
```
```
qiskit/visualization/latex.py in _build_latex_array(self, aliases)
    378                     qarglist = op.qargs
    379                     name = generate_latex_label(
--> 380                         op.op.base_gate_name.upper()).replace(" ", "\\,")
    381                     pos_array = []
    382                     num_ctrl_qubits = op.op.num_ctrl_qubits

AttributeError: 'ControlledGate' object has no attribute 'base_gate_name'
```

**Comment by 1ucian0** [comment]
It seems same as https://github.com/Qiskit/qiskit-terra/pull/3779#issuecomment-582603695

**Comment by mtreinish** [comment]
@1ucian0 we were racing here, see the 2 recent commits I pushed a few minutes ago, https://github.com/Qiskit/qiskit-terra/pull/3777/commits/379cfef383ce0e4b1f825230f60765ddfb0f300c fixed it

**Pull request merged**
