### PR TITLE
revert computing matrix for trivial matrices

### PR DESCRIPTION
**Pull request by ewinston**
### Summary
Revert changes  to `to_matrix` for some standard gates which computed the matrix instead of using a pre-written one causing somewhat degraded performance.

### CODE REVIEW

**Comment by ajavadia** [comment]
what is the context here, was there a performance issue?

**Comment by ewinston** [comment]
@ajavadia Yes this is the one Matthew referred to in the last meeting;

https://qiskit.github.io/qiskit/#passes.PassBenchmarks.time_commutation_analysis?machine=dedicated-benchmarking-softlayer-baremetal&os=Linux%204.15.0-46-generic&ram=16GB&p-n_qubits=14&p-depth=1024&commits=6a1e8b12

**Comment by ajavadia** [comment]
Ok. Are `h`, `swap` and `y` the only relevant gates for this?

**Comment by ewinston** [comment]
@ajavadia These were the ones related to the performance issue. I think in the subsequent pr when I validate to_matrix with docs can apply to other gates; there are several others.

**Pull request merged**
