### PR TITLE
Fix Errors in Primitives

### PR DESCRIPTION
**Pull request by ikkoham**
### Summary

This PR changes QiskitError to ValueError.

### CODE REVIEW

**Comment by ikkoham** [comment]
@woodsp-ibm I think you reported this issue. Could you review this PR?

**Review by t-imamichi — APPROVED** [review]
LGTM

**Comment by woodsp-ibm** [comment]
It seems that there are some fidelity tests for mismatched left and right circuits that are testing the sampler usage by fidelity to presumably ensure its catching the expected error when it calls run. https://github.com/Qiskit/qiskit-terra/blob/4ac8b24af1cf6f99a418b5f118c29661f89a2b2c/test/python/algorithms/state_fidelities/test_compute_uncompute.py#L141 While the job.result() call is in a try catch block where it re-raises the exception, the call run, like the gradients is not, so this change affected the test. It seems more like its testing the sampler than the fidelity as such with this error checking though - bit since the fidelity has none itself on the run and relies on this I guess it checks the overall behavior is as expected. @ElePT FYI

**Comment by ElePT** [comment]
> It seems that there are some fidelity tests for mismatched left and right circuits that are testing the sampler usage by fidelity to presumably ensure its catching the expected error when it calls run.
> 
> https://github.com/Qiskit/qiskit-terra/blob/4ac8b24af1cf6f99a418b5f118c29661f89a2b2c/test/python/algorithms/state_fidelities/test_compute_uncompute.py#L141
> 
> While the job.result() call is in a try catch block where it re-raises the exception, the call run, like the gradients is not, so this change affected the test. It seems more like its testing the sampler than the fidelity as such with this error checking though - bit since the fidelity has none itself on the run and relies on this I guess it checks the overall behavior is as expected. @ElePT FYI

I see. Given that as Steve mentioned, these errors are actually handled by the `Sampler` and not `ComputeUncompute`, I can remove this test from the fidelity module. I see 2 options:
1. I have an open PR addressing a few bug fixes in the fidelity classes #8755, it's a bit messy but I could include the fix there. 
2. If there is no rush to include this PR in the next release, I could open a quick bug-fix PR for this purpose. 

Whichever you prefer :)

**Comment by ikkoham** [comment]
TBH, I don't have a strong opinion to this issue. We don't have any major rules about Qiskit errors...
Since this is an API breaking, I would like to change it before next release.

**Comment by ElePT** [comment]
Well, you already fixed the CI but decided to remove the test anyway to prevent future situations like this.

**Review by woodsp-ibm — APPROVED** [review]

**Review by t-imamichi — APPROVED** [review]

**Pull request merged**
