### PR TITLE
Reduce custom gate width in MPL drawer

### LINKED ISSUE #3641: Drawing initialize disordered in mpl drawer
### Information

- **Qiskit Terra version**: 0.12.0.dev0+6b6170a
- **Python version**: 3.6
- **Operating system**: Ubuntu 18.04

### What is the current behavior?
The box of 'initialize' is disordered. It gets outside of the circuit and overlaps with other gates.

initialize-error

### Steps to reproduce the problem

```from qiskit import *
from math import pi, sqrt
import numpy as np

vec = np.array([sqrt(1/2), 0, 0, sqrt(1/2)])

qc = QuantumCircuit(2)
qc.initialize(vec, [0,1])
qc.u3(0.12,pi/2,pi/4,0)
qc.draw(output="mpl")
```

### PR DESCRIPTION
**Pull request by NuoWenLei**
### Summary

fixes #3641 

### Details and comments

changed layer width ratio with box_width of all custom multiqubit gates

### CODE REVIEW

**Comment by ajavadia** [comment]
It seems the box should be dynamically sized otherwise there will always be some custom box that shows poorly. For example here what happens if you do an 
```python
qc = QuantumCircuit(4)
qc.initialize([1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], [0, 1, 2, 3])
qc.draw('mpl')
```

**Comment by mtreinish** [comment]
Right I agree with @ajavadia adjusting these spacing parameters is quite finicky why is this 1 now instead of 2.5? Changing that will likely throw off all the spacing for other gates, especially ones with long names and not long parameter lists.

The real bug here is actually in how the dynamic spacing is done is not factoring into account the different font size for the parameters list. Using @ajavadia's example there are 48 characters in the output vector that will be displayed as the subtext. This gets used here: https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/visualization/matplotlib.py#L193 assuming the width in the output visualization are the same size between text and subtext despite subtext being a smaller font size. This is why the box stretches too far we need to properly scale that value based on fontsize and that should fix #3641)

**Comment by NuoWenLei** [comment]
So perhaps there should be a scale ratio multiplied to the subtext to balance the font difference?

**Comment by ajavadia** [comment]
I actually think long parameters should not be displayed. Like for my example this can cause ridiculously long boxes which is not really useful as a visualization tool, so I'd just print the name there. So I would set a cutoff for this.

As for pixel size, I think that's going a bit too far. It's true that characters are different widths but if you just choose some average size it should work for most sane cases. Really what we want is not a perfect box, but something that mostly works so you probably have to play with some parameters. 

Once you're done can you please post a circuit diagram here with some standard gates, plus `initialize` and `diagonal` over 2, 4, 6 qubits?

**Comment by 1ucian0** [comment]
Hi @NuoWenLei 

Still working on this?

**Comment by 1ucian0** [comment]
MPL circuit drawer issues are piling up, since we dont have a good way to track changes on it. I'm putting this PR `on hold` (meaning "do not merge yet") until https://github.com/Qiskit/qiskit-terra/pull/4544 (or a similar solution) gets in.

**Comment by NuoWenLei** [comment]
Sorry, I was not working on this recently. I will work on this and will reach out once I've fixed the issue.

**Comment by NuoWenLei** [comment]
Sorry, I thought I would have time to work on this during summer break, but I am unable to continue working on this issue. If someone else wants to work on fixing this, I suggest looking at the _custom_qubit_gates function under visualization/matplotlib.py

**Comment by 1ucian0** [comment]
#4544 is merged... Let's add a test with the new method!

I will try helping, but fill free to do it yourself and ask me if any question.

**Comment by 1ucian0** [comment]
This PR fixes a closed issue. Therefore, I'm closing this PR too. If you still think this PR is solving other issues or it improves the MPL drawer, please reopen.

Thanks!

**Pull request closed without merging**
