### PR TITLE
cregbundle might be impossible sometimes

### LINKED ISSUE #4320: text drawer cregbundle bug when instructions with classical wires
```python
qr2 = QuantumRegister(2, 'qr')
cr2 = ClassicalRegister(2, 'cr')
inst = QuantumCircuit(qr2, cr2, name='name').to_instruction()
circuit = QuantumCircuit(qr2, cr2)
circuit.append(inst, qr2[:], cr2[:])
circuit.draw(cregbundle=False)
```
```
      ┌───────┐
qr_0: ┤0      ├
      │       │
qr_1: ┤1      ├
      │  name │
cr_0: ╡0      ╞
      │       │
cr_1: ╡1      ╞
      └───────┘
```
but
```python
circuit.draw(cregbundle=True)
```
```
ValueError: max() arg is an empty sequence
```

### PR DESCRIPTION
**Pull request by 1ucian0**
Fixes #4320
There are some cases where an instruction needs to point to individual classical wires.
```python
qr2 = QuantumRegister(2, 'qr')
cr2 = ClassicalRegister(2, 'cr')
inst = QuantumCircuit(qr2, cr2, name='name').to_instruction()
circuit = QuantumCircuit(qr2, cr2)
circuit.append(inst, qr2[:], cr2[:])
circuit.draw()
```
```
      ┌───────┐
qr_0: ┤0      ├
      │       │
qr_1: ┤1      ├
      │  name │
cr_0: ╡0      ╞
      │       │
cr_1: ╡1      ╞
      └───────┘
```
The option cregbundle cannot handle this situation I think.

This PR captures when these situations, raise a warning, and disables the option. 
disable cregbundle automatically when an instruction needs to point to individual classical wires

### CODE REVIEW

**Comment by ajavadia** [comment]
this is a pretty esoteric case so i don't think it's critical for this release given the CI bottleneck

**Comment by 1ucian0** [comment]
Sure, specially now that #4321 is merged.

**Comment by ajavadia** [comment]
Can we set the cregbundle to True by default now?

**Comment by 1ucian0** [comment]
> Can we set the cregbundle to True by default now?

Done in https://github.com/Qiskit/qiskit-terra/pull/4595

**Pull request merged**
