### PR TITLE
Faster Paulis to Matrix method

### PR DESCRIPTION
**Pull request by yotamvakninibm**
### Summary

Faster Paulis to Matrix calculation using bit-wise operations. Since we are only dealing with (2x2) Pauli matrices, we can utilize some relations between their different representations.

### Details and comments

The most important relation is, that if a Pauli matrix has a value at (x,y) [Where x,y are positions in a 2x2 matrix], then the same matrix also has a value at (1,1)^(x,y) where [^] is the xor operator. For example, for a X gate, we have values at (1,0) and at (1,1)^(1,0)=(0,1). Taking into account the Kronecker product, we can use this relationship to calculate the spmatrix faster.

A Pauli-Product matrix has values in each column, and the corresponding row is just the result of converting the series of X gates to a binary number (xs), and taking row=column^xs (this is again the xor operator). A similar calculation finds the appropriate phase. 

My tests showed this runs, for up to 10 Qubit Hamiltonians, about 4 times faster.

### CODE REVIEW

**Comment by yehuda-naveh** [comment]
Hi @yotamvakninibm , as this shows some substantial runtime improvement on possibly important problems, can you open an issue which shows some explicit results / graphs so we know exactly what problems it improves? If most problems are Aqua/VQE-like, I think best to open the issue in Aqua

**Comment by yotamvakninibm** [comment]
Sure, I'll do it.

**Comment by yehuda-naveh** [comment]
@yotamvakninibm I didn't mean for you to close... I think the PR is in place, just need in addition an exhibition/discussion of the runtime improvement results - see where it's relevant etc.

**Comment by yotamvakninibm** [comment]
Opened an Issue in Aqua:
https://github.com/Qiskit/qiskit-aqua/issues/636

**Comment by jaygambetta** [comment]
this LGTM.

**Pull request merged**
