### PR TITLE
Remove ParametrizedSchedule

### PR DESCRIPTION
**Pull request by nkanazawa1989**
### Summary

This PR removes deprecated `ParametrizedSchedule`. This has been deprecated in 0.17.0 with #5358 and seems no official tutorial has dependency on it.

### CODE REVIEW

**Comment by nkanazawa1989** [comment]
The parametrized schedule dependency has been removed from ignis. This is ready to go in (given ignis release is faster than terra).

**Comment by jakelishman** [comment]
We're still on hold in Terra until a new version of Ignis is actually released, but once that happens, we'll be good to go here.  We should be able to align things so that this happens either before, or in conjunction with, Terra 0.19.

Just for linking purposes: downstream use was removed in Qiskit/qiskit-ignis#592.

**Review by jakelishman — DISMISSED** [review]

**Comment by mtreinish** [comment]
Just a heads up the ignis release is blocked on terra 0.19.0 because ignis 0.6.0 will start emitting deprecation warnings (which we can't do until #6867 merges and is released).

**Comment by jakelishman** [comment]
@mtreinish: can we align to get Terra 0.19 and Ignis 0.6 released at the same time?

**Comment by jakelishman** [comment]
I don't think there's any rush to get this in for 0.19 - it's just a removal of deprecated functionality, after all.  That's fair - I hadn't considered the tutorials' CI in managing the warnings before release.

**Comment by nkanazawa1989** [comment]
I think this PR can be merged now.

**Review by jakelishman — APPROVED** [review]

**Pull request merged**
