### PR TITLE
Remove deprecated interactive visualizations

### PR DESCRIPTION
**Pull request by 1ucian0**
The PR https://github.com/Qiskit/qiskit-terra/pull/4438 (July 2020) deprecated interactive visualizations in `qiskit/visualization/interactive/`. This was released in Terra 0.15.1 (August 2020). Time to remove them.

### CODE REVIEW

**Review by kdk — COMMENTED** [review]
Looks good. There's a tutorial that needs to be updated first: https://dev.azure.com/qiskit-ci/qiskit-terra/_build/results?buildId=25235&view=logs&j=47acf835-66bb-5b0f-07e4-6f53ffe80e20&t=9f7ed58b-d163-5f95-b1ee-84b468b7577e&l=48

**Comment by 1ucian0** [comment]
@kdk ,  Qiskit/qiskit-tutorials#1142 got merged. This one should be good to go

**Review by mtreinish — COMMENTED** [review]
Code-wise this LGTM, I'm a bit upset you beat me to it I was looking forward to finally removing these, but honestly forgot about it until I saw the PR. But before we merge can you add an upgrade release note saying that we removed these deprecated functions.

**Comment by 1ucian0** [comment]
release notes in 0e0abcc

**Review by kdk — APPROVED** [review]

**Pull request merged**
