### PR TITLE
Visualizers print physical qubits as integers

### LINKED ISSUE #3462: Impossible to understand Q-register labels in transpiled circuits
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
It is impossible to tell what the labeling means for qubits in a transpiled circuit:

Screen Shot 2019-11-13 at 4 54 59 AM

I understand that it is supposed to show the mapping, but anyone else coming across this may not know that.  And it is unclear what term goes with what.  Does the bracket label mean physical or virtual?  Why do they have the same labels?

The figures need to be drawn in such a way as to make this obvious to anyone coming across the plot.  This also needs to be documented somewhere, e.g. an example.

### PR DESCRIPTION
**Pull request by 1ucian0**
Fixes #3462 

In this PR, the visualizers are printing physical qubits (when the layout is available) as integers. This removes the ambiguity in their meaning.

Screen Shot 2019-12-31 at 7 21 54 AM
Screen Shot 2019-12-31 at 7 23 05 AM
Screen Shot 2019-12-31 at 7 23 39 AM

### CODE REVIEW

**Comment by ajavadia** [comment]
did you want to put an arrow `->` to signify mapping? i see that's what the issue says. i don't care either way

**Comment by 1ucian0** [comment]
I thought it might take too much space.
Screen Shot 2019-12-31 at 7 29 56 AM
Screen Shot 2019-12-31 at 7 30 35 AM
Screen Shot 2019-12-31 at 7 30 53 AM

Any opinion @nonhermitian ?

**Comment by nonhermitian** [comment]
The arrow makes it explicit, so in favor of that.

**Comment by ajavadia** [comment]
The mpl seems to have extra parenthesis

**Comment by 1ucian0** [comment]
> The mpl seems to have extra parenthesis

Fixed in https://github.com/Qiskit/qiskit-terra/pull/3663/commits/948a6e87e0513e21e2cd6e3efc888f4abaa2463c

**Comment by 1ucian0** [comment]
> The arrow makes it explicit, so in favor of that.

Arrows implemented!

**Comment by 1ucian0** [comment]
In https://github.com/Qiskit/qiskit-terra/pull/3663/commits/2d8231d58c33f2a2f7aa4172b2248f187a9c3e87 i'm adding the fix from https://github.com/Qiskit/qiskit-terra/pull/3590 because affects the same line and that PR is unmergable.

**Pull request merged**
