### PR TITLE
Fixes decompose/unroller bug

### PR DESCRIPTION
**Pull request by faisaldebouni**
### Summary
Fixes an issue with unroller/decompose where registers are mismapped if a gate is defined using only one operation.

example:
```
qc = QuantumCircuit(2)
qc.cx(1, 0)
qc2 = QuantumCircuit(2)
qc2.append(qc.to_gate(),[0,1])
qc2.decompose().draw()

outputs:
q_0: ──■──
     ┌─┴─┐
q_1: ┤ X ├
     └───┘
```
 The registers would be correctly mapped if a gate had more than one operation
example:
```
qc = QuantumCircuit(2)
qc.cx(1, 0)
qc.cx(1, 0)
qc2 = QuantumCircuit(2)
qc2.append(qc.to_gate(),[0,1])
qc2.decompose().draw()

outputs:
     ┌───┐┌───┐
q_0: ┤ X ├┤ X ├
     └─┬─┘└─┬─┘
q_1: ──■────■──
```
Similar output will happen when using Unroller.
This PR will update qregs order according to gate definition.

### Details and comments
During unrolling/decomposing, if a gate definition was one operation, the node's operation would be simply substituted using `DAGCircuit.substitute_node()`. This neglects to consider how the operation is applied since this function will infer qregs from the node to be replaced.

This PR:
1- Extends `DAGCircuit.substitute_node()` to allow for remapping of wires by passing an optional qargs parameter. If not passed this function will behave just like before.

2- Figure out the correct qargs order to use when substituting nodes in both Unroller and Decompose

-  In Decompose, this done by comparing operation qargs with the definition circuit qregs.
-  In Unroller, since it unrolls gates recursively, at each recursion the order of qargs is updated and the final order does reflect the successive unrolling.

### CODE REVIEW

**Comment by ajavadia** [comment]
@faisaldebouni nice catch. can you please rebase the branch

**Review by kdk — COMMENTED** [review]
Thanks @faisaldebouni , this is a good catch!

There's a potential problem with allowing `qargs` in `DAGCircuit.substute_node` in that, in general, `substitute_node` will not re-wire the replaced node to use the updated `qargs` (thus the need for the `_check_wiremap_validity` call before `substitute_node`). This makes the `DAGCircuit` API inconsistent in that it exposes a way for users to generate an invalid DAG.

Can this logic be moved inside the `substitute_node` function (or alternately, can the `if len(rule) == 1 and len(node.qargs) ....` check be updated to find this case and fallback to `substitute_node_with_dag`)?

Also, we should make sure that other existing callers of `subtitute_node` (`BasisTranslator` and `Optimize1qGates` at the moment) are similarly updated.

**Comment by 1ucian0** [comment]
In #5225 I'm suggesting an alternative solution that does not modify the DAGCircuit API. I'm reusing the tests from here.

**Comment by 1ucian0** [comment]
Closing in favor of https://github.com/Qiskit/qiskit-terra/pull/5225

Thanks!

**Pull request closed without merging**
