### PR TITLE
Import commonly used visualizations by default

### PR DESCRIPTION
**Pull request by nonhermitian**
### Summary
From an usability point of view, it should be easier to use the `circuit_drawer` and `plot_histogram` functions.  Especially given that they are used in the very first intro notebook.

### Details and comments
This PR makes the `circuit_drawer` and `plot_histogram` functions available at import.

### CODE REVIEW

**Comment by ajavadia** [comment]
should this be done for `plot_histogram` as well?

**Comment by nonhermitian** [comment]
Sure.  It is in the most basic tutorial.

**Comment by nonhermitian** [comment]
I had to wrap the imports in a try because our travis builds do not build Python correctly for matplotlib osx backend.

**Comment by nonhermitian** [comment]
@ajavadia please take a look

**Comment by ajavadia** [comment]
Looks good to me. Don't know if it's something that merits a changelog.

**Pull request merged**
