### PR TITLE
Fix start time updates in ConstrainedReschedule pass

### PR DESCRIPTION
**Pull request by alexanderivrii**
### Summary

In #10051 the `ConstraintReschedule` transpiler pass was updated to remove recursion, however it changed (in a very subtle way_ how node start times were updated. This PR fixes makes sure that node start times get updated in the exactly same way as before.

### Details and comments

See #10051 for details.

### CODE REVIEW

**Review by mtreinish — APPROVED** [review]

**Comment by mtreinish** [comment]
LGTM, thanks for catching and fixing this for the comments discussing the need for this fix see: https://github.com/Qiskit/qiskit-terra/pull/10051#issuecomment-1534087482

**Comment by mtreinish** [comment]
I've pushed this back to 0.24.1, I think we still need to do some more testing here and I don't want to block the release on this until we're sure this is correct. Although for 0.24.1 we might just want to rewrite the internals of the pass to be more efficient (which is risky from a backport potential the runtime performance of the pass makes it very difficult to use in practice).

**Review by kdk — COMMENTED** [review]
Is there somewhere in `test_instruction_alignments.py` (or elsewhere) that we should add a test for this? Would it be worthwhile to check the output circuit's `.op_start_times`?

**Comment by mtreinish** [comment]
I think with #10077 we have a path to testing this. It was prohibitively slow without that. But I think having a test like this maybe with a few different alignment values that validates the output scheduled circuit is properly aligned would have a lot of value moving forward.

That being said I think this PR has been superseded by #10077 so maybe we should open a separate one to expand the testing.

**Comment by mtreinish** [comment]
Confirmed with @alexanderivrii that this isn't needed anymore and I'm going to close this. I still think it might be worth adding additional test coverage like what I used to test the performance here. But we can do that in a different PR.

**Pull request closed without merging**
