### PR TITLE
Revert the addition of the bit classes

### LINKED ISSUE #2496: Deprecating isinstance(qr[0], tuple) #2474 causes major performance regression
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
This has caused major performance regressions as discussed in #2474.

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

This commit reverts #2414 and #2474 to undo the introduction of a new Bit, Qubit, and Clbit class. These cause a ton of backwards compatibility headaches since it changes what was essentially a key interface for circuits. While a lot of backwards compat shims were added to try and minimize the impact of the breakage there were situations where this was exceedingly difficult to do in a graceful manner. For example see #2474 which went to a lot of effort to ensure we could treat the new classes as a tuple in `isinstance()` and other type checks expecting a tuple. However, that caused a very large performance regression.

Since there doesn't seem to be a significant benefit gained from these new classes (I think the argument was it's a cleaner interface, but personally I didn't see an issue with the tuple) this PR just reverts these changes in the interest of preserving backwards compatibility and the previous level of performance.

### Details and comments

Fixes #2496

### CODE REVIEW

**Comment by 1ucian0** [comment]
I think #2414 should not be reversed, but just #2474. We should explore alternatives to #2474.

**Comment by 1ucian0** [comment]
It seems that the penalizations happens with legacy `isinstance` call:
```
start = time()
isinstance(qr[0], tuple)
print(time()-start)

start = time()
isinstance(qr[0], Qubit)
print(time()-start)
```
```
0.22604894638061523
1.7881393432617188e-05
```

**Comment by mtreinish** [comment]
> 0.22604894638061523
> 1.7881393432617188e-05

So `isintance()` is ~12642x slower if you don't update your code? I don't view that as a viable solution for backwards compat. But, even ignoring that, you also didn't check the performance of anything else that access `__class__`. For example the issue that @nonhermitian initially reported about this: #2489 is about unit tests which as far as I can tell never call `isinstance()` (I might have missed it while tracing through the code).

> 
> We should found those legacy calls and update them. If third-parties are having performance issues, they should update too.

Right, that's why I view #2414 (and it's follow-on PRs) as a breaking change that's not backwards compatible. We're forcing our users (both other qiskit elements and anyone else) to update their code or take a huge performance regression. That's not a compatibility story at all and why I proposed the revert. Switching from a tuple seems quite invasive as it's used a lot of different places currently. It's how we've interfaced with individual all over the place and it's been the interface for a long time. IMHO the benefits of switching to a custom class haven't been made clear enough as to why it justifies breaking all the users who are using tuples today.

**Comment by nonhermitian** [comment]
Indeed, those tests run twice as close once the PR in question was merged. Note too that aqua is seeing 6x slow downs on some of their stuff.

**Comment by jaygambetta** [comment]
I tend to Agree with @mtreinish here. 

For me can you remind me why we need a qubit operator. As if the use cases out way the backward compatibility we should discuss and then make it clear that old way is not the way forward.

**Comment by ajavadia** [comment]
The reasons for going to Qubit/Clbit classes were:
- it cleans up the code (checking tuple instances 100s of times was very ugly)
- it gives precedence to qubits rather than registers (now registers are collections of qubits, rather than qubits always being subparts of a register), which allows you to write register-free circuits

It depends on whether we see (QuantumRegister, int) tuples as having been a public API. To me they were not -- people may have used them, but for example this does not appear in any of our tutorials. The only thing we advertise is `qr[0]`, which **internally** gets expanded to the tuple `(qr, 0)`. 

The current method of deprecating clearly does not work. So if think this should be backward compatible, we just revert both PRs, and probably never do it (as I don't see an easy way to deprecate this). Or (as I do) think that this was not a public/committed functionality and we simply require people who used it to update.

As an aside, can we check that #2414 itself did not introduce performance issues?

**Comment by nonhermitian** [comment]
Register int pairs were in fact part of the specifying of layouts used up until the latest release.

**Comment by nonhermitian** [comment]
Also, #2474 is the performance regression about (54% slower unit tests overall).  #2414 does not appear to appreciably change anything.

**Comment by ajavadia** [comment]
Ok so we should revert.

**Comment by ajavadia** [comment]
> Also, #2474 is the performance regression about (54% slower unit tests overall). #2414 does not appear to appreciably change anything.

I don't think so. You are referring to the old ("qr", 0) layouts, those were (**register name**, int) tuples and they have been deprecated for a while. The fact that `(qr, 0)` works does not mean it is the right API to use (`qr[0]` is the right API).

**Comment by hushaohan** [comment]
https://github.com/Qiskit/qiskit-terra/pull/2414 makes things run roughly 10% slower as far as a few Aqua tests go, just fyi

**Comment by mtreinish** [comment]
Adding more info on the performance impact of these new classes now that #2474 has been reverted it's much easier to see the performance impact of just the new classes. Just #2414 introduces an almost 2x performance regression to the benchmark suite: http://169.61.88.206/#regressions?sort=3&dir=desc (you can see it as any row there with the sha1 79c44e56 ) Between this and the backwards compat concerns I still feel that a full revert is the correct path forward here.

**Comment by nonhermitian** [comment]
That is a big hit for something that is not strictly necessary. I think it is best to run the profiler on routines to see exactly where these new classes are limiting performance. If it is not something that can be easily fixed then I would agree above reverting.

**Comment by kdk** [comment]
Closing this following last week's discussion. The consensus was to leave #2414 in place and address the performance impact in-place.

**Pull request closed without merging**
