### PR TITLE
[RFC] Use a multiple dispatch library

### PR DESCRIPTION
**Pull request by jlapeyre**
This PR refactors some code using multiple dispatch. This is an experiment in applying multiple dispatch in
various situations. The experiments are mostly spread sparsely across the repo.

This PR requires the *master* branch of [plum-dispatch](https://github.com/wesselb/plum). You can get this by cloning
plum-dispatch and doing, for example in a virtual env,  `pip install -e .`.

### Advantages/Motivation

* disentangles forests of  `isinstance` conditionals, making the logic more clear.
* Remove type-checking boilerplate. A method error is thrown if no matching method exists. For example
```python
        if not isinstance(scalar, (int, float, complex, ParameterExpression)):
            raise ValueError('Operators can only be scalar multiplied by float or complex, not '
```
* Especially useful with mathematical operators. This is by far the [heaviest use case in Julia](https://en.wikipedia.org/wiki/Multiple_dispatch#Use_in_practice). This is difficult in python because operators must be class methods that privilege one operand. A workaround is to use function calls rather than infix operators.
    * Or, one could have `__mul__` and `__rmul__` for several classes all call a function (not method) `multiply` which supports multiple dispatch.
   
 MD with operators can greatly increase the composabilty of the classes. This works in Julia in concert with a parametric type system. It may also give some similar benefit in qiskit (a python project), but it would probably require larger scale design changes, or development. 

* types representing lists and tuples of homogeneous type simplify logic. An example (not in this PR) is
https://github.com/Qiskit/qiskit-terra/blob/10a1c907f3281b1f9b451c9c81d5f05b24101d9f/qiskit/opflow/gradients/circuit_gradients/lin_comb.py#L142-L144

    is replaced by something like
```python
def func(params: {tuple, plum.List(tuple)}):
```
* Currently used mostly *within* classes in an asymmetric situation. I.e. with gradients the class is doing something to the argument. A bigger advantage is gained when you have an operation between two objects and it is not clear two which class the method should belong. (Explain why: it's not just that you don't have to make this decision; it affords more flexibility)

### Multiple-dispatch libraries

Multiple dispatch or multimethods in languages such as Dylan and Common Lisp (as CLOS) is older than the Julia language.
However, much of the motivation and design choices of current Python implementations come from Julia.

* [multimethod](https://github.com/coady/multimethod) It's stated goal is dispatch speed.
    * No matching method prints error giving missing signature (not non-matching signatures). plum does this as well.
* [plum-dispatch](https://github.com/wesselb/plum) Probably the most feature-ful
    * Also exposes type conversion and promotion mechanisms modeled on Julia
    * Keyword-only args, separated by `*`, are supported. They do not enter into dispatch. This is similar to Julia
    * Supports @staticmethod, at least basic.
    * If no matching method is found at dispatch time, a `NotFoundLookupError` is raised. One could add a feature to plum to print closest matching methods, as Julia does. 
* multipledispatch
    * Cannot use default values for args. This should be a possible feature.
    * Lowest time overhead for dispatch in benchmarks (of multipledispatch, plum-dispatch, and fastcore)
* fastcore
    * If there is no matching method, a method may still be called, and also called incorrectly. It would be better to throw some kind of `MethodError`.
    * Not as featureful as others
    * Small. A single file < 200 LOC.

### Design issues

* How to organize documentation. Doc system is not built to accommodate MD

#### Storing type-like information in various places

In qiskit, we sometimes distinguish "kinds" of objects by attributes; a flag or a string. Or by checking whether a method exists. This design complicates MD and makes it more difficult to apply broadly. I would be a good idea to move these things into the type system. The easiest way is to make another type rather than a use a flag. But, maybe there is also a way to use dispatch with a trait system.

Does a multiple-dispatch system turn Python into Julia? No. The blurred distinction between run time and compile time in Julia offers an advantage that is difficult to reproduce in Python (compilation itself is a big problem in Python). First, let's be more precise by what we mean by multiple dispatch.

#### Multiple dispatch vs. operator overloading
 MD is distinguished from function overloading in that the former is dynamic while the latter is static. Dispatch in the former is done on the dynamic type, in the latter it is done on the statically, lexically, analyzed type. Consider the code
```julia

function func(a::Animal)
    make_noise(a)
end
```
where we have three abstract types with the relation `Animal <: Thing`, `Machine <: Thing`, and another type `Dog <: Animal`. We might have methods
```julia
make_noise(m::Machine) = "crash"
make_noise(a::Animal) = "cry"
make_noise(dog::Dog) = "bark"
```
What happens when I call `func(dog)` ? In an operator-overloading language I get "cry", the static, lexically, deterimined type of `a`. In a MD language, dispatch is on the actual type of the object; I get "bark".

#### Run-time compilation and inference

But, an important advantage is present in both static languages and Julia that is not available in Python and CLOS. In Julia, when `func(dog)` is first called, the types of all expressions in the body are inferred if possible and code is compiled specially for the inferred types. In particular, although this is "dynamic dispatch", the method `make_noise` is devirtualized, and inlined if advantageous. This strategy  may be pursued to any depth (there are algorithms to determine when it is advantageous *not* to specialize). One thereby obtains advantages of both static and dynamic languages. 

* No diagonal dispatch. Some (all?) MD libraries' docs claim they do no support diagonal dispatch. I think the issue more broadly is that they do not support proper parametric types, in particular type parameters in the parameter lists. plum claims it has a method to get around lack of diagonal dispatch (using `Self`). But, I don't the problem worked around by `Self` is stated correctly. It is that `@dispatch` can't recognize the type of a class inside the definition of the class, because is net yet recognized by python. `Self` is in some sense a way to defer referring to the class by name.

* No universal, coherent type system.

### CODE REVIEW

**Comment by ikkoham** [comment]
In many cases, `singledispatch` is enough. How about using https://pypi.org/project/singledispatchmethod/?
This is standard from Python 3.8 and we can use it for Python 2.7-3.7 by installing the library.

**Comment by kdk** [comment]
Thanks @jlapeyre , this looks cool, and there are definitely some places where something like this could bring some clarity/readability improvements, specifically where we're expecting to be handling multiple different input types that require unique handling e.g. 
https://github.com/Qiskit/qiskit-terra/pull/5985/files#diff-a84abe28fb4a52b1ee2989190156adf34e0f09cbcffc5b2663697843d8893bd3R236

I'm not as much of a fan of applying this broadly across the code base. For example 
https://github.com/Qiskit/qiskit-terra/pull/5985/files#diff-f8bf228c13afac54d0487df4391520ab5b0efbe5649e447475d99dd04ce06c89R62 ,
obscuring the two `isinstance` checks, combined with the added metaclass structure and added decorators leaves the final code for me less readable and approachable.

**Comment by Cryoris** [comment]
I agree with @kdk. It looks like it could be very useful in some cases but using MD even in simple cases seems to add overhead and is, at least to me, less straightforward to read. 

Is it an option to only use MD in cases where we have large `isinstance` code blocks but keep `isinstance` in simple case distinctions?

**Comment by jlapeyre** [comment]
Thanks for the looking at this.

I should note first that I have since looked at `multimethod`, which might be a better choice: Dispatch is much faster than plum-dispatch. It has a longer history, and the currently released version is sufficient. It is small and pure python. There may be a feature or two that are missing, but it probably does what is necessary.

* > In many cases, singledispatch is enough. 

The places where it is used most effectively, such as the gradients code, requires multiple dispatch. Also we often have an object that it passed another object of the same kind, say for some kind of reduction. In this case you want a method for which you can dispatch on a single non-`self` argument, that is of the same type as `self`. The single dispatch library can't do this. Multiple dispatch libraries can.

* > obscuring the two `isinstance` checks, combined with the added metaclass structure and added decorators leaves the final code for me less readable and approachable.

This makes sense. Even one decorator adds some noise. The metaclass structure is unfortunate. The multimethod library, which I mentioned above, does not require the metaclass stuff, and doesn't seem the worse for it. In any case. I think it makes sense to try multiple dispatch more narrowly, say in a single class, and where the benefits are most clear.

* > is, at least to me, less straightforward to read.

This is hard to answer. In part, of course, it's a matter of getting used to understanding the logic when presented this way, which is not difficult. This PR doesn't really touch the main benefit of multimethods, which is to loosen the constraints of class-based dispatch allowing easier composability.

**Comment by jlapeyre** [comment]
This is not going to be merged. I'll close it. There may be some useful information for reference in this PR; that will still be available when it's closed.

**Comment by jlapeyre** [comment]
This is not going to be merged. I'll close it. There may be some useful information for reference in this PR; that will still be available when it's closed.

**Pull request closed without merging**
