### PR TITLE
Reject bad values in `SparsePauliOp.paulis` setter

### PR DESCRIPTION
**Pull request by atharva-satpute**
### Summary
Updated the sparse pauli setter method to propagate dimension info by calling the parent's (`BaseOperator`) `__init__()`
Fix: #10384

### Details and comments
The dimension info was updated and propagated up via `PauliList` but remained unchanged when accessed via `SparsePauliOp` object

### CODE REVIEW

**Review by jakelishman — COMMENTED** [review]
Thanks for looking at this.  I'm not certain that this will be the direction we ought to go with the linked issue: see https://github.com/Qiskit/qiskit-terra/issues/10384#issuecomment-1638621942.

For what it's worth, it's typically not good to call an `__init__` method from anywhere other than a child class's `__init__`; it's quite easy for bugs to slip in like this if the child class `__init__` prepares some other state before calling up to its parent initialiser.  It doesn't happen _currently_ in `SparsePauliOp`, but it's something that may well get introduced in the future.

**Review by ikkoham — COMMENTED** [review]
Thanks. It looks good to me. Could you add the release note and tests to check this spec?

**Comment by atharva-satpute** [comment]
Sure

**Comment by jakelishman** [comment]
@ikkoham: I've just updated this PR to add the tests and a release note.  Could you review / merge?

**Review by ikkoham — APPROVED** [review]
Nice. LGTM! (I believe this is back port stable potential.)

**Pull request merged**
