### PR TITLE
Add functional option to `circuit_key` primitives util

### PR DESCRIPTION
**Pull request by pedrorrivero**
### Summary
Adds optional kwarg to request a purely functional key from the `circuit_key` primitives utility. This is necessary to avoid recomputation on circuits which are functionally equivalent but vary in non-functional data (e.g. name, id).

### Details and comments
Default behavior is set to `False` (i.e. default key is not purely functional) this decision has been made for compatibility with the previous implementation, but I think setting the default to `True` would be preferred.

**EDIT: default behavior set to `True` after discussion (see below).**

### CODE REVIEW

**Review by ikkoham — DISMISSED** [review]
I understood the necessity of the feature. I approve this change, but note that `_circuit_key` is only a workaround in the first place, which is why it is set to private.

**Review by t-imamichi — DISMISSED** [review]
I'm personally fine to remove `id` from this key. We need to discuss it in the future.

**Comment by t-imamichi** [comment]
`id` was kept in the previous PR #8604 because I heard from @ikkoham that @jyu00 and @ikkoham had an agreement to make a composite key in addition to `id`. https://github.com/Qiskit/qiskit-terra/pull/8604#issuecomment-1247529117
If they agree to remove `id` and `name`, I'm fine to remove them. It makes the function simpler.

**Comment by jyu00** [comment]
Yeah we talked about using `id` and `len(data)`, but this is much better. I agree with removing `id`. In fact do we even have a use case for specifying `functional=False`?

**Comment by t-imamichi** [comment]
Thank you, Jessie. We can simplify the code by removing `id` and `name`. Let's go for it.

**Comment by ikkoham** [comment]
IMO, I like to stay on the safe side for these rare cases, in which circuits have different  `id` and `name` but same functionality. As Imamichi-san indicated in the previous PR, collisions are occurring in the corner cases. There are probably collisions that we are not aware and `id` and `name` might help.

It is a preference which way to fall on the tradeoff between efficiency and safety, so let's take the efficiency side in this case.
I believe it is unlikely in normal use and let's hope no bug reports come in 🤞

**Comment by pedrorrivero** [comment]
Okay, let's do the following then:
1. We add the `functional` kwarg to allow @ikkoham to include non-functional data when needed.
2. We default to `functional=True` since this seems to be the best approach to avoid recomputation.
3. We add `name` to the non-functional key to better handle corner cases.
4. We get rid of `id` since it may cause conflicts when running different interpreters (e.g. client and server), and when running a single interpreter it stands in it of itself as a unique key: hence making all other values inconsequential in that case.

The PR should now be ready to merge 😉

**Review by t-imamichi — APPROVED** [review]
LGTM

**Review by ikkoham — APPROVED** [review]
Thanks. LGTM.

**Comment by ikkoham** [comment]
Since this PR is not a new feature, but a follow-up of #8604 to improve efficiency, I would put it in at 0.22.

**Pull request merged**
