### PR TITLE
from qiskit.pulse import SamplePulse for type hints

### PR DESCRIPTION
**Pull request by cclauss**
### Summary

from qiskit.pulse import SamplePulse for type hints

### Details and comments

Help readers (and mypy) know where __SamplePulse__ is defined.

### CODE REVIEW

**Comment by taalexander** [comment]
Hi @cclauss, thanks for the contribution. The reason we initially went with the string names was due to import issues that the CI tests and linting are currently running into. If you can find a way to gracefully resolve these issues I would be very happy to have the type signatures return the type directly!

**Comment by taalexander** [comment]
Closing as this was addressed in #3902 as part of sweeping documentation updates. Thank you for your effort to clean up our code 😄

**Comment by cclauss** [comment]
Wow.  What was the logic behind removing all the type hints and moving them into comments?

**Comment by mtreinish** [comment]
The sphinx type hints extension was unable to resolve the type hints correctly without actually importing it as you do in this PR. But, when you do import it as @taalexander reported (and CI here showed) it causes both test and linter failures around circular imports. To fix the documentation build and properly resolve a link in the compiled documentation it was necessary to stop using type hints

**Comment by cclauss** [comment]
Got it.  The return values as strings were a better solution than no type checking at all.

**Pull request closed without merging**
