### PR TITLE
Decrease test runner concurrency on travis

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

Since enabling parallel test execution we're seeing a couple new issues
including failures caused by memory allocation issues in travis. This is
likely caused by increased memory pressue from running with nproc
workers, which on travis for linux means 32 workers. To decrease our
memory usage in CI and to also decrease the chances of a cross
interaction between tests running at the same time this commit changes
the test runner concurrency in travis runs to two workers instead of
nproc workers. Two workers is the least common demoniator between all
the travis environments (osx nodes only having 2 cpus), and since we
are using a fixed value that is used.

### Details and comments

See #1227 and https://travis-ci.org/Qiskit/qiskit-terra/jobs/451631270#L1615 for examples of the issues likely caused (or increased frequency of occurring) with higher concurrency.

### CODE REVIEW

**Comment by mtreinish** [comment]
We could use the nproc command (which is part of coreutils) to get the cpu on linux. But I'm not sure if it actually is worth trying to do this more dynamically.

As for speed I don't think it'll actually have a noticeable effect on the run time of the tests:

With 32 workers:
- 159.5 seconds https://travis-ci.org/Qiskit/qiskit-terra/jobs/451955827#L1562 

With 2 workers:
- 126.6 seconds https://travis-ci.org/Qiskit/qiskit-terra/jobs/451967434#L1562

**Comment by delapuente** [comment]
It is weird that 32 processes take longer than 2 but also possibly due to the overhead. I would expect some improvement in keeping the cores busy so, do you mind to test it adjusting the number of processes. I think the typical numbers are one less than the number of cores (pinging @atilag for confirmation). Can we do this to set the number of processes?

**Comment by mtreinish** [comment]
You shouldn't read to much in to the numbers I posted. It's just from one sample and the amount of variability in the travis environment is huge. I only used that to showcase that it's roughly in the same range, and we won't be able to notice a significant runtime difference (especially compared with how long it takes to setup a test env). For example you can look at the most recent run here: https://travis-ci.org/Qiskit/qiskit-terra/jobs/452065866#L1562 and see that it's slower than both the earlier numbers with 167.4 seconds

**Comment by delapuente** [comment]
Well, numbers aside. Why not fixing the number of logic cores trying to make the most of the number of available cores?

**Comment by mtreinish** [comment]
@delapuente if you really want to try and maximize the optimization for run time you can use the worker balance (that stestr prints by default) at the end of the run to see which worker is taking the most time (although I'd argue that it's not worth it with runtime this short). For the 32 worker case it's you can see: https://travis-ci.org/Qiskit/qiskit-terra/jobs/451955827#L1571 The 2 workers that take the longest are running the test_mapper.TestMapper class. I had a patch to change how we parallelized so we can split up the slow test classes (see https://github.com/Qiskit/qiskit-terra/pull/737/commits/0e8fd27debc55dca86ff80bdf25d4149909f28f7 ) which would make things faster. But it caused memory issues immediately

**Comment by mtreinish** [comment]
I don't really think there are significant gains to be had here by fine tuning the number of workers. The test suite is only ~500 tests even in the best case lets say we got it to execute tests in < 1 min. We're still spending several minutes setting up a node. I picked a value of 2 here because it made the patch simple since the osx nodes always only have 2 vcpus. I've seen several of the memory allocations already and I wanted to fix it quickly. Since we've had a lot of instability in the CI system lately.  Also using only 2 workers simplifies debugging if we do encounter isolation issues between tests because we don't have to worry about cross interactions with n different things. It also means when we run online tests post merge it means we only are making 2 api requests at a time which will decrease the load those tests place on the api endpoint (and it does seem to be pretty fragile).

**Comment by nonhermitian** [comment]
Yes, I got a memory allocation issue in the py35 tests. It is intermittent though

**Comment by atilag** [comment]
@delapuente @mtreinish my experience running these kind of things is that you have to test it by yourself and see the numbers, there's no maigc number here. Basically, because it really depends on what kind of tests you are running, whether they spwan other proccesses or not, whether they take time to execute or not, what other processes are running in your system at this very time. But in general, having more processes than the number of virtual cores doesn't usually helps so a good starting point is set the number of processes to the exact number of cores your O.S. sees. Having too many processes makes tracking a possible test fail way more difficult, as you have to wait for the other processes running in parallel to finish, and then finding in the log what's going on.
In this case, I'd rather use an env variable instead of setting a fixed value so it's easier to play with it and adjust it if needed.

**Comment by mtreinish** [comment]
@atilag right that's almost exactly what I was saying before. With the exception we're not talking about big time savings either way. It's not going to be noticeable in CI that we've decreased the concurrency.

That being said this patch is just for a quick fix to avoid running out of memory. It was supposed to be a quick fix, to eliminate one failure mode. The better fix is to decouple local test running settings from the CI environment, which I want to during the switch to using tox to run CI tests. Since right now between the combination of cmake and make doing that is much more involved. Which is why I don't want to try to micro-optimize anything here, it was to be a simple patch to quickly eliminate the memory issues in CI.

**Pull request merged**
