### PR TITLE
schemas: remove remaining "PersistentValue"s

### PR DESCRIPTION
**Pull request by drewrisinger**
### Summary

Remove "PersistentValue" instructions from the OpenPulse example schemas/QObj tests

### Details and comments

Follow-up to #4671. I think I got all the references using a search.

### CODE REVIEW

**Comment by taalexander** [comment]
I am not certain we should remove keys from the schema as this is a breaking change and would technically require a major version bump to the schema. The one caveat is that the schemas are permissive so if this instruction is removed it will continue to work with the backend. What are your thoughts @mtreinish.

**Comment by drewrisinger** [comment]
The main thing that prompted this was the removal of the "pv" instruction bind/handler in https://github.com/Qiskit/qiskit-terra/blob/f132cf7fc69920f393bc2055e98f20e8e7d6bce0/qiskit/qobj/converters/pulse_instruction.py#L387 (commit a9b68a5f6b108fcc981e64d2d822c556bdcdd0ab)

**Comment by taalexander** [comment]
> The main thing that prompted this was the removal of the "pv" instruction bind/handler in
> 
> https://github.com/Qiskit/qiskit-terra/blob/f132cf7fc69920f393bc2055e98f20e8e7d6bce0/qiskit/qobj/converters/pulse_instruction.py#L387
> 
> (commit [a9b68a5](https://github.com/Qiskit/qiskit-terra/commit/a9b68a5f6b108fcc981e64d2d822c556bdcdd0ab))

I suppose this will cause an error if a qobj with a PV instruction is supplied? If so I think the removal in `a9b68a5` might qualify as a bug.

**Comment by drewrisinger** [comment]
> I suppose this will cause an error if a qobj with a PV instruction is supplied? 

Exactly right. I'm agnostic about whether it's a bug or not. I assumed it was correct behavior, so I thought the schemas/examples should be updated to reflect that "pv" instruction is no longer handled by stock ``qiskit-terra``

**Comment by taalexander** [comment]
I think either solution is probably ok as the schemas are permissive, even if pv is removed a backend that supports it will be fine. I'll leave @mtreinish to weigh in with a final decision.

**Comment by mtreinish** [comment]
My feeling here is that we shouldn't remove it from the schema (for now) if `pv` is still a valid instruction on the backend side in IBMQ (and anybody else who happens to be using qobj). I agree it's backwards compatible in the sense validation won't fail because it'll just get passed in as a standard pulse and the parameter validity checking there now won't happen. We should have the schema reflect the validation we want the backend to use when it receives a random payload (because that's how it gets used by IBMQ for right now). If someone is using an older version of terra and submits a pv instruction we would want the schema validation to catch structural issues with the pv instruction instead of blindly accepting it. Once we split the schema out of terra it's usage as the backend's validation specification and that it's not strictly a client side testing thing will become clear.

**Comment by taalexander** [comment]
Given @mtreinish's comments, this PR should have the schema changes removed and then it will be good to go.

**Comment by drewrisinger** [comment]
@taalexander ack, pushed

**Pull request merged**
