### PR TITLE
Add option to user config to control reverse_bits in circuit drawer 

### LINKED ISSUE #9150: Add option in user config file to control `reverse_bits` in `circuit_drawer`
### What should we add?

Currently, the user config file supports `circuit_drawer` display options such as `output` (`"text"`, "`mpl`", etc.). Including the ability to change the `reverse_bits` option would allow users that prefer setting this option to `True` to not have to explicitly set this parameter every time a circuit is drawn.

### PR DESCRIPTION
**Pull request by diemilio**
### Summary
Fixes #9150. 

### Details and comments
This PR adds the option `circuit_reverse_bits` to the user config file to modify the default behavior of the `reverse_bits` option in the `circuit_drawer`. For example, the following configuration in the `settings.conf` file:
```text
[default]
circuit_drawer = mpl
state_drawer = latex
circuit_reverse_bits = True
```
the circuit drawer will display a circuit with the most significant bit at the top without explicitly passing the `reverse_bits=True` option to the `draw()` method:
``` python
from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
n = 4
qr = QuantumRegister(n, name='q')
cr = ClassicalRegister(n, name='c')
qc = QuantumCircuit(qr,cr)
qc.h(range(n))
for i in range(n-1,0,-1):
    qc.cx(i,i-1)
qc.barrier()
qc.measure(qr,cr)
qc.draw()
```
image

### CODE REVIEW

**Review by jakelishman — APPROVED** [review]
I tweaked the release note slightly and added an extra test that the changes to the user configuration file are correctly loaded up.  I hope you don't mind, sorry - normally I'd have asked them in a comment for you to do, but we're getting a little close to the target release of 0.23.0rc1 (my fault for not looking at the PR sooner).

This looks good to me - congratulations on your first code merged to Terra!  It'll be released on PyPI as a pre-release hopefully this Thursday and as a full release hopefully a week on Thursday.

**Comment by diemilio** [comment]
Thank you @jakelishman!

**Comment by jakelishman** [comment]
No worries! There's no need for you do anything more here, by the way - the bot will take care of merging.  We're just having minor problems with our CI at the moment, which should be cleared out in a couple of hours' time.

@Mergifyio requeue

**Comment by jakelishman** [comment]
@Mergifyio requeue

**Pull request merged**
