### PR TITLE
Refactor coverage CI workflow

### PR DESCRIPTION
**Pull request by jakelishman**
### Summary

This relaxes the constraint on `coverage` added in #9305.  The issue there is actually the now unmaintained `coveragepy-lcov` package is not compatible with Coverage.py 7.0.  However, we only needed `coveragepy-lcov` to convert Coverage's format into LCOV, which is a feature Coverage has had itself since version 6.0.

This commit also updates some parts of the coverage workflow that were old:

- there are new versions of the Actions `checkout` and `setup-python`, which swap to using Node 16 rather than Node 12, which is deprecated in GHA
- `grcov` is packaged and installable from `cargo` now, rather than needing a manual hard-coded pull from GitHub
- we can have `grcov` only keep the parts we care about immediately, rather than converting everything and later discarding it

### Details and comments

The chance of me having got this right first time is pretty slim.

### CODE REVIEW

**Comment by jakelishman** [comment]
There we go - fixed things up where I'd mishandled the configuration when transferring some of the new stuff I learned while writing my version of Rust coverage for https://github.com/jakelishman/qiskit-qasm2.

**Review by mtreinish — APPROVED** [review]
This LGTM, but before we merge do we need to update anything in the tox coverage job. It doesn't include rust coverage but is there any cli changes needed for just the python coverage we get from tox?

**Comment by jakelishman** [comment]
The tox job as it stands should just continue to work in the same way, though we could add Rust coverage to it if we wanted. There's a difficulty in that we'll need users to manually install a working version of `grcov` and `lcov` or the job will fail, but it's what I did on my OQ2 parser: https://github.com/jakelishman/qiskit-qasm2/blob/57005e6f1c41fca36c1436e50c5b668c83ae7ff3/tox.ini#L8-L35.  I'm happy to go either way.

**Comment by mtreinish** [comment]
Yeah, that makes sense. When I added the rust coverage collection I just skipped the tox piece because I didn't want to deal with grcov and lcov for local users. I think for this PR just doing the CI piece is fine, I was more just checking we didn't need to change `coverage3`  to `coverage`. If we want to look at adding rust coverage collection to the tox coverage job we can do that in a follow up.

**Pull request merged**
