### PR TITLE
QuantumCircuit.to_gate(..., label=...) support 

### LINKED ISSUE #4252: QuantumCircuit.append(custom_gate, label='foo') overwrites earlier labels
### Steps to reproduce the problem

```
>>> import qiskit as qk
>>> hadamard = qk.QuantumCircuit(1)
>>> hadamard.h(0)
>>> h_gate = hadamard.to_gate()
>>>
>>> circ = qk.QuantumCircuit(1)
>>> circ.append(h_gate, [0], label='Q')
>>> circ.append(h_gate, [0], label='P')
>>> print(circ)
     ┌───┐┌───┐
q_0: ┤ P ├┤ P ├
     └───┘└───┘
```

### PR DESCRIPTION
**Pull request by 1ucian0**
Fixes #4252

In https://github.com/Qiskit/qiskit-terra/issues/4207 @ajavadia introduced the use case of adding a custom gate with a label. He attempt the idea of allowing setting label at `QuantumCircuit.append` time. That brought [some problems](https://github.com/Qiskit/qiskit-terra/issues/4207) and the PR was reversed in https://github.com/Qiskit/qiskit-terra/pull/4328.

In https://github.com/Qiskit/qiskit-terra/issues/4252#issuecomment-620756458 I suggested the posibility of adding this label at `to_gate` time.

```python
hadamard = QuantumCircuit(1)
hadamard.h(0)

circ = QuantumCircuit(1)
circ.append(hadamard.to_gate(label='Q'), [0])
circ.append(hadamard.to_gate(label='P'), [0])
print(circ)
```
```
     ┌───┐┌───┐
q_0: ┤ Q ├┤ P ├
     └───┘└───┘
```

### CODE REVIEW

**Comment by Cryoris** [comment]
Could we add the same functionality to `to_instruction`? In most code I've seen people use `to_instruction` per default instead of `to_gate` 🙂

**Comment by 1ucian0** [comment]
> Could we add the same functionality to `to_instruction`?

`Instruction` does not have `label`, right?

**Comment by Cryoris** [comment]
Oh, right. What's the difference between `label` and `name` then again?

**Comment by 1ucian0** [comment]
`name` should be a short type name for Qobj and QASM pourpose.

`label` is set by the user.

In that direction,  https://github.com/Qiskit/qiskit-terra/issues/2393

**Comment by kdk** [comment]
> > Could we add the same functionality to `to_instruction`?
> 
> `Instruction` does not have `label`, right?

Is there a reason `Gate`s have labels but `Instruction`s don't?

**Comment by 1ucian0** [comment]
I guess because `labels` were introduced for noise. But probably that difference makes less sense now.

**Comment by Cryoris** [comment]
I think it would be useful to have `label`s then also for `Instruction`. But we can open another issue for that.

**Comment by 1ucian0** [comment]
I agree that gates and instruction should be more uniformed, both in #2393 way.

**Comment by 1ucian0** [comment]
> Needs a release note, otherwise looks good.

Done in 75f4d73

**Pull request merged**
