### PR TITLE
Level 1 chooses between trival and dense layout selection, depending on the layout score

### LINKED ISSUE #2845: optimization_level=1 always uses Trivial layout
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
```
               ┌───┐                ░ ┌─┐            
q37_0: |0>─────┤ X ├────────────────░─┤M├────────────
          ┌───┐└─┬─┘┌───┐           ░ └╥┘┌─┐         
q37_1: |0>┤ H ├──■──┤ X ├───────────░──╫─┤M├─────────
          ├───┤     └─┬─┘┌───┐      ░  ║ └╥┘┌─┐      
q37_2: |0>┤ H ├───────■──┤ X ├──────░──╫──╫─┤M├──────
          ├───┤          └─┬─┘┌───┐ ░  ║  ║ └╥┘┌─┐   
q37_3: |0>┤ H ├────────────■──┤ X ├─░──╫──╫──╫─┤M├───
          ├───┤               └─┬─┘ ░  ║  ║  ║ └╥┘┌─┐
q37_4: |0>┤ H ├─────────────────■───░──╫──╫──╫──╫─┤M├
          └───┘                     ░  ║  ║  ║  ║ └╥┘
  c5_0: 0 ═════════════════════════════╩══╬══╬══╬══╬═
                                          ║  ║  ║  ║ 
  c5_1: 0 ════════════════════════════════╩══╬══╬══╬═
                                             ║  ║  ║ 
  c5_2: 0 ═══════════════════════════════════╩══╬══╬═
                                                ║  ║ 
  c5_3: 0 ══════════════════════════════════════╩══╬═
                                                   ║ 
  c5_4: 0 ═════════════════════════════════════════╩═
```
```python
backend = provider.get_backend('ibmq_20_tokyo')
new_qc = transpile(qc, backend, optimization_level=1)
```

shows initial layout as the trivial layout, which is disconnected:

Screen Shot 2019-07-22 at 4 14 54 PM

However part #2 in the source says `_layout_check` does better layout 
if the circuit needs swaps, 

```python
# 2. Use a better layout on densely connected qubits, if circuit needs swaps
```
which is obviously the case here, but no other layouts
are actually selected (or imported).

### What is the expected behavior?
Expected that the `DenseLayout` is used if there are swaps needed.

### PR DESCRIPTION
**Pull request by 1ucian0**
On top of #3035, #3018, and ~#3321~ (therefore, `on hold`).

Fixes #2845

### CODE REVIEW

**Comment by ajavadia** [comment]
i'd like to get some timing on this for a very large circuit before we activate it for Level 1. Because it does a circuit deepcopy.

**Comment by 1ucian0** [comment]
> i'd like to get some timing on this for a very large circuit before we activate it for Level 1. Because it does a circuit deepcopy.

Using this 40-depth circuit in `FakeMelbourne`.
```python
qc = QuantumCircuit(14)
for i in range(39):
    qubit = i % 13
    qc.h(qubit)
    qc.cx(qubit, 13)
```

I timed them using (because, at least in my laptop, the result was varying a lot)
```
timeit(lambda: passmanager.run(qc), number=100)
```
The exact code here: [3324_rollback.txt](https://github.com/Qiskit/qiskit-terra/files/3799314/3324_rollback.txt)

## Without rollback

Using the following "level 1" (like the one on this PR but without the control flow):
```
pm1.append([DenseLayout(coupling_map, backend_properties), Layout2qDistance(coupling_map, property_name='dense_score')])
```
The result is: `133.380383911`

## With rollback
With the PR as it is 77d678a.

The result is: `189.16023166399998`.

Thanks a lot @kdk for helping me with this.

## Comparing against master

Considering the benchmark `qft.QftTranspileBench.time_ibmq_backend_transpile(2)`, this PR is 1.78x slower than master. However, it's important to notice that master is not running `DenseLayout` at all.

## Possible "solutions"

@kdk suggested a great possible optimization to `rollback_if`: Do not rollback (e.i. deepcopy) the dag if all the passes in the pass set are analysis pass (which is the case when layout selection).  I would really like to implement that optimization, but one that this PR is merged, because the stack of PRs is getting complicated.

**Comment by 1ucian0** [comment]
Other result, 600 depth circuit:
```
qc = QuantumCircuit(14) 
In [ ]: qc = QuantumCircuit(14) 
   ...: for i in range(599): 
   ...:     qubit = i % 13 
   ...:     qc.h(qubit) 
   ...:     qc.cx(qubit, 13) 
   ...: print(qc.depth()) 
   ...: start = time.time() 
   ...: passmanager.run(qc)      
   ...: print(time.time()-start)                                                                                                             
600
11.103873014450073
```

**Comment by 1ucian0** [comment]
> @kdk suggested a great possible optimization to rollback_if: Do not rollback (e.i. deepcopy) the dag if all the passes in the pass set are analysis pass (which is the case when layout selection).

Good news! Adding this optimization was trivial (see https://github.com/Qiskit/qiskit-terra/pull/3324/commits/ec8e31ac6311b8a1a903f6423b0f1a9edd26c055). I will rerun the tests.

**Comment by 1ucian0** [comment]
(because I'm getting full different set of values (probably related with changes in master or my machine is just less loaded) here are the new outputs:

## Without rollback

The result is: `58.22561879`

## With rollback

The result is: `58.96733729300001`

## Comparing with level 2

Level 2 is running in: `346.168352814`

## Comparing against master

[1.74x slower](https://travis-ci.com/Qiskit/qiskit-terra/jobs/252033582#L979) for `qft.QftTranspileBench.time_ibmq_backend_transpile(2)`

**Comment by 1ucian0** [comment]
Closing in favor of #3657

**Pull request closed without merging**
