### PR TITLE
Visualization of open controlled gates added in latex drawer

### LINKED ISSUE #3958: add visualization of open controlled gates [latex drawer]
@ewinston says in https://github.com/Qiskit/qiskit-terra/issues/3864:
> In PR #3739, open controlled gates were implemented. With that PR a new keyword argument was added to specify the control state,
> 
> `XGate().control(3, ctrl_state=6)`
> 
> This creates a 4 qubit gate where the first three qubits are controls and the fourth qubit is the target where the x-gate may be applied. A `ctrl_state` may alternatively be expressed as an integer string,
> 
> `XGate().control(3, ctrl_state='110')`
> 
> where it is more apparent which qubits are open and closed. In this case when q[0] is open and q[1] and q[2] are closed the x-gate will be applied to q[4].

As a reference https://github.com/Qiskit/qiskit-terra/pull/3867 implements open controlled gates for the text visualizer like this:
```python
qr = QuantumRegister(4, 'q')
circuit = QuantumCircuit(qr)
circuit.append(U2Gate(pi, -5 * pi / 8).control(3, ctrl_state='100'),
               [qr[0], qr[3], qr[2], qr[1]])
circuit.draw('text')
```
```
                         
q_0: |0>────────o────────
        ┌───────┴───────┐
q_1: |0>┤ U2(pi,-5pi/8) ├
        └───────┬───────┘
q_2: |0>────────■────────
                │        
q_3: |0>────────o────────
```
The current output for `circuit.draw('latex')` is:
image

### PR DESCRIPTION
**Pull request by TharrmashasthaPV**
### Summary

Fixes  #3958 .

### Details and comments

The visualization of open control gates have been added for all controlled-gates for latex drawer. A sample circuit open controlled gates looks like below:

all_latex_circuit

### CODE REVIEW

**Comment by ajavadia** [comment]
Looks pretty neat.
How does the example code in the issue draw?
```
qr = QuantumRegister(4, 'q')
circuit = QuantumCircuit(qr)
circuit.append(U2Gate(pi, -5 * pi / 8).control(3, ctrl_state='100'),
               [qr[0], qr[3], qr[2], qr[1]])
circuit.draw('text')
```

**Comment by TharrmashasthaPV** [comment]
The example code is drawn as 

example

**Comment by TharrmashasthaPV** [comment]
> 
> 
> Looks pretty neat.
> How does the example code in the issue draw?
> 
> ```
> qr = QuantumRegister(4, 'q')
> circuit = QuantumCircuit(qr)
> circuit.append(U2Gate(pi, -5 * pi / 8).control(3, ctrl_state='100'),
>                [qr[0], qr[3], qr[2], qr[1]])
> circuit.draw('text')
> ```

The example code is drawn as 

example

**Comment by ajavadia** [comment]
can it be modified so the line doesn't go through the U2 box? this will happen for any gate whose controls are on either side

**Comment by TharrmashasthaPV** [comment]
> 
> 
> can it be modified so the line doesn't go through the U2 box? this will happen for any gate whose controls are on either side

I'm on it.

**Comment by TharrmashasthaPV** [comment]
I have corrected the circuit drawings. Following is an example circuit.

line_adjusted_example

I suppose this is fine.

**Pull request merged**
