### PR TITLE
Improve sum op equals

### PR DESCRIPTION
**Pull request by towynlin**
### Summary

Fixes the specific problem that was the impetus for #5745.

```python
>>> from qiskit.opflow import I, X
>>> (0 * X + I) == I
True  # was False before this PR
>>> I == (0 * X + I)
True  # was False before this PR
```

### Details and comments

The only reason those equality tests unexpectedly failed before was because the code didn't handle the comparison of a `PauliSumOp` with a single `PauliOp` and explicitly returned False when the types differed. Wrapping the `PauliOp` into a `PauliSumOp` easily enables the rest of the existing comparison logic.

This is a pretty surgical change compared to the [solution](https://github.com/Qiskit/qiskit-aqua/pull/1263/files#diff-81ae98372256dee6226b03147e6e558cedea1a45403dcc00d2d3bb5b8df1921b) proposed about a year-and-a-half ago for qiskit-aqua. There may be more to improve regarding equality testing of `SummedOp`.

If there's some further clear failure case that requires the originally proposed threshold checking beyond what already happens in `reduce`, let me know, and I'll be happy to extend this PR — or else we can open another issue for such a case.

### CODE REVIEW

**Comment by ikkoham** [comment]
@towynlin Thank you for your contribution.
When I made PauliSumOp, I defined that PauliOp and PauliSumOp are not equal because they have different types. The reason is that introducing this would require similar conversions for other primitive operators (e.g. MatrixOp and CircuitOp), which would be too expensive. However, if you want to do the same conversion for all operators, it might be a good idea to be consistent. 

I'd like to hear other people's opinions on this issue.

**Comment by towynlin** [comment]
Watching discussion with curiosity. Happy to help in any way I can.

**Comment by towynlin** [comment]
@ikkoham Thank for you sharing the history of how you made PauliSumOp and your rationale at that time. It's a very useful tool, and the performance gains over the prior implementation are indeed impressive. 🙇 I enjoyed reading through [the original PR from Nov-Dec 2020](https://github.com/Qiskit/qiskit-aqua/pull/1440) and understand better your intentions.

I think from a developer ergonomics perspective I agree with you @woodsp-ibm that expensive conversions here should be avoided unless more explicitly requested by the user. We wouldn't want to surprise folks with complex computations when they thought they were making a simple comparison.

After thinking about this for the last week of silence on this issue, I believe the best path is to merge this PR as-is **_if_** we agree that `0 * X + I == I` should evaluate to True, from the perspective of a qiskit user (who reads the [Operators docs](https://qiskit.org/documentation/apidoc/opflow.html), basically understands John Watrous's formalism, and, crucially, _does not know about the underlying software architecture_). I believe that is what such a user would expect and thus makes the most sense here.

Other related issues like comparisons for MatrixOp and CircuitOp could be filed as their own githhub issues and discussed independently.

**Comment by ikkoham** [comment]
To be honest, I don't use this feature (SummedOp of PauliOp) of opflow (I always use PauliSumOp).
So I'm not sure how this equals would be useful for users, so I'm not sure. Basically, I'm not strongly opposed to it...

**Comment by woodsp-ibm** [comment]
> So I'm not sure how this equals would be useful for users. But, basically, I'm not strongly opposed to it...

@ikkoham I think this just makes sure some of the basics work as expected. I'll go ahead and approve to try and get this finished off - it seems that this is ok for you, in that you are not strongly opposed, but this is to do a final check with you .

**Review by woodsp-ibm — APPROVED** [review]

**Review by ikkoham — APPROVED** [review]
Thank you. I thought this was a good user request. LGTM.

**Pull request merged**
