### PR TITLE
Fixed issue 6612 by covering ibmq examples by lint check

### LINKED ISSUE #6612: Pylint not applied to examples/python/ibmq
In making #6611 I noticed that the way we were applying pylint to the examples directory, as 

    pylint -rn --disable='C0103, C0114, W0621' examples/python/*.py

only covers the top-level python directory but not the ibmq subdirectory. In #6597 I made the git path `:(glob,top)examples/python/*.py` rather than the more complete `:/examples/*.py` to avoid raising new pylint errors, but we should fixup the ibmq examples and cover them by the default lint rule.

### PR DESCRIPTION
**Pull request by dhruvbhq**
### Summary

Fixes #6612 

### Details and comments

The ibmq examples were not being covered by lint checks. This PR fixes lint errors in ibmq examples and covers them by the lint checks.

1. Added `__init__.py` files to convert qiskit examples to package to facilitate lint checking
2. Updated Makefile and tox.ini lint targets to cover ibmq examples as well
3. Updated Make.bat batch file to make it consistent with these and other recent changes
4. Fixed up lint errors found
5. The check C0114 (missing module docstring) is no longer disabled in examples, as it is good to have docstrings.

### CODE REVIEW

**Comment by dhruvbhq** [comment]
Hi, as some things are new to me, I'd like to discuss some points about this PR:

1. I got two lint errors while running pylint on ibmq examples: E0611: no name 'ibmq' in module 'qiskit.providers' and E0401: Unable to import 'qiskit.providers.ibmq'. These were appearing even after doing 'pip install qiskit-ibmq-provider'. When trying to run the ibmq examples locally, 'import qiskit.providers.ibmq' is able to locate it in 'virtualenvpath'/lib/site-packages/qiskit/providers/ibmq. However, I believe pylint is looking for it in qiskit-terra/qiskit/providers, where it is not present. Therefore, I think the pylint check is too strict in this case and I believe it is appropriate to disable these two checks in the lint targets. If there is a better solution to this, I'd love to hear. @levbishop 

2. From what I could understand by reading the code, examples are not yet checked by pylint in the azure_pipelines.yml. Is there a reason for doing so? I think azure_pipelines.yml should be updated similarly too.

Thanks :)

**Comment by 1ucian0** [comment]
Hi @dhruvbhq !

Sorry we missed this one. Is your first point ("Added `__init__.py` files to convert qiskit examples to package to facilitate lint checking") necessary? Im not sure if the examples are being packaged.

**Comment by dhruvbhq** [comment]
Hi @1ucian0!

I haven't looked at this in a while, but I think what I did/meant was this:

In the Makefile, the lint target runs pylint ... on examples/python/*.py . [See here.](https://github.com/Qiskit/qiskit-terra/blob/299d03bf7ad717a85e60931a9ea67405ae198986/Makefile#L52)

However, the IBMQ examples are present as `examples/python/ibmq/*.py`, so the above implementation didn't cover the `ibmq/ *.py` files.
I believe adding the \_\_init\_\_.py files allowed me to define the line target as 
`pylint -rn --disable='C0103, W0621, E0611, E0401' examples`,
instead of individually specifying the \*.py files.
I think I went for this implementation because if other example subdirectories get added in future, it would not be needed to add an extra dir/*.py to the lint.

**Comment by 1ucian0** [comment]
Hmm... I think pylint is recursive in all the subdirectories by default. But I did not check it.

**Comment by dhruvbhq** [comment]
Hi,
Ah, I see. Those are some interesting consequences which I was unaware of. I will try to work on it as soon as I am able to.

**Comment by jakelishman** [comment]
Hi there - sorry to come back like this, but with #8080 (and general Qiskit direction), we're going to be removing the IBMQ examples from the Terra repository because `qiskit-ibmq-provider` is going to be deprecated in favour of a new package called `qiskit-ibm-provider` (`ibm` not `ibmq`).  We won't be replacing these examples, so covering them for lint isn't necessary any more.

Thanks for the interest in contributing, though, and sorry it came down like this.  If you're interested in finding something else, please have a look at our issues tagged ["good first issue"](https://github.com/Qiskit/qiskit-terra/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) or ["help wanted"](https://github.com/Qiskit/qiskit-terra/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22).

**Pull request closed without merging**
