### PR TITLE
set default draw(cregbundle=True)

### PR DESCRIPTION
**Pull request by 1ucian0**
Undoing https://github.com/Qiskit/qiskit-terra/pull/4321/ for 0.15.

### CODE REVIEW

**Comment by ajavadia** [comment]
needs a release note

**Comment by enavarro51** [comment]
@1ucian0 and @ajavadia as per #4554, doing this will cause the latex drawer with a conditional to fail, as per test_teleport in test_visualization.py. One option might be to temporarily set default in latex to False, until the bug is fixed.

**Comment by 1ucian0** [comment]
Hopefully,  #4554 will be closed soon (ping @rao107 ?). 

The minimal example to reproduce this issue:
```
from qiskit import *
qr = QuantumRegister(1, 'q')
cr = ClassicalRegister(3, 'c')
qc = QuantumCircuit(qr, cr)
qc.z(qr[0]).c_if(cr, 1)
qc.draw(output='latex', cregbundle=True)
```
```
IndexError: list index out of range
```

Adding `on hold` as #4554 is blocking it.

**Comment by 1ucian0** [comment]
In https://github.com/Qiskit/qiskit-terra/pull/4595/commits/ba01a5137bfc47a1b8a2378ac276bfbb4339cff2 I'm adjusting the test.

**Comment by enavarro51** [comment]
@1ucian0 Here's a diff that I think fixes the problem, but I'm not real familiar with the latex drawer, so I didn't submit since I wasn't sure if this would cause any other issues. 
```
@@ -423,8 +424,10 @@ class QCircuitImage:
                         temp.sort(key=int)
                         bottom = temp[len(pos_array) - 1]
                         gap = pos_cond - bottom
-                        for i in range(self.cregs[if_reg]):
-                            if if_value[i] == '1':
+                        creg_rng = 1 if self.cregbundle else self.cregs[if_reg]
+                        for i in range(creg_rng):
+                            if (if_value[i] == '1' or (self.cregbundle
+                                                       and int(if_value) > 0)):
                                 self._latex[pos_cond + i][column] = \
                                     "\\control \\cw \\cwx[-" + str(gap) + "]"
                                 gap = 1
@@ -551,8 +554,10 @@ class QCircuitImage:
                                 self._latex[pos_1][column] = ("\\gate{%s}" % nm)
 
                             gap = pos_2 - pos_1
-                            for i in range(self.cregs[if_reg]):
-                                if if_value[i] == '1':
+                            creg_rng = 1 if self.cregbundle else self.cregs[if_reg]
+                            for i in range(creg_rng):
+                                if (if_value[i] == '1' or (self.cregbundle
+                                                           and int(if_value) > 0)):
                                     self._latex[pos_2 + i][column] = \
                                         "\\control \\cw \\cwx[-" + str(gap) + "]"
                                     gap = 1
@@ -623,8 +628,10 @@ class QCircuitImage:
                             bottom = temp[1]
 
                             gap = pos_3 - bottom
-                            for i in range(self.cregs[if_reg]):
-                                if if_value[i] == '1':
+                            creg_rng = 1 if self.cregbundle else self.cregs[if_reg]
+                            for i in range(creg_rng):
+                                if (if_value[i] == '1' or (self.cregbundle
+                                                           and int(if_value) > 0)):
                                     self._latex[pos_3 + i][column] = \
                                         "\\control \\cw \\cwx[-" + str(gap) + "]"
                                     gap = 1
@@ -831,8 +838,10 @@ class QCircuitImage:
                             bottom = temp[2]
 
                             gap = pos_4 - bottom
-                            for i in range(self.cregs[if_reg]):
-                                if if_value[i] == '1':
+                            creg_rng = 1 if self.cregbundle else self.cregs[if_reg]
+                            for i in range(creg_rng):
+                                if (if_value[i] == '1' or (self.cregbundle
+                                                           and int(if_value) > 0)):
                                     self._latex[pos_4 + i][column] = \
                                         "\\control \\cw \\cwx[-" + str(gap) + "]"
                                     gap = 1
```

**Comment by rao107** [comment]
Hi! Apologies for not responding sooner, I can definitely work on #4554.

**Comment by rao107** [comment]
I think @enavarro51 essentially fixed the problem in his diff. I would just also change
`if self.cregbundle and self.ops[0][0].name == "measure"`
to
`if self.cregbundle and (self.ops[0][0].name == "measure" or self.ops[0][0].condition):`
on lines 295 and 390 to keep the number of classical registers visible.

I also felt like the index of the classical register that the conditional gate connects to (like when a qubit is measured) would be nice to add but the latex would either not compile or ignore it when I tried to implement it. Is it possible to have both the black dot from the conditional gate and the index of the classical register?

**Comment by enavarro51** [comment]
@rao107 I'm not sure that the index adds a lot. If the user wants the details of the cregs, they can turn the cregbundle off. I think what you have is enough to submit a PR for #4554.

**Comment by 1ucian0** [comment]
#4554 is fixed. Removing `on hold`.

**Pull request merged**
