### PR TITLE
Fix seed in QAOA test

### PR DESCRIPTION
**Pull request by ikkoham**
### Summary

Fix https://dev.azure.com/qiskit-ci/qiskit-terra/_build/results?buildId=24547&view=logs&jobId=6d8ff735-f981-52fa-2234-caef37f9a56b&j=3956a1e0-82bc-50b0-1442-e87b8e13252f&t=4d4946a8-bdaf-51d1-e5e9-413bd0078b90

### CODE REVIEW

**Review by manoelmarques — APPROVED** [review]

**Comment by Cryoris** [comment]
Would it be better to go via `algorithm_globals.random_seed` to also fix the numpy seeds?

**Comment by ikkoham** [comment]
Yes. And, I think we should use same quantum algorithm initialized in `setUp `. Can I refactor the code in another Pull Request?

**Comment by woodsp-ibm** [comment]
If this is holding up the build due to randomly failing then merging seems, fine since its no different than the other tests in the same module. Improving them in another PR seems ok as its not so high priority as having the tests work reliably.

**Comment by ikkoham** [comment]
if you want to merge this ASAP, please revert 1c11d84. (if so I will make another PR.)

**Review by manoelmarques — APPROVED** [review]

**Pull request merged**
