### PR TITLE
Cleanup test suite a bit

### PR DESCRIPTION
**Pull request by nonhermitian**
### Summary

The tests were looking a bit ugly so I cleaned them up a bit:

- All test names now fit within std 80 char terminal line.
- Removed depreciation warnings, where possible.
- Moved some tests away from using `QuantumProgram`.
- Removed a bunch of 'test' in the descriptions of the test, since it is obvious.

### CODE REVIEW

**Comment by ajavadia** [comment]
I disagree with chopping off class names just to save a few characters. They don't even run into any line limits. Instead, we lose descriptiveness of what the tests are:
TestAnonymousIdsInQuantumProgram -> TestAnonIdsInQP
TestLocalQasmSimulatorPy -> TestQasmSimPy
TestLocalQasmSimulatorCpp -> TestQasmSimCpp
TestWrapperCredentials -> TestCredentials
TestLatexSourceGenerator -> TestLatex
TestQuantumProgram -> TestQP
etc...

The docstring changes are fine.

The removal of Quantum Program in tests is really good. Does this PR remove all quantum program usages from the tests (except inevitable places like `test_quantumprogram.py`).

**Comment by nonhermitian** [comment]
I got some, but probably not all. The use of quantum program should raise an exception, so we can get them all. 

As for the test and module names, we really arent losing much given everything has docstrings. Do we really need reminding that the local qasm simulator is local in the module name, for example?

**Comment by nonhermitian** [comment]
Maybe QP to QuantProg though.

**Comment by nonhermitian** [comment]
Ok, then I will close this.

**Comment by ajavadia** [comment]
Sorry about the confusion, my comment was only about chopping off those names. The rest is good and is actually needed. As I mentioned, the other PRs I opened are **follow-ups**.

**Comment by diego-plan9** [comment]
I also agree cleaning up the test suite is needed, and there are actually more items to be taken care of eventually (ie. not for 0.6) - thanks for starting the effort, @nonhermitian !

Following up on @ajavadia comment about shortening the names, the ultimate reason is derived from [PEP20](https://www.python.org/dev/peps/pep-0020/):
> Readability counts.

Code is written once but read many times, and that is basically the reason why we insist in keeping descriptive names and are insistent in this aspect during the reviews: it's generally much easier to find a good name while writing the PR, than updating it afterwards, and helps maintainability a lot. In this particular case, it's a very frequent case for the testing tools and IDEs to end up printing `TestQuantumProgram.test_something` failed, which is much easier to parse mentally than `TestQP.test_sth`.

As for the docstrings, thanks for the efort as well! Can you however tweak the _style_ to adhere to [PEP8](https://www.python.org/dev/peps/pep-0008/#documentation-strings) (further expanded in [PEP257](https://www.python.org/dev/peps/pep-0257) - we don't adhere to that one explicitely, but provides more rationale):
> For one liner docstrings, please keep the closing """ on the same line.

In regards to changing the content of the docstrings in order to remove the annoying `Test that ...` bits, I'm a bit unsure. Technically PEP8 and others have some recommendations for comments (and docstrings are considered as a subset of comments in that regard) that we also generally follow:
> Comments should be complete sentences. The first word should be capitalized, unless it is an identifier that begins with a lower case letter (never alter the case of identifiers!).
> When writing English, follow Strunk and White.

But I think we can be lenient on this one, as they are indeed repetitive and all of them starting with `Test if ...` does not provide a lot of value comparing to how annoying it is. So no strong opinion from me on this one :grin:

**Comment by ajavadia** [comment]
@nonhermitian can you rebase this due to recent changes (merge of #739)? The changes are mostly cosmetic.

**Comment by nonhermitian** [comment]
I think the only thing of value left in this PR is the removal of `QuantumProgram` from the mapping tests.  I will just make a new PR with that change.

**Comment by delapuente** [comment]
Per the previous comment, closing this PR.

**Comment by ajavadia** [comment]
@nonhermitian I will do the `QuantumProgram` removal in #724 so you don't have to.

**Pull request closed without merging**
