### PR TITLE
Add support for attachments to test execution

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

By default in CI and with tox locally we run all the tests in parallel.
However, this makes things like printing to stdout, warnings on stderr,
or logging during tests difficult to deal with. This is because we'll
have multiple writers to the output streams simultaneously and no way
to figure out which text goes to which test. Luckily stestr and the
subunit protocl it uses internally has a method for adding attachments
to test results to handle this kind of case. Using this each output
stream is associated with the test which generated it and will get
displayed as such. The only issue with this is that the stdlib unittest
doesn't know how to write attachments to it's result stream. There is a
unittest extension library testtools[1] that provides this functionality
in a strictly compatible manner with unittest, however the current state
of the library needs some work before it can work well with more modern
features of stdlib unittest from python>3.5 so we either have to change
the tests to not use these features or come up with an alternative
solution for test attachments.

This commit ports the necessary result streaming functionality from
testtools into the QiskitTestCase base test class and then sets up the
appropriate fixtures to attach output streams from each test. This works
around the current limitation with testtools (I'm slowly working on
fixing this in testtools) but still provides the functionality. When
testtools is at the point it can be a drop in replacement for unittest
as terra is using it we can drop this code.

As part of this change all the test classes that define a setUp have a
missing super() call added. This framework does not work without setUp
in the base class being defined since that's what is used to setup the
stream capture. Moving forward the base test class actually enforces
that super() is called, otherwise the tests will fail.

### Details and comments

[1] https://github.com/testing-cabal/testtools

### CODE REVIEW

**Comment by mtreinish** [comment]
For an example of the attachments output: https://travis-ci.com/github/Qiskit/qiskit-terra/jobs/298739756#L586

**Comment by mtreinish** [comment]
This is stuck on python 3.5 because of subTest usage. The result reporting mechanism in python 3.5's unittest module differs from python 3.6+ which causes the new test results handler to fail when it encounters a subtest on python 3.5. I can either look at backporting py3.5 compat code from python 3.6 to the results handling added here, or convert subtests to use ddt which just uses standard test case results.

**Comment by 1ucian0** [comment]
ping @mtreinish !

python 3.5 is reaching EOL.

**Comment by mtreinish** [comment]
@1ucian0 thanks for the reminder this is unblocked now since we've merged #4926 I'll rebase it.

**Comment by mtreinish** [comment]
@1ucian0 ok this is working now. You can see examples of the attachments in the CI log here:

https://dev.azure.com/qiskit-ci/qiskit-terra/_build/results?buildId=18729&view=logs&j=8eacdd59-c2e8-5617-75a5-8ed7c854a78f&t=5df005f4-d5f4-5d2d-0307-5b24b15488fc&l=754

**Review by 1ucian0 — APPROVED** [review]
Great! This will save us some headaches...

**Pull request merged**
