### PR TITLE
Avoid using np.round in optimize1q pass

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

In #4015 a fix was added to handle fp precision issues around 0
comparisons that involved calling np.round to adjust the values for
comparison. However this is kind of an antipattern for doing this type
of check, since round involves making a copy of the input and truncating
the value. Instead this commit adjusts the rounding to use a more
standard pattern, using abs and an adjustable eps value to use.
This should avoid the unnecessary overhead caused by using
np.round().

### Details and comments

### CODE REVIEW

**Comment by mtreinish** [comment]
Running the asv benchmarks for the optimize 1q pass with this applied locally shows a good speedup:

```
Benchmarks that have improved:                                                  
                                                                                
       before           after         ratio                                     
     [5bdd12db]       [bbc3fbaf]                                                
     <master>         <remove-round-optimize-1q>                                
-         296±1ms        171±0.5ms     0.58  passes.UnrolledPassBenchmarks.time_optimize_1q(5, 1024)                                                            
-         923±4ms          530±3ms     0.57  passes.UnrolledPassBenchmarks.time_optimize_1q(14, 1024)                                                           
-      1.33±0.01s          760±5ms     0.57  passes.UnrolledPassBenchmarks.time_optimize_1q(20, 1024)                                                           
                                                                                
SOME BENCHMARKS HAVE CHANGED SIGNIFICANTLY.                                     
PERFORMANCE INCREASED.
```

**Comment by 1ucian0** [comment]
Cool! I didn't know that. Does it make sense to chance every round into this pattern?

**Comment by mtreinish** [comment]
> Cool! I didn't know that. Does it make sense to chance every round into this pattern?

It depends if there are other places it makes sense sure. `np.round` has its place like when you need a value with a fixed precision. But if you're just comparing against a constant this is better, or if you're comparing 2 variables `np.isclose()` is a better choice. For string formatting you can use format or the several methods numpy provides to get strings from values or adjust default formatting. Although for strings performance doesn't typically matter as much.

**Comment by 1ucian0** [comment]
From a quick grep, it does not seems that are many of those situations. The only one I found was in `qiskit/circuit/library/arithmetic/weighted_adder.py` where the full thinks looks more complicated that it should:

```python
131         if weights:
132             for i, weight in enumerate(weights):
133                 if not np.isclose(weight, np.round(weight)):
134                     raise ValueError('Non-integer weights are not supported!')
135                 weights[i] = np.round(weight)
```

**Pull request merged**
