### PR TITLE
Change algorithms from pending deprecate to deprecate

### PR DESCRIPTION
**Pull request by manoelmarques**

### CODE REVIEW

**Comment by woodsp-ibm** [comment]
Needs care when conflicts are resolved to include the url to migration guide again and the version since deprecation will need to be 0.24.0

**Comment by Eric-Arellano** [comment]
> Needs care when conflicts are resolved to include the url to migration guide again and the version since deprecation will need to be 0.24.0 (https://github.com/Qiskit/qiskit-terra/pull/9616 was the cause of the conflicts)

I will push a commit today to fix the merge conflicts to clean up after myself :) My understanding from https://github.com/Qiskit/qiskit-terra/pull/9616#discussion_r1110387405 was that we didn't want me to make the change to Deprecated in that PR.

**Comment by woodsp-ibm** [comment]
Thanks in advance! That comment was more that the pending deprecation has been in place since 0.22. It now says 0.23,, not that it matters really since this PR will override that yet again to make it since deprecation.

I imagine this will all need fixing up too #9176 - which is the deprecating the logic that the deprecated algorithms relied on for the transition over to primitives.

**Comment by woodsp-ibm** [comment]
Closing as superseded by #9883 which has now been completed and merged.

**Pull request closed without merging**
