### PR TITLE
enables the code example

### PR DESCRIPTION
**Pull request by JiahaoYao**
Two things 

- equation does not show up (this hasn't been fixed)
image

- the code doesn't render
image

### CODE REVIEW

**Review by ikkoham — APPROVED** [review]
Thank you for finding the problem and fixing it. This is a great first contribution to qiskit!

**Comment by 1ucian0** [comment]
The first issue you mentioned was fixed in https://github.com/Qiskit/qiskit-terra/pull/8106

**Comment by JiahaoYao** [comment]
Sounds good and thanks @ikkoham @1ucian0 , and let me know if there is other potential issues i can contribute to!

**Comment by 1ucian0** [comment]
Welcome to the Qiskit community! You can either fix issues as run into them or check out the `good first issue` or `help wanted` issue label

**Pull request merged**
