### PR TITLE
Convert sym in pi_check to sympy sstr instead of str

### LINKED ISSUE #6757: pi_check does not convert param containing ParameterExpression of a float
### Information

- **Qiskit Terra version**: current main
- **Python version**: 3.8
- **Operating system**: Ubuntu

### What is the current behavior?

Running this code with main from June 29th,
```
from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister, transpile
from qiskit.test.mock import FakeTenerife
circuit = QuantumCircuit(3)
circuit.h(1)
transpiled = transpile(circuit, backend=FakeTenerife(),
                       optimization_level=0, initial_layout=[1, 2, 0],
                       basis_gates=["id", "cx", "rz", "sx", "x"], seed_transpiler=0)

transpiled.draw('mpl')
```
produces
image
and using current main produces
image
All other gates with params seem to properly display pi.

### What is the expected behavior?

Should see pi/2.

### Suggested solutions

Not sure what changed. The param in this case is a ParameterExpression which follows a different path in pi_check. For some reason, either a change in tolerances or a change in sympy perhaps, a trailing zero was being added to the sympy expression. This meant the param would not match the sympy expression and the pi string was not substituted.

Should be fixable by a str(float(sym)), but it might be good to know what changed in case there are hidden issues.

### PR DESCRIPTION
**Pull request by enavarro51**
### Summary

Fixes #6757

### Details and comments

This fixes a problem that arose from #6505. In that PR, the `__str__` method for `ParameterExpression`s was changed from using `str` to using the `sympy` `sstr` with `full_prec=False`. The `ParameterExpression` portion of `pi_check` was still using `str` so for fractions of pi with 0 at the last precision (most notably pi/2), the comparison would fail and the float would be displayed instead of the pi fraction.

### CODE REVIEW

**Comment by jakelishman** [comment]
This whole method of stringify-ing the expression, then attempting to patch the output seems a little fragile to me.  For example, here's a contrived example using a large `eps` which causes incorrect string replacement:
```python
>>> from qiskit.circuit.tools import pi_check
>>> from qiskit.circuit import Parameter
>>> x = Parameter('x')
>>> expr = 1 + 10.1*x; expr
ParameterExpression(10.1*x + 1)
>>> pi_check(expr, eps=0.02)
'5π/160.5π/16*x + 5π/16'
```

Instead, is it worth considering patching the expression _before_ the stringification by replacing numbers with a derived type that knows how to print itself?  I think it'd look something like

```python
class _PiCheckNumber(sympy.AtomicExpr):
    def __new__(cls, *_):
        # Intercept sympy's attempt to return singletons
        return object.__new__(cls)

    def __init__(self, base, options=None):
        self.__base = base
        self.__options = options or {}

    def __getattr__(self, attr):
        # Pass through to the base, except for our patch.
        if attr == "_sympystr":
            return self._sympystr
        return getattr(self.__base, attr)

    def _sympystr(self, _printer):
        sign = "-" if self.__base.is_negative else ""
        return sign + pi_check(abs(float(self.__base)), **self.__options)
```

Inside `pi_check` we'd then do `expr.subs(sym, _PiCheckNumber(sym, kwargs)` for each numeric symbol, and finally just return `sympy.sstr(patched, ...)`, which will have `sympy` treat everything itself.

We can't add on a `_sympystr` method to the instances for two reasons: one, sympy likes to return immutable singletons, and if we modified it we'd mess everything up; two, `sympy.Number` has `__slots__`, so we can't add undefined methods anyway.

**Comment by jakelishman** [comment]
So after a little more playing, I came up with a fully working solution that's relatively elegant.  First, we make a dynamic wrapping class, so we can inherity _all_ behaviour from the input:
```python
def _wrap_sympy_number(symbol: "sympy.Number", options: dict) -> "_PiCheckNumber":
    """Return a wrapped version of a sympy number atom, which overrides the string-printing method
    into one which respects :obj:`.pi_check`.
    """
    # Derive from the exact type of the given symbol, so all `__eq__` methods, and so on get defined
    # in the expected manner.
    class _PiCheckNumber(type(symbol)):
        def __new__(cls, *_):
            # Intercept sympy's attempt to return a singleton instance.
            return object.__new__(cls)

        def __init__(self, base):
            self.__base = base

        def __getattr__(self, attr):
            # The only things in __dict__ are the functions we define locally; we preferentially
            # return those, and if that fails, then delegate to the wrapped object instead.
            try:
                return self.__dict__[attr]
            except KeyError:
                return getattr(self.__base, attr)

        def _sympystr(self, _printer):
            """Return a string, representing how this element should be printed by sstr.  This
            overrides sympy's normal methods for determining how to print an object."""
            sign = "-" if self.__base.is_negative else ""
            return sign + pi_check(abs(float(self.__base)), **options)

    return _PiCheckNumber(symbol)

```

Now inside `pi_check` the whole `ParameterExpression` branch is much simplified, and fully uses sympy's enginge to do the replacement:

```python
def pi_check(inpt, eps=1e-6, output="text", ndigits=5):
    ...
    if isinstance(inpt, ParameterExpression):
        if not hasattr(inpt._symbol_expr, "expr_free_symbols"):
            from sympy import sympify

            expr = sympify(inpt._symbol_expr)
        else:
            expr = inpt._symbol_expr
        syms = expr.expr_free_symbols
        kwargs = {"eps": eps, "output": output, "ndigits": ndigits}
        for sym in syms:
            if sym.is_number:
                expr = expr.subs(sym, _wrap_sympy_number(sym, kwargs))
        return str(expr)
    ...
```

Unlike the previous thing I wrote, this one correctly makes the object appear as a number to sympy, which means it organises it with respect to symbols correctly (e.g. `2*x` instead of `x*2`), and all the other niceties.  To re-use the same example as before, with this version:

```python
>>> from qiskit.circuit.tools import pi_check
>>> from qiskit.circuit import Parameter
>>> x = Parameter('x')
>>> expr = -1 - 10.1*x; expr
>>> pi_check(expr, eps=0.02)
'-10.1*x - 5π/16'
```

**Comment by enavarro51** [comment]
@jakelishman Thanks for the feedback. Considering that pi_check is only a method for taking a float and making it look better for visualization or in a qasm string, I'm not sure we need to overthink it. In your example, simply using eps = 1e-2 would be sufficient to return the original parameter string. I agree we should not allow eps to be too large, but that can be done by simply internally and in docs setting a limit on the size of eps, perhaps 1e-3 would be enough. I don't think we want users entering 3.1 and expecting to see pi displayed.

If there's more to it than that, I'm open to looking at a more general solution.

**Comment by jakelishman** [comment]
Actually, I noticed I got too deep into my method in the second step and somehow missed the fact that deriving from `sympy.Float` and family means that my `_sympystr` method never gets called at all!  So my example doesn't even solve the problem yours does, as it's written.

I think your patch solves the issue just fine, and my problem here is with the original method, not with your implementation.  Could you add a regression test to prevent this case from re-emerging?  Apologies for going off the deep end a bit here - I'm new to the team and codebase, and trying to learn about how everything works!

---

I think maybe you thought I was pointing out a slightly different problem - mine was that the string replacement is incorrect, not that the function _shouldn't_ replace the value `1` with a sufficiently high epsilon.

I still think that the correct way to do things is to patch the sympy printers, rather than trying to do regex replacement on a string, and hoping that there's never a collision.  My example was a simple contrived one to show the principle. It's easiest to see with a large `eps`, but I don't think that's the only case it'll work - it'll work with a value `eps=1e-3` and a value of 2:
```python
>>> from qiskit.circuit.tools import pi_check
>>> from qiskit.circuit import Parameter
>>> x = Parameter('x')
>>> n = 2
>>> expr = 2.01*x + 2
>>> pi_check(expr, eps=1e-3)
'7π/11.01*x + 7π/11'
```
I don't think `eps=1e-3` is an especially large value any more - we're getting close to being within hardware error on some hardware at this point. Further, it'll work with arbitrarily small epsilon if at any point `MAX_FRAC` is increased.  To take another extreme example, 1 is equal to `113/355 * pi` to within 1e-7, which means it would then get replaced at the default tolerance.

Another point is that this regex replacement method doesn't respect the `ndigits` argument to `pi_check` as it stands.  Assuming I could tweak my method to _actually_ override the print function, it would automatically treat those values the same way.

**Comment by enavarro51** [comment]
@jakelishman Thanks for your deep dive into this and you raise some important points. I think for now we're going to proceed with the simpler solution to fix this bug, but if you'd like to open a separate issue for doing a more serious refactor, it could be worthwhile.

**Review by jakelishman — APPROVED** [review]

**Comment by jakelishman** [comment]
I figured out how to patch the `sympy` printers in the end.  As you say, for a function like this, it's probably like swatting a fly with a rocket launcher, but I previously had no experience with sympy, and now I feel like I've got a pretty deep handle on a lot of its inner workings, so I definitely gained something!  I can make another PR/issue to discuss that.

If you have the power, you can add the relevant tags and whatnot for the merge.  I'm still only very new here, so it's better if someone who knows what they're doing makes sure I've not messed anything up or missed anything first.  If you've not got the power, I'll ask somebody tomorrow.

**Pull request merged**
