### PR TITLE
Reorganised algorithms.gradients

### PR DESCRIPTION
**Pull request by ica574**
Fixes issue #9695 by reorganising algorithms.gradients into separate folders.

### Summary
Reorganised algorithms.gradients as per issue #9695.

### Details and comments
Changed folder structure of algorithms.gradients, and collected files pertaining to base, finite_diff, lin_comb, param_shift, qgt, reverse, and spsa, into folders as per issue #9695. This also required that multiple files be refactored to reflect this change.

### CODE REVIEW

**Comment by woodsp-ibm** [comment]
@ica574 Docs is failing as follows:

`* ModuleNotFoundError: No module named 'qiskit.algorithms.gradients.base'`

The new folders should have `__init__.py` files in them. They can be empty - except that they need the standard copyright like what is in `reverse_gradient` folder for example.

----------------

@a-matsuo in the linked issue we has discussed this, which would affect the docstring in the algorithms init file that list them, i.e. new categories and ordering - I guess we still want this

> > In the gradients in the docstring the organization/presentation to the user is not the same as the above structure (has Estimator grads, Sampler grads and QGT) - would you change that too, to reflect this organization or not. It would not affect the code in any way just how they are grouped in the docs.
> 
> I hadn't thought of that. I think it's better to group by gradient type in the docs, too, if the file structures are so.

Also I note that the module is called `reverse_gradient` while the class name is ReverseEstimatorGradient. Most other module names have Estimator, Sampler etc in them. If I look at folders, like lin_comb, I can see the estimator and sampler modules and its clear.  If I look in reverse then by the module name it's unclear what reverse_gradient is and maybe its better if we are moving things around to call it reverse_estimator_gradient?

The `reverse_gradient` folder, now just seems to have a couple of utility modules in it. I imagine they should be moved along with the gradient module itself into the reverse folder (or more simply rename the original folder reverse). I think something is needed as there is both a `reverse` folder, containing the reverse_gradient module, and `reverse_gradient` folder now with what remains.

**Comment by a-matsuo** [comment]
Hi, @ica574 .  Thank you for working on this. Can you also modify the following things?
- Move `estimator_gradient_result.py` and `sampler gradient_result.py` into the `base` folder.
- Move `qgt_result.py` into the `qgt` folder.
- Make a folder for `qfi` and move related files into that.

**Comment by ica574** [comment]
I'm about to push another commit where I've added __init__.py files and took into consideration the comments by @a-matsuo and @woodsp-ibm. I have one suggestion, where it might be better if `reverse_qgt.py` is moved to the `reverse` folder. I'll amend this in another commit if needs be.

**Comment by a-matsuo** [comment]
@ica574 Thank you for the changes.  I think it's better to place  `reverse_qgt.py` to the `gpt` folder to make it easier for users to find all the GPT-related classes. This way, all the relevant files will be located in one place, and users won't have to search through multiple folders to locate them. (If we will have more gpt classes in the future, we might need to make subfolders in the `gpt` folder, but I think it's ok for now)

**Comment by ica574** [comment]
Apologies, I accidentally closed this request when trying to bring the branch up to date. I'll reopen a new one, and mention the original issue.

**Pull request closed without merging**
