### PR TITLE
Improve performance of _observable_key in Primitives

### PR DESCRIPTION
**Pull request by ikkoham**
### Summary

Since `to_list` is slow, this improves the performance issue.

Question:
Does this PR have `stable backport potential`?

### CODE REVIEW

**Comment by Cryoris** [comment]
If this is not a massive performance improvement, I would maybe not backport it as it changes the return type of `_observable_key`. If it's a big improvement and we could sell it as "performance bug", it might be ok as it's also an internal type, but I think it would definitely be more stable to not backport.

**Comment by t-imamichi** [comment]
Could you compare the performance with a typical VQE code or something?

**Comment by Cryoris** [comment]
On my laptop this PR gives a speedup of 5-6 times (2s vs 13s for 100'000 key generations), but I would assume that the key generation is a minor part in the whole stack, or isn't it?

**Comment by ikkoham** [comment]
Thank you.

Here is the benchmark of VQE (main thread)
Before this PR:
image
After this PR:
image

As you know, calculations outside of the main thread are so heavy, so a one second improvement here is not such a big improvement.
I'm fine with both.

**Review by Cryoris — APPROVED** [review]
LGTM, but probably not for backport as discussed above 🙂

**Pull request merged**
