### PR TITLE
Extended explanation from plot_bloch_multivector API reference

### PR DESCRIPTION
**Pull request by Guillermo-Mijares-Vilarino**
### Summary
Extended the explanation on the `plot_bloch_multivector` [API reference](https://qiskit.org/documentation/stubs/qiskit.visualization.plot_bloch_multivector.html#qiskit.visualization.plot_bloch_multivector).

### Details and comments
Explained with more detail what each component (x,y,z) of the Bloch sphere of each qubit actually means in terms of operators (expected value of the corresponding Pauli operator acting only on that particular qubit).

### CODE REVIEW

**Review by HuangJunye — COMMENTED** [review]
The explanation looks pretty good to me. Can you please also add similar explanations for [`plot_bloch_vector`](https://github.com/Qiskit/qiskit-terra/blob/f37dcf9d9c879867140b3072483a3dbd36cb5c1f/qiskit/visualization/state_visualization.py#L181) and [`Bloch`](https://github.com/Qiskit/qiskit-terra/blob/f37dcf9d9c879867140b3072483a3dbd36cb5c1f/qiskit/visualization/bloch.py#L94)?

**Comment by mtreinish** [comment]
The `Bloch` class isn't part of the documented API (it's also not re-exported as part of `qiskit.visualization`) so I think just updating `plot_bloch_vector` is enough.

**Comment by HuangJunye** [comment]
@mtreinish How do we check if a certain class is not documented (I guess you mean not built by sphinx)? For this specific case, it is probably not built by sphinx because it is not listed in `qiskit.visualization.__init__.py`. 

Another question is how to decide which classes to add to documentation. Should we only include classes and functions that "we" (as qiskit developers) think the users will use?

**Comment by mtreinish** [comment]
The only way to check is manual inspection or build the documentation and look. We are explicitly adding everything to the doc tree that is included through a combination of `autodoc` and `autosummary` directives. https://qiskit.org/documentation/maintainers_guide.html#documentation-structure explains the flow here. The only way to tell is to look at the autosummary directives which we put in module level docstrings (it's often easier to just do a doc build and see what gets included because there are a lot of modules we include in the documentation https://github.com/Qiskit/qiskit-terra/tree/main/docs/apidocs and having an indexed search is faster).

As for what we should put in there, yeah that's the basic rule of thumb. We include the documentation for things that we intend to be user facing to one degree or another. The `Bloch` class in this case is lower level than the intended user interface for the visualization module (it's also just a fork of QuTiP's bloch sphere visualization class) so we don't include it in the documentation.

**Comment by HuangJunye** [comment]
@Guillermo-Mijares-Vilarino Can you please make the changes as suggested? This is the only PR tagged with 0.21.2 milestone that are still open.

**Comment by Guillermo-Mijares-Vilarino** [comment]
Just changed the `plot_bloch_vector` explanation. Sorry for the delay 😅

**Review by HuangJunye — DISMISSED** [review]
LGTM. Thanks for adding the explanations.

**Review by jakelishman — APPROVED** [review]
I just pushed a commit to modify the LaTeX dots commands into `\dotsb` ([dots] between [b]inary operators) because they've got better kerning and are raised off the base-line, but no other changes.  I'm merging this now, and it'll get built into the new documentation when 0.21.2 goes out later today.

**Pull request merged**
