### PR TITLE
Making quantum_info and the states

### LINKED ISSUE #1194: Move tools.qi to a folder quantum_info
Move tools.qi to a foder quantum_info.

### LINKED ISSUE #1196: quantum state methods.
These include

basis_state
random_state
projector
state_fidelity

### PR DESCRIPTION
**Pull request by jaygambetta**
### Summary
Fixes #1196 
Fixes #1194

### CODE REVIEW

**Comment by jaygambetta** [comment]
@chriseclectic this is ready to start. I will slowly go through and move qi over.

**Comment by chriseclectic** [comment]
Should we make the `states` a subpackage for organization, and the inside have
- `states.py` for functions that return common states like basis states, random states etc
- `measures.py` for all the measures/quantities like fidelity, purity, entropy, entanglement etc
- `operations.py` for things like partial trace, projector, outer, vectorize etc
and then use the `states.__init__.py` to import all the functions we want exposed in `qi.states`

**Comment by jaygambetta** [comment]
I don't think there will be enough measures lets just keep it states and operations.

**Comment by jaygambetta** [comment]
@chriseclectic should be done.

**Comment by chriseclectic** [comment]
I can't officially review but I Approve if someone can merge this

**Comment by yaelbh** [comment]
See a relevant pull request from qiskit-aer:
https://github.ibm.com/IBMQuantum/qiskit-aer/pull/88

This pull request contains a file named ``qstructs.py``, with stuff that can be imported to Terra:
https://github.ibm.com/YAELBH/qiskit-aer/blob/1ef4042275eb63154ae4a7642346dc97b34e42a4/test/terra/validate_against_density_matrix_simulator/qstructs.py

**Pull request merged**
