### PR TITLE
Add plugin interface for external provider registration

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

This commit adds a simple and standardized interface for external
plugins to register providers and have them work natively off of the
qiskit namespace. With this anyone can setup providers to be
discoverable and automatically loaded into qiskit-terra if they're
installed. It leverages setuptools entry points to define an entry point
to basically advertise to terra that a python package provides a
backend provider. Terra now leverages the stevedore library (which just
provides a useful API ontop of entrypoints and plugins) to discover
the providers installed.

### CODE REVIEW

**Comment by ewinston** [comment]
How does stevedore support prospective qiskit plugins that can't be done with builtin methods, e.g. setuptools entry_points, which it is built upon?

**Comment by mtreinish** [comment]
The stevedore bit is just for discovery of plugins that advertise themselves as such using entry_points. If a plugin doesn't expose the entry point at install time stevedore won't do anything with it (since it won't see it). If a plugin can't use entry_points for some reasons it'll still work like things already do today where you have to manually import the plugin from wherever and access it directly (like in the case of JKU you would use `from qiskit_jku_provider import JKUProvider` still if it couldn't use entrypoints). This patch is only about simplifying the discovery of provider plugins and standardizing how users can interact with them, it doesn't really change anything in the plugins themselves.

**Comment by ewinston** [comment]
My understanding was that setuptools already does discovery of plugins,
https://packaging.python.org/guides/creating-and-discovering-plugins/#using-package-metadata?

**Comment by mtreinish** [comment]
@ewinston yeah, stevedore is just using that under the covers. It provides a nicer api to work with than the raw setuptools.

**Comment by ajavadia** [comment]
So with this patch, the only difference would be that the user writes:
```from qiskit import JKUProvider```
instead of
```from jku_provider import JKUProvider```?

Not sure if that's desired. Wouldn't it somehow imply that JKUProvider belongs to qiskit, rather than being clearly a 3rd party installed package?
Also it really relies on that package doing this thing in its `setup`. So we may end up with an inconsistent situation where some providers are in the qiskit namespace and some are not, which we won't be able to control

**Comment by mtreinish** [comment]
@ajavadia Well it's actually from `qiskit.providers import JKUProvider`, the original patch I had did it `from qiskit import JKUProvider` but the intent there was for Aer and IBMQ to use this which we don't need anymore. I switched it to try and outline that exact difference of this being a 3rd party provider, not an in-repo thing. So the 1st party providers that we support (Aer, BasicAer, and IBMQ) are all accessed off of `qiskit.*` and then the 3rd party ones which we don't support are all accessed off of `qiskit.providers.*`. I can easily change that path to be something else to try and highlight that difference more though, it's very straightforward.

As for some providers using vs not, it's true we can only provide the interface but not force an external provider to use. But, I figure if we clearly document it and the benefits of using it people will start to adopt it, but we can't force anyone to use it. Just like we can't really force anyone to inherit from our abstract provider classes today.

**Comment by ajavadia** [comment]
So if the 3rd party provider just does a directory reorganization and puts their code under 
`qiskit/providers/third_party` (like Aer does at the moment), would that solve the problem?

**Comment by mtreinish** [comment]
Yeah, I wrote this before the docs migration. I left it in the PR because it helps explain what the patch does. I will remove it from this PR an open up a docs one when we're ready to merge this.

**Comment by ajavadia** [comment]
@mtreinish can you address my comment above? I'm not sure that what a backend developer has to do here is different from just organizing their namespace under `qiskit/providers`, like Aer does.

**Comment by mtreinish** [comment]
> @mtreinish can you address my comment above? I'm not sure that what a backend developer has to do here is different from just organizing their namespace under `qiskit/providers`, like Aer does.

This actually isn't a solution for third party providers. Having external provider isn't something I would recommend generally, mostly because it is confusing to have an import from qiskit that isn't maintained by a qiskit project. There are also edge cases with namespace packages which we can workaround by maintaining the projects by the same people. I'm not really comfortable encouraging external projects using that mechanism.

But even ignoring all of that, simply moving code to `qiskit/providers` isn't actually a solution. The way providers are used it's a global instance of the provider class. So when you call `qiskit.Aer` it's actually an object not the class and we need to instantiate it. For example for, Aer we do this in Terra here: https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/__init__.py#L45-L48

This plugin provider makes the namespaces for external code live outside of `qiskit.*` and it provides a common interface for plugin authors to advertise that they have a provider for qiskit users. Then users have a single place they can access those instantiated Provider objects. Right now it's off of `qiskit.providers` but we can move that somewhere else, like `qiskit.providers.plugins` or `qiskit.providers.external`.

If you'd like I can write an example patch for JKU or another provider, or I can just write a fake provider plugin example to show how this works.

**Comment by mtreinish** [comment]
I moved the docs from here to the qiskit repo in: https://github.com/Qiskit/qiskit/pull/190

**Comment by ajavadia** [comment]
closing this until there's a clear use case for doing this (i.e. there is complaint about 3rd party provider being hard to use under its own namespace). I think there is value in the qisksit namespace being preserved for things we provide.

**Pull request closed without merging**
