### PR TITLE
Allow multiplication of SparsePauliOp and ParameterExpression

### PR DESCRIPTION
**Pull request by SimoneGasperini**
### Summary
Fix issue #10185 relying on the already implemented and tested method `SparsePauliOp._multiply`.

### CODE REVIEW

**Comment by SimoneGasperini** [comment]
Thank you @woodsp-ibm for the suggestions. Should I write a separate testing function for this or add it to the current `TestSparsePauliOpMethods.test_mul` method in [`test_sparse_pauli_op.py`](https://github.com/Qiskit/qiskit-terra/blob/main/test/python/quantum_info/operators/symplectic/test_sparse_pauli_op.py)?

**Comment by woodsp-ibm** [comment]
If adding new parameterexpression value(s) to the current test works out with the current code then that would be ok. It already deals with a param and having that now as value I do not know how well things would fit to the code given how you might want/need to check the outcome. If it turns out better to be a separate test, save complicating what's there, I think that's fine.

**Review by ikkoham — COMMENTED** [review]
Thank you for the PR. Agree with @woodsp-ibm, it needs some tests. The dtype of the coeffs must be handled carefully.

**Comment by SimoneGasperini** [comment]
Thank you again for the feedback. I added the test and the release note.
Honestly, I don't understand why some tests are still failing (they don't look related to this).

**Comment by SimoneGasperini** [comment]
Thank you again for the feedback. I added the tests and the release note.
Some tests are still failing but they look related to the other changes from the 'main' branch. Maybe I shouldn't have merged it to my feature branch (apologies, I'm just at the beginning of my experience as an open-source contributor).

**Comment by woodsp-ibm** [comment]
Hi, as far as the test failure sometimes other changes affect things - in this case its failing due to a change in newly released qiskit aer - #10270 addresses this so after thats merged and your branch is updated to include it then things should be ok.

**Comment by SimoneGasperini** [comment]
@ikkoham @woodsp-ibm Anything still missing? I updated the branch and now all the checks are successful.

**Review by ikkoham — APPROVED** [review]
Thank you for adding tests and a release note. LGTM!

**Pull request merged**
