### PR TITLE
Update BarrierBeforeFinalMeasures to preserve existing barriers

### LINKED ISSUE #1709: Transpiler reorders measure through barriers
### Informations

- **Qiskit Terra version**: master
- **Python version**: 3.6
- **Operating system**: MacOS

### What is the current behavior?

A recent merge into master (I think probably #1705) is `qiskit-aer` master to fail because it reorders measurements past barriers.

### Steps to reproduce the problem

One of the Aer tests is a non-local measure noise: if I measure qubit 0, apply a noise operator on qubit 1. To test this the circuit has to ensure measure of qubit 0 happens before measure of qubit 1 and looks like

```
qr = QuantumRegister(2)
cr = ClassicalRegister(2)
circ = QuantumCircuit(qr, cr)
circ.measure(qr[0], cr[0])
circ.barrier(qr)
circ.measure(qr[1], cr[1])
```

Before this would ensure the output qobj had instructions:

```
[QobjInstruction(memory=[0], name='measure', qubits=[0]),
 QobjInstruction(memory=[1], name='measure', qubits=[1])]
```

But now it reorders the measures past the barrier returning:
```
[QobjInstruction(memory=[1], name='measure', qubits=[1]),
 QobjInstruction(memory=[0], name='measure', qubits=[0])]
```

### What is the expected behavior?

Measure instructions should respect barrier placement

### PR DESCRIPTION
**Pull request by kdk**
Fixes #1709 by including barriers as ops to be re-inserted in the DAG after the new barrier. Also, removes the existing logic to consolidate barriers (this can be re-added, but probably as a separate pass).

### CODE REVIEW

**Comment by ajavadia** [comment]
The code and tests look good. 

However, I think there are cases when the new barrier is not *exactly* equivalent to an existing barrier, but still redundant.

For example, with your code, this circuit:
image

will get turned into:
image

But the new barrier is a subset of the old barrier, so it doesn't need to be inserted. 

I think we should not insert a new barrier if an already stronger barrier exists.
And if we are inserting a stronger barrier, then the old one should be removed.

**Comment by ajavadia** [comment]
@kdk I see you made some changes. The example I pointed out is fixed now. So is this PR ready to be reviewed/merged now?

**Comment by kdk** [comment]
This is ready to merge.

**Comment by ajavadia** [comment]
Awesome, thanks.

**Pull request merged**
