### PR TITLE
Improve the performance of AerExpectationValue

### LINKED ISSUE #5744: Unused measurement gates in VQE circuits
### Information

- **Qiskit Aqua version**: master
- **Python version**: 3.8.1
- **Operating system**: Linux

### What is the current behavior?

Running VQE with Aer Pauli expectation, the circuit that's sent to the simulator measures all the qubits. While the measurement results are not used, they may affect performance.

Specifically, they are not so expensive for the statevector simulator: one more loop over the basis states - the cost is equal to the cost of one gate - regardless of the number of shots. However, the MPS simulator is sensitive to the number of shots.

Here are run times in seconds of one simulation of a 20-qubits circuit (output of the two simulators is the same):

shots | statevector | MPS
------ | ------------ | -----
0 (no measurements) | 7.6 | 0.78
1 | 7.6 | 0.78
1024 (default) | 7.3| 2.6
10000 | 7.7 | 19

### Suggested solutions

Remove the unused measurement gates.

### PR DESCRIPTION
**Pull request by ikkoham**
### Summary

Remove unnecessary measurements.
This resolves  #5744.

### Details and comments

Benchmark:

VQE, H2, ParityMapper, UCCSD, qasm_simulator,  shots=1000000, SLSQP

Main: 0167c156d2e2c929fd9041ef75762905ae826ccc

30 sec

image

This PR:
2 sec

image

### CODE REVIEW

**Comment by ikkoham** [comment]
@Qiskit/terra-core Could you add label, mod:opflow and performance?

(I want to add the labels by myself...)

**Comment by woodsp-ibm** [comment]
@ikkoham 

> (I want to add the labels by myself...)

You need to ask for write access to the repo to be able to add them etc - it seems you do not have that.

**Comment by woodsp-ibm** [comment]
Does this also end up addressing #5744 such that it can finally be fixed/closed?

**Comment by ikkoham** [comment]
@woodsp-ibm Thanks. I will ask it to the code owner.

> Does this also end up addressing #5744 such that it can finally be fixed/closed?

Thanks again. I forgot to link the issue.

**Review by woodsp-ibm — APPROVED** [review]

**Pull request merged**
