### PR TITLE
Fixes issue #7296 by adding a new transformation pass 

### PR DESCRIPTION
**Pull request by TheGupta2012**
### Summary
Fixes issue #7296 by adding a new transformation pass in the transpiler

### Details and comments
- Issue #7296 suggests adding the `InverseCancellation` pass to the preset passmanagers to cater to the example presented in the issue.
- This PR tries to solve the problem by incorporating that pass with a small change in the way back to back gates are eliminated by the `InverseCancellation` pass. 
- Essentially swap gates are symmetric in the sense of their qubit arguments. One of the conditions which `InverseCancellation` pass checked during optimization was to assert that the qargs were same ([here](https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/transpiler/passes/optimization/inverse_cancellation.py#L102)). This did not allow optimization for the case when two consecutive swaps were present on the same *set* of qubits {0,1} but not the same list ( ex. (0,1) and (1,0) as qargs were treated differently when in case of swaps, the order does not matter ).
- This could be extended to a more general set of symmetric gates but for now the functionality for swap gates is added. 
- Each transpiler level > 0 now optmizes the case mentioned in the issue correctly - 
```
from qiskit import QuantumCircuit, transpile 

qc = QuantumCircuit(3)
# same qargs
qc.swap(0,1)
qc.swap(0,1)
qc.x(2)
#different qargs
qc.swap(2,1)
qc.swap(1,2)
qc.h([0,1])

for level in range(1,4):
    tqc = transpile(qc, optimization_level = level)
    assert("swap"not in tqc.count_ops().keys())
print("Correct.")
```
with the output - 
```
Original :
             ┌───┐        
q_0: ──X───X─┤ H ├────────
       │   │ └───┘   ┌───┐
q_1: ──X───X───X───X─┤ H ├
     ┌───┐     │   │ └───┘
q_2: ┤ X ├─────X───X──────
     └───┘                
Level 1 : 

     ┌───┐
q_0: ┤ H ├
     ├───┤
q_1: ┤ H ├
     ├───┤
q_2: ┤ X ├
     └───┘
Level 2 : 

     ┌───┐
q_0: ┤ H ├
     ├───┤
q_1: ┤ H ├
     ├───┤
q_2: ┤ X ├
     └───┘
Level 3 : 

     ┌───┐
q_0: ┤ H ├
     ├───┤
q_1: ┤ H ├
     ├───┤
q_2: ┤ X ├
     └───┘
Correct.

```
- I see this to be added as a feature to the `InverseCancellation` pass eventually but for now, the functionality is added to a separate class.

### CODE REVIEW

**Review by kdk — COMMENTED** [review]
Thanks for taking this on @TheGupta2012 !

Rather than adding a new pass for this case, I wonder if we can extend `InverseCancellation` to cover it. (This would reduce some duplication in the code, and also be marginally faster, in that we'd only need to scan the DAG once.)

Ideally, we should be able to annotate a gate type or instance as being `"qarg_symmetric"` (along the lines of the `num_params` attribute in https://github.com/Qiskit/qiskit-terra/pull/6883 ). Possibly this is something we could look into integrating in the future with the `Operation` base class ( @ShellyGarion @alexanderivrii thoughts? ), but for now, maybe we can incorporate this as an additional field/annotation in the `gates_to_cancel` list.

I'm not tied to this approach, because it seems to add a lot of complexity to unpacking `gates_to_cancel`, so happy to hear other ideas!

**Comment by ShellyGarion** [comment]
@kdk - following your comment,  it seems that an `Operation` level `"qarg_symmetric"` attribute is not an optimal solution as it may be relevant to only a small subset of the cases. 
`"qarg-symmetric"` makes sense as a class-level attribute for some basic gates (e.g. `SWAP`, `CZ`, `CCX`) and `MCX`, however, for more general gates it may depend on the specific gate instance parameters. For other Operations `"qarg-symmetric"` is not really applicable, either since it's meaningless (e.g. `Barrier, Reset, Measure` ) or the symmetry is difficult to compute.

**Comment by ajavadia** [comment]
I think symmetric cancellation is not the right approach. Symmetric gates don't always cancel, e.g. ZZ(theta). I am also not a fan of the InverseCancellation pass because it is very limited. 

All of these are special cases of the `TemplateOptimization` pass which we already have. And we have a lot of templates defined in `qiskit.circuit.library`. If you could incorporate that into the preset passmanagers, then it would eliminate the need for both this pass and the `InverseCancellation` pass. For example this particular template is under `qiskit/circuit/library/templates/clifford/clifford_2_4.py`.

It just needs a bit of experimentation with what templates to include in what optimization level. Matching 2-qubit templates should be trivial and we can include in level 1. Matching them gets slower for larger templates.

Also as I commented on the original issue this can be resolved by providing a basis to the transpiler (which is not too difficult). But anyway, without the basis, template optimization is the way to go I think.

**Comment by ajavadia** [comment]
To clarify what I mean, here's how to optimize the circuit with current passes in qiskit. It's just not in any of the preset passmanagers, because you have to provide a list of known templates to search over. As I said this requires a bit of profiling to see which ones make sense to include at which level, but these are all well-known templates.

```py
from qiskit import QuantumCircuit
from qiskit.circuit.library.templates import clifford_2_4
from qiskit.transpiler import PassManager
from qiskit.transpiler.passes import TemplateOptimization
from qiskit import transpile

circuit = QuantumCircuit(2)
circuit.swap(0,1)
circuit.swap(0,1)
circuit.h(0)
print(circuit)

t1 = clifford_2_4()
pass_ = TemplateOptimization(template_list=[t1])
pm = PassManager(pass_)
print(pm.run(circuit))
```

**Comment by javabster** [comment]
hi @TheGupta2012 are you still working on this?

**Pull request closed without merging**
