### PR TITLE
Latex dawer supports custom instructions containing classical register

### LINKED ISSUE #3202: Latex drawer support for complex custom instructions
The following circuit is being draw like wrongly:
```python
from qiskit.circuit import Gate, Parameter
qinst = QuantumRegister(1, 'q')
cinst = ClassicalRegister(1, 'c')

inst = QuantumCircuit(qinst, cinst, name='instruction').to_instruction()

qr = QuantumRegister(2, 'q')
cr = ClassicalRegister(2, 'c')
circuit = QuantumCircuit(qr, cr)
circuit.append(inst, [qr[0]], [cr[1]])
circuit.draw(output='latex')
```
image

It should be similar to this:
Considering the following custom instruction:
```
        ┌─────────────┐            
q_0: |0>┤1            ├            
        │             │            
q_1: |0>┤             ├            
        │ instruction │            
 c_0: 0 ╡             ╞            
        │             │            
 c_1: 0 ╡0            ╞            
        └─────────────┘
```

Additionally, based on the consensus in #3073, the mpl drawer should support controlled/conditional custom instructions. The following is an example for conditional:
```
from qiskit.circuit import Gate, Parameter
qinst = QuantumRegister(1, 'q')
cinst = ClassicalRegister(1, 'c')

inst = QuantumCircuit(qinst, cinst, name='instruction').to_instruction()

qr = QuantumRegister(2, 'q')
cr = ClassicalRegister(2, 'c')
circuit = QuantumCircuit(qr, cr)
circuit.append(inst, [qr[0]], [cr[1]]).c_if(cr, 2)
circuit.draw(output='latex')
```

Controlled is not yet supported (see #2862).

### LINKED ISSUE #4421: Error in drawing classical controlled custom instructions in latex drawer
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?

Classical controlled custom instructions which act on two or three qubits are improperly drawn by latex drawer as below:

test_1

### Steps to reproduce the problem

```
qinst = QuantumRegister(2, 'q')
cinst = ClassicalRegister(1, 'c')

inst = QuantumCircuit(qinst, cinst, name='instruction').to_instruction()

qr = QuantumRegister(3, 'q')
cr = ClassicalRegister(2, 'c')
circuit = QuantumCircuit(qr, cr)
circuit.append(inst, qr[0:2], [cr[1]]).c_if(cr,2)
circuit.draw(output='latex')
```

### PR DESCRIPTION
**Pull request by TharrmashasthaPV**
### Summary

Fixes #3202 .
Fixes #4421 .

### Details and comments

Custom instructions containing classical registers are now drawn correctly by extending the instruction box to the classical bit in latex drawer. The missing instruction boxes for instructions containing 2 or 3 qubits and missing classical control wires as reported in #4421 have been corrected. An example circuit is as below:

fc_1

fc_2

### CODE REVIEW

**Comment by 1ucian0** [comment]
Thanks for your patience with this PR @TharrmashasthaPV . Do you mind having a look to the current conflicts? Also, adding testing would be great. I will have a deeper look the coming days.

**Comment by TharrmashasthaPV** [comment]
> 
> 
> Thanks for your patience with this PR @TharrmashasthaPV . Do you mind having a look to the current conflicts? Also, adding testing would be great. I will have a deeper look the coming days.

Sure, I will work on it.

**Comment by 1ucian0** [comment]
I think just extending the boxes creates some ambiguities. Consider these two situations:
```python
qinst = QuantumRegister(1, 'q')
cinst = ClassicalRegister(1, 'c')

inst = QuantumCircuit(qinst, cinst, name='instruction').to_instruction()

qr = QuantumRegister(2, 'q')
cr = ClassicalRegister(2, 'c')
circuit = QuantumCircuit(qr, cr)
circuit.append(inst, [qr[0]], [cr[1]])
```
```python
qinst = QuantumRegister(2, 'q')
cinst = ClassicalRegister(2, 'c')

inst = QuantumCircuit(qinst, cinst, name='instruction').to_instruction()

qr = QuantumRegister(2, 'q')
cr = ClassicalRegister(2, 'c')
circuit = QuantumCircuit(qr, cr)
circuit.append(inst, [qr[0], qr[1]], [cr[0], cr[1]])
```
Both instructions are having the same following representation while being very different:
image

Is it possible to have number in the box like with `text` or `mpl`?
```
     ┌──────────────┐
q_0: ┤0             ├
     │              │
q_1: ┤              ├
     │  instruction │
c_0: ╡              ╞
     │              │
c_1: ╡0             ╞
     └──────────────┘
```
```
     ┌──────────────┐
q_0: ┤0             ├
     │              │
q_1: ┤1             ├
     │  instruction │
c_0: ╡0             ╞
     │              │
c_1: ╡1             ╞
     └──────────────┘
```

**Comment by enavarro51** [comment]
Actually all the multiqubit gates in the latex drawer should have wire numbers added.

**Comment by 1ucian0** [comment]
Okey.. this latex is not elegant. But it gets close to a reasonable solution:
```
\begin{equation*}
\Qcircuit @C=1em @R=.7em {
& \rstick{^{^1}} & \multigate{2}{inst} & \qw \\
& \rstick{} & \ghost{inst}& \qw \\
& \rstick{^{^2}} & \ghost{inst} & \qw
}
\end{equation*}
```
Screen Shot 2020-09-15 at 10 37 49 PM

**Comment by enavarro51** [comment]
This works as long as there are no spacing issues between gates. Probably would be better inside the box, but don't know if that really matters.

**Comment by 1ucian0** [comment]
It's very limited what it can be done with [qcircuit](https://ctan.org/tex-archive/graphics/qcircuit?lang=en). Any other hack is welcomed!

**Comment by 1ucian0** [comment]
ping @TharrmashasthaPV?

**Comment by 1ucian0** [comment]
Closing this as stalled. @TharrmashasthaPV feel free to reopen if you are back!

**Comment by TharrmashasthaPV** [comment]
> 
> 
> Seems like spacing is handled well:
> 
> ```
> \begin{equation*}
> \Qcircuit @C=1em @R=.7em {
> & \gate{H} & \rstick{^{^1}} \qw  & \multigate{2}{inst} & \qw \\
> & \gate{H} & \rstick{} \qw & \ghost{inst}& \qw \\
> & \cw & \rstick{^{^{0}}} \cw & \cghost{inst} & \cw \\
> }
> \end{equation*}
> ```
> 
> Screen Shot 2020-09-16 at 5 09 55 PM
> 
> It's very limited what it can be done with [qcircuit](https://ctan.org/tex-archive/graphics/qcircuit?lang=en). Any other hack is welcomed!

Hi @1ucian0 .  I understand that this is a good way to represent the wire numbers. But another trouble is representing the wire numbers if two or more classical bits are in the instruction. Visualizing this in text does not become a problem because each classical wire is drawn separately in text visualization. But in latex and mpl, all the classical bits are just represented using a single classical wire. So do you have any suggestions?

**Pull request closed without merging**
