### PR TITLE
Add cross-build wheel jobs for ppc64le and s390x

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

This commit adds a new CI job at release time to build precompiled
binaries for s390x and ppc64le linux platforms.  These platforms do not
have precompiled wheels for any upstream dependencies (except for
retworkx and tweedledum, which both publish binaries for both platforms).
Since the only publically available CI service that has native s390x and
ppc64le environments available is travis which doesn't provide
sufficient quota to open source projects anymore to make it usable we
have to rely on either cross compilation or emulation. Cross compiling
with python wheels while possible is quite tricky to setup and configure
in practice so emulation is used here. This is a much simpler path
configure, especially because cibuildwheel has support for emulating
non-x86 architectures via QEMU to build wheels. While QEMU emulation of
other architectures is exceedingly slow, we have a 6 hour job time limit
with github actions which should hopefully be sufficient to compile the
binary and build wheels for all our supported python versions.

This was previously attempted in #5844 but we hit a timout issue
reliably every time trying to build scipy from source. Compiling scipy
is slow on a native system and it's an order of magnitude slower under
qemu emulation. In #5844 we exceeded the 6 hour job time limit just
compiling scipy once for testing. To avoid this issue (since scipy
doesn't publish s390x or ppc64le wheels) this commit skips the test
runs on these jobs. This means we're solely building the wheels and not
testing if they're valid. This also means installing scipy and other
dependencies is still an exercise for the s390x and ppc64le users. But,
if this works it will mean that at least for Qiskit there will not be a
need to compile anything from source.

### Details and comments

### CODE REVIEW

**Comment by mtreinish** [comment]
Ci worked, you can see the logs (and download the wheels) from here: https://github.com/Qiskit/qiskit-terra/actions/runs/1724756938

I'll spin up an s390x vm in a bit to test the wheel works

**Review by jakelishman — COMMENTED** [review]
In principle this looks good to me, but I don't really have the experience with virtualisation to meaningfully test the output wheels (nor the right software on my laptop, as far as I know!).

Do we want a release note to talk about the new wheels?

**Comment by mtreinish** [comment]
> In principle this looks good to me, but I don't really have the experience with virtualisation to meaningfully test the output wheels (nor the right software on my laptop, as far as I know!).

You could install QEMU locally for emulation like we do in CI to build these but I don't really recommend this as it's super slow. I normally test s390x via the LinuxONE community cloud which let you provision s390x VMs for open source work:

https://developer.ibm.com/gettingstarted/ibm-linuxone/

(my account was stale so I'm waiting on a new one to be provisioned now). For ppc64le I don't have a good test mechanism short of knowing someone with a server.

> 
> Do we want a release note to talk about the new wheels?

Yeah a release note is a good call, I'll add one in a bit.

**Review by jakelishman — APPROVED** [review]

**Comment by jakelishman** [comment]
Approved, provided you're happy with your latest VM tests.  It might not worth backporting this to 0.19.2, unless you reckon it'd be good to do a test release with the new platforms before the next minor.

**Comment by mtreinish** [comment]
I've tested this on s390x (with the python 3.8 wheel) and it works fine (after compiling numpy and scipy from source):

```
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.processor()
's390x'
>>> import qiskit
>>> qiskit.__version__
'0.20.0'
>>> qc = qiskit.QuantumCircuit(2)
>>> qc.h(0)
<qiskit.circuit.instructionset.InstructionSet object at 0x3ff7e6bc080>
>>> qc.cx(0, 1)
<qiskit.circuit.instructionset.InstructionSet object at 0x3ff7e6bc340>
>>> qc.measure_all()
>>> from qiskit.test.mock import FakeRome
>>> print(qiskit.execute(qc, FakeRome()).result().get_counts())
/home/linux1/test_wheels/lib/python3.8/site-packages/qiskit/test/mock/fake_backend.py:156: RuntimeWarning: Aer not found using BasicAer and no noise
  warnings.warn("Aer not found using BasicAer and no noise", RuntimeWarning)
{'11': 521, '00': 503}
```

**Comment by mtreinish** [comment]
> Approved, provided you're happy with your latest VM tests. It might not worth backporting this to 0.19.2, unless you reckon it'd be good to do a test release with the new platforms before the next minor.

Yeah, I think we can just hold this until 0.20.0. There's no pressing need here. It's not like either of these platforms have a lot of users. Looking at the CPU stats from PyPI over the last 30 days:

```
| cpu      | download_count |
| -------- | -------------- |
| x86_64   |         52,446 |
| None     |         25,158 |
| AMD64    |          9,037 |
| arm64    |            465 |
| aarch64  |            198 |
| armv7l   |            138 |
| i686     |            136 |
| s390x    |             58 |
| iPad13,4 |             24 |
| iPad8,5  |             20 |
| Total    |         87,680 |
```

s390x clients are only 0.06% of our downloads and 0 ppc64le downloads.

**Comment by hhorii** [comment]
I've tested this on ppc64le (with python 3.7, 3.8, and 3.9) and they work fined.
```
$ python
Python 3.7.11 (default, Jul 27 2021, 15:02:35) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.processor()
'ppc64le'
>>> import qiskit
>>> qiskit.__version__
'0.20.0'
>>> qc = qiskit.QuantumCircuit(2)
>>> qc.h(0)
<qiskit.circuit.instructionset.InstructionSet object at 0x7dd35f50caa0>
>>> qc.cx(0, 1)
<qiskit.circuit.instructionset.InstructionSet object at 0x7dd35f50cdc0>
>>> qc.measure_all()
>>> from qiskit.test.mock import FakeRome
>>> print(qiskit.execute(qc, FakeRome()).result().get_counts())
/home/hhorii/anaconda3/envs/qiskit202201_3.7/lib/python3.7/site-packages/qiskit/test/mock/fake_backend.py:156: RuntimeWarning: Aer not found using BasicAer and no noise
  warnings.warn("Aer not found using BasicAer and no noise", RuntimeWarning)
{'00': 502, '11': 522}
```

**Pull request merged**
