### PR TITLE
Add documentation to predecessor function

### PR DESCRIPTION
**Pull request by ElisaGarijo**
### Summary
ISSUE #2207 New documenation in the predecessor function

### Details and comments
Resolution for issue #2207 in relation with list order is resolved with documentation in the API

### CODE REVIEW

**Comment by kdk** [comment]
Hi @ElisaGarijo , thanks for looking into this! One small comment, can you update the docstring to say that `DAGCircuit.predecessors` returns an `iterator`, not a `list`?

**Comment by ElisaGarijo** [comment]
> Hi @ElisaGarijo , thanks for looking into this! One small comment, can you update the docstring to say that `DAGCircuit.predecessors` returns an `iterator`, not a `list`?
It is  good clarification but  Let me verify it before to update.

**Comment by 1ucian0** [comment]
No need to close the PR. You can modify your branch and the change will update this PR. Reopening.

**Comment by ajavadia** [comment]
@ElisaGarijo is this still on your radar?

**Comment by 1ucian0** [comment]
I think will take over this one @ajavadia

**Pull request closed without merging**
