### PR TITLE
Fixes 3684 - MPL drawer renders cU1 gate correctly

### LINKED ISSUE #3684: MPL drawer CU1 gate is inconsistent with other drawers
### Information

- **Qiskit Terra version**: 0.11.0
- **Python version**: 3.7
- **Operating system**: Mac OS 10.15.1

### What is the current behavior?
```
circuit = QuantumCircuit(2)
theta = numpy.pi/2
circuit.cu1(theta,0,1)
circuit.draw()
```
Output-
```            
q_0: |0>─■─────
         │pi/2 
q_1: |0>─■─────
```
However, mpl shows fine-
image

### Steps to reproduce the problem
Paste the above code in Jupyter notebook and run.

### What is the expected behavior?
The text drawer should show up like this-
```            
q_0: |0>─────■──────
        ┌────┴─────┐
q_1: |0>┤ U1(pi/2) ├
        └──────────┘
```

### Suggested solutions

Fix is provided below in the PR by making changes in qiskit/visualization/text.py

### PR DESCRIPTION
**Pull request by sumitpuri**
Fixes #3684

### Summary
The MPL drawer for cU1 gate is now displayed correctly.

### Details and comments

The MPL drawer did not render the cU1 gate as expected. This PR fixes the issue reported in #3684.

### CODE REVIEW

**Comment by sumitpuri** [comment]
@1ucian0 Did you get a chance to take a look at this PR?

**Comment by 1ucian0** [comment]
This PR seems on top of #3683. So let's merge that one first.

**Comment by sumitpuri** [comment]
@1ucian0 PR #3683 was merged, I think we are ready to merge this as well.

**Comment by 1ucian0** [comment]
There are some conflicts now. Probably you can just merge the branch from #3683 to this one for fixing them.

**Comment by sumitpuri** [comment]
@1ucian0 I have merged the branches, can you please try again.

**Comment by sumitpuri** [comment]
Hi @1ucian0 did you get a chance to take a look at this if it is ready to be merged?

**Comment by 1ucian0** [comment]
There are some docstring changes that seems coming from #3683, are you sure the merge was correct?

**Comment by 1ucian0** [comment]
> There are some docstring changes that seems coming from #3683, are you sure the merge was correct?

It seems it was just out of sync with master. done.

**Pull request merged**
