### PR TITLE
Remove legacy C++ simulator code

### PR DESCRIPTION
**Pull request by chriseclectic**
### Summary

Removes the `src` directory containing the legacy C++ simulator now that Qiskit-Aer is released.

### Details and comments

* Removes the `src` directory
* Attempts to update `.travis.yml` to not build anymore (please check/fix this @atilag or @diego-plan9 )
* renames legacy simulator tests to aer_provider_tests
* renames `requires_cpp_simulator` test decorator to `requires_aer_provider`

### CODE REVIEW

**Comment by mtreinish** [comment]
I think we probably can get away with removing cmake completely since it doesn't really add anything if we're sticking to just python code in terra, and will just make things more confusing. We'll still keep the makefile for running tests (since people are used to it as a local command) but the cmake stuff is there to facilitate building the c++ code and integrating that with the python.

**Comment by chriseclectic** [comment]
I think I've done about all I can... need someone more familiar with the build/install to double check and fix up make/cmake/setup/pypi/travis etc

**Comment by atilag** [comment]
I got this!

**Comment by mtreinish** [comment]
@atilag Oh I didn't see you're comment and went through and cleaned things up a bit more with: https://github.com/Qiskit/qiskit-terra/pull/1644/commits/890fd30a751f6cecfeaa285f2bb79aa3995dab81. But if I missed something (or more likely made a typo and broke everything) feel free to push on top and fix things

**Comment by atilag** [comment]
Na, it's fine! I'll take a look tomorrow

**Pull request merged**
