### PR TITLE
Fix issue #3951

### PR DESCRIPTION
**Pull request by javabster**
### Summary

This is a WIP, addressing issue #3951

### CODE REVIEW

**Comment by javabster** [comment]
@taalexander based on your comment in the issue I've attempted to write a hash test in test_channels.py. Was this the kind of test you were describing? And would I do the same kind of test for every channel type? I've only written one test so far, just want to check I'm on the right track before writing all the rest :)

**Comment by taalexander** [comment]
Hi Abby, I think what you have added so far looks good. Unfortunately, it was added to the deprecated `Commands` which have since been merged into `Instructions` in `qiskit.pulse.instructions` if you could move your hashing modification there it would be great. I hope its not too much trouble :(

**Comment by lcapelluto** [comment]
@javabster one thing I recently discovered about the built in `hash` method is that it is not deterministic. It was returning the same hash for one object, but the initializing the same type with the same args was giving a different hash. This makes it very hard to test. If you use the `hashlib` standard lib, then hashes are deterministic and you could test by just seeing that the hash is equal to a value that you expect. We could use `id` in the hash to keep otherwise identical objects from colliding.

One request: since this is performance related, would you mind giving just a little data on the improvement? For instance, you could call `hash` 1000x using the code on master and compare it to the time it takes now using your branch.

**Comment by javabster** [comment]
> Hi Abby, I think what you have added so far looks good. Unfortunately, it was added to the deprecated `Commands` which have since been merged into `Instructions` in `qiskit.pulse.instructions` if you could move your hashing modification there it would be great. I hope its not too much trouble :(

Ok sure no worries, I'll see what I can do :)

**Comment by javabster** [comment]
> @javabster one thing I recently discovered about the built in `hash` method is that it is not deterministic. It was returning the same hash for one object, but the initializing the same type with the same args was giving a different hash. This makes it very hard to test. If you use the `hashlib` standard lib, then hashes are deterministic and you could test by just seeing that the hash is equal to a value that you expect. We could use `id` in the hash to keep otherwise identical objects from colliding.
> 
> One request: since this is performance related, would you mind giving just a little data on the improvement? For instance, you could call `hash` 1000x using the code on master and compare it to the time it takes now using your branch.

Hi @lcapelluto thanks for the feedback :) I was told originally to use the same hashing method as was used for #3940, are you saying the requirements have now changed and I should redo using the hashlib library?

Also, could you point me to some resources or provide some examples of how to implement the hash timing data comparison thing? Apologies, this stuff is still all quite new to me so I'm not really sure how to go about this kind of data comparison.

**Comment by javabster** [comment]
@taalexander @lcapelluto I've just tried pulling from master and now whenever I run the pulse tests I get a bunch of errors about 'No module named fastjsonschema'. Have no idea what this is referring to or how to go about fixing it, is it something you've come across before?

**Comment by kdk** [comment]
> @javabster one thing I recently discovered about the built in `hash` method is that it is not deterministic. It was returning the same hash for one object, but the initializing the same type with the same args was giving a different hash. ...

Sort of surprising, but hash seed randomization is a feature of the built-in `hash`. (The second 'Note:' from [https://docs.python.org/3/reference/datamodel.html#object.__hash__ ](https://docs.python.org/3/reference/datamodel.html#object.__hash__) has some details on the motivation. In short, `__hash__` will be deterministic within a process, but not across processes.)

In practice, this shouldn't be an issue because the only conditions on `__hash__` are that it return an integer and that objects which are `__eq__` have the same `__hash__`.

**Comment by javabster** [comment]
> Hi Abby, I think what you have added so far looks good. Unfortunately, it was added to the deprecated `Commands` which have since been merged into `Instructions` in `qiskit.pulse.instructions` if you could move your hashing modification there it would be great. I hope its not too much trouble :(

Hi @taalexander I've had a look at the new `Instructions` files but the only one that contains any existing hashing is `instruction.py`. Do you want me to just add the `update_hash` modification to this file or also add new hashing functions in the other `qiskit.pulse.instructions` files? Also do you want me to remove the `update_hash` modification from the deprecated `Commands` or leave it in?

Sorry for all the questions I'm just getting a bit confused about what exactly the new requirements are :/ I'm happy to jump on a webex call sometime if it's easier to explain in person

**Comment by lcapelluto** [comment]
Kevin explained this well: tests would be checking that hash returns an int and that two objects give the same hash (so we shouldn't include `id` in the hash). No requirement here to use hashlib.

This is what I think remains to do:
 - [ ] revert changes to `Command` since they are already deprecated and will  be removed in a couple months
 - [ ] All hashing of `Instruction`s is handled by the super class `Instruction`, so you only need to update `pulse/instructions/instruction.py`. Please use a regular memoization style, where you 
1) set `self._hash = None` in `Instruction.__init__`, 
2) in `__hash__`, if `self._hash is None`, then set `self._hash` according to the lines that are there already (i.e., replace `return` with `self._hash =`), and add a line `return self._hash` at the end
3) Use `timeit` or `cProfile` around calling `hash` on some instructions many times to give us an idea of the performance gain (you can just leave a comment in this thread with the results)

**Comment by lcapelluto** [comment]
Here's an example of a mini profile I'm doing now for another PR:
```
# Append
schedule = Schedule()

chans = 1_000

profile = Profile()
profile.enable()

for i in range(chans):
    schedule += Play(Gaussian(amp=0.5, sigma=10, duration=10), DriveChannel(i))
    
profile.disable()
stats = Stats(profile)
stats.sort_stats('tot').print_stats(3)
stats.dump_stats("output.pstats")
```
As it turns out, `__hash__` is taking the most time :D looking forward to this PR!

**Comment by javabster** [comment]
@lcapelluto thank-you for your detailed comments, I feel a lot clearer on my next steps now :D I'll get working on it this week

**Comment by javabster** [comment]
@lcapelluto I generated some stats using timeit as suggested:

For instructions.py:
```
my_setup = '''
kernel_opts = {
'start_window': 0,
'stop_window': 10
}
kernel = Kernel(name='boxcar', **kernel_opts)
discriminator_opts = {
'neighborhoods': [{'qubits': 1, 'channels': 1}],
'cal': 'coloring',
'resample': False
}
discriminator = Discriminator(name='linear_discriminator', **discriminator_opts)
acq_1 = Acquire(10, AcquireChannel(0), MemorySlot(0),
kernel=kernel, discriminator=discriminator, name='acquire')
'''
test_code = '''hash(acq_1)'''
my_setup = """from qiskit.pulse.channels import AcquireChannel; acq_channel_1 = AcquireChannel(123)"""
test_code = """hash_1 = hash(acq_channel_1)"""
print(timeit.timeit(setup=my_setup, stmt=test_code, number = 10000))
```

old hashing method: 0.0024801600000001756 seconds
new hashing method: 0.0017750540000001092 seconds
i.e. the new hashing method is about 1.41 times faster

For channels.py:
```
my_setup = """from qiskit.pulse.channels import AcquireChannel; acq_channel_1 = AcquireChannel(123)"""
test_code = """hash_1 = hash(acq_channel_1)"""
print(timeit.timeit(setup=my_setup, stmt=test_code, number = 10000))
```
old hashing method: 0.0100543609999999 seconds
new hashing method:  0.003225801000000139 seconds
i.e. the new hashing method is about 3.12 times faster

**Pull request merged**
