### PR TITLE
Make Bit and Register base classes read-only and cache instances.

### PR DESCRIPTION
**Pull request by kdk**
### Summary

Operations on Bit and Register classes show up frequently in profiling (much more so following #3810 ), especially `Bit.__eq__`. However, since these classes are small and essentially static, equality, hashing and type checking cost can be avoided (and we can avoid memory allocations) by making these objects singletons. (Only a single instance with a given set of parameters will be created and subsequently reused.)

The Bit and Register classes are modified so that their properties can only be set once (at construction) and requests to create a new Bit or Register will re-use an existing one from memory, if it already exists.

### CODE REVIEW

**Comment by 1ucian0** [comment]
is this an alternative to https://github.com/Qiskit/qiskit-terra/pull/3940 and https://github.com/Qiskit/qiskit-terra/pull/3939 ?

**Comment by ajavadia** [comment]
@kdk @mtreinish is this still relevant?

**Comment by kdk** [comment]
This is on hold until after (or as part of the) registerless circuits work.

**Comment by jakelishman** [comment]
I believe this PR to be obsolete, so I'll close it as stale now.

**Pull request closed without merging**
