### PR TITLE
Issue 6633: Update _parameter_table after circuit assignment

### LINKED ISSUE #6633: Parameter table not updated after circuit assignment
### Information

- **Qiskit Terra version**: 0.17.4
- **Python version**: 3.9.5
- **Operating system**: Darwin

### What is the current behavior?

When performing a circuit assignment, `_parameter_table` is not updated to remove the discarded instruction, causing certain methods to fail (i.e., `.copy()`). 

### Steps to reproduce the problem

```
from qiskit import QuantumCircuit, QuantumRegister
from qiskit.circuit import Parameter

theta = Parameter('$\\theta$')
qr = QuantumRegister(2, 'q')
qc = QuantumCircuit(qr)
qc.rz(theta, 1)
print(qc)
print(qc._parameter_table[theta])
```
prints
```
q_0: ────────────────
     ┌──────────────┐
q_1: ┤ RZ($\theta$) ├
     └──────────────┘
[(<qiskit.circuit.library.standard_gates.rz.RZGate object at 0x7ffc7bd23eb0>, 0)]
```

Now, modify circuit by assignment in some way, for example by adding a control to the `RZGate`:

```
# make every gate controlled by q_0
for idx, (instr, qargs, cargs) in enumerate(qc.data):
    g = instr.control(1)
    qc.data[idx] = (g, [qr[0]] + qargs, cargs)

print(qc)
print(qc._parameter_table[theta])
```
prints
```
q_0: ───────■────────
     ┌──────┴───────┐
q_1: ┤ RZ($\theta$) ├
     └──────────────┘
[(<qiskit.circuit.library.standard_gates.rz.RZGate object at 0x7ffc7bd23eb0>, 0), (<qiskit.circuit.library.standard_gates.rz.CRZGate object at 0x7ffc7bd3e370>, 0)]
```

Note that there are two instructions in the parameter table, one corresponding to `CRZGate` that was assigned, and the original `RZGate` that is no longer in the circuit. This causes errors when trying to map between parameter tables, for example the `.copy()` method:

```
print('Original RZ instruction id is '+str(id(qc._parameter_table[theta][0][0])))
qc.copy()
```
prints
```
Original RZ instruction id is 140722385862320
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-4-79e10aadd73c> in <module>
      1 print('Original RZ instruction id is '+str(id(qc._parameter_table[theta][0][0])))
----> 2 qc.copy()

~/anaconda3/envs/qiskit27/lib/python3.9/site-packages/qiskit/circuit/quantumcircuit.py in copy(self, name)
   1749                         for id_, instr in instr_instances.items()}
   1750 
-> 1751         cpy._parameter_table = ParameterTable({
   1752             param: [(instr_copies[id(instr)], param_index)
   1753                     for instr, param_index in self._parameter_table[param]]

~/anaconda3/envs/qiskit27/lib/python3.9/site-packages/qiskit/circuit/quantumcircuit.py in <dictcomp>(.0)
   1750 
   1751         cpy._parameter_table = ParameterTable({
-> 1752             param: [(instr_copies[id(instr)], param_index)
   1753                     for instr, param_index in self._parameter_table[param]]
   1754             for param in self._parameter_table

~/anaconda3/envs/qiskit27/lib/python3.9/site-packages/qiskit/circuit/quantumcircuit.py in <listcomp>(.0)
   1750 
   1751         cpy._parameter_table = ParameterTable({
-> 1752             param: [(instr_copies[id(instr)], param_index)
   1753                     for instr, param_index in self._parameter_table[param]]
   1754             for param in self._parameter_table

KeyError: 140722385862320
```

In this case, we see that the error was caused by instruction 140722385862320, which corresponds to the original `RZGate` instruction.

### What is the expected behavior?

The parameter table should be updated upon assignment.

### Suggested solutions

Remove overwritten instructions from the parameter table.

### PR DESCRIPTION
**Pull request by TakahitoMotoki**
### Summary
The problem is data property in QuantumCircuit object is inconsistent with ParameterTable when data property is updated by `__setitem__` in quantumcircuitdata.py. In this modification, ParameterTable is cleared and reconstruct from the updated data property.

#### Problem
When data property in QuantumCircuit `qc.data` is set via `__setitem__` in quantumcircuitdata.py, `qc.data` becomes inconsistent with `qc._parameter_table`.

#### Reason
`qc.data` element is updated in `__setitem__` but a new element is added to qc._parameter_table by `_update_parameter_table()` instead of updating an existing element.

#### Solution
My idea is

1. Update an element of `qc.data`.
2. Obtain relating Parameter object from old `qc.data` and instruction.
3. Clear `qc._parameter_table`.
4. Reconstruct  qc._parameter_table` from the new  `qc.data`.

Fixes #6633

### CODE REVIEW

**Review by jakelishman — COMMENTED** [review]
Hello, thanks for looking at this!

At the moment, I'm quite worried that this implementation will have really big performance implications - on every modification to the circuit data, it iterates through the entire circuit's data twice over.  The current data structures in `ParameterTable` are really only designed for additive usage; they can't really handle modification, because there's no way to tell how many different data elements use each entry in the table.  I think we would need to introduce some form of reference counting to the elements of `ParameterTable` to handle this somewhat efficiently.

**Comment by 3yakuya** [comment]
Also appears to be blocked on https://github.com/Qiskit/qiskit-terra/issues/7457

**Comment by TakahitoMotoki** [comment]
@jakelishman 
Thank you for your comment. I modified the PR.
I think your comment is reflected on 3 and 4 in the steps below.
When `qc.data` is updated, find a corresponding element in `qc._parameter_table` instead of reset and reconstruct it.

1. Before the update, save original `qc.data` to `circ_data["old"]`.
2. Update `qc.data` and `qc._parameter_table`.
3. If an original element in `qc.data` have Parameter, delete a corresponding element in `qc._parameter_table`.
4. If an updated element in `qc.data` have Parameter, insert an element in `qc._parameter_table`.

**Comment by javabster** [comment]
In addition to @jakelishman's comments, a few more things from me:

- CI is failing with lint errors, running `tox -eblack` should fix this up
- Could you please add a test for this? I think `test_circuit_data.py` would be a good place to add some
- Please also add a release note, instructions [here](https://github.com/Qiskit/qiskit-terra/blob/main/CONTRIBUTING.md#release-notes)

**Review by jakelishman — COMMENTED** [review]
I don't think that this new form has addressed the efficiency concerns from before; it still loops over the entire circuit data twice, even though this implementation of `__setitem__` only allows replacements.  Since the number and position of all the instructions cannot change, we shouldn't need to loop over everything each time to determine things.

I think a lot of the parameter handling here should be done in `ParameterTable`, not in this structure.   We shouldn't be mutating private attributes of objects that aren't ourselves - it's very fragile to code changes, and it's difficult to maintain, because it's never clear which object is responsible for the mutations.  I think some of this will be made easier by #7408; the ordering of references in the table will become less important, so searching it will be much faster.

This whole `QuantumCircuitData` object is a _slight_ exception, because it mutates private methods of `QuantumCircuit`, but in an ideal world, this object would be defined _inside_ `QuantumCircuit` itself, because it's really not separate at all.

**Comment by TakahitoMotoki** [comment]
@jakelishman 
Thank you for your review. 
I have read through the comments and found that it needs quite a big modification.

Thus, I want to set direction with this issue.

I think the solution to this problem looks like…

- Define a new public method to remove an instruction in ParameterTable.py if instructions set in  _parameter_table and the input instruction have the same address.
- The method is similar to _check_dup_param_spec in QuantumCircuit.py. 
- The method is called from __setitem__ in QuantumCircuitData.py.  The input should be the instruction defined in qc._data before the replacement.

**Comment by TakahitoMotoki** [comment]
## Problem (Copy from PullReq statement)
When data property in QuantumCircuit `qc.data` is set via __setitem__ in quantumcircuitdata.py, `qc.data` becomes inconsistent with `qc._parameter_table`.

## Reason (Copy from PullReq statement)
An element of `qc.data` is properly updated by __setitem__ but an old instruction remains in `qc._parameter_table` because there is no code to remove an old instruction from `qc._parameter_table` in __setitem__.

## Solution
My idea is

1.  Define a public method to remove an element from ParameterTable. This method takes old instruction as an input. If ParameterTable has an element with the same address of the input, then remove it.
2. Call the public method from __setitem__ in quantumcircuitdata.py.

## About test code
I added a new test in test/python/circuit/test_circuit_data.py.
It covers following cases

- Case1-1: Add an instruction with a parameter that was not previously in ParameterTable.
- Case1-2: Add an instruction with a parameter that was already in ParameterTable.

- Case2-1: Replace an instruction with a parameter by other instruction with the same parameter.
- Case2-2: Replace an instruction with a parameter by other instruction with a different parameter.
- Case2-3: Replace an instruction with a parameter by other instruction with no parameters.

- Case3-1: Add an instruction with multiple parameters
- Case3-2: Replace an instruction with multiple parameters by other instruction

**Comment by HuangJunye** [comment]
@TakahitoMotoki Sorry for slow response. Are you still working on this PR? There are a few conflicts with the main branch. Can you please resolve them? Please let us know if you need help.

**Comment by javabster** [comment]
Closing this PR as contributor is no longer responsive. 
If contributor returns feel free to let us know if you would like us to re-open this PR 😃

**Pull request closed without merging**
