### PR TITLE
Fixed issue 3885 by adding list input to define dimensions of axes for pulse visualization

### LINKED ISSUE #3885: Pulse visualizations should support ability to provide a matplotlib ax
### What is the expected enhancement?
The pulse figures should support the ability for an `ax` to be provided on which the figure will be drawn. See [Seaborn](https://seaborn.pydata.org/generated/seaborn.heatmap.html) for an example.

### PR DESCRIPTION
**Pull request by michelle4654**
### Summary

Fixes #3885 

### Details and comments

It was recommended to add the capability for manual axis input for pulse visualizations. The example to emulate was listed as seaborn heatmap, where users can create an axis for which to draw the heatmap on. However, pulse visualization actually outputs a figure so these axes mostly need to be created within the function. I added a parameter for users to input **ax=[width, height]** where **width** and **height** are in dimensions of fraction of figure size. We could also look into changing the range and domain of the graph?

Note -- I haven't reconciled ScheduleDrawer.__draw_table yet. Should I let users adjust their axes if they're drawing a table as well? In this case, the input should maybe look more like **ax=[h_table, h_waves, h_space]** but maybe I don't have intuition about what users want

### CODE REVIEW

**Comment by ajavadia** [comment]
@michelle4654 could you please update this to resolve the conflicts? Thanks for the contribution.

**Comment by nkanazawa1989** [comment]
I think the interface should to accept matplotlib axis object rather than the size of figure. The figure size can be set with the stylesheet.
https://github.com/Qiskit/qiskit-terra/blob/b7fd3a8147236ea39c196a703d459b6aa28d5e5c/qiskit/visualization/pulse/qcstyle.py#L32

So what you need to do is using the given `ax` as a canvas (instead of generating it internally) when the `ax` argument is not `None`, and return nothing (or return the ax).

As you mentioned, we also have another axis object for the event table, 
https://github.com/Qiskit/qiskit-terra/blob/b7fd3a8147236ea39c196a703d459b6aa28d5e5c/qiskit/visualization/pulse/matplotlib.py#L786
Here you can check if `table` is True or not, and if `table=True` and there is only one `ax` is given you can raise a `VisualizationError` to request two axis objects for waveforms and table.

**Comment by taalexander** [comment]
Is there any update here?

**Comment by michelle4654** [comment]
Sorry! I've been really busy -- I can take a look at this today.

**Comment by mtreinish** [comment]
Since there hasn't been an update on this in nearly a year and there are several merge conflicts (also the pulse visualizer has been completely rewritten and the fixes being made here have been superseded by the v2 drawer) I'm going to close this as stale. But, please feel free to reopen this PR if you have the bandwidth to resolve the conflicts and update the code for current qiskit.

**Pull request closed without merging**
