### PR TITLE
Adds documentation to circuit.initialize

### LINKED ISSUE #5400: circuit.initialize has no documentation
### What is the expected enhancement?
Have more than this:
```

Docstring: Apply initialize to circuit.
```

### PR DESCRIPTION
**Pull request by elmandouh**
Fixes #5400

### CODE REVIEW

**Comment by Cryoris** [comment]
Hi @elmandouh, thanks for taking this on! A few more suggestions to further improve the documentation:
* we could add an example, both for passing a complex array and a string, something like
    ```
    .. code-block::
    
        import numpy as np
        from qiskit import QuantumCircuit
        circuit = QuantumCircuit(1)
        circuit.initialize([1/np.sqrt(2), -1/np.sqrt(2)], 0)
        print(circuit.draw())
        # show circuit diagram here
    ```
* we could add a note that this resets the qubits to |0> before applying a state preparing unitary
* the type hints are not quite correct, the qubits can also be an integer or a quantum register
* we could add the reference to the algorithm that is used for the initialization (see the docstring of `Initialize._define`)

**Comment by elmandouh** [comment]
Hi @Cryoris, thank you for the feedback! I fixed the type error, expanded on the description and added three examples. The circuit diagrams are not very helpful but I still included them. Let me know if anything else needs to be fixed.

**Comment by Cryoris** [comment]
@elmandouh do you still pursue this? It looks good, you just need to resolve the conflicts and get the CI to pass 🙂

**Comment by Cryoris** [comment]
@elmandouh I think something went wrong when with merging (reverting merges can often be the culprit), there are 14 files change when it should be just one 🙂 Maybe it's best to revert to a previous stage (like ec22f97), reset your master branch to be the same as Qiskit/master and then do a new merge.

**Comment by elmandouh** [comment]
@Cryoris Indeed something went very wrong with while trying to fix the conflicts? Should I close this PR and reopen a new one from an up-to-date branch?

**Pull request closed without merging**
