### PR TITLE
Fix parallel compilation in transpile.compile

### PR DESCRIPTION
**Pull request by nonhermitian**
### Summary

#977 removed most of the `wrapper.compile` function leaving only a wrapper for `transpile.compile`.  However, this modified the way that parallel compilation is done.  This PR returns parallel execution to how it was done before.

### CODE REVIEW

**Comment by nonhermitian** [comment]
`_circuit_2_dags` was not being used anywhere now that the parallel compile is done by parallelization over each circuit -> qobj experiment conversion.  There is always a DAG in the middle.

I can make more descriptive names.

**Comment by ajavadia** [comment]
> _circuit_2_dags was not being used anywhere now that the parallel compile is done by parallelization over each circuit -> qobj experiment conversion. There is always a DAG in the middle.

Yeah but basically I was gonna make _circuit_2_dags into a public function later, because working with the transpiler I find myself using it to get the dag, visualize it, etc. Unless you want to make a `QuantumCircuit.dag()` method, which I am fine with :).

**Comment by jaygambetta** [comment]
@nonhermitian this is not the way i want to go. Lets talk about how i want to do compile.

**Comment by 1ucian0** [comment]
A consensus is needed. On hold until then.

**Comment by jaygambetta** [comment]
after pr #1134 this needs to be redone. tracked issue #1146

**Pull request closed without merging**
