### PR TITLE
Drawing CCZ now consistent

### LINKED ISSUE #3968: ccz drawing inconsistency
A cz gate is being draw like this:
```
qr = QuantumRegister(2, 'q')
circuit = QuantumCircuit(qr)
circuit.append(ZGate().control(1), [qr[0], qr[1]])
circuit.draw()
```
```  
q_0: |0>─■─
         │ 
q_1: |0>─■─     
```

image

image

A ccz gate is being draw like this:
```
qr = QuantumRegister(3, 'q')
circuit = QuantumCircuit(qr)
circuit.append(ZGate().control(2), [qr[0], qr[1], qr[2]])
circuit.draw('text')
```
```
             
q_0: |0>──■──
          │  
q_1: |0>──■──
        ┌─┴─┐
q_2: |0>┤ Z ├
        └───┘
```
image

image

I thinks they all should be something like this:
```
             
q_0: |0>──■──
          │  
q_1: |0>──■──
          │  
q_2: |0>──■──
```

### PR DESCRIPTION
**Pull request by TharrmashasthaPV**
### Summary

Fixes #3968 .

### Details and comments

The CCZ gate was previously drawn as a double controlled box gate. It has been changed to be drawn as follows:

mpl_img

Additionally the 'mpl' version of CZ  gate was drawn as a controlled box gate. It has been updated to be drawn as below:

mpl_img

### CODE REVIEW

**Comment by 1ucian0** [comment]
Thanks a lot! Good work! From what I see in the code (did not run it yet), this example might not work. Probably a more general approach is needed...
 
```python
qr = QuantumRegister(4, 'q')
circuit = QuantumCircuit(qr)
circuit.append(ZGate().control(3), [qr[0], qr[1], qr[2], qr[3]])
circuit.draw('...')
```

**Comment by TharrmashasthaPV** [comment]
> 
> 
> Thanks a lot! Good work! From what I see in the code (did not run it yet), this example might not work. Probably a more general approach is needed...
> 
> ```python
> qr = QuantumRegister(4, 'q')
> circuit = QuantumCircuit(qr)
> circuit.append(ZGate().control(3), [qr[0], qr[1], qr[2], qr[3]])
> circuit.draw('...')
> ```

**Comment by TharrmashasthaPV** [comment]
Sorry my bad. Clicked the wrong button.

> 
> 
> Thanks a lot! Good work! From what I see in the code (did not run it yet), this example might not work. Probably a more general approach is needed...
> 
> ```python
> qr = QuantumRegister(4, 'q')
> circuit = QuantumCircuit(qr)
> circuit.append(ZGate().control(3), [qr[0], qr[1], qr[2], qr[3]])
> circuit.draw('...')
> ```

Good point. I'm on it.

**Comment by TharrmashasthaPV** [comment]
Have tried to make the controlled-z more general. The gates are now drawn as follows:

text_img

mpl_img

latex_img

I suppose this should be sufficient.

**Comment by 1ucian0** [comment]
I made some small changes in the text drawer. Thanks alot for your contribution!

**Pull request merged**
