### PR TITLE
Deprecate allowing extra keys in circuit drawer style dict

### PR DESCRIPTION
**Pull request by 1ucian0**
fixes part of #2797 

The MPL drawer was ignoring `style: {'plotbarrier':...}` anyway, so I'm not sure if I should deprecated just in case.

Also, I added an error when `style` contains element that are not being used.

### CODE REVIEW

**Comment by mtreinish** [comment]
Setting plot barrier and reverse bits in the style dict was deprecated as part of the 0.7 release and removed in 0.8 (the actual 0.8 patch was: https://github.com/Qiskit/qiskit-terra/pull/1567 ). Any leftover documentation or anything else referring to it in the style dict was just an oversight from that.

**Comment by 1ucian0** [comment]
Oh! good to know! I that case I will clean it up.

**Comment by mtreinish** [comment]
I'm fine with the text drawer changes because it's not user facing, just making the internal kwargs consistent with the other drawers. But I'm a bit concerned about the style dict changes I support the goal of making it more clear that people are passing in invalid values (a config dict isn't really a good pattern, they should be kwargs) but I'm concerned about the end user implications. The style dict has behaved this way for a number of releases (since the `mpl` drawer was introduced) and it'll potentially be abrupt for users to have it stop working. What do you think about doing this softly at first making it warn that invalid args have been passed in and that in the next release this will be a failure?

**Comment by 1ucian0** [comment]
Yeap. What you are saying makes total sense. Fixed in da802e5

**Comment by 1ucian0** [comment]
> should add a release note.

Added in 5f397c8840329297be70b88d2ebe2715d6eb9858

**Pull request merged**
