### PR TITLE
New commutation passes

### PR DESCRIPTION
**Pull request by godott**
### Summary
1. A commutation analysis pass and a commutation transformation are added.
2. Test cases for commutation passes are added.
3. An example is added.

### Details and comments
The commutation analysis pass figures out the commutation relations for gates in DAGCircuit, all the 1&2 qubit gates are supported now. 

Here are some examples:
# 1. Test all the gates
## Circuit:
gate_test_circuit
## DAG before:
gate_test_before
## DAG after:
gate_test_after

# 2. An example of Quantum Instantaneous Polynomial Time(all gates commute)
## Circuit:
qipt_circuit
## DAG_before:
qipt_before
## DAG_after:
qipt_after

# 3. Circuits produced by Jordan-Wigner transformation
## Circuit:
jw_circuit
## DAG before:
jw_before
## DAG after:
jw_after

### CODE REVIEW

**Comment by jaygambetta** [comment]
is nice that we show the dag before and after but can we also show the circuit. It would also be nice to have the circuit in the example

**Comment by godott** [comment]
> is nice that we show the dag before and after but can we also show the circuit. It would also be nice to have the circuit in the example

For that, I think a DAG_to_circuit() method is needed. Right now, we have functions to convert DAG to openQASM and convert openQASM to QuantumCircuit, but the two functions don't work together.

**Comment by ajavadia** [comment]
> > is nice that we show the dag before and after but can we also show the circuit. It would also be nice to have the circuit in the example
> 
> For that, I think a DAG_to_circuit() method is needed. Right now, we have functions to convert DAG to openQASM and convert openQASM to QuantumCircuit, but the two functions don't work together.

you can use
```
from qiskit.converters import dag_to_circuit
circuit = dag_to_circuit(dag)
circuit.draw()
```

but i don't think drawing the circuit shows much. this pass modifies DAG edges, to make them more amenable to scheduling, optimization, etc. The circuit drawer may just move some boxes around.

**Comment by jaygambetta** [comment]
@ajavadia and @godott i have already done that i push a pr into your branch dealing with some linting.

**Pull request merged**
