### PR TITLE
Remove `parameters` arguments for `run` method of Primitives

### PR DESCRIPTION
**Pull request by t-imamichi**
### Summary

Removes `parameters` argument from `BaseSampler.run` and `BaseEstimator.run`.
Primitives won't be a context manager but will be like an ordinal function with `run` method.
Setting `paramaters` argument to `run` method could be tricky.
So, this PR removes the argument for discussion purpose.

Note that it has no reno because `BaseSampler.run` and `BaseEstimator.run` are not released yet #8382.

### Details and comments

Need to sync with qiskit-aer and qiskit-ibm-runtime, which as their own Primitives implementation.

### CODE REVIEW

**Comment by Cryoris** [comment]
Looks good to me, as I don't know of any use case where one needs to set `parameters`. The only use case that comes to my mind is for re-ordering how parameter values are bound to the circuit, but that can just be handled by resorting the `parameter_values` directly.

The Aer (and runtime primitives) also have this argument which we would need to update before the release then too, right? 🙂

**Comment by t-imamichi** [comment]
Yes, if we all agree to remove `parameters`, we have to update Aer and qiskit-ibm-runtime too.

E.g., [Aer estimator](https://github.com/Qiskit/qiskit-aer/blob/1fb055eab16c6206cc42f2646d852a9535686cef/qiskit_aer/primitives/estimator.py#L146)
[qiskit-ibm-runtime estimator](https://github.com/Qiskit/qiskit-ibm-runtime/blob/af308caeb7c261a1fb1a7ca7a45c49f55df02215/qiskit_ibm_runtime/estimator.py#L194)

**Comment by ikkoham** [comment]
As `run()` method has not been released in Terra, but has been released in `qiskit-ibm-runtime`, I think it is better to wait for the deprecation period before removing it than to simply remove it.

**Comment by pedrorrivero** [comment]
I agree with this update, it simplifies the interface at no real cost in terms of functionality.

**Comment by t-imamichi** [comment]
I updated docsrting and reno to remove `parameters`. Could you review it, @ikkoham?

If you have any concern from qiskit-aer or qiskit-ibm-runtime perspectives, could you let me know, @ikkoham and @jyu00?

**Comment by ikkoham** [comment]
I reverted Aer's `_run` method https://github.com/Qiskit/qiskit-aer/pull/1597 because it does not support this PR.

**Review by ikkoham — COMMENTED** [review]
The code change looks good to me, however I don't know if qiskit-ibm-runtime will accept this change, so I can't approve it at this time.

**Comment by t-imamichi** [comment]
I resolved the conflicts to merge main. Do you have any concern to merge this PR, @jyu00?

**Comment by jyu00** [comment]
> I resolved the conflicts to merge main. Do you have any concern to merge this PR, @jyu00?

Go for it. I'll update qiskit-ibm-runtime to do the same once this is merged.

**Comment by t-imamichi** [comment]
Thanks, @jyu00! Let's merge this, @ikkoham.

**Pull request merged**
