### PR TITLE
Subcircuits with classical wires stay right of measures

### LINKED ISSUE #5947: Circuit drawers misorders subcircuits which depend only on a classical wire
### Information

- **Qiskit Terra version**: master @ 296a745
- **Python version**:  3.6
- **Operating system**: osx 10.15

### What is the current behavior?

Appending a circuit which uses both qubits and clbits can be drawn out of order, if it introduces a dependency which can only be followed along classical wires.

### Steps to reproduce the problem

Base circuit:
```
qc = qk.QuantumCircuit(2,1)
qc.h(0)
qc.measure(0,0)
qc.draw()
```

```
     ┌───┐┌─┐
q_0: ┤ H ├┤M├
     └───┘└╥┘
q_1: ──────╫─
           ║ 
c: 1/══════╩═
           0 
```

Circuit to be appended:

```
qc_2 = qk.QuantumCircuit(1,1)
qc_2.h(0).c_if(qc_2.cregs[0], 1)
qc_2.draw()
```

```
      ┌───┐ 
q_0: ─┤ H ├─
      └─╥─┘ 
     ┌──╨──┐
c: 1/╡ = 1 ╞
     └─────┘
```

Combined circuit:

```
qc.append(qc_2, [1], [0])
qc.draw()
```

```
          ┌───┐     ┌─┐
q_0: ─────┤ H ├─────┤M├
     ┌────┴───┴────┐└╥┘
q_1: ┤0            ├─╫─
     │  circuit111 │ ║ 
c_0: ╡0            ╞═╩═
     └─────────────┘   
```

Matplotlib:

image

Latex:

image

DAG drawer has the right dependency on `c[0]`:

image

### What is the expected behavior?

The appended circuit should be drawn after the measure.

### PR DESCRIPTION
**Pull request by enavarro51**
### Summary

Fixes #5947

### Details and comments

This PR fixes a problem where a subcircuit that contains classical wires that is appended to another circuit with a measure on one of those wires, will sometimes display to the left of the measure. For example, from master,
```
qc = QuantumCircuit(2, 2)
qc.h(0)
qc.measure(0, 0)
qc_2 = QuantumCircuit(1,1,name='add_circ')
qc_2.h(0).c_if(qc_2.cregs[0], 1)
qc_2.measure(0, 0)
qc.append(qc_2, [1], [0])
qc.draw('text')
         ┌───┐    ┌─┐
q_0: ────┤ H ├────┤M├
     ┌───┴───┴───┐└╥┘
q_1: ┤0          ├─╫─
     │  add_circ │ ║ 
c_0: ╡0          ╞═╩═
     └───────────┘   
c_1: ════════════════
                     
```
is now
```
     ┌───┐┌─┐             
q_0: ┤ H ├┤M├─────────────
     └───┘└╥┘┌───────────┐
q_1: ──────╫─┤0          ├
           ║ │  add_circ │
c_0: ══════╩═╡0          ╞
             └───────────┘
c_1: ═════════════════════
                          
```
This is fixed for all 3 circuit drawers.

### CODE REVIEW

**Review by 1ucian0 — CHANGES_REQUESTED** [review]
Great! Can you add a release note? I assume this affected the other drawers too. Do you mind adding tests for them?

**Comment by enavarro51** [comment]
Will do the release note. On the test, it probably makes more sense to move the test into `visualization.test_utils.py` where there are other `_get_layered_instructions` tests since that's where the change was made, rather than adding additional tests.

**Comment by enavarro51** [comment]
Release note added and test moved to test_utils.py in https://github.com/Qiskit/qiskit-terra/pull/5958/commits/e1f85346597a00253bf35acd4becf55a1bc2d14f and https://github.com/Qiskit/qiskit-terra/pull/5958/commits/22b71d8ea53436ac6a6f6d81b2d38f556853199a

**Review by 1ucian0 — APPROVED** [review]

**Comment by 1ucian0** [comment]
Thanks! merging...

**Pull request merged**
