### PR TITLE
skip test_crosstalk_adaptive_scheduler when z3-solver not available

### PR DESCRIPTION
**Pull request by 1ucian0**
PR #3532 introduced an optional dependency on `z3-solver`. This PR skips the tests using that module when not available.

### CODE REVIEW

**Comment by mtreinish** [comment]
I assume you want to do this because there is no precompiled binary for the z3 package on osx. Can you give the test wheel in: https://github.com/Z3Prover/z3/issues/2800#issuecomment-568196989 a try and see if that works for you. I think if that works they'll probably start uploading osx wheels for new releases.

**Comment by 1ucian0** [comment]
> I assume you want to do this because there is no precompiled binary for the z3 package on osx.

I think, in general, it's too much to ask for a contributor, specially if the developer is not going to hack around this specific pass. We don't have a clear policy about it. python-constraint  is not in req-dev currently (it's same case as this one) because is a dependency for a specific pass that is not in the default pipeline. As @kdk noticed, `pydot` is. I can argue that pydot is a more "general" dependency, and touching some part of the code might affect things that are tested by pydot. Probably we should formalized what it means an optional dependency.

> Can you give the test wheel in: Z3Prover/z3#2800 (comment) a try and see if that works for you. I think if that works they'll probably start uploading osx wheels for new releases.

I can do that. But let do that independently of this PR.

**Comment by 1ucian0** [comment]
> Agree that we should formalize how optional dependencies are defined

Discussion issue here: https://github.com/Qiskit/qiskit-terra/issues/3654

**Comment by 1ucian0** [comment]
@mtreinish said:
> Can you give the test wheel in: https://github.com/Z3Prover/z3/issues/2800#issuecomment-568196989 a try and see if that works for you. 

It does work (at least these tests) when I install the wheel from https://github.com/Z3Prover/z3/issues/2800#issuecomment-568196989

**Pull request merged**
