### PR TITLE
Add support for Python 3.10

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

Python 3.10.0 was released on 10-04-2021, this commit marks the support
of Python 3.10 in qiskit-terra. It adds the supported python version in
the package metadata and updates the CI configuration to run test jobs
on Python 3.10 and build Python 3.10 wheels.

### Details and comments

TODO:

- [x] Wait on azure pipelines images to add python 3.10

Wait on wheels for:

- [x] numpy (no i686)
- [x] scipy
- [x] retworkx (main has support after https://github.com/Qiskit/retworkx/pull/447 just needs a new release)
- [x] symengine (https://github.com/symengine/symengine-wheels/issues/7 )

Test dependencies:

- [x] scikit-learn (https://github.com/scikit-learn/scikit-learn/pull/21232 )
- [x] jax (https://github.com/google/jax/issues/8097 )
- [x] jaxlib (https://github.com/google/jax/issues/8097 )

### CODE REVIEW

**Comment by jakelishman** [comment]
In principle I don't see any problems with the PR, but it's going to be a nightmare for CI runs - it'll add an extra 3 jobs to the main test matrix.  The current main test run already sets 10 jobs in motion, which is our full provision of Azure machines, so some will have to run after others and that'll add 20+ minutes to CI in a vacuum, let alone with multiple PRs.  Is there any chance we _can_ drop Python 3.6 for Terra 0.19?

**Comment by mtreinish** [comment]
We've already advertised 0.19.0 will be the last release with 3.6 release so it's kind of hard to walk that back. I wasn't actually planning to merge this for 0.19.0, as from past experience I don't think our upstream dependencies will be ready by the time we release 0.19.0. I just pushed this up because I was curious of the current state and wanted to see what CI looked like right now (and to have something to point to when the flood of people start complaining about the lack of python 3.10 support in a month or two).

**Comment by jakelishman** [comment]
Yeah, that seems fine to me - I was mostly just whining about dropping 3.6 for 0.19.

Numpy has Python 3.10 wheels for manylinux2014 published already (since the 15th of August!) but nothing else - I'm slightly surprised they didn't have them all, to be honest.

**Comment by levbishop** [comment]
Should `tox.ini` be updated also? (I note that it doesn't include py39 now)

**Comment by mtreinish** [comment]
> Should `tox.ini` be updated also? (I note that it doesn't include py39 now)

Yeah, we should add it. It's not actually an explicit support list, just the list of what calling `tox` bare attempts to run by default, but it's good to include. I'll add it the next time I bump this PR (it's still a long way to go before we can support 3.10)

**Comment by mtreinish** [comment]
One thing I've noticed is that for python 3.10 both numpy and scipy have dropped 32bit platforms (i686 and win32) in their recent releases with python 3.10 support. I don't think they'll be supporting either 32bit platform on newer python versions. If this is the case we'll also have to drop support for i686 and win32 on py3.10.

**Comment by jakelishman** [comment]
Passed on Windows Python 3.10!  Maybe we should mark Jax as unnecessary on all Python 3.10 versions until they release wheels/an sdist?

**Comment by mtreinish** [comment]
> Passed on Windows Python 3.10! Maybe we should mark Jax as unnecessary on all Python 3.10 versions until they release wheels/an sdist?

It's not a bad idea but I do worry about how much we're building from source still. It looks like in that passing windows job we're still building all of these from source:

- retworkx (this is on me, I wasn't planning to have a release until after terra 0.19.0)
- psutil
- matplotlib
- scikit-learn
- lazy-object-proxy
- tornado
- wrapt
- pyrsistent

So if we set a version marker on jax entries in the `requirements-dev.txt` we'll be able to run in CI but we'll be forcing people to compile all of those from source to run tests (the caching will prevent us from having to do this on every run in CI though) and at least retworkx, and psutil to just run qiskit.

**Comment by jakelishman** [comment]
If they try and do `pip install qiskit` on Python 3.10 it'll still try and compile a bunch of stuff first before failing anyway, I think?  So removing Jax, which _can't_ build on Python 3.10, limits our requirements only to things that will build, albeit slowly, as opposed to the build failing.

If someone's using Python 3.10, the best we can do is make our own stuff have wheels - at that point we've done as much as we can to ease the transition, and at the moment we're making it impossible to develop with Python 3.10 on Linux or Mac (unless you know enough to not to `pip install -r requirements-dev.txt`). We probably don't want to wait until all our downstream dependencies have wheels to produce our own - I think now Numpy and Scipy have wheels, we could do as well.

**Comment by mtreinish** [comment]
I'm removing on hold here. We should be hopefully releasing retworkx in the next week or so (once I get the open PRs https://github.com/Qiskit/retworkx/milestone/7 reviewed and merged ) Which will definitely be before the next release. But until that happens we shouldn't block this on retworkx being slow to release especially because we have a rust compiler in CI and can build the wheel to test with 3.10. We'll just have to wait to release this (and as part of a backport release too) until after retworkx releases (so we're not requiring a rust compiler for py3.10 users to install qiskit.

**Review by jakelishman — APPROVED** [review]

**Comment by mtreinish** [comment]
Retworkx 0.11.0 was released earlier today with python 3.10 wheels so I'm tagging this for merge now.

**Comment by jakelishman** [comment]
Do we want to backport this for 0.19.2 as well (which we ought to put out soon)?

**Comment by mtreinish** [comment]
> Do we want to backport this for 0.19.2 as well (which we ought to put out soon)?

Yeah, we should backport this to get it out sooner.

**Pull request merged**
