### PR TITLE
Latex drawer now graphs symmetrical gates and their names together

### LINKED ISSUE #6050: Symmetric side text gates do not display properly in the latex drawer
### Information

- **Qiskit Terra version**: Any
- **Python version**: Any
- **Operating system**: Any

### What is the current behavior?

Symmetric gates that have a name and a parameter printed to the right of the gate (side text) do not display properly in either the old or the new latex drawer. There are 2 issues with this.

The first is that when using `@!R` in setting up qcircuit, the library will then evenly space the rows based on the size of the largest vertical gate. Here are 3 examples of where the side text will display.

image

image

image

The side text should adjust vertically so it is evenly spaced between the rows.

The second problem is that with qcircuit, it is only possible to have one command for each row/column intersection. The side text is displayed using \\dstick which places the side text below the top bullet of the symmetric gate. To get it to the right it is placed in the next column over. So this can happen,

image

And with a very wide gate name, the side text can seem lost way out to the right.

### Suggested solutions

There doesn't appear to be any solution to this using qcircuit commands only. A \newcommand using xy-pic and/or Latex commands should probably be written to specifically address the side text situation.

### PR DESCRIPTION
**Pull request by jsistos**
### Summary
Fixes #6050 and updates some of the tests using the methods that were affected.

### Details and comments
Currently, the latex drawer uses ``` \dstick ``` to write the names of symmetrical gates (namely, ``` RZZ, CU1, CP ```). As @enavarro51 noted, this leads to issues in the ``` qcircuit ``` package, which takes such names to the next column and looks odd when a symmetrical gate is in the same layer as a really wide gate.
image

Also, depending on the spacing between wires, the location of the name could look arbitrary.
image

By [using](https://github.com/CQuIC/qcircuit/blob/master/qcircuit.sty) ``` \cds ``` instead, we can fix (or at least mitigate) both issues. First, it allows us to place the name of the gate in the same column as the ``` \control ``` command (in the xymatrix). Also, using ``` -1 ``` as the first parameter of ``` \cds ``` seems to locate the label in the middle of two wires, no matter the spacing.

image
image
image

The corresponding ``` LaTeX ``` tests were also updated to follow these changes.

### CODE REVIEW

**Comment by enavarro51** [comment]
Good find on this. It almost works for every case. But you have to allow for the possibility of a float as a param, so this circuit,
```
qc = QuantumCircuit(3)
qc.x(0)
qc.cu1(3.222, 0, 1)
qc.draw('latex')
```
gives you,

image

You may have to adjust the hspace based on how wide the param is.

**Comment by jsistos** [comment]
> You may have to adjust the hspace based on how wide the param is.
Nice catch! I kind of figured it out by defining a length command ``` \glen ``` and setting it to the length of the gate text name each time a symmetrical gate is used. I'll submit the commit soon.

**Comment by enavarro51** [comment]
This is looking good. A smaller font for the floats might be good, but if that's not a reasonable option, you can just increase the column count for symmetric gates from 4 to 5. You need to do it in two places.
https://github.com/jsistos/qiskit-terra/blob/cf58afdf3db6bf5a006a0bb875f37b2fecfdfd4e/qiskit/visualization/latex.py#L274
https://github.com/jsistos/qiskit-terra/blob/cf58afdf3db6bf5a006a0bb875f37b2fecfdfd4e/qiskit/visualization/latex.py#L490

5 columns may seem like a lot, but in qcircuit land, the U gate here takes up 1 column and the cu1 takes up 5. There may be a  bit of excess space for simple pi/2 params, but trying to change column counts dynamically might be too much.

image

**Comment by jsistos** [comment]
Thank you for the observation. I think for now I will change the number of columns, and I'll upload the changes as soon as I can successfully update the tests that depend on this.

**Comment by enavarro51** [comment]
@jsistos Just checking if you are still working on this. The merge conflicts should not be too bad. For the .tex files you can just delete those in your local references dir and run the visualization test locally to recreate them after merging with main.

**Comment by javabster** [comment]
@jsistos as we haven't heard from you I will reassign to @enavarro51, if you would still like to work on it please reach out to Ed about continuing to work on it together 😄

**Comment by jakelishman** [comment]
I'll close this as superseded by #6877 as discussed above (which is also currently a bit stale).  Feel free to re-open/re-submit if I've missed something, though.

**Pull request closed without merging**
