### PR TITLE
Fix wrapping of ``GroverOperator``

### PR DESCRIPTION
**Pull request by Cryoris**
### Summary

Fixes the finance tutorials (see also https://github.com/Qiskit/qiskit-finance/pull/71).

### Details and comments

Due to our current distinction into `Gate` and `Instruction` and their different features, we have to explicitly try converting the library circuits to gates and only to instructions when the gate conversion fails.

### CODE REVIEW

**Review by mtreinish — APPROVED** [review]
LGTM, @woodsp-ibm can you confirm this is fixing the issues you hit?

**Comment by woodsp-ibm** [comment]
> can you confirm this is fixing the issues you hit?

Ok, let me double-check. I would hope Julien tried it with the failing Finance Notebook - but I'll check too

**Comment by Cryoris** [comment]
I did but checking twice is never bad 😄

**Review by woodsp-ibm — APPROVED** [review]
Notebook, that was failing, runs fine for me too with this fix.

**Pull request merged**
