### PR TITLE
Fix Windows multiprocessing script errors

### LINKED ISSUE #424: Local qiskit simulator slow on Windows
I have both a Mac and a PC, and when I try and run my code using the 'local_qiskit_simulator' as the backend, it's much faster on Mac than it is on Windows.  It seems like it built correctly (there's a qiskit_simulator.exe file in the backend folder), but it's still not as fast.  Is there a way to confirm that the existent .exe file is correctly compiled and that it's not falling back to the slower Python backend?

Any help would be greatly appreciated, thank you.

For context, my environment is:  
* pip version 9.0.1  
* python version 3.6.4 (Anaconda custom 64-bit)
* conda version 4.5.1
* qiskit version 0.4.14

QISKit was installed using pip.

Let me know if you need any more information!  Thanks.

### LINKED ISSUE #608: concurrent.futures.process.BrokenProcessPool error when running example program
### Informations

- **QISKit (Python SDK) version**: most recent edition as of 6/28/2018
- **Python version**: 3.6.5
- **OS**: Windows

### What is the current behavior?

Run the program given below; I get the results

```
Local backends:  ['local_qasm_simulator', 'local_statevector_simulator', 'local_unitary_simulator']
Traceback (most recent call last):
  File "C:/Users/hyoung/Documents/python/qiskittest.py", line 25, in <module>
    sim_result = job_sim.result()
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\qiskit\backends\local\localjob.py", line 57, in result
    return self._future.result(timeout=timeout)
  File "C:\Program Files (x86)\Python36-32\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "C:\Program Files (x86)\Python36-32\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
>>> 
```

### Steps to reproduce the problem

Run the example program given on the main page:

```
# Import the QISKit SDK
from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister
from qiskit import available_backends, execute

# Create a Quantum Register with 2 qubits.
q = QuantumRegister(2)
# Create a Classical Register with 2 bits.
c = ClassicalRegister(2)
# Create a Quantum Circuit
qc = QuantumCircuit(q, c)

# Add a H gate on qubit 0, putting this qubit in superposition.
qc.h(q[0])
# Add a CX (CNOT) gate on control qubit 0 and target qubit 1, putting
# the qubits in a Bell state.
qc.cx(q[0], q[1])
# Add a Measure gate to see the state.
qc.measure(q, c)

# See a list of available local simulators
print("Local backends: ", available_backends({'local': True}))

# Compile and run the Quantum circuit on a simulator backend
job_sim = execute(qc, "local_qasm_simulator")
sim_result = job_sim.result()

# Show the results
print("simulation: ", sim_result)
print(sim_result.get_counts(qc))
```

### What is the expected behavior?

It should print the simulation results.

### Suggested solutions

Not really sure; this is my first time using qiskit and I was expecting the example program to just work out of the box.

### PR DESCRIPTION
**Pull request by nonhermitian**
### Summary

We have seen several reports of users having issues with spawning processes on Windows (#608 for example.)  Here I simply move to a `ThreadPool` on Windows for the `LocalJob` instance.  Remote jobs all use a `ThreadPool`.  Windows plays nice with threads.  This should also remove the slowdown on Windows platforms, but I have not confirmed this.

### Details and comments
Confirmed this works on Win7 VM using Bell script example.

Fixes #608.
Fixes #424.

### CODE REVIEW

**Comment by diego-plan9** [comment]
Thanks @nonhermitian - it is looking promising!

Can you update the branch taking the latest changes for travis implemented at #614 ? It seems the source of the CI issue was the (very unfortunately timed for our CIs) release of Python 3.7, and those changes basically pin 3.6.5 for the osx travis run. We should check that everything works for Python 3.7 overall in a separate issue which I'll open to track those changes.

**Comment by nonhermitian** [comment]
Can do.

**Comment by nonhermitian** [comment]
I can confirm that this also fixes #424.

**Comment by jaygambetta** [comment]
does it also mean we can get ride of the if function in the examples.

**Comment by nonhermitian** [comment]
Yes it does.

**Comment by jaygambetta** [comment]
great then i remove this from the addon examples.

**Pull request merged**
