### PR TITLE
Fixes #4894 : A small change in docstring.

### LINKED ISSUE #4894: Documentation minor mistake
https://github.com/Qiskit/qiskit-terra/blob/8636502a832ee5c63a26f66c9669c88a1149e432/qiskit/qobj/pulse_qobj.py#L601

Probably won't matter too much, but just to state everything correctly. The PulseQobj.to_dict() should return a dictionary that describes the PulseQobj instead of QasmQobj, right?

### PR DESCRIPTION
**Pull request by TanveshT**
### Summary

Under the `PulseQobj` Class, the method `to_dict()` had a statement that it returns `QasmQobj dictionary`  instead of `PulseQobj dictionary`

### Details and comments

So there has been made a change to do the same as the `to_dict()` method returns a dictionary of the `PulseQobj`. 
**Fixes** #4894

### CODE REVIEW

**Comment by TanveshT** [comment]
Can anyone tag any reviewers?

**Comment by TanveshT** [comment]
@Cryoris Can you review this?

**Comment by TanveshT** [comment]
@1ucian0 Do you know why it's failing to merge?

**Comment by 1ucian0** [comment]
> @1ucian0 Do you know why it's failing to merge?

It seems like a problem on the CI side. No worries.

**Pull request merged**
