### PR TITLE
QuantumCircuit.decompose() can specify gates to decompose

### LINKED ISSUE #2906: QuantumCircuit.decompose() should take which gate(s) to decompose
### What is the expected enhancement?
If find myself looking at circuits that look like this:

Screen Shot 2019-08-05 at 6 28 05 AM

and I am always interested in seeing what the circuits look like in terms of cx and other gates.  However, this requires doing:

```python

from qiskit.transpiler import PassManager
from qiskit.transpiler.passes import Unroller
pass_ = Unroller(['u1', 'u2', 'u3', 'cx'])
pm = PassManager(pass_)
new_circ = pm.run(circ)
```

It would be nice if there was a `decompose_unitaries(basis)` method that did this for you.

### PR DESCRIPTION
**Pull request by septembrr**
### Summary
This pull request resolves #2906 and allows specification of gates to decompose inside circuit.decompose(). It takes a list of strings such as ['cz', 'h']. One additional test was added to account for this feature.

### Details and comments
While working on this feature, I discovered that the Decompose class already holds one parameter (gate) that controls which gates to decompose. However, this parameter is passed to DAGCircuit.op_nodes(Gate) which returns only those nodes that are of the same type. If there are other types of gates in the circuit, they will be removed. The documentation does not make this side effect clear: https://qiskit.org/documentation/stubs/qiskit.transpiler.passes.Decompose.html.

I have left this parameter alone in this pull request for now. However, is this expected behavior or should I open a related issue?

### CODE REVIEW

**Comment by Cryoris** [comment]
@septembrr thanks for this addition! We discussed this and we think it would be nice to add a little more work into it -- if you want to 🙂 

First, it wasn't clear to us that `gates` is the list of gates that is decomposed, we thought it's the target gate set. Could you rename the variable so this becomes clearer? E.g. to `gates_to_decompose` or so.

Secondly, it would be nice to support support for the `*` wildcard, particularly at the end of a string. Often the name of instructions is autogenerated to things like `circuit319 circuit291 circuit11` or `su4_911 su4_2193`. It would be nice to be able to write 
```
circuit.decompose('su4_*')
circuit.decompose('circuit*')
```
for that.

Do you think you could add that to this PR?

**Comment by septembrr** [comment]
Yes! I will update this PR.

**Comment by javabster** [comment]
hi @septembrr how is this going? Let us know if you have any questions 😄

**Comment by septembrr** [comment]
I'd love to tackle this but it looks like I won't have time to complete it right now, so if someone else wants to take it on that's fine!

**Comment by javabster** [comment]
ok sure thanks for letting us know @septembrr! I will un-assign you from the original issue for now and if you are interested in picking it up again in future just let me know and I will re-assign to you 😄

**Comment by 1ucian0** [comment]
Closing in favor of https://github.com/Qiskit/qiskit-terra/pull/6587 .

**Pull request closed without merging**
