### PR TITLE
Avoid skipping channels in pulse visualizer

### PR DESCRIPTION
**Pull request by wshanks**
### Summary

This PR fixes some cases where the pulse visualizer would skip some channels.

### Details and comments

`inds` is a set that is iterated over and compared to sorted lists that get their values popped off the end when they match. I guess typically `inds` has iterated in a way that matches the sorting of the lists so this wasn't noticed before, but the order is random in principle. This PR is a quick fix to sort `inds` so it matches the ordering of the lists. This problem was first noticed in [Qiskit Slack](https://qiskit.slack.com/archives/CMBARB4LX/p1666274705046109).

This is a pretty small change -- we could add a release note or tests (I haven't looked at the tests for this part of the code) if they seemed worthwhile.

### CODE REVIEW

**Review by nkanazawa1989 — COMMENTED** [review]
LGTM. I'll approve after release note.

**Comment by wshanks** [comment]
Okay, I found the relevant test and modified it to fail. All the tests in the class use the same set of channels and I didn't want to have to update every test so I just modified the channel list in the one test to get it to fail. If that's too weird, maybe we can just drop that commit. It was a nice sanity check that the fix actually changed a fail into a pass.

I also added a release note. I opened #8981 because it seemed cleanest to reference an issue in the release note.

**Comment by nkanazawa1989** [comment]
close #8981

**Review by nkanazawa1989 — APPROVED** [review]
LGTM thanks for adding test and note.

**Comment by wshanks** [comment]
@nkanazawa1989 Should we have labeled this with "stable backport potential"?

**Pull request merged**
