### PR TITLE
[WIP] Adding _define_from_str to initializer

### PR DESCRIPTION
**Pull request by WiFisunset**
### Summary
Adding _define_from_str to initializer so that string inputs can be accepted as an initialization state. 

The function takes a string, converts it to binary, followed by converting the binary to an int list array, and then attempts to assign XGates in reversed order to each qubit. 

Note: Currently a Work-In-Progress as the current output test is a DAGwire error; and self._from_str is currently set to True to test/debug (not a permanent change; will be set back to False as per default).

### Details and comments

Note: Current test output is a DAGerror.

Error:
Qubit(QuantumRegister(10, 'q'), 0)
Qubit(QuantumRegister(10, 'q'), 0)
Qubit(QuantumRegister(10, 'q'), 0)
Qubit(QuantumRegister(10, 'q'), 1)
Qubit(QuantumRegister(10, 'q'), 1)
Qubit(QuantumRegister(10, 'q'), 1)
Traceback (most recent call last):
  File "test3.py", line 20, in <module>
    print(qc.decompose().draw())
  File "quantumcircuit.py", line 1296, in decompose
    decomposed_dag = pass_.run(circuit_to_dag(self))
  File "circuit_to_dag.py", line 56, in circuit_to_dag
    dagcircuit.add_qreg(register)
  File "dagcircuit.py", line 280, in add_qreg
    self._add_wire(qreg[j])
  File "dagcircuit.py", line 318, in _add_wire
    raise DAGCircuitError("duplicate wire %s" % (wire,))
qiskit.dagcircuit.exceptions.DAGCircuitError: 'duplicate wire None'

### CODE REVIEW

**Comment by javabster** [comment]
Hi @WiFisunset I think what you're trying to do here is functionality that already exists 😅 If you're looking for something to contribute it might be better to take a look at issues that are already open and ask to be assigned to one. If it's your first time you can also filter the issues by the 'good first issue' label

**Comment by WiFisunset** [comment]
> Hi @WiFisunset I think what you're trying to do here is functionality that already exists 

I was starting to think that too, my original goal was to input "Hello World" into an initialized state. But there are a lot of issues I'm running into in trying to get the code to work (which I do want to solve), but I've been trying to figure out why I want to do specifically that. 

And I have a question that I can't answer in my head when thinking about it (@javabster I need help answering it tbh). Is qiskit a Programming Language? Or more of a "library" of quantum functions and classes (like how numpy is something I can import, but it's not a language). I think that's why I'm taking the approach of really wanting to have "Hello World" as an input, I'm thinking of qiskit structurally as a programming language (like python and others, where the user doesn't have to convert to binary manually).

**Comment by javabster** [comment]
Hi @WiFisunset GitHub isn't really the right forum for this kind of discussion 😄 I'd recommend going through the [Qiskit Textbook](https://qiskit.org/textbook/preface.html) for a better understanding, and putting questions in the Qiskit Slack or Stack Exchange for further discussion with the community

**Comment by WiFisunset** [comment]
Thanks so much for the suggestion. I'm going to close this out because I got the function to work in quantumcircuit.py (#6517).

**Pull request closed without merging**
