### PR TITLE
Text and LaTex drawers do pi fractions now

### PR DESCRIPTION
**Pull request by nonhermitian**
### Summary
```
        ┌──────────────┐       
q_0: |0>┤ U2(2pi,pi/3) ├─■─────
        └──────────────┘ │pi/4 
q_1: |0>─────────────────■─────
                               
 c_0: 0 ═══════════════════════
                               
 c_1: 0 ═══════════════════════
```

### CODE REVIEW

**Comment by 1ucian0** [comment]
This is a nice change! How other drawers handle it? If it's something that other drawers also need, maybe can be moved `qiskit/visualization/utils.py`. Or even a pass? @ajavadia?

**Comment by nonhermitian** [comment]
The mpl drawer has similar functionality, but it does not quite work right, and the code is hacky. I do not think latex drawer does this. 

Someone could extend the others using the same check code.

**Comment by nonhermitian** [comment]
I have moved the pi check code into visualizations, cleaned it up to return strings, and added latex string support.  So extending it to other circuit drawers should be fairly straight forward.

**Comment by t-imamichi** [comment]
mpl has pi format mode. See [12] of https://github.com/Qiskit/qiskit-tutorials/blob/dd676abdb7cc53df17050e5ea454505298a0fc8f/to_sort/circuit_drawing.ipynb
image

**Comment by nonhermitian** [comment]
Yeah but it is a bit inconsistent.  Does look for more advanced fractions up to 100 though:

Screen Shot 2019-07-18 at 11 20 27 AM
Screen Shot 2019-07-18 at 11 20 34 AM
Screen Shot 2019-07-18 at 11 20 42 AM

**Comment by nonhermitian** [comment]
If you want to port the mpl version over to the other drawers I am fine with that.  You can feel free to close this if that is the desire.

**Comment by nonhermitian** [comment]
I have added other fractions up to a denominator of 8.

```
        ┌───────────────┐
q_0: |0>┤ U2(pi,-5pi/8) ├
        └───────────────┘
```

this should cover most real-world cases, and does only 64 iterations vs. the 9801 iterations per parameter that the mpl version does.

**Comment by nonhermitian** [comment]
Added pi fractions to latex drawer.

**Comment by t-imamichi** [comment]
I don't intend to port mpl pi format to the other drawers. I wanted to answer this question. https://github.com/Qiskit/qiskit-terra/pull/2808#issuecomment-512277436
Yes, mpl pi format covers denominator up to 99 because I thought it covers many use cases. If you have any suggestion to realize the same behavior as text and latex drawer, I can adjust mpl.

**Comment by 1ucian0** [comment]
I replaced the mpl implementation with the suggested function in https://github.com/Qiskit/qiskit-terra/pull/2808/commits/c750691096778262f855f810e1ed335143c07aae

**Comment by t-imamichi** [comment]
How about using a unicode character 'π' instead of 'pi' for text drawer?

**Comment by ajavadia** [comment]
can we just remove `usepiformat` from `mpl` and have that be the default behavior?

**Comment by nonhermitian** [comment]
The previous way was over an order of magnitude slower than with off. Should check again first

**Comment by nonhermitian** [comment]
Using unicode pi is a good suggestion. However sympy.pi prints as just pi, so we would need to account for that as well

**Comment by nonhermitian** [comment]
For the record, the text drawer is over an order of magnitude faster than the mpl one, and for whatever reason, it is now faster to use mpl with the pi mode on than it is to have it off (about 50% faster, vs 10x slower with the previous pi implementation).  So lets make it on by default as @ajavadia suggested.

**Comment by nonhermitian** [comment]
I can not get unicode pi to play well with monospaced fonts, so just printing `pi` seems the way to go.

**Pull request merged**
