### PR TITLE
Add custom gate support to latex circuit drawer

### LINKED ISSUE #1942: latex drawer cannot draw custom gates
### What is the expected enhancement?
Currently only the text drawer is able to do this. This capability is useful when defining hiearchical circuits.

Also refer to #1939 for a discussion of how to draw these.

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

This commit adds support to the latex circuit drawer backend to draw
custom gates. Currently when a circuit with a custom element is passed
into the latex circuit drawer it is silently ignored and not drawn. This
supports a custom gate with any number of qubits. This also has a bonus
effect if there was a standard gate which wasn't accounted for in the
latex drawer (we've had bugs like this in the past, see #1880) this will
also fix that for us, assuming the node name matches the expected gate
name (which isn't always the case). The only limitation with this is that
it doesn't support conditionals on the custom gates, which is a limitation
with the upstream qcircuit library for right now (we can prioritize adding it
for a future release if it's important).

### Details and comments

Fixes #1942

This depends on #1816 to be usable, but is a standalone improvement and
won't effect anything by itself.

### CODE REVIEW

**Comment by mtreinish** [comment]
Testing this with #1816 locally by running a script like:

```
from qiskit import QuantumRegister
from qiskit import QuantumCircuit
from qiskit.circuit import Gate

q = QuantumRegister(3)
circ = QuantumCircuit(q)
my_gate = Gate(name='CustomGate', num_qubits=2, params=[])
circ.append(my_gate, [q[0], q[1]])
circ.append(my_gate, [q[1], q[2]])
circ.draw(output='latex', filename='/tmp/foo.png')
```

yields a png file like:

foo

**Comment by ajavadia** [comment]
I noticed a couple bugs here when I tweaked your example:

1- It can't draw gates on non-adjacent wires
```python
from qiskit import QuantumRegister
from qiskit import QuantumCircuit
from qiskit.circuit import Gate

q = QuantumRegister(3)
circ = QuantumCircuit(q)
my_gate = Gate(name='CustomGate', num_qubits=2, params=[])
circ.append(my_gate, [q[0], q[2]])
circ.draw(output='latex', filename='/tmp/foo.png')
```
image

2- It can't draw gates when qubit 0 has a higher index than qubit 1. In #1939, I suggested putting a small number at the input so it's clear which wires the gate is attached to, and in which order.

```python
from qiskit import QuantumRegister
from qiskit import QuantumCircuit
from qiskit.circuit import Gate

q = QuantumRegister(3)
circ = QuantumCircuit(q)
my_gate = Gate(name='CustomGate', num_qubits=2, params=[])
circ.append(my_gate, [q[1], q[0]])
circ.draw(output='latex', filename='/tmp/foo.png')
```

image

**Comment by mtreinish** [comment]
Ok, I can fix the second case pretty easily and will push a fix for that shortly (to draw the box correctly only). 
But, to fix the first one and the add the numbers to the gate (which is really necessary to fix it, otherwise it'll just look like a 3 qubit gate) I think I'll have to modify the upstream qcircuit library to accomplish that. I don't believe there is a method to annotate the inputs in the latex as we generate it today and visualize that as you suggested in #1939 .

**Comment by ajavadia** [comment]
I would say that for the first one at least fix the range so that the box draws on the right wires (even if it looks like a 3-qubit gate for now). I agree that adding the little numbers inside the box are harder and can leave that for a follow-up PR.

**Comment by mtreinish** [comment]
@ajavadia ok I think I fixed the cases you outlined with: https://github.com/Qiskit/qiskit-terra/pull/2049/commits/20e4c0bfdbf53b93cacb3774d97dbbef0f120a73 but can you test it further. I'm sure there are more edge cases in there.

**Comment by ajavadia** [comment]
@mtreinish works well! There are just some print statements in there that you have to remove.
I'll make a follow up issue for numbering the active wires.

**Pull request merged**
