### PR TITLE
fixed issue 5862 by updating the basis gates

### LINKED ISSUE #5862: CrosstalkAdaptiveSchedule needs to be updated according to the latest basis gates
### Information

- **Qiskit Terra version**: 0.16.4
- **Python version**: 3.8
- **Operating system**: Ubuntu 18.04

### What is the current behavior?

> BackendPropertyError: BackendPropertyError: 'Could not find the desired property for u1'

### Steps to reproduce the problem
```
crosstalk_prop = {}
#Add crosstalk properties
backend = provider.get_backend('ibmq_casablanca')
bprop = backend.properties()
pass_ = CrosstalkAdaptiveSchedule(bprop, crosstalk_prop)
```

### What is the expected behavior?
There should be no errors.

### Suggested solutions
In [this function](https://github.com/Qiskit/qiskit-terra/blob/47f2faf9560deb2b1ffdab94fe3f4371485aae2a/qiskit/transpiler/passes/optimization/crosstalk_adaptive_schedule.py#L140) , it uses `backend_prop.gate_length('u1', qid)`, and same for ``u2, u3``, which are the previous basis gates. Since the basis gates have been changed to `rz, sx`, this code should be updated as well. Otherwise, we cannot use this compiler.

### PR DESCRIPTION
**Pull request by peachnuts**
### Summary
Fixes #5862 by updating basis gates, modifying gate duration, and adding gate error qid.

### Details and comments

1. The basis gates of [crosstalkAdaptiveSchedule](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/transpiler/passes/optimization/crosstalk_adaptive_schedule.py) and [test_crosstalk_adaptive_schedule](https://github.com/Qiskit/qiskit-terra/blob/master/test/python/transpiler/test_crosstalk_adaptive_scheduler.py) are updated as `rz, sx, x,cx`.
2. The [duration of the gate](https://github.com/Qiskit/qiskit-terra/blob/7c7a956d53c742b0f14a090557bec1fd6757fb72/qiskit/transpiler/passes/optimization/crosstalk_adaptive_schedule.py#L151) is modified. It is always 0 for every gate in the previous version.
3. Add [qid](https://github.com/Qiskit/qiskit-terra/blob/7c7a956d53c742b0f14a090557bec1fd6757fb72/qiskit/transpiler/passes/optimization/crosstalk_adaptive_schedule.py#L155) to every single-qubit gate error.

### CODE REVIEW

**Review by mtreinish — COMMENTED** [review]
While this looks good to me as a fix specifically for the ibm backends I do wonder if we should make this pass more general? The basis gates for backends aren't fixed (both in a single provider and between providers). So I'm wonder how useful this pass is in practice without being basis aware.

**Comment by peachnuts** [comment]
> While this looks good to me as a fix specifically for the ibm backends I do wonder if we should make this pass more general? The basis gates for backends aren't fixed (both in a single provider and between providers). So I'm wonder how useful this pass is in practice without being basis aware.

Since the Crosstalk_Adaptive_Scheduler requires the crosstalk properties of the real quantum device, I think it's more useful when we want to execute a circuit on the real device to mitigate the crosstalk error. An error will appear because of the inconsistency between the general basis gates and the basis gates of IBM devices.

**Comment by HuangJunye** [comment]
This PR has been staled for more than a year. @peachnuts are you still working on it? Do you need further comments from @mtreinish to proceed? Please let us know how we can help.

**Comment by jakelishman** [comment]
Closing due to inactivity.

**Pull request closed without merging**
