### PR TITLE
Use Sabre by default for optimization levels 1 and 2

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

This commit updates the preset pass manager construction to use the
`SabreLayout` and `SabreSwap` passes by default for optimization level 1 and
level 2. With the recently merged #7977 the performance of the sabre
swap pass has improved significantly enough to be considered for use by
default with optimization levels 1 and 2. While for small numbers of
target device qubits (< 30) the `SabreLayout`/`SabreSwap` pass doesn't quite
match the runtime performance of `DenseLayout`/`StochasticSwap` it typically
has better runtime performance for larger target devices. Additionally,
the runtime performance of Sabre should also improve further after #8388
is finished. However, the output quality from the sabre passes is
typically better resulting in fewer swap gates being inserted. With the
combination of better quality and comparable runtime performance it
makes sense to use sabre as the default for optimization levels 1 and 2.
For optimization level 0 stochastic swap is still used there because we
want to continue to leverage `TrivialLayout` for that level and to get
the full quality advantages `SabreSwap` and `SabreLayout` should be used
together.

### CODE REVIEW

**Comment by mtreinish** [comment]
For some data backing this change up, I ran these benchmarks: https://github.com/Qiskit/red-queen/tree/main/red_queen/games/mapping/benchmarks/misc#readme to compare `SabreLayout`/`SabreSwap` with `DenseLayout`/`StochasticSwap` which yielded the following plots:

For CX gate count post routing:

mapping_bench_kdk_view

For runtime performance of layout and routing:

mapping_bench_kdk_view_time

**Comment by nonhermitian** [comment]
This is nice.

**Comment by kdk** [comment]
💯 , can you add the scripts to generate these plots as an example somewhere in `red-queen`?

**Comment by gushuli** [comment]
Thank you for your efforts in redeveloping Sabre in Rust! I really appreciate it~

Gushu

**Comment by mtreinish** [comment]
Since #8388 is ready for review now I reran the benchmark script used above with #8388 applied to get a feel for the relative performance after it merges:

mapping_bench_kdk_view
mapping_bench_kdk_view_time

With #8388 it looks like Sabre is faster most of the time and definitely scales better for larger inputs and target devices.

I also added a graph showing the output circuit depth after running `SabreLayout` and `SabreSwap` on the input circuits:

mapping_bench_kdk_view_depth

The interesting thing there is that circuit depth seems to increase slightly when using sabre but the overall swap count decreases.

**Comment by kdk** [comment]
For the 0.22 release, there is a goal of having the preset pass managers support control flow, so before we can merge this we should have a plan or PR for integrating control flow support in sabre, similar to  https://github.com/Qiskit/qiskit-terra/pull/8565 .

**Comment by jakelishman** [comment]
@kdk: or we can cheat, and use Sabre by default if there's no control flow, and whatever we've got if there is.

**Comment by kdk** [comment]
Following some discussion with the team, the current plan is to start with `Dense`+`StochasticSwap` as default for circuits with control flow (as part of #8630 and #8418 ), and implement control flow handling with `SabreSwap`/`SabreLayout` post 0.22 release.

**Review by kdk — APPROVED** [review]

**Pull request merged**
