### PR TITLE
Added calibrations annotation to matplotlib

### LINKED ISSUE #5920: Circuit drawers should indicate which gates have been overloaded with pulse gates
### What is the expected enhancement?
The circuit drawers will have some indication whether or not a gate has been replaced with a custom pulse gate ("calibration")/.

### PR DESCRIPTION
**Pull request by wmurphy-collabstar**
Fixes #5920

### Summary
This is my work in progress for fixing issue #5920 . Currently, what @1ucian0 added is a calibrations attribute to the matplotlib drawer in order to check to see if a gate has calibrations. I'm currently working on editing the label when the gate has calibrations added.

### CODE REVIEW

**Comment by javabster** [comment]
hi @wmurphy-collabstar are you still working on this? Let us know if you have any questions 😄

**Comment by wmurphy-collabstar** [comment]
> hi @wmurphy-collabstar are you still working on this? Let us know if you have any questions 😄

Hello @javabster, I'm still working on this, but it's slow going. Thank you for the offer, I'll reach out when I do have questions :)

**Comment by wmurphy-collabstar** [comment]
I have committed new changes, which include a cal label for 2 qubit gates. But there is a bit of a formatting issue. For example, when I create a circuit where the cx gate has a long label:
   ```
   from qiskit import QuantumCircuit
   circuit = QuantumCircuit(2, 2)
   circuit.ch(0,1,label="label for the control hadamard gate")
   circuit.draw('mpl')
   ```
image

And then add calibrations to it, I get this output:
```
from qiskit import pulse

with pulse.build(name='ch') as ch_q01:
    pulse.play(pulse.library.Gaussian(duration=128, amp=0.1, sigma=16),
                pulse.DriveChannel(1))

circuit.add_calibration('ch', [0,1], ch_q01)
circuit.draw("mpl")
```
image

Does anyone have any suggestions about what might help with this issue or is it not that big of an issue?
@nonhermitian Does this representation of calibrations look like what you imagined for labeling calibrations? Is there something else you think would be useful to add?

**Comment by wmurphy-collabstar** [comment]
It's been a while since I've commented here, and that's because I put less time into this pull request. What I just committed to this pull request are some of the updates I've made, which includes adding the "cal" label to the swap gate and the reset gate, and trying to add it to the RZZ and RXX gates, but it either doesn't appear (for RZZ gate) or appears in the wrong place (RXX gate). Here's a picture below illustrating that:

Screen Shot 2021-08-02 at 9 47 05 AM

This issue, and the issue of readability when there are already long labels present for the gate, are where I'm stuck. I'm going to try to resolve the conflicts in the conflicting files. Other than that, I don't have a plan of how to proceed.

**Comment by javabster** [comment]
Hi @wmurphy-collabstar sorry for the delay in responding 😄 

for the issue of RZZ not showing the (cal) label I think this is because you add the (cal) text to the `gate_text` attribute but the side text for that type of gate (set on line 1361 of `matplotlib.py`) adds `ctrl_text` (which is `None` for rzz gates).

for the Rxx issue where are you intending for the (cal) to be located? If you want it to go on the same line as the pi in your screenshot then I think you will need to update the `get_param_str` function in `utils.py`

**Comment by javabster** [comment]
@1ucian0 I've polished this up a bit and I think it achieves the minimum requirements, just a couple v small issues (maybe for a future PR?):

- the layer width calcs include `\n` so the gates and labels with `(cal)\n` are wider than they need to be (this leads to too much spacing e.g. around the Rzz label)
- perhaps using `\n` is not advisable and instead the positioning should just be set by `ypos`?

**Comment by javabster** [comment]
for completeness, screenshots of other spacing issues now fixed:
Screenshot 2021-08-20 at 11 38 36
Screenshot 2021-08-20 at 11 39 06

**Comment by nonhermitian** [comment]
I think this looks about as good as one can get given the static format of the plots.  As the circuits has gotten enriched, it is hard to create a faithful static image of them.  This helps in that regard.

**Comment by 1ucian0** [comment]
Thanks @javabster ! Can you squash the commits so we can merge it?

**Comment by 1ucian0** [comment]
Thanks!

**Review by 1ucian0 — APPROVED** [review]

**Pull request merged**
