### PR TITLE
Deprecate the CouplingMap.subgraph() method

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

The `CouplingMap.subgraph()` method has overlapping functionality with the
`reduce()` method as both return a new `CouplingMap` object with a subset of
nodes from the original. In practice the only difference between the 2 is
that `subgraph()` doesn't retain the input list order for the output
coupling map while `reduce()` does. Since there is likely a use case for
retaining that list order this commit deprecates the `subgraph()` method
so we don't maintain duplicate methods.

It's worth noting that the `subgraph()` method is probably slightly faster
as it just calls retworkx's subgraph. So if you don't care about node list order
You can still do use this method with the `CouplingMap` API by just doing
something like:
```python
subgraph = CouplingMap()
subgraph.graph = original_cmap.graph.subgraph(node_list)
```
instead of:
```python
subgraph = original_cmap.subgraph(node_list)
```

### CODE REVIEW

**Comment by jakelishman** [comment]
The deprecation is clearly fine - the failure is due to the relevant test not marking the call as deprecated.  If we want to support the form suggested in the commit message, perhaps we should change/add to the failing test (in test/python/transpiler/test_coupling.py line 199) to try that path.

**Review by jakelishman — DISMISSED** [review]
Ha - I actually wrote that _exact_ same patch this morning, but then thought "nah, it's a bit rude to push to someone else's branch"!

**Review by jakelishman — DISMISSED** [review]
I just pushed a super minor wording tweak to the release notes, because the GitHub outage yesterday had left this PR out-of-sync with its tests, and consequently it was blocking the mergify bot from doing anything.  Azure reported that all tests finished successfully 20 hours ago, but that was in the middle of the GH downtime, and the PR status seemed to have become frozen.

This should get things moving again, and free up the bot.

**Comment by mtreinish** [comment]
@jakelishman it looks like github got confused again it said I dismissed your review by https://github.com/Qiskit/qiskit-terra/pull/6823/commits/f7a644a3ae65bdeb9cc12416256e9d18ba7e3952 which you pushed.

**Review by jakelishman — APPROVED** [review]
Maybe I just reviewed too soon after pushing the commit.  Strange, but let's try again!  At any rate, the tweak commit had the desired effect - it unblocked the bot, which has now been chugging its way through a 4-5 PR backlog.

**Pull request merged**
