### PR TITLE
#1586: avoid dependencies duplicity

### PR DESCRIPTION
**Pull request by iblancasa**
### Summary
This change introduces a way to avoid dependencies duplicity in the `requirements.txt` and `setup.py` files. Now, you only need to add the dependencies to `requirements.txt`.

### Details and comments
Link to the issue [#1586](https://github.com/Qiskit/qiskit-terra/issues/1586)

### CODE REVIEW

**Comment by iblancasa** [comment]
@ajavadia perfect! :)

**Comment by 1ucian0** [comment]
hi @iblancasa,
    After talking with @diego-plan9 and @delapuente, it seems the agreement is to go the other way around, in which requirements depends on setup. Can you update and adapt your PR to follow https://github.com/Qiskit/qiskit-terra/issues/1586#issuecomment-454024429 ? let us know if you have thoughts about it.

**Comment by iblancasa** [comment]
Hi @1ucian0,

Sure! I will work on that as soon as possible :D

**Comment by 1ucian0** [comment]
Shall we close this PR for now? It isn't merging and the change to do is just too different. Feel free to reopen if you disagree.

**Pull request closed without merging**
