### PR TITLE
speeling fixes

### PR DESCRIPTION
**Pull request by levbishop**
Fixed a bunch of typos.
Added a local wordlist and pylint spelling configuration -  makes it a little less noisy, but far from quiet enough to enable by default.

### CODE REVIEW

**Comment by ajavadia** [comment]
I like that your commit says "speeling fixes" ;)

**Comment by woodsp-ibm** [comment]
Nice - we had spelling running on Aqua since the docstrings end up as the published documentation it made sense to us to fix them in build. 

I note you changed `parametrized` to `parameterized`. I recall looking at that and the former is an accepted spelling but standardizing on the latter seems fine.

In your exception list you have `favour` and while I can approve of that along with colour, neighbour etc I would have thought it should be `favor` since its supposed to all be US English, no?

**Comment by levbishop** [comment]
> Nice - we had spelling running on Aqua since the docstrings end up as the published documentation it made sense to us to fix them in build.

Yeah it would be nice to get to the point to turn it on by default, but the pylint spelling checker is fairly unintelligent and for example doesn't add the names that are in scope locally to the wordlist, doesn't ignore sphinx directives, inline tex, etc. Don't want to discourage contributors from writing more docstrings by making them fight with pylint.

> I note you changed `parametrized` to `parameterized`. I recall looking at that and the former is an accepted spelling but standardizing on the latter seems fine.

Parametrize{,d} looked so obviously wrong to me I didn't even think to check... Seems like both are used, but parameterize is  quite a bit more common.

> In your exception list you have `favour` and while I can approve of that along with colour, neighbour etc I would have thought it should be `favor` since its supposed to all be US English, no?

My schooling coming through there. Probably best to go all US.

**Comment by levbishop** [comment]
> > In your exception list you have `favour` and while I can approve of that along with colour, neighbour etc I would have thought it should be `favor` since its supposed to all be US English, no?
> 
> My schooling coming through there. Probably best to go all US.

On the other hand we already have (favoured internationally) `JobStatus.CANCELLED` in the code (not just docs) and I don't feel the need break the API and switch to (favored in US) `JobStatus.CANCELED` etc as long as we are consistent, which we seem to be.

**Review by lcapelluto — APPROVED** [review]

**Pull request merged**
