### PR TITLE
Reverts #4207: allow setting label on circuit append

### LINKED ISSUE #4257: Initialize tutorial example fails to draw
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
```python
# Initializing a three-qubit quantum state
import math
desired_vector = [
    1 / math.sqrt(16) * complex(0, 1),
    1 / math.sqrt(8) * complex(1, 0),
    1 / math.sqrt(16) * complex(1, 1),
    0,
    0,
    1 / math.sqrt(8) * complex(1, 2),
    1 / math.sqrt(16) * complex(1, 0),
    0]

q = QuantumRegister(3)

qc = QuantumCircuit(q)

qc.initialize(desired_vector, [q[0],q[1],q[2]])
qc.draw(output='mpl')
```

gives

```
/opt/miniconda3/lib/python3.7/site-packages/qiskit_terra-0.14.0-py3.7-macosx-10.9-x86_64.egg/qiskit/visualization/matplotlib.py in _draw_ops(self, verbose)
    856                     vec = '[%s]' % param
    857                     self._custom_multiqubit_gate(q_xy, wide=_iswide,
--> 858                                                  text=op.op.label or "|psi>",
    859                                                  subtext=vec)
    860                 elif op.name == 'unitary':

AttributeError: 'Initialize' object has no attribute 'label'
```

### PR DESCRIPTION
**Pull request by 1ucian0**
Reverts #4207 

Related #4252. I keep #4252 to keep the discussion open.

Fixes #4257

The performance regressions stays there, because they type checking in append is being used right now.

### CODE REVIEW

**Comment by 1ucian0** [comment]
Because the documentation was triggering https://github.com/Qiskit/qiskit-terra/issues/4257, this also fix it.

**Comment by ajavadia** [comment]
this is preventing circuits from drawing as their labels were intended:

```py
from qiskit.circuit.library import Permutation
A = [2,3,0,1]
circuit = Permutation(4, A)
print(circuit)
```

on master:
```
     ┌────────────────────────┐
q_0: ┤0                       ├
     │                        │
q_1: ┤1                       ├
     │  permutation_[2,3,0,1] │
q_2: ┤2                       ├
     │                        │
q_3: ┤3                       ├
     └────────────────────────┘
```

in this branch
```
     ┌────────────┐
q_0: ┤0           ├
     │            │
q_1: ┤1           ├
     │  circuit63 │
q_2: ┤2           ├
     │            │
q_3: ┤3           ├
     └────────────┘

```

**Comment by 1ucian0** [comment]
> There's a left over append in `iqp.py`.

Fixed in 4e204423588c4fa951bf71972475dcda7142ff00

**Comment by 1ucian0** [comment]
> this is preventing circuits from drawing as their labels were intended:

For the permutation case, the fix is in bff48e3cae93bb0525f19abddba7b5c789ce1228

**Comment by jaygambetta** [comment]
what do you get when you draw the quantum volume and then draw quantum volume decompose then draw quantum volume decompose twice.

**Comment by 1ucian0** [comment]
```python
from qiskit.circuit.library import QuantumVolume
circuit = QuantumVolume(2, 2, seed=2, classical_permutation=False)
circuit.draw()
     ┌─────────────────────────┐
q_0: ┤0                        ├
     │  quantum_volume_[2,2,2] │
q_1: ┤1                        ├
     └─────────────────────────┘
```
```python
circuit.decompose().draw()
     ┌────────────────────┐┌──────────┐┌────────────────────┐┌──────────┐
q_0: ┤0                   ├┤0         ├┤0                   ├┤0         ├
     │  permutation_[1,0] ││  su4_837 ││  permutation_[0,1] ││  su4_262 │
q_1: ┤1                   ├┤1         ├┤1                   ├┤1         ├
     └────────────────────┘└──────────┘└────────────────────┘└──────────┘
```
```python
circuit.decompose().decompose().draw()
        ┌────────────────────────────┐      ┌───────────────────┐       ┌────────────────────────┐     ┌───────────────────────────┐ ┌────────────────────┐┌───────────────────────────┐        ┌──────────────────┐      ┌──────────────────────┐     ┌────────────────────────────┐
q_0: ─X─┤ U3(2.9196,-2.6658,0.78547) ├──■───┤ U3(0.90037,-pi,0) ├────■──┤ U3(0.085471,-pi/2,-pi) ├──■──┤ U3(0.77399,-3.451,2.2206) ├─┤0                   ├┤ U3(2.9967,0.17162,5.5334) ├───■────┤ U3(0.8403,-pi,0) ├───■──┤ U3(0.32143,-3pi/2,0) ├──■──┤ U3(0.70106,-4.3433,1.5448) ├
      │ ├────────────────────────────┤┌─┴─┐┌┴───────────────────┴─┐┌─┴─┐└─┬────────────────────┬─┘┌─┴─┐├───────────────────────────┴┐│  permutation_[0,1] │├───────────────────────────┴┐┌─┴─┐┌─┴──────────────────┴┐┌─┴─┐└┬────────────────────┬┘┌─┴─┐├────────────────────────────┤
q_1: ─X─┤ U3(1.5961,-1.7729,-3.9854) ├┤ X ├┤ U3(0.032158,pi/2,pi) ├┤ X ├──┤ U3(pi/2,-pi/2,-pi) ├──┤ X ├┤ U3(0.96619,1.7631,-1.0508) ├┤1                   ├┤ U3(2.1709,-0.39978,5.6485) ├┤ X ├┤ U3(0.40107,pi/2,pi) ├┤ X ├─┤ U3(pi/2,-pi/2,-pi) ├─┤ X ├┤ U3(1.8563,-1.5758,-4.6112) ├
        └────────────────────────────┘└───┘└──────────────────────┘└───┘  └────────────────────┘  └───┘└────────────────────────────┘└────────────────────┘└────────────────────────────┘└───┘└─────────────────────┘└───┘ └────────────────────┘ └───┘└────────────────────────────┘
```

**Pull request merged**
