### PR TITLE
Fix tox.ini for tox 4

### PR DESCRIPTION
**Pull request by ikkoham**
### Summary

Fix the tox when one runs it on `tox4` and the following error occurs:
```
lint-incr: failed with PATH_TO/qiskit-terra/tools/pylint_incr.py (resolves to PATH_TO/qiskit-terra/tools/pylint_incr.py) is not allowed, use allowlist_externals to allow it.
```

### Details and comments

I was taught by @jakelishman how to fix it.
Thank you very much.

### CODE REVIEW

**Review by jakelishman — COMMENTED** [review]
I think there'll probably be similar changes needed in other jobs as well.  Things like `stestr` and `black` should work without extra `allowlist_externals` entries, because they're managed by the Python environment, but at the very least, `testenv:lint` also would need updating with these changes.

(Essentially, tox 4 allows any executable that ends up in the `bin` folder of the Python venv after setup, but nothing else without being explicitly allowed.)

**Comment by ikkoham** [comment]
`tox -e py3x` and `tox -e black` works well. I'm not sure the reason...

**Comment by jakelishman** [comment]
The `py3x` and `black` jobs (and `docs`) only use executables that get installed in the virtual environments `bin` directory by the jobs' requirements (e.g. `python`, `black`, `sphinx-build`).  That directory makes up the default set of allowed executables.  `lint` and `lint-incr` both attempt to run scripts in `<repo root>/tools/` as executables (relying on the hashbang to find `python3` as the executor), which is forbidden.  We get around that either by explicitly using `python` to execute those scripts, which `tox` will allow because it recognises it'll get the Python binary from its virtual environment.

We could also add the files to the `allowlist_externals` manually, but at that point we're relying on the hashbang to find the binary.  That requires the system we're running on to have an executable `/usr/bin/env` and that's beyond the control of `tox`.  It's better to manually invoke `tox`'s managed `python`.

**Comment by jakelishman** [comment]
(we also need to update the `lint` job)

**Comment by ikkoham** [comment]
> (we also need to update the lint job)

Oh! Thank you. I didn't notice that.

**Review by jakelishman — APPROVED** [review]
Thanks, sorry I forgot to come back to this!

**Pull request merged**
