### PR TITLE
Update pylint to 2.3

### PR DESCRIPTION
**Pull request by diego-plan9**
### Summary

After the cleanups in #2465, #2374 and others, we can finally update to the 2.3 version of `pylint`.

### CODE REVIEW

**Comment by mtreinish** [comment]
I would still feel more comfortable if we pin both asteroid and pylint to a known working combination in the constraints.txt file. The reason we had to add them before was because a patch release of asteroid broke pylint 2.2 outright. There is pretty much a 1:1 mapping between asteroid and pylint version that ends up being very fragile in practice, so ensuring we ensure known working versions without any behavior changes is important if we're going to rely on it for CI.

**Comment by diego-plan9** [comment]
I think `2.3,<2.4` should give us a sufficient level of comfort (bar unfortunate and isolated occurrences that might happen with the rest of the packages we depend on as a whole, not only the linter) - we can reevaluate eventually if the problem reoccurs.

**Comment by mtreinish** [comment]
I don't believe it does, and it's not really an isolated occurrence it's happened multiple times already, most recently with #1868 and #1859 which were for different pylint versions. The problem is actually the cap which while it protects us from changes in pylint behavior (which seem to come with every release) the asteroid dependency is very tightly coupled with pylint internals and they don't pin versions of asteroid in pylint's requirements. This leads to a very common situation where asteroid pushes a new release that breaks something pylint relies on. Pylint will fix it for the current release series, but not for our capped version. Just pinning it with constraints provides both a level of repeatability and reliability which we need if we're going to rely on for CI.

**Comment by diego-plan9** [comment]
No worries, all for the sake of the project! In general, I believe that the project would benefit from statements and technical decisions backed by more accurate facts (counting #1868 and #1859 as two separate incidents seems a bit too creative for my taste), but I'm fine leaving that exercise for a separate issue.

**Comment by mtreinish** [comment]
> (counting #1868 and #1859 as two separate incidents seems a bit too creative for my taste)

No, they were very distinct issues that just happened to appear around the same time (only because of no activity on stable for a few months) and had completely different failure signatures. Which is why the fix was different for both even though both involved using a constraints file to pin things to known working versions. The pylint issue in #1859 occurred because of an isort package release and astroid not being pinned for that. It caused an infinite recursion error: https://travis-ci.com/Qiskit/qiskit-terra/jobs/180259803#L2655 To fix that while keeping the old version of pylint we pinned to on 0.7 stable (pylint >1.8,<1.9) we required pinning everything installed from the last stable patch to a known working version (there was likely a dependency overlap somewhere causing an incompatible bump triggering the issue again). 

While #1868 was just us hitting: https://github.com/PyCQA/astroid/issues/649 when astroid 2.2 was released. Upgrading to pylint 2.3 to fix that in the short term wasn't an option for all the reasons this PR mentions (and some other cleanups that landed before those) and there would be no fix for using astroid 2.2 on pylint 2.2. So pinning to the last known working version of astroid and pylint was the best way to avoid that.

**Pull request merged**
