### PR TITLE
Add tools/verify_headers.py to check copyright headers

### LINKED ISSUE #3127: Adapt file headers to Lint specifications
### What is the expected enhancement?

When running the test suite, specifically 'lint' tests for code quality, the same message is displayed for every file in the project:

`************* Module qiskit.tools.visualization
qiskit\tools\visualization.py:1:0: C5001: File header should match regex "(?:(?:#[^\n]*)?\n)*# This code is part of Qiskit.\n#\n# \(C\) Copyright IBM [0-9, -]*.\n#\n# This code is licensed under the Apache License, Version 2.0. You may\n# obtain a copy of this license in the LICENSE.txt file in the root directory\n# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.\n#\n# Any modifications or derivative works of this code must retain this\n# copyright notice, and modified files need to carry a notice indicating\n# that they have been altered from the originals.\n" (invalid-file-header)`

This message, with some variations, appears hundreds of times in the log. That makes it a bit difficult to keep track of the other code smells that should be fixed. Setting a new format for the headers, or making Lint ignore this issue, would remove hundreds of log entries in one go.

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

Currently we're relying on a pylint plugin to verify copyright headers
conform to the project guidelines. However this is problematic for a
number of reasons. The first is it has proven to be unstable there have
been several instances of both users and CI failing on header files that
do not have any issues. This is pretty common with pylint in general
since it's very sensitive to differences in environment. Additionally,
it was using a regex to try and match the entire header string. This
provided no practical debuggability when it fails (especially when the
failure is unexpected) because we end up with only a didn't match error.
This commit addresses these issues by removing the use of the regex
based pylint plugin and adding a small script to verify the header in
every qiskit file and provide useful debugging if there is an issue with
a header in a python file.

### Details and comments

Fixes #3127

### CODE REVIEW

**Comment by mtreinish** [comment]
> Looks good. Can we check that this fixes the issues for contributors on windows?

I haven't been able to locally create a reproduce case for the failures so I haven't been able to verify this fixes it myself. There were PRs in the past that had this problem, but unfortunately none with the failing branches left intact.

**Comment by mtreinish** [comment]
@eddieschoute reported having a problem with the pylint rule locally, maybe he can test this locally to see if it resolves the issue for him.

**Comment by mtreinish** [comment]
I spun up a windows VM locally and did test this script and found a small issue around character encoding, which is fixed by https://github.com/Qiskit/qiskit-terra/pull/4525/commits/223b140107b5ad249070fb296a73fda6870d75f0

**Comment by eddieschoute** [comment]
Seems like the header check passes but it gives an exception later on by running `tox -elint`
```
Traceback (most recent call last):
  File "c:\users\eddie\appdata\local\programs\python\python38\Lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\eddie\appdata\local\programs\python\python38\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\dev\test\qiskit-core\.tox\lint\Scripts\reno.EXE\__main__.py", line 7, in <module>
  File "e:\dev\test\qiskit-core\.tox\lint\lib\site-packages\reno\main.py", line 210, in main
    return args.func(args, conf)
  File "e:\dev\test\qiskit-core\.tox\lint\lib\site-packages\reno\linter.py", line 40, in lint_cmd
    content = load.parse_note_file(f, None)
  File "e:\dev\test\qiskit-core\.tox\lint\lib\site-packages\reno\loader.py", line 116, in parse_note_file
    body = self._scanner.get_file_at_commit(filename, sha)
  File "e:\dev\test\qiskit-core\.tox\lint\lib\site-packages\reno\scanner.py", line 815, in get_file_at_commit
    return self._repo.get_file_at_commit(filename, sha)
  File "e:\dev\test\qiskit-core\.tox\lint\lib\site-packages\reno\scanner.py", line 478, in get_file_at_commit
    return f.read()
  File "e:\dev\test\qiskit-core\.tox\lint\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 529: character maps to <undefined>
ERROR: InvocationError for command 'E:\dev\test\qiskit-core\.tox\lint\Scripts\reno.EXE' lint (exited with code 1)
_______________________________________________________ summary _______________________________________________________
ERROR:   lint: commands failed
```

**Comment by mtreinish** [comment]
Hmm, yeah that stack trace looks like an issue with `reno lint` not the script being added here. We probably should report the bug to them, it looks like the reno scanner module doesn't set an encoding on the files when it reads them: https://opendev.org/openstack/reno/src/branch/master/reno/scanner.py#L477 which is what I had to fix in the script here in: https://github.com/Qiskit/qiskit-terra/pull/4525/commits/223b140107b5ad249070fb296a73fda6870d75f0

I'm pretty sure these encoding errors are coming from https://github.com/Qiskit/qiskit-terra/issues/2616 when we added text drawer visualizations inline to the documentation or release notes.

**Comment by mtreinish** [comment]
I opened a bug on reno about the character encoding failure here: https://storyboard.openstack.org/#!/story/2007757

**Pull request merged**
