### PR TITLE
Create string_initialization function

### PR DESCRIPTION
**Pull request by WiFisunset**
### Summary
The goal is to eventually map chars and strings to initializations, in the case that the following might yield more use cases and unique results: a -- > binary (01000001)--> initialized state --> QuantumCircuit Output (result 1); followed by, b -- > binary (01000010) --> initialized state --> QuantumCircuit Output (result 2). Comparing result1 and result 2 when applying some set of gates, may help form more algorithms possibly.

### Details and comments
Creates a class that takes a classical input like 'a', converts to binary (in this case: 01000001), and then maps that to an initialized state for the QuantumCircuit.

Note: Should throw an error if the output of the converted char (or string eventually), is less than the (2**qubits function that's a WIP Pull Request at the moment).

Note2: This is a Work-In-Progress, and suggestions on where this function should be located in Terra (or if it's better to do this as a class) would be appreciated.

### CODE REVIEW

**Comment by WiFisunset** [comment]
Completed the function, in that it works as intended. It takes in a string input, converts it to binary, and then assigns x gates for each  "1" in the index of the binary string. 

The function also raises a CircuitError if the string produces a binary string that's longer than the number of qubits in the Circuit,

I've tested converting the output given into a gate using to_instruction (naming the gate after the string input, and that works as well. That is included in the test file attached as a txt). 

Note: I'll also add in the error output, the length of the binary string so the user knows what number of qubits is needed for the circuit to work.

[test.txt](https://github.com/Qiskit/qiskit-terra/files/6613375/test.txt)

**Comment by Cryoris** [comment]
Hi @WiFisunset, I think this feature already exists in `QuantumCircuit.initialize` 🙂 
```python
>>> from qiskit import QuantumCircuit
>>> qc = QuantumCircuit(3)
>>> qc.initialize("101", qubits=[0, 1, 2])
>>> qc.decompose().draw()
          ┌───┐
q_0: ─|0>─┤ X ├
          └───┘
q_1: ─|0>──────
          ┌───┐
q_2: ─|0>─┤ X ├
          └───┘
```

**Comment by WiFisunset** [comment]
> Hi @WiFisunset, I think this feature already exists in `QuantumCircuit.initialize` 🙂
> 
> ```python
> >>> from qiskit import QuantumCircuit
> >>> qc = QuantumCircuit(3)
> >>> qc.initialize("101", qubits=[0, 1, 2])
> >>> qc.decompose().draw()
>           ┌───┐
> q_0: ─|0>─┤ X ├
>           └───┘
> q_1: ─|0>──────
>           ┌───┐
> q_2: ─|0>─┤ X ├
>           └───┘
> ```

Thanks! I'm going to relocate this suggested function change to initializer.py. It takes in a str label to initialize, but not strings --> binary --> XGates in reversed order (I'm thinking words as input will help abstract things even further and give programmers more options to use). 

I'll close out this PR and reopen one under initializer.py. Thanks for pointing that out 🙂!

**Comment by WiFisunset** [comment]
I'm reopening this PR, because I was able to get it to work (string input to initialization). Though, when using more than a 5 letter word in testing it out with circuits added, it runs out of memory. I have to go through it again to maybe add an error for if the string is too long (if that even needs to be mitigated for the time being, I think the error it gives is pretty direct, but this error add is just a suggestion).

**Comment by Cryoris** [comment]
Ok, now I see what you want to implement. Do you have a practical use-case where converting characters to binaries is frequently needed? 

Otherwise I'd suggest that this is more a special case that we should leave to the users by converting characters manually (e.g. using https://stackoverflow.com/questions/7396849/convert-binary-to-ascii-and-vice-versa). Especially since we're trying to only add essential methods to the circuit class to avoid overcrowding it.

**Comment by jakelishman** [comment]
I'm going to close this for inactivity now, and because in general, I believe the feature it is trying to add is too specific for Terra and would be better handled by a simple utility function that maps general strings to bit strings, so that they can simply be fed to `QuantumCircuit.initialize`.  Feel free to open a new discussion if I've missed something, though.

**Pull request closed without merging**
