### PR TITLE
Classical condition boxes are now drawn as bullets in text drawer

### LINKED ISSUE #6290: Inconsistency in drawing classical control in text drawer when cregbundle=False
### Information

- **Qiskit Terra version**: 0.18.0.dev0+b026000
- **Python version**: 3.7
- **Operating system**:

### What is the current behavior?

The classical control is currently drawn in text drawer as a box with control value inside it when cregbundle=False. This is inconsistent with the other drawers in which the same is drawn as bullets.

### Steps to reproduce the problem

We have the following for example:

``` python
from qiskit import *

q = QuantumRegister(2,'q')
c = ClassicalRegister(2,'c')
circ = QuantumCircuit(q,c)
circ.h(0).c_if(c,2)
```

Text drawer draws this circuit as 

text_control_error

while the latex drawer and mpl draws the same as

latex_control_correct

mpl_control_correct

### What is the expected behavior?

For consistency, the classical control in text drawers should be drawn using open and closed bullets.

### PR DESCRIPTION
**Pull request by TharrmashasthaPV**
### Summary

Fixes #6290 .

### Details and comments

In this PR, the classical condition boxes are replaced with open and close bullets when cregbundle=False. This ensures that the text drawer drawings of classical conditioned gates are consistent with that of the latex and mpl drawers.

For instance, the example circuit given in #6290 is now drawn as 

ex_1

Update:
     As it was suggested in the comment, the conditional value is also drawn along with the circuit. It looks like the following
```
     ┌───┐
q_0: ┤ H ├
     └─╥─┘
q_1: ──╫──
       ║  
c_0: ══o══
       ║  
c_1: ══■══
       =2 

```

Also the existing tests have been modified and new tests have been added.

### CODE REVIEW

**Comment by 1ucian0** [comment]
This is great! Can we still keep the dec representation of the condition?
```
     ┌───┐
q_0: ┤ H ├
     └─╥─┘
q_1: ──╫──
       ║  
c_0: ──o──
       ║  
c_1: ──■──
      0x2
```
Like MPL:
image

**Comment by TharrmashasthaPV** [comment]
> This is great! Can we still keep the dec representation of the condition?
> 
> ```
>      ┌───┐
> q_0: ┤ H ├
>      └─╥─┘
> q_1: ──╫──
>        ║  
> c_0: ──o──
>        ║  
> c_1: ──■──
>       0x2
> ```
> 
> Like MPL:
> image

Hey @1ucian0 . I was actually unable to give the condition value as '0x2' as that would require a significant amount of code change. However, in the new circuit diagram the condition values are given as '=2'. I suppose that is fine.

**Comment by enavarro51** [comment]
@TharrmashasthaPV #5938 fixes a problem with condition bits not reordering when `reverse_bits `is set. This was not addressed for the text drawer, because it wasn't showing the condition bits. Now that your PR fixes that, the `reverse_bits `issue should be addressed, either here or in a new issue. The fix is fairly simple
- In `circuit_visualization.py`, pass `reverse_bits` to the text drawer.
- In the text drawer `__init__` add `self._reverse_bits = reverse_bits`
- In `set_cond_bullets,` your current line 1474 could change to
```
vlist = list(val) if self._reverse_bits else list(val[::-1])
```

**Review by 1ucian0 — CHANGES_REQUESTED** [review]
Dont forget the reno!

**Comment by TharrmashasthaPV** [comment]
> @TharrmashasthaPV #5938 fixes a problem with condition bits not reordering when `reverse_bits `is set. This was not addressed for the text drawer, because it wasn't showing the condition bits. Now that your PR fixes that, the `reverse_bits `issue should be addressed, either here or in a new issue. The fix is fairly simple
> 
> * In `circuit_visualization.py`, pass `reverse_bits` to the text drawer.
> * In the text drawer `__init__` add `self._reverse_bits = reverse_bits`
> * In `set_cond_bullets,` your current line 1474 could change to
> 
> ```
> vlist = list(val) if self._reverse_bits else list(val[::-1])
> ```

Sorry @enavarro51 . I missed your comment somehow. Sure, I will fix that. Just to keep things a bit simple, I will push that as a different PR. Thanks a lot for pointing this out!!!

**Comment by 1ucian0** [comment]
Let me know when you add the @enavarro51 fix . Once done, I think it will be ready to go.

**Comment by TharrmashasthaPV** [comment]
Hi @1ucian0 . I have added the fix for the reverse bit as suggested by @enavarro51 . I have also added two tests. I think it is now ready to go.

**Comment by javabster** [comment]
Hi @TharrmashasthaPV this looks good! After merging main there are some deprecation warnings that are causing the CI to fail, could you address them please? Then should be good to go 😄

**Review by 1ucian0 — DISMISSED** [review]
Thanks Tharrma!

**Comment by TharrmashasthaPV** [comment]
I had to push a new commit since there were some conflicts with main. I have resolved the conflicts. The changes were minor. I guess this PR needs a re-review. Sorry for the inconvenience.

**Review by javabster — APPROVED** [review]
This LGTM 🚀 @1ucian0 thoughts?

**Review by 1ucian0 — APPROVED** [review]
Thanks!

**Pull request merged**
