### PR TITLE
Add hinton diagram to plot_state methods

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

The interactive js plot_state visualizations had an additional method
'hinton' for drawing a hinton diagram of the quantum state. However
this method was missing from the non-js plot_state function. This commit
adds the missing method. 

### Details and comments

The hinton diagram implementation here is based
on the example from the matplotlib documentation, which can be found
here: https://matplotlib.org/gallery/specialty_plots/hinton_demo.html

### CODE REVIEW

**Comment by jaygambetta** [comment]
can you post a version of the figure

**Comment by mtreinish** [comment]
@jaygambetta this is what it does now:

hinton

Basically just a 2d version of the cities plot:

city

I still need to look into adding the x and y ticks and labels.

Personally I don't find this super useful, but I only pushed the PR because the iplot_state function (for the js version) supports this method and it was missing from the local version. (as part of #1229 )

**Comment by jaygambetta** [comment]
great. I agree and it looks good. 
I will fix the Pauli but first, i'm dealing with a pip mess and found out the readme is broken a bit so I fix that first.

**Comment by nonhermitian** [comment]
You need a colorbar as well to make it useful:

http://qutip.org/docs/latest/images/visualization-rho-ss.png

**Comment by mtreinish** [comment]
@nonhermitian oh, actually this implementation doesn't do color shading. It's binary colors black (negative) or white (positive) and only the size is adjusted for the value. I didn't check qutip and just referred to the matplotlib docs which did it that way.

**Comment by jaygambetta** [comment]
yeah there is no color bar its the size of the square

**Comment by mtreinish** [comment]
Ok, now with tick marks and labels the same script generates:

hinton

**Comment by jaygambetta** [comment]
does it have to be one above the other. Can they go next to each other

**Comment by mtreinish** [comment]
@jaygambetta sure, I'll put them side by side. I just did top to bottom because I copied the subplot setup from the 3d bar graph function.

**Comment by mtreinish** [comment]
hinton

**Comment by jaygambetta** [comment]
Great. I think we should change the other one as well

**Comment by jaygambetta** [comment]
also I think we should change the order of the city labels to match this

**Comment by mtreinish** [comment]
@jaygambetta sure, can you open an issue for the improvements to the city plots (just so I don't forget about it)

**Pull request merged**
