### PR TITLE
Revert "Add visualization methods to state classes (#4546)"

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

The changes made in this commit have several key issues which should
have been addressed before it merged. The primary issues with the
commit are:

1. it breaks the `__repr__` of the state classes. The expectation of a
   repr is that should look like a valid python expression used to
   recreate the object. [1] This is what existed prior to the PR, the
   repr should not return the output from a drawer.
2. The use of latex and other visualization formatters should be opt-in
   not opt-out in jupyter. The use case for generating latex matrices or
   other visualizations by default from state classes is relatively
   niche and should only be done if users request it (or by default with
   a user config file, although documentation on this was missing).

There was also no way to disable the drawer inside jupyter and return
to the previous behavior which is the primary reason for a revert here.

This reverts commit 884addec150844ad36027a691217c5aeddf114e7 so it can
be reproposed again without these issues which are causing issues for
anyone who relies on the Quantum Info state classes currently and is
using a development version of terra.

### Details and comments

[1] https://docs.python.org/3/reference/datamodel.html?highlight=__repr_#object.__repr__

### CODE REVIEW

**Comment by mtreinish** [comment]
If this is approved and merged this should be re-proposed in 3 PRs. The first adds the array to latex piece as a standalone visualization function that's an easy approval. The second adds a draw method and user config option for the default output style to the state classes which is also a straightforward enhancement. The third which will require more discussion is how we handle the representation of state classes in jupyter.

**Comment by enavarro51** [comment]
And maybe a minor point, but I think the array_to_latex function should be in array.py and not in latex.py, since latex.py is just for the latex drawer, not for utility functions.

**Comment by mtreinish** [comment]
This is going to be superseded by #5881 I still think the original #4546 should have been at least 3 separate PRs and needed more review before it merged, but with #5881 we can fix the critical issues there and roll forward as long as we get everything before the 0.17.0 release.

@enavarro51 I agree do you mind pushing a PR to move that (that way I can approve the PR :) )?

**Comment by enavarro51** [comment]
On the way shortly.

**Pull request closed without merging**
