### PR TITLE
Skip binding when parameter is None

### PR DESCRIPTION
**Pull request by ikkoham**
### Summary

This is a part of https://github.com/Qiskit/qiskit-terra/pull/8367.
This PR reduces deepcopy of the circuit by not calling `bind_parameters` when no parameters exist.

### CODE REVIEW

**Comment by ikkoham** [comment]
@pedrorrivero @caleb-johnson This is the PR for the reference implementation.

**Comment by caleb-johnson** [comment]
Thanks!

> @pedrorrivero @caleb-johnson This is the PR for the reference implementation.

Looks great, thank you for the quick turnaround! We should see big speedups when this is implemented in the Runtime Estimator

**Review by t-imamichi — APPROVED** [review]
LGTM

**Comment by t-imamichi** [comment]
I also updated #8403, which has an optimization of `circuit_to_instruciton`.

**Comment by caleb-johnson** [comment]
> I also updated #8403, which has an optimization of `circuit_to_instruciton`.

Thank you, do you think we should also include the `bound_circuit_to_instruction` function in this PR to prevent `Statevector` constructor from making a copy of the `QuantumCircuit`?

**Comment by t-imamichi** [comment]
Let's merge them separately. I merge this PR first.

**Pull request merged**
