### PR TITLE
ruff executable check

### PR DESCRIPTION
**Pull request by levbishop**
Enable ruff `EXE` category and remove X bit from a few files

### CODE REVIEW

**Comment by jlapeyre** [comment]
This looks good.
It might be useful to add comments or links to aid understanding what the codes mean. I can think of a few situations where it would be  convenient. Just one example: a rule that becomes obsolete would stand out. Maybe like this in pyproject.toml
```shell
 F823 # undefined-local
```

**Comment by levbishop** [comment]
I added the symbolic rule/category ids to the ruff config, and alphabetized.

**Comment by jlapeyre** [comment]
CI fails because `setup.py` has executable bit set.  I think it does not need to be (should not be).

**Comment by jlapeyre** [comment]
Bump to @Eric-Arellano . I clicked the "Update branch" button and merging was reblocked. I suppose it might be legal for me to approve.

**Review by Eric-Arellano — APPROVED** [review]

**Review by mtreinish — APPROVED** [review]

**Pull request merged**
