### PR TITLE
added y axis ticks to schedule.draw()

### LINKED ISSUE #3485: pulse amplitudes not show in schedule.draw()
the amplitudes of pulses are not shown in a schedule and it's hard to know the scale.

image

single pulse visualizations (commands) have this information
image

### PR DESCRIPTION
**Pull request by dennis-liu-1**
### Summary

Fixes #3485 

### Details and comments

Y ticks are now displayed (before the change, no ticks will be displayed with the empty array in the parameter). As a result of this I had to shift the channel labels over. 

Screen Shot 2019-11-20 at 2 10 05 PM

### CODE REVIEW

**Comment by ajavadia** [comment]
The y axis is shared among all channels here. It should be separate though. Each channel's vertical axis should display a scale such that one can see the amplitude of pulses on each channel.

**Comment by dennis-liu-1** [comment]
Ok, will fix

**Comment by taalexander** [comment]
Any update on this?

**Comment by dennis-liu-1** [comment]
To have 3 separate y axes I'm considering doing something like this (but only ticks for the length of each channel):

Screen Shot 2019-12-05 at 11 00 40 AM

unless there is a better way of implementing this

**Comment by nkanazawa1989** [comment]
I have two implementation ideas to show ytick labels.

1. use [matplotlib.pyplot.text](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.text.html) to add tick values instead of using default y ticks.
2. use `plot.yticks` for generating separated axis. see the [example](https://matplotlib.org/examples/ticks_and_spines/ticklabels_demo_rotation.html).

in both cases, you need to generate a table to map actual y-coordinate to separated axis labels which is also scaled by scaling option.

**Comment by taalexander** [comment]
What is the status of this @dennis-liu-1 and @nkanazawa1989?

**Comment by taalexander** [comment]
@dennis-liu-1, bump

**Comment by dennis-liu-1** [comment]
I'll try to get it done this week - had some implementation questions that I'll get the answers to

**Comment by dennis-liu-1** [comment]
Figured out how to get multiple and separated axes (can make it more compact later). There's a pretty specific blocker that I've been stuck on for more than a few days - how to get the y axis tick positions to align for just the drive (or measure or U) channel's subplot. I can get the correct drive channel's y axis coordinates, but they span across the entire plot instead of just on the drive channel. My idea was try to identify the subplot where the drive channel is drawn and set the y limits on that, but I'm having a hard time finding where that subplot is. I'm also not sure if this idea works so any suggestions would be very helpful.

Screen Shot 2020-03-03 at 11 48 36 AM

**Comment by taalexander** [comment]
@nkanazawa1989?

**Comment by nkanazawa1989** [comment]
@dennis-liu-1 thanks for tackling with the issue. first, I recommend you to update your branch to avoid conflict with master (currently the drawer is actively updated).

One of the solutions I can suggest is to use combination of [set_yticks](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.axes.Axes.set_yticks.html) and [set_yticklabels](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.axes.Axes.set_yticklabels.html) instead of using subplots. This enables you to set arbitrary y-coordinate to put the labels and also arbitrary label names.

here you can pass a dictionary `Dict[label_coordinate, actual_y_value]` which manages y labels
https://github.com/Qiskit/qiskit-terra/blob/e100a4c8bbcd71d16404fc2e000ef8227f1dec72/qiskit/visualization/pulse/matplotlib.py#L510-L511
I recommend you to add only +y side to the dictionary because by default -y side is not shown to remove redundant space. note that on +y side the maximum value is 1.0 times `scale`.
https://github.com/Qiskit/qiskit-terra/blob/e100a4c8bbcd71d16404fc2e000ef8227f1dec72/qiskit/visualization/pulse/matplotlib.py#L569-L570
+0.5 is inserted to keep the space for +y side of next channel and actual space for -y side of this channel is `amp_min`. this is often zero. if you add a label on -y side, this could overlap with the label on +y side of next channel.

finally you can add y axis from the dictionary. here you can set `set_yticks` with the key of the dictionary and `set_yticklabels` with the value of the dictionary.
https://github.com/Qiskit/qiskit-terra/blob/e100a4c8bbcd71d16404fc2e000ef8227f1dec72/qiskit/visualization/pulse/matplotlib.py#L669-L671

and I also recommend you to add `show_y_axis` option in the style sheet with `True` by default.
https://github.com/Qiskit/qiskit-terra/blob/e100a4c8bbcd71d16404fc2e000ef8227f1dec72/qiskit/visualization/pulse/qcstyle.py#L18-L26

because in IBMQ system pulse amplitude is normalized by _some factor_ so that it's value ranges from -1 to 1 and we don't provide the info to convert it into actual microwave power. thus, the value is physically meaningless. perhaps some people don't want to show such value in scientific article and offering the option to turn it off could be important.

**Comment by lcapelluto** [comment]
Hey crew, how is this going? @dennis-liu-1 @nkanazawa1989

**Comment by dennis-liu-1** [comment]
Sorry for the delay... I've been working on internal backend issues in the past few weeks, will have this on my to do list very soon

**Comment by lcapelluto** [comment]
@dennis-liu-1 thanks!

**Comment by taalexander** [comment]
Any update here?

**Comment by taalexander** [comment]
Closing and unassigning due to inactivity. Feel free to reopen if you want.

**Pull request closed without merging**
