### PR TITLE
Add plot_qv_logo() visualization function

### PR DESCRIPTION
**Pull request by nonhermitian**
### Summary
Makes the QV logo plot

qv16

### CODE REVIEW

**Comment by 1ucian0** [comment]
I might be missing something... what is this for?

**Comment by nonhermitian** [comment]
A visual aid when reporting quantum volumes of devices.  Will be used in jupyter tools.

**Comment by 1ucian0** [comment]
Oh, I see. So in the future `backend.quantum_volume()` will create the graph?

**Comment by nonhermitian** [comment]
Umm no. The jupyter stuff will have this as the icon that will show what the qv for a given device is, if one is returned. It will be backend.configuration().quantum_volume

**Comment by nonhermitian** [comment]
Closing this as it will be used elsewhere.

**Pull request closed without merging**
