### PR TITLE
Fix an isintanceof statement to allow all numpy integers

### PR DESCRIPTION
**Pull request by t-imamichi**
### Summary

Fix an `isinstance` of statement to allow all numpy integers.

Discussed in #5758

### CODE REVIEW

**Comment by mtreinish** [comment]
This LGTM, but I think we should also do this in the quantum_info module too as you pointed out in #5758. I'm pretty sure the use of `np.int` there before was a mistake and the intent was to be `np.integer` to also allow numpy integer types.

**Comment by t-imamichi** [comment]
I'm wondering it because `np.int` is not always used. For example, `PauliTable.__getitem__` used `np.int`, but `delete` did not as follows.
https://github.com/Qiskit/qiskit-terra/blob/0bb570f4a3ecbd8f830866f7ca1306fe2e028c9c/qiskit/quantum_info/operators/symplectic/pauli_table.py#L245
https://github.com/Qiskit/qiskit-terra/blob/0bb570f4a3ecbd8f830866f7ca1306fe2e028c9c/qiskit/quantum_info/operators/symplectic/pauli_table.py#L274
`StabilizerTables` did not use `np.int` either. 
https://github.com/Qiskit/qiskit-terra/blob/0bb570f4a3ecbd8f830866f7ca1306fe2e028c9c/qiskit/quantum_info/operators/symplectic/stabilizer_table.py#L256
Note that they are files of the stable branch.

It's good to use the same type of index (just `int` or `(int, np.integer)`) among all `symplectic` objects, at least within an object (pauli_table).
Which type of index should I use?

**Comment by chriseclectic** [comment]
The intent of most of these locations in qiskit was to allow python or numpy integer types since numpy integer values (eg there were occasional cases where a numpy int was used if it came from something like `index = array[i]`, so index would have type `np.int64` which would return false for `isinstance(x, int)`).

**Comment by t-imamichi** [comment]
@chriseclectic Thank you for your information. I replace `isinstance(int)` in `symplectic` with `isinstance(int, np.integer)`.

**Comment by t-imamichi** [comment]
I replaced all `isinstance(*, int)` with `isinstance(*, (int, np.integer))` in quantum_info.operators. Could you verify my changes?

**Review by mtreinish — APPROVED** [review]
LGTM, thanks for updating.

**Pull request merged**
