### PR TITLE
[WIP] CmdDef str and repr Fixes #2861

### LINKED ISSUE #2861: CmdDef should have a simpler representation
### What is the expected enhancement?
The current `CmdDef`'s, `repr` is based on its underlying dictionary. This quickly becomes complicated. Perhaps something like

`CmdDef(commands=['u1','u2','u3','measure','cx'], qubits=[0,1,2,3])`

is simpler to take in at a quick glance.

### PR DESCRIPTION
**Pull request by eggerdj**
* Added __str__ to CmdDef.

### Summary

Improved string and representation for CmdDef.

### Details and comments

The information return by repr for CmdDef was not readable enough.

### CODE REVIEW

**Comment by taalexander** [comment]
Could you please post example outputs for `repr` and `str`?

**Comment by eggerdj** [comment]
See here: https://github.com/Qiskit/qiskit-terra/issues/2861

**Comment by taalexander** [comment]
I think this looks good. I might recommend three changes:
1. For the string, representation is there much point in listing every qubit that is used? It typically will be all of the qubits?
2. Could we drop `ParameterizedSchedule` in the `repr`?
3. Could we include the parameters in `repr`?

So something like this:
```
CmdDef(commands=['cx', 'id', 'measure', 'u1', 'u2', 'u3', 'x'])
 
CmdDef(Command(name='u3', params=('P1', 'P2', 'P3'), qubits=[(0,), (1,), ...]),
...
)
```

**Comment by 1ucian0** [comment]
Is this still `[WIP]`?

**Comment by lcapelluto** [comment]
Going to close it, because it should be fixed by the PulseDefaults PR https://github.com/Qiskit/qiskit-terra/pull/3088/files#diff-857b3719e5ecea22a9e93456d0c94713R372

**Pull request closed without merging**
