### PR TITLE
Remove numpy max version cap

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

The version cap was put in place to prevent a potential incompatibility
but removing doesn't seem to cause any issues. Having it in place on
terra will cause an issue with ignis which requires numpy>=1.16.0 to
work as expected. While they're both co-installable because pip doesn't
have a depedency solver this only works if ignis is installed second.
(as installing terra second pip will use it's requirements with the
version cap, instead of ignis which has already been installed). To
avoid any potential confusion just removing the version cap is easiest.

### CODE REVIEW

**Comment by nonhermitian** [comment]
What makes the numpy requirement of ignis so high?  Also given this numpy requirement, we should bump the cython requirement to 0.29+ to be inline with the numpy recommendations

**Comment by nonhermitian** [comment]
I deleted my last comment as it is not needed

**Comment by mtreinish** [comment]
> What makes the numpy requirement of ignis so high? Also given this numpy requirement, we should bump the cython requirement to 0.29+ to be inline with the numpy recommendations

Well it's not that 1.16 is required per say it's more that using 1.15.x was failing. Running with 1.15.x (I started by mirroring the terra numpy cap in ignis) on ignis was causing issues with cvxpy which was raising an import error internally and disabling the solver the tests were relying on. It's really cvxpy, cvxopt, and scs which are causing the headaches on ignis. They required specific versions of things and everything has to be installed in a very specific order to work.

**Comment by 1ucian0** [comment]
Is this fixing https://github.com/Qiskit/qiskit-terra/issues/1679?

**Comment by mtreinish** [comment]
@1ucian0 it will on the next patch upload, I'm just disabling the linter checks as it looks more like pylint misbehaving than an issue with numpy. For example pylint errors on `logical_xor()` not having a return which is just wrong. (I think it's because the functions are actually generated and compiled in numpy and not statically defined python code)

**Pull request merged**
