### PR TITLE
Fix issue7865

### PR DESCRIPTION
**Pull request by saktar-unr**
### Summary

Fixing issue #7865. Removing IBMQ-specific functionality from job_monitor() method.

### Details and comments

The current job_monitor() method uses queue_position() method that is not available in JobV1 (https://qiskit.org/documentation/stubs/qiskit.providers.JobV1.html). I solved the issue by replacing computation of job queue position with showing only message like other job status.

### CODE REVIEW

**Comment by javabster** [comment]
Hi @saktar-unr thanks for working on this! I'm not sure we want to remove the entire QUEUED block, probably just the parts related to the `queue_position`. Otherwise what happens if the the job status is queued? Have you tested this manually? Might be worth also adding a test to the `test_job_monitor` file as well. Also please add a bugfix release note too please 😄

**Comment by javabster** [comment]
hi @saktar-unr are you still working on this?

**Comment by saktar-unr** [comment]
> hi @saktar-unr are you still working on this?

No. I am not working

**Comment by javabster** [comment]
ok thanks for letting us know, I'll close this PR but if you'd like to come back adn work on it at a later date just let us know and we can reopen it 😄

**Pull request closed without merging**
