### PR TITLE
Add a mailmap to qiskit-terra

### PR DESCRIPTION
**Pull request by levbishop**
This adds a mailmap for qiskit terra in order to merge multiple commit identities into a single author and to choose a canonical name/email for the authors suitable for the attribution scripts to use for generating the `AUTHORS` file, bibtex file, and zenodo authorship metadata. I did a small amount of work and figured out full names for a few authors who used opaque github ids. I didn't do too much detective work to unmask the last few in case they are trying to be anonymous on purpose.

This resolves the terra piece of Qiskit/qiskit#229

I preferred the noreply.github email if one was present and failing that preferred an IBM email over any other.

Without this PR  git-shortlog thinks there are 146 unique authors. After this PR merges duplicates, it shows 105 unique authors. This is 5 fewer than the "100 contributors" quoted on the github webpage because of:
1) 2 authors who have commits but seem to have no github account: Vojtech Havlicek, Christian Claus
2) 3 authors who have a github account but have committed using an email address not attached with that account: @jerrymchow @Trabing @mryu1 

@jesusprubio  Is this your preferred citation? 

Anyone may comment with their preferred name for citations and favourite email address, but in particular these github users without a full name associated to their profile should comment if they want to be credited by name: 
- [x] @carmenrv
- [x] @gadial 
- [ ] @LuhangYang 
- [x] @mtillet 
- [x] @nkanazawa1989  
- [x] @npdeep 
- [x] @rfclambert 
- [x] @sathayen

### CODE REVIEW

**Comment by mtreinish** [comment]
@levbishop awesome, thanks for getting the ball rolling on this. I'm good with merging this as is especially since you put clear instructions in the file on how to update the mailmap. But lets give it a day or 2 just to see if any of the contributors who's names you didn't find chime in.

**Comment by rfclambert** [comment]
Thank you for this work! My full name is Raphaël Lambert.

**Comment by carmenrv** [comment]
> This adds a mailmap for qiskit terra in order to merge multiple commit identities into a single author and to choose a canonical name/email for the authors suitable for the attribution scripts to use for generating the `AUTHORS` file, bibtex file, and zenodo authorship metadata. I did a small amount of work and figured out full names for a few authors who used opaque github ids. I didn't do too much detective work to unmask the last few in case they are trying to be anonymous on purpose.
> 
> This resolves the terra piece of [Qiskit/qiskit#229](https://github.com/Qiskit/qiskit/issues/229)
> 
> I preferred the noreply.github email if one was present and failing that preferred an IBM email over any other.
> 
> Without this PR git-shortlog thinks there are 146 unique authors. After this PR merges duplicates, it shows 105 unique authors. This is 5 fewer than the "100 contributors" quoted on the github webpage because of:
> 
> 1. 2 authors who have commits but seem to have no github account: Vojtech Havlicek, Christian Claus
> 2. 3 authors who have a github account but have committed using an email address not attached with that account: @jerrymchow @Trabing @mryu1
> 
> @jesusprubio Is this your preferred citation?
> 
> Anyone may comment with their preferred name for citations and favourite email address, but in particular these github users without a full name associated to their profile should comment if they want to be credited by name:
> 
> * [ ]  @carmenrv - Carmen Recio Valcarce car_rv@outlook.es
> * [ ]  @gadial
> * [ ]  @LuhangYang
> * [ ]  @mtillet
> * [ ]  @nkanazawa1989
> * [ ]  @npdeep
> * [ ]  @rfclambert
> * [ ]  @sathayen

Hello, I have updated the name in my profile. I include it in the provided list. Thank you!

> This adds a mailmap for qiskit terra in order to merge multiple commit identities into a single author and to choose a canonical name/email for the authors suitable for the attribution scripts to use for generating the `AUTHORS` file, bibtex file, and zenodo authorship metadata. I did a small amount of work and figured out full names for a few authors who used opaque github ids. I didn't do too much detective work to unmask the last few in case they are trying to be anonymous on purpose.
> 
> This resolves the terra piece of [Qiskit/qiskit#229](https://github.com/Qiskit/qiskit/issues/229)
> 
> I preferred the noreply.github email if one was present and failing that preferred an IBM email over any other.
> 
> Without this PR git-shortlog thinks there are 146 unique authors. After this PR merges duplicates, it shows 105 unique authors. This is 5 fewer than the "100 contributors" quoted on the github webpage because of:
> 
> 1. 2 authors who have commits but seem to have no github account: Vojtech Havlicek, Christian Claus
> 2. 3 authors who have a github account but have committed using an email address not attached with that account: @jerrymchow @Trabing @mryu1
> 
> @jesusprubio Is this your preferred citation?
> 
> Anyone may comment with their preferred name for citations and favourite email address, but in particular these github users without a full name associated to their profile should comment if they want to be credited by name:
> 
> * [ ]  @carmenrv
> * [ ]  @gadial
> * [ ]  @LuhangYang
> * [ ]  @mtillet
> * [ ]  @nkanazawa1989
> * [ ]  @npdeep
> * [ ]  @rfclambert
> * [ ]  @sathayen

Hello, I have updated my name in the profile but I also include it here. Thanks a lot!!
my preferred name for citations is: Carmen Recio Valcarce 
and favourite email address: car_rv@outlook.es

**Comment by mtillet** [comment]
Hello, my full name is Mathieu Tillet (associated with mtillet). Thank you !
----- Original message -----From: Carmen Recio Valcarce <notifications@github.com>To: Qiskit/qiskit-terra <qiskit-terra@noreply.github.com>Cc: mtillet <mathieu.tillet@ibm.com>, Mention <mention@noreply.github.com>Subject: [EXTERNAL] Re: [Qiskit/qiskit-terra] Add a mailmap to qiskit-terra (#2666)Date: Fri, Jun 21, 2019 12:17 PM 
This adds a mailmap for qiskit terra in order to merge multiple commit identities into a single author and to choose a canonical name/email for the authors suitable for the attribution scripts to use for generating the AUTHORS file, bibtex file, and zenodo authorship metadata. I did a small amount of work and figured out full names for a few authors who used opaque github ids. I didn't do too much detective work to unmask the last few in case they are trying to be anonymous on purpose.
This resolves the terra piece of Qiskit/qiskit#229
I preferred the noreply.github email if one was present and failing that preferred an IBM email over any other.
Without this PR git-shortlog thinks there are 146 unique authors. After this PR merges duplicates, it shows 105 unique authors. This is 5 fewer than the "100 contributors" quoted on the github webpage because of:
        2 authors who have commits but seem to have no github account: Vojtech Havlicek, Christian Claus        3 authors who have a github account but have committed using an email address not attached with that account: @jerrymchow @Trabing @mryu1
@jesusprubio Is this your preferred citation?
Anyone may comment with their preferred name for citations and favourite email address, but in particular these github users without a full name associated to their profile should comment if they want to be credited by name:
         @carmenrv - Carmen Recio Valcarce car_rv@outlook.es         @gadial         @LuhangYang         @mtillet         @nkanazawa1989         @npdeep         @rfclambert         @sathayen
Hello, I have updated the name in my profile. I include it in the provided list. Thank you!
This adds a mailmap for qiskit terra in order to merge multiple commit identities into a single author and to choose a canonical name/email for the authors suitable for the attribution scripts to use for generating the AUTHORS file, bibtex file, and zenodo authorship metadata. I did a small amount of work and figured out full names for a few authors who used opaque github ids. I didn't do too much detective work to unmask the last few in case they are trying to be anonymous on purpose.
This resolves the terra piece of Qiskit/qiskit#229
I preferred the noreply.github email if one was present and failing that preferred an IBM email over any other.
Without this PR git-shortlog thinks there are 146 unique authors. After this PR merges duplicates, it shows 105 unique authors. This is 5 fewer than the "100 contributors" quoted on the github webpage because of:
        2 authors who have commits but seem to have no github account: Vojtech Havlicek, Christian Claus        3 authors who have a github account but have committed using an email address not attached with that account: @jerrymchow @Trabing @mryu1
@jesusprubio Is this your preferred citation?
Anyone may comment with their preferred name for citations and favourite email address, but in particular these github users without a full name associated to their profile should comment if they want to be credited by name:
         @carmenrv         @gadial         @LuhangYang         @mtillet         @nkanazawa1989         @npdeep         @rfclambert         @sathayen
Hello, I have updated my name in the profile but I also include it here. Thanks a lot!!my preferred name for citations is: Carmen Recio Valcarceand favourite email address: car_rv@outlook.es

**Comment by npdeep** [comment]
Pradeep Niroula (niroulapradeep@gmail.com) for @npdeep

**Comment by sathayen** [comment]
@levbishop  @ajavadia  -- Ninad Sathaye for @sathayen . thanks

**Comment by levbishop** [comment]
@mtreinish I made a couple fixes to make the Co-Authored-By lines work. I agree to merge it now and let anyone remaining open their own PR now

**Pull request merged**
