### PR TITLE
Respect backend defaults for BackendV1 path in execute()

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

A BackendV1 backend object has default values for all it's options set
already in the Options object stored in the options attribute of the
object. However when running execute targettting a backend for backwards
compatibility we were overriding the default to what the execute
function used to default to. The most basic example of this was
something like shots. If the backend accepts a shots option execute()
would override whatever the default for the backend was to 1024 to be
consistent with what execute() did before BackendV1 was introduced. This
commit changes this behavior so that execute() will respect the default
set in the backend's options instead of it's own defaults.

### CODE REVIEW

**Review by jakelishman — APPROVED** [review]
Looks good to me.  Is there a reason that the `memory` kwarg (in the parameter list) defaults to `False` rather than `None`?  It'll bypass this method of resetting it to the backend's default.

**Comment by jakelishman** [comment]
@mtreinish: This wasn't marked automerge at the time because I had that one question about the `memory` kwarg.  As it stands, in the parameters of `execute` we have
https://github.com/Qiskit/qiskit-terra/blob/addbdd15fdca416f1e64b4474ac539687933bfde/qiskit/execute_function.py#L51-L54
so `memory=False`, but everything else in `None`.  This means that it dodges the removal from the `run_kwargs` dict if unset, and so a backed which defaults to `memory=True` will have that overridden by the defaults of `execute`.  Is that intended, or should it be changed?

**Comment by mtreinish** [comment]
That's a good question, I'm not sure why `memory` defaults to `False`. I agree we should fix that too. I expect it was just an oversight in #5341. I'll push a fix right now to bring it inline with the others.

**Review by jakelishman — APPROVED** [review]
Looks good to me!

**Pull request merged**
