### PR TITLE
Fixed issue 3099 by removing try and except blocks in dag_visualtion

### LINKED ISSUE #3099: dag_drawer should check the existence of filename extension
### Information

- **Qiskit Terra version**: 0.10.0.dev0+831d942
- **Python version**: 3.7
- **Operating system**: Mac

### What is the current behavior?

If a filename without extension is passed to the function `dag_drawer`, this [line](https://github.com/Qiskit/qiskit-terra/blob/d090eca91dc1afdb68f563885c4ccf13b31de20e/qiskit/visualization/dag_visualization.py#L91) reports two errors:
```
nxpd.pydot.InvocationException: Program terminated with status: 1. stderr follows: Format: "XXXXX" not recognized. Use one of: ......
During handling of the above exception, another exception occurred:
qiskit.visualization.exceptions.VisualizationError: 'dag_drawer requires GraphViz installed in the system. Check https://www.graphviz.org/download/ for details on how to install GraphViz in your system.'
```

This is confusing because the second error thrown by Qiskit is not the cause of the problem.

### Steps to reproduce the problem

Try `dag_drawer(dag, filename='abc')`

### What is the expected behavior? 

Make the error catching better.

### Suggested solutions

We could either catch this error by reading and filtering the error message, or we could check the existence of the filename's extension, and provide a default one.

### PR DESCRIPTION
**Pull request by spencerchurchill**
### Summary

Fixes #3099

### Details and comments

I removed the try and except block surrounding the import nxpd and pydot (50, 53-55) because the ModuleNotFoundError gives sufficient information to install the packages. I also removed the try and except block surrounding the return nxpd.draw() function (90, 92-95) because in the case of issue #3099, the Qiskit VisualizationError was being thrown for an nxpd InvocationException. Import and extension errors will now be correctly shown as suggested by @kdk and @we-taper:

**Raised import error**:
```
ModuleNotFoundError: No module named 'nxpd'
ModuleNotFoundError: No module named 'pydot'
```

image

**Raised extension error**:
`InvocationException: Program terminated with status: 1. stderr follows: Format: "/var/folders/kh/wvhq4p916pgdhhcxjr2btq_00000gn/T/tmpp34a77_0" not recognized. Use one of: bmp canon cgimage cmap cmapx cmapx_np dot dot_json eps exr fig gif gv icns ico imap imap_np ismap jp2 jpe jpeg jpg json json0 mp pct pdf pic pict plain plain-ext png pov ps ps2 psd sgi svg svgz tga tif tiff tk vml vmlz xdot xdot1.2 xdot1.4 xdot_json`

image

I also fixed a small stylistic error where an open angle bracket was left unclosed (31).

### CODE REVIEW

**Comment by 1ucian0** [comment]
I would prefer the approach to #3099 suggested by @kdk in https://github.com/Qiskit/qiskit-terra/issues/3099#issuecomment-531759960

Did you try it?

**Comment by 1ucian0** [comment]
I think is better to capture the errors to raise Qiskit exceptions as the corner case is considered. However, the errors should be different to avoid confusing the user.

**Comment by 1ucian0** [comment]
@spencerchurchill  still working on this?

**Comment by spencerchurchill** [comment]
> @spencerchurchill still working on this?

Hi! Sorry school was a little busy recently but I'm definitely going to try to fix this up :)

**Comment by 1ucian0** [comment]
It seems that @spencerchurchill is still busy. Please, reopen it whenever you get time!

**Pull request closed without merging**
