### PR TITLE
Tweak colors to match new IQX colors

### PR DESCRIPTION
**Pull request by nonhermitian**
### Summary
Match the upcoming changes to IQX circuit composer styling.

### CODE REVIEW

**Comment by nonhermitian** [comment]
Once again, I cannot pass the unit tests using my own reference images.

**Comment by ajavadia** [comment]
Yes these visualization tests seem painful. But in #2968 @drholmie is proposing a solution which might alleviate the pain so I think we should give that a try.

**Comment by 1ucian0** [comment]
The conflicts should be easy to resolve, do you mind having a look?

**Comment by ajavadia** [comment]
@nonhermitian what's the status on this?

**Comment by nonhermitian** [comment]
I have not looked at this in four months when it was working just fine.  Now there are two files and three images with conflicts.  So need to resolve those when time permits.

**Comment by ajavadia** [comment]
if the image tests fail are failing i think they should just be disabled until someone can make them work properly. there's no point having them right now.

**Comment by ajavadia** [comment]
also while you rebase this can you fix a color regression that was introduced in #3709? it draws cu1 as black. it should be purple

image

your current branch has the colors right (below) but doesn't draw cu1 as symmetric, which was the bug fixed by PR above
image

**Comment by 1ucian0** [comment]
This PR seems stalled for some months already. I'm turning this PR as issue https://github.com/Qiskit/qiskit-terra/issues/5032 to keep track of it and look for other contributor that can help with it.

**Pull request closed without merging**
