### PR TITLE
Bugfix in clifford instruction name

### PR DESCRIPTION
**Pull request by gadial**
### Summary
This PR fixes a small bug in clifford instruction naming, caused by `def decompose_clifford_` simplifying the giving clifford, changing its name in the process, before using the name for the resulting instruction. This results in correct behavior but wrong naming.

### CODE REVIEW

**Review by ShellyGarion — APPROVED** [review]
LGTM, thanks Gadi for fixing this!

**Review by itoko — CHANGES_REQUESTED** [review]
@gadial Thank you for the quick fix!
Could you add a small test to check if `Clifford.to_instruction()` return the correct name? For example,
```
clifford = random_clifford(2, seed=777)
assertEqual(clifford.to_instruction().name, str(clifford))
```
I don't think it's too much, it would help us not revisit the same bug in the future.

I personally like the following code change to prevent someone accidentally revert this fix:
Copy the original clifford name at the first line of `decompose_clifford_bm`, 
```
    ret_circ_name = str(clifford)  # keep the original clifford name
```
and create circuit to be returned with the name.
```
    # Decompose the remaining product of 1-qubit cliffords
    ret_circ = QuantumCircuit(num_qubits, name= ret_circ_name)
```

**Comment by gadial** [comment]
> @gadial Thank you for the quick fix!
> Could you add a small test to check if `Clifford.to_instruction()` return the correct name? For example,
> 
> ```
> clifford = random_clifford(2, seed=777)
> assertEqual(clifford.to_instruction().name, str(clifford))
> ```
> 
> I don't think it's too much, it would help us not revisit the same bug in the future.
> 
> I personally like the following code change to prevent someone accidentally revert this fix:
> Copy the original clifford name at the first line of `decompose_clifford_bm`,
> 
> ```
>     ret_circ_name = str(clifford)  # keep the original clifford name
> ```
> 
> and create circuit to be returned with the name.
> 
> ```
>     # Decompose the remaining product of 1-qubit cliffords
>     ret_circ = QuantumCircuit(num_qubits, name= ret_circ_name)
> ```

Thank you for your helpful comments! Fixed accordingly.

**Review by ShellyGarion — APPROVED** [review]

**Review by ShellyGarion — APPROVED** [review]

**Review by itoko — APPROVED** [review]
Thanks!

**Pull request merged**
