### PR TITLE
Fix `DiagonalGate` QPY serialisation

### LINKED ISSUE #10364: qpy roundtrip for FourierChecking fails with TypeError: DiagonalGate.__init__() takes 2 positional arguments but 5 were given
### Environment

- **Qiskit Terra version**: 0.24.1
- **Python version**: 3.10
- **Operating system**: NixOS 23.11

### What is happening?

This is likely because the named gate (`DiagonalGate`) is not explicitly supported in the gates in the following code branch: https://github.com/Qiskit/qiskit-terra/blob/e9f8b7c50968501e019d0cb426676ac606eb5a10/qiskit/qpy/binary_io/circuits.py#L282-L289

### How can we reproduce the issue?

```python
import io
from qiskit import qpy
import qiskit.circuit.library as qcl

def encode(qc):
    with io.BytesIO() as f:
        qpy.dump(qc, f)
        # Rewind back to the beginning of the "file".
        f.seek(0)
        serialized = f.read()
    return serialized

def decode(data):
    with io.BytesIO(data) as f:
        circuits = qpy.load(f)
    return circuits[0]

# Works
decode(encode(qcl.QFT(3)))
# Doesn't work
decode(encode(qcl.FourierChecking([1, -1, -1, -1], [1, 1, -1, -1])))
```

### What should happen?

The error message should have said that the `DiagonalGate` is not supported when it is not covered by the if-else checks in the `_read_instruction`.

### Any suggestions?

_No response_

### PR DESCRIPTION
**Pull request by Raghav-Bell**
Added "diagonal" in line 282

### Summary
Diagonal gate is causing error as discussed in issue #10364 . This PR closes the issue #10364 

### Details and comments

As suggested by @jakelishman , i have added `"diagonal"` at line 282.

Fix #10364.

### CODE REVIEW

**Comment by jakelishman** [comment]
Thanks for looking at this! Please can you add a test case and a "bug fix" release note (see the contributing guide in the repo root for information on that).

**Comment by Raghav-Bell** [comment]
@jakelishman I have added release notes using `reno` but i am new to `tox` can you please help me in adding test cases.

**Comment by rht** [comment]
@Raghav-Bell you can do so by adding `FourierChecking` to https://github.com/Qiskit/qiskit-terra/blob/8a8609f93a600019bf208610a348adcbe61e3acd/test/qpy_compat/test_qpy.py#L577 (or a simpler circuit that has `DiagonalGate`). You should go through the functions `generate_*_circuit`. Read https://github.com/Qiskit/qiskit-terra/blob/main/CONTRIBUTING.md#test for running the tests locally.

**Comment by jakelishman** [comment]
Thanks @rht!  The `test/qpy_compat` place is the backwards-compatibility tests for QPY; those are actually a little tricky to run locally, but it would be good to add a case to them (protected on Terra version `>= (0, 25, 0)`, since that's when we'll release the fix).  You can also add a regular unit test to `test/python/qpy/test_circuit_load_from_qpy.py`, which are all just regular `unittest` tests.

**Comment by jakelishman** [comment]
(btw, the lint is failing with a style error - if you `pip install tox`, you can `tox -e black` to fix it up automatically.)

**Comment by Raghav-Bell** [comment]
I have tested for diagonal gate test using `tox -ep310 -- generate* `and `tox -ep310 -- diag*` both ends succesfully. Complete tests take alot time ,hence i hv dropped .

**Review by jakelishman — DISMISSED** [review]
Thanks for this! I fixed up the release note a little and moved the test into the regular unit tests (there's a complication with `DiagonalGate` itself that will make it hard to use our QPY backwards-compatibility tests for now).

**Review by mtreinish — APPROVED** [review]
LGTM, this seems straightforward enough

**Review by jakelishman — APPROVED** [review]

**Pull request merged**
