### PR TITLE
Add support for barriers to latex_drawer()

### LINKED ISSUE #731: Draw barrier in `latex_drawer`
### What is the current behavior?
Right now the barriers are not drawn with latex. We want them to be drawn for `barrier`, `noise`, `save`, `load`, and `snapshot` instructions at that depth.

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary
This commit adds support for drawing barriers to the latex_drawer(). The
Qcircuit LaTeX package doesn't have support for drawing barriers yet
(it's pending with CQuIC/qcircuit#33 ) so for now this commit inlines
the command definition. In the future when the Qcircuit package is
released to include the command we can remove that.

### Details and comments

Fixes #731

### CODE REVIEW

**Comment by mtreinish** [comment]
This is still WIP because the fixed offset for drawing barriers will overlap with the box for measurement if it's immediately after a gate. (because the measurement image is wider than a gate)

**Comment by ajavadia** [comment]
@mtreinish It seems like your change has been released as part of Qcircuit, based on the conversation here: https://github.com/CQuIC/qcircuit/pull/34.

So is this PR ready to be taken out of WIP and merged?

**Comment by mtreinish** [comment]
@ajavadia I've updated the patch to try and address those issues. The spacing for the barriers is still a bit weird because it's still not truly dynamic. So there are likely cases where the barrier won't be properly drawn in the middle of elements because it's naively assuming fixed spacing. That being said it seems to work for my simple test:

```
qp = QuantumProgram()

qr = qp.create_quantum_register('q1', 3)
qr_a = qp.create_quantum_register('q2', 2)
c = qp.create_classical_register('c1', 3)
c_a = qp.create_classical_register('c2', 2)
qc = qp.create_circuit('qc', [qr, qr_a], [c, c_a])

qc.h(qr[0])
qc.barrier(qr)
qc.y(qr[0])
qc.x(qr_a[0])
qc.h(qr[1])
qc.h(qr[2])
qc.x(qr_a[1])
qc.barrier(qr[0])
qc.measure(qr, c)
qc.measure(qr_a, c_a)
from qiskit.tools import visualization
visualization.latex_circuit_drawer(qc, filename='barrier.png')
```
normal

**Comment by ajavadia** [comment]
@mtreinish can you please add the following commands to be drawn like barriers also?
`snapshot`, `load`, `save`, `noise`

These are simulator-specific instructions, and behave like barriers. So the circuit drawer should draw them like barriers. They are available when you do `import qiskit.extensions.simulator`.

**Comment by mtreinish** [comment]
@ajavadia sure I can look into that. But I think it'll be better to do add support for the other commands in a follow up PR. Since it'll take me a bit of time to figure out how to best draw the annotation next to the barrier line.

**Comment by ajavadia** [comment]
@mtreinish Sure, that can be done later. The current barrier plotting looks great. Merging.

**Pull request merged**
