### PR TITLE
Add dev version to version string

### LINKED ISSUE #1796: Allow versioning to include git information if not using released version
### What is the expected enhancement?

Currently there is no way to distinguish between the master branch dev version and a final release version.  Currently, for example, they would both be labeled as `0.8.0`.

It would be nice to have unreleased (dev) versions tagged with the git repo commit that they are pulled from.  This is done, for example in SciPy and NumPy, and it quite easy to implement.

### LINKED ISSUE #2615: Import of qiskit causes console window to be opened many times
### Information

- **Qiskit Terra version**: 0.8.1
- **Python version**: 3.6.8
- **Operating system**: Windows 10

### What is the current behavior?

If I import qiskit a console window is opened and closed many times. It is due to the execution of 
``` 
cmd=['c:\\projects\\venv\\scripts\\pythonw.exe', '-m', 'pip', 'freeze']
reqs = subprocess.check_output(cmd)
```
in `qiskit\version.py` (line 29, in `_get_qiskit_versions`)

### Steps to reproduce the problem

Import qiskit with the following command:
```
import qiskit
```

### What is the expected behavior?

Qiskit should be important without side effects.

### Suggested solutions

The issue seems to be the same as described in https://stackoverflow.com/questions/6390394/executing-subprocess-from-python-without-opening-windows-command-prompt, however the sollutions suggested there do not work.

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

This commit adding dev versions to the qiskit.__version__ string. If a
.git dir is found and we determine that the current head does not point
at a tag then we will append a dev version to the version string to
indicate that. If however we can't find a .git dir (likely meaning it's
a pip install) or the curret git HEAD is a tag, then we use the version
string from VERSION.txt.

### Details and comments

Fixes #1796
Fixes #2615

### CODE REVIEW

**Comment by nonhermitian** [comment]
Downloaded your branch, but it does not seem to work for me:

```python

In [8]: get_version_info()
Out[8]: '0.9.0'
```

**Comment by nonhermitian** [comment]
Actually, I guess the git info is '' when you download.

**Comment by mtreinish** [comment]
Yeah it will default to `0.9.0` (or whatever version is in the version.txt) if it can't find a .git dir. If you run 
`git checkout -b mtreinish-dev-version-str master && git pull https://github.com/mtreinish/qiskit-core.git dev-version-str` in a terra repo checkout it should work fine. (or at least it does for me locally):

```
Python 3.7.3 (default, Mar 26 2019, 21:43:19) 
[GCC 8.2.1 20181127] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import qiskit
dot - graphviz version 2.40.1 (0)
b''
q>>> qiskit.__version__
'0.9.0.dev0+64e5ca7'
>>> 

``` (ignore the dot output, that's fixed by #2495 )

**Comment by nonhermitian** [comment]
Yeah, I got it to work.  Does this work on Windows?

**Comment by mtreinish** [comment]
Umm, it should assuming git is in the windows PATH and there is a .git. In the worst case it will just fail to run git and set the version string to `0.9.0.dev0+Unknown`

**Comment by nonhermitian** [comment]
Ok this is failing because the basic aer sims use the terra version as their own. So need to mod that as well.

**Comment by mtreinish** [comment]
Ok, I spun up a windows vm to test this there. I got it working eventually (it did take more effort than I expected). In the process I did a find a few issues though, first we don't suppress stderr from the git commands, second we didn't catch an exception from the is this commit also a tag check, third we didn't handle running outside of the repo correctly. I've got fixes for those which I'll push up shortly.

**Pull request merged**
