### PR TITLE
implement coeffs method for SummedOp (Issue #5931), matching coeffs m…

### PR DESCRIPTION
**Pull request by john-judge**
…ethod of PauliSumOp

### Summary
Enhancement requested in Issue #5931, implementing a property `coeffs` in `SummedOp` that returns the simplified list of all the coefficients that precede the operators in the sum list. This matches the  property `coeffs` in 'PauliSumOp'.

### Details and comments
Unit test explicitly covers both the `Complex` coefficient case and the `ParameterExpression` coefficient case.

### CODE REVIEW

**Comment by john-judge** [comment]
Looks like I need to fix whitespace formatting to pass some of the tests. Should this PR be abandoned and I'll try submitting a new one?

**Comment by ikkoham** [comment]
I think ListOp (superclass) shoud have it. And, what should be returned for nested SummedOp? (i.e. SummedOp[SummedOp])
SummedOp[PauliSumOp] also appear in opflow.

**Comment by woodsp-ibm** [comment]
Having such a property/method in the base ListOp class seems like the right place.

And as noted since a ListOp can contain other ListOps etc., ie. be nested then what to do. As far as I can see we have some options:

1. Provide back the main coeff to the nested ListOp but not its individual ones. (This appears to be what has done)
2. If there are any nested ListOps raise an exception to that effect, otherwise return the list of coeffs
3. Return a list that may have coeffs or other lists (i.e take care of nesting)

@jlapeyre You note a use case in the original issue. Did you have any thoughts around the above when you wrote the issue as to what you might expect given that ListOps can contain other ListOps. Somehow 3 above seems like it would be complicated to handle such a return in general - a user could always compute that themselves if we choose to stay with 1 or 2 as above. Somehow I am thinking 2 above would allow users to use it he simplest - it will fail on more complex ListOps, by intent and won't 'hide' the fact that there are nested ListOps as in 1 above.

**Comment by john-judge** [comment]
There are some additional details of jlapeyre's use case in #5547:

> It would be useful to be able to iterate over, or return a list of coefficients

Given that "multiple dimensional lists" and nesting are a major use cases of `ListOps` according to the docs, and that the purpose of `coeffs` is to let the user extract data for their own analysis (such a user is less likely to be confused by jagged lists), I think I prefer @woodsp-ibm 's option 3.

Here's a quick sketch of what option 3 might look like:

```
	@property
	def coeffs(self)-> List[Union[complex, ParameterExpression]]:
		"""Return the coefficients. Returns nested list for nested ListOps. """
		cs = []
		for op in self.oplist:
			if isinstance(op, ListOp):
				cs.append([self.coeff * op2.coeff for op2 in op.coeffs])
			else:
				cs.append(self.coeff * op.coeff)
		return cs
```

**Comment by jlapeyre** [comment]
I am in favor of 1 or 2. Number 3 is my least favorite: We don't need to support all the possible complexity.

In number 2, is the proposal to allow everything but a `ListOp` instance (not a subclass)?

I think 1 might be best. Opflow allows you to create just about anything. In the case of 2, we would need to decide what to allow. For example, the `ListOp` might contain a `ComposedOp` that has a proper `ListOp` at a lower level. I suppose we could look only one level down and exclude only explicit `ListOp`s on that level. But, it seems simpler to extract a list of top-level coefficients.

**Comment by woodsp-ibm** [comment]
@jlapeyre The difference between 1 and 2 - at least what I was meaning when I wrote it was how to handle the ListOp that may itself contain one or more ListOps i.e. be nested - of this can be recursive.

1 was just to go through the ListOp and at that level, if it had a ListOp just take its main coeff and return that in the list - of course this 'hides' any nesting that might be present which might be not be apparent and undesirable.

2 was to say instead of that simply raise an exception that coeffs is not supported when the ListOp contains other ListOps (or words to that effect). In this latter case a user can of course compute things however they like in getting coeffs out of the ListOp but we would not do it via the coeffs function here. 

Does that seem clearer?

**Comment by john-judge** [comment]
@woodsp-ibm / @jlapeyre Thanks for the discussion -- that makes sense. Raising an exception seems like the most informative option from the user's perspective. How does this look?

```
	@property
	def coeffs(self)-> List[Union[complex, ParameterExpression]]:
		"""Return the coefficients. Raises exception for nested Listops. """
		if any(isinstance(op, ListOp) for op in self.oplist):
			raise ValueError("Coefficients are not returned for nested ListOps.")
		return [self.coeff * op.coeff for op in self.oplist]
```

**Comment by jlapeyre** [comment]
> was just to go through the ListOp and at that
I was wondering whether we are talking about an instance of the super class `ListOp`, or whether subclasses such as `ComposedOp` are included.  Sounds like the latter.


I'm ok with the code above that raises an exception, although I favor the simpler option of extracting top-level coefficients.
I think what to do really depends on what the use case is. I can imagine a `SummedOp` whose elements are all `ComposedOp`s and all I care about is the coefficient of the a `ComposedOp`, not of its factors. But, I don't have a concrete example of such a use. If someone needs to broaden the allowed arguments, we could always add the behavior by removing the check and exception. It's harder to take it away.

**Review by jlapeyre — DISMISSED** [review]

**Comment by woodsp-ibm** [comment]
And its not like you can't compute this easily if whatever is done by the `coeffs` here does not meet your needs of course.

The code as it stands in the PR has no exception and is just getting all the top level coeffs regardless. @jlapeyre is that what you prefer since you approved this? I think at least we should state that this is the case for any nested ListOps that might be there however that is phrased in the docstring.

**Comment by john-judge** [comment]
@jlapeyre @woodsp-ibm I don't recommend approving yet -- I haven't pushed any commits since our recent discussion started.

I plan to write an additional test for the exception raising case and have a commit by Sunday at the latest.

**Comment by john-judge** [comment]
@woodsp-ibm Ok, this is ready for review. Thanks for your help.

**Comment by woodsp-ibm** [comment]
It looks good to me. Since this is a feature addition can you add a reno release note (See this for more info about release notes and reno if you are unfamiliar https://github.com/Qiskit/qiskit-terra/blob/main/CONTRIBUTING.md#release-notes)

@jlapeyre Any thoughts on the current implementation - meets with your approval?

**Comment by jlapeyre** [comment]
Yes, the implementation and documentation look good to me.

**Review by jlapeyre — APPROVED** [review]

**Review by woodsp-ibm — APPROVED** [review]

**Pull request merged**
