### PR TITLE
Fix label inconsistency issue when gate inverse is called.

### PR DESCRIPTION
**Pull request by Jwala-1908**
### Summary
The label input when creating the gate is not carried forward into its inverse.

### Details and comments
PR #5600 
Upon running the following code,
`from qiskit import QuantumCircuit`
`qc = QuantumCircuit(2)`
`qc.cx(0,1)`
`qc_gate = qc.to_gate(label='qc_gate')`  
`qc_gate_inv = qc_gate.inverse()`

`print(qc_gate.label)`
`print(qc_gate_inv.label)`

The output was:
`qc_gate`
`None`

The output after the proposed changes is:
`qc_gate`
`qc_gate_dg`

Some more related irregularities were pointed out in #5600 by @itoko. Among those, 
the repeated appending of '_dg' suffix has also been solved in the proposed changes.
E.g.  
Before: `qc_gate.inverse().inverse().name` would print `circuit_dg_dg `.  
After this change: `qc_gate.inverse().inverse().name` prints `circuit`.

### CODE REVIEW

**Review by 1ucian0 — CHANGES_REQUESTED** [review]
Looks good! Do you mind adding a reno and tests? Probably `test/python/circuit/test_instructions.py` is a good place for these tests.

**Comment by Jwala-1908** [comment]
Added the test `test_inverse_with_label` to `test/python/circuit/test_instructions.py` and reno.

**Review by javabster — APPROVED** [review]
LGTM 🚀

**Comment by 1ucian0** [comment]
After digging the previous PR https://github.com/Qiskit/qiskit-terra/pull/5600#issuecomment-859653423 I'm not sure if this is an issue to solve.

However, there is a related issue, similar to the one mentioned by @itoko :
```
from qiskit import QuantumCircuit
qc = QuantumCircuit(2, name="qc_gate")
qc.cx(0,1)
qc_gate = qc.to_gate()
qc_gate_inv = qc_gate.inverse()
qc_gate_inv_inv = qc_gate_inv.inverse()

circuit = QuantumCircuit(2)
circuit.append(qc_gate, [0,1])
circuit.append(qc_gate_inv, [0,1])
circuit.append(qc_gate_inv_inv, [0,1])
circuit.draw('mpl')
```
image

**Comment by Jwala-1908** [comment]
I've addressed the duplication of '_dg' in the name attribute in c434638.

**Comment by 1ucian0** [comment]
Closing in favor of #6563

**Pull request closed without merging**
