### PR TITLE
Very small clean up in the count_ops() method

### PR DESCRIPTION
**Pull request by rajkk1**
### Summary

Very small clean up in the count_ops() method in the QuantumCircuit class. No change in functionality.

### Details and comments

The clean up made the code slightly shorter and (in my opinion) slightly more readable. I am working on a different PR and thought of this small optimization so I thought I would create a separate PR for this before submitting my bigger PR. Thanks!

### CODE REVIEW

**Comment by rajkk1** [comment]
Thank you! I've fixed all the errors except for a single"invalid-file-header" error. I am running this on Windows 10 so I wonder if there is some weirdness going on there. I checked this thread https://github.com/Qiskit/qiskit-terra/issues/3127 but I couldn't really resolve the problem. Have you come across this before?

**Comment by rajkk1** [comment]
Hi @mtreinish, hope you had a good weekend! Just wondering if you had a chance to look at my [comment above](https://github.com/Qiskit/qiskit-terra/pull/4002#issuecomment-601841069). Thank you!

**Comment by mtreinish** [comment]
@rajkk1 looking at the current version of this branch I do not think you're hitting an environment difference with pylint. The failures with the lint job here are from pycodestyle which does not have the same issues as pylint from that issue. You've removed all the blank lines from the class you were editing and added a blank line to the end. I would recommend reverting those changes on the branch `git revert 53e86a1cde905704d00037087dfd8b0c28f82bca` and `git revert cc3b4325ed23637be9b8d879b290a96c0fb16acc` (which are causing the doc job failure) and then look at the failure reported by CI for lint and manually fix those. It's just a mix of tabs and spaces for indents and whitespace in blank lines.

**Comment by rajkk1** [comment]
thank you @mtreinish! I tried reverting and it still wasn't happy. This is getting a bit confusing so I might just re-do the whole pull request to make it easier

**Pull request closed without merging**
